### ISSUE TITLE
Error: COM object that has been separated from its underlying RCW cannot be used.

### ISSUE THREAD

**Issue by JeroenTuinstra** [phw198/OutlookGoogleCalendarSync#1001]
Recently the log shows the following error:

Sync version: 2.8.3.0

Sync started at 03/06/2020 17:52:10

Syncing from 02/06/2020 to 03/08/2020

Outlook → Google

Finding Calendar Entries
Scanning Outlook calendar...

35 Outlook calendar entries found.

Scanning Google calendar...

29 Google calendar entries found.

Total inc. recurring items spanning sync date range...
Outlook 29, Google 29
Checking for orphaned items
Matching calendar items...

0 Google calendar entries to be deleted.

1 Google calendar entries to be created.

28 calendar entries to be compared.

Creating 1 Google calendar entries
10/06/2020 13:30 "Kantooroverleg - Rencontre de bureau"

Comparing 28 existing Google calendar entries
0 entries updated.

Sync finished!

**COM object that has been separated from its underlying RCW cannot be used.**

Everything seems to be working, just that remark.

**Comment by phw198** [comment]
Could you let me know which link you followed to create this issue? Looks like it hasn't used the template for some reason.

:spiral_notepad: To investigate this further please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) for the time when you got that error.
