### ISSUE TITLE
Error using mapping on 2.8.2.13

### ISSUE THREAD

**Issue by sjsdoc60** [phw198/OutlookGoogleCalendarSync#1005]
Paul, I did get the alpha installed.  I checked the Colour and clicked on mapping.  the attached error occurred.  

I did run the exe from the alpha subdirectory, not the main directory for OGCS.  Not sure if  that matters.  I had renamed the exe in main directory to a .bak extension prior to installing in the alpha subdirectory and did not see a new exe in the parent dir.

Thanks
[2020-06-09_11-23-09.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/4753736/2020-06-09_11-23-09.pdf)

**Comment by sjsdoc60** [comment]
Forgot to add the details from the error message
[debugf.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4753779/debugf.txt)

**Comment by phw198** [comment]
Thanks - yes, I think there's a few bugs that need ironing out for fresh installs. I'll get that fixed up and a new build out ASAP...

**Comment by sjsdoc60** [comment]
Attached is the error screen.  I did put the .exe in the alpha subdir.  It did show 2.8.3.14 when I opened the .exe.  I went to What/checked Colours/opened Mappings/clicked on an Outlook category I have and then got this error.  Could not exit the error screen. Had to Ctrl-Alt-Del.
[2020-06-14_12-58-50.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/4777039/2020-06-14_12-58-50.pdf)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4777042/OGcalsync.log)

**Comment by phw198** [comment]
Hi @sjsdoc60 Thanks for the update. However, v2.8.3.15 was released yesterday (posted on the orginal #580 issue) - please use this for further testing. I'll close this issue now so any issue encountered under 2.8.3.15 can have a new issue.

> I had renamed the exe in main directory to a .bak extension prior to installing in the alpha subdirectory and did not see a new exe in the parent dir.

As per the hotfix patching guidance, only changes should be applied to the alpha subdirectory - if you have changed the executable in the parent directory you will have broken the upgrade mechanism, so best to rename the extension back to `.exe`.

Please keep testing - hoping to get it into the next alpha release in the next week or so :slightly_smiling_face:

**Comment by sjsdoc60** [comment]
Ok.

But i am confused.  This is different way to update than i have done.  The
main directory seems unchanged with all these hot fixes.  I had assumed the
main directory .exe would update.  But it doesn’t as long as i am replacing
the alpha directory exe.  I have been running each iteration only from the
alpha directory exe as I dont see any changes to the main directory.  This
is confusing to me.  Is this the correct way to do this? Changing the main
directory exe to bak doesn’t seem to do anything as it appears the main
directory isn’t being used best i can tell.

**Comment by sjsdoc60** [comment]
where do I find the 2.8.3.15?  Am on github site but cant find it.

Mark
