### ISSUE TITLE
Hard to fix with no error

### ISSUE THREAD

**Issue by pltapley** [phw198/OutlookGoogleCalendarSync#1006]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
It's really simple, I just hit sync and it says it finished successfully and then I look in the calendar and there is no changes. 

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4754792/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Even harder to diagnose with no description of what change you expect to see.

Also you've not bothered to upgrade to the latest alpha release.
