### ISSUE TITLE
How To Make Load With Outlook

### ISSUE THREAD

**Issue by chadjans1** [phw198/OutlookGoogleCalendarSync#1007]
Version 2.8.0.0

Is there a way to have OGCS load when outlook is started? I know there is an option to load OGCS with "Start on login..." but I do not want to have outlook load on windows startup. 

I tried to add OGCS as a COM addin in Outlook but upon selecting the exe is is never added to the COM list in outlook.

Thank you for the help.

Chad

**Comment by phw198** [comment]
If OGCS starts on login, it should not fully open Outlook but just open it in "programmatic access" mode which is only visible by a little Outlook icon with a cog in the tasktray.

However, if you still wish to start OGCS when Outlook is opened, that is [possible with VBA code](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#start-ogcs-after-outlook).
