### ISSUE TITLE
Specified cast is not valid in 2.8.3.14

### ISSUE THREAD

**Issue by jbtapscott** [phw198/OutlookGoogleCalendarSync#1008]
Installed Hotfix 2.8.3.14 in line with instructions and had app working okay.   Had a few errors thrown up which I initially put down to my errors, but also got the app fully working and, on an Outlook->Google sync, got the colours updated in Google exactly as required (based on the new Mapping facility).    

Returned to the app today and, on hitting the Sync Options / What / Mappings button got the above error.   Details from error message attached (I hope - not used GitHub before!).   Should add - if I hit Continue on error message, window with mappings displayed error occurs again - thereafter each time I click anywhere on that window the error message appears again (with same error message)
[debugf.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4771521/debugf.txt)

**Comment by phw198** [comment]
Thanks @jbtapscott - I've replicated this by saving a colour mapping, closing OGCS, reopening and **before any sync** clicking the Mapping button - the Google colour dropdowns are not populated properly.

**Comment by phw198** [comment]
:package: This should now be resolved with [build v2.8.3.15.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4775163/v2.8.3.15.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by jbtapscott** [comment]
Limited time this evening to test, but have run through this several times using different combinations of when I hit the Mapping button, together with a number of Saves / Sync's / Restarts.  Have encountered no crashes.    Am away for the next few days but will carry out more testing later in the week.
