### ISSUE TITLE
Unwanted popups

### ISSUE THREAD

**Issue by dh78751** [phw198/OutlookGoogleCalendarSync#1011]
**Are you already using OGCS?**
Yes, v 2.8.3.0

**Describe the question you have**
Every time there is a sync between Google and Outlook, I receive a popup informing me they've synced. Any way to get rid of this?

**Comment by TheJacksonian** [comment]
Yes, untick this option in Application Behaviour
![OGCSync](https://user-images.githubusercontent.com/26889446/97232114-b4751180-1830-11eb-8466-bd70e1506894.png)
