### ISSUE TITLE
COM error not redirected to wiki: Interface not registered [0x80040155]

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1012]
> **Checklist**:
> - [x] Upgraded to the latest release latest alpha release
> - [x] Reproduced the issue several times
> - [x] Reported the issue
> - [x] Provided the OGcalsync.log file (see below)

**OGCS Version**: v2.8.3 / v2.8.0 / v2.5.3
**Edition**: Install & Portable
**Sync Direction**: Not applicable

**Bug Description**
I'm experiencing a very similar issue where OGCS crashes upon launching. This started happening after I went through a complete re-installation of Outlook last weekend. I've tried re-installing v2.8.3, v2.8.0, and even 2.5.3 which I used earlier. I've also tried using the portable edition of v2.8.3. All crash the exact same way. I've tested the above before starting Outlook as well as after starting Outlook. I've tested it while the machine had been running for a while as well as right upon rebooting. All approaches result in the same error 0x80040155.

**Steps to Reproduce the Issue**
Launch OGCS

**Any other information**
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4778052/OGcalsync.log)

_Originally posted by @ond198 in https://github.com/phw198/OutlookGoogleCalendarSync/issues/999#issuecomment-643902031_

**Comment by ond198** [comment]
@phw198 Thank you for your response and for pointing to the wiki instructions. I didn't quite grasp what you meant by "This can be a particularly nasty problem". Well, once I was passed a windows blue :( "bad news" screen and completed the remaining steps of the instructions, I had a better idea. Boy that WAS a nasty one! The good news is... it's resolved and OGCS is humming again. Thanks for your help!
