### ISSUE TITLE
Outlook "out of office"

### ISSUE THREAD

**Issue by ghnogueira** [phw198/OutlookGoogleCalendarSync#1013]
Outlook has a feature on its calendar where you can select the status on your calendar that particular appointment will have, named "Available", "Provisional", "Busy", "Out of office". There's an option in OGCS where we can set the appointment that's being synced as "free/available", and it works fine, but I couldn't find the same option for the "out of office", and that's the standard behaviour I'd like to have when syncing my personal calendar (from Google) to the business calendar (on Outlook).

I think that the program might be halfway there, as when I select to set it as available, when syncing it showed once in the log "Free/BusyolOutOfOffice → olFreeCategory", so I guess we just have to force that "olOutOfOffice" category.

Thanks in advance.

**Comment by phw198** [comment]
:package: This should now be possible with development build [v2.8.4.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4873420/v2.8.4.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) in the same way as a hotfix).

Let me know any feedback.

**Comment by ghnogueira** [comment]
Great, I'll take a look :)
Thanks!

**Comment by phw198** [comment]
Any update @ghnogueira?

**Comment by ghnogueira** [comment]
Hi Paul. I lost access on the notebook I was using, and then had trouble to apply the update, even tho I followed the instructions. Pandemic times + a newborn are also preventing me from having the proper time. I'm really sorry about showing this thing and then not even testing =(

**Comment by ghnogueira** [comment]
Hi there! Finally I was able to spare some time to do this :) and it works nicely, thanks for the addition!

Only downpoint I saw was if the entry was already synced to Outlook and I change the setting in the OGCS app (for example, from available to out of office) the entry doesn't get changed in Outlook (so it stays available, in the example, instead of changing to OOO).

**Comment by phw198** [comment]
Thanks for confirming! The behaviour you describe would be expected - to force a sync through into Outlook having changed the OGCS config, press and hold `Shift` and click the `Sync` button.
