### ISSUE TITLE
[Question] How does Outlook handle multiple reminders?

### ISSUE THREAD

**Issue by Invisible40** [phw198/OutlookGoogleCalendarSync#1015]
**Are you already using OGCS?**
I'm about to install it.

**Describe the question you have**
On Google Calendar, I have multiple reminders for my events. How does Outlook handle this, which can only make events with one reminder?

Also, if I make an event with Outlook, does it sync with Google Calendar? And vice versa?

**Comment by phw198** [comment]
Only "notification" reminders are considered (not email reminders) and the final reminder is synced to Outlook (ie the last one before the event actually occurs).

Not sure what you mean by your second question, but certainly calendar appointments will sync either way if you configure two-way sync.
