### ISSUE TITLE
The recurrence pattern is not valid.

### ISSUE THREAD

**Issue by fogoat** [phw198/OutlookGoogleCalendarSync#1016]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.3
**Edition**: Portable  
**Sync Direction**: G->O 

**Bug Description**  

I am not sure why this error is occuring. I have two recurring events. One for every 15th of the month and another for 30th of the month. 15th works fine, but 30th does not.

![image](https://user-images.githubusercontent.com/6989799/84859017-1ae75900-b021-11ea-9aa3-37769ff87184.png)

I think I know why... February does not end on 30th.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4790496/OGcalsync.log)

**Comment by phw198** [comment]
I'd need to see the `DBUG` log line that says what the `RRULE` is in Google: eg `Converting RRULE:FREQ=MONTHLY`

If I create a recurrence as per your screenshot, that's what I get and it is handled without issue in Outlook. However, I believe your `RRULE` has a `BYDAY` element to it too. What service created the Google event?

**Comment by fogoat** [comment]
Google calendar created the event. Outlook can't handle 30th day because Feb is 28 or 29. Creates ok in Outlook but unsupported in Google calenda4. I just set it for the 1st and early notify by one day (which makes it last day of previous month).

**Comment by phw198** [comment]
Sorry, I'm completely lost! If you created it on Google how can it be unsupported on Google?

You said you were syncing from Google to Outlook and the error message is from Outlook. If I manually create an event in Google with the same recurrence as in your screen shot, OGCS syncs it to Outlook without issue. FWIW, the 30 Feb occurrence in Outlook displays on 28th Feb, which Google doesn't, but nothing can be done about that...

**Comment by fogoat** [comment]
I'm unable to reproduce the issue now after I recreated the event. Since Feb is 28 or 29, I think setting at day 1 and adding a notification of 1 day will do what I want. Sorry for the trouble.
