### ISSUE TITLE
On startup OGCS 2.8.0.0 loads 2 instances of itself instead of just 1

### ISSUE THREAD

**Issue by jrkoop** [phw198/OutlookGoogleCalendarSync#1017]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.0.0  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
On startup OGCS 2.8.0.0 loads 2 instances of itself instead of just 1. Log pasted below because the file for some reason wouldn't copy and attach.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

[Gist Logfile](https://gist.github.com/phw198/e34f26884de2ce16963ffd58588c354b)

**Comment by phw198** [comment]
From the logfile you provided, stored in `C:\bin\ogcs\OGcalsync.log`, you have OGCS set to start on startup with a 30 sec delay. What happens if you turn this off? Does only one instance of OGCS start then?

For the instance(s) that start, on the "About" page where do they say they are running from - is there any difference? Also check Task Manager, Process tab, View, Select Columns, Check "Command line" and then see where the two OGCS processes are running from.

**Comment by tk2themax** [comment]
V2.8.4
Same problem - two instances running in system tray.   
Also two show up in task mgr.  - properties in BOTH  are \Local\OutlookGoogleCalendarSync\app-2.8.4-alpha
(Dont know why alpha showing - is that normal for a full release?)
scrnshts and LOG provided

![Snipaste_2020-08-06_10-08-35](https://user-images.githubusercontent.com/5501336/89514873-5525d900-d7ce-11ea-9a96-71b3feb88f04.jpg)
![Snipaste_2020-08-06_10-20-16](https://user-images.githubusercontent.com/5501336/89515027-80102d00-d7ce-11ea-98e3-bbaf8147a10a.jpg)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5033898/OGcalsync.log)

**Comment by phw198** [comment]
Found we have two issues tracking this - could you have a look at [my comment](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1052#issuecomment-675137631) for further troubleshooting steps?
