### ISSUE TITLE
Google handshake failed - custom proxy

### ISSUE THREAD

**Issue by shajar007** [phw198/OutlookGoogleCalendarSync#1018]
**OGCS Version**: v2.8.3  
**Edition**: Installed 
**Sync Direction**: G->O 
**Bug Description**  
When trying to synchronize, chrome opens and asks me to choose a google account. After I choose it I receive a message on the browser: "Received verification code. You may now close this window.". The OGCS says:"Google handshake failed"
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4815167/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. Syncronize

Thanks for any help.

**Comment by phw198** [comment]
Looks like your custom proxy settings aren't working for OGCS. Have you tried just inheriting the system proxy by "inheriting from IE"? Also, is the Browser Agent critical - maybe make sure the value OGCS is using is accurate for you?

**Comment by shajar007** [comment]
Thanks!  inheriting the system proxy by "inheriting from IE" solved the problem!
