### ISSUE TITLE
Unable to connect to the Google calendar. The following error occurred:

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#102]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/643947" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/Modrica" target="_blank">Modrica</a></strong> wrote at 2015-08-20 08:50:</p><div class="markDownOutput ">Anyone know solution for this problem ? <br>
<br>
<br>
Sync started at 20.08.2015 09.45.56 <br>
Syncing from 19.08.2015 to 20.10.2015<br>
<h2>Outlook → Google</h2>
Reading Outlook Calendar Entries...<br>
<h2>7 Outlook calendar entries found.</h2>
Reading Google Calendar Entries... <br>
Unable to connect to the Google calendar. The following error occurred: <br>
Google.Apis.Requests.RequestError <br>
Bad Request [400] <br>
Errors [<br>
<pre><code>Message[Bad Request] Location[ - ] Reason[badRequest] Domain[global]</code></pre>
] <br>
<br>
Operation aborted after 1 failed attempts!<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/phw198" target="_blank">phw198</a></strong> wrote at 2015-08-28 07:10:</p><div class="markDownOutput ">Hi <br>
Have you been able to select the Google calendar you want to sync to? Make sure you've followed the instructions on the Help tab....if you have already, it would be good if you could post your OGcalsync.log file whilst in Debug mode so I can see better exactly
 what's happening. <br>
Thanks<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/Laraxl" target="_blank">Laraxl</a></strong> wrote at 2015-09-11 17:10:</p><div class="markDownOutput ">I don't know if it's part of the same thing but in my case the error I receive is &quot;Unable to connect to the Google calendar. The following error occurred:
<br>
Web request to '<a href="https://accounts.google.com/o/oauth2/token"  rel="nofollow">https://accounts.google.com/o/oauth2/token</a>' failed.&quot;
<br>
<br>
Can you help me? <br>
Thanks<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/phw198" target="_blank">phw198</a></strong> wrote at 2015-10-25 22:33:</p><div class="markDownOutput ">I think this is most likely because the application defaults to using the Internet Explorer proxy settings. Try using no proxy and then retrieving your calendars again?<br>
</div></div>

**Comment by darrensiow** [comment]
I used 'no proxy' but I'm still getting the error message (Web request to 'https://accounts.google.com/o/oauth2/token' failed." )
Help!
