### ISSUE TITLE
v2.8.4.0 immediately quits with exception after starting

### ISSUE THREAD

**Issue by FabianBeiner** [phw198/OutlookGoogleCalendarSync#1020]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Upgraded to the latest version, and now the app starts with an error. This also happens after reinstall (and a complete wipe of all leftover folders).

**Steps to Reproduce the Issue**  
1. Install the latest version.
2. Start it. ;-)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4826267/OGcalsync.log)

**Comment by phw198** [comment]
Hi @FabianBeiner and thanks for reporting this so quickly.

:package: Could you confirm if the following [v2.8.4.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4827487/v2.8.4.1.zip) fixes it ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix))?

**Comment by FabianBeiner** [comment]
Thanks for that quick fix, @phw198! This fixes the error, and the sync was successful.

And by the way: Chrome reports the latest version as possible dangerous on download, while this happens not with the previous version.

**Comment by phw198** [comment]
Awesome, I'll think I'll backport that into v2.8.4.0 :slightly_smiling_face: 

I've applied a new code signing certificate for v2.8.4 which will take a little while for its reputation to build - warning should go away once that happens.
