### ISSUE TITLE
Erroneous delete confirmations now popping up

### ISSUE THREAD

**Issue by Perk75** [phw198/OutlookGoogleCalendarSync#1024]
> Checklist:-
> * [x ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: 2.8.0.0--
 
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
I keep getting a delete confimation for 2 google calendar entries "Delete 1/11/2020 (R) Keith Mitchell - Birthday"? and Delete 1/11/2019 (R) Keith Mitchell - Birthday"?  These entries are still on my Outlook calendar and I never deleted (nor intended to delete).  I just noticed the issue occurring yesterday.

**Steps to Reproduce the Issue**  
! suspect the issue my be related to the Outlook file, so I'm at a loss on how to advise anyone to recreate the problem in a test environment.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4833793/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
You've said you've upgraded to the latest release, but are still on 2.8.0 - please [upgrade to 2.8.4](https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.8.4-alpha) and check if the issue remains.

Also have a look at the [wiki entry](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).

**Comment by Perk75** [comment]
Looks like the check update is broken…

**Comment by phw198** [comment]
Well yes, but you'll notice I didn't say to upgrade using that method. Also the 2.8.4 release notes say under bugfix "Broken upgrade mechanism (fixed from this release onwards)".

Not sure what further information you need that isn't in the upgrade link in your opening post...
