### ISSUE TITLE
ERROR: Unable to connect to the Google calender

### ISSUE THREAD

**Issue by dmccrea** [phw198/OutlookGoogleCalendarSync#1026]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.3.0
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
The sync immediately fails with the above message: ERROR: Unable to connect to the Google calender

**Steps to Reproduce the Issue**  
1. Start Outlook Google Calendar Sync
2. Click on Sync
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4835379/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by dmccrea** [comment]
Downloaded and ran 2.8.4 and got the same error.

**Comment by mcbros** [comment]
+1

**Comment by petergardner79** [comment]
same here

**Comment by DirkB64** [comment]
same here for 2.8.3, update to 2.8.4 shows the error too

**Comment by phw198** [comment]
Looks like a huge jump in Google response times and they're now rate limiting hard. I would expect the issue to resolve itself once Google have resolved the underlying problem (though there's nothing reported on their health status yet).

For those who tested under 2.8.4 was the error message reported any differently?

**Comment by petergardner79** [comment]
Thanks looks like it has resolved itself now
