### ISSUE TITLE
Error 0x80004002 - E_NOINTERFACE; repair didn't work; upgrade doesn't work either....

### ISSUE THREAD

**Issue by MarcusDom** [phw198/OutlookGoogleCalendarSync#1029]
Hi,
Thanks for a nice product.
Got W10, latest, all updates, etc.
Got error as indicated.
Did Office repair (both quick & full online ones).
Error still persists.
Went to URL (in 3 browsers) of  update to your software.
Blank page each time apart from version # 

Over to you please.
MTIA.

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4840743/OGcalsync.log)

**Comment by phw198** [comment]
You mean the [Upgrade URL](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) - works for me....

Your actual error is `0x80029C4A` so try the [wiki instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary) for various registry fixes.
