### ISSUE TITLE
Error Saving change in Settings 2.8.4

### ISSUE THREAD

**Issue by sjsdoc60** [phw198/OutlookGoogleCalendarSync#1031]
Deleted prior  versions and the OGCS folder.  Installed alpha 2.8.4.0
I did get it to sync with new mappings.  Was working well.  Went to set it to Start on Login, Start in Tray, and Minimize to Tray.  Tried to save.  Got Unhandled Exception Error.  Removed all 3 checkboxes but still unable to save.  I copy/pasted the debug window to attachment and took a picture.  It did keep the start on login with time delay between quitting and restarting but still get same save error now with any attempt to save.
[2020-06-28_11-48-14.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/4842752/2020-06-28_11-48-14.pdf)
[New Text Document.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4842753/New.Text.Document.txt)

**Comment by phw198** [comment]
Hi @sjsdoc60 

Could you also send me your `OGcalsync.log` file and your `settings.xml` file? Thanks.

**Comment by sjsdoc60** [comment]
Here is one.  GitHub says does not support uploading of that type when try settings.xml.  So I did a copy and just changed extension to txt.  You can change it back if needed to xml.
[settings.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4875910/settings.txt)

[calendar.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4875908/calendar.log)

**Comment by phw198** [comment]
Reopening this, as I'm assuming you didn't mean to close this issue...

**Comment by phw198** [comment]
You've now provided the log file for the 29-Jun, not 28-Jun when you reported this error, and apparently you are no longer experiencing the issue (as you have no colour mappings defined).

:package: However, I think I've found a problem which may resolve it should you get the same error - [hotfix v2.8.4.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4944662/v2.8.4.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by sjsdoc60** [comment]
I have applied the 2.8.4.4 hotfix and double checked the About tab.
I do not understand your comment re: colour mappings.  I dont use those.  Never have.  Colors are unhelpful.  I use the CATEGORIES in Outlook and separate calendars (with its own color) in Google.  Mapping to colors always got me in trouble from the early days (as well as others) hence your excellent work to bypass colors and use the actual method of categorization in each program.  If I am supposed to use color mappings, can you further explain.  At the moment, I send calendar items from one program Category to the other Program category.
Thank you

**Comment by sjsdoc60** [comment]
Here is an example of a missed calendar item in Outlook 365 supposed to go to Google on a one way sync.  The recurring item is 'Key Updates, hosted by xxxx' on Monday July 27, 2020.  This is 115PM local time.  It is a every 2 week recurring item.  Categorized as EPIC/HI correctly.  It should be copied over to Google.  The recurrence goes from 6/29/20 to 7/27/20 which is the date of the missing item.  I did remove and re-add in the category.  Either OGCS is not seeing it or thinks it doesn't need to add to Google.  Tried several times today.  It is interesting that the recurrence date ends on the same date as the last occurrence of the meeting.  Maybe that is the problem?

[settings.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4948474/settings.txt)

[calendar.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4948475/calendar.txt)

**Comment by phw198** [comment]
@sjsdoc60 It's up to you to work out how you wish to configure OGCS. v2.8.4 provides the ability to specify which Outlook category (and its associated colour) maps to which colour in Google (which does not have categories). You had previously shown interest in this feature, and the bug I believe you were reporting on this issue was related to you having defined such a mapping. v2.8.4.4 should fix said bug and will also be released into v2.8.5.0.

Thanks.
