### ISSUE TITLE
Google to Outlook merge entries not working

### ISSUE THREAD

**Issue by sjsdoc60** [phw198/OutlookGoogleCalendarSync#1032]
[calendar.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4846604/calendar.log)
![2020-06-29_9-58-23](https://user-images.githubusercontent.com/49739237/86028465-25293000-b9ef-11ea-8087-3eb75e14f3e7.jpg)
![2020-06-29_9-57-38](https://user-images.githubusercontent.com/49739237/86028481-29554d80-b9ef-11ea-8e36-99dce5b0fa0f.jpg)

Version 2.8.4.0
Google to Outlook one way sync
Merge with Existing Entries not working.  doesnt matter if I toggle box on or off.  I enclose pictures of OGCS and my Outlook calendar after 3 sync operations.  Note the Pilates on Tues and Thurs are repeated 3 times.  A new entry is made every time.  Yet, the Mike Rankin appt which is also Google to Outlook is not repeated.  Both are repeating entries.  I did delete all the Outlook entries but did not make a difference with new entries on every sync.

Thank you

**Comment by phw198** [comment]
Without the day or the time or the start date of the recurring Pilates session, I really can't tell what I'm looking at between the screenshot and the log file.

I see you've tested the Outlook date format a couple of times, but no evidence of you trying different values? I suspect you weren't using `g` with the previous version of OGCS...?

**Comment by sjsdoc60** [comment]
The Tuesday morning is Pilates from 9-10, recurring weekly for a year or more.   The Thursday morning is Pilates recurring weekly 9am-10 same recurring.  They dont have a defined end point.

I dont know what outlook date format means.  I use it as it comes default for date.  I never changed the 'g' in Outlook/Regional Date format/Default.  Picture enclosed.

I just uploaded my calendar.log and settings.xml if needed in post 1031

![2020-07-05_17-20-48](https://user-images.githubusercontent.com/49739237/86544427-f2e26b80-bee3-11ea-89d5-3decdfa8e011.jpg)

**Comment by sjsdoc60** [comment]
Sorry, the Tuesday is actually 10am-11, recurring weekly, indefinite

**Comment by sjsdoc60** [comment]
It is now working.  I deleted all items from Google in Outlook and started over.  It now is correct.  Not sure what the issue was.  Enclosed is the log and settings if desired.
[calendar.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4876131/calendar.log)
[settings.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4876141/settings.txt)

Donated
