### ISSUE TITLE
Edge/Windows 10 indicates programme as unsafe

### ISSUE THREAD

**Issue by JeroenTuinstra** [phw198/OutlookGoogleCalendarSync#1033]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.4.0  
**Installed or Portable**: Installed

**Problem Description**  
In programme update fails, so directed to your website. The download is blocked by Edge (latest version) with the indication:
"This file was blocked because it could harm your device." When you accept the download anyways, Windows 10 blocks the setup with the following indication: 
Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.
Application: | Setup.exe
Publisher: | Open Source Developer, Paul Woolcock

**Steps to Reproduce the Issue**  
1. Download file from site: https://phw198.github.io/OutlookGoogleCalendarSync/
2. Indicate to "keep file anyway" in Edge
3. Start setup.exe 

**Any other information**

**Comment by phw198** [comment]
Hi @JeroenTuinstra - thanks for reporting. However, the code signing certificate is new and it takes a while for the trust to build against it. Hopefully it will stop being blocked soon...

**Comment by KarlKl** [comment]
I think this can be closed. Didn't show up on my PC.

**Comment by phw198** [comment]
Yes, though annoyingly it is an ongoing issue - every time I release a new version of OGCS, it takes a certain amount of time/downloads (I don't know the specifics of Microsoft's algorithm) before the warnings disappear. Also the code signing certificates can only be issued for a year, so the reputation associated with that repeatedly gets lost too! All very frustrating...
