### ISSUE TITLE
Feature Request: Choose whether to sync All-Day events

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#104]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/646796" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/aejaygoehring" target="_blank">aejaygoehring</a></strong> wrote at 2015-10-29 17:01:</p><div class="markDownOutput ">I don't know how it is for everyone else, but at my place of work my calendar is pretty constantly inundated with All-Day requests from people saying they will be Work at Home or Out of Office. I try to keep my calendar trimmed of them, but it made me
 realize... <br>
<br>
I really don't want <em>any</em> All-Day meeting synced to my Google Calendar. I've never had an All-Day item that was useful and needed to be referenced later in the other Calendar. I really just need the regular meeting during the day so I get reminders and
 can pull up the descriptions. <br>
<br>
Does a setting for this exist already (I've looked around, but I could have missed it)? If not, could it be considered?<br>
</div></div>

**Comment by euinor** [comment]
Hi, any news on this enhancement? It would be nice to not sync all day events. 
Also, I would like to only sync accepted events - I have many events in my calendar set as 'tentative' so I am aware of them but are unlikely to attend. I don't need to sync these.

Edit: similar to https://github.com/phw198/OutlookGoogleCalendarSync/issues/825 (as all day or tentative events are usually 'free').
Workaround: categorise all day/tentative events and exclude that category.
Edit2: workaround doesn't work 100% as you cannot categorise individual occurrences in a series, whereas you can be tentative on one occurrence in a series.

**Comment by phw198** [comment]
:package: This should now be available with [hotfix v2.10.0.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12064933/v2.10.0.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/b52d8d9d-d95c-455c-8ea0-8b3087a27f63)

If you give it a go, please let me know how it goes!

**Comment by euinor** [comment]
Tested it (with exclude-all-day-items ticked and that-are-free unticked) and it works as expected. Thanks!

**Comment by euinor** [comment]
I did notice applying this hotfix turned off 'start on login'. I don't know if it was a coincidence.  Is there a log I can send to you?

**Comment by phw198** [comment]
That's odd - do you still have the log file from the day when you applied the hotfix and first started OGCS?

What version of OGCS were you running beforehand?

**Comment by euinor** [comment]
I was running v2.9.7.0.
Links below are OGcalsync.log.2023-07-17, which is the last log with v2.9.7.0
and OGcalsync.log.2023-07-20, which is the next log recorded and is says version v2.10.0.5
(hopefully the links work...)
[2023-07-17](https://drive.google.com/file/d/1B0XP57wT1rAbUgnSQSos28CGYwbZre0g/view?usp=sharing)
[2023-07-20](https://drive.google.com/file/d/1Ao1NhDmAuY5ANt5ZEDd5-nV_z0-JQjnq/view?usp=sharing)

**Comment by phw198** [comment]
From your first log file, it looks like the setting was false even under 2.9.7, so I think you just noticed it when you patched to v2.10.0.5

> StartOnStartup: False; AllUsers: False; DelayedStartup: 300

Hard to know if it was a bug if we don't really know when it happened...

**Comment by euinor** [comment]
> From your first log file, it looks like the setting was false even under 2.9.7, so I think you just noticed it when you patched to v2.10.0.5
> 
> > StartOnStartup: False; AllUsers: False; DelayedStartup: 300
> 
> Hard to know if it was a bug if we don't really know when it happened...

I hadn't changed the version in a while and it was running fine before. So if the flag was changed before I upgraded, then it must have been something I did. Chalk it up to user error for now - I'll make a ticket if it comes up again.
