### ISSUE TITLE
I donated, please help to remove splash screen. Thanks

### ISSUE THREAD

**Issue by tommytsengiphone** [phw198/OutlookGoogleCalendarSync#1040]
I donated, please help to remove splash screen. Thanks
tommytseng@qnap.com

**Comment by phw198** [comment]
Hi @tommytsengiphone When did you donate? I can't seem to find anything looking like your GitHub handle. Can you provide the PayPal transaction ID?

**Comment by tommytsengiphone** [comment]
After checked PayPal, it seems that the transaction was not completed. 

I will try later.
