### ISSUE TITLE
Exception from HRESULT: 0x8004010F Errors

### ISSUE THREAD

**Issue by deinfluence** [phw198/OutlookGoogleCalendarSync#1042]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0
**Edition**: Installed 
**Sync Direction**: O->G 
**Bug Description**  
I keep getting random sync failures which have the following text in the OGcalsync.log
```
2020-07-08 13:44:49,474 WARN  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Failed to get appointment summary: 
2020-07-08 13:44:49,474 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x8004010F
2020-07-08 13:44:49,475 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x8004010F;-2147221233
2020-07-08 13:44:49,475 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_AllDayEvent()
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.GetEventSummary(AppointmentItem ai, Boolean onlyIfNotVerbose)
```
The annoying thing is that OGCS won't sync again unless I click to try again and then it usually works for a while until it happens again.

**Comment by phw198** [comment]
I don't think the log lines you have provided are actually the cause of OGCS not syncing again, but it captures a `0x8004010F` which goes to the point of your Outlook profile and/or data files being corrupt.

[Google returns many results](https://www.google.com/search?q=0x8004010F&oq=0x8004010F&aqs=chrome..69i57j69i61&sourceid=chrome&ie=UTF-8) for this, maybe have a [read through this one](https://techhelpguide.com/outlook-data-file-cannot-be-accessed/). Would be interested to hear your particular solution if you find it...

**Comment by deinfluence** [comment]
Thanks @phw198 for the advice - I will try and investigate.

Is there a way to increase the number retries or prevent the retry prompt appearing? I typically find if I just click retry it works fine again and as this is running on an unattended PC I don't know its stopped until I periodically check.

**Comment by phw198** [comment]
Not really - it's also potentially rather a big problem, so not one that should be ignored. It's possible it's the same item that's always causing the issue, but it's not always included in the sync. What's the date range you are syncing - could try reducing it and seeing if the problem goes away? I could also maybe amend the logging to capture the subject of the problematic item(s), as currently it fails right at the start determining if it's an all day event...
