### ISSUE TITLE
Access to file denied

### ISSUE THREAD

**Issue by jorgenbosman** [phw198/OutlookGoogleCalendarSync#1043]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0
**Edition**: Installed
**Sync Direction**: G->O 

**Bug Description**  
When running multiple instances, each with a seperate logfile, I have it at c:\temp\OGcalsync_xxx.log and c:\temp\OGcalsync_yyy.log, After 30 days it seems to delete old log files, but then both instances do it in parallel and one of the instances says: Access to path 'C:\Temp\OGcalsync_xxx.log.yyyy-mm-dd' is denied. I guess both instances try to delete the same files. I guess that they are trying to delete OGCalsync* instead of OGCalcync_xxx* and OGCalSync_yyy*

**Steps to Reproduce the Issue**  
1. Run 2 or more instances of OGCS each with different logfile in same folder at system startup (in registry Run key)
2. Wait until files start to be removed
3. One of the instances will raise this error

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync_SMCB.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4912216/OGcalsync_SMCB.log)
[OGcalsync_OLV.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4912217/OGcalsync_OLV.log)
[OGcalsync_duofoto.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4912218/OGcalsync_duofoto.log)

**Comment by phw198** [comment]
:package: Thanks - this should now be resolved with [hotfix v2.8.4.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4944681/v2.8.4.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

BTW, did you know there's a `/t` CLI argument to append custom text to the OGCS window title?

**Comment by jorgenbosman** [comment]
This patch seems to have fixed it. 😊

Thanks for the tip!
