### ISSUE TITLE
Does OGCS use Shuttlecloud?

### ISSUE THREAD

**Issue by RootX99** [phw198/OutlookGoogleCalendarSync#1044]
**Are you already using OGCS?**
2.8.4.0

**Describe the question you have**
Google has sent me a few warnings that there is an unverified developer application called Gmail Shuttlecloud Migration that has access to my Gmail account.  Is this related to OGCS?  If yes, is there any reason to worry?  If not, I am going to remove the app.

Thanks
Matt

**Comment by phw198** [comment]
No, ShuttleCloud isn't anything to do with OGCS.
