### ISSUE TITLE
OGcalsync.log may contain private information

### ISSUE THREAD

**Issue by jay-gates** [phw198/OutlookGoogleCalendarSync#1046]
> Checklist:-
> * [+] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [+] Reproduce the issue
> * [+] Complete the information below
> * [+] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4  
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
While the log does redact some user information, it misses others. Some of this may only apply in a corporate environment. Examples are from 2.8.3 (because I'm submitting a log for another report), but confirmed in 2.8.4. In the examples below, {THIS TEXT} contains private information.

Ex. 1:
Adding listener for Explorer 'Inbox - {FULL EMAIL ADDRESS} - Outlook'

Ex. 2:
OutlookGoogleCalendarSync.Settings [0] -  C:\Users\\{USERNAME}\bin\Portable_OGCS_v2.8.3\settings.xml

**Steps to Reproduce the Issue**  
1. Run OGCS

2. Share log file (ex., attach to a bug report here)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync_redacted.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4961893/OGcalsync_redacted.log)

**Comment by phw198** [comment]
Thanks for reporting - both examples you mentioned should be fixed in the next release.
