### ISSUE TITLE
unable to connect to the Google Calendar

### ISSUE THREAD

**Issue by IanNettleton** [phw198/OutlookGoogleCalendarSync#1049]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<unable to connect to the Google Calendar>

**Steps to Reproduce the Issue**  
1. \<Update>
1. <Click Sync>
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4986362/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by IanNettleton** [comment]
Problem started yesterday

**Comment by morphmkd** [comment]
I also had the same problem this morning. I managed to fix it by going to https://console.developers.google.com/apis/credentials and creating a new project (You can name the project as you wish). You then need to create a consent screen for the OAuth and then go to Credentials to create credentials for your computer. You then go back to the program (Outlook Google Calendar Sync) and enter the CLient ID and Secret that you just created in to Settings / Google tab (you need to click on Show advanced developer options).
Then when you try to sync you will see in the log a final requirement to enable the google calendar API. Something like this: "Message[Google Calendar API has not been used in project XXXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/calendar-json.googleapis.com/overview?project=XXXXXXXXXXXXX then..."
Go to the url, enable the API and that's it.

There is maybe a simpler solution for this but this is how I got it working.

Regards.

**Comment by phw198** [comment]
@IanNettleton Did this resolve itself? Quota wasn't be exhausted at that time and shouldn't have been rate limited. 

However, stats are showing an odd sudden jump in errors listing calendar events between 03:00-10:00 for the 28-Jul:
![image](https://user-images.githubusercontent.com/11843015/89351956-f87dcd80-d6aa-11ea-9439-9e98bbbd57e7.png)

I'm thinking Google had some transient problem...

**Comment by IanNettleton** [comment]
Yes it did seem to resolve itself - you can close the issue - thanks

**Comment by IanNettleton** [comment]
Syncing fine now - but it seems the update prompt is failing - update
failed.
Anyhow not a major for me as I rarely update
Cheer
[image: image.png]
[image: image.png]

**Comment by chichaz** [comment]
> I also had the same problem this morning. I managed to fix it by going to https://console.developers.google.com/apis/credentials and creating a new project (You can name the project as you wish). You then need to create a consent screen for the OAuth and then go to Credentials to create credentials for your computer. You then go back to the program (Outlook Google Calendar Sync) and enter the CLient ID and Secret that you just created in to Settings / Google tab (you need to click on Show advanced developer options). Then when you try to sync you will see in the log a final requirement to enable the google calendar API. Something like this: "Message[Google Calendar API has not been used in project XXXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/calendar-json.googleapis.com/overview?project=XXXXXXXXXXXXX then..." Go to the url, enable the API and that's it.
> 
> There is maybe a simpler solution for this but this is how I got it working.
> 
> Regards.

Thanks for this! I've gotten into your instructions, but am stuck getting OGC to authorize during "retrieve calendars." Google's giving me a "not authorized" error. I think I missed something in the API setup. What & where am I to authorize OGC Sync? 

Google says:
_The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
access_type: offline
response_type: code
redirect_uri: http://localhost:56384/authorize/
client_id: 250188496351-ms2q034p1r48nhk2ntt2jeq9f5mp9k33.apps.googleusercontent.com
scope: https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/userinfo.email openid_
