### ISSUE TITLE
2-way Outlook deletion not synced first time

### ISSUE THREAD

**Issue by Kandrina** [phw198/OutlookGoogleCalendarSync#1050]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4987152/OGcalsync.log)

**OGCS Version**: v2.8.0.0 
**Installed or Portable**: Installed

**Problem Description**  
\I'm using Two-Ways sync, but when i delete an entry from Outlook, t won't delete in the Google Calander and the other way round. I unchecked "Disable deletions" and "Confirm deletions"

**Steps to Reproduce the Issue**  
1. Create 2 entries and sync
2. delete 1 Entry from outlook and/or one entry from google, sync again

**Any other information**  
Using Outlook 2019

**Comment by Kandrina** [comment]
UPDATE: Seems to work if i sync twice in a row.. but requires confirmation even though "Confirm deletions" is unchecked

**Comment by Kandrina** [comment]
Update2: It works if i have more than 1 Event, deleting from google only takes  sync to show up in outlook, but deleting in outlook still needs 2 syncs. But no more confirmation required

**Comment by phw198** [comment]
I'm guessing that the confirmation you were getting was "Confirm mass deletion" and "All Google events are going to be deleted." warning? This happens regardless of whether you have confirm deletions checked or not, as it's trying to protect against people wiping their entire calendar through some misconfiguration.

If you were testing and only had 1 item in your calendar that was being deleted, that might not have been so obvious. :slightly_smiling_face: 

The needing two syncs before the delete takes place has been a bug I've noted for a while...will try and track it down!

**Comment by phw198** [comment]
:package: The failure to delete on the first two-way sync from Outlook should now be resolved with [hotfix v2.8.4.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5045119/v2.8.4.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
