### ISSUE TITLE
sync multiple calendars

### ISSUE THREAD

**Issue by mosd3f** [phw198/OutlookGoogleCalendarSync#1054]
**Are you already using OGCS?**
Yes, version 2.8.4.0.

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.
I'm not sure if this is a feature request or something I need guidance on. In any case, I hope it's the latter (as it'll in all likelihood be easier to resolve). Ok, here I go.

I am primarily using OGCS to (one-way) sync O365 to Google Calendar and would like to sync multiple O365 calendars (2) of mine to Google (both are calendars in my O365 mailbox: one is the default calendar, the other is a calendar I set up and share with my team). Both O365 calendars can sync to the same Google calendar. 

Any ideas how I can make this work in OGCS? Thanks in advance and please let me know if I was unclear in any way.

**Comment by phw198** [comment]
Syncing multiple calendars is not yet built in to OGCS, but there's some [guidance on a workaround](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars)...

**Comment by as1414** [comment]
+1
