### ISSUE TITLE
"Allow Access" keep prompting on Outlook 2019?

### ISSUE THREAD

**Issue by automatorMaxima** [phw198/OutlookGoogleCalendarSync#1055]
As per screenshot below. How do I remove this annoying prompt permanently? The max I can dismiss is 10 minutes.

https://i.imgur.com/euxmq0f.png

:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Well [documented](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security).
