### ISSUE TITLE
Permission error to write in Google calendar

### ISSUE THREAD

**Issue by kunjays** [phw198/OutlookGoogleCalendarSync#1056]
<img width="1210" alt="2020-08-10_16-06-44" src="https://user-images.githubusercontent.com/69487653/89839926-c09bdd80-db23-11ea-8171-923b98096809.png">

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by kunjays** [comment]
Hi 
I am unable to sync with the error saying it needs write permission on Google Calendar, even after having the account authorized.

**Comment by kunjays** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5053896/OGcalsync.log)

**Comment by jeresk** [comment]
I had the same issue - I looked at the Google tab - where it says "Select calendar" right under the Disconnect Account - I saw it says "Contacts."  When I switched it to the email address calendar it worked.  If that helps :)  

![Capture](https://user-images.githubusercontent.com/69555636/90043062-c828c700-dc88-11ea-8970-d7bdf929e2bc.PNG)

**Comment by phw198** [comment]
You guys would save yourselves so much time if you followed the guidance and upgraded to the latest alpha before logging issues :roll_eyes:

**Comment by kunjays** [comment]
Thanks I had tried the different calendars, but the upgrade to latest alpha fixed it. Thanks @phw198
