### ISSUE TITLE
Incorrect colour mapping (from Google 'Blueberry' to Outlook)

### ISSUE THREAD

**Issue by essdeeay** [phw198/OutlookGoogleCalendarSync#1057]
**OGCS Version**: v2.8.40 alpha
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I've got 3 colour mappings in place, (Outlook Blue <=> Blueberry, Outlook Green <=> Basil, and Outlook Red <=> Tomato). both the Basil and Tomato colour mappings work, but all Blueberry (which is the Google default) get synced to Outlook as OGCSBlack.

**Steps to Reproduce the Issue**  
N/A

**Any other information**  
None

I'll contact you directly with the URL to the gist of the log file.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.8.4.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5323583/v2.8.4.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes!

**Comment by phw198** [comment]
@philwe [Confirmed](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1098#issuecomment-709880363) this fixed - thanks!
