### ISSUE TITLE
Deletion in Outlook didn't follow deletion in Google

### ISSUE THREAD

**Issue by Wave89** [phw198/OutlookGoogleCalendarSync#1058]
**OGCS Version**: v2.8.4 alpha
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Google event will not be deleted

**Steps to Reproduce the Issue**  
1. create a google event
2. sync
3. delete the outlook event
4. sync
5. Google event is still there

**Any other information**

**Comment by BassTea87** [comment]
I noticed that too. Also the other way around from Outlook to Google. Normally after some time (10-30 minutes) the event is deleted nevertheless. Maybe it takes some time to mark the event as deleted for the API 🤷‍♂️

**Comment by phw198** [comment]
Duplicate of #1050 which has a hotfix posted.
