### ISSUE TITLE
Deleted Google event failed to remove [410=Gone]

### ISSUE THREAD

**Issue by Chrismartin76** [phw198/OutlookGoogleCalendarSync#1060]
**OGCS Version**: v2.8.4.0
**Edition**: Installed / 
**Sync Direction**: O<->G

**Bug Description**  
I have two way syncing set up. If I initiative a Sync, the app asks me to confirm the deletion of a particular event, but when I say yes, I get the error "Deleted Google event failed to remove. Continue with synchronisation?" Yes/No.

**Steps to Reproduce the Issue**  
1. Go to Sync tab.
2. Click on Sync button.
3. Wait until confirmation message to delete the event on 8/3/2020 at 7 pm.
4. Click to confirm the deletion.
5. The error pops up:  "Deleted Google event failed to remove. Continue with synchronisation?" 
6. The log later shows "Deleted event failed to remove. Resource has been deleted [410=Gone]

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by Chrismartin76** [comment]
Just wanted to follow up on this.

**Comment by Chrismartin76** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5132763/OGcalsync.log)

Here is my Ogcalsync file again.

**Comment by brianoforlando** [comment]
I too am receiving this message
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5150145/OGcalsync.log)

**Comment by ichmateo** [comment]
Same issue here as well. 
As this happens to a recurring calender event, this error appears every day. Is there away that your software will ignore the error  without interrupting the synchronisation ? thx for your quick feedback

**Comment by brianoforlando** [comment]
Since the sound of crickets was deafening to me, I looked into this further.  
I closed down OGCS
I researched the event and found it on the google calendar side in the trash.  
I restored the and waited 10 minutes and then deleted the event on the Google calendar.  
I deleted all the information in AppData\Roaming\Outlook Google Calendar Sync
restarted OGCS.
I have completed several OGCS cycles successfully.

**Comment by Chrismartin76** [comment]
Unfortunately my event is no longer in the trash.

**Comment by Chrismartin76** [comment]
Is there anything else I can try here? I deleted all my logs and settings and reset the app, and I still have this problem.

**Comment by Chrismartin76** [comment]
This seemed to solve the problem
1. set past days to 0 and future days to 60
2. do a one way sync from Outlook to Google
3. do a one way sync from Google to Outlook
4. do a two way sync

**Comment by phw198** [comment]
There's a lot of good background on #1038 on this error too - seems to be some kind of combination of:
* two-way sync
* merge items turned on
* An invitation from another person sent
* Invitation is declined at some point, potentially after the invitation has changed and been resent.

However, I'm not able to find a process to replicate the 410 error. I have a sneaking suspicion is may also be related to #654 where declined Google events were still being synced to Outlook - these items will only show in Google if you have the "show declined events" option checked in the settings, but OGCS would sync them regardless. There is a fix now posted for this on #654.

Google docs say this error can just be ignored anyway though, so I have amended the behaviour of OGCS accordingly.

:package: This should now be resolved with [hotfix v2.8.5.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5507093/v2.8.5.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by Imbutien** [comment]
Hi,

Thank you for this fix.
Unfortunately, i still ahve the same issue with the message "410 gone".
My sync is one way outlook => google
I have a recurring event that face the issue (only onee, other similar cases do not face issues)
On every sync, i'm asked to delete the previous week occurence and then i get the "410 gone" error.

Please find my log file attached. I'm using the portable version on windows 10 Pro with Microsoft 365 outlook version. The portable version mixed with the hotfix may be an issue.

Your solution is great and i've donated to you so i hope the couple of beers will help you fix this :)

Regards,

Imbutien
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5524745/OGcalsync.log)

**Comment by Chrismartin76** [comment]
I thought I had resolved the problem  but after upgrading to the latest version the problem occurred again. I once again did these steps:

verified that past day was set to 0
set past to days to 1, saved, and then set it back to 0
did a one way sync from Google to Outlook
did a two way sync

You're correct that I had two-way sync, merge items turned on, and the item was an invitation sent from another person, which may have been changed. I turned off "merge with existing entries" today.

**Comment by Chrismartin76** [comment]
I just installed the Hotfix above.

**Comment by phw198** [comment]
@Imbutien You appear to be running v2.8.5.4, which is from #654.

You need to be running v2.8.5.6 posted above on this ticket to confirm if the `410` error is resolved.

**Comment by Imbutien** [comment]
> @Imbutien You appear to be running v2.8.5.4, which is from #654.
> 
> You need to be running v2.8.5.6 posted above on this ticket to confirm if the `410` error is resolved.

Thank you ! My mistake, it looks like the fix is ok with the v2.8.5.6 as i did not get the error message from my first sync :) Will let you know if the issue comes back. If no news, good news :)
Please let me know when this fix moves to the standard beta release. 🥇

**Comment by Imbutien** [comment]
Hello,

So far, so good. No issues any more so i confirm this looks like being resolved. Thank you !
Any idea about the date the V2.8.6 should be released ?

Regards,

Frederic
