### ISSUE TITLE
Google to Outlook will not save appointments

### ISSUE THREAD

**Issue by compdepo** [phw198/OutlookGoogleCalendarSync#1065]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5093268/OGcalsync.log)

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Outlook appointments save properly to Google Calendar but not the other way.  The app reports "A custom field with this name but a different data type already exists. enter a different name." I have Location, Description, and 1-way: Outlook to Google selected as options.>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<The problem is not random.  It happens with any entry in Google Calendar
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5093281/OGcalsync.log)
>

**Comment by phw198** [comment]
Not sure if you've been able to use OGCS, but just wondering if you used it a long time back - maybe when the project was on the old CodePlex site?

It seems OGCS cannot save a custom property to the appointment, which is of datetime format - I'm wondering if at some point at the start of the project is was held as a string. According to [this thread](https://social.msdn.microsoft.com/Forums/office/en-US/9264454c-f71a-4b07-8a64-4978d718e8f6/itemproperty-already-exists?forum=outlookdev), "Once you used a particular custom property, its...name/id, property type are cast in stone and cannot be changed for that store.".
