### ISSUE TITLE
How to enable ticking the description & attendees attributes | current notification: your corporate policy is blocking this feature

### ISSUE THREAD

**Issue by lucijo** [phw198/OutlookGoogleCalendarSync#1067]
**Are you already using OGCS?**
Yes, version 2.8.4.0

**Describe the question you have**
I would like to tick the boxes of "description" and "attendees attributes" in order to have them synced. 
They are not tickable and the information "your corporate policy is blocking the ability to use this feature" showws. Where and how can I change my corporate policy? 

Thanks a lot in advance!

![2020-08-19_13h57_43](https://user-images.githubusercontent.com/69903093/90632045-0b081300-e224-11ea-86b6-ed418ce8e88d.png)

**Comment by phw198** [comment]
I'm assuming your running OGCS in a work environment against an Exchange account? In which case, there's nothing you can do as the company you work for has restricted the amount of information that can be programmatically accessed.
