### ISSUE TITLE
Interferes with Outlook spam protection

### ISSUE THREAD

**Issue by tnjgb** [phw198/OutlookGoogleCalendarSync#1072]
V2.8.4.0. When OGCS is active and a message in Outlook 2016 is moved from the Junk email folder to the Inbox by dragging the message the message still has the warning:![outlook](https://user-images.githubusercontent.com/70089616/91556806-39c07080-e92b-11ea-9383-d86a6ea50425.png)  Right clicking on it gives the option to move it to the inbox which it is already in. Selecting move to the inbox with the right click has no effect. If OGCS is then exited then the message appears instantly as it should in the Inbox. With OGCS running if the junk message moved to the inbox is left for some time it eventually appears as it should.

**Comment by tnjgb** [comment]
![image](https://user-images.githubusercontent.com/70089616/91554814-bfdab800-e927-11ea-8fc2-085eee1543d7.png)

**Comment by phw198** [comment]
Can't replicate this against a hotmail account. 

What account type are these emails in? Exchange? Are you running in cached mode? Would need your logfile to see what OGCS config settings you have too.

**Comment by tnjgb** [comment]
![image](https://user-images.githubusercontent.com/70089616/97797721-38efd780-1c17-11eb-957e-4b1d23cda263.png)

Above is how an message appears in the inbox of MS Office Pro Outlook 2016 (or 365) when it has been received by POP3 and initially directed into the junk mail folder by Outlook set to safe senders only then dragged to the inbox. Using "move to inbox" has the same effect. It occurs on both BT and Clara ISPs POP3. The message appears as above until OGCS is exited and another mail folder is viewed before returning to the inbox when it appears as a normal message in the inbox.  It then appears as below:

![image](https://user-images.githubusercontent.com/70089616/97797989-a7359980-1c19-11eb-8e52-5bfa0efc84f1.png)


[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5470359/OGcalsync.log)
[settings - xml.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/5470372/settings.-.xml.txt)

**Comment by tnjgb** [comment]
Just to note this is still happening on 2.8.6.0 and Outlook 365 13801.20360 64bit

**Comment by phw198** [comment]
One suggestion might be to turn off Push Sync, restart OGCS and see if the issue persists...

**Comment by tnjgb** [comment]
I assume to turn off "Push sync" that you clear the tick box on "Push Outlook changes immediately"? I have just tried this  and restarted and it is exactly the same.

**Comment by phw198** [comment]
With Outlook closed, could you start OGCS and then run a sync. In your system tray, a little Outlook icon with a cog over it should appear (hover-over says something about programmatic access). Once the sync has completed, does this icon disappear after a few seconds?

**Comment by tnjgb** [comment]
Yes the cog appears with a message about another program using Outlook and to disconnect and exit etc. After the sync the icon with cog disappears until the next sync.

**Comment by phw198** [comment]
In which case, that proves OGCS isn't holding any connection open in Outlook except for when it is actively syncing - and therefore I can't see how it's apparently affecting the spam protection or how to troubleshoot further...

**Comment by tnjgb** [comment]
I have no idea why but somehow it locks messages originally identified as spam and does not recognise that these messages are not spam when transferred to the inbox. These are messages identified as spam by Outlook rather than those identified as spam by Norton/Symantec. After several have been received OGCS shows multiple icons in the taskbar.
![GCS Sync](https://user-images.githubusercontent.com/70089616/115311331-67328680-a167-11eb-839f-8725775abf57.jpg)

**Comment by tnjgb** [comment]
Here are two screenshots of how a message which has been moved from the spam folder to the inbox appears in the inbox with OGCS open and then after OGCS has been closed. If OGCS is opened again the message stays as normal in the second image.

**With OGCS open**
![With OGCS](https://user-images.githubusercontent.com/70089616/115359559-b227ba80-a1b6-11eb-980b-ce07071d4971.jpg)

**With OGCS closed**
![Without OGCS](https://user-images.githubusercontent.com/70089616/115359555-b18f2400-a1b6-11eb-871c-252b73dace05.jpg)

**Comment by phw198** [comment]
So OGCS will hold a connection open with Outlook in the background, so it can detect changes for Push sync and sync without having to constantly reconnect, but I'm mystified why this would cause such behaviour for spam emails. 

The multiple OGCS icons seems pertinent - it's reproducible that you get a new icon for each spam mail? When exactly does the icon appear (eg on start of scheduled sync)? In task manager can you see multiple `outlookgooglecalendarsync.exe` processes running?

**Comment by tnjgb** [comment]
I cannot currently replicate the multiple instances.

I have tried changing various settings to find out where this locking of the spam emails occur and cannot find any which remedy the problem. However it is interesting to note that if I change the setting from Outlook Default mailbox to Alternative mailbox by selecting its radio button, there is a flash of red and yellow colour on the text of "select calendar" and the locking of the spam email is gone without having to carry out any further settings changes, save, sync or restart of the OGCS program.

**Comment by phw198** [comment]
I think the multiple instances might be related to the API quota exhaustion notification in v2.8.6, which was fixed as part of #1163.

Well spotted about the switch of mailboxes - this action forces OGCS to reconnect to Outlook, thereby dropping the connection it holds open. Clearly, holding that connection is messing with Outlook's spam mechanism! How much of a problem is this for you now you know a workaround?

**Comment by tnjgb** [comment]
It is not a major problem but it means either "adjusting" the settings or exiting OGCS when you want to read an email that is marked as spam or only running OGCS when you want to sync. Not knowing how OGCS works would it be possible for OGCS to momentarily drop the connection every so often without introducing other issues?

**Comment by phw198** [comment]
:package: Please could you try this [hotfix v2.8.6.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6429330/v2.8.6.12.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

The new setting is not configurable (yet) via the application, so after applying the hotfix:
1. Start OGCS, go to Settings and click Save
2. Go to the About tab and double click on the path for "Config In" - this will open Windows Explorer
3. Close OGCS
4. In the Explorer window, find your `settings.xml` file and open in an editor
5. Find the `DisconnectOutlookBetweenSync` line and change the value from `false` to `true`
6. Save and start OGCS.
7. Verify if the issue is resolved.

**Comment by tnjgb** [comment]
I had a few issues with Norton 360 and MS Defender trying to block the hotfix version as an unknown app and also through the firewall. 

This hotfix seems to sort of work but I cannot quite work out the timings. If I move a mail between junk and inbox it does not change to the correct presentation immediately but it appears to change to how it should be after the next sync. I will look a bit more at this and see if I can see a pattern tomorrow.

**Comment by tnjgb** [comment]
When a message is first moved between the inbox and spam folder it appears to have the wrong spam related notification showing each time that message is selected (preview) or opened. After a sync it does not appear to change to the correct format until after the message is reselected or reopened and then it appears as it should. 

My guess is that somewhere in a sync cycle Outlook is released and the moved message is then processed as per the folder it is in. So the only issue is if you want to view the message before the next sync you will have to manually sync and this is not a significant issue when you know what to do.

No adverse effects noted.

**Comment by phw198** [comment]
Given this is pretty edge-case, I think I'm going to leave this as a hidden setting - now [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#outlook-spamjunk-mail-interference).
