### ISSUE TITLE
Descriptions not changed in Outlook when updated in Google

### ISSUE THREAD

**Issue by tnjgb** [phw198/OutlookGoogleCalendarSync#1073]
OGCS 2.8.4 Outlook 2016-32bit. Sync bothways. Removing or changing a description in Google does not remove or change the description in Outlook. Changing the appointment title in Google updates the title in Outlook but still does not amend the description. Changing anything in Outlook updates Google.

**Comment by phw198** [comment]
I would suspect you have the "1-way: Outlook to Google" box checked for description...

**Comment by tnjgb** [comment]
Yes, I was set to "1-way" as I had a yellow warning come up when I set it to 2-way. Now works when set as 2-way.
