### ISSUE TITLE
Unable to connect to the Google Calendar and update fails

### ISSUE THREAD

**Issue by IanNettleton** [phw198/OutlookGoogleCalendarSync#1074]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
the update failed to download
> * [ ] Reproduce the issue - ERROR: Unable to connect to the Google Calendar
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
cannot locate log file

**OGCS Version**: v2.8.0.0
**Edition**: Installed  
**Sync Direction**:  O<->G

**Bug Description**  
ERROR. Unable to connect to the Google Calendar and update fails
**Steps to Reproduce the Issue**  
1. Go to...the app
1. Click on...sync

**Any other information**  
update fails
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by IMakePoorDecisions** [comment]
@phw198  
FYI - I had this problem starting on 8/31 using my calendar that I'll call "Primary Calendar".

1. Confirmed I was running the latest version that is available:  2.9.0-beta.
2. Disconnected and reconnected Google account - Primary Calendar fails
3. Created a second google calendar called "Test Calendar."  Changed OGCS config to use "Test Calendar"  - Test Calendar success
4. Changed OGCS config back to Primary Calendar.   Primary Calendar fails
5. Downloaded a fresh copy of v2.9.0-beta.   Installed v2.9.0-beta over the existing install.   Primary Calendar fails.  Test Calendar success.
6. Uninstalled v2.9.0-beta.   Re-install v2.9.0-beta.   Primary Calendar fails.  Test Calendar success.
NOTE: This re-install did NOT require me to reconfigure OGCS again (if it matters).   The config settings were set exactly as previous instance.

7. Downloaded **v2.8.7-alpha**
https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.8.7-alpha

8. Uninstall v2.9.0-beta.   Install v2.8.7-alpha. 
NOTE: This install **did** require me to configure OGCS again (connect to google account, set up outlook side again, etc)
9. Tested against configuration:    Primary Calendar **success**
10. Use downloaded installer to upgrade from v2.8.7-alpha to 2.9.0-beta:    Primary Calendar **success**

Just wanted to document in case someone else has the same problem and wants help getting it running again.

**Comment by phw198** [comment]
@IMakePoorDecisions do you still have the log files for the fails under 2.9.0 and if so are you able to upload them?
