### ISSUE TITLE
Is OCGS compatible with Microsoft 365 

### ISSUE THREAD

**Issue by jm2144** [phw198/OutlookGoogleCalendarSync#1075]
Running Microsoft 365 on PC with local outlook not cloud based, OCGS used to work perfectly until I moved to 365. Produces error 0x80004002 repaired Office install  quick and reinstall but no effect. Folllowing other error message instructions on Wiki seems to indicate all setting to version 9.6. If it should work I will persevere! Tried install and Portable versions.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5170072/OGcalsync.log)

John

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Don't know what version of OGCS you are running, but upgrade to the latest version as I suspect you are on an old version and the error isn't being reported correctly.

OGCS does support M365, yes.
