### ISSUE TITLE
Sync Google Meet details from Google Calendar entry

### ISSUE THREAD

**Issue by KennSchaefer** [phw198/OutlookGoogleCalendarSync#1076]
### Development Builds
:package: [v2.10.2.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13403570/v2.10.2.4.zip) 

### Google -> Outlook
- [x] Plaintext
   - [x] Add as dedicated body (no Google description)
      - [x] Remove if GMeet deleted
   - [x] Append to description
      - [x] Remove if GMeet deleted
   - [x] Update URL if meeting ID changed
- [x] RTF
   - [x] Add as dedicated body (no Google description)
      - [x] Remove if GMeet deleted
   - [x] Append to description
      - [x] Remove if GMeet deleted
   - [x] Update URL if meeting ID changed
- [x] HTML
   - [x] Add as dedicated body (no Google description)
      - [x] Remove if GMeet deleted
   - [x] Append to description
      - [x] Remove if GMeet deleted
   - [x] Update URL if meeting ID changed

### Outlook -> Google
- [x] Extract GMeet ID from body
- [x] [Create in Google Event](https://developers.google.com/calendar/api/guides/create-events#conferencing)
- [x] Update in Google
- [x] Remove in Google

### GUI
- [x] New checkbox to opt-in/out of GMeet sync
   - [x] Dependency on Description checkbox

----------
Hi.  
Potentially the best product ever!

Question:
Currently, when creating a calendar event within Google Calendar, it seems some elements don't get passed into the Outlook sync version.  It would be great to add the Google Meet details such as the conferencing URL if that is possible?

Ken

**Comment by grandrew** [comment]
Is there a way to sync the other way around too? Creating an event in outlook and having google meet link appear and sent to all participants?

**Comment by phw198** [comment]
Example display of GMeet link in Outlook taken from #1605 
![image](https://user-images.githubusercontent.com/11843015/228664143-4b58d315-818b-4e90-b4e1-b69265a062e1.png)

**Comment by coercoer** [comment]
+1 for this having Google Meet links synced to Outlook. 
Thanks you added this as priority.

**Comment by phw198** [comment]
Well that was _a lot_ more complicated than it should have been, thanks to Outlook appointments having any of HTML, RTF or plain bodies! :confounded: 

But the below new option should now 
* G->O: add/update/delete Google Meet information at the end of the Outlook body as required
* O->G: add/update/delete Google conference information when a Meet URL is detected in the Outlook body

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/e81739f9-f025-43b0-80e2-c70e6f6def03)

:package: Please have a go with [early release build v2.10.2.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13403570/v2.10.2.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes!
