### ISSUE TITLE
sync date range

### ISSUE THREAD

**Issue by Cindy62707** [phw198/OutlookGoogleCalendarSync#1077]
I am setting up a new computer and would like to sync ALL calendar events from the past (for the last 10 years at least) as well as all future events.  Is there a way to make the date range greater than 365 days either way?  If not, please consider making this an option for us to be able to set custom date ranges to include all older and newer items longer than 365 days.

**Comment by phw198** [comment]
OGCS is for syncing, not exporting and importing entire calendars.

See [here for further info and tips](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-cant-i-sync-more-than-1-year-past-or-future).
