### ISSUE TITLE
nothing is syncing

### ISSUE THREAD

**Issue by Cindy62707** [phw198/OutlookGoogleCalendarSync#1078]
New user.  On Windows 10 desktop.  Downloaded the Beta version but was getting the Forbidden error message.  Forum said to update to the Alpha version.  Updated to it and still not syncing.  

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0  
**Edition**: Installed  
**Sync Direction**:O<->G

**Bug Description**  
Nothing is syncing..no deletions happening.  No new items being added.

**Steps to Reproduce the Issue**  
1. Go to... OG
1. Click on...Sync

**Any other information**  
I am a brand new user so please let me know if I am doing something wrong to cause the problem.
:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5177016/OGcalsync.log)

**Comment by phw198** [comment]
Hi @Cindy62707 It looks like the items on your Google calendar with which you are two-way syncing are read-only?

For example, do you own the item `8/23/2010 5:30 PM => "AORN"` or is this shared from someone/somewhere else and you don't have update rights? Can you make a change to this item manually in Google's web view?

**Comment by Cindy62707** [comment]
I gave up on this as I needed something to work ASAP and this wasn’t working. I do own the AORN appointment.  I own all the spots on the calendar. I do not get them from somewhere else. 

Cindy

**Comment by phw198** [comment]
Thanks for letting me know :+1:
