### ISSUE TITLE
ogcs is added to email domain

### ISSUE THREAD

**Issue by c5c86a** [phw198/OutlookGoogleCalendarSync#1079]
**OGCS Version**: v2.8.0.0 
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  

Even though sync is completed successfully, It seams that you have put the suffix ".ogcs" in the domain of my email:

I'm getting an email with title "Delivery Status Notification (Failure)" and message: DNS type 'mx' lookup of pccwglobal.com.ogcs responded with code NXDOMAIN Domain name not found: pccwglobal.com.ogcs

**Steps to Reproduce the Issue**  

I'm afraid that's not reproducible to be honest. 

**Any other information**  

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5178770/OGcalsync.log)

**Comment by phw198** [comment]
You can turn that off if you want by just unchecking the "Cloak email" option, but you'll probably wish you didn't - it's to [workaround a Google bug](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google).
