### ISSUE TITLE
Could not load file or asembly 'Microsoft.CSharp verson=4.0.0.0'

### ISSUE THREAD

**Issue by ianhops** [phw198/OutlookGoogleCalendarSync#1084]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  

Getting the below error come when attempting to sync google and outlook
```
Sync version: 2.8.4.0

Sync started at 09-09-2020 8:30:25 AM

Syncing from 08-09-2020 to 09-11-2020

Outlook ↔ Google

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.

Finding Calendar Entries
Scanning Outlook calendar...

67 Outlook calendar entries found.

Scanning Google calendar...
5 Google calendar entries found.

4 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...

Failed to retrieve master for Google recurring event outside of sync range.

Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The module was expected to contain an assembly manifest.

Sync aborted after 1 failed attempts!
```

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5191427/OGcalsync.log)

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
The Microsoft CSharp DLL is part of the .NET Framework and not shipped with OGCS. Therefore, it would seem your .NET installation is corrupted somehow - I would suggest a reinstall of it.

`2020-09-09 08:16:02,516 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  System.BadImageFormatException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The module was expected to contain an assembly manifest.`
