### ISSUE TITLE
Sync Failed

### ISSUE THREAD

**Issue by Ethan5150** [phw198/OutlookGoogleCalendarSync#1085]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.4.0
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>
Sync Failed
The synchronization failed - check the Sync tab for further details.
Do you want to try again?

The following error was encountered during sync:-
ERROR: Unable to connect to the Google calendar.

Sync aborted after 1 failed attempts.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>
This just started.  Nothing changed on my machine or Google account.  I tried disconnecting the account and reconnecting.  No problem there.  Tried resetting Gmail password.  Still get error.  Please advise.

**Comment by dddeluca1** [comment]
I have been having the same problem for a days.  Intermittently at first, but quite consistently now.  I tried: upgrading from 2.7.0.0 to 2.8.0.0, then to 2.8.4.0 alpha, I have tried rebooting.  Last I tried disconnecting my google account to re-add, but cannot get through the process, it fails trying to connect to the calendar.  The error I get is:


> Authenticating with Google
> Preparing to authenticate with Google.
> Handshake successful.
> 
> 
> Unable to get the list of Google calendars. The following error occurred:
> 
> Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

It is only 2:30 in the morning, so I cannot believe I have exceeded the per day quota.

**Comment by renebliekendaalcentric** [comment]
Having the same issue on my side. Latest stable release. Tried solving it by disconnecting my google account, rebooted my system and connected the google account again. It fails on retrieving my calendars.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5223110/OGcalsync.log)

**Comment by dddeluca1** [comment]
Case #1074 12 days ago, is the same issue I believe,

and case #1069 I believe the cause of the multiple sync failed error cascaded windows is the same quota exceeded error.

Attaching two log files.  My oldest from 8/18, and newest from today, both showing multiple Quota Exceeded errors.  I think it is not an individual quota exceeded, but for the project in general, therefore impacting all users.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5222964/OGcalsync.log)

[OGcalsync.2020-08-18.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5222970/OGcalsync.2020-08-18.log)

**Comment by renebliekendaalcentric** [comment]
> Case #1074 12 days ago, is the same issue I believe,
> 
> and case #1069 I believe the cause of the multiple sync failed error cascaded windows is the same quota exceeded error.
> 
> Attaching two log files. My oldest from 8/18, and newest from today, both showing multiple Quota Exceeded errors. I think it is not an individual quota exceeded, but for the project in general, therefore impacting all users.
> 
> [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5222964/OGcalsync.log)
> 
> [OGcalsync.2020-08-18.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5222970/OGcalsync.2020-08-18.log)

I just uploaded OGcalsync.log from my installation. I think it is a different issue. It does not state the quota exceeded errors.

**Comment by renebliekendaalcentric** [comment]
@dddeluca1 sorry for hijacking.. our problems are of a different kind. Mine btw got solved automatically. It works again over here. So I do not think that it is a project quota.

**Comment by dddeluca1** [comment]
Glad your issue was resolved.  Mine works intermittently, and just started working for now.  Last failed sync was 2:59 EST.  I turned up logging to debug to see if I can see when it stops syncing and when it resumes.  Will look over the next few days.

**Comment by Ernst79** [comment]
If you have issues with the project quota, it will mainly occur just before the quota's are being reset. The google quota are reset at midnight Pacific Time (0.00 PT), which is e.g. 9.00 AM in Europe. So it highly depends on where you live, when the timers are reset.

**Comment by kapustor** [comment]
It is not you projects quotas, guys, it is project 653617509806. It is set in the code here: https://github.com/phw198/OutlookGoogleCalendarSync/blob/2bc2611b73bb74446cdc0cd737691db2e03b2fa6/src/OutlookGoogleCalendarSync/GoogleOgcs/ApiKeyring.cs
Why do we need to sync to this project?

**Comment by JTHicks26** [comment]
This appears to be the same issue as #1062, #1053, and #603. The shared OGCS google calendar API key has reached its request limit for the day.

According to [#603 (comment w/instructions)](https://github.com/phw198/OutlookGoogleCalendarSync/issues/603#issuecomment-428962128) this can be fixed by creating your own credentials and API key, or by becoming a paid OGCS subscriber.

**Comment by dddeluca1** [comment]
I did pay once quite some time ago, but after changing computers it no
longer shows me as having paid.  I am happy to pay again though, first
because I love this app, second because it will fix this problem :-).
Thanks!

Dorothy

**Comment by Kevode** [comment]
Same issue here. Noticed since last week my Outlook events are not syncing to Gmail. I suspect either OGSC wants us to pay which means it has been falsely advertising that the product is FREE or Google has made changes causing OGSC to NOT work correctly.

Just let me know if it's not FREE anymore and that I should uninstall the product and look for a free app or if OGSC is actually fixing this problem.

**Comment by sjschultze** [comment]
I'm getting the same error for the same reason.  I'm a paid user and happy to pay again.  I think I last paid a couple of years ago, and this tool is well worth it.  But I think my application is functioning in "paid" mode yet still giving me the error.  It manifests for me as a "The synchronization failed" popup.  In fact, I have dozens of these popups cascading on top of each other when I wake up in the morning. Setting aside the quota issue, it would be nice to be able to suppress the "Sync Failed" popup.  Maybe this is a simple setting that could be added?  @phw198, I guess this is a feature request.

**Comment by phw198** [comment]
Yes, this is a duplicate of #1053 which has a hotfix posted and will be in the next alpha release.

@Kevode Not falsely advertise, no - [further explanation here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Is-OGCS-Free%3F).

@sjschultze If you are showing as a subscriber on the `About` tab, then this needs a separate investigation if you would like to raise a new GitHub issue.

Thanks!

**Comment by aprayiii** [comment]
Hi, Please clarify. I am also having the issue
The following error was encountered during sync:-
ERROR: Unable to connect to the Google calendar.

I am not seeing an error message about Quota. Yet it appears most of the discussion above is about a Quota error message. Is there a non-quota issue here? How do we fix that?

Edit - Never mind. The quota messages are in the log. Sorry I misunderstood that.

**Comment by famco75** [comment]
[image: image.png]
