### ISSUE TITLE
Meetings not showing up or double meetings

### ISSUE THREAD

**Issue by mdoxendi** [phw198/OutlookGoogleCalendarSync#1087]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<I have several calender meetings in outlook that do not show up in google, and other meetings that have duplicate meetings.>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Zero information provided by which to troubleshoot.
