### ISSUE TITLE
Unable to retrieve 

### ISSUE THREAD

**Issue by ghnogueira** [phw198/OutlookGoogleCalendarSync#1089]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.2
**Edition**: Portable  
**Sync Direction**: G->O (but tbh I did not see if it also happens in my O -> G instance)

**Bug Description**  
For quite some days, in just some syncs (once or twice a day, and I have syncs every 15 mins), I get this bug where in the sync screen a message appears saying "Unable to retrieve Google calendar's global timezone", and a message in my local language right after saying something like "There was an error while trying to send the request".

**Steps to Reproduce the Issue**  
To be honest it all happens in the background while syncing, and I haven't been able to reproduce it or at least understand if something triggers it. Sometimes it happens when I'm using the laptop, and sometimes it happens when I'm not using it overnight (and leave it on).

**Any other information**  
[OGcalsync_GO.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5263104/OGcalsync_GO.log)

**Comment by ghnogueira** [comment]
Forgot to add the print (maybe it also tells something else other than the log file).

![000012](https://user-images.githubusercontent.com/66975674/93917907-f961d180-fce1-11ea-9430-508eed33d4c9.jpg)

**Comment by phw198** [comment]
This is probably going to be due to quota problems which can be sporadic:
```
2020-09-22 01:27:24,439 WARN  9 OutlookGoogleCalendarSync.OGCSexception [0] -  Not able to retrieve Google calendar's global timezone
2020-09-22 01:27:24,439 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  Google.GoogleApiException: Google.Apis.Requests.RequestError
Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403]
Errors [
	Message[Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'.] Location[ - ] Reason[rateLimitExceeded] Domain[usageLimits]
]
```
v2.8.6 handles this much better though, so will close this issue - please raise a new one if still encountering a problem on the latest alpha release.
