### ISSUE TITLE
Limit attendees on large events

### ISSUE THREAD

**Issue by wicketr** [phw198/OutlookGoogleCalendarSync#1090]
**Is your feature request related to a problem? Please describe.**
When there are 50+ attendees in an event, I don't need the attendees sync'd to Gmail. All i need it just the calendar info. This would reduce data transfer/CPU cycles. Right now I also get warnings in OGCS for events that have 200+ attendees, and that Gmail can't sync that many. Syncing anywhere close to that is irrelevant to me, but for smaller events where I know half of the attendees, I would like to know.

**Describe the solution you'd like**
On the dialog where there is a checkbox to sync attendees, I'd like a box to enter a number for attendees. Like: "Attendee Limit: ___". This would only sync attendees when there are fewer than that number. For large events (greater than number), don't sync the attendees.

**Comment by phw198** [comment]
:package: This should now be available with development build [v2.8.6.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6057419/v2.8.6.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix), same as a hotfix).

Let me know how it goes!

**Comment by schwaben-github** [comment]
Hi Paul,
you are still awaiting the fix confirmation for this one...
I tried out this ~~hotfix~~ build, and limiting the number of attendees works fine! Thanks!
