### ISSUE TITLE
0 calendar items found in google calendar

### ISSUE THREAD

**Issue by CodeSJS** [phw198/OutlookGoogleCalendarSync#1092]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0
**Edition**: Installed
**Sync Direction**: G->O

My google calendar is filled with appointments.  I set the sync range to +/- 365 days.  OGCS reports handshake is successful, and then at the end Sync finished! with no errors reported. Howeer, OGCS reports no google calendar items.

I would not rule out the possibility that my google calendar has some poorly formed entry.  However, I don't know how to trace that.

Output is below, and I'll attached the log file.  I've tried stable release, beta version, and now alpha version.

Thanks!
```
Sync version: 2.8.4.0
Sync started at 9/23/2020 6:36:27 PM
Syncing from 9/24/2019 to 9/24/2021
Outlook ← Google
Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.
Finding Calendar Entries
Scanning Outlook calendar...
86 Outlook calendar entries found.
Scanning Google calendar...
0 Google calendar entries found.
Total inc. recurring items spanning sync date range...
Outlook 86, Google 0
Checking for orphaned items...
Matching calendar items...
86 Outlook items would have been deleted, but you have deletions disabled.
0 Outlook calendar entries to be deleted.
0 Outlook calendar entries to be created.
0 calendar entries to be compared.
Sync finished!
```
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5272381/OGcalsync.log)

**Comment by phw198** [comment]
So simple things first - you have selected the "Sherwin Singer" Google calendar to sync from. Are you absolutely sure this calendar actually contains items?
