### ISSUE TITLE
Multiple Sync Failed dialog boxes overnight

### ISSUE THREAD

**Issue by iamnaeth** [phw198/OutlookGoogleCalendarSync#1094]
When leaving the computer overnight, I get multiple dialogue boxes saying the sync failed.  However, it appears that some syncs are successful and my calendars appear up to date.  Has been happening for quite a while.

![PXL_20200924_220559434](https://user-images.githubusercontent.com/72088009/94571447-ff096b00-023d-11eb-8341-5f60358f8e1a.jpg)

[OGcalsync (2).log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5299695/OGcalsync.2.log)

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by KaiDK** [comment]
I bet its the same like this: https://github.com/phw198/OutlookGoogleCalendarSync/issues/1096

**Comment by daraeburn** [comment]
I can confirm I have the same issue, happens most nights when I leave my computer on.
![2020-10-20 08_13_15-googlesyncissue](https://user-images.githubusercontent.com/7756481/96561123-107ee980-12b7-11eb-8580-52b66f86c4e3.png)

**Comment by pilotjoe** [comment]
I am having the same issue.  It seems to happen after my system has suspended for the night and I wake it back up in the morning.  Log and requested information is attached/below.
OGCS Version: v2.8.4.0
Edition: Installed
Sync Direction: O->G
[OGcalsync.log.2020-10-19_sanitized.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/5409842/OGcalsync.log.2020-10-19_sanitized.txt)

[
![OGCS_windows](https://user-images.githubusercontent.com/36243295/96608361-4a57ec00-12c7-11eb-9bda-df5fac0f32eb.png)
](url)

**Comment by phw198** [comment]
@iamnaeth Your log file doesn't appear to cover the issue being reported, plus you are not on the latest alpha anyway.

@pilotjoe I think the underlying issue causing this is #1053 - the hotfix here should help. It also looks like on 19-Oct that Google miscalculated the API quota available and there were lots of failures.
