### ISSUE TITLE
Sync multiple Google calendar

### ISSUE THREAD

**Issue by SemperF1** [phw198/OutlookGoogleCalendarSync#1097]
I have multiple Google calendar in my google account and i need to Select every calandar, save and Sync for every calendar.

It would be nice to select all google calendar and sync them all at once.

![OutlookGoogleCalendarSync](https://user-images.githubusercontent.com/23488625/95092846-646ec780-0728-11eb-8243-373b7e7a3ab1.jpg)

**Comment by brentw1584** [comment]
Yes, this would be a great feature, I'm looking for this also as I have multiple calendars. Thanks!

**Comment by RobinEd** [comment]
I am looking for this feature too. Thanks!

**Comment by phw198** [comment]
Duplicate of #165 - please upvote there.
