### ISSUE TITLE
[Sync Options] Can't select colour for new entries

### ISSUE THREAD

**Issue by philwe** [phw198/OutlookGoogleCalendarSync#1098]
**OGCS Version**: v2.8.4.0
**Installed or Portable**: Installed

**Problem Description**  
I want to set the color for new calendar entries to red. When I try to set the color I cant choose any color.
![Screenshot 2020-10-13 135626](https://user-images.githubusercontent.com/12611169/95857477-f5165a80-0d5b-11eb-81bb-e53ae6c90d31.png)

**Steps to Reproduce the Issue**  
1. Go to sync options
2. Activate "set colour/category to". 

**Any other information**  
Worked in the past. Doesnt work anymore.

**Comment by phw198** [comment]
Can you try the hotfix on #1057

**Comment by philwe** [comment]
Thanks. This worked.
