### ISSUE TITLE
Failed to retrieve Google Calendars

### ISSUE THREAD

**Issue by eknox76** [phw198/OutlookGoogleCalendarSync#1099]
[debug.log](https://github.com/phw198/OutlookGoo
[debug.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5382306/debug.log)
gleCalendarSync/files/5382299/debug.log)
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\Attempted to sync and received multiple errors. Disconnected Google account and cannot reconnect.
**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by PrinceWm3** [comment]
**OGCS Version:** 2.8.4.0
**Installed or Portable:** Installed

**Problem Description:**
Attempts to sync and receives multiple "Unable to get list of Google Calendars..." errors. Disconnected Google account and tried to re-add it. Was successfully granted access to Google Account from the Google account page (even received the security notifications for the granted access), but Calendar Sync still presented "Failure to retrieve" errors.

**Steps to Reproduce the Issue:**
1. Problem presented itself suddenly on 10/16/2020 late afternoon. No changes were made to my system.
2. System is set to auto-sync 2-way throughout the day. Seems to work for 3-4 hours after a system reboot, then sync errors appear.

Any other information:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5405339/OGcalsync.log)
[Outlook Google Calendar Sync error details-10-14-2020.png.docx](https://github.com/phw198/OutlookGoogleCalendarSync/files/5405345/Outlook.Google.Calendar.Sync.error.details-10-14-2020.png.docx)

**Comment by droza123** [comment]
Here are my logs:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5406177/OGcalsync.log)

I am having the same problem, and have taken the same steps as PrinceWm3. 
And in the Sync tab I also get this error, which I am guessing is what is causing this:

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.


Unable to get the list of Google calendars. The following error occurred:

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.


Unable to get the list of Google calendars. The following error occurred:
`Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]`

**Comment by wildwildwilliam** [comment]
Same error here. Only started recently (in the last two weeks?)

**Comment by bbak** [comment]
Same here. Started today.

**Comment by thedarkdestructor** [comment]
Sam problem here for me and my colleagues. 

This seems somewhat related to the fact that the frequency set in the settings is not taken into the account, hence causing the quick expire of the API quota. 

Anyone have news about this issue?


![image](https://user-images.githubusercontent.com/4816982/96551412-8c2a6780-12b2-11eb-947d-efda2b698d1d.png)

**Comment by heliaburgunder** [comment]
SOLVED !!!
Same here, started today.
I get the error message:


Sync version: 2.8.4.0

Sync started at 20/10/2020 08:56:50

Syncing from 31/08/2020 to 21/10/2021

Outlook ↔ Google

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.

Sync encountered a problem and did not complete successfully.
1 consecutive syncs failed.
Unable to get the list of Google calendars. The following error occurred:

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

**Comment by apietroni** [comment]
Same "quota exceeded" here. It has been happening for quite a while though. Seems to happen randomly.

Wait.... i also have "**project_number:653617509806**"... is the key unique for the app??

**Comment by phw198** [comment]
Duplicate of #1053 - hotfix posted and will be in next alpha release.

**Comment by PrinceWm3** [comment]
Thanx so much Paul.
