### ISSUE TITLE
Deleted Items

### ISSUE THREAD

**Issue by dsdoermann** [phw198/OutlookGoogleCalendarSync#1103]
**Are you already using OGCS?**
2.8.0.0

**Describe the question you have**
Not sure if there is a general discussion board, but here is the problem.
1) Sync of Deleted Items in Gmail
         Using it initially I synced "attendees and colors" from outlook to Gmail. Then tried deleting a few and resyncing, thinking after I changed to options, the sync would put these back in.  They are recurring events I set up a while ago. But that is not happening....  they events are not showing up in.  ANy way to fix that?  Luckily it was only a day worth of repeating transactions, so I can probably just change them in outlook and they will resync, but then everyone gets more notifications in outlook!  For the other events, I just deleted the attendees in Gmail and changed the colors

2) Attendees - this is probably not your issue, but it is a question
When I deleted the attendees in Gmail, it asked if I wanted to update ALL events and I did, then it asked me if I wanted to notify deleted attendees, and I said NO.  But I noticed in Gmail I got bounced messages anyway as if it was trying....  But they went to out anyway it seems. Here is a bounce:  Your message wasn't delivered to nratha@buffalo.edu.ogcs because the domain buffalo.edu.ogcs couldn't be found

3) I just donated! Thank you, this is great.  (My goal is just to have a place my wife can see my calendar... and as you know, outlook did not play well before)

Dave

**Comment by phw198** [comment]
1. This sounds like you need to do a full sync (not just those that are modified more recently than Google). Press and hold `Shift` while clicking `Sync` button.
2. Long standing Google bug they refuse to fix. Which is why OGCS appends `.ogcs` to your attendee addresses to stop them actually be spammed!
3. Thanks so much!!

**Comment by dsdoermann** [comment]
Thank you!

-----------------
David Doermann
Professor, SUNY Empire Innovation
Professor, Department of Computer Science and Engineering
University at Buffalo

doermann@buffalo.edu
cse.buffalo.edu/~doermann<http://cse.buffalo.edu/~doermann>
Office: 716-645-1557
Mobile: 410-493-9043
