### ISSUE TITLE
Not showing as subscriber

### ISSUE THREAD

**Issue by sjschultze** [phw198/OutlookGoogleCalendarSync#1106]
As came up in #1085, I'm apparently not seen as a subscriber.  "About" tab shows "N/A."  I've changed computers since I last contributed, so maybe that's it.  Happy to provide info from config xml.  Not a high priority.  @phw198

**Comment by sjschultze** [comment]
Oh, now I see that donation and subscription are different: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Is-OGCS-Free%3F

So maybe this is expected behavior.

**Comment by phw198** [comment]
Yes, this is expected behaviour. However, as noted in that wiki article and as you have been a long time user of OGCS, I would be happy to migrate your donation over to your first year's subscription if you would like.

**Comment by sjschultze** [comment]
Oh, thank you!  That's very generous.  I'll email you the donation email separately.

I do wonder whether there should be an option to suppress sync failure notifications.  For non-subscription users, they can end up with messages like in the screenshot attached.
![sync_failed](https://user-images.githubusercontent.com/60554/97309702-c0fd6800-1838-11eb-8df1-6eaccb4d01b5.PNG)

**Comment by phw198** [comment]
The repeated failed syncs should be resolved in v2.8.5 as this will delay subsequent syncs until there is more quota available again. (OGCS did do this before as well, but Google helpful changed the error being returned for exhausted quota!).
