### ISSUE TITLE
OGCS attempts to delete recurring Google calendar events in Outlook calendar

### ISSUE THREAD

**Issue by McoreD** [phw198/OutlookGoogleCalendarSync#1111]
**OGCS Version**: v2.8.5.0
**Edition**: Portable  
**Sync Direction**: O<->G and confirm deletion enabled

**Bug Description**  
Please see this screencast:
https://mike.getsharex.com/2020/10/20201028_kdlNRzTTnH.mp4

Both Outlook calendar and Google calendar have "Empty Jas bin" as shown in the screenshot below. Proof that OGCS still tries to delete it from Outlook calendar:
![](https://mike.getsharex.com/2020/10/20201028_FhgKdI5RfB.png)

**Steps to Reproduce the Issue**  
Create recurring calendar events in Google Calendar.
OGCS would intermittently prompt for disabling these recurring calendar events synced to Outlook as the screencast shows.

**Any other information**  
[OGcalsync-2020-10-27.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5451516/OGcalsync-2020-10-27.log)

**Comment by phw198** [comment]
Hi @McoreD The log file provided is very short and appears to be configured at `ERROR` level - please can you raise to `DEBUG` and replicate the issue.

There is also [some tips around this type of issue](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) - see if that helps?

**Comment by McoreD** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5470940/OGcalsync.log)
Thanks for the advice, I have uploaded a log with Fine detail. I hope you see the information you are looking for. 
I will sync one-way and see if the problem gets fixed. This is not the first time this has happened. Last year 2 months' worth of calendar events were removed in November when I did not have confirm deletion checked.

**Comment by phw198** [comment]
`ULTRA-FINE` logging is a little too noisy, but suffice it to say, I don't see any evidence that the "Empty Jas bin " appointments in Outlook are in fact recurring. In addition, the Google event IDs that are stored against those Outlook appointments are all different, which confirms Google's events for "Empty Jas bin " were also not recurring.

Same goes for "Clean the house". Can you show me the master Google events for these and the recurrence pattern defined?

Oh....hang on, in your screen shot "Clean the house" has a flag by it - that's a Google goal isn't it....and you have those excluded in your OGCS settings.

**Comment by McoreD** [comment]
Thanks @phw198 for pointing out the Exclude Goals checkBox, although I recognise that as a new feature, and I did not disable it on purpose. Its default setting must have been `true`.
