### ISSUE TITLE
Application GUI crashes on opening - public folder mailbox RPC server unavailable

### ISSUE THREAD

**Issue by phanvuliem** [phw198/OutlookGoogleCalendarSync#1112]
**OGCS Version**: v2.8.5
**Installed or Portable**: tested with both Installed and Portable

**Problem Description**  
Whenever I open the application the splash screen displays and then disappear forever.

**Steps to Reproduce the Issue**  
1. Open the Outlook google Calendar Sync app, Outlook is auto started
2. The splash screen displays for a while and then the whole app disappears.
3. I opened Task Manager and the app is still there. It looks like that only the GUI is crashed. However, the synchronization doesn't work anymore. So, for me the whole app is crashed.

**Any other information**  
I tried with both installed and Portable versions. I tried to start Outlook first and then this app. I tried to start the app with Admin right. Non of these tries works.
The [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5472583/OGcalsync.log) file is attached. 
I use Outlook 2016.
**NOTE:** no issue happens when I select to synch with default calendar. It only happens when I select a shared calendar to sync.

**Comment by phw198** [comment]
Looks like the alternative mailbox account became unavailable halfway through a sync, and any subsequent reconnects to the public folder just results in `The RPC server is unavailable.`. I would expect accessing items directly in the Outlook account to not really be functioning properly either?

Has there been any change/improvement since you reported this issue?

**Comment by phanvuliem** [comment]
FYI, The error only happens when I try to select the shared calendar. If I select the "Default mailbox" or "Alternative mail box" then everything is fine. I workaround by using the "Alternative mailbox" feature.
About the accessing mail box in Outlook account: everything is fine for the shared mail box, I can access it normally without any lag or issue.

**Comment by phw198** [comment]
If you have a workaround, then might just have to go with that. I don't have any public folders I can test with and the error message is related to the server not communicating mid-sync - I've not heard anyone else report this, though not sure how many users work with public folder mailboxes.
