### ISSUE TITLE
Option to Break Recurrence / Sync recurring series as single items

### ISSUE THREAD

**Issue by doubled136** [phw198/OutlookGoogleCalendarSync#1114]
It would be nice to have an option (toggle box) to break recurrence of an event, as I'm only interested in day-to-day updates for syncing, rather than keeping a series active.

I think I'm having an issue with a combination of programs where sync modification date does not override creation date in finding daylight savings offsets.

**Comment by phw198** [comment]
Unfortunately, I won't be accepting this enhancement request - it would be a significant amount of work to treat recurring series as individual items for very limited user base.

> I think I'm having an issue with a combination of programs where sync modification date does not override creation date in finding daylight savings offsets.

I don't really understand this? A sync can and should never override a creation date and creation date doesn't impact on DST offsets anyway.

**Comment by doubled136** [comment]
Thank you again for your response.  Greatly appreciated!
