### ISSUE TITLE
Daylight savings mis-sync for subset of meetings

### ISSUE THREAD

**Issue by rippey154** [phw198/OutlookGoogleCalendarSync#1115]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>
After daylight savings in the US this past weekend, two of my recurring meetings show up in the wrong hour. These two were created by someone else (though, other recurring meetings created by someone else did successfully reflect the correct timezone).

**Steps to Reproduce the Issue**  
1. \<Update>
1. Wake up on Monday of last week and see that not all meetings are refreshed to new time.
2. Note that a full resync (shift-sync) did not affect the problem
3. Restarting computer, restarting Outlook, restarting Sync did not affect the problem.
Log file attached from today when I did a full resync (shift-sync)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5512224/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by rippey154** [comment]
Thank you for your reply. As I use this for work and productive purposes, I am risk adverse and wish to avoid using an alpha version.  

Can you give any best guess (no promise) of when the alpha will be promoted to at least beta, or better yet to productive version?

Note that I did apply my OC.calcsync.log - can you please let me know if I did so incorrectly?

Many thanks for your efforts (to me and for everyone)!

**Comment by phw198** [comment]
I'm probably overly cautious with my release names - alphas are pretty stable and released every month or two, betas are closer to annual. No immediate plans for the next beta, could be 6 months or so...
