### ISSUE TITLE
No longer updates Google Calendar

### ISSUE THREAD

**Issue by railfanron** [phw198/OutlookGoogleCalendarSync#1116]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

Have used OGCS for years. All of a sudden this past month it no longer updates the Google Calendar when I sync from Outlook 2007. 

Added a test appointment for November 16th for illustration. 
![Outlook 1](https://user-images.githubusercontent.com/36484311/98579406-7a196480-2273-11eb-80eb-c92888882eec.JPG)
Ran OGCS
![Sync 1](https://user-images.githubusercontent.com/36484311/98579488-94534280-2273-11eb-954d-ca4b317f521d.JPG)
OGCS Finished
![Sync 2](https://user-images.githubusercontent.com/36484311/98579534-a46b2200-2273-11eb-9712-033888a0b2ea.JPG)
Google Calendar did not update.
![Google 2](https://user-images.githubusercontent.com/36484311/98579675-d8dede00-2273-11eb-8faf-a159b6e96918.JPG)

log file
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5512505/OGcalsync.log)

Running version 2.8.4.0

Stumped
Ron Butts

**Comment by phw198** [comment]
Your logfile doesn't include your configuration settings (either load OGCS from afresh and then perform a sync, or click `Save` under settings to log them).....but the following line looks pretty suspicious:
> 146 Outlook items excluded due to active category filter.

**Comment by railfanron** [comment]
OGCS was/is configured to save. I have tinkered with all of the settings and seemed to have OGCS working properly now. Sync options are now set for date range 0 days in the past, 30 days in the future, scheduled every 120 hours, and Push Outlook changes immediately. Previous setting was 180 days in the future. 

For the several days I was tinkering with OGCS, I manually entered new entries into Google Calendar at the same time I added them to Outlook 2007. When I got OGCS to work, I found it duplicated the entries I had made in the Google Calendar. Is this normal?

Thanks for looking into this for me.
Ron

**Comment by phw198** [comment]
Again, depends entirely on your settings - I would expect "duplicates" if you had "Merge items" checked, yes.

**Comment by ChrisDodd99** [comment]
I also have a new copy of OGCS which appears not to sync properly. I attach the info below
![image](https://user-images.githubusercontent.com/75809179/101821574-0bece980-3b20-11eb-9d96-0d12e4596926.png)
![image](https://user-images.githubusercontent.com/75809179/101821616-1b6c3280-3b20-11eb-9406-b0949edc9082.png)
and yet here are the two calendars
![image](https://user-images.githubusercontent.com/75809179/101821699-3b035b00-3b20-11eb-9633-4cd9fb822c52.png)

**Comment by phw198** [comment]
Your logfile is much more important than screenshots - I cannot begin troubleshooting without knowing how you've configured OGCS. You also need to be using the latest alpha release of OGCS before reporting issues.

**Comment by railfanron** [comment]
After reinstalling OGCS and a little tinkering, I have gotten OGCS to work properly! The issue has been resolved. Thanks for following up.
