### ISSUE TITLE
Hot Fixes version numbers

### ISSUE THREAD

**Issue by tnjgb** [phw198/OutlookGoogleCalendarSync#1117]
Are Hot Fixes all incremental or issue specific? As in I see hot fixes are issued with version numbers such as 2.8.5.1 which fixes issue A and 2.8.5.2 which fixes issue B, does 2.8.5.2 also have the 2.8.5.1 issue A fix in it?

**Comment by kwagner115** [comment]
Here is the feedback I received back in June 2020 on the same question: 

_**No, not cumulative (unless necessary); they're built on top of the latest alpha release, eg 2.8.3.0, which is what the issues should be reported against (though I accepted this issue against 2.8.0 as I knew it wasn't fixed or affected by subsequent releases).**_

**Comment by phw198** [comment]
I have now [added this detail](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) to the wiki.
