### ISSUE TITLE
Out of Memory Close Some Windows

### ISSUE THREAD

**Issue by marshak59** [phw198/OutlookGoogleCalendarSync#1119]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.5.0
**Edition**: Installed   
**Sync Direction**: O<->G

**Bug Description**  
I keep getting sync error messages that Out of memory of system resources, close some windows or programs and try again.
**Steps to Reproduce the Issue**  

**Any other information**  
Any additional information that may help troubleshoot the issue.  

:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Are you running an Outlook Exchange account? Are you using cached mode? Without cached mode you might just have to reduce the sync window in OGCS...

**Comment by phw198** [comment]
Similar to #1143.
