### ISSUE TITLE
Calender quota problem NOT solved in 2.8.5.0

### ISSUE THREAD

**Issue by Ernst2020** [phw198/OutlookGoogleCalendarSync#1120]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

v2.8.5.0 alpha  
Portable
In the list of issues it was mentioned that in 2.8.5.0 the problem with calendar quota would be solved. It isn't.

See screenshot

![Dump](https://user-images.githubusercontent.com/70779597/99107467-32356d00-25e6-11eb-8472-fd402c893f90.png)

**Comment by phw198** [comment]
Well it can't magic new quota from Google, no. What it should be doing is handling the error neatly, but as you have evidenced, it is attempting to delay the next sync until after new quota is available...and then overrides that and sets the next sync for 15 minutes time :roll_eyes: 

:package: This should now be resolved with [hotfix v2.8.5.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5580420/v2.8.5.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by Ernst2020** [comment]
Installed the hotfix 2.8.5.7 and will observe the behaviour for a while. Will update here my findings.

**Comment by Ernst2020** [comment]
This morning, same thing with 2.8.5.7, it seems it now waits for 8 hours to get quota?:

![image](https://user-images.githubusercontent.com/70779597/100121529-421c3f00-2e79-11eb-83e1-1601125d1099.png)

And a dialogue box asking me whether I would like to try again, Yes / No:

![image](https://user-images.githubusercontent.com/70779597/100120866-bb676200-2e78-11eb-8dff-2e8e7c7b35b0.png)

Is it possible to make it retry automatically, i.e. not showing the dialogue box?

(Could only make a screendump for the first picture above by clicking **No** in the second picture, before that the next scheduled sync was 8 hours after the sync that failed... but the dialogue box pops up so the retry is never done until I press Yes, which is beyond the point of this retry.)

**Comment by phw198** [comment]
OK, that's still not working how I would expect.

:spiral_notepad: Please could you provide your `OGcalsync.log.2020.11.24` file for the 24-Nov ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by phw198** [comment]
Think I've identified the issue without the log file actually. 

:package: Please try [hotfix v2.8.5.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5611075/v2.8.5.9.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes again...

**Comment by Ernst2020** [comment]
Just installed v2.8.5.9 and will see what happens. Attached the log of November 24th.
[OGcalsync.log.2020-11-24.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5625150/OGcalsync.log.2020-11-24.log)

**Comment by Ernst2020** [comment]
Nope. Now it just stops when the quota are exhaused, see screenshot. Quota depleted, next sync was scheduled 8 hours later but never started. Also attached the log of December 3rd, strangely enough there is a log of December 4th although the screen suggests a sync was not performed that day.
![Screendump](https://user-images.githubusercontent.com/70779597/101260816-c355ba80-3732-11eb-8dd5-e29dc280c707.jpg)

[OGcalsync.log.2020-12-03.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/5647704/OGcalsync.log.2020-12-03.txt)
[OGcalsync.log.2020-12-04.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/5647705/OGcalsync.log.2020-12-04.txt)

Update; I pressed "Sync" and then the screen updated with the error information of December 3rd, see:

![Screendump2](https://user-images.githubusercontent.com/70779597/101260918-86d68e80-3733-11eb-99fb-8b1755b0ebf7.jpg)

And after this succesfull sync, see top right; next sync scheduled December 3rd? Although I just synced on December 5th? The latest fixes appear to make things worse.

Had to restart OGCS, after the restart it shows next sync December 5th, indeed 1 hour (as configured) in the future.

**Comment by Ernst2020** [comment]
Same yesterday, and it does not continue.... i.e. all syncing halted until "Start Sync" is clicked.

It is now December 10th, just saw this:

![Screen](https://user-images.githubusercontent.com/70779597/101643495-7cb6d780-3a34-11eb-9963-1a1afef0d8fa.jpg)

**Comment by phw198** [comment]
This took quite a bit of reworking the scheduling mechanism, so if you are able to do some extra tests around automated syncs as well as handling the quota issue properly, it'd be appreciated.

:package: Anyway, please try [v2.8.5.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5744812/v2.8.5.13.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes.

**Comment by Ernst2020** [comment]
Paul,

Thanks. Installed 2.8.5.13 and will let it run for a week, the previous version did not bomb last week but could be due to a lot less sync traffic due to the holidays.

Will keep you updated.

Regards,

Ernst

**Comment by phw198** [comment]
Thanks - yes, traffic over the holidays will have dropped significantly. Unfortunately, I'll not be surprised with some quota issues at the start of January as everyone attempts to organise their lives/calendars :wink:  

Hopefully, shouldn't be too bad though...

**Comment by Ernst2020** [comment]
Would it help to do a funding round or something to raise money to allow you to raise quota?

Ernst

**Comment by Ernst2020** [comment]
2.8.5.13 has been running for several days. No hangups in syncs. But it seems that the message about depleted quota is not removed when a subsequent sync is successful, just saw this:

![Screendump](https://user-images.githubusercontent.com/70779597/103935245-99732780-5126-11eb-9594-8615b248f9af.jpg)

It went away after a manual sync.

**Comment by phw198** [comment]
Thanks for the feedback @Ernst2020 

:package: [Hotfix v2.8.5.17.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5792952/v2.8.5.17.zip) has a minor change on the yellow note, as you've reported ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by Ernst2020** [comment]
Thanks! Installed 2.8.5.17 and will give feedback in a week or so.

**Comment by Ernst2020** [comment]
Since 2.8.5.17 no problems anymore. Thanks!
