### ISSUE TITLE
Color index is off by 1

### ISSUE THREAD

**Issue by tcs63f** [phw198/OutlookGoogleCalendarSync#1121]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.5.0
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
Effective color is one "below" selected color: sage gives grape... graphite gives blueberry and tomato produces index-errror.

**Steps to Reproduce the Issue**  
1. Goto Settings->Sync Options->How->Set colour
2. Select color, sync and look at the result in google calendar.

**Any other information**  
![FarbFehler](https://user-images.githubusercontent.com/74457867/99148337-6f9e0700-2687-11eb-8660-bbb150b7a893.jpg)

**Comment by phw198** [comment]
You're missing a "Calendar Default" option at the top - does this ever display for you??

If not, I will likely need to see your OGcalsync.log file to see where this is going wrong for you...

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.8.5.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5610719/v2.8.5.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by tcs63f** [comment]
It is :-)

"Calendar Default" is now shown an works as expected.
"Tomato" can be selected without error an makes realy red items in 
google calendar.
Values between "Default" and "Tomato" seem to work; I tried "Basil" and 
got what I expected... a darker green.

Thanks!



Am 28.11.2020 um 15:17 schrieb Paul Woolcock:
