### ISSUE TITLE
Deleting new event

### ISSUE THREAD

**Issue by caporalx** [phw198/OutlookGoogleCalendarSync#1128]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8 
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
I used to leave automatically deletion of events.
Then, one outlook meeting disappeared from my calendar. I check the trash and it was there.
I restored and the sync deleted again.
I changed to confirm deletion. Removed the application and settings and put all bak on again.
Still, the application always try to delete that meeting.

**Steps to Reproduce the Issue**  
Sync. And it will delete that particular meeting. All other meetings are fine.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5607973/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Read the [wiki advice](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) on this and see if that helps resolve it.

**Comment by amig500** [comment]
Have the same issue here using 2.8.0.0

**Comment by phw198** [comment]
@amig500 and the same advice would still stand.

**Comment by amig500** [comment]
The suggested fix does not work.

**Comment by amig500** [comment]
True. I upgraded to 2.8.5.0 and still have the issue. Sorry I did not say it.
