### ISSUE TITLE
telemetry disabled but still getting warning

### ISSUE THREAD

**Issue by gpion** [phw198/OutlookGoogleCalendarSync#1135]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)

Done

> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

I can't, private data in that file

**OGCS Version**: v2.8.5.0
**Edition**:  Portable  
**Sync Direction**:  O->G 

**Bug Description**  
Telemetry is disabled but still getting the warning

**Steps to Reproduce the Issue**  
Each time at app start

**Any other information**  
Screenshots:
![image](https://user-images.githubusercontent.com/2971216/101327386-e38a9400-386e-11eb-816e-41c8e54947c6.png)

![image](https://user-images.githubusercontent.com/2971216/101327427-f43b0a00-386e-11eb-9fc3-82bac5ed15bd.png)

**Comment by kwagner115** [comment]
I too have the same issue on v2.8.5

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.8.5.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5721230/v2.8.5.12.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by gpion** [comment]
> Please let me know how it goes.

So far so good
