### ISSUE TITLE
Getting Outlook meeting attendee responses in Gmail

### ISSUE THREAD

**Issue by voodoochild1979** [phw198/OutlookGoogleCalendarSync#1138]
Hi there, 

I'm using OGCS on my laptop to have one-way syncing of my work Outlook calendar in my Google Calendar (O->G). Everything seems to work fine but I'm 'randomly' getting attendee responses (of Outlook meetings) emailed to my gmail, for meetings that I am NOT the chair of. I've attached an image of one of those emails. You'll see in that image that in the 'Google version' of this Outlook meeting, it now lists me (a*****b@gmail.com) as the organizer, which is not the case. The Outlook meeting was sent by someone else and I accepted it in Outlook (as I normally would).

Note that I am NOT getting those email responses in Outlook, and these responses seem to usually be for meetings with many invitees, and also these are not meetings for which I am the chair but rather just one of the participants.

Hopefully this was clear! 

I've attached a zip of the log files for the last 10 days (as long as I've been using OGCS) as I'm not sure if this issue would show up in just yesterday's log file, but this is not an issue I am able to reproduce as it seems to happen randomly and I can't connect it to any specific actions happening on those meetings in Outlook...[Outlook Google Calendar Sync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5675519/Outlook.Google.Calendar.Sync.zip)

Thanks for your help!

![Screenshot 2020-12-10 154924](https://user-images.githubusercontent.com/75810557/101828269-4f832b80-3aff-11eb-9cb3-00c785d288e8.png)

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg

)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log.2020-12-09.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5675494/OGcalsync.log.2020-12-09.log)

**Comment by phw198** [comment]
Well [known and documented Google bug](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google).
