### ISSUE TITLE
Sincronization error Google-->Outlook

### ISSUE THREAD

**Issue by Albertozanni** [phw198/OutlookGoogleCalendarSync#1139]
An error occurs. I am looking for a nice person to help me solve the problem, I am attaching photos and log files, Thanks thanks a lot to everyone:
"An error is thrown You do not have the necessary permission to create an entry in this folder. To check the permissions you have on the folder, right-click the folder, then click Properties. To change permissions, contact the owner of the folder or the administrator.

version 2.8.0.0
Running From C: \ Users \ Alberto Zanni \ AppData \ Local \ OutlookGoogleCalendarSync \ app-2.8.0-beta \ OutlookGoogleCalendarSync.exe
Config In C: \ Users \ Alberto Zanni \ AppData \ Roaming \ Outlook Google Calendar Sync \ settings.xml
Subscription N / A
Timezone DB 2020d
![image](https://user-images.githubusercontent.com/76038240/102317336-a792b580-3f77-11eb-8fa6-c8ad64284366.png)

This is file log:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5700985/OGcalsync.log)

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Hi @Albertozanni, I'm not sure what more I can add to the message you have already supplied - you need to make sure you have enough permissions to create new items in the Outlook calendar (folder) you are trying to sync to.

> You do not have the necessary permission to create an entry in this folder. To check the permissions you have on the folder, right-click the folder, then click Properties. To change permissions, contact the owner of the folder or the administrator.
