### ISSUE TITLE
OGCS Setup File was quarantined by my Antivirus (BitDefender) because of infection

### ISSUE THREAD

**Issue by mjlipton** [phw198/OutlookGoogleCalendarSync#1141]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0

**Bug Description**  
Here is message from AV software:

Infected file detected
40 minutes ago

Feature:
Antivirus

The file C:\Users\mjlip\Downloads\OGSC Setup.exe is infected with Gen:Variant.Bulz.254207 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is cle

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Thanks @mjlipton - if you time to assist, [see the wiki for reporting false positives](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#anti-virus-false-positives) to your AV provider.
