### ISSUE TITLE
3 Appointments from Outlook not added to Google Calendar Despite Two Way Sync

### ISSUE THREAD

**Issue by Hank61** [phw198/OutlookGoogleCalendarSync#1142]
When I run a manual two way sync, 3 appointments aren't transferred from my Outlook 2016 calendar to Google.  For some reason OGCS, prompts me whether I want to delete each of these appointments (not sure why) and I select "no".  However when I open my Google Calendar, they're missing.  The appointments in question are :
12/6/20 10:30 am Start NO2, Lemon Balm, Theanine
12/23/2020 11:00 AM Follow-up w A&E Cage company
1/7/2021  10:00 AM Take Backups to Bank

[Calendar Sync Print Screen.docx](https://github.com/phw198/OutlookGoogleCalendarSync/files/5720021/Calendar.Sync.Print.Screen.docx)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5720024/OGcalsync.log)

**Comment by phw198** [comment]
See if [this helps](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync)?

**Comment by Hank61** [comment]
Hello Paul,

The first procedure listed did the trick. This has been an ongoing nuisance with many of my Outlook appointments not transferring to google calendar, so it's a relief knowing how to fix it. You're the man!!! 

Many thanks.

Jeff
