### ISSUE TITLE
After resume from sleep OGCS attempts sync before network becomes available.

### ISSUE THREAD

**Issue by kuraikaze** [phw198/OutlookGoogleCalendarSync#1144]
**OGCS Version**: v2.8.5.0  
**Edition**: Installed  
**Sync Direction**:  O<->G

**Bug Description**  
After PC resumes from S3 sleep or hibernation OGCS attempts a sync cycle immediately, frequently before the network stack has completed re-initialisation, leading to a connection failure which generates the error popup.

**Steps to Reproduce the Issue**  
1. Sleep/hibernate PC
2. Resume PC

**Any other information**  
Error occurs at 2020-12-26 14:36:34 in log.

This behaviour was not apparent with v2.7 which I was using previously.

:paperclip: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5743234/OGcalsync.log)

**Comment by phw198** [comment]
This has been covered on https://github.com/phw198/OutlookGoogleCalendarSync/issues/886#issuecomment-748627877 which also has an unconfirmed hotfix, if you would like to test it.

**Comment by kuraikaze** [comment]
No re-occurrence since hotfix v2.8.5.11 applied as per  https://github.com/phw198/OutlookGoogleCalendarSync/issues/886#issuecomment-748627877
It was intermittent rather than consistently reproducible, but I've slept/resumed the machine half a dozen times now without problem so it looks like that did the job.
