### ISSUE TITLE
Synchronization failed "Outlook ← Google"

### ISSUE THREAD

**Issue by Marjdje** [phw198/OutlookGoogleCalendarSync#1146]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.0.0  
**Edition**: Installed
**Sync Direction**: G->O

**Bug Description**  
During the funal phase of sync I've received this messagge: "Unable to update existing entries in the Outlook calendar. Metodo non supportato dall'oggetto. Operation aborted after 1 failed attempts!" [Code: 0x8A420009;-1975386103].
I have been using this program since vs. 2.7 and I have never had any problems until now.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5750111/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
It looks like there may be an issue with `07/11/2020 19:00 (R) => "Inizio Backup Settimanale Nas [Collegare HD Esterno]"` and the category "Teal" (or lack of it).

But, you need to reproduce this on the latest alpha before further investigation can be done.

**Comment by Marjdje** [comment]
Hi phw198,
Yesterday I updated the stable version from 2.8.0.0 to alpha 2.8.5.0 without changing anything and the problem solved.
Thanks for help me!
