### ISSUE TITLE
Syncing more oulook calendars at once

### ISSUE THREAD

**Issue by svenvonk** [phw198/OutlookGoogleCalendarSync#1147]
I would like to sync more than one Outlook Calendar to Google Calendar.
Would preferably also sync to more than one Google Calendar if possible.

Kind regards 
Sven Vonk
the Netherlands

**Comment by phw198** [comment]
See https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars

Duplicate #165
