### ISSUE TITLE
Retrieve Calendars Does Not Return/Display All Available Calendars

### ISSUE THREAD

**Issue by burneremail** [phw198/OutlookGoogleCalendarSync#1151]
Greetings, 

I have tried this on 2.8.0 and 2.8.5.

When I connect to my Google Calendar/account, only a subset of the calendars I'm subscribed to are showing up in the list of available calendars to select.  More frustratingly, my own calendar isn't available to select nor are any of my other calendars listed under "my calendars".  

Additionally, of the calendars that do show as available to select, it's not 100% either as several are missing.

I have checked that the "Show calendar info in other Google apps, limited by access permissions" option for my calendar is selected.

I'm assuming that it's something with my account perhaps?  Or maybe a rogue bug, but any advice here would be greatly appreciated.

**Comment by burneremail** [comment]
Update: After a bit of troubleshooting, I think I found the real bug.

In my Google Calendar, I'm subscribed to 50+ different calendars.  It seems that the dropdown list (or the query behind it) is limiting the number of displayed calendars available to 29 or 30 total.  I don't know how the program is building or limiting the query result, but it's definitely that.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.8.5.19.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5825094/v2.8.5.19.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by phw198** [comment]
I'm going to roll this change into the next v2.8.6 alpha release anyway.

**Comment by burneremail** [comment]
Apologies as I've been away the last week, but I'll validate for you Monday or Tuesday. Thanks for addressing this one. 

Out of curiosity, what is the sort order on the received calendars?

**Comment by phw198** [comment]
@burneremail Thanks (and v2.8.6 just released). Sort order is after retrieving from Google is:-

1. Owner's primary calendar
1. Owners other calendars
1. Write access to other's calendars
1. Read access to other's calendars
1. Free/Busy access to other's calendars

**Comment by burneremail** [comment]
Fix confirmed; nice job!
