### ISSUE TITLE
OGS will not start anymore

### ISSUE THREAD

**Issue by JoopHofland** [phw198/OutlookGoogleCalendarSync#1152]
When starting former version 2.7.x on laptop: splashscreen is showed, release notes online open
Deleted progrma en downloaded setup.exe
When installing version 2.8.0: beta splashscreen is showed, release notes online open
When installing version 2.8.5: alpha only animated OGS logo is showed

Program terminated after 30 seconds (error popup)

Was working fine untill a few days ago... :(

Pls advice

**Comment by phw198** [comment]
Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

Let me know if you cannot locate this file.

**Comment by JoopHofland** [comment]
I got working again! Thanks for your support!

Op za 16 jan. 2021 20:51 schreef Paul Woolcock <notifications@github.com>:
