### ISSUE TITLE
Confirm Mass Deletion Prompt

### ISSUE THREAD

**Issue by opjullee** [phw198/OutlookGoogleCalendarSync#1153]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.0 and v2.8.5  
**Edition**: Installed   
**Sync Direction**: O->G

**Bug Description**  
We just started using the software and there are 12 calendar entries to sync.  Confirm Deletions checkbox is unchecked but still being prompted to confirm. 

![confirm](https://user-images.githubusercontent.com/23486775/104648810-8ef5e800-5668-11eb-9890-ba1e826dac97.jpg)

**Steps to Reproduce the Issue**  
It happens every time our scheduled sync starts (every 15 minutes)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5816982/OGcalsync.log)

**Comment by phw198** [comment]
Expected behaviour. Either sync to an empty Google calendar, or turn on merging of calendars in the settings.
