### ISSUE TITLE
Time Travel Breaks OGCS

### ISSUE THREAD

**Issue by quarteringsea** [phw198/OutlookGoogleCalendarSync#1154]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.5
**Edition**: Installed 
**Sync Direction**: G->O / **O->G** / O<->G

**Bug Description**  
This is a very stupid problem of my own making.

For reasons unrelated to OGCS I had to manually set the clock on my computer to the future today. Since returning to the present, OGCS unexpectedly terminates on launch with an error. It looks like the interval between syncs (measured in seconds?) cannot be a negative number, which is too bad if you let it sync while your computer is set to a date later than today.

**Steps to Reproduce the Issue**  
1. Manually set the date/time on your computer to some time in the future.
2. Allow OGCS to sync (or manually force a sync)
3. Set the date/time back to the present. 
4. ![image](https://user-images.githubusercontent.com/69681781/104787116-c0e87680-575c-11eb-9710-0c25ff730073.png)

**Any other information**  
Possibly related, my OGcalsync.log file is nowhere to be found in Appdata.

**Comment by phw198** [comment]
Slightly strange one, but thanks for reporting it!

:package: This should now be resolved with [hotfix v2.8.5.18.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5825035/v2.8.5.18.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

You'll get a massive delay for the next sync, but you should then be able to edit the sync interval to update it again.
