### ISSUE TITLE
I am getting following error. Updated event failed to save. Cannot specify both default reminders and overrides at the same time. 

### ISSUE THREAD

**Issue by panzner** [phw198/OutlookGoogleCalendarSync#1156]
I have version 2.8.5.11; it is Installed and is O<->G.

I am getting the following error for roughly 7 entries when the program syncs:

Updated event failed to save.
Cannot specify both default reminders and overrides at the same time. [400=BadRequest]

Each time, it is accompanied by the following error popup:

[deleted]

Updated Google event failed to save. Continue with synchronisation?
I am forced to answer "yes" or "no" before it proceeds.

Any suggestions?

I have attached the log file.

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Configuration to replicate issue:
* Set Google to create a default email notification for the calendar, no popup reminders
* Set OGCS to sync reminders and use Google default reminders
* Create Outlook item with no reminders
* Sync to Outlook
* Make a change in Outlook and resync

:package: This should now be resolved with [hotfix v2.8.5.20.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5860692/v2.8.5.20.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by panzner** [comment]
That worked! Thank you.
