### ISSUE TITLE
New Outlook calendar entries with MS Teams meeting info are deleted during the sync process

### ISSUE THREAD

**Issue by Todd-Mc** [phw198/OutlookGoogleCalendarSync#1158]
**OGCS Version**: v2.8.5.0
**Edition**: Installed  
**Sync Direction**:  O<->G

**Bug Description**  
When I create a calendar entry in Outlook, then add in a MS teams meeting, add attendees (either internal or external) and send it out, the entry resides on my calendar briefly until OGCS performs a sync (either automatic or manual), at which time, the calendar entry gets deleted.

**Steps to Reproduce the Issue**  
1. Go to the calendar in Outlook (our company uses our Outlook on an Exchange server)
2. Double-Click on a desired time slot to bring up a calendar entry/appointment
3. Populate the title, start & end times, and any text wanted in the entry
4. Click on the Teams Meeting icon which inserts the MS Teams meeting link and info
5. Add attendees to the required and optional fields (location turns to Microsoft Teams Meeting automatically)
6. Click on Send....and the meeting appears on the calendar
7. At the next sync with OGCS, the calendar entry gets deleted by OGCS.  If I turn on confirm deletions in OGCS, it will ask me if I want to delete the entry, though I typically default to leaving these check boxes unchecked.  If I choose not to delete the entry, it will continue to ask me each time it syncs.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
1.  If I am creating an appointment, with no MS Teams meeting, then there is no issue with the sync and the calendar appointment remains in place.
2.  If there are calendar entries created by others and sent to me as an invitee, there are no problems with that syncing, even when there is a MS Teams meeting included
3. I have noticed this for several months, though, it didn't bother me too much, however, I am creating a lot of meetings now, and it's more annoying.
4. I can search Outlook for the calendar entry, and it shows moved to the deleted folder
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Does the Outlook Teams meeting actually get synced to Google before OGCS tried to delete it in Outlook?

If so, I think this may be a duplicate of #1123 - worth upgrading to v2.8.6 now anyway and confirming if the issue persists.

**Comment by mtasseva** [comment]
I'm having the same problem with entries that involve Zoom meetings. I'm using v. 2.8.6.0. OGCS insists on deleting them. For a while I had the 'Disable delete' option on but it caused a different problem for me tracking what I need to do between my personal (Gmail) and professional (Outlook) life. So now the disable setting is off and the 'Confirm deletion' setting is on and the OGCS is constantly trying to delete Zoom meetings. If I'm not careful, it will delete a meeting

**Comment by Todd-Mc** [comment]
I was finally able to find the2.8.6, and this appears to have solved this issue for me.  I have created several calendar items, including with and with MS teams embements, and it appears that they are staying put and not deleting.

To answer your previous question, yes the event would show up in the Google calendar until it was deleted later, but for now, it appears to be working under the new version release.

Thanks for the help.

**Comment by phw198** [comment]
@mtasseva If new Zoom items you are creating whilst running v2.8.6 are getting deleted, would be worth raising a new issue to investigate this.
