### ISSUE TITLE
two way: not syncing back changes to outlook

### ISSUE THREAD

**Issue by jaguarman** [phw198/OutlookGoogleCalendarSync#1159]
----

**OGCS Version**: v2.8.6.0 (lastest alpha) 
**Installed or Portable**: Installed

**Problem Description**  
Thank you. This is already great and nearly insane!
outlook (company exchange) to google -> perfect!
two way: not yet perfect:
does not sync back to outlook

**Steps to Reproduce the Issue**  
1) create calendar entry in Outlook
2) sync 2-way
3) entry now exists in google-calendar (name is: oc-outlook)
4) change time of that entry in google calendar
5) sync again
6) does not sync to outlook

**Any other information**  
\<Update here>
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5892774/OGcalsync.log)

**Comment by phw198** [comment]
I've followed your steps and OGCS sync the changes as would be expected.

What is the subject and time of the appointment you were syncing? Please can you 
* create a new test item
* turn on "Create CSVs" under Settings > Application Behaviour > Logging
* run through your steps to reproduce the issue
* zip up your log file along with the CSV files and upload that
* let me know the name and time of that test item

Thanks

**Comment by jaguarman** [comment]
Sorry Paul, didn't see your reply until today. Please excuse that.
I will follow your instructions and send the report within one week.
Best regards
Peter

Paul Woolcock ***@***.***> schrieb am Sa., 30. Jan. 2021,
22:55:
