### ISSUE TITLE
Approval error 401 Error: invalid_client Client missing a project id.

### ISSUE THREAD

**Issue by hanpedro** [phw198/OutlookGoogleCalendarSync#1160]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.0 beta  
**Edition**: Installed  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
After installing OGCS, I got this message when click "Settings" - "Google" - "Retrieve Calendars".

**Steps to Reproduce the Issue**  
1. click "Settings" - "Google" - "Retrieve Calendars".

2. The message printed on Chrome.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
~~[OGcalsync.log]()~~

**Comment by phw198** [comment]
You appear to be attempting to set up your own API keys, but are not putting in the right information at all (I've removed your logfile as it held sensitive information).

I am unable to provide support on creating your own API keys, but you would [start here](https://console.developers.google.com/apis/credentials) and there is plenty of support documentation provided by Google.
