### ISSUE TITLE
2.8.6: Syncs every minute after manual sync when no sync interval set

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1161]
If the sync interval is zero, after performing a manual sync another sync will be scheduled in one minute's time. This will continue repeatedly.

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.8.6.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5898764/v2.8.6.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

If anyone is affected by this and tests it, let me know how it goes.

**Comment by rpaulbeck** [comment]
In case you were still needing confirmation.  I can confirm that v2.8.6.1 does fix this issue.  Have my Sync options set to schedule every zero hours and after running manual sync, I have no scheduled next sync (says Inactive).  Thanks.
