### ISSUE TITLE
Sync single occurence instead of series

### ISSUE THREAD

**Issue by euinor** [phw198/OutlookGoogleCalendarSync#1162]
**Is your feature request related to a problem? Please describe.**
My use case for outlook syncing is to manage my daily agenda. I don't need to see events further in the future than 1 day. So when syncing series it would be great to sync only the single occurrence each time, future events do not need to be synced.
Also I would not expect to see events further ahead than the number of days in the future than is set in syncing date range.

**Describe the solution you'd like**
An option to treat events that are a part of a series as a single event and to enforce syncing date range (so no events outside the period are created).

**Comment by phw198** [comment]
Hi @euinor 

Unfortunately, this is a duplicate of #1114 which I declined. IMO it's a retrograde step and a huge amount of work for an extremely small user-base that would use it.

**Comment by euinor** [comment]
Ok, thanks for confirming!
