### ISSUE TITLE
After exhausted quota the yellow message to that effect is not erased after a subsequent succesfull sync 

### ISSUE THREAD

**Issue by Ernst2020** [phw198/OutlookGoogleCalendarSync#1163]
Subject says all I guess.

See screenshot. Version 2.8.5.17.

![screendump](https://user-images.githubusercontent.com/70779597/106772776-a0fff080-6640-11eb-9f91-0706b21cab06.jpg)

**Comment by phw198** [comment]
Do you have the logfile for when the sync ran and the quota was exhausted? I'm concerned that the calculation for when to run the next sync is wrong - 23 hours to delay the sync by doesn't seem right.

Do you know when the next scheduled sync was due to run? Was it 4th Feb at 08:00? Did you have to run it manually for the above screenshot.

FWIW. the yellow info should remain visible for some hours for informational purposes.

**Comment by Ernst2020** [comment]
Paul,

See attached log file, from the exhausted resources are logged from"2021-02-03 08:25:52,389" onwards... it then retries every 15 minutes and then succeeds at 09:11.

These times are local times Amsterdam/Bruxelles timezone (GMT+1).

So the text in the yellow block about a delay of 23 hours is wrong and the yellow block does not disappear at a successfull sync.

For the screenshot in the Github issue I did a manual sync to see whether that would make the yellow block disappear.

Hope this helps.

Regards,

Ernst

**Comment by phw198** [comment]
:package: I think should now be resolved with [hotfix v2.8.6.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5940518/v2.8.6.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by Ernst2020** [comment]
Nope. Not solved in v2.8.6.2. See screenshot.
![Screendump](https://user-images.githubusercontent.com/70779597/107392368-e6696580-6af9-11eb-8db3-07d47f454aad.jpg)

**Comment by phw198** [comment]
:package: Please try again with [v2.8.6.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5976399/v2.8.6.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes!

**Comment by Ernst2020** [comment]
Nope. Also with 2.8.6.3 the yellow textblock remains even after a succesfull sync:

![Screendump](https://user-images.githubusercontent.com/70779597/108061626-e23ccb00-7058-11eb-8a25-0f57ebee5717.jpg)

**Comment by Ernst2020** [comment]
I don't think we are getting anywhere... with 2.8.6.3 this evening the modal dialogue box that the sync failed appeared again. With in the backgroung GoogleSync proudly telling the world that the sync was finished. Why does it then say that it failed?

**Comment by phw198** [comment]
> Also with 2.8.6.3 the yellow textblock remains even after a succesfull sync:

Yes, it should display the yellow box you have on your screen shot for the 3 hours following the first successful sync. With the information available I cannot tell if that had happened - can you confirm?

Re the modal dialogue box, do you have a log file for that time period? I cannot troubleshoot without it.

**Comment by Ernst2020** [comment]
Paul,

Let me observe a couple more days...

I had renamed previous versions of the executable and the pdb file so that I always could go back. Decided today to delete those but couldn't since 2 previous exe and pdb files were in use. Huh? Stopped 2.8.6.3 and still had 4 GoogleSync processes running... had to stop them using Task Manager.

Now 2.8.6.3 is running again. Don't know what made those exe and pdb files "stick". Just exiting those previous GoogleSync versions had apparantly not killed those...

Perhaps that explains all the weird behaviour. Give it a couple of days and see what happens.

**Comment by Ernst2020** [comment]
Paul,

Had 2.8.6.3 running for a day now without any ghosts from previous versions.

See screendump I just made; yellow warning about exhausted quota.

From the attached log file of today, it shows that quota exhausted at 05:00 and 08:59.

Then at 09:58 a sync is succesful, as well as every hour thereafter, but as the screendump shows, the yellow box remains.

I can't imagine that the yellow box must remain until eternity after successful syncs...

Regards,

Ernst

**Comment by Ernst2020** [comment]
Paul,

As said below, I clean restarted 2.8.6.3 yesterday, this evening I saw the following (see screendump)...

Attached the log file.

From (the "---" are mine to find the appropriate place) the logfile it shows that at 20:59 a sync was started but that the authentication failed. The sync at 21:59 (I have hourly syncs) was succesful.

Hope this helps to determine why syncs sometimes fail.

Regards,

Ernst


  ----- Original Message -----

**Comment by phw198** [comment]
:paperclips: Unfortunately, files and screenshots can't be attached to the ticket when replying by email - in future you need to log in to GitHub to upload files.

> Now 2.8.6.3 is running again. Don't know what made those exe and pdb files "stick". Just exiting those previous GoogleSync versions had apparantly not killed those...

Yep, there was another bug that stopped previous versions fully closing - should be fixed in v2.8.6.3 also.

> Then at 09:58 a sync is succesful, as well as every hour thereafter, but as the screendump shows, the yellow box remains.

OK, think I've found the issue - sorry this is taking so many attempts! Appreciate your perseverance :+1: 

:package: Please try with [hotfix v2.6.8.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6017829/v2.6.8.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by Ernst2020** [comment]
Will install 2.6.8.4 and let you know.

Also the sync failed appeared in 2.6.8.3, will post the dump/log to github.

**Comment by Ernst2020** [comment]
Paul,
 
Installed 2.8.6.3 yesterday, this evening I saw the following (see screendump)...

![Screendump](https://user-images.githubusercontent.com/70779597/108628181-ccb11200-7459-11eb-86a9-8f6a1f3db8ec.jpg)

[OGcalsync.log.2021-02-19.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/6017867/OGcalsync.log.2021-02-19.txt)

Attached the log file.
 
From (the "---" are mine to find the appropriate place) the logfile it shows that at 20:59 a sync was started but that the authentication failed. The sync at 21:59 (I have hourly syncs) was successful.
 
Hope this helps to determine why syncs sometimes fail.
 
Regards,
 
Ernst

**Comment by phw198** [comment]
Looks like after you started OGCS at 20:28 on 19-Feb, the next auto sync kicked in at 20:58 to which Google responded with an "unauthenticated" response - hence the failure popup. 

Then at 21:29 another scheduled sync kicked in - this is odd because you've only scheduled once per hour. I think this is before you spotted the multiple instances of OGCS running though, which likely accounts for both the authentication error.

Let me know if you see this behaviour again on v2.8.6.4...also looks like there have been a few quota issues over the last week - how did it go?

**Comment by Ernst2020** [comment]
Haven't seen any errors, yellow boxes this week. So all appears to be fine now.

Thanks.

**Comment by phw198** [comment]
> ...to which Google responded with an "unauthenticated" response - hence the failure popup.

I've raised #1184 for this issue.

**Comment by phw198** [comment]
@Ernst2020 Could you search your past log files for the following lines to check you have in fact encountered a quota issue on the latest hotfix:
> Showing quota exhausted advisory until
....
Quota exhausted advisory notice period ending.
...
Removing quota exhausted advisory notice.

If you can post those lines including the timestamps, it'd be appreciated.

**Comment by Ernst2020** [comment]
Yes, since 21/02, the date the last hotfix was installed, there have been logs with quota exhaust errors.

Is there a way to email them directly to you? I am a bit weary posting them on GitHub since there is some info in those log files that should not be shared with others.

**Comment by phw198** [comment]
I just meant posting those particular lines, so I can see the right things are happening at the right times?

**Comment by Ernst2020** [comment]
Here goes, part of the log of yesterday:

---

2021-03-02 09:55:59,746 INFO  1 OutlookGoogleCalendarSync.Console [282] -  Sync finished!
2021-03-02 09:55:59,823 DEBUG  37 OutlookGoogleCalendarSync.Forms.Main [668] -  Showing quota exhausted advisory until 3/2/2021 12:55:59

2021-03-02 12:56:01,343 DEBUG  37 OutlookGoogleCalendarSync.Forms.Main [673] -  Quota exhausted advisory notice period ending.
2021-03-02 12:56:01,346 DEBUG  37 OutlookGoogleCalendarSync.Forms.Main [657] -  Removing quota exhausted advisory notice.

---

Do you need more?

**Comment by phw198** [comment]
Perfect, that was just what I was hoping to see - thanks!

**Comment by Ernst2020** [comment]
Glad to have been of any help. And thanks for all your support.
