### ISSUE TITLE
FW: Delivery Status Notification (Failure)

### ISSUE THREAD

**Issue by mrdantzig** [phw198/OutlookGoogleCalendarSync#1167]
Hi

Whenever I send an update notice from my google calendar at my mobile phone, I receive and email message titled 'Delivery Status Notification (Failure)' as below. Seems OGCS is changing the email address to 'orginal adress.ocgs', e.g. 'hanra-81@mf.seegene.com' to 'hanra-81@mf.seegene.com.ogcs' as below. Pls let me know how to fix it.

주소를 찾을 수 없음                                  mf.seegene.com.ogcs       도메인을 찾지 못하여 hanra-81@mf.seegene.com.ogcs 주소로 메일을 전송하지 못했습니다. 오타나 불필요한 공백이       있는지 확인한 후 다시 시도하세요. | 주소를 찾을 수 없음                                  mf.seegene.com.ogcs       도메인을 찾지 못하여 hanra-81@mf.seegene.com.ogcs 주소로 메일을 전송하지 못했습니다. 오타나 불필요한 공백이       있는지 확인한 후 다시 시도하세요. | 주소를 찾을 수 없음 | mf.seegene.com.ogcs       도메인을 찾지 못하여 hanra-81@mf.seegene.com.ogcs 주소로 메일을 전송하지 못했습니다. 오타나 불필요한 공백이       있는지 확인한 후 다시 시도하세요.
-- | -- | -- | --
주소를 찾을 수 없음                                  mf.seegene.com.ogcs       도메인을 찾지 못하여 hanra-81@mf.seegene.com.ogcs 주소로 메일을 전송하지 못했습니다. 오타나 불필요한 공백이       있는지 확인한 후 다시 시도하세요. | 주소를 찾을 수 없음 | mf.seegene.com.ogcs       도메인을 찾지 못하여 hanra-81@mf.seegene.com.ogcs 주소로 메일을 전송하지 못했습니다. 오타나 불필요한 공백이       있는지 확인한 후 다시 시도하세요.
주소를 찾을 수 없음
mf.seegene.com.ogcs       도메인을 찾지 못하여 hanra-81@mf.seegene.com.ogcs 주소로 메일을 전송하지 못했습니다. 오타나 불필요한 공백이       있는지 확인한 후 다시 시도하세요.
응답은 다음과 같습니다.   DNS   Error: 3821430 DNS type 'mx' lookup of mf.seegene.com.ogcs responded with   code NXDOMAIN Domain name not found: mf.seegene.com.ogcs

**Comment by phw198** [comment]
Nothing really to fix unless you want Google to spam your meeting attendees. See wiki for [further details](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-am-i-getting-undeliverable-notifications-from-google-for-recipients-ogcs).

**Comment by mrdantzig** [comment]
Thanks Paul,

What I'm asking for is not to add '.ogcs' after the email addresses of the recipients. Is '.ocgs' attached by Google Calendar not by OCGS?
Please let me know how you can fix it. Otherwise, I will be receiving a bunch of bounced messages whenever I revise my schedule at Google Calendar. This is a serious issue and I expect you to provide a solution or workaround about this problem.

Thanks

**Comment by phw198** [comment]
Did you read the wiki information? Yes, OGCS adds the `.ogcs` to your attendees emails to _stop_ Google incorrectly emailing them whenever you make a change in Google web interface. Given OGCS is syncing these details from Outlook, attendees will be surprised/concerned to be getting meeting updates from Google.

Nevertheless, by all means you can turn this feature off by unchecking the "Cloak email in Google" under Settings > Sync Options > What. Then perform a full sync by pressing `Shift` when clicking `Sync` button.

**Comment by mrdantzig** [comment]
Thanks Paul

I’ve made it by setting ‘Cloak email in Google’ option as you’ve guided.
You may close this case.

Best Regards,
Stephen
