### ISSUE TITLE
Events are being marked for deletion when they shouldn't be

### ISSUE THREAD

**Issue by keegantgovender** [phw198/OutlookGoogleCalendarSync#1169]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6.0 
**Edition**:  Portable (custom directory location on laptop)
**Sync Direction**: G->O

**Bug Description**  
Some events are marked for deletion however I don't believe they should be deleted.
Uncheck Disable Deletions
Check Confirm Deletions
Outlook <- Google direction sync. 

**Steps to Reproduce the Issue**  
1. Run OGCS
2. Let it run the sync
3. Confirmation dialogues appear to confirm deletion of events. 

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5947564/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5947566/OGcalsync.log)

**Comment by scottslee-orig** [comment]
I keep having this problem, especially with recurring meetings generated in Outlook. It has been occurring intermittently for several months now. I believe (though am not sure) that when one instance in a series is modified, the subsequent events in the series are flagged for deletion. My sync setup is bidirectional. I will try to upload a log when I next encounter this behavior.

**Comment by keegantgovender** [comment]
I ha sent noticed this happening with adjusted meeting series but I'll
review and confirm either way.

**Comment by phw198** [comment]
@keegantgovender So for example `29-Jan-21 01:30 PM "Pfizer RFP Plan"` is getting flagged for deletion in Outlook - does this item exist in your Google calendar or not?

If not, did you delete the item in Google after having synced it to Outlook? Or how does the appointment come to be in Outlook?

**Comment by Imbutien** [comment]
Hi,

I'm having this issue as well even though i don't know yet how this happens. As i checked the option to confirm deletion i keep getting a popup asking to delete with non sucess...
As i already got the Deleted Google event failed to remove [410=Gone] #1060 issue befire (**thank you** for having fixed it 👍👍), could you enable a king of bug feature such as "forget it" that will enable to OGCS to forget an event or an action (delete, create...) ?
that would be nice ! 

Keep rocking with OGDC

**Comment by phw198** [comment]
Generally the advice to resolve unwanted deletions is [here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).

Copy and pasting already synced items is also a [known issue](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#outlook-appointment-copy--paste) if done whilst OGCS is not running.
