### ISSUE TITLE
Outlook Access Pop-ups

### ISSUE THREAD

**Issue by hemper77** [phw198/OutlookGoogleCalendarSync#1170]
**Are you already using OGCS?**
Provide the version number.
2.8.6.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

Whenever I restart my machine I will see these pop-ups asking for allowed access to my Outlook information, and there will be 7+ of these pop-ups back to back (once I clicked allow on one, another one will appear immediately, repeating at least 7 times.

Wondering if there's a setting that I did wrong? Thank you.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5960304/OGcalsync.log)
![image](https://user-images.githubusercontent.com/78872130/107549343-8e2b7580-6b84-11eb-9e66-8362ffc47428.png)

**Comment by phw198** [comment]
Well documented in the wiki - https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security
