### ISSUE TITLE
Events are being marked for deletion when they shouldn't be (forked)

### ISSUE THREAD

**Issue by scottslee-orig** [phw198/OutlookGoogleCalendarSync#1174]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6.0 (was also occurring on v2.8.0)
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
This is a fork of [Events are being marked for deletion when they shouldn't be](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1169).

I am prompted to delete events that should not be deleted. This happens with events created both in Google and in Outlook. It seems to happen more frequently with recurring events, but not exclusively.

**Steps to Reproduce the Issue**  
1. Create a Google/Outlook event.
1. Run sync.

**Any other information**  
In the attached log, I was erroneously prompted to delete the following events:
1.  2/15/2021 10:30 AM "JP Carta  Scott" (one-time event, originally created in Google)
2. 2/19/2021 1:00 PM "Hospital Medicine Grand Rounds" (recurring event, originally created in Outlook)

:paperclip: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5984317/OGcalsync_github.log)

![Google event](https://user-images.githubusercontent.com/7134499/108643162-e27d0200-746e-11eb-90ee-e97e0b00fff7.png)
[Manually deleted Outlook ICS event](https://github.com/phw198/OutlookGoogleCalendarSync/files/6018879/JP.Carta.Scott.zip)

**Comment by phw198** [comment]
It looks like the first one is for an Outlook appointment for which you are an attendee of and the organiser changed it? Although the time remains the same, the subject has changed from "JP <redacted>" to "JP <redacted2>". In addition, you are excluding sync of appointments you have not responded to - which I think is causing odd behaviour.

1. Initial invite received, responded to and synced to Google.
2. Replacement invite sent, not responded to, out of scope for OGCS, so deleted in Google
3. Because 2-way sync, then also trying to delete in Outlook - undesired behaviour.

**Comment by scottslee-orig** [comment]
Re: "JP Carta Scott", I actually manually edited that in the log after the fact, so as to protect that person's identity. I did a search for the last name and didn't see it elsewhere. If you wouldn't mind editing your post to remove the full last name, I would certainly appreciate it. That event was notable in that it was (a) non-recurring, (b) created by me, and (c) never edited.

Having said that, I have disabled the "only respond to events I've responded to" option and will see how that goes.

**Comment by phw198** [comment]
@scottslee Hmm, I'm not sure on my previous analysis actually - but it would help to know the background to the changes on this appointment.....ah you've literally just posted!

So you manually created the item in Google, it synced to Outlook and then with no further changes at all, OGCS started to request deletion of the Outlook item?

Essentially the Google item at `2/15/2021 10:30 AM` is no longer being found - silly question, you're absolutely sure it is still in the Google calendar being synced? You could turn on the CSV file creation option in OGCS, and then check the `google_events.csv` file to see if it is listed in there...

**Comment by scottslee-orig** [comment]
It's certainly still in my Google calendar (see image attached to top post), and it's in `google_events.csv` as well.

One odd thing is that at some point the event got duplicated. So I deleted it (I believe in Outlook -- see attached ICS file in top post), at which point the duplicate item disappeared from Google as well (though I don't see it in my trash folder).

> So you manually created the item in Google, it synced to Outlook and then with no further changes at all, OGCS started to request deletion of the Outlook item?

Mostly yes. I never touched the event once it was created. I don't know if OGCS was requesting deletion of the Outlook item or the Google item. And the caveat to me saying that I created it is that it was created by a scheduling app called [Motion](https://inmotion.app). In any case, I'm not sure I've ever had this happen with a non-recurring, non-invited event, so something very idiosyncratic may have happened in this instance, especially since I was in the process of changing settings in OGCS in an effort to troubleshoot the overall deletion problem.

**Comment by phw198** [comment]
I would say the standard advice for [fixing unwanted deletions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) still stands - sounds like things have got rather confused with apparent duplicates and deletions of them (eg how do you know you deleted the "correct" duplicate?").

If you continue to encounter problems after that, I would suspect that Motion is causing problems by recreating the Google event. You could confirm this by checking if the two fields `Google EventID` and `Google CalendarID` match between `google_events.csv` and `outlook_appointments.csv` for that calendar item.

**Comment by scottslee-orig** [comment]
Thanks for the tips! Will keep an eye going forward...
