### ISSUE TITLE
Any chance to make this work with Thunderbird on Linux?

### ISSUE THREAD

**Issue by FlexMcMurphy** [phw198/OutlookGoogleCalendarSync#1176]
I was just wondering if there are any plans to make a Linux version of this tool that could sync Google Calendar with an email client such as Thunderbird such that all the Google Calendar would be available to add and edit calendar entries off-line in Thunderbird and not just when on-line?

If anyone knows of such a tool please let me know?

Cheers,

Flex

**Comment by phw198** [comment]
Thanks for raising the enhancement request, but there are no plans or intention to support Linux or Thunderbird, sorry.

(I'm also not aware of any product that does.)
