### ISSUE TITLE
Cannot load the "RichEd20.DLL" DLL into memory.

### ISSUE THREAD

**Issue by morgangrobin** [phw198/OutlookGoogleCalendarSync#1179]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file
))

**OGCS Version**: v2.8.0.0, v2.8.6.0
**Edition**: Installed 
**Sync Direction**: O->G

**Bug Description**  
After Office re-install, OGSC stopped syncing, and began displaying popup error "Application unexpectedly terminated!" "Cannot load the "RichEd20.DLL" DLL into memory." on startup. Reinstalling OGSC did not fix the issue. It also reproduces with the alpha version.

riched20.dll exists in C:\Windows\system32, and permissions are set so that 'ALL APPLICATION PACKAGES'  have Read & execute and Read permission; TrustedInstaller has all permissions. I've tried re-installing office and restarting the computer. 
**Steps to Reproduce the Issue**  
1. ? reinstall Office? unclear if this contributed or not
2. Open OGSC

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6045834/OGcalsync.log)

**Comment by phw198** [comment]
Try re-registering the DLL? Open a CMD window in Administrator mode:
```
regsvr32.exe %windir%\system32\riched20.dll /i
regsvr32.exe %windir%\system32\riched32.dll /i
```
It Outlook itself stable? Google seems to report users saying it sporadically crashes when this DLL is corrupt/not registered properly.

**Comment by morgangrobin** [comment]
For a ...possibly related, possibly unrelated issue, I needed to re-install Windows today, and this is no longer repro-ing! Thank you!

**Comment by phw198** [comment]
Thanks for letting me know @morgangrobin
