### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Grsands** [phw198/OutlookGoogleCalendarSync#1181]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
Not all events on Outlook are being transferred to Google\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Depending on your OGCS configuration, that could be entirely expected.

All guidance for logging an issue ignored, so closing.
