### ISSUE TITLE
All outlook items have been filtered out

### ISSUE THREAD

**Issue by wmfrog** [phw198/OutlookGoogleCalendarSync#1183]
Hi,
Having problem with Outlook to Google sync.
Installed latest version, repeated, etc.

Error during sync says 'Due to your ogcs outlook settings all outlook items have been filtered out". So nothing shows in Google.
However the test button shows outlook items detected in the OGCS outllook settings.

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[Log file](https://gist.github.com/phw198/4c06017e778e7a09ae1d4475300c8dfb)

**Comment by phw198** [comment]
> 9 Outlook items excluded due to active category filter.

Your category settings are:
> Category Filter: Include
Categories: Blue Category,Get back to,Purple Category,Red Category,Reference,Yellow Category

I guess none of those 9 items have that category...
