### ISSUE TITLE
SyncBack Free fails as OutlookGoogleCalendarSync locks all .PST files

### ISSUE THREAD

**Issue by johnferreira15** [phw198/OutlookGoogleCalendarSync#1186]
When running my nightly backup using SyncBack Free (Latest version). the backup fails because OutlookCalendarSync locks all .PST files. I do close Outlook nightly before the backup runs at 3:00 am.

> Checklist:-
Running Version 2.8.0.0 of Google Calendar Sync

Reproduce:
SyncBack fails, unless I close OutlookGoogleCalendarSync

Log file NOT needed as the error is in SyncBack Free.

**REQUEST: To solve this,** 
OutlookGoogleCalendarSync needs to release the .pst files when the user logs out of Outlook.

Thank you

**Comment by phw198** [comment]
Upgrade to the latest alpha and then when Outlook is closed, check if there is the Outlook icon in the task tray with a cog over it. If there is, you can click it to exit Outlook completely - but if it keeps happening, will need to see your log file to investigate further why this might be happening.
