### ISSUE TITLE
Unable to open OGCS

### ISSUE THREAD

**Issue by MarkJSpencer** [phw198/OutlookGoogleCalendarSync#1191]
2.8.6.0

I have been using OGCS for several years with great success.  I use Outlook 2016.

It stopped working so I uninstalled it and reinstalled the lasted version but while the logo comes up, it just takes me automatically to the GitHub webpage. I tried the Alpha and beta versions, tried downloading the portable version, etc... but it always just takes me to the GitHub page. Under no scenario can I pull up the OGCS app so that I can configure my syncs. 

Any Ideas?  Thanks.

Mark

**Comment by phw198** [comment]
In order to receive support, you need to provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by MarkJSpencer** [comment]
2.8.6.0

I have been using OGCS for several years with great success. I use Outlook 2016.

It stopped working so I uninstalled it and reinstalled the lasted version but while the logo comes up, it just takes me automatically to the GitHub webpage. I tried the Alpha and beta versions, tried downloading the portable version, etc... but it always just takes me to the GitHub page. Under no scenario can I pull up the OGCS app so that I can configure my syncs.

Any Ideas? Thanks.

Mark

[OGCS Log.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/6138314/OGCS.Log.pdf)

**Comment by phw198** [comment]
:arrow_double_up: Your logfile shows you are running 2.8.0 - please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

If there are any issues with that, you can [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).
