### ISSUE TITLE
Google created item is deleted during synchronization

### ISSUE THREAD

**Issue by ralfeus** [phw198/OutlookGoogleCalendarSync#1194]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6.0
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
The event "Deutsch" is created in Google. Then it was synchronized to Outlook. After some time synchronization deleted it from both Google and Outlook. After restoring the event in Google next synchronization deletes it again.

**Steps to Reproduce the Issue**  
Not sure what exactly events are deleted. Before I had a situation that some (not all) events created in Outlook where deleted.

**Any other information**  
Log can be found here:
https://gist.github.com/ralfeus/28037cbe06e729230dfd97af3d18c918

**Comment by phw198** [comment]
What created the "Deutsch" event in Google?

Could you 
1. turn on CSV creation in OGCS
2. run a sync that reproduces the deletion request
3. provide the CSV files created - specifically interested in the "Deutsch" rows obviously.

Thanks.

**Comment by ralfeus** [comment]
> What created the "Deutsch" event in Google?

The event "Deutsch" was created in Google.

> Could you
>     1. turn on CSV creation in OGCS
>     2. run a sync that reproduces the deletion request
>     3. provide the CSV files created - specifically interested in the "Deutsch" rows obviously.

The `google_delete.csv` file contains this:
```
Start Time,Finish Time,Subject,Location,Description,Privacy,FreeBusy,Required Attendees,Optional Attendees,Reminder Set,Reminder Minutes,Google EventID,Google CalendarID,Outlook EntryID,Outlook GlobalID,Outlook CalendarID,OGCS Modified,Force Save,API Limited
17.03.2021 14:00:00,17.03.2021 15:00:00,"Deutsch",,,"","transparent",";;;;","",true,5,2dscl9bacd8rkl410pd6gj7n9e,ralfeus@gmail.com,0000000001084DAC92BDA343A0862F0D77037B1A07007083657E6F65B44781E73D629E93B3B300000000010D0000A2046B71A8A7934B9C3E18F3C052F60B00022ABEE8520000,040000008200E00074C5B7101A82E00800000000D05780B07819D701000000000000000010000000D3268812BAB7BD489DB8AA3AACEFBA0D,0000000001084DAC92BDA343A0862F0D77037B1A01007083657E6F65B44781E73D629E93B3B300000000010D0000,20210316090302,,
24.03.2021 14:00:00,24.03.2021 15:00:00,"Deutsch",,,"","transparent",";;;;","",true,5,2dscl9bacd8rkl410pd6gj7n9e_R20210324T130000,ralfeus@gmail.com,0000000001084DAC92BDA343A0862F0D77037B1A07007083657E6F65B44781E73D629E93B3B300000000010D0000A2046B71A8A7934B9C3E18F3C052F60B00022ABEE8520000,040000008200E00074C5B7101A82E00800000000D05780B07819D701000000000000000010000000D3268812BAB7BD489DB8AA3AACEFBA0D,0000000001084DAC92BDA343A0862F0D77037B1A01007083657E6F65B44781E73D629E93B3B300000000010D0000,20210316090302,,
```

**Comment by phw198** [comment]
I'd also need the entries from `outlook_appointments.csv` to compare the IDs. I think this will only prove that somehow the IDs no longer match and hence OGCS is doing the "right" thing - without knowing the exact events preceding this, there's probably not much I'll be able to do.

[FAQ advice here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) would still stand as a workaround/fix.

> The event "Deutsch" was created in Google.

Specifically I meant _how_ was it created? Manually in the Google website, on your phone, though some third party app...?

**Comment by ralfeus** [comment]
Well, FAQ partially helped. It led me to using Calendar API just to remove
OGCS specific properties at those events. After that synchronization works
fine.
Thank you

**Comment by ralfeus** [comment]
It seems the problem is caused by the event modified by Outlook. As company policy is to limit amount of recurrent events the event with no recurrence end is modified by the Exchange server. So modification of the event at Outlook side most likely caused it to be deleted at Google side.

So probably the main question would be - is synchronization of event modifications at the non-origin system considered "by design"? I would say that each event has to have only one source of truth and target system changes should be ignored/overwritten.

**Comment by phw198** [comment]
Whichever calendar has the most recent last modified date will have its attributes synced to the other calendar. If the Exchange server is editing the recurrence duration and causing the last modified timestamp to be updated, that would sync to Google. 

However, I suspect Exchange is being much dumber than that and actually either recreating the entire series, or somehow causing the unique ID for the Outlook appointment to change (which is what I was trying to determine with the CSVs). In this situation, OGCS would rightly proceed with deleting the previously synced Google appointment and create the altered appointment afresh in Google.

**Comment by ralfeus** [comment]
Ok, I've encountered the issue again with different item. This time it's not recurrent 
Steps to reproduce:
1. Create item in Google
2. Perform sync
3. Move item in Google outside of synchronization time range
4. Perform sync. It will delete the item in the Outlook. 
5. Wait for item to be in synchronization time range
6. Perform sync
7. Enjoy item deletion in Google

I suppose the reason is that following happens:
1. Item can't be found and therefore considered as deleted
2. The corresponding Outlook item is deleted. Outlook attributes though aren't cleaned up from Google item
3. When the Google item is in sync range it checks the item, finds Outlook attributes but doesn't find corresponding Outlook item.
4. Because there is no corresponding Outlook item the item in general is considered deleted and is deleted from Google too

I would say the solution would be to have a source attribute set for each item and update only ones that are created by the synchronizer. Original items both in Outlook and Google must not be changed

**Comment by phw198** [comment]
Thanks for getting to the bottom of that and reporting back - however, this is essentially what's [documented in the limitations](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#calendar-items-moving-through-sync-window-bounds) section of the wiki. Never changing the original item of a calendar rather undermines the concept of two-way sync, and is much more likely to cause confusion with users.

It looks like you are only syncing 30 days into the future? I'd suggest you increase that sync window so it's less likely you'll move a Google item out of the synced date range, and therefore won't encountered this limitation.
