### ISSUE TITLE
Appointment update failed

### ISSUE THREAD

**Issue by frannavarro27** [phw198/OutlookGoogleCalendarSync#1198]
**OGCS Version**: v2.8.0.0  
**Edition**: Installed
**Sync Direction**:O<->G

**Bug Description**  
Appointment update failed
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6234187/OGcalsync.log)

**Comment by frannavarro27** [comment]
Any help, please?

**Comment by phw198** [comment]
In order to receive support, you need to [upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)

**Comment by frannavarro27** [comment]
It works!!!!
Thanks so much. The latest version fixes the bug.
