### ISSUE TITLE
Occurrence does not exist in Google, but does in Outlook

### ISSUE THREAD

**Issue by scosmo** [phw198/OutlookGoogleCalendarSync#1199]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6.0
**Edition**: Installed / Portable  
**Sync Direction**:  O->G 
**Bug Description**  
Two outlook calendar series "FA Exec" and "FA Rep" populate in google correctly. Upon next sync I get the message "Occurrence does not exist in Google, but does in Outlook" and to remove the Google series in Google and let OGCS recreate it. I have done. Does not fix it. 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6237940/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. Go to...sync
1. Click on...sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by jsabra1** [comment]
I have this bug as well, OG was working fine for me until this happened, and now it happens with some 25 series which I have, so it#s a huge task for me to delete & recreate all of them, this renders OG useless for me.

**Comment by jsabra1** [comment]
@phw198  Do you have any suggestions how to work around this? Thanks!

**Comment by phw198** [comment]
@scosmo Your log file does not show any evidence of it creating the "FA Exec" or the "FA Rep" series after you manually deleted them in Google. Neither have you said that the information it is providing is incorrect, for example for "FA Exec", "The occurrence on 3/26/2021 does not exist in Google, but does in Outlook." - are you saying you _can_ see the 26-Mar occurrence?

@JawadS Same goes for you, the occurrence OGCS is reporting as deleted in Google but not in Outlook, are you saying this is incorrect? If not, then he work around is already provided - manually delete them in Google. Unfortunately, there is no technical way to undelete a particular occurrence of a recurring series.
