### ISSUE TITLE
Calender Sync does not sync category colour

### ISSUE THREAD

**Issue by Bea66** [phw198/OutlookGoogleCalendarSync#1203]
**Are you already using OGCS?** Yes
Provide the version number: 

2.8.0.0
--

**Describe the question you have**
No sync of the categories coulors in both ways. Would be great if the colour synchronize too, otherwise it gives me double work.
Thanks for your help 👍🏼
Best, Beatrice

**Comment by phw198** [comment]
Category synchronisation is well catered for in subsequent releases - upgrade to the latest alpha.
