### ISSUE TITLE
One Recurring Event not Syncing from Outlook to Gmail

### ISSUE THREAD

**Issue by eromrab** [phw198/OutlookGoogleCalendarSync#1204]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I have a recurring event I was invited to on Outlook. I accepted.  For some reason, all other events get synced but that one won't.  Not sure why?

**Steps to Reproduce the Issue**  
I've tried manually syncing back 365 days. I've tried accepting the meeting again.  Event just won't sync to my Google from Outlook even though every other meeting I can see does...

**Any other information**  
\<Update here>

**Comment by eromrab** [comment]
[OGcalsync.log.2021-04-05.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/6269041/OGcalsync.log.2021-04-05.txt)

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by eromrab** [comment]
I did the log in the first comment and am on the most current version.

**Comment by phw198** [comment]
v2.8.0 is not the latest version, no - v2.8.6 is.

**Comment by mvaede** [comment]
Hello,

Not sure I'd like to use an Alpha version, might wait for a stable version

**Comment by eromrab** [comment]
> v2.8.0 is not the latest version, no - v2.8.6 is.

That's an Alpha release.  I'm on the most up to date normal release.

**Comment by phw198** [comment]
Well observed. Less well on the second line of your OP which says "Upgrade to the latest alpha release to check if the problem is already fixed."
