### ISSUE TITLE
Authorisation token invalid

### ISSUE THREAD

**Issue by mikedelic** [phw198/OutlookGoogleCalendarSync#1205]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.6
**Installed or Portable**: Portable

**Problem Description**  
\App worked on first machine. App doesn't work on second machine. On second machine, receiving "Authorisation token invalid" error. "Your Google authorisation token needs updating. The process to reauthorise access to your Google account will now begin...". I've tried multiple ways to reauthorize. Website indicates authorization is successful, but not app.
![2021-04-08 12_38_57-Windows 10 MCS - Desktop Viewer](https://user-images.githubusercontent.com/64810499/114065082-46655980-9868-11eb-9a96-39264adc6914.png)

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:spiral_notepad: Please reproduce the issue and then provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
