### ISSUE TITLE
og not finding outlook on install/setup

### ISSUE THREAD

**Issue by HansWallz** [phw198/OutlookGoogleCalendarSync#1210]
**Are you already using OGCS?**
Provide the version number.

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

**Comment by phw198** [comment]
What's your question exactly?

If you wanted assistance getting OGCS to work, please provide some details around what happens and what you see when you start OGCS. Providing your `OGcalsync.log` file is also invaluable for troubleshooting ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
