### ISSUE TITLE
Update event duration

### ISSUE THREAD

**Issue by vizinho** [phw198/OutlookGoogleCalendarSync#1215]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6 
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
I have an event in Outlook. Already synced with google.
The bug: When I extend the event duration in Outlook (example I add 2 more hours) it does not sync that duration to google.
All ok If I change the duration in Google. It reflects on Outlook.

**Steps to Reproduce the Issue**  
1. Create event
1. Update event duration

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6400365/OGcalsync.log)

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

If this fails for some reason, please [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

Then reproduce the issue and reupload your log file. Thanks

**Comment by vizinho** [comment]
I was sure I installed the latest release... seems not.
Made the update and all worked fine. **Thank you**.

(FYI: The check for update feature returned an error. I had to download and install.)
