### ISSUE TITLE
Some Birthday/Anniversary sync O>G improperly

### ISSUE THREAD

**Issue by 9Halcyon** [phw198/OutlookGoogleCalendarSync#1216]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6 alpha
**Edition**: Installed  
**Sync Direction**: O->G

**Bug Description**  
Some (but not all) birthdays and anniversary all day events in Outlook are synced to Google with a 1 hour offset, causing them to span 2 days in Google. Does not happen with all, only with some--I do not see a pattern. And I have not seen it happen with all day Outlook appointments , neither single day nor multi day.

**Steps to Reproduce the Issue**  
Occurred the first and subsequent times I used OGCS. Did not happen with CompanionLink previously.
Upgrade to 2.8.6 alpha did not fix the incorrect items.

**Any other information**  
Is there a way to stop OGCS from syncing birthdays and anniversaries from Outlook? I'd rather not have them than have them span 2 days.
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6414917/OGcalsync.log)

**Comment by 9Halcyon** [comment]
Is there a way to cause these Outlook birthday and anniversary events NOT to sync to Google? If I could exclude them as a group, that would be sufficient.

**Comment by phw198** [comment]
I would suspect this may be due to whether the birthday falls in a daylight saving month or not.

As you have now upgraded to v2.8.6, please perform a full sync by pressing `Shift` while clicking `Sync` button. And/or since upgrading, check if newly created all day appointments suffer the same problem.

Feature request would be a duplicate of #104.

**Comment by 9Halcyon** [comment]
DST does not seem to be the culprit, as some birthday/anniversary events in the same week synced correctly and other incorrectly. 

I deleted all the offending items from GCal, disabled the birthday/Anniversary feature in outlook, and did a shift-sync and all is well now. Hope it stays this way.

I am closing this item, seems an odd issue. Thanks for the quick response!
