### ISSUE TITLE
More frequent syncs and multiple calendars

### ISSUE THREAD

**Issue by Noxdor** [phw198/OutlookGoogleCalendarSync#1219]
**Are you already using OGCS?**
2.8.0.0

**Describe the question you have**
I just started to use your amazing tool and I have two questions I couldn't find answers to:

1. Can I and if so how, reduce the time between syncs below 120min/2h? Whenever I try to do that, it resets the time to 120min.
2. Can I and if so how, synchronise more than one calendar from Google to more than one of my Outlook calendars?

Help with this will be greatly appreciated!
Thanks for developing this great tool, which can do something so simple Google and Microsoft are too blind to find a common standard for.

**Comment by phw198** [comment]
Hi and welcome @Noxdor 

1. https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-the-restriction-on-sync-schedule
2. Issue #165 contains a workaround for multiple calendars.

Hope that helps.
