### ISSUE TITLE
Outlook slows down when Sync is running

### ISSUE THREAD

**Issue by chanpreetsal** [phw198/OutlookGoogleCalendarSync#1220]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6.0
**Edition**: Installed   
**Sync Direction**: O->G 

**Bug Description**  
Outlook is very slow when Sync is running. It was working fine for a while till recently the issue started occuring. When i close the Sync app, outlook returns to normal behavior.

**Steps to Reproduce the Issue**  
1. Launch Sync
2. Launch Outlook
3. I notice that the initial sync occurs successfully. Then outlook is slow. When i click on emails etc it takes a second longer to open the items. 
4. Closing Sync returns Outlook to normal.. 

**Any other information**  
Outlook version - Microsoft® Outlook® for Microsoft 365 MSO (16.0.14026.20140) 64-bit 
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by matthewclaussen** [comment]
I also experienced this with 2.8.7.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6498484/OGcalsync.log)

**Comment by matthewclaussen** [comment]
I've tried repairing my OST file and going full cached mode too "all" from "1 year" without any luck.

**Comment by phw198** [comment]
Are you saying that once the first sync has completed, even when a sync is not actively running, that Outlook is slow to open emails etc?

@matthewclaussen Can you try turning off Push Sync and seeing if that helps?

**Comment by cdj-again** [comment]
Outlook stalls (CPU 25%), "Not Responding" on Task Manager when

"Comparing 59 existing Google calendar entries" on OGCS

Cancelling the sync allows Outlook to recover.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6863087/OGcalsync.log)

**Comment by phw198** [comment]
@cdj-again The only stall I can see in your logs is here for a couple of minutes, but it does continue by itself without a cancel:
```
2021-07-22 10:43:26,476 DEBUG  27 OutlookGoogleCalendarSync.Recurrence [582] -  1/22/2021 12:00 PM (R) => "Hembree Hangout"
2021-07-22 10:43:26,476 DEBUG  27 OutlookGoogleCalendarSync.Recurrence [583] -  This is a recurring appointment with 7 exceptions that will now be iteratively compared.
2021-07-22 10:45:43,734 DEBUG  27 OutlookGoogleCalendarSync.Recurrence [411] -  Finding Google instance for Outlook exception:-
2021-07-22 10:45:43,734 DEBUG  27 OutlookGoogleCalendarSync.Recurrence [412] -    Original date: 23/07/2021
2021-07-22 10:45:43,789 DEBUG  27 OutlookGoogleCalendarSync.Recurrence [416] -    Current  date: 23/07/2021
```
Seems like there's something wrong with the Hembree Hangout series. Have you tried running a [repair on your PST/OST](https://support.microsoft.com/en-us/office/repair-outlook-data-files-pst-and-ost-25663bc3-11ec-4412-86c4-60458afc5253) files(s)?
