### ISSUE TITLE
v2.8.7.0 detected by avast as a Virus

### ISSUE THREAD

**Issue by HartLarsson** [phw198/OutlookGoogleCalendarSync#1222]
**OGCS Version**: v2.8.7.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Avast antivirus detect the new version infected by IDP.HEUR.23

**Steps to Reproduce the Issue**  
1. Upgrade/install to 2.8.7.0
1. Avast during the launch of the app will notice of a virus detection

**Any other information**  
![image](https://user-images.githubusercontent.com/16102074/118314073-e8293780-b4f3-11eb-9a35-055c2f4ec3f6.png)

**Comment by phw198** [comment]
Thanks - [please see here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#anti-virus-false-positives) for how you can assist.
