### ISSUE TITLE
Carbon Black blocks execution

### ISSUE THREAD

**Issue by elalewen** [phw198/OutlookGoogleCalendarSync#1223]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.7.0  
**Edition**: Portable  
**Sync Direction**: G->O

**Bug Description**  
My Company uses Carbon Black to secure our computers. 
Carbon Black blocks execution of OGCS application 

**Steps to Reproduce the Issue**  
1. Try to execute OGCS
2. Nothing happens
3. Application logs in Windows shows a Carbon Black blocking

**Any other information**  
OGCS logs are empty because execution stoped by Carbon Black
Thanks for your help
:paperclip: Attach your `OGcalsync.log` file.

**Comment by elalewen** [comment]
With v2.8.7 alpha : same problem

**Comment by phw198** [comment]
Thanks, but I'm not sure what you are I hoping I can do? Beyond providing a portable executable of OGCS that users can use as they see fit, circumventing corporate infosec policies is not something I am able to assist with.

Here's a search on [Carbon Black's KB](https://community.carbonblack.com/t5/custom/page/page-id/Search#q=whitelist%20application&t=Posts&sort=relevancy) for "whitelisting applications" - you'll likely be at the behest of your IT as to whether they will whitelist OGCS or not...
