### ISSUE TITLE
Sync only Accepted meetings

### ISSUE THREAD

**Issue by euinor** [phw198/OutlookGoogleCalendarSync#1224]
Feature Request: Can we sync only accepted meeting items. In Outlook receive a lot of meetings I cannot attend, but like to be aware of so I mark them tentative. But I'm not interested in syncing these items with my Google Calendar (which I use as a day planner).

So I would like to be able to set tentative items to be ignored.

My workaround is to mark those items with a specific category that has been set to be ignored in OutlookGoogleCalendarSync. But this doesn't work for recurring meetings, where one item can be marked as tentative and others with other statuses - you can only set a category for all the meetings in that sequence.

Similar to #825, #104 and #113

**Comment by XtremeMaC** [comment]
I've checked out the similar topics @euinor mentioned and I'd also love to be able to differentiate the tentatively accepted from Accepted. 
If there is a way to map Outlook Tentative to Google Maybe, that would resolve my problem partially, but would be of great help. Perhaps also allow user to either carry over the Reminder or Remove Reminder for Tentatively accepted meetings.

**Comment by phw198** [comment]
#825 has now been developed and provides the ability to exclude Free or Tentative items from sync - as such, is this feature still required as a combination of `Exclude tentative` and `Only invites I've responded to` will pretty much achieve the same?

**Comment by euinor** [comment]
sorry I never saw your response @phw198 - yes this can be closed, the settings do what I want. Thanks!
