### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mitac71** [phw198/OutlookGoogleCalendarSync#1225]
**Are you already using OGCS?**
Provide the version number.  v2.8.7.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.
dowloaded setup and installed on pc  to complete installtion click icon directed to release notes and cannot setup OGCS

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
