### ISSUE TITLE
OGCS seems to want to delete a series of events when first event is deleted

### ISSUE THREAD

**Issue by tnjgb** [phw198/OutlookGoogleCalendarSync#1227]
2.8.7.0 - Outlook 365 sync both ways.

I recently deleted the first event that had passed in Google calendar from a recurring set of weekly events with a set end date. OGCS then repeatedly wanted to delete the whole series of events from Outlook which I initially denied and kept repeating this delete request. I tried editing the event and resaving it in both Google and Outlook but OGCS still wanted to delete the event. I eventually let OGCS delete the event, first from Outlook then from Google. I then moved the event back from the Outlook Deleted Items folder into the Outlook Calendar folder and OGCS wanted to delete it again. I eventually let it delete the event and created a new recurring event which is now as expected.

**Comment by phw198** [comment]
I need some more details on this:
1. What date did the series start and end
2. What sync period did you have set in OGCS (past and future number of days)
3. On which date did you delete the first occurrence of the series
4. Did you make the delete in Google or Outlook
5. From which date did OGCS start wanting to delete the series

**Comment by tnjgb** [comment]
The details I can remember:
1. The series ran weekly from 20th May to 30th September.
2. The sync period is 10 days in the past to 365 days in the future.
3 & 4. The first occurrence (20th May) was deleted in Google around 25th May.
5. OGCS wanted to delete the series the next time it was started after the deletion.

OGCS tells me every sync under "Authenticating with Google" that "4 are exceptions to recurring events". I only have one recurring event series in my calendar. I have not had this delete situation occur again when deleting one event from the new version of the series.

**Comment by devan24** [comment]
I have a similar issue where the first occurrence was May 27. The 2nd occurrence was deleted around May 31. For some reason the first event will not save in Google, and asks each sync to delete it from Outlook.  The rest of the series appeared to have been deleted at some (unknown) date. I recovered the series from Outlook as it was not recoverable in Google. It won't sync back into Google, either. This happens with every sync.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6683065/OGcalsync.log)

1. Series ran from May 27 to roughly the end of 2021, every other week.
2. Sync period is set to30 days past, 366 days into the future

**Comment by phw198** [comment]
@tnjgb I don't seem to be able to replicate this issue based on the details you've provided, and as the offending series has now been deleted and you created a new one to replace it, we won't be able to gather any logs to investigate further.

@devan24 Your issue sounds different if at some point the whole series was deleted. From what I can tell the Google recurring series for "Sea Rose Board Meetings" on 27-May was deleted, but remains in Google (to be deleted) and only a single non-recurring meeting on the 17-Jun exists in both calendars.

If the recurring series was manually and incorrectly deleted, then it can be recovered by restoring from the calendar bin/deleted items and then [a full one-way sync](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).

**Comment by devan24** [comment]
Paul, thank you for the response, I had already restored the entries, didn’t realize one way sync would solve it, and it has.
