### ISSUE TITLE
Error 0x80004002 when starting the app

### ISSUE THREAD

**Issue by sunew84** [phw198/OutlookGoogleCalendarSync#1229]
> Checklist:-
> * [x ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x ] Reproduce the issue
> * [x ] Complete the information below
> * [ x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.7.0  
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
While launching the app from the desktop icon, the error message "A problem was encountered with your Office install. Please see the wiki for a solution. [0x80029C4A]" is displayed.
The solution (repairing the Office installation) does not fix the problem.

**Steps to Reproduce the Issue**  
1. Launch OGCS from dekstop icon

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6574091/OGcalsync.log)

**Comment by phw198** [comment]
Looks like you upgrade to 2.8.7, received the actually error code `0x80029C4A` and wiki entry...and hopefully those instructions resolved it for you.
