### ISSUE TITLE
New items created in Google cal synced to Outlook are then deleted upon next sync

### ISSUE THREAD

**Issue by Judi-mae** [phw198/OutlookGoogleCalendarSync#1230]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.7.0 
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
Been using this awesome app for 2 years and always have it set to auto update including alphas. Am not a developer so even though been experiencing this issue for about 9 months, this is my first time reporting it - never used GitHub before! Really hope you can help. Note: have found some similar issues reported on here but nothing EXACTLY the same so have created new bug report. If mods disagree, please advise what I need to do differently, thanks.

Issue is that sometimes (not always, seemingly no logic to when it happens) when I create a new event in Google calendar, it syncs fine to my Outlook and then the next time the app syncs the calendars it deletes said event from both calendars. It was happening for a week or so until I noticed, then I turned it so that I had to accept deletions. Now I live with the app by not agreeing to these deletion requests, which I would rather not have to do.

Have tested allowing event deletion and then recreating the event in Google again, to see it happen all over again, or not at all. I cannot work out any logic for it. I have tweaked settings and then returned them to how I need them, in case it bumps something into action to fix it (LOL), nothing changes. It is random, sometimes happening with recurring events, sometimes with standalone events. Sometimes one out of 6 new events is chosen for this, sometimes it is all of them.

Reporting today as I just added in more than 15 new events to my Google calendar and 10 or so of them are now stuck in this deleting cycle. Having to click 'no' that many times every time my calendars sync is making the app really difficult to use. I love the app and thought it is probably about time I reported this bug I am experiencing.

Please advise if you need any more info!

**Steps to Reproduce the Issue**  
1. Create new event in Google calendar
2. Let OGCS sync the calendars
3. Sync again 
4. Deletions will be attempted and dialogue box will pop up to ask if you would like to delete one / many of the new events added.

**Any other information**  
It does not ever seem to do this when an event is created in Outlook. I use Google to create certain items though, because it allows me to choose colour options. To organise effectively (and use my calendar without the need for my PC), I need to keep this use of colours and as such I cannot simply stop adding things into Google to avoid the problem.

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6599308/OGcalsync.log)

**Comment by phw198** [comment]
I think this might boil down to your use of colours/categories. 

You have OGCS configured to only include certain categories from Outlook - however when you add a new item in Google, I think you may be giving it the colour Basil (dark green)? This then translates to the category Dark Teal in Outlook, and this is not a category you have selected for sync; so it falls out of scope for future syncs and is therefore deleted in Google.

Let me know if I'm along the right lines...

**Comment by Judi-mae** [comment]
Hi and thanks for your comment / investigation! Interesting... I didn't specifically set that colour not to sync, so I'll check my settings and make sure all the colours are ticked. I've also noticed that you can map colours so I'll set the ones I usually use and see if the issue happens again. Thanks for this advice!
