### ISSUE TITLE
Uninstallation problem

### ISSUE THREAD

**Issue by amir-mhanna** [phw198/OutlookGoogleCalendarSync#1231]
I uninstalled the program but i still get the following window every time I start Outlook:
![image](https://user-images.githubusercontent.com/85575875/121223758-2530e180-c888-11eb-8e42-df74e50581d3.png)

- Product version: 2.8.0 Beta

I appreciate you support!

**Comment by phw198** [comment]
That's nothing to do with OGCS - it just means you have multiple mail profiles configured for Outlook and there's no default set. 

In Outlook, go to File > Info > Account Settings > Manage Profiles - here you can set one of your profiles to be the default when you start Outlook.

**Comment by amir-mhanna** [comment]
Thanks man!! This happened after I installed or installed OGCS, so thought its a Bug.

Problem solved.
