### ISSUE TITLE
OGCS doesn't sync my Outlook to my Google Calendar

### ISSUE THREAD

**Issue by kurtfajardo** [phw198/OutlookGoogleCalendarSync#1235]
**Are you already using OGCS?**
Provide the version number.    2,8.7.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying. 

The google calendar doesn't update with the Outlook events.

**Comment by phw198** [comment]
So what's the question?

Have a [read through this wiki entry](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems) and raise a bug ticket/provide the required information here.
