### ISSUE TITLE
OGCS is blocked by Google since 15-06-2021

### ISSUE THREAD

**Issue by Drakis** [phw198/OutlookGoogleCalendarSync#1236]
[:memo:] Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.7.0  
**Installed or Portable**: Installed

**Problem Description**  
Synchronisation forces a login attempt by Google and after login this error message appears:

> This app is blocked
>
> This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

**Steps to Reproduce the Issue**  
1. Start OGCS (Sunchronisation starts automatically, triggering the above behaviour)

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6676143/OGcalsync.log)

**Comment by phw198** [comment]
You're on one of the very old API keys that is no longer valid - [see this comment](https://github.com/phw198/OutlookGoogleCalendarSync/issues/915#issuecomment-563376974) and let me know if that resolves this for you.

**Comment by Drakis** [comment]
Today, after login, Google allowed me to verify access by OGCS. I assume this solved the issue; I'll keep you posted.

**Comment by phw198** [comment]
Sounds like you've successfully moved over to the approved API keys, so OGCS should work properly again now.
