### ISSUE TITLE
Unable to sync after uninstalling Office 2013 and installing Office 365

### ISSUE THREAD

**Issue by fogoat** [phw198/OutlookGoogleCalendarSync#1237]
**Are you already using OGCS?**

2.8.0 Beta

**Describe the question you have**

I was using Office 2013 64-bit great with OGCS 2.8 for the longest time. I upgraded to Office 365. I uninstalled Office 2013, restarted the computer. Then I got an error saying that an Office repair would fix it. Ran Office 365 Repair. 

Now every time Portable 2.8.0 runs, I the Hide Splash screen button (like the $10 I donated is not recognized) and all my settings done. My settings.xml in the portable are still there but doesn't seem to recognize. I also try `/s:settings.xml` but that doesn't seem to create a different behavior.

I am including Process Monitor for the process name OutlookGoogleCalendarSync.exe and settings.xml

[procmon-Logfile.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6690738/procmon-Logfile.zip)
[settings-xml.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6690744/settings-xml.zip)

I am not including logs because none were generated for 19 June 2021.

I don't know if the Office version changed my license or settings, but any clarification is appreciated.

**Comment by phw198** [comment]
The `settings.xml` file you have looks to be for v2.8.7 not v2.8.0 - which version of OGCS were you actually executing? Please use the latest alpha as 2.8.0 is likely not reporting correctly the exact fix your Windows registry needs.

Would be worth changing setting to `<LoggingLevel>DEBUG</LoggingLevel>`. then try providing the full path to your `settings.xml` file: `/s:c:\path\to\settings.xml` and also specify the logfile `/l:c:\path\to\OGcalsync.log`.

**Comment by fogoat** [comment]
My mistake - I was using 2.8.7. `/s:settings.xml` did not work but `/s:c:\full\path\settings.xml` worked.
