### ISSUE TITLE
Independently set color/category

### ISSUE THREAD

**Issue by lifebound** [phw198/OutlookGoogleCalendarSync#1238]
Currently, OGCS allows, under Sync Options, the ability to set color/category on sync. However, this coloration only works in one direction. You can colorize while syncing from google to outlook, or while syncing from outlook to google. You cannot, however, set new colors in both directions.

For example, My default calendar color in Google is blue. My default calendar color in Outlook is green. I would like OGCS-created entries on my google calendar to show up green AND my OGCS-created entries on my outlook calendar to show blue. Or red. or Yellow.

Currently I don't have that level of granularity.

**Describe the solution you'd like**
Under Sync Options -> How, there should be two sub-containers, labeled something like 'Syncing From Google', and "Syncing from Outlook'. each box would have the same sub-selection boxes currently at the bottom of the 'How' container: 
* Set entries to private"
* Set entries as free/available
* Set Color/Cateogry color
The containers would either show/hide or at least gray out depending on what direction is chosen in the drop down at the top of the "How" container

**Comment by phw198** [comment]
Which version of OGCS are you running? The later alphas have lots more options around categories and colour mappings between calendars...

**Comment by lifebound** [comment]
Ah yeah, I am on beta 2.8.0. I'll take a look at the alpha, thanks!

**Comment by phw198** [comment]
Closing this as most/all of the functionality is available as of release v2.10.1
