### ISSUE TITLE
Can't launch OGCS

### ISSUE THREAD

**Issue by leifalbor** [phw198/OutlookGoogleCalendarSync#1244]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed
**Sync Direction**: Not applicable

**Bug Description**  
Unable to start OGCS.  System reports OGCS settings are corrupt, and then reports the settings file is being used by another process

**Steps to Reproduce the Issue**  
1. Install OGCS
2. Run OGCS
3. Error generated.
![image](https://user-images.githubusercontent.com/29937194/125010537-0ea9c000-e0aa-11eb-8905-a93a831f78b6.png)
4. Click OK
5. Error generated.
![image](https://user-images.githubusercontent.com/29937194/125010603-31d46f80-e0aa-11eb-9ab1-012cfff8ab3a.png)

**Any other information**  
:paperclip: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6788116/OGcalsync.log)

**Comment by phw198** [comment]
You'd need to close/shutdown any process that is running and locking the `settings.xml` file - possible there is more than one OutlookGoogleCalendarSync.exe process running? Check in the Task Manager under the "Processes" tab...

**Comment by leifalbor** [comment]
Checked for this, nothing was using the process.

I ended up discovering that .Net was corrupt/missing files.  Was a messy job to get it working again 😂
