### ISSUE TITLE
Push Function

### ISSUE THREAD

**Issue by davefeeser1** [phw198/OutlookGoogleCalendarSync#1247]
**Are you already using OGCS?**
Provide the version number.

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.
I have the "Push" command checked. However, changes I make in Outlook are not pushed to Google until a sync takes place. What an I doing wrong?
Dave

**Comment by davefeeser1** [comment]
I AM using version 2.8.7.0. Also, have my settings configured for two-way sync between Outlook and Google

**Comment by phw198** [comment]
> However, changes I make in Outlook are not pushed to Google until a sync takes place.

Yes, that's right, a sync should run within 2 minutes of a change in Outlook.
