### ISSUE TITLE
Syncing Settings

### ISSUE THREAD

**Issue by NoisyTigress** [phw198/OutlookGoogleCalendarSync#1250]
**Is your feature request related to a problem? Please describe.**
I would love the option to sync my OGCS settings to an account that I can sign into on multiple computers. 

**Describe the solution you'd like**
I access my work Outlook from multiple computers, and I'm worried about duplicating every appointment (both personal and work) on both sides.

**Describe alternatives you've considered**
As of right now, my options are to either log into my work computer several times a day while using my personal computer for work (which doesn't work if I leave my computer at the office) or to try to recapture the magic of the settings that I (finally) figured out and got working perfectly, hoping that my events do not duplicate since it's a different computer starting a distinct sync.

**Additional context**

**Comment by phw198** [comment]
As long as you are using at least v2.8.0 then you shouldn't get any duplicates - though I don't think you would anyway. Your Outlook calendar for work is going to be stored centrally (O365 cloud?) anyway, so it doesn't matter if you are accessing it from multiple different computer, same as for Google.

So I think you just want to store your OGCS settings.xml file in a directory that is syncing eg to Google drive and therefore available on multiple computers? My only caution here is that the file is not designed to be accessed simultaneously - ie by running OGCS at the same time from different computers.

That said, you could either run the OGCS portable application and unzip it to a cloud-synced folder, or use the installed version but start it from the command line and specify the location of the settings file - see #165 for more detail.

**Comment by phw198** [comment]
Just to note that v2.10.1 and #1561 brought in import and export of the OGCS settings too.
