### ISSUE TITLE
Outlook calendar entry constantly recreated

### ISSUE THREAD

**Issue by DannyBeanz** [phw198/OutlookGoogleCalendarSync#1251]
**OGCS Version**: v2.8.7.0  
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
I had a tentative Outlook meeting that recurred every weekday.  I no longer need the meeting in my diary so rejected it.
The rejection was successfully synced to Google calendar.
I noticed, roughly 24hrs later, that the Outlook appointment had been recreated but had not been synced to Google Calendar.
Each time I now delete or reject the meeting, it is recreated in Outlook and never syncs to Google.

Logs attached.
[Portable_OGCS_v2.8.0.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6884285/Portable_OGCS_v2.8.0.zip)

**Comment by phw198** [comment]
Once you have rejected a meeting occurrence in Outlook and it's synced to Google, there's no way to bring it back automatically. OGCS should show an update:
> The occurrence on <occurrence date> does not exist in Google, but does in Outlook.
This can happen if, for example, you declined the occurrence (which is synced to Google) and proposed a new time that is subsequently accepted by the organiser.
<u>Suggested fix</u>: delete the entire series in Google and let OGCS recreate it. Ensure you first set OGCS to one-way sync O->G.

What I'm less clear on is what is recreating the rejected occurrence in Outlook? Is the meeting organiser sending out updates, or does it appear after OGCS runs G->O.

Can you provide the item's subject, date and time that is the problem - you have a lot of logs!

**Comment by DannyBeanz** [comment]
Thanks for coming back to me.

> What I'm less clear on is what is recreating the rejected occurrence in Outlook? Is the meeting organiser sending out updates, or does it appear after OGCS runs G->O.

There are no updates coming from the meeting organiser, at least that I am seeing in Outlook.  It appears after OGCS is running so far as I can tell.  The entry is:

```
OpenSpace Standup
Weekdays @ 10:00am - 10:15am
Acceptance: Tentative
```

Come back to me if you need further details.

HTH & Thanks

**Comment by phw198** [comment]
There's no sign of "OpenSpace" in any of your logs!

You'll need you to replicate the issue and then provide your logs again - logging level at `DEBUG` should be sufficient:
1. Delete/reject an Outlook occurrence
2. Perform 2-way sync
3. Confirm deletion occurrence has reappeared
4. Upload log file(s) for the period covering the test.

Thanks

**Comment by DannyBeanz** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6953006/OGcalsync.log)
Fresh log attached.

HTH

**Comment by DannyBeanz** [comment]
This isn't an OGCS issue.

I was working late last night and spotted, at the stroke of midnight, that it is (as you probably expected) Outlook recreating this calendar event, completely unprompted.

So strange, but at least it doesn't appear to be an issue with OGCS.

Thanks for your help!

**Comment by phw198** [comment]
That's pretty crazy! I wonder what's causing that... but as you say, glad it's not OGCS. And glad you spotted it  as we could have been chasing our tails for some time otherwise 🙂
