### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by vprichard** [phw198/OutlookGoogleCalendarSync#1252]
**Are you already using OGCS?**
Provide the version number. 2.8.7.0

**Describe the question you have**
First sync after installation worked.  Sync is set for O<->G.  Later manual and scheduled sync run, but no changes in Outlook appear in Google.  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6919574/OGcalsync.log)

**Comment by phw198** [comment]
It looks like you've set OGCS to exclude pretty much all Outlook items due to your category settings of "exclude" for <No category assigned>,Blue Category,Green Category,Orange Category,Purple Category,Red Category,Yellow Category.

If you did this subsequent to the initial sync, then this would likely explain why "nothing" is synced - in fact OGCS now wants to delete 40 or so items from Google, but it isn't because you have deletion disabled also.

**Comment by vprichard** [comment]
Hi Paul,
 
  Thanks for the clarification.  I didn't know what the category settings were for and so left them at the defaults. I've now cleared the check-marks for all of them, and the current Outlook items went into Google under the  O - > G setting that I now have in place.  Here are some more questions for you if you have the time to reply:
 
  1. Is there a place I can see all of the O-G functions and options, what they do and how to choose them, i.e., a User Manual?
  2. I was surprised when I temporarily set the sync method to O < - > G after getting sync to work that numerous older Outlook items were flagged as "Reclaimed" and then no longer appeared on my Outlook calendar.  I had cleared the "Disable deletions" option and chose "Confirm deletions" in the Sync Options settings.  I did get confirmation dialogs for Google items I had removed from Outlook for testing. But no confirmations appeared for the older Outlook items that were deleted, apparently by the "Reclaim" function. I must retain ALL Outlook items and restored from my most recent backup of the Outlook.pst file.  Then I reset the sync method to just O - > G. Is there a way to use the sync method O < - > G sync method WITHOUT ever deleting Outlook items?
  3. Am I correct that the utility does not run in background, even when a sync is scheduled for every two hours? My testing has indicated that no sync is done unless the program has been manually launched.  Of course I could set a Windows startup item to launch it, but is that step intended?

My most recent OGcalsync.log file is attached.

Best Regards and Stay Safe . . .

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6951681/OGcalsync.log)

**Comment by phw198** [comment]
The default setting for category sync is to exclude none, so somewhere along the line your must have inadvertently changed them.

1. Yes, press F1 and you'll be taken to the User Guide on the project website.

2. The reclaim function purely matches up items that are in one calendar but not the other - it will do this simply based on matching start/end time, subject and location if the item was not synced one-way by OGCS in the first place. Once reclaimed (paired up) if you delete an item in Google, then OGCS will delete the associated item in Outlook - that's the point of two-way sync and there's no way to prevent synced deletions in one calendar.
I suspect you don't particularly want to anyway. Just performing a one-way Full Sync (press `Shift` and click `Sync`) before then turning on two-way sync should be enough.
Any items that get deleted you didn't want to be can be recovered from the Deleted Item folder in Outlook or Google Bin.

3. Just select "Start on login" and "Start in tray"
