### ISSUE TITLE
Error in syncing recurring event with end date - showing in Outlook as never-ending recurring event

### ISSUE THREAD

**Issue by asalomark** [phw198/OutlookGoogleCalendarSync#1253]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.7  
**Edition**: Installed / Portable  
**Sync Direction**: G->O

**Bug Description**  
I have a recurring event on Google calendar that stopped at a specific date.  It had previously been ongoing, but I changed it to end on a date in July.  For some reason, the recurring event remains ongoing in Outlook even after a full sync.  Not sure what else I can do to tell Outlook to stop the recurring event.  I see in the below copy of what shows up on my screen, that is says "1 are exceptions to recurring events."  I'm not sure if that's relevant.  I have attached a text copy of the OGcalsync log. 

**Steps to Reproduce the Issue**  
1. Go to Google Calendar.  Create an ongoing recurring event.  Sync with Outlook.  Change the ongoing recurring event to a specific end date. Sync with Outlook.  

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsynclog.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/6931346/OGcalsynclog.txt)
[OGcalsynclog.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/6931382/OGcalsynclog.txt)

**Comment by phw198** [comment]
Your log files show you syncing from Outlook to Google, yet your steps to reproduce the issue talk about making a manual change in Google and expecting that to sync to Outlook?

Can you clarify what the issue is and how you have OGCS configured?
