### ISSUE TITLE
Reverse sync order

### ISSUE THREAD

**Issue by joliecd** [phw198/OutlookGoogleCalendarSync#1255]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
During the two-way sync, Outlook always tries to delete events in Google, they are usually new Google events that need to be synced with Outlook. Since outlook compares to Google first, it is constantly asking me to delete those items before I get the chance to add them to outlook.  Also, I am sort of confused why this is happening.  I have merge entries selected so I don't understand why Outlook's items are trying to delete Google entries instead of just trying to delete from google deleted Outlook events since the last sync, for example. 

**Describe the solution you'd like**

I would like to be able to choose which calendar syncs first.   For the two way sync in my case, I would like to Sync Google first instead of outlook.

**Describe alternatives you've considered**
Only delete "deleted" items. 

**Additional context**
I am using Reclaim.AI, so if I delete something from my Google calendar during the sync it changes how that application behaves.

**Comment by phw198** [comment]
You haven't said what version of OGCS you are using, but if it's the latest alpha, then the behaviour you describe is not expected anyway and a bug issue should be raised.

How are the new items in Google being created? Are you duplicating an item in Google that was previously synced by OGCS?

**Comment by joliecd** [comment]
I'm using 2.8.7.0
 I'll try to attach some logs.  The new items are being created by reclaim.ai and putting them on the Google calendar.  I'm not aware of the technical details behind this

**Comment by phw198** [comment]
So what are the order of events? OGCS syncs Outlook items to Google, Reclaim AI adds some new events to Google, OGCS then deletes those new ReclaimAI events instead of syncing them to Outlook? Or has ReclaimAI modified an OGCS synced item and then this is subsequently deleted by OGCS?

**Comment by phw198** [comment]
Closing this as it doesn't matter which direction is synced first - items that are new in Google don't get deleted, so suspect ReclaimAI is doing something odd.
