### ISSUE TITLE
Consistant Error on Sync Fail

### ISSUE THREAD

**Issue by rwilsondoyle** [phw198/OutlookGoogleCalendarSync#1257]
**Are you already using OGCS?**
2.8.0.0

**Describe the question you have**
I have used OGCS for years and just purchased it a few months ago. My hard drive crashed and I replaced it and install OGCS. Everytime it runs now (for a week or two) it shows the attached Error screen. I have to click the YES button to continue and all is well. But if I don't see it, it will run every hour so I have to click it 7 times to catch up. I have attached my log file also. Thanks for the help. It is a great app and was greater, I figure I set something up wrong. 

Ron Doyle 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6955950/OGcalsync.log)
![OGCS](https://user-images.githubusercontent.com/71282140/128740519-4ccc3303-54df-48cc-af35-056e8e516446.png)

**Comment by phw198** [comment]
Hi @rwilsondoyle and thanks for your usage and support of OGCS :slightly_smiling_face: 

The advise when encountering issues is to always upgrade to the latest release, alpha if available. I believe the issue you describe has indeed already been fixed.

:arrow_double_up: Please upgrade by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

If this fails for some reason, [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).
