### ISSUE TITLE
Persist Outlook "Out of Office" and Tentative statuses

### ISSUE THREAD

**Issue by NoisyTigress** [phw198/OutlookGoogleCalendarSync#1259]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Portable

**Problem Description**  
When syncing from Google -> Outlook (either one-way or bidirectional) Google overwrites the status to Busy since Google only recognizes Free/Busy, but not Tentative or Out of Office. This is intermittent, but 

happens about 50-75% of the time, which means going back and updating Outlook so my calendar is up-to-date.

**Steps to Reproduce the Issue**  
1. Set status in Outlook to Out of Office
2. Start sync
3. Outlook -> Google sync works fine
4. Google -> Outlook updates the Attribute "Free/Busy" from "olOutOfOffice" -> olBusy
![2021-08-11 13_54_37-Outlook Google Calendar Sync](https://user-images.githubusercontent.com/87985467/129087005-a75872b4-9913-4b9c-a8cb-5d60cf8f93ce.png)

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:package: This should now be achieved with [hotfix v2.10.1.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12447963/v2.10.1.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

If Google's availability is simply "Busy", but Outlook is one of the following, then Outlook's status will persist:
* Out of office
* Tentative
* Working elsewhere

Please let me know how it goes.

**Comment by toasterking** [comment]
**THANK YOU** for fixing this in 2.10.2! :D
