### ISSUE TITLE
OGCS Automatically Being Terminated Upon Load - Cannot Open At All

### ISSUE THREAD

**Issue by Judi-mae** [phw198/OutlookGoogleCalendarSync#1261]
**OGCS Version**: v2.8.7.0
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
![OGCS error Aug-21](https://user-images.githubusercontent.com/85355787/129385871-f672c0c9-c4bb-489e-8f21-c1bf46b66644.png)
![OGCS Terminated](https://user-images.githubusercontent.com/85355787/129385884-b90812e2-7b6e-40e8-8f6d-8219a960da6d.png)

Hi guys, I cannot upload a log file as I cannot open the program. I've only ever created a log file by using debugging mode so not sure of another way to generate one. Have searched my C: drive for OGcalsync.log as well as looked in the app folder on my hard drive (C:\Users\User\AppData\Local\OutlookGoogleCalendarSync\app-2.8.7-alpha) and had no luck - please advise if there's another way.

Anyway! I am seeing the error message 'Outlook and OGCS are running in different security elevations. Both must be running in Standard or Administrator mode.' after the splash screen upon loading. I click OK and the second dialogue box comes up - 'Application Terminated'.

I have made no changes to my 'security elevations'. I don't know what this means to check it. I wanted to check whether anybody was seeing a similar issue before I uninstalled OGCS and tried reinstalling it...

**Steps to Reproduce the Issue**  
1. Try to open OGCS

**Comment by Judi-mae** [comment]
I have done extensive research and worked out the issue. FIXED.

**Comment by phw198** [comment]
Hi @Judi-mae, would you be able to describe what the solution was for this, in case it helps others out?

Normally this message about different security elevations means that either OGCS _or_ Outlook has been started using the option "Run As Administrator", and either they both need to be running as adminstrator, or neither of them.

**Comment by Judi-mae** [comment]
Hi @phw198, no problem! I was troubleshooting my laptop last week, specifically Outlook. It had put it into exactly that: 'run as admin' mode. I didn't realise nor did I know how to turn it off. I ended up doing loads of research, working it out, and re-troubleshooting in order to turn it off. The sync with OGCS is now working fine again :)
