### ISSUE TITLE
Update detection 

### ISSUE THREAD

**Issue by joostiphone** [phw198/OutlookGoogleCalendarSync#1262]
Not a big issue, just wanted to mention that the update detection doesn't seem to work. Best regards! Joost.
----

**OGCS Version**: v2.8.7.0
**Installed or Portable**: Installed

**Problem Description**  
The app doesn't find an update of OG

**Steps to Reproduce the Issue**  
Press the update button with or without Alpha version selected. I updated manually. 

**Any other information**  
Trying to go from 2.8.7.0 to latest (2.9.0).

**Comment by phw198** [comment]
Thanks @joostiphone - as I am progressively rolling out the update, only a small percentage of users are currently being targeted, so  this would be expected behaviour. 

Manually downloading the update for those keen to get on board is the right way to go 👍
