### ISSUE TITLE
Update popup keeps popping up no matter what choice i make.

### ISSUE THREAD

**Issue by buttonics** [phw198/OutlookGoogleCalendarSync#1263]
**OGCS Version**: v2.8.0.0  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
keep getting update popup. 
![image](https://user-images.githubusercontent.com/10638027/129629147-cb4a2d1b-95f2-4b4b-81c8-554cf4aa8752.png)

**Steps to Reproduce the Issue**  
Every time I start pc I get the message.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Your screenshot looks corrupted? Is that really how it's displaying, with the release notes inside the sync window somehow?

:spiral_notepad: Also, please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by buttonics** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6997452/OGcalsync.log)

It starts like this :
![image](https://user-images.githubusercontent.com/10638027/129673044-11aa1cad-68c7-460c-8a7e-60af23fcc84c.png)

After resizing it looks like this : 
![image](https://user-images.githubusercontent.com/10638027/129673158-4f92d03f-8546-4eef-bebb-057e62f328de.png)

**Comment by kctechpro** [comment]
I have the same problem.  Can't skip, and don't want the alpha.

**Comment by jpr85338** [comment]
same issue, resolved by manually downloading and installing v2.9

**Comment by phw198** [comment]
I think this may be a product of the fact v2.9.0 is being rolled out in a phased mode, so it's somehow knowing an update is released, but it's also not available to you yet. I'll try and investigate further.

As @jpr85338 says, manually downloading [Beta v2.9.0 Setup.Exe](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.9.0-beta/Setup.exe) and installing that will resolve the problem.

(@buttonics Unfortunately you have configured logging to `OFF` so there is not really anything in your logfile!)

**Comment by phw198** [comment]
I've added additional checks to make sure no notifications of alpha releases are made if alphas are set to false in settings. 

Also stopped trying to show GitHub webpages in the application webbrowser, as it's no longer compatible - will now just show a hyperlink to view the release notes in your default browser.

These changes won't be available until the next beta though - v2.10.0 (or v2.9.1 alpha).
