### ISSUE TITLE
Maybe link this page in wiki to set right registry values for outlook shipped with office 365

### ISSUE THREAD

**Issue by MatthiasNeuhaus** [phw198/OutlookGoogleCalendarSync#1264]
**Is your feature request related to a problem? Please describe.**

A was really annoyed by the pop up information occurring on every sync that OGCS did.

**Describe the solution you'd like**

I found in the wiki help for the Outlook trust center settings. As I was not able to change them, I searched for some registry keys to set. Sadly found nothing directly fitting to office 365. Now (after a long time) I found a page with settings, that worked for me. Maybe you could help other Users by linking this on your wiki page?!

https://www.sagecity.com/ca/sage_50_accounting_ca/f/sage-50-ca-printing-emailing-and-importing/123303/what-are-current-regedit-or-gpedit-fixes-to-bypass-mapi-popups-click-to-run-office-365

Thanks a lot - I love your tool!

**Comment by phw198** [comment]
Thanks for the research and suggestion! I have duly [updated the wiki page](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security#outlook-for-office-365) with those instructions :+1:

**Comment by MatthiasNeuhaus** [comment]
Thanks a lot for your fast reaction 😉
