### ISSUE TITLE
No permission for Outlook

### ISSUE THREAD

**Issue by RGBeaumont** [phw198/OutlookGoogleCalendarSync#1266]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
On upgrade to 2.9.0.0, sync fails becuase it reports there is no permission to write to Outllok

**Steps to Reproduce the Issue**  
1.Run Sync
1. get error report
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7042087/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7042091/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
The error message seems pretty clear - you need to pick a calendar for which you have write permissions:

> You don't have permission to create an entry in this folder. Right-click the folder, and then click Properties to check your permissions for the folder. See the folder owner or your administrator to change your permissions.

Looking back through your log, when you upgraded to v2.9.0, you were syncing with the Default Outlook calendar...38 seconds later you changed the calendar to "Birthdays", which is no doubt read-only, and all subsequent syncs failed.

**Comment by phw198** [comment]
I was hoping to maybe add an enhancement and check the permission level on the calendar folders, but it seems Microsoft don't surface this detail via the COM model :roll_eyes:
