### ISSUE TITLE
Website popping when I launch the app

### ISSUE THREAD

**Issue by rajivdaga** [phw198/OutlookGoogleCalendarSync#1267]
**Are you already using OGCS?**
Provide the version number. 
I have been a long time user of 2.8 (portable) and recently updated to 2.9 (portable)

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.
post the recent update whenever I launch the application it is also loading the website home page which was not happening 2.8. Is there a way I can disable this?

**Comment by phw198** [comment]
It should only do this the first time the new version is opened. 

:spiral_notepad: Would need to see your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) for further detail if it really is happening every time.
