### ISSUE TITLE
Outlook - Googel Calender Syn

### ISSUE THREAD

**Issue by PaFr1972** [phw198/OutlookGoogleCalendarSync#1272]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by PaFr1972** [comment]
Hello everyone, I have been redirected to your homepage by eKiwi-Blog Tutorials because they can't help me with my problem.
Currently I use "Outlook Google Calendar Sync" and I have some problems with it.
Get a huge error message every time I sync and when I enter data in Outlook in the calendar, they are not transferred to the cell phone.
However, when I make entries in cell phone, they are transferred.
What can I do?

**Comment by PaFr1972** [comment]
[outlook_delete-prev.csv](https://github.com/phw198/OutlookGoogleCalendarSync/files/7104268/outlook_delete-prev.csv)

**Comment by PaFr1972** [comment]
> > Checklist:-
> > 
> > * [x]  [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://camo.githubusercontent.com/7b4c3c86b3b43815a41e90a6eb242b545cd8ae3c9163c9f19cf3d44467a954a9/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f72656c656173652f7068773139382f4f75746c6f6f6b476f6f676c6543616c656e64617253796e632f616c6c2e737667)
> > * [ ]  Reproduce the issue
> > * [ ]  Complete the information below
> > * [ ]  Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
> 
> **OGCS Version**: v1.2.3.4
> **Edition**: Installed / Portable
> **Sync Direction**: G->O / O->G / O<->G
> 
> **Bug Description**
> A clear and concise description of what the bug is.
> 
> **Steps to Reproduce the Issue**
> 
> 1. Go to...
> 2. Click on...
> 
> **Any other information**
> Any additional information that may help troubleshoot the issue.
> 📎 Attach your `OGcalsync.log` file.

Hello 
until when can I count on an answer ?

**Comment by phw198** [comment]
You need to follow the instructions for reporting an issue.

- v1.2.3.4 is not a valid OGCS release, certainly not the latest.
- Reproduce the issue
- Upload your OGcalsync.log file
- A "huge error message" is hardly anything to troubleshoot with

**Comment by PaFr1972** [comment]
Hello 

attached is the representation.

 

According to the system, this is already the current version.

 

What can I do ?

 

I am looking forward to your feedback.

 

Best regards /mit freundlichen Grüßen


Patrick Freche | REFA Prozessorganisator | Solutions and Ergonomics at Work

Master of Technical Management (CCI)

**Comment by phw198** [comment]
:paperclips: Unfortunately, files and screenshots can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by PaFr1972** [comment]
![Outlook_Googel1](https://user-images.githubusercontent.com/89916465/132989070-d01a7dba-3301-4ac5-987d-be0c321eb7cd.JPG)
![Outlook_Googel2](https://user-images.githubusercontent.com/89916465/132989073-c5319d8b-e795-44f9-b297-ea4f9e96c86f.JPG)

**Comment by phw198** [comment]
You still need to provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) as indicated in the instructions when you opened the issue 

I'm not sure what the screenshot of Outlook's send and receive failures has to do with OGCS.

**Comment by PaFr1972** [comment]
Hello

have uploaded various pictures on the site.

Best regards /mit freundlichen Grüßen

Patrick Freche | REFA Prozessorganisator | Solutions and Ergonomics at Work

Master of Technical Management (CCI)

**Comment by phw198** [comment]
I think it may be better for you to source a different application, perhaps a paid product that provides a level of support more in keep with your needs.
