### ISSUE TITLE
Application not Found when starting OGCS

### ISSUE THREAD

**Issue by ravenswood** [phw198/OutlookGoogleCalendarSync#1273]
**OGCS Version**: v2.9.0
**Edition**: Installed / Portable  
**Sync Direction**: n/a
![image](https://user-images.githubusercontent.com/5385476/131676191-08c662de-255d-4754-b9e6-c52450de0061.png)

**Bug Description**  
After unzipping OGCS and running the executable, I get the splash screen and the following error:

![image](https://user-images.githubusercontent.com/5385476/131675560-493ddf50-6eb9-4557-82e4-6809fc82f1f0.png)

Log attached
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7091240/OGcalsync.log)

**Comment by ravenswood** [comment]
I have worked out what the problem was here. I am using Portable Chrome as my default browser. As Windows doesn't seem to properly store its location, when OGCS started up it was unable to find Chrome. I installed the full version of Chrome and it is now  working perfectly!

**Comment by phw198** [comment]
Incidentally, I had [already developed](https://github.com/phw198/OutlookGoogleCalendarSync/commit/345ac2844ac8dca3c7be620d8c33cb7a8ec19d26) what is hopefully a fix, with further checks in the registry to try and determine which browser to use.

This will be included in v2.9.1
