### ISSUE TITLE
Wrong time in one specific recurring event

### ISSUE THREAD

**Issue by robsonrosa** [phw198/OutlookGoogleCalendarSync#1274]
**OGCS Version**: v2.9.0.0
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
I have several events in my outlook calendar that are successfully synced with Google Calendar, but I have one specific recurring event that always get a wrong datetime. In my Outlook Calendar it has scheduled for every day at 15:00, but after syncing, the recurring in Google Calendar is created for every day at 14:00. I tried to delete recurring event and to create it again and the problem persists. I have deleted the recurring event in Outlook and Google manually and then created again in Outlook and the problem persists. It occurs only with this specific event. 

**Steps to Reproduce the Issue**  
1. Create a recurring event for every day at 15:00 in Outlook
1. Sync with Google Calendar
1. Check the created event with wrong time (14:00).

**Any other information**  
- My timezone is `(UTC-03:00) Brasilia`.
- Event Configuration in Outlook
![image](https://user-images.githubusercontent.com/2868031/131683699-8990e945-eda9-4651-abbd-2c786d4618f6.png)
- Outlook Calendar event
![image](https://user-images.githubusercontent.com/2868031/131682631-219a9da7-dafe-4058-9b29-2e1a8ce73897.png)
- Google Calendar event
![image](https://user-images.githubusercontent.com/2868031/131682743-0493d1aa-9759-425e-8183-2dd06117f00d.png)

**Logs**
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7091577/OGcalsync.log)

**Comment by phw198** [comment]
So you look to be based in Brazil and your computer is running in that timezone, which doesn't observe daylight saving.
```
2021-09-01 09:26:49,006 INFO  1 OutlookGoogleCalendarSync.Settings [598] -    System Time Zone: Hora oficial do Brasil; DST=False
```
But you've configured a custom timezone mapping for Brazil to Canada, which _does_ observe DST.
```
2021-09-01 09:26:48,987 INFO  1 OutlookGoogleCalendarSync.Settings [490] -    Custom Timezone Mapping:-
2021-09-01 09:26:48,987 INFO  1 OutlookGoogleCalendarSync.Settings [491] -      (UTC-03:00) Brasilia => Newfoundland Standard Time
```
Remove that mapping, force a full `Shift`+`Sync` and it should resolve.

**Comment by robsonrosa** [comment]
Hi @phw198 

It worked!! 🎊 👏 

I have no idea why that mapping was created. I can't exclude that mapping, but I've changed to something useless:

![image](https://user-images.githubusercontent.com/2868031/133135441-36918070-7204-40b0-94aa-926a1fd40f07.png)

Thanks!!

**Comment by tiagojufr** [comment]
I think I have the same issue. @robsonrosa how do you get to that Timezone Mapping screen? I can't find it anywhere

**Comment by phw198** [comment]
@tiagojufr If you have a custom timezone configured, you will have a "Custom Timezone Mapping" button on the Settings > Outlook page, just above the "Regional Date Format" section. If it's not showing, it's unlikely you have this issue.

**Comment by tiagojufr** [comment]
@phw198 I don't have that button. I noticed some of my meeting times were off by 1 hour on a very special scenario. I work in Portugal for a USA based team. The recurred meetings were created with a US time zone. One of the countries updates his Daylight Savings clock 1 week before the other. During that week, the meetings appeared correctly on my Outlook (1 hour earlier or later than usual for me, I don't recall) but on my Google calendar they were appearing at the same time as if there were no Daylight Savings changes.

**Comment by phw198** [comment]
@tiagojufr I think for this, you need to make sure the timezone is set right on the specific Google calendar you are syncing to (note, this can be different from the "primary timezone" in the main settings screen in Google)? Can you confirm what that is set to?

**Comment by tiagojufr** [comment]
@phw198 I have it set as GMT+00:00 Lisbon time

**Comment by phw198** [comment]
@tiagojufr OK, and what is the timezone held on the actual recurring appointment in Google? Does it match the timezone in Outlook for the appointment?

TBH, the best way to proceed on this would be:
1. Make sure you are on the latest alpha release of OGCS
2. Set OGCS to one-way sync (O->G) if currently two-way sync
3. Delete the Google recurring series
4. Run a manual sync to recreate the series
5. Upload your `OGcalsync.log` file

Thanks

**Comment by tiagojufr** [comment]
@phw198 the Outlook time zone is UTC-07:00 but the Google time zone is GMT+00:00. I don't feel comfortable on sharing the log as it contains some sensitive data on my meeting names. 
I think you should be able to reproduce this if you create a Outlook recurring event with a time zone different from yours (assuming both time zones change their daylight savings clocks at different dates). You will notice that on the days where 1 of the zones already changed DST but the other didn't yet you will find that the Google appointment time does not match Outlook's time (it has a 1 hour diff due to DST).

**Comment by phw198** [comment]
> the Outlook time zone is UTC-07:00 but the Google time zone is GMT+00:00

That'll be your problem then. OGCS should be able to detect that Outlook is `UTC-7` and convert that to an IANA timezone eg `America/Denver`. But it's not and it's getting set to GMT (and the time changed instead no doubt), which is clearly wrong and would result it poor/non-existant DST calculation. 

Without a log file though I would not be able to troubleshoot further and it will be specific to your invitation and Windows config as to the particular issue. That said, pretty sure this is all catered for with the "custom timezones" I mentioned previously, but you've never said what version of OGCS you are running. Make sure it's at least v2.9.0.
