### ISSUE TITLE
A few e-mail box => GCalendar

### ISSUE THREAD

**Issue by jakublekij** [phw198/OutlookGoogleCalendarSync#1275]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**Edition**: Installed / Portable  
**Sync Direction**: O->G

**Bug Description**  
I have outlook and there 2 different e-mail box.
I wanted to synchronize this two box to one google calendar (one direction: outlook=>Google but from a few mails box), so I open two portable version instance OutlookGoogleCalendarSync, next set  two different e-mail box address.
Unfortunately, it is still export from only one e-mail box.

Goal: have at Google calendar view of 3 calendars (two from outlook, one from Google)

:paperclip: Attach your `OGcalsync.log` file.
![img](https://user-images.githubusercontent.com/89930475/132088931-980db55d-ce95-48b6-b5eb-decee712beda.png)

**Comment by phw198** [comment]
This should work and other users are doing this. Are you definitely configuring both portable OGCS deployments with separate settings.xml files?

I assume you've followed guidance in #165 ? Why have you not upgraded to v2.9.0? What version are you running?

**Comment by jakublekij** [comment]
Yes, it was my mistake. I used version 2.7.0. At 2.9.0.0 is good.
Thank you.

sob., 11 wrz 2021 o 12:34 Paul Woolcock ***@***.***>
napisał(a):
