### ISSUE TITLE
Notifications not appearing on Android phone.

### ISSUE THREAD

**Issue by sigmablock1** [phw198/OutlookGoogleCalendarSync#1276]
Version 2.9.0 
Installed
Sync direction O<->G

I don't know when it started but, notifications on my android phone when syncing from outlook are not appearing. The events appear in the Google Calendar, but the notifications do not show up. I only realised this when i had my phone in my hand and a notification popped up on my laptop but didn't on the phone, and didn't appear even after the start time of the appointment. Syncing the calendar entries both ways works fine, it's just the notifications that aren't working properly.
There are several reasons why I don't think its the phone/Android.
Older entries, eg recurring reminders to transfer money, still produce a notification.
If I enter an appointment in the Google Calendar app it will generate the relevant notification on the phone (and in Outlook).
Also, just as an experiment, I uninstalled OGCS and installed gSyncit. When i set up some test entries, they produced the corresponding notifications on the phone. Any advice as to what i may be doing wrong, greatly appreciated.

I am using version 2.9.0 installed, which I downloaded after discovering the issue in version 2.8.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7098559/OGcalsync.log)

If you need anymore information, please ask.

**Comment by sigmablock1** [comment]
Most up to date log,

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7098589/OGcalsync.log)

**Comment by marcosegato** [comment]
I had the same issue but then I noticed that the reminders' option was not properly enabled (I don't know if due to my mistake or maybe affected by the upgrade to 2.9.0 release).
Check in "Settings" / "Sync Options" / "What": "Reminders" option must be enabled to have them synced.

**Comment by sigmablock1** [comment]
Well, that seems to be the answer. Thank you. I have made 2 separate tests that have functioned correctly.
Confused as to how though, and for 2 reasons.
First, "old" notifications were still working ok. And second, new ones were failing in version 2.8 before I updated to 2.9 (I only updated to see if that would cure the problem) and in 2.8, I hadn't altered anything in the settings since i was happy with the way it worked when I installed originally.
Thanks again.

**Comment by phw198** [comment]
@sigmablock1 I suspect you originally had a default notification set in your Google calendar settings, which was then removed at some point:

![image](https://user-images.githubusercontent.com/11843015/132942519-a821db86-6039-40e0-8ba6-97ab160fce4d.png)
