### ISSUE TITLE
The option "Push Outlook changes automatically" does not SEEM to be working

### ISSUE THREAD

**Issue by MilosBranko** [phw198/OutlookGoogleCalendarSync#1277]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v. 2.9.0.0
**Installed or Portable**: Installed

**Problem Description**  
Actually I can get the syncronisation manually, by the button Sync\"Start sync", but I would like the sync to happen automatically in G. Cal. every time I change something in Outlook (2010). That is what I supposed to be the aim of the option Sync.Options\When\"Push Outlook changes automatically". So I put this checkmark on, but nothing happens. 
Where am I wrong? What I misunderstood? And, above all, how can I get the outcome I need?

**Steps to Reproduce the Issue**  
1. post a new item in Outlook cal. and save
2. chek in Google cal. to see if the change is pushed automatically
3. no change in Google Cal., even refreshing the page

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Push sync triggers every 2 minutes - it's not instant. I would need your log file covering the period you are going through the above steps to evidence what you describe and to investigate further.

:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by MilosBranko** [comment]
Thank you for your kind reply. 

Please, excuse me for not posting this reply on GitHub, but I do not want to add there my log file, including my Gmail address, even public or private.

After more tests on my pc & Outlook 2010, I confirm that items added or changed in OCal. do not sync automatically on GCal, , even after a much longer time than 2 minutes, practically they never do. Probably I mistook some setting.

So I attach here the log file and I remain awaiting for your reply, with no hurry.

Thanks

**Comment by phw198** [comment]
:paperclips: Files and screenshots can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

Would also be helpful if you could be set logging level to `FINE` first, add an item to outlook calendar, wait a couple of minutes, then provide logfile.

**Comment by MilosBranko** [comment]
Thank you for your prompt reply.

Unfortunately, things are getting too complicated for me (I mean: managing GitHub, creating a new gist (?), going on and on with posts, etc,), instead than exchanging a couple of emails, even if with needed attachments

So, I’m sorry, I must give up. 

Anyway, thanks again and, please, excuse me for the time you dedicated to me.

**Comment by phw198** [comment]
I understand - equally however, it is impossible to support and develop an application with tens of thousands of users via email. Thanks for your efforts.
