### ISSUE TITLE
Hide Sensitive information like meeting passwords

### ISSUE THREAD

**Issue by Nisar222** [phw198/OutlookGoogleCalendarSync#1278]
Feature request: An option to Strip all calendar (body) content. Just sync the Meeting header (Subject).

Organizations prevent sync with Google Calendar because it's outside their security perimeter. 

Outlook sync users may unknowingly sync Sensitive information like meeting passwords or other confidential data with Google Calendar. Whilst I understand the data is secured with Google but this may get users with strict infosec compliance in trouble.

I use OGC, because my office 365 prevent syncing with Gcal.  I need notifications and meeting reminders on my personal phone and watch.  I just need to see the meeting subject, not the embedded body information, which may contain sensitive information.

**Comment by phw198** [comment]
So you mean you want to uncheck the `Description` box?

![image](https://user-images.githubusercontent.com/11843015/132942672-9f54af0c-8f95-4947-b637-fc175e4ebb71.png)

Note, previously synced body/descriptions won't be removed when this option is unchecked, only future synced items. You will have to manually remove the body text once OGCS is no longer syncing that data.

**Comment by Nisar222** [comment]
Hi Paul,
Apologies, I didn't realize you had that option.. awesome!

Thanks for your response.

I can't tell you how much of a life saver your app is..

I need the appointments on Gcal so I can get a daily email summary and the
meeting reminder on my watch and phone.

Thank you so much for this great app!

I've already contributed, is there anything else I can do to support you?

Cheers,
Nisar

**Comment by phw198** [comment]
> I've already contributed, is there anything else I can do to support you?

Thank you - just evangelising OGCS to everyone you meet 😉
