### ISSUE TITLE
Error installing to Windows 10

### ISSUE THREAD

**Issue by adegeofroy21** [phw198/OutlookGoogleCalendarSync#1280]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.0 and older
**Installed or Portable**: Installed _and_ Portable

**Problem Description**  
\Any time I attempt to run either the installer or the portable application I receive an error with the title 'Application unexpectedly terminated!' and the text "Value cannot be null. Parameter name: oldValue". This is happening on a clean install of Win10 (sys info shared as an attachment below). I've attempted with v2.9.0 and v2.8.6 (the version I had been using successfully on my old machine).

**Steps to Reproduce the Issue**  
1. Download and attempt install using either installer or portable.

**Any other information**  
![OutlookGoogleCalendarSync_SAcLV1T0R9](https://user-images.githubusercontent.com/49454381/132352439-ad35f818-99fc-46b7-afc3-b155185ba912.png)

[System Information.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/7121812/System.Information.txt)

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by phw198** [comment]
Possible duplicate of #1282, which has a hotfix posted and would be worth trying.
