### ISSUE TITLE
Color mapping not working?

### ISSUE THREAD

**Issue by heutsm** [phw198/OutlookGoogleCalendarSync#1284]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0.0
**Edition**: Installed 
**Sync Direction**: O->G

**Bug Description**  
First of all, it's a fantastic program, thank you for that.
The program would be even better for me if I manage to get the mappings of the colors to work properly. Whatever i try, the color of the appointment in Google Agenda is always the color 'Banana' wich is choose at 'Set colour /category to' in 'How' on the tab 'Settings'.

The settings in color mapping is:
![image](https://user-images.githubusercontent.com/90608884/133154954-8ac85576-1f8b-41b5-b51e-460f14776e71.png)

In Outlook, i created the categories 'Op locatie' and 'In Amersfoort'.
The colors i choose to show as Google-colors, don't show in my agenda.
What am I doing wrong?

By the way, what does 'Test map' mean?

I really hope you can give me the solution.

**Steps to Reproduce the Issue**  
To be honest, it's probably not a bug, but i am doing something wrong.
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7157337/OGcalsync.log)

**Comment by phw198** [comment]
> ...Google Agenda is always the color 'Banana' wich is choose at 'Set colour /category to' in 'How' on the tab 'Settings'.

You'll want to uncheck that option then - that forces "all items synced to Google calendar set colour to banana" and will override any map you have.

The "test map" allows you to check what colour maps to what for each of the calendars, taking into account the custom maps in the table below. Change the drop down and the other one will change accordingly.

**Comment by heutsm** [comment]
Thanks for your answer! I unchecked the option you mentioned (tried this before) but the colors i choose won't show in my Google Calendar...
Is there something else i have to do?

**Comment by phw198** [comment]
Unless you've added an appointment or made a change in Outlook for it to sync, you'd need to do a full sync - press and hold `Shift` and click `Sync`.

**Comment by heutsm** [comment]
Wow, it worked, fantastic!
Thanks a lot for your help!
Just donated 10 GBP...

**Comment by heutsm** [comment]
I got one more question: 
I am looking for a way to give the agenda-items without a category (in Outlook) another color than the agenda-items i set in G-agenda directly. That way, i will see the difference in agenda-items in Google between agenda-items i put in directly in Google and the items i put in OUtlook.

Do you know of such a possibility?

**Comment by phw198** [comment]
No, you're correct, OGCS doesn't support this configuration. 

However, are you not able to sync from Outlook to a dedicated calendar in Google with that colour you want as default - then just overlay that calendar against your others? Or do you have to have all the appointments in a single calendar?

**Comment by heutsm** [comment]
I'll look into that. Thanks for the advice.
