### ISSUE TITLE
Could not determine exact Outlook version (Standard2019Volume)

### ISSUE THREAD

**Issue by James-Oakley** [phw198/OutlookGoogleCalendarSync#1287]
**OGCS Version**: v2.9.00
**Edition**: Installed / Portable  - not sure; I just ran Setup.exe and encountered the problem below

**Bug Description**  
On running the Setup.exe program downloaded from the Github Release, I was shown the splashscreen, and then an error log. The line that failed is:

`2021-09-17 17:09:20,546 ERROR  1 OutlookGoogleCalendarSync.OutlookOgcs.Factory [131] -  Could not determine exact Outlook version with codebase v16. Access2019Volume,Standard2019Volume`

**Comment by phw198** [comment]
This error shouldn't prevent OGCS from opening??

:package: I've now added some new product IDs so your `Standard2019Volume` should be recognised with [hotfix v2.9.0.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7192013/v2.9.0.9.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by James-Oakley** [comment]
Thanks, Paul - yes, I later discovered it hadn't prevented it from opening. The "would you like to report this error automatically" was the main window I could see, so it looked like it was reporting that the application had failed to start. I then realised that wasn't so.

Thanks for the hotfix.
