### ISSUE TITLE
OGCS not syncing "Focus time" from Outlook Insights

### ISSUE THREAD

**Issue by sanderssean** [phw198/OutlookGoogleCalendarSync#1288]
**OGCS Version**: v2.9.0.0  
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I have Outlook Insights create "Focus Time" on my calendar every day.  This used to sync with my Google calendar using OGCS.  However, recently (perhaps since installing v2.9.0.0, the Focus Time no longer appears on my Google calendar and previous instances going back to Aug 27 have also been removed.

I found the following reference to "Focus Time" in the debug log, attached (this was after I tried moving the Focus Time on one date from 1:00 pm to 1:30 pm to see if that would force it to sync):

2021-09-18 17:54:15,540 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [64] -  We've got 1 items selected for copy.
2021-09-18 17:54:15,545 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [73] -  9/20/2021 1:00 PM => "Focus time"
2021-09-18 17:54:15,562 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [84] -  **This item isn't managed by OGCS.**
2021-09-18 17:54:17,606 DEBUG  18 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [180] -  Untagging copied Outlook item
2021-09-18 17:54:17,622 DEBUG  18 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [187] -  9/20/2021 1:30 PM => "Focus time"
2021-09-18 17:54:17,628 DEBUG  18 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [268] -  Removed locallyCopied property.

I've emphasized where it says that this item isn't managed by OGCS.  Why is this?  Can it be forced to sync?

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7190728/OGcalsync.log)

**Comment by phw198** [comment]
I don't think that "Item isn't managed by OGCS" is really related - that is purely identifying if the item that has been copy/cut and pasted was previously synced by OGCS - and as you've raised, they are not being synced.

First thing that jumps out is your are only including these categories for sync: <No category assigned>,Low Priority,OGCS Steel,Reply urgently,Respond,Tracked,Urgent

Are focus time getting some other category?

**Comment by sanderssean** [comment]
Thanks for the response, PHW.  I'm not sure that's the issue, as "No category" is also checked (see screenshot attached).  Also, Focus Time was syncing just fine until a few weeks ago!

Maybe I should try go back to a previous version?

![image](https://user-images.githubusercontent.com/90989620/133942321-3ebafca7-68a5-4254-89a2-eb589c24cac6.png)

**Comment by phw198** [comment]
I think it would be safer to exclude no categories (uncheck them all) - that's the default. 

If that doesn't work, yes try downgrading to previous version again...

**Comment by sanderssean** [comment]
Paul, that seemed to do the trick: I changed Settings > Outlook >  Filter
Categories from "Include" with all boxes checked to "Exclude" with no boxes
checked.  The weird thing is that I haven't changed these settings in over
a year, so I guess the new version treated this setting
slightly differently.

Many thanks for your help!

**Comment by phw198** [comment]
Glad that resolved it 👍
I don't think there's anything that changed in this area, so suspect you inadvertently changed the dropdown from Exclude to Include, and the checkbox selections automatically invert.

Doing some further testing, I've noticed that Insights/Cortana automatically adds its own category to the Focus Time appointment: "Green category". However, this is not a "normal" category as it only exists on the individual appointment and not in the category master list. OGCS only has visibility of the master list, so you cannot select this focus time category for inclusion 👎 

![image](https://user-images.githubusercontent.com/11843015/134338438-79404c3b-b33f-414e-bf21-30a96476fcec.png)
