### ISSUE TITLE
Meeting appointment sync from Google to Outlook deletes the invites

### ISSUE THREAD

**Issue by ErwinWarmerdam** [phw198/OutlookGoogleCalendarSync#1291]
Hello I have a strange issue..........

**OGCS Version**: v2.9.0.0
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
When creating a meeting appointment in Google with invites, users are not able to accept the meeting invite after the sync to Outlook was done.

Also when already accepted (before the sync to Outlook is done) users get removed from the meeting and are not able to accept. They receive an error message they are not allowed to join this meeting.

When the sync is finished from Google to Outlook, in Outlook it looks like the meeting invite has been changed to a "normal" appointment.

**Steps to Reproduce the Issue**  
1. In Google calendar create a new appointment and add invitees
2. Let one user accept (appointment should appear in google agenda of the user)
3. Sync with Outlook
4. Let other user accept (will result in error)
5. Let first user check Google agenda (the appointment should be removed)
6. In Outlook check the appointment (this should now be a normal appointment instead of a meeting request)

**Extra information**
Outlook version: Microsoft® Outlook® for Microsoft 365 MSO (16.0.14326.20384) 64-bit 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7209150/OGcalsync.log)

**Comment by phw198** [comment]
2-way sync and cloaking the attendee email addresses would seem like a Bad Idea. Can you disable the "cloak email address in Google" and see if that makes any difference?

**Comment by ErwinWarmerdam** [comment]
Thank you for the tip. 
I have changed the settings and now it seems to be working as expected. Again thanks for the tip!

**Comment by phw198** [comment]
Fantastic! I'm glad that was the answer - I've [added it to the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-am-i-getting-undeliverable-notifications-from-google-for-recipients-ogcs) :slightly_smiling_face:
