### ISSUE TITLE
Recurring event deleted when days in the past reached

### ISSUE THREAD

**Issue by danji77** [phw198/OutlookGoogleCalendarSync#1292]
**OGCS Version**: v2.9.0.3
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I noticed yesterday (Sep 21) that OGCS wanted to delete a recurring event July 12 (all weekdays for three weeks). It was synced nicely between Outlook and Google Calendar and had not be touched. I noticed that it was 71 days in the past, and my sync is set up with a date range of 70 days in the past.

I allowed the sync to delete, and went on to reproduce the problem (same event date and recurrence, date range increased to 71 days in the past).

**Steps to Reproduce the Issue**  
1. Set date range to 71 days in the past.
2. On September 21, create Outlook event on July 12, recurring all weekdays for three weeks (end on July 30).
3. Perform sync.
4. Wait one day.
5. On September 22nd, redo sync, and OGCS requests to delete Google recurring event on July 12.

**Any other information**  
Deletion from Google would indicate that due to the days in the past, on the Outlook side the event is ignored, even if recurrence expands into the date range. This seems not the case on the Google side.
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7210448/OGcalsync.log)

**Comment by phw198** [comment]
I think #1279 already covers this issue, so please upgrade to v2.9.1

Thanks!

**Comment by danji77** [comment]
Sounds great. Checked for updates before raising the issues (including alphas). OGCS says I am on the latest version. Maybe because I got a test release for #1269.

**Comment by danji77** [comment]
Performed sync using v2.9.1 without issue.

**Comment by phw198** [comment]
Ah yes, quite right - I've not completed rollout of v2.9.1 to make it available to everyone yet.
