### ISSUE TITLE
"The Google calendar being synced with must not be read-only"

### ISSUE THREAD

**Issue by derechtemike** [phw198/OutlookGoogleCalendarSync#1293]
Hi,

I get the above Error while syncing. I struggle to find the right setting to change it. When I check in my Google account OGS have read, write and erase access to all caledars in the google calendar app. However, in the preferences of the specific calendar I can't find any setting what may cause the error.

Can you help?

BR

Michael

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issu
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7211007/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7211019/OGcalsync.log)
e
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7211027/OGcalsync.log)

**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Always mystifies me why this confuses people. You've select a a read-only calendar "Feiertage in Deutschland" to sync to - you don't have the ability to add events to it in the web view of the calendar, so how do you expect OGCS to be able to write to it? Pick a calendar you _do_ have write permissions on...
