### ISSUE TITLE
'No Google credentials file available'

### ISSUE THREAD

**Issue by kaoscoach** [phw198/OutlookGoogleCalendarSync#1298]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.7.0
**Installed or Portable**: Installed

**Problem Description**  
OGCS worked previously. My company switched to using ZScaler, so this might be an issue that is not solvable. I will attached the log file but I do not see the 'Google credentials file' it is trying to access. I also know that my company prevents access to Google drive and other services like that even though I can access Gmail, Calendar, Contacts, etc. It also might be possible that they are preventing the app itself from outbound access? but I guess I am not sure. I tried downloading v.2.9.1 or v.2.9.0 but they are getting flagged as viruses. I am willing to help troubleshoot if told what to do.

**Steps to Reproduce the Issue**  
1. \<Update>
1. Try to retrieve calendars, it errors.

**Any other information**  
\<Update here
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7227432/OGcalsync.log)

>

**Comment by phw198** [comment]
So do you get directed to the Google authorisation screen in your web browser, to allow OGCS access to your calendars? It appears that the response from this authorisation is corrupted, but it's unclear whether you are even able to provide the approval?

**Comment by kaoscoach** [comment]
Yes the browser opens and it says something like authorization code was received, you can close this window. Then it goes back to OGCS and does the same thing again. Just keeps opening browser tabs but never seems to get it past it. Unsure how to proceed.

**Comment by kaoscoach** [comment]
To clarify, I get the prompt to log into Google, then to approve OGCS, which I do. The response page is presented from 127.0.0.1 so I am not sure if the auth code is in that url? or if I can extract it to manually apply it somehow?

**Comment by phw198** [comment]
Hmm, I wonder if Zscaler is man-in-the-middle-ing (given that's what it does) the traffic from localhost. Have you tried copying and pasting that URL out into a different browser or an incognito window, see if that helps?

Do you have any control over the browser's proxy settings? There's normally an option for "bypass proxy for local addresses". Or can you temporarily disable the proxy manually just for that page - i.e. go through the authorisation with proxy on, then at localhost page, turn it off and hit F5?

Final option might to download a [portable version of Firefox](https://portableapps.com/apps/internet/firefox_portable) and use that for the authorisation process.

Unfortunately, I don't think there's any way to manually build the credentials file.

**Comment by kaoscoach** [comment]
I was able to get OGCS working by going onsite. When onsite, I think Zscaler is not in the path for the Google query. I was able to auth, retrieve and sync the calendars. Once that initial sync occurred, I am now able to sync when offsite and using Zscaler again. I think when I tried to do the update to v2.9.1, something caused OGCS to think it wasn't 'in sync' so it wanted to re-auth? That is when my issues arose. I think if OGCS  just used the previous/existing settings, I would not have run into this issue? I think the issue happened because I had to do a re-auth? So I am not sure if that can be taken into account for future updates? But I do not really know. I am just a user of this helpful utility, so I probably can't provide any 'developer' insights?

In the end, my issue no longer exists but I am not sure if it will occur again or if my company will block it when onsite in the future? Feel free to close this 'ticket'.

**Comment by phw198** [comment]
The file that manages your Google authorisation is `Google.Apis.Auth.OAuth2.Responses.TokenResponse-user` which should be in the same folder as your `settings.xml` and `OGcalsync.log` file. Might be worth taking a manual backup of this before any future upgrade, though it should be maintained automatically.

Also, a lot of the Google DLL files were updated in v2.9.1, so this may have caused the need to reauthorise - normally I only update the DLLs after a beta release.

**Comment by kaoscoach** [comment]
Thanks, I will do that going forward. I thought I have noticed that sometimes the OGCS files are in %appdata%\roaming and sometimes in %appdata%\local. It currently appears to be in %appdata%\roaming. What determines where it is located? and should it always be in %appdata%\roaming and I am just misremembering?

**Comment by phw198** [comment]
The installed executables and DLLs should be in `%LOCALAPPDATA%` and the log files and settings should be `%APPDATA%` (roaming).

If it's a portable deployment, then all the files are in the same place.
