### ISSUE TITLE
Prevent multiple instances of your program from running, especially in the tray.

### ISSUE THREAD

**Issue by plevintampabay** [phw198/OutlookGoogleCalendarSync#1301]
**Is your feature request related to a problem? Please describe.**
After you crash or hang and I have to kill you from Task Manager, when I restart I seem to frequently get 2 of you in the tray.  you 

**Describe the solution you'd like**
The second instance should pop a window saying it is already running.  You could ask then if they really want 2 instances.

**Describe alternatives you've considered**
I kill both and restart again.

**Additional context**
When I clicked to check for updates, your program hung.
Once you popped a confirmation window under your other windows. I had to kill you in Task Manager then too.

**Comment by phw198** [comment]
What version of OGCS are you running? v2.9.0 shouldn't allow popups behind the main window. 

The route cause that needs fixing here is the crash or hang that making you have to force close OGCS. Are you able to provide your logfile when this happens?

There are many users that want multiple instances and putting in controls around that will likely just cause other problems/challenges.

**Comment by plevintampabay** [comment]
this is no longer an issue

**Comment by phw198** [comment]
:link:  #1524
