### ISSUE TITLE
Entries from Google not set as private in Outlook anymore

### ISSUE THREAD

**Issue by DominikGuentensperger** [phw198/OutlookGoogleCalendarSync#1303]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
Entries from Google Calandar used to be set as private in my Outlook calandar. Recently, I discovered that this is not the case anymore. 

**Steps to Reproduce the Issue**  
I tried to switch the option "Set entries to private" on and off many times and tested the sync from google to outlook. I restarted the application, my computer, outlook, reconnected my google calandar. The results were always the same and none of the entries are set to 'private' anymore.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7249408/OGcalsync.log)
[OGcalsync.log.2021-09-28.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7249422/OGcalsync.log.2021-09-28.log)
.

**Comment by phw198** [comment]
You have only configured items to be synced as private as they flow from Outlook to Google - switch the "target" by selecting "For all items synced to Outlook calendar".

**Comment by DominikGuentensperger** [comment]
Hi.
Thanks for answering. You were right, I could fix it like that. I did not understand that entries can only be set as private for one direction. Also, I don't remember changing anything in these settings. Anyway, it works again. Thanks!
