### ISSUE TITLE
Given Key not present in Dictionary

### ISSUE THREAD

**Issue by miaferr** [phw198/OutlookGoogleCalendarSync#1304]
> Checklist:-
> * [ X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ X] Reproduce the issue
> * [X ] Complete the information below
> * [X ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed  
**Sync Direction**:  O->G 

**Bug Description**  
When I try to run a sync, it says "The given key was not present in the dictionary" I've been using the app for a few months now successfully. This only started happening after I updated the other day.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file
[Ferraina OGcalsync log 9-28-21.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/7254173/Ferraina.OGcalsync.log.9-28-21.pdf)

**Comment by phw198** [comment]
Duplicate #1289
