### ISSUE TITLE
Google entries are not synced to Outlook anymore

### ISSUE THREAD

**Issue by mayonezo** [phw198/OutlookGoogleCalendarSync#1305]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
O -> G seems to work, G -> O does not anymore. Newly created entries in Google are not detected anymore. Syncing used to work with previous versions. 

**Steps to Reproduce the Issue**  
1. Set sync to O <-> G
2. Start syncing process. 

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7259320/OGcalsync.log) file

**Comment by phw198** [comment]
Well it finds 227 events in your Google calendar every time, but I don't really see any evidence of any changes happening in either calendar. The Google calendar configured to sync in OGCS is "DB Netz AG" - are you sure that's where you're adding the new events?

If so, turn on "Create CSV files" under Application Behaviour > Logging and then check if the new event is recorded in `google_events.csv`.

**Comment by mayonezo** [comment]
I found out that the problem was between my mobile phone and google calendar, it had nothing to do with OGCS. After reactivating the google calendar app, Etar started syncing events to my google calendar again. Sorry for wasting your time!
