### ISSUE TITLE
Can't open executable at all.

### ISSUE THREAD

**Issue by ymyinfinity** [phw198/OutlookGoogleCalendarSync#1309]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Both

**Problem Description**  
\Can't open the program. Keeps saying Outlook Calendar Not Available, Calendar Calendar has been selected..." but when I choose OK, goes to "Application Unexpectedly Terminated!" Object reference not set to an instance of an object.
App then closes out, there's no way to start it up to debug.  Happens for both installed as well as portable versions.  Is there a registry entry somewhere I need to delete?

**Steps to Reproduce the Issue**  
1. Not even sure. how I got here, was just trying to set it up, was setting up hotmail calendar.

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
