### ISSUE TITLE
Help - OGCS stopped working this morning - Reseting Connection doesn't help

### ISSUE THREAD

**Issue by plevintampabay** [phw198/OutlookGoogleCalendarSync#1311]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
When OGCS attempts to sync, it continually give the error - The given key was not present in the dictionary.

**Steps to Reproduce the Issue**  
1. start OCGS
2. let it attempt to sync
3. get error
.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7304985/OGcalsync.log)

I disconnected the google connection and reconnected it.  Still did not work.

**Comment by phw198** [comment]
Duplicate of #1289 which has the hotfix.
