### ISSUE TITLE
Auto sync reports multiple errors; manual sync works fine

### ISSUE THREAD

**Issue by billlanding** [phw198/OutlookGoogleCalendarSync#1313]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.5  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
I am using Outlook and Google calendar on my PC laptop. I am syncing Outlook-Google with two profiles: default for my primary Google calendar (syncs both ways) and KTB for a shared calendar (only syncs Google to Outlook). When OGCS does an Auto sync it reports multiple errors ; manual sync works fine. log file attached.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7318046/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7318048/OGcalsync.log)

**Comment by phw198** [comment]
Sorry, I'd also opened #1314 before I read this. I'll close and track on the other issue...
