### ISSUE TITLE
Sync version: 2.9.1.0  Appointment update failed. Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT)) 

### ISSUE THREAD

**Issue by pjmonline** [phw198/OutlookGoogleCalendarSync#1315]
Since latest update.

Log attached
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7325355/OGcalsync.log)
.

**Comment by phw198** [comment]
Seems like you've lost permission to make changes on your default Outlook calendar. To start with, have you restarted Outlook and/or reboot - there doesn't seem to be any indication of this in your logfile...

**Comment by pjmonline** [comment]
Thanks Paul.

Seems to be working OK now.  I’ll keep an eye on it.

I appreciate the quick response.

Peter.
