### ISSUE TITLE
Add the default notifications when adding an event to Google Calendar

### ISSUE THREAD

**Issue by mgardes** [phw198/OutlookGoogleCalendarSync#1317]
Hello,

When i create an event directly on Google Calendar, the default notifications that i set in my parameters of this calendar are well added to my event (in my case, one hour before and 10 minutes before for normal events, and 0 day before at 05:00 and 1 day before at 20:00 for all-day events).

When i create the event on my outlook which is synchronized with the samed Google calendar, the event is well created on Google but there is no notifications added on it.

It will be great if the notifications could by added when the events are created on Google Calendar.

**Comment by phw198** [comment]
It sounds like you haven't checked the "Use Google Default" option next to the "Reminders" checkbox in OGCS settings?

**Comment by mgardes** [comment]
Yes it works. Thanks. But i have to set zero alerts on Outlook, otherwise the Outlook alert is synchronisez instead of the Google default ones.

Thanks a lot for your answer and for your program. Have a nice day.
