### ISSUE TITLE
Event created in Google with Notification will not get a Reminder in Outlook

### ISSUE THREAD

**Issue by Justheretoreportanissue** [phw198/OutlookGoogleCalendarSync#1318]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0  
**Edition**: Installed  
**Sync Direction**: G->O & O<->G

**Bug Description**  
Create an event with a Notification in Google Calendar. Run a Sync. The resulting event in Outlook will not have a Reminder.
In Sync Options I have the following Checked.
Merge with existing entries
Disable deletions
Confirm deletions
Location
Description
Reminders
The reverse works. Creating an event in Outlook with a Reminder will result in an event in Google with a Notification.
I have tested this for both G->O and O<->G and it is still the same.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Not something I have been able to replicate, following your steps:

![image](https://user-images.githubusercontent.com/11843015/137585017-91d75df8-1b7b-4a8f-b5bf-05b7f06d5c20.png)

**Comment by Justheretoreportanissue** [comment]
Ok, let me add a bit to this then.

This is my settings for Sync Options
![image](https://user-images.githubusercontent.com/63780150/137692536-ea27cef3-1fad-4e32-b692-da53245ca214.png)

My calendar in Google have a default Notification setting for 30 minutes.
![image](https://user-images.githubusercontent.com/63780150/137692713-57fdb6a6-988a-42a9-957b-9c89a74b466c.png)

If I create an event in Google and leave the notification setting at the default (30 minutes).
![image](https://user-images.githubusercontent.com/63780150/137693161-b04d790f-4a0e-42e5-ab57-375122153964.png)
![image](https://user-images.githubusercontent.com/63780150/137693255-85f11f8e-e578-4a78-92f1-ae4e80403a29.png)

It will not get a Reminder in Outlook after Sync.
![image](https://user-images.githubusercontent.com/63780150/137693483-811b724e-30e5-46cc-9510-c933a6f4aa7c.png)
![image](https://user-images.githubusercontent.com/63780150/137693591-7e2971b9-5a19-4c8c-a675-8072563b066d.png)

If I set any other Notification on the Google created event, like 1 hour, it will actually sync over to Outlook.

Expected behaviour would be that any, default or other, Notification in Google would be synced over to Outlook.
For all I can see the reverse works, ie a created event in Outlook with default Reminder will be synced over to Google with a correct Notification set.

(Maybe I'm doing it wrong and should have some other settings enabled. Please inform me in that case.)

Regards,
   /Jonas...

**Comment by phw198** [comment]
Thanks for the extra details.

:package: This should now be resolved with [hotfix v2.9.1.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7402985/v2.9.1.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes...

**Comment by Justheretoreportanissue** [comment]
Confirmed that a new event in Google with default Notification is now synced over correctly to Outlook with Reminder.

However... If I then later do any changes to the Notification in Google it will NOT sync over and update the Outlook Reminder. The opposite, Outlook to Google, with a change to the Reminder will get synced to the Notification. At least for an event created in Google with a default Notification to start with.
Settings are unchanged since above images.

Should I open a new issue for this? It's somewhat related. What do you prefer?

Regards,

    /Jonas...

**Comment by phw198** [comment]
The issue here is the default notifications aren't actually stored against the individual calendar events, but the _calendar_ they are on. The default sync mode is to only sync items that have been modified since the last sync - which none have if you alter the calendar notifications.

The work around would be to perform a **full** `Shift+Click sync` after you have made changes to the Google configuration.

**Comment by Justheretoreportanissue** [comment]
I might not have been clear, or I do not understand.
I have not made a change to the default calendar Notification setting in Google, I have made a change to the Notification setting for an individual calendar event in Google (that used to have the default calendar Notification setting). This change is not synced over to the Outlook calendar Reminder for that individual event, which I think it should (the item has been changed/modified).
Please tell me if I should clarify further or supply more example.

Regards,

    /Jonas....

**Comment by phw198** [comment]
OK yes, I have now also reproduced that issue....but unfortunately it's a bug with Google. When the reminder is changed and saved, it does not update the last modified timestamp! 

Given this is what OGCS relies upon when doing it's differential sync, the only work around is to either edit some other attribute on the event (during or after the edit to the reminder), or running a full sync in OGCS as described earlier.

**Comment by Justheretoreportanissue** [comment]
Ok, thank you for explaining.
It'll probably be a big rework to have this to work since there is no support in Google for this.

Regards.

   /Jonas...

**Comment by phw198** [comment]
Just reopening until v2.9.2 is released with the partial fix.
