### ISSUE TITLE
"Confirm deletion" steals focus

### ISSUE THREAD

**Issue by Big-Gaz** [phw198/OutlookGoogleCalendarSync#1321]
**OGCS Version**: v2.9.1.0
**Installed or Portable**: Installed

**Problem Description**  
The window asking whether to confirm deletion steals the focus, which is *extremely* annoying when concentrating on another program, e.g. editing videos / streaming games.

**Steps to Reproduce the Issue**  
1. Delete an item from Google.
1. Start doing something in another window.
2. Wait for Confirm Deletion window to appear.

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Thanks for raising this.

:package: This should now be resolved with [v2.9.1.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7403650/v2.9.1.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Note, however, that if you are minimising OGCS to the task tray notification area, message box windows will still steal focus. This seems to be a limitation of Windows re-instantiating the window on restoration and it automatically appears on top of everything.

Let me know how it goes.

**Comment by Big-Gaz** [comment]
Many thanks, I'll be sure to let you know what happens.

Thanks also for the note – I didn't know that about Windows!

**Comment by phw198** [comment]
How's v2.9.1.8 going?

**Comment by Big-Gaz** [comment]
No problems so far, thank you – if I do come across something then I'll let you know!
