### ISSUE TITLE
google entries not syncing

### ISSUE THREAD

**Issue by profit-biz** [phw198/OutlookGoogleCalendarSync#1322]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0  
**Edition**: Installed / Portable  
**Sync Direction**: O<->G

**Bug Description**  
I have created appointments in google calendar but they will not sync. Outlook events sync

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7370714/OGcalsync.log)

**Comment by profit-biz** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7370730/OGcalsync.log)

**Comment by phw198** [comment]
Your logfile shows `26 Google calendar entries found.` - you'll need to provide more information on the item(s) you are saying are not being synced. Are they single events or recurring? What date are they on? All day appointments or not? etc

To confirm, you are syncing with the Google calendar called "outlook" so please ensure you are adding the Google events to this calendar. You also have invites you have declined should be excluded.
