### ISSUE TITLE
Is there a way to hide/suppress the "new version available" message on start up?

### ISSUE THREAD

**Issue by BassTea87** [phw198/OutlookGoogleCalendarSync#1323]
Version 2.8

Hi Paul, I just wanted to know if there is a way to hide the "new version available" message after program start up. Some people prefer the "if it is not broken, do not update it" strategy as long as there are no security fixes in an update, but they do not like the daily pop up :)

Best,
Bastian

**Comment by phw198** [comment]
You should just be able to click the "skip" option on the popup?

**Comment by BassTea87** [comment]
![image](https://user-images.githubusercontent.com/69904819/138656474-45b80c29-ed65-4818-ba95-14548987e43a.png)

Hi Paul, I am only able to say Yes (Ja) or No (Nein) on the popup. If I say "No" the program asks again during the next startup.

**Comment by phw198** [comment]
Yep, so you'll need to upgrade to get the option skip :wink:

**Comment by phw198** [comment]
For info, the popup looks more like this in later releases:
![image](https://user-images.githubusercontent.com/11843015/139438663-064239af-e07c-494b-b36b-e0bb8d5fefec.png)

**Comment by maribox** [comment]
<img width="380" height="149" alt="Image" src="https://github.com/user-attachments/assets/55b9815a-26ed-461f-905f-37ab577e7440" />

Why does v3 again look like this?
Apart from that I think an option to disable automatic update checks would be great! (I, for one, don't like to change a running system and don't want to update if not necessary and then on every startup I will get an annoying prompt informing me of something I don't care about and already know)

Thanks for the cool tool!

**Comment by phw198** [comment]
You're on a development build (bleeding edge), so are expected to use the latest. The prompt is not part of the normal upgrade process hence why you can't skip or ignore it. 

That said, I'm going to release v3 as an alpha in the next couple of weeks, so would advise you at least upgrade to v3.0.1 when it's out, so you can then skip further releases if you wish.

**Comment by maribox** [comment]
Ok understood. But then every new version will still give me a popup, right? 🥺

**Comment by phw198** [comment]
If you don't move off your current version, yes - but I already advised to upgrade to v3.0.1 when it's available. Obviously once off the development build(s) it will revert to standard upgrade window as per my previous screenshot.

**Comment by maribox** [comment]
That's what I meant, when I am on a stable release every new version will give me a new prompt, correct?

**Comment by phw198** [comment]
A prompt with the option to Upgrade, Later or Skip, yes.
