### ISSUE TITLE
busy/free doesn't sync Google to Outlook

### ISSUE THREAD

**Issue by workjoeea** [phw198/OutlookGoogleCalendarSync#1324]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

I can't use the alpha...it gets caught in a sync loop.  I've noticed Google to Outlook is set to Free on the  settings, but when Outlook is populated they show as busy.

**Comment by phw198** [comment]
You've not provided any of the requested information, not even what version of OGCS you are running.

However, testing it with what I would assume you have configured, worked as expected:
![image](https://user-images.githubusercontent.com/11843015/138572939-3d6b654b-46c2-483f-a73c-791181792e49.png)

![image](https://user-images.githubusercontent.com/11843015/138572946-b81d1559-3d05-4ffb-b4a2-6651ab99e94d.png)


Not sure what a "sync loop" is.

**Comment by workjoeea** [comment]
I apologize for not having provided what you needed.  Your program is
really great, but seems more geared towards folks that can do some
programming, and I couldn't quite figure out how to get you the info.
Also, don't I mention that I'm using  the Alpha version?  I'll see what I
can do.  I am hesitant to try to run the beta again, as I don't know how
better to describe what happened, but the program just kind of seemed stuck
running in some kind of loop, and also it doesn't seem to do well with
cancelling a sync.  Also, I have it configured to talk back and forth
between Outlook and Google, and to set entries as busy and private.

**Comment by workjoeea** [comment]
Sorry, I misspoke.  I am using the Beta.  Here is the latest log files, I think.

https://gist.github.com/phw198/695a013b386aa98e8cb071159252bee3

**Comment by phw198** [comment]
So your configuration is:
* two-way sync
* all items (new and updated) synced from Outlook to Google to be [marked as Busy](https://gist.github.com/phw198/695a013b386aa98e8cb071159252bee3#file-ogcalsync-log-L91-L95)

Could you describe the exact steps that produce the problem you are encountering? For example, 
1. Create Outlook as free
2. Sync to Google as busy
3. Modify that Google event, eg alter the subject
4. The subject modification syncs back to Outlook, but also sets it to busy

For the record the above doesn't result in Outlook getting set to Busy in the latest alpha - it remains as Free.

Your logfile also doesn't show any evidence of unexpected repeated syncing: the first two are scheduled 2-hourly, the third triggered by Push Sync and you making a change in Outlook.
