### ISSUE TITLE
Sync private calendar items to non-private on the target calendar

### ISSUE THREAD

**Issue by tdanckaerts** [phw198/OutlookGoogleCalendarSync#1325]
Hi,

I've recently started to use OGCS since the previous sync tool I used couldn't work anymore on my new PC.
My situation is this :
* I have an Outlook calendar in the company where I work. I not only use this for scheduling work meetings and tasks but I also use it as my one-and-only calender for combined proffesional and personal planning. The calendar entries for personal things are set as private in Outlook so my colleagues don't see the contents.
* I have a google calendar to which I do a one-sided sync from Outlook to Google. The reason is I have shared this calendar with my family so they can always see what I have planned.

The problem is now that any entry set as private in Outlook, is also set as private in Google, and as a result my family cannot see the contents anymore through the sharing. My previous syncing tool didn't do that, it would sync all entries as non-private so my family could see all the details.

In the OGCS Sync Options there is an option "Set entries as private" which applies to the target calendar.
I actually need the opposite : Set all entries as non-private.

So, suggestion : in the same options area there is "Set entries as Free/Busy" with a dropdown to choose from, which allows you to overrule to either Free or Busy depending on what you need. Please implement something similar on the "Set entries as Private/Non-private" so you can overrule in either direction.

Thanks for considering this !

Regards,

Tony

**Comment by FilippoLepri** [comment]
Same here: exactly the same situation as Tony! (Outlook calendar in the company used also for personal planning ... Google calendar one-sided-synced for the family ... and so on). :)

F.

**Comment by phw198** [comment]
:package: This should now be possible with [v2.9.4.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8610686/v2.9.4.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes!

**Comment by tdanckaerts** [comment]
Hi Paul,

That would be awesome !
I'll definitely try it out.

Thanks !!

Tony

Op di 3 mei 2022 om 15:23 schreef Paul Woolcock ***@***.***>:

**Comment by phw198** [comment]
Any feedback on this @tdanckaerts? I'd like to include it in the next alpha release if you didn't encounter any issues with it...

**Comment by FilippoLepri** [comment]
It seems working perfectly ... THANK YOU!

**Comment by tdanckaerts** [comment]
Hi Paul,

I’ve activated those new settings the day after you mailed me it was available. 
It has been running fine since then, no issues. 
It works exactly as I had expected. 

Many thanks !

Tony

Verstuurd vanaf mijn iPhone
