### ISSUE TITLE
Running in github actions workers

### ISSUE THREAD

**Issue by Soneji** [phw198/OutlookGoogleCalendarSync#1328]
Hi

I had an idea about running this software within a GitHub actions worker on Windows. A lot of people don't have windows devices, and still would like to run the software. Do you think it's possible?

Thanks

**Comment by phw198** [comment]
Well that would be a complete rewrite from the ground up :slightly_smiling_face: 

I agree a cloud solution would be nice, but 
* it's beyond the time I have available
* would either require considerable technical knowledge to setup up the user **or** be a cost for me to host the service (and there are plenty of other players in the market already for that)
* the users OGCS is focused on are those sat behind a corporate firewall connecting to Exchange accounts - a cloud service would be very unlikely to be able to connect to the Exchange account (unless their company's IT isn't too worried about security and random third party services connecting in from the internet!)

**Comment by phw198** [comment]
I've now worked this into the [FAQs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-does-ogcs-need-to-run-on-a-pc).

**Comment by Soneji** [comment]
Thanks for the reply!

I meant instead of rewriting the software, writing a compatibility layer, like using some sort of automation software or something like that...

Do you think it's possible?

**Comment by phw198** [comment]
No, not possible - OGCS requires an install of Outlook to hook into. A cloud hosted version of OGCS would need to hook into the O365/Outlook.com APIs which is a completely different model.

**Comment by Soneji** [comment]
Ohh I see, this makes sense. Maybe the best way to do it in the cloud would be to get a very cheap windows vm or use an old computer for this purpose, thank you!
