### ISSUE TITLE
Exclude 'private' Google Cal events in sync

### ISSUE THREAD

**Issue by ht31** [phw198/OutlookGoogleCalendarSync#1330]
**Is your feature request related to a problem? Please describe.**
Hi there! Love the software it works really well, but was wondering whether there is an option to exclude certain items from the sync Google -> Outlook.
For context I have all day events which are essentially 'kids in school' 'WFH' etc which are needed in the calendar but I don't want to show up as an all day event in Outlook

**Describe the solution you'd like**
Ideally an option to exclude 'private' events from Google to stop them syncing to Outlook

**Describe alternatives you've considered**
I've thought about adding them as tasks or on a different calendar but as I share my calendar with the rest of the house, it's so much easier if we all have our all day position on our respective calendars rather than adding a new one

thanks guys!

**Comment by phw198** [comment]
Hi thanks for submitting the enhancement idea - I've also found #415 which covers this. It's been open a long time, but I do hope to begin developing such enhancements in the next few months...
