### ISSUE TITLE
Unverified Developer status

### ISSUE THREAD

**Issue by rleikis** [phw198/OutlookGoogleCalendarSync#1331]
**Are you already using OGCS?**
2.9.1

**Describe the question that you have**
Google currently lists you as an Unverified Developer and a Risky security threat after their latest update to their Security Checkup feature.  I've been getting a few different notifications around my Google account about it since setting up their latest phone.  I've been using OGCS forever and understand what access and risk this comes with.  However, can you share with us whether you have pursued a verified status and what that requires for you?  Is it something that is within reach or would require help from this community to help make happen?

![Screenshot_20211101-060510](https://user-images.githubusercontent.com/10184069/139670735-809b473c-b4fc-4a3e-82e0-beb9c6b9fed5.png)

**Comment by phw198** [comment]
You mention you have used OGCS for ages and the screenshot shows authorising it access back in 2019 - this would probably have just been before Google forced me through the verification process on a different app (different API keys) that is now the default for OGCS. 

The default API has the proper OGCS logo and a lot more users. You could transition on to it by clicking the disconnect button on the Google settings page within OGCS and then reconnecting - but tbh the two apps are set up in exactly the same way and you probably have a lot less contention with others user, so I'd probably not be in a rush to transition :slightly_smiling_face:

**Comment by rleikis** [comment]
Okay, that is about what I suspected.  I knew Google has made repeated changes to this over the last several years.  I've confirmed this through testing it with another account.  Thanks for the quick response.
