### ISSUE TITLE
Outlook appointment update failed. Continue with syncronisation?

### ISSUE THREAD

**Issue by lbinokc** [phw198/OutlookGoogleCalendarSync#1333]
Hello. I keep getting an "Sync item failed" message (Outlook appointment update failed. Continue with synchronisation?" I cannot identify what the problem is. Please advise. 

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
A "Sync item failed" message (Outlook appointment update failed. Continue with synchronisation?" No issues syncing Outlook to Google. The failed process window comes when Google is Syncing to Outlook "Appointment update failed. The recurrence pattern is not valid." I cannot identify what the problem is.

**Steps to Reproduce the Issue**  
1. Go to Sync tab 
2. Click on Start Sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
I won't be able to identify the problem either without your logfile...

**Comment by lbinokc** [comment]
I think this is it. Let me know if you need something else.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by phw198** [comment]
:paperclips: Unfortunately, GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by lbinokc** [comment]
Here it is:
[OGcalsync.log.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7479124/OGcalsync.log.zip)

**Comment by phw198** [comment]
It's a [bug with Outlook](https://stackoverflow.com/questions/63645851/creating-outlook-appointments-recurring-every-12-years) - your recurring series `3/28/2008 (R) => "Nick & Stefanie Malone's Anniversary"` repeats every 12 years*, but that's not permitted when programmatically setting this (only up to 8 year intervals can be set).

You might be able to work around this by manually creating the series in Outlook with the same subject, date and recurring pattern, and then OGCS will "reclaim" it.

\* I'm thinking you may not have intended this in the first place though?
