### ISSUE TITLE
Only Push the word "Busy" as a generic title to the meeting from Outlook to Google Calendar

### ISSUE THREAD

**Issue by wtstreetglow** [phw198/OutlookGoogleCalendarSync#1334]
Hello,

Is there anyway to Only Push the word "Busy" as a generic title to the meeting from Outlook to Google Calendar for each appointment in the outlook calendar.

I am in a situation at work where we are trying to come up with a solution to push our personal calendars to a google calendar and I have noticed that OGCS has a lot of features for turning off certain parts of the appointments transferring from outlook to google however we would like a way to "cloak" the meeting name in our instances because many people put personal appointments in our work calendars.-- I noticed there was a feature for color coding that would exclude certain appointments based on its color code and I suppose that would suffice but we we're looking for a more "nuclear" option and the idea described above is the only one I could think of that would require no additional thought to the user. 

I imagine all people use their calendars a little differently but would assume the majority of people only put things in their work calendars as appointments of when they are busy in order to not be interrupted by others.

Thank you for any guidance you all can give or thoughts about the situation.

**Comment by phw198** [comment]
This would already be possible through the Word Obfuscation feature and setting a rule to find `.*` and replace it with `Busy`.

However, if there is a team of you doing this, I would be inclined for each person to sync to their own personal Google account normally, then share that Google calendar with the "team" Google account, but only sharing free/busy status.

**Comment by wtstreetglow** [comment]
Ahhh, I follow you. Thank you for those ideas, those are more than suffice. Thank you again for responding and helping!!

-Weston
