### ISSUE TITLE
Appointment creation skipped: WET is not a valid IANA timezone

### ISSUE THREAD

**Issue by Curtalain** [phw198/OutlookGoogleCalendarSync#1337]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [ ] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.2.0  
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
6 items are identified for being created in Outlook from Google, but OGCS just displays the message "Appointment creation skipped".

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7510816/OGcalsync.log)

**Comment by phw198** [comment]
OK...should I assume you didn't expect this item to be skipped?

You have two-way sync configured - in which calendar is it not being created? What are the details of the skipped item: date, time, subject, single or recurring, who created it (eg organised by someone else and you're an attendee) etc etc.

You could enable CSV creation and then check in the same folder as your `OGcalsync.log` file to see if the skipped item is listed in the relevant CSV file.

**Comment by Curtalain** [comment]
Hello
It is not being created in OUTLOOK.

The items are created by my air plane company AIR FRANCE.

I have upgraded to V2.9.2

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7537490/OGcalsync.log)

The items are in Google_events.csv but not created in google_created.csv
[google_create.csv](https://github.com/phw198/OutlookGoogleCalendarSync/files/7537541/google_create.csv)
[google_events.csv](https://github.com/phw198/OutlookGoogleCalendarSync/files/7537542/google_events.csv)

**Comment by phw198** [comment]
Ahhh, so you mean "Appointment creation skipped" is the message that is being displayed by OGCS when it's trying to create the items!
```
2021-11-15 10:35:33,961 INFO  10 OutlookGoogleCalendarSync.Console [282] -  Creating 6 Outlook calendar entries
2021-11-15 10:35:34,247 DEBUG  10 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [284] -  Processing >> 23/11/2021 07:10 => "Vol Paris - Tunis"
2021-11-15 10:35:34,247 DEBUG  10 OutlookGoogleCalendarSync.Console [280] -  23/11/2021 07:10 "Vol Paris - Tunis"
2021-11-15 10:35:34,363 WARN  10 OutlookGoogleCalendarSync.Console [274] -  Appointment creation skipped.
```
:package: Please could you apply [v2.9.2.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7574643/v2.9.2.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)), reproduce the problem and then re-upload your `OGcalsync.log` file.

Thanks!

**Comment by Curtalain** [comment]
Good Moring
I apply V2.9.2.3 release; No success ! The same messages

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7580297/OGcalsync.log)

**Comment by phw198** [comment]
So now we can see the issue with these are due to the assigned timezone `WET` / Western European Time:
```
2021-11-22 11:34:11,253 DEBUG  12 OutlookGoogleCalendarSync.Console [280] -  23/11/2021 07:10 "Vol Paris - Tunis"
2021-11-22 11:34:11,322 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ApplicationException: Timezone "WET" has no mapping.
2021-11-22 11:34:11,491 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131600,-2146232832; Location: WindowsTimeZone() in OutlookNew.cs:833:17
2021-11-22 11:34:11,492 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [65] -     à OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.WindowsTimeZone(String ianaZoneId) dans C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookNew.cs:ligne 833
   à OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.WindowsTimeZone_set(AppointmentItem ai, Event ev, String attr, Boolean onlyTZattribute) dans C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookNew.cs:ligne 793
   à OutlookGoogleCalendarSync.OutlookOgcs.Calendar.createCalendarEntry(Event ev, AppointmentItem& ai) dans C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:ligne 290
   à OutlookGoogleCalendarSync.OutlookOgcs.Calendar.CreateCalendarEntries(List`1 events) dans C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:ligne 243
2021-11-22 11:34:11,493 WARN  12 OutlookGoogleCalendarSync.Console [274] -  Appointment creation skipped.
```
The problem here is not with OGCS, but with whatever is creating these events in the Google calendar - [as confirmed here](https://time.is/WET), WET is not a valid IANA timezone (as required by Google) and the valid values are:
* Atlantic/Canary
* Atlantic/Faroe
* Atlantic/Madeira
* Europe/Lisbon

Fix up Google and they will sync to Outlook properly.
