### ISSUE TITLE
Solved - Sync not working: One or more items in the folder you synchronized do not match

### ISSUE THREAD

**Issue by Improov-All** [phw198/OutlookGoogleCalendarSync#1338]
**OGCS Version**: v2.9.0  
**Installed or Portable**: Portable

**Problem Description**  
Sync doesn't start since the 4th of November. Log is full of the errors below: 
```
2021-11-10 08:04:59,303 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: One or more items in the folder you synchronized do not match. To resolve the conflicts, open the items, and then try this operation again.
2021-11-10 08:04:59,303 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xB5920009,-1248722935; Location: get_Categories() in <Unknown File>
```
Log attached: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7511838/OGcalsync.log)

I have no idea which item doesn't match or how to find it. Any help appreciated. 

**Steps to Reproduce the Issue**  
1. Start OGCS, press sync.

**Comment by phw198** [comment]
Are you using OGCS against an Exchange account? I think you'd need to look through the your [Sync Issues folder in Outlook](https://www.howtogeek.com/377695/view-and-delete-sync-issues-in-outlook/) and resolve those before OGCS will work...

**Comment by Improov-All** [comment]
Thank you for your response Paul. I had indeed many sync issues in the designated folder. However, checking and removing them didn't fix anything. 

I've tried several steps and finaly removed all Outlook mailboxes and setup a new profile. Sync works again!

For whoever runs into the same issue, I tried the following steps to no avail:
- Checking and removing sync issues in different mail accounts
- Removing all mail-accounts other than the one with sync issues, as they appeared to interfere
- Excluding (almost) all items to be synced, using the 'sync categories filter'. 
- Upgrading to 2.9.1.0 beta
- Select other calendars to sync to
- Braking google-sync connection and re-authorize
- Using a fresh OGCS 'instance' altogether (I use portable) 
- Rebooting (doh)
Again, what did work was removal of the outlook account that I wanted to sync.

**Comment by phw198** [comment]
Thanks for the update @Improov-All :+1: 

The only other things I would have suggested would have been:
* an [Office repair](https://support.microsoft.com/en-us/office/repair-an-office-application-7821d4b6-7c1d-4205-aa0e-a6b40c5bb88b)
* a [repair of the OST/PST file](https://support.microsoft.com/en-us/office/repair-outlook-data-files-pst-and-ost-25663bc3-11ec-4412-86c4-60458afc5253)

Glad you got OGCS working again though!

**Comment by objarni** [comment]
@Improov-All thanks for you detailed research and write-up! I am trying to interpret what "Again, what did work was removal of the outlook account that I wanted to sync." means in practice. I tried:

1. Changing the "mailbox" dropdown in OGCS (from default to a specific, it auto-reverted to default)
2. Looking for a way to remove the Outlook "connection" from OGCS, could not find any such method

What does "removal of the outlook account" mean?

**Comment by phw198** [comment]
@objarni Just to make it clear, this error is not from OGCS but from Outlook itself - it appears to have corrupted itself somehow, hence why my suggestion was an OST/PST file repair first. [Removal of the mail account](https://support.microsoft.com/en-us/office/remove-or-delete-an-email-account-from-outlook-1fa900ae-6dc8-468c-b754-10292f7ee47a), or the [entire profile](https://support.microsoft.com/en-us/office/remove-a-profile-d5f0f365-c10d-4a97-aa74-3b38e40e7cdd) simply will delete the OST/PST file and recreate it when you add the account back.

Once the mail account is working properly again, so will OGCS.

Another suggestion - try going through [the instructions found here](https://www.fieldstonsoftware.com/support/gsyncit/topic_olsyncfail.aspx) for the calendar folder you are syncing with OGCS - see if you can spot any items with the cross-swords icon which indicate a conflict.

**Comment by Improov-All** [comment]
That is indeed what I meant: from the Outlook program, follow Paul's advice
or just delete the account that is causing problems.

Op za 29 jan. 2022 20:18 schreef Paul Woolcock ***@***.***>:

**Comment by objarni** [comment]
It just started working a couple of days later, after a reboot of windows (that good ole trick!). I tried to update my comment but couldn't find my way back here, so thanks for giving me a chance to explain another "workaround" - Just Reboot Windows 👯
