### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by devan24** [phw198/OutlookGoogleCalendarSync#1340]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\![image](https://user-images.githubusercontent.com/85245005/141819647-b1ec206f-5bd5-4c20-89b7-87e5d41e8d70.png)Installation Failed

**Steps to Reproduce the Issue**  
1. \<Update>
1. Had to create new Outlook profiles and OGCS didn't work with new profile. 
2. Couldn't access it to update Outlook side
3. Tried updating and got Installation Failed message.
4. Tried uninstalling and reinstalling but can't reinstall, Installation Failed message 
5. Got this message  ---------------------------
Application unexpectedly terminated!
---------------------------
Could not find file 'C:\Users\anned\AppData\Local\OutlookGoogleCalendarSync\app-2.9.0-beta\ErrorReportingTemplate.json'.
---------------------------
OK   
---------------------------

**Any other information**  
\<Update here> Then, this dialog box appeared:
[SquirrelSetup-DESKTOP-G2RF63D.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7540199/SquirrelSetup-DESKTOP-G2RF63D.log)

![image](https://user-images.githubusercontent.com/85245005/141819689-cbab1d69-5b32-4dbc-ac64-5133263852ee.png)

**Comment by phw198** [comment]
This is your Squirrel install log:
```
2021-11-15 11:23:22> Program: Starting Squirrel Updater: --install .
2021-11-15 11:23:22> Program: Starting install, writing to C:\Users\anned\AppData\Local\SquirrelTemp
2021-11-15 11:23:22> Program: About to install to: C:\Users\anned\AppData\Local\OutlookGoogleCalendarSync
2021-11-15 11:23:22> Program: Install path C:\Users\anned\AppData\Local\OutlookGoogleCalendarSync already exists, burning it to the ground
2021-11-15 11:23:23> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Access to the path 'C:\Users\anned\AppData\Local\OutlookGoogleCalendarSync\app-2.9.1-alpha\log4net.dll' is denied.
```
Looks like OGCS is running maybe more than once. Check there are no `OutlookGoogleCalendarSync.exe` processes running in Task Manager, then download the `Setup.exe` from the website and run it.

**Comment by devan24** [comment]
Only had one process running. After uninstalling, got 2.9.0 to install, then updated to 2.9.1 alpha. Update to 2.9.2 didn’t work as I encountered the same problem as others with OGCS frozen on “checking”. Will wait a few days to try again for 2.9.2.

**Comment by phw198** [comment]
OK, that sounds positive. Upgrade from v2.9.1 to v2.9.2 now has a [patch available](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1341#issuecomment-970915208), and it's possible the issues encountered on this ticket were related complications.

**Comment by devan24** [comment]
It worked. Thank you, Paul.
