### ISSUE TITLE
OGCS stopped working after Windows 11 update [0x80040155]

### ISSUE THREAD

**Issue by zenkosa** [phw198/OutlookGoogleCalendarSync#1342]
> Checklist:-
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1 
**Edition**: Installed and Portable  
**Sync Direction**: G->O

**Bug Description**  
After the Update to Windows 11 OGCS is stopping during the start with Error: 0x80040155 - Interface not Registered

**Steps to Reproduce the Issue**  
1. Start OGCS 

**Any other information**  
The FAQs COM Errors description and the steps do not solve the issue.

**Comment by phw198** [comment]
If you also [followed these steps](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#1-fix-the-interface) through, then your only option is an [Outlook Repair](https://support.microsoft.com/en-us/office/repair-an-office-application-7821d4b6-7c1d-4205-aa0e-a6b40c5bb88b) or Office reinstall.

**Comment by zenkosa** [comment]
The Outlook Repair solved the issue. Its running fine. Many thanks phw198.

**Comment by billlanding** [comment]
Same issue. Recently "upgraded" to WIN11 on Lenovo laptop, OGCS fails, Interface not registered error.
Reinstalled Office 365. Uninstalled previous OGCS. Downloaded 2.9.0 and 2.9.2. Neither will install; report same Interface not registered error. I am not savvy enough to try the Regedt steps that are recommended. 
Any ideas?

**Comment by phw198** [comment]
@billlanding Unfortunately not if you've already gone through a reinstall of Office365 - that's normally the nuclear option that's guaranteed to sort out the registry problems for you...  DId you reboot inbetween uninstall and reinstall?

**Comment by billlanding** [comment]
Yes, I did reboot after uninstall and reinstall. Tried again today to install 2.9.2. Got same error about "Interface not Registered".

**Comment by phw198** [comment]
Just to clarify, OGCS is installed successfully, just that when you run it, it cannot connect to Outlook because Office is not installed/registered properly on your computer. Manual editing of the registry as per the wiki should fix it...not sure why reinstalling didn't do the trick though :slightly_frowning_face:
