### ISSUE TITLE
Tab Switching

### ISSUE THREAD

**Issue by micropcla** [phw198/OutlookGoogleCalendarSync#1343]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**2.9.2.0
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>
When I use tab switching I see the OGCs program and on the older versions I do not recall seeing it.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.9.2.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7574779/v2.9.2.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by micropcla** [comment]
Works.

**Comment by micropcla** [comment]
I am getting this error I never saw before. 

Sync version: 2.9.3.0
Profile: Default
Sync started at 2/27/2022 10:43:10 AM
Syncing from 11/29/2021 to 2/28/2023
Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...
234 Outlook calendar entries found.

Scanning Google calendar...
233 Google calendar entries found.
8 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...
Outlook 234, Google 234
Checking for orphaned Google items 

Syncing Outlook → Google
Matching calendar items...
0 Google calendar entries to be deleted.
0 Google calendar entries to be created.
234 calendar entries to be compared.

Comparing 234 existing Google calendar entries
0 entries updated. 

Syncing Outlook ← Google

Matching calendar items...
0 Outlook calendar entries to be deleted.
0 Outlook calendar entries to be created.
234 calendar entries to be compared.
Comparing 234 existing Outlook calendar entries

3/5/2022 4:00 PM "Colorado Rapids vs Atlanta United"
Attribute
Change
Recipient ***@***.***

1 attributes updated.

Appointment update failed.

Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).

Appointment update failed.

Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).

Appointment update failed.

Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).

Appointment update failed.

Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).

Sync finished!

**Comment by phw198** [comment]
@micropcla Looks like you closed Outlook whilst OGCS was busy syncing, which would resolve itself on the next sync. Not sure what this has to do with tab switching though?

**Comment by micropcla** [comment]
Outlook was open and it always stays open.

**Comment by micropcla** [comment]
Nothing to do with tab switching.

I just used an old e mail to get a hold of you.

**Comment by micropcla** [comment]
Closing Outlook and restarting it seems to have fixed it.

**Comment by phw198** [comment]
The error is specifically related to when Outlook has been closed, but OGCS should automatically reconnect on the subsequent sync. If it did not, please open a new GitHub issue and upload your OGcalsync file so I can take a closer look.
