### ISSUE TITLE
Rename setup.exe

### ISSUE THREAD

**Issue by breisfeld** [phw198/OutlookGoogleCalendarSync#1346]
OutlookGoogleCalendarSync is a very useful tool!

However, the name of the installer, `setup.exe`, is too generic. Once it has been downloaded, it is confusing as to exactly what it represents. Moreover, all versions have this same name. 

It would be great if it had a more descriptive name, e.g. `ogcs_2.9.2.0alpha.exe`.

Thank you.

**Comment by MartinJJ** [comment]
That is a good idea. I now rename manually... But sometimes forget. An later it's not clear which tool it is from.

**Comment by phw198** [comment]
Seems this is a safe thing to do:
https://github.com/Squirrel/Squirrel.Windows/issues/219 and [from the developer of Squirrel](https://github.com/OpenLiveWriter/OpenLiveWriter/issues/27#issuecomment-163750681).
