### ISSUE TITLE
OGCS is writing Outlook Calendar Entries every Time new

### ISSUE THREAD

**Issue by bansheeat** [phw198/OutlookGoogleCalendarSync#1349]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.2.0
**Edition**: Portable  
**Sync Direction**: G->O 

**Bug Description**  
With every Sync the Google Calendar Entries are created again in the Outlook Calendar

**Steps to Reproduce the Issue**  

1. Click on..."Sync Now"

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
https://gist.github.com/bansheeat/cdb89acee62961810a64455d5896b966

**Comment by phw198** [comment]
Your log only shows it creating 1 item in Outlook `17.11.2021 => "WhatsApp Backup "`, even though Google has 14, so they're not all continually being created in Outlook.

Also, you have deletion disabled and there are 7 Outlook items OGCS wants to remove - are you sure the "duplicates" are not ones that OGCS wants to delete anyway?

**Comment by bansheeat** [comment]
Hello Paul, so I obviously made a mistake with the setup of the program. 
Your program should only sync from Google Calender to Microsoft Outlook 2007. But I need it on 3 different computers - first one is used 5 days (Monday to Friday), second one is used Friday, Sat. and Sunday, last one is used only on Sunday. 
Maybe you can help me with that ?

**Comment by phw198** [comment]
The configuration you describe should be supported.

So you have OGCS installed once on each computer, each with their own configuration? The log file you provided shows OGCS is running from `D:\Portable_OGCS_v2.9.2` - where is the D:\ drive? If it's a cloud drive which all 3 computers have then this will be your problem, as each computer running OGCS needs to have it's own settings.xml configuration file. See #165 for more details of switches available to specify different settings and log files.

**Comment by bansheeat** [comment]
Hello Paul, thanks for your reply. My D:\ Drive is a partition on my System Drive. But I am glad you mentioned a Cloud Drive, because I once tried to run your program from my Google Drive. Maybe that is what messed up my configuration. So I will start again from the scratch for my 3 computers. Thanks again, have a nice weekend.
