### ISSUE TITLE
Start OGCS on system startup not working

### ISSUE THREAD

**Issue by davefeeser1** [phw198/OutlookGoogleCalendarSync#1350]
**Are you already using OGCS?**
2.9.2.0
**Describe the question you have**
OGCS will not startup at login to windows. App Behavior is set to start on login with delay of 0 seconds. I can manually start it if I change OGCS to run as Administrator.

**Comment by phw198** [comment]
Can you check if the startup registry key is being set properly? `\\HKCU\Software\Microsoft\Windows\CurrentVersion\Run` - there should be a key for OGCS?

Would be good to see your `OGcalsync.log` file when you toggle the option for OGCS to start on startup...

**Comment by davefeeser1** [comment]
Paul-
Thanks for your help!
 
§ Attached is the Debug Log when I first startedOGCS this morning and the settings log from the App.

§ I could not check the registry key (\\HKCU\Software\Microsoft\Windows\CurrentVersion\Run)because I didn’t know how to do that.

§  Myissue: at the initial startup, when I bring up my computer in the morning, Ican only manually start OLCS. Ido this by setting the “Run as Administrator” commandunder the dropdown list of the application, even though I checked the start onlogin with a delay of 0 seconds in the settings menu of Application Behavior.

§  Iam running Windows 10 Home Edition, Version 21H2

I love OGCS.

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

To check the registry key:
1. Start > Run > `regedit.exe`
2. Navigate down through `KEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` then check for a key called `Outlook Google Calendar Sync` and see what value it has.

It's rather concerning you are needing to run OGCS as Administrator though - this really shouldn't be necessary, or even advisable, as it won't work unless Outlook is _also_ running as Administrator?

**Comment by davethegeo** [comment]
I have the same issue. OGCS (2.9.4.0) does not start automagically with Windows although I can double click the exe to start it later. Registry key exists and points to the exe with value d:10 which is what I had asked for in the settings.
Other than that, it works well.

**Comment by phw198** [comment]
@davethegeo Has this ever worked for you, or it stopped working with v2.9.4?

Can you try manually putting the same registry key in the following location and seeing if that works?
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run`

**Comment by davethegeo** [comment]
@phw198 
Adding that Registry key has solved the problem. OGCS now starts reliably with Windows. Many thanks.

**Comment by phw198** [comment]
Thanks for confirming. So do you always log in to Windows as the same user? Specifically, when you checked the "Start on system startup" option in OGCS, were you then subsequently logging into Windows under the same user account? Just not sure why it was necessary for you to add the startup key under HKLM, as this will now start OGCS for _any_ user that logs in...

**Comment by davethegeo** [comment]
I always log on to my Windows PC as the same user. However, I do use several different desktops on the same machine. I wonder if this has an effect on OGCS? The account I use Outlook for is not the same as my windows logon? Relevant or not? I'm just glad it's working!

**Comment by phw198** [comment]
:package: I've added a new option to set that registry key through the application with [development build v2.9.4.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8656084/v2.9.4.13.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

![image](https://user-images.githubusercontent.com/11843015/167517599-4a458488-0e58-4711-8248-f26a9015cbcd.png)

Any testing you can do with this would be greatly appreciated!
