### ISSUE TITLE
Notes entries

### ISSUE THREAD

**Issue by jimjph** [phw198/OutlookGoogleCalendarSync#1352]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0.0
**Edition**: Installed
**Sync Direction**: G->O / O->G / O<->G - All

**Bug Description**  
When writing notes into the notes section of a calendar appointment on my iphone, they get lost when the sync takes place, not all the time but usually. If the appointment is updated on my laptop then the notes get deleted everytime.

[Google.Apis.Auth.OAuth2.Responses.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7628903/Google.Apis.Auth.OAuth2.Responses.zip)
**Steps to Reproduce the Issue**  
1. Go to...iphone, enter notes in a calendar entry, then appointment on laptop
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
That would be expected - you are syncing the calendar item description from Outlook to Google:
1. Sync appointment from Outlook to Google
2. Edit it in Google on your phone and add a note
3. Modify the Outlook item somehow (eg alter subject)
4. OGCS will resync and over-write the Google description with the empty/original description from Outlook.
