### ISSUE TITLE
application inoperable when an upgrade comes out

### ISSUE THREAD

**Issue by asgreenb** [phw198/OutlookGoogleCalendarSync#1353]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
I am using portable version 2.9.1 on Win 10 pro 64 bit

> * [x] Reproduce the issue
open the application (C:\+Portable_OGCS_v2.9.1\OutlookGoogleCalendarSync.exe)

> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7629212/OGcalsync.log)

**Sync Direction**: G->O / O->G / O<->G
outlook to google

**Bug Description**  
the application load with this error
![image](https://user-images.githubusercontent.com/64911719/144136551-62e82f68-e5db-4c58-b18b-a9633709b477.png)

**Steps to Reproduce the Issue**  
see above

**Any other information**  
Any additional information that may help troubleshoot the issue.  

:paperclip: Attach your `OGcalsync.log` file
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7629231/OGcalsync.log)

**Comment by phw198** [comment]
The subject of your issue makes it sounds like this always happens after an upgrade? 
* What other versions has this happened on?
* As you're running the portable release, I wouldn't really call this an "upgrade" - what's the solution to getting OGCS to run, or is v2.9.1 refusing to run at all?
* Have you tried v2.9.2 portable release?

**Comment by NHasgreenb** [comment]
Yes, it has happened each time an alpha version is released (since 2.8.7). As soon as I download the new version, copy the settings xml file from the previous version into the newest version's folder and launch the application it works fine. It's just that the upgrade timing is not always in synch with mine :-)

**Comment by phw198** [comment]
> It's just that the upgrade timing is not always in synch with mine

I don't quite follow what you mean here? If you are running portable releases, isn't the timing of the upgrade and when you copy the settings file entirely within your control?

**Comment by asgreenb** [comment]
That's exactly what I would have thought.
It could be a completely random coincidence, but synching has failed in conjunction with the release of the last 3-5 new alpha versions.

It is not a huge deal, and considering you do not get any other complaints, it is not worth too many cycles / effort.

Thanks
Adam

________________________________
