### ISSUE TITLE
Outlook 2019 access warning

### ISSUE THREAD

**Issue by amig500** [phw198/OutlookGoogleCalendarSync#1356]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.2.0
**Installed or Portable**: Installed

**Problem Description**  
From time to time, multiple times a day, a series of warnings raise from outlook 2019, stating that OGCS is trying to access it. Neither accepting nor refusing access does stop the warnings to raise.
https://ibb.co/znH9FHS 

**Steps to Reproduce the Issue**  
1.  Install outlook 2019 and sync
2.  Just wait. Problem also happens even if Outlook is not launched yet.

**Any other information**  
Seen on Windows 10

**Comment by phw198** [comment]
You AV definitions will be out of date - standard security as [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security).
