### ISSUE TITLE
Calendar sync deleted all my events in both calendars!

### ISSUE THREAD

**Issue by ls6777** [phw198/OutlookGoogleCalendarSync#1362]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I updated my Outlook calendar with only events that originated in outlook.  I think updated my google calendar with only events that originated in google calendar.  I then did a 2-way sync.  It proceeded to delete all my entries in both calendars!!!  WTF???  How do I get my entries back?  

This was after I just donated to this project to hide the splash screen... and then it just totally screwed me!!

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by ls6777** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7772761/OGcalsync.log)

**Comment by rgleim** [comment]
I will chalk this up to user error.  I should have marked "confirm deletion" option.  Not sure why it decided everything needed to be deleted still.  There has to be some way to reset the program so it's not already thinking everything is synced between the 2 calendars.  I believe that's why it deleted everything.  It thought I deleted a bunch in both calendars, and tried to sync those updates.  Instead, I wanted it to start over and just "add" both directions.  Not sure how that's done.

**Comment by phw198** [comment]
@ls6777 

> I updated my Outlook calendar with only events that originated in outlook. I think updated my google calendar with only events that originated in google calendar.

I'm not really sure what this means.

The deleted items would be in the Deleted Items or Bin of Outlook and Google respectively, so they can be recovered from there. Once done, set OGCS to sync _one way_ from the calendar which has all the items you need it to. Once complete, set it back to two-way sync.

@rgleim Yes, that sounds about right - if you had two-way sync configured and then cleared out a calendar to "start again", OGCS would see that as needing to replicate those deletions to the other calendar. Normally, the solution is to do a one-way sync first and then back to two-way.

However, to reset the metadata OGCS holds on the calendar's synced items, [instructions are available in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#removing-all-ogcs-metadata-from-your-calendars).
