### ISSUE TITLE
Startup with two portable versions

### ISSUE THREAD

**Issue by JP3251** [phw198/OutlookGoogleCalendarSync#1363]
:memo: Use the below template to report your issue.  
:bulb:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Hi,  I am using two portable programs to sync two outlook calendars with my google calendar.  The issue is that I cannot start up both and only one launches.  How can I fix this issue?

**Steps to Reproduce the Issue**  
1. Set up two portable programs with two outlook accounts.
2. Set up start on login for both

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Hi @JP3251 

This should be covered under the section "Start OGCS on Startup" of issue #165.
