### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by bjones1** [phw198/OutlookGoogleCalendarSync#1366]
I just downloaded and tried this tool, and it works wonderfully! Thanks for your time and effort in creating this tool. I really appreciate it. I spend uncounted hours trying other methods. Finally, I found your tool, and it's a lifesaver. Thanks again.

**Comment by phw198** [comment]
Thanks so much for taking the time to give feedback - really great to hear and so pleased it's working out for you!
