### ISSUE TITLE
Add 2nd option to allow SYNC to process small date range, e.g. hourly, and large date range, e.g. once daily

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#1367]
Add 2nd option to allow SYNC to process small date range, e.g. hourly, and large date range, e.g. once daily.

It would allow much quicker sync for the vast majority of calendar updates/changes/additions, for a smaller date range.

And save a large amount of processing requirements and time that are being used often only to process a lonely single calendar change 7-8 months in advance. Those changes are rarely time sensitive, and could updated  once every 24-48 hours.

Not sure how you would handle reoccurring events.

**Comment by phw198** [comment]
Thanks @kwagner115 - will certainly consider this, though arguably, this could be achieved in the next release that will provide "profiles" and separate profiles could be configured with those different settings you mention.

> Not sure how you would handle reoccurring events.

If the recurring event spans even the small date range, there's a lot of logic and processing related to retrieving these series and working out if an occurrence falls in the sync window and has changed etc...

**Comment by kwagner115** [comment]
I tried using the new Alpha release with the new profiles feature to handle this suggestion. Nothing I try seems to work.

**Comment by phw198** [comment]
Closing as enhancement request is now achievable via Profiles.
