### ISSUE TITLE
Missing calendar event description information

### ISSUE THREAD

**Issue by Helmuttie** [phw198/OutlookGoogleCalendarSync#1368]
**Are you already using OGCS?**
2.9.0.0.

**Describe the question you have**
I noticed that sometimes in an calendar event the description information disappears after syncing. Is there a setting that prevents/causes this?

**Comment by phw198** [comment]
Might you be having the same issue as #1352? 

If you have two-way sync configured and only one-way sync Outlook -> Google for the Description, where Outlook has no description, then the Google description would get removed.

If you could confirm this is what is happening, I'll consider an enhancement to not overwrite Google with nothing in that situation...

**Comment by Helmuttie** [comment]
I do have the 1-way Outlook to Google option checked on in "Settings>Sync options>What". I decided to do that after reading the online Userguide. I understood that this option prevented issues but apparently that caused the problem, so I turned it off. Why did you include this particular option? When would it be helpful?

**Comment by phw198** [comment]
It's helpful in the following situations:
* more than 8k characters in Outlook, Google truncates it, the truncation would sync back to Outlook
* Outlook is HTML formatted, Google doesn't support that, "corrupted" description is synced back to Outlook

However, when Outlook has no description, we don't want it to wipe was you have entered to Google, hence why I've suggested I'll look at a fix for this.
