### ISSUE TITLE
Exchange Web Services

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#137]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/653933" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/zjllee" target="_blank">zjllee</a></strong> wrote at 2016-04-24 07:56:</p><div class="markDownOutput ">The exchange web services option is blanked out in Outlook Google Calendar Sync. Is this something to do with my exchange settings (i.e blocked by the admins) or is the feature not available yet? Thank you.<br>
</div></div>

**Comment by phw198** [comment]
EWS option was never implemented and has been removed.

**Comment by Giorgi** [comment]
Do you have any plans to implement EWS support or would you be interested in it I send a PR ?
