### ISSUE TITLE
G -> O: Calendar entries are duplicated, despite "merge" if Outlook categories excluded

### ISSUE THREAD

**Issue by heilieriksson** [phw198/OutlookGoogleCalendarSync#1377]
**OGCS Version**: v2.9.2.0

**Installed or Portable**: Installed

**Problem Description**  
\When syncing Google to Outlook, calendar entries are duplicated, despite the setting "Merge with existing entries" setting being ticked.

**Steps to Reproduce the Issue**  
1. \Run sync, happens everytime since I started running v2.9.2.0. I did not have the problem in the previous version I was using.

**Any other information**  
\
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7984864/OGcalsync.log)

**Comment by phw198** [comment]
You appear to be filtering out every single category? Try unchecking all the categories under "Exclude".

**Comment by SVNKoch** [comment]
for me and a friend the problem was that in the outlook tab we excluded / not included the category in which the google appoinments were beeing synced to.
This probably leads to OGCS not checking these calenders for existing items for merging are creates a duplicate.
@phw198 is this by design? It is not immidiately obvious why changing something in the outlook tab would affect the syncing from G -> O.

**Comment by phw198** [comment]
This is loosely related to #1083, which related to two-way sync. You're right, if excluding items from Outlook and syncing G->O, it's not too obvious that can cause "duplicates".

It's not "design" per-say, but if OGCS doesn't pick up the Outlook items, then it won't think they exist and so create them afresh.

I'll add a warning in this situation...thanks @SVNKoch !

**Comment by phw198** [comment]
The following warning will now display if Outlook items are filtered out and syncing G->O:-

![image](https://user-images.githubusercontent.com/11843015/164937170-c35189c6-e381-4acb-97da-0d6b5b6ea099.png)

**Comment by heilieriksson** [comment]
Brilliant. Thank you for adding this warning.

//Heili
