### ISSUE TITLE
Google Calendar showing duplicate Outlook events, I just want to delete the entire program, please help!!!!!!!

### ISSUE THREAD

**Issue by picard19** [phw198/OutlookGoogleCalendarSync#1378]
**Are you already using OGCS?**
Provide the version number.

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

**Comment by phw198** [comment]
I'm assuming you mean uninstall the program, not delete - which is as [simple as](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Uninstall#githubsquirrel-installs) going to your Windows settings, viewing the applications, finding OGCS and clicking uninstall.
