### ISSUE TITLE
Can I restore my settings from a backup?

### ISSUE THREAD

**Issue by plevintampabay** [phw198/OutlookGoogleCalendarSync#1380]
**Are you already using OGCS?**
Version 2.9.0.0

**Describe the question you have**
I had to reinstall the Windows and all the programs.
I have a complete backup from beforehand.
Is the configuration I had before the reinstall in a file somewhere?
Can I copy that file from the backups to the new windows installation, and have OGCS work from that configuration?

**Comment by netjeff** [comment]
Based on the FAQ entry for "[How do I reset the configuration](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#how-do-i-wipereset-the-configuration)", I just wrote these steps.  I haven't actually tried these steps, so no promises that they will work.  :-)


1. Click the Settings tab, and then Application Behaviour tab
2. Click the `Open Log` button.  This will open Windows Explorer file browser.
3. Close OGCS
4. In the Windows Explorer window, replace the `settings.xml` file with the backup version.
5. Restart OGCS

**Comment by phw198** [comment]
Yep, that should work - thanks for the input @netjeff ! I've now added a section in the [Hints and Tips](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#restoring-ogcs-configuration).
