### ISSUE TITLE
Excluding Google entries by category (color) for sync

### ISSUE THREAD

**Issue by chross** [phw198/OutlookGoogleCalendarSync#1383]
**Is your feature request related to a problem? Please describe.**
When using the new profile feature in 2.9.3.0, I am syncing two different Outlook calendars to the same google calendar.
For calendar one, sync direction is Outlook -> Google, the other one is bidirectional Outlook <-> Google. Obviously this leads to some confusion when deletions are enabled and especially when confirm deletions is enabled for the bidirectional one.
When syncing, OGCS will push all Outlook entries to Google, as expected, but in the second step, it will offer to delete these items again as they are not present in the second calendar.

**Describe the solution you'd like**
Filter Google entries by category when syncing. The above problem could be solved by allowing to filter out certain categorie colors.
Upon pushing from Outlook to Google, a color category will be assigned, specific to the first calendar. The bidrectional sync will omit this color category and everything will be fine.

PS: I love this software. Keep up the good work.

**Comment by phw198** [comment]
> I am syncing two different Outlook calendars to the same google calendar.

Whilst the enhancement is a good suggestion, the above scenario should be supported since a couple of beta releases ago. The Outlook1 items in Google should not be flagged for delete when Outlook2 syncs bidirectionally. I'll do some further testing around this...

**Comment by phw198** [comment]
@chross Yep, this seems like a bug introduced with Profiles - I've created issue #1394 which has a hotfix if you would like to try that out.
