### ISSUE TITLE
OGS Stopped connecting with my Google and keeps throwing errors

### ISSUE THREAD

**Issue by spschauhan** [phw198/OutlookGoogleCalendarSync#1386]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8058082/OGcalsync.log)

**Comment by spschauhan** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8058090/OGcalsync.log)

**Comment by phw198** [comment]
Looks like you have network connectivity problems:
```
2022-02-14 10:55:04,760 ERROR  15 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Net.WebException: Unable to connect to the remote server
2022-02-14 10:55:04,763 ERROR  15 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 13.127.247.216:443
```
That IP at the end appears to be owned by Amazon Web Services in India - not sure if you're using that as part of your internet proxy? Basically, OGCS isn't able to talk to the Google servers.
