### ISSUE TITLE
How to cancel subscription

### ISSUE THREAD

**Issue by gafox1** [phw198/OutlookGoogleCalendarSync#1387]
**Are you already using OGCS?**
2.9.10

**Describe the question you have**
I need to stop my subscription after the current one runs out. Not a problem with your excellent program - just not using Outlook any longer! Please let me know how to do this.

Thanks.
Gordon

**Comment by phw198** [comment]
Hi Gordon,

Sure, just log in to PayPal and browser to https://www.paypal.com/myaccount/autopay/ find the OGCS recurring payment and cancel it.

Thanks for being a supporter of OGCS!

**Comment by gafox1** [comment]
Thanks!
