### ISSUE TITLE
Cannot map google peacock blue color to equivalent in outlook 

### ISSUE THREAD

**Issue by hxgee** [phw198/OutlookGoogleCalendarSync#1388]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed
Installed version

**Problem Description**  
\<Cannot map to google peacock blue category.   In outlook when you try to use a similar color - it  gets picked up as blue or navy or blueberry blue - most other colors seem to work>

**Steps to Reproduce the Issue**  
1. \<Go to Sync Options, Colours/categories, Mapping - choose Google Peacock color and try to map to outlook category of the same color - it shows up as navy blue or blueberryblue>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
That's what the custom colour mapping is for - in the table, choose the Outlook category you want to map to Google's Peacock colour and click OK.

![image](https://user-images.githubusercontent.com/11843015/155906562-4681314f-6a32-4a1e-b1db-61b8276a1fb3.png)

**Comment by hxgee** [comment]
It works for every colour except the equivalent of Google’s Peacock blue – it maps it to blue or blueberry blue.

**Comment by hxgee** [comment]
Sorry meant to add - I did replicate the issue on two installs - desktop
and laptop ....

Thanks

**Comment by phw198** [comment]
Please upload a screenshot of your colour mapping configuration - note this can't be done by email, you need to login to GitHub.

**Comment by hxgee** [comment]
Thanks – shall do

**Comment by hxgee** [comment]
![Color categories](https://user-images.githubusercontent.com/31830694/155908461-93bb1dda-53c4-4034-a8eb-63d22dd98ba2.jpg)
![Mapping](https://user-images.githubusercontent.com/31830694/155908524-2258152d-166b-4058-a916-cd8ead2d0a3f.jpg)

**Comment by hxgee** [comment]
Attached

**Comment by phw198** [comment]
So in the grid, on the left next to the Google "Peacock" which is covered by the dropdown from "Test map", what have you selected? That specific Outlook category will sync as Peacock in Google.

**Comment by hxgee** [comment]
Originally it was sync to a blue color with out any intervention by myself.

I tried to change it to a more peacock color 

But it looks like this:


Thanks

**Comment by phw198** [comment]
Once again, GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

For each Outlook category you wish to sync to Google Peacock colour, you will need a row in the mapping screen.

**Comment by hxgee** [comment]
Sorry ...
![image001](https://user-images.githubusercontent.com/31830694/158076225-7f751956-7cb3-45ce-8a7b-3bfb1cdf486b.jpg)
![image002](https://user-images.githubusercontent.com/31830694/158076227-67c13938-f367-487f-a497-4c5e96ac351b.jpg)
![image003](https://user-images.githubusercontent.com/31830694/158076228-863a74b7-42e7-4fd8-993c-b4b0c80208aa.jpg)

**Comment by phw198** [comment]
So on that basis, any new item with the "OGCS Blue" category in Outlook will sync to Google with Peacock colour. Are you saying that is _not_ happening?

If there are any existing items already synced to Google without Peacock set, try pressing `Shift` and clicking `Sync` to do a full sync.

**Comment by hxgee** [comment]
Sync is happening but I cannot get the OGCS Blue color to match the Peacock color.  Is this by design?  I created an OGCS Peacock and it still changes the color to a "blueberry blue"

thanks

**Comment by phw198** [comment]
I'm not sure what you mean by "created an OGCS Peacock" (aside from creating a new Outlook category called that)? You can map the Google colour "Peacock" to any Outlook colour/category - the name is not relevant.

It would help to follow the guidance for reporting issues and provide your `OGcalsync.log` file. I'm not even sure which direction you are syncing in. 

To confirm the functionality, for syncing O->G with the configuration in your screenshot, any Outlook item with the primary category of "OGCS Blue" will sync to Google as Peacock. If existing items have synced with the wrong colour, try a full sync by pressing and holding `Shift` while clicking `Sync`.

**Comment by hxgee** [comment]
Sorry I will try to explain .....

Google Category color is Peacock Blue as above
Outlook Category color looks like Peacock Blue i.e. looks same as Google Category Color as above
but OGCS mapping shows the color as blue not Peacock blue as above.  I can select the mapping correctly but the color showing up in the mapping is blue - not peacock blue.   I have no idea if I can change the mapping color in OGCS?

If this doesn't make sense to you - apologies for wasting your time - please go ahead and close the request.

I am synching one way - Google to Outlook but have tried two way as well.

Thanks

**Comment by phw198** [comment]
OK, I've set up exactly the same mapping as you, created a Google item, assigned it the Peacock colour and synced it to Outlook - OGCS gave it the "OGCS Blue" category as expected:
![image](https://user-images.githubusercontent.com/11843015/161646268-b17d5760-ce59-4b18-896b-8bfae8e3384e.png)

I'm not sure if I'm missing something here? Are you actually setting the colour on the individual Google calendar event, or is the default for the whole calendar Peacock?

**Comment by hxgee** [comment]
ah thats what I want - i want the same color blue you're getting for OGCS Blue - my blue shows up as a blueberry blue color not peacock blue.  The color is set at the individual calendar event by way of categories

**Comment by phw198** [comment]
Categories is solely an Outlook concept, all Google has is the ability to set an individual colour to an event. Blueberry and Peacock are both Google colours, so I'm still non-the wiser on what you're quite doing.

It's as simple as:

1. Create a Google event and set the colour of it to Peacock
2. One-way sync to Outlook, OGCS will set the category for it to "OGCS Blue", as per your mapping:
![image](https://user-images.githubusercontent.com/11843015/161647893-98be5fda-15c8-4454-b4ff-695550c9c892.png)

**Comment by hxgee** [comment]
Thanks Paul for the efforts - I basically want the OGCS Blue color (its showing up as a darker blue (blueberry blue) than the peacock blue) to be the same color as the Google Color (in this case Peacock).  The only way it works now is if I go into Outlook afterwards to change the color manually to match the Google color - change it from the darker shade blue to the peacock blue.

**Comment by phw198** [comment]
Sorry, but you're really not giving me anything to go on. No log file, no description of the Outlook category that OGCS _is_ assigning and the colour that you have assigned in Outlook to that category etc etc....so unfortunately, I'm gonna need to close this issue. I hope you manage to find a configuration the works for you!
