### ISSUE TITLE
O->G: Colours are lost and set to default on 2nd sync

### ISSUE THREAD

**Issue by orgdave** [phw198/OutlookGoogleCalendarSync#1389]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.3  
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
On the first sync (outlook to google only) meeting colours are transferred to google calendar. On 2nd sync all meetings in both Outlook and Google are set to the meeting default colour in google

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsynclog2022-02-18.xls](https://github.com/phw198/OutlookGoogleCalendarSync/files/8102088/OGcalsynclog2022-02-18.xls)

**Comment by phw198** [comment]
I can't replicate this, but there are some oddities in your log:
1. You previously configured a colour map for Outlook category `All About Children`, but it seems there is no category colour assigned in Outlook for it any more? Did you delete it?
2. You have excluded certain categories from sync, one of them `ALL ABOUT CHILDREN` - did you maybe change the category name from title case to all uppercase at some point?

Could you resolve the above issue in your colour map configuration and see if that helps fix the overall problem? If not, please upload your log file again.

> On 2nd sync all meetings in both Outlook and Google are set to the meeting default colour in google

What did you mean by this? You are only syncing one-way from Outlook to Google, so nothing should ever change in Outlook. What is the "default" colour in Google? Peacock?

**Comment by phw198** [comment]
Think I have replicated this issue actually:
1. Create a category `Test` and assign it to an Outlook item
2. Create a custom mapping for `Test` to a Google colour
3. Sync it to Google complete with colour
4. Rename Outlook category to `TEST`
5. Force a full sync and see change of colour back to default
6. Open custom map and see there is a blank for the Outlook category.
     1. Actually this crashed OGCS if a refresh of categories isn't done first!

I see if I can get a fix out for this.

**Comment by orgdave** [comment]
Hi Paul,

Thanks for the update – can you let me know when the fix is out and how I should go about loading it.

Many thanks and keep up the good stuff!

Cheers,
Dave

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.9.3.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8192706/v2.9.3.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by orgdave** [comment]
Hi Paul,

Thanks for the update (Literally 😊)

It seems to be working ok – but there is one small issue. I can’t seem to tidy up the colour mappings and as a result have a “multiple mapping” which I can’t clear.

Can you tell me how to either – 
1.	Clear the multiple mappings (see images below)
2.	Reset all the mappings so that I can re-map them all from fresh.

Otherwise it seems to work as required.

The good news that if we can sort this, I have ordered my 5 colleagues to install the sync so hopefully a few more £ for the pot.

Thanks again for your help and guidance.

Kind regards,
Dave

**Comment by phw198** [comment]
Hi @orgdave 

Unfortunately images and attachments can't be added to GitHub via email, so I'm not sure what your mappings are looking like. However, you should be able to click on the left hand end of the row to highlight the whole row and these hit the `delete` key to remove the row?

![image](https://user-images.githubusercontent.com/11843015/158062189-2ee7e688-c067-465a-93d5-0369d4e3db98.png)

If not, we can edit the `settings.xml` file directly, but that shouldn't be necessary!

**Comment by phw198** [comment]
@orgdave Is everything on this working as you'd expect now?

**Comment by phw198** [comment]
I'll roll the fix here into the next alpha release - if there are any further problems, please raise a new issue.
