### ISSUE TITLE
Scheduling multiple profiles

### ISSUE THREAD

**Issue by SDeGonge** [phw198/OutlookGoogleCalendarSync#1390]
Version 2.9.3.0 portable

In the past I've used 2 instances to sync 2 different calendars.

Perhaps I'm not understanding the profile feature of the latest version...
With 2.9.3.0 I'm attempting to consolidate to one instance using 2 profiles. I'm able to create my profiles, however, sync will only use the currently selected profile. Is there a switch to tell OGCS to sync all profiles when syncing?

Thanks

**Comment by phw198** [comment]
You would set each profile to sync automatically on a schedule, and they will run as per that schedule. If you click the `Sync` button manually, it will only sync the currently displayed/selected profile.

**Comment by SDeGonge** [comment]
Thanks for the quick replay. I guess I was just impatient and didn't wait for my 2 hour update to execute.
