### ISSUE TITLE
Unintelligible UI

### ISSUE THREAD

**Issue by gcbodie** [phw198/OutlookGoogleCalendarSync#1391]
**OGCS Version**: v2.9.3.0
**Edition**: Installed 
**Sync Direction**: O<->G if I'm lucky

**Bug Description**  
UI messed up, form controls overlay each other making it "a challenge" to use the screen with confidence. Just downloaded and installed on Win 10 Pro 21H2 and doing my initial Settings configuration. Here's one screen but several others are equally messed up.

![Capture](https://user-images.githubusercontent.com/97281272/155653116-5881e9c2-3446-45ee-b9f2-b42f6f1ef460.JPG)

**Comment by phw198** [comment]
Thanks for reporting this - however, it's a duplicate of #1329, which is awaiting more details around the Windows display settings.
