### ISSUE TITLE
Unable to find a Calender folder in the alternative mailbox

### ISSUE THREAD

**Issue by FranzKillig** [phw198/OutlookGoogleCalendarSync#1392]
Hello, I installed above version 2.9.0 on two systems. Each with Windows 11 and current Office 365 version. It worked right away on the first system. With the second system, however, I get the error message mentioned above. If I select "alternative mailbox", the above searches for a calendar, but does not find it, although it is available, and then aborts with the error message mentioned. The alternative mailbox is an "internet calendar"
Greetings Franz

**Comment by phw198** [comment]
:spiral_notepad: On the system that is having the problem, can you provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)). after you have searched the calendars and it has not been found. 

If you could also do the same search on the system that does work and then send me that log file too, so I can compare?

Can you also see any difference in how the accounts have been set up in Windows/Outlook between the two systems?
