### ISSUE TITLE
Nest Hub Notifications 

### ISSUE THREAD

**Issue by BublilDaniel** [phw198/OutlookGoogleCalendarSync#1393]
**Is your feature request related to a problem? Please describe.**
I got a Google Nest Hun at my office, I would like to see notifications for upcoming events.
The problem is that google wont show notifications for calendar events only for reminders.
[(based on this)](https://www.googlenestcommunity.com/t5/Speakers-and-Displays/Nest-Hub-Calendar-notifications/m-p/30336/highlight/true#M6770)

**Describe the solution you'd like**
Add an option to create all events to google as reminders instead of events

**Describe alternatives you've considered**
I tried to add a calendar item  but it wont show on the Nest, only on my phone.

**Additional context**

Thanks

**Comment by phw198** [comment]
Reminders, tasks and calendar events are all distinct from each other in the Google ecosystem - I wouldn't want to blur this by syncing Outlook calendar items to Google reminders. 

> google wont show notifications for calendar events only for reminders

I'm not sure this is quite true? I have a hub and when I approach it, it will display current/upcoming calendar items - I think it started using echo-location around 2020 to detect your presence and therefore whether you are nearby. Ultrasound sensing and personal results both need to be enabled for this. Possibly if you have it in the office and you are sat fairly still it doesn't know you are nearby?

Granted, calendar events are never audible announced on the Hub, but it doesn't seem right to sync across product stacks. I started OGCS before the Hub, and probably for the same reason you want this, I created a Tasker script on my phone to announce meetings when they started....

**Comment by BublilDaniel** [comment]
my nest hub wont show my calendar that often, and even though I still want a notification.

I understand your point that those 2 different.
I will open tickets for google maybe that can add notifications for calendar events also

Thanks
