### ISSUE TITLE
Profiles: Incorrect Outlook calendar may be targeted

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1394]
The target Outlook calendar is sometimes not set correctly, which can cause items to be created in the wrong calendar or, if bi-directionally syncing, incorrectly deleting items from Google.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.9.3.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8149198/v2.9.3.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by chross** [comment]
Hi!
It seems to work now, however, I need some more testing as some entried were duplicated and need manual removal.
I will report back if anything is amiss.

**Comment by phw198** [comment]
@chross No news is good news? Hopefully I'm good to roll this into the next release...

**Comment by Kuki77** [comment]
> 📦 This should now be resolved with [hotfix v2.9.3.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8149198/v2.9.3.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
> 
> Please let me know how it goes.

I can confirm, that the fix solved this issue on my side, too.
