### ISSUE TITLE
New appointment failed to save. Precondition Failed [412]

### ISSUE THREAD

**Issue by SDeGonge** [phw198/OutlookGoogleCalendarSync#1397]
**OGCS Version**: v2.9.3.3  
**Edition**: Portable  
**Sync Direction**: G->O

**Bug Description**  
New appointment failed to save. Precondition Failed [412=PreconditionFailed]. 
This failed message occurs when an item was added to a google calendar on my android device then attempts to sync on my laptop which is running Outlook. If I continue, it appears to sync okay but each time it syncs I get this message. Also, the sync window shows OGCS deleting the item(s) then attempting to add the same item(s) back.

![image](https://user-images.githubusercontent.com/14916505/156904774-8639ad71-2ffe-4324-ac4b-3a2d39f5ac95.png)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8191758/OGcalsync.log)

**Comment by phw198** [comment]
So just to be clear, this issue is still occurring after applying #1394, as this is what I initially thought could be causing it? Your logfile is very verbose - could you decrease it to just `DEBUG`, reproduce the issue and then re-upload please?

#528 also deals with `412` errors - that seemed to indicate multiple instances of OGCS may be running. Is this the case for you too?

**Comment by SDeGonge** [comment]
Yes, 2.9.3.3 installed. I will upload debug log next time it happens. I rebuilt my configuration a few days ago and have not seen the problem yet. Note that prior to using the current beta I was running 2 instances so I could sync 2 calendars. When I started using the beta, I continued launching via the command line and was specifying the settings file...
OutlookGoogleCalendarSync.exe /s:D:\Apps\OGCS\My Settings\settings.xml /l:D:\Apps\OGCS\My Settings\OGcalsync.log
Now I'm just launching OGCS without the command line switches since there's only one configuration now.

One thing to note: Prior to getting the 412 error, the sync would delete the item in question from outlook then it would attempt to add it again from google and that's when the error occurred. Also note that the error seems to be related to when an event is added to a google calendar on another PC then synced to outlook on my computer.

Let me know if there's anything else you need.

**Comment by SDeGonge** [comment]
Just got the 412 error. Log file attached.

![image](https://user-images.githubusercontent.com/14916505/158281163-554ff49e-1206-4cd9-b988-7443d6110beb.png)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8249169/OGcalsync.log)

**Comment by SDeGonge** [comment]
> Just got the 412 error. Log file attached.
> 
> ![image](https://user-images.githubusercontent.com/14916505/158281163-554ff49e-1206-4cd9-b988-7443d6110beb.png) [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8249169/OGcalsync.log)

03/18/22 - I ticked off the following in my profiles to see if it helps.... 
![image](https://user-images.githubusercontent.com/14916505/159028504-d3f109e1-ed87-47f7-a370-c61df4878cf0.png)

**Comment by SDeGonge** [comment]
> I ticked off the following in my profiles to see if it helps....
> ![image](https://user-images.githubusercontent.com/14916505/159824350-ce06d048-a11e-4487-bd32-c65190213270.png)
> 
SUCCESS!  It has been 5 days and no more errors! Don't know why the errors occur when it's unchecked.

**Comment by phw198** [comment]
OK, so I have an idea on what's going on, but need a bit more background.

* The calendar item is originally created on Google using what mechanism? Via an app on an Android device? What app are you using?
* The initial sync is fine, to copy it to Outlook and subsequent syncs don't make any change?
* _Something_ is then done on either Outlook or Google to amend the item - do you know what? On what device/app?
    * On your log file it detects a copy-and-paste action, but determines it's not an appointment item. Do you know what this copy-and-paste was? Is this the trigger for the problem?
* When OGCS next syncs, the deletions and error occurs (worked around by option to Merge items)
* You do a bi-directional sync on your WORK profile, then HOME, then WORK. Does the problem only show after HOME has synced? Might be worth turning off the schedule and manually triggering them to figure this out...

**Comment by SDeGonge** [comment]
So checking the "Merge with existing entries" did not solve the problem - just happened again this week.

> * The calendar item is originally created on Google using what mechanism? Via an app on an Android device? What app are you using?
The last time I got the error it was from an Outlook created item so it actually may not matter which device created the item. Initially it was Google created items but the last time it was an Outlook item.

> * The initial sync is fine, to copy it to Outlook and subsequent syncs don't make any change?
Not sure since I don't monitor the sync status until I get the error popup.

> * _Something_ is then done on either Outlook or Google to amend the item - do you know what? On what device/app?
Possibly editing a scheduled item may cause it but since it is not easily repeatable I'm not sure.
   
>   * On your log file it detects a copy-and-paste action, but determines it's not an appointment item. Do you know what this copy-and-paste was? Is this the trigger for the problem?
I'll watch for that next time.

> * When OGCS next syncs, the deletions and error occurs (worked around by option to Merge items)
Got an error this week with the Merge items checked so my theory that this was a fix no longer applies.

> * You do a bi-directional sync on your WORK profile, then HOME, then WORK. Does the problem only show after HOME has synced? Might be worth turning off the schedule and manually triggering them to figure this out..
Not sure but I'll try manually synching.

Sorry I couldn't answer any of your question. I'll manually sync and attempt to duplicate the problem and post the logs.

**Comment by SDeGonge** [comment]
ok...I was able to repeatedly create the error...
1. Create an appointment `TEST - CREATED IN OUTLOOK` in Outlook
2. Sync two-way with WORK profile
3. Syncs item to Google (no problem)
4. Delete the appointment in Outlook
5. Sync two-way with WORK profile
    1. Google item is deleted OK
    2. Outlook item recreates, then fails to update the non-exists Google item

Log file attached.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8405127/OGcalsync.log)
[settings.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8405135/settings.zip)

**Comment by phw198** [comment]
Nope, I still can't replicate this!! I have a suspicion this is related to #1396, but you don't have the build that includes the final commit [1d9defb](https://github.com/phw198/OutlookGoogleCalendarSync/commit/1d9defbc0653aaa03c7f98ffa4ba2645f210b176). Let me provide another build...

**Comment by phw198** [comment]
:package: Please try replicating the issue with [v2.9.3.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8405279/v2.9.3.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes...

**Comment by SDeGonge** [comment]
That version appears to have worked. Was not able to duplicate issue. I'll monitor this week and report back.

**Comment by phw198** [comment]
OK, that's good news. Changes in #1396 will be going into the next release anyway, so hopefully this ticket can then be closed too.

**Comment by phw198** [comment]
@SDeGonge Is v2.9.4 behaving itself for this issue? If so, let's close it off.

**Comment by SDeGonge** [comment]
All is good.
No more problems.
