### ISSUE TITLE
Appontment update failed

### ISSUE THREAD

**Issue by Curtalain** [phw198/OutlookGoogleCalendarSync#1400]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

Bonjour, Hi,

**OGCS Version**: v2.9.3.0
**Edition**: Installed 
**Sync Direction**: O<->G
Device : PC windows 10 pro version 1909, system version 18363.1440.

**Bug Description**  
Appointement update failed

![image](https://user-images.githubusercontent.com/94040074/157440313-5f72abe6-cf69-482a-9ca6-789943766c8b.png)
 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8214567/OGcalsync.log)

**Comment by BarryBJB** [comment]
Hi - I have exactly the same issue -  Appointment update failed. #1395 - opened 9 days ago.  There´s been no response to mine, so I though commenting on yours might help to raise it´s profile a little.

**Comment by kwagner115** [comment]
I too have been experiencing the same issue. 

And I am running 2.9.3.2.

**Comment by Curtalain** [comment]
Hello
I started the DCOM server in Services Administration from the control panel and it works

**Comment by phw198** [comment]
@Curtalain It's rather odd, as OGCS was working fine except for when processing the series master of `08/04/2014 (R) => "Anniversaire Lolo"` and then it would fail each time on that one. But the COM service must have been kind of working for OGCS to be able to get the other calendar items. I think I'll put this down to the service being in an odd state and a restart fixed it.

Out of interest, had you not reboot inbetween raising the issue and finding the solution?
