### ISSUE TITLE
Sync items as private, without everyting is marked private.

### ISSUE THREAD

**Issue by anders-m** [phw198/OutlookGoogleCalendarSync#1401]
OGCS 2.9.3.0
I can't figure out how to set up the sync, so my Google calender items is synced to Outlook as private. This is how the settings are now:
![image](https://user-images.githubusercontent.com/96893120/157619838-f32c4580-c9fc-4c8b-9d1f-bafad908a3d1.png)

The problem is, that the items from Outlook is synced to Google, and then synced back to Outlook as private. That way all my items is now private. How should I do this the correct way?

**Comment by phw198** [comment]
I think you need to change it to "For items created by sync in Outlook calendar"...set entries as private.

**Comment by anders-m** [comment]
Hi Paul
Thanks for the feedback. After trying a lot of settings, I got it to work! I dont know how, but from now on, Outlook entries dont come back as privat, and it is the same settings as in the first post... Stange, but nice!
