### ISSUE TITLE
Items become "unconfirmed" for organiser after being moved

### ISSUE THREAD

**Issue by SteveH-B** [phw198/OutlookGoogleCalendarSync#1402]
**OGCS Version**: v2.9.0.0  
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
A synchronised item goes from being confirmed to being unconfirmed in the calendar if it is rescheduled.

**Steps to Reproduce the Issue**  
1. Create calendar item in Google Calendar
2. Sync - Item appears in Outlook
3. Move item in Google Calendar to new time
4. Sync
5. Item becomes "unconfirmed" in Google Calendar (Even for me as the organiser)
6. Set status in Google Calendar to "Going - Yes"
7. Sync
8. All appears OK
9. Sync
10. Calendar item goes back to being unconfirmed!
11. Repeat ad nauseum from step 6 in never ending loop

**NOTE:** I don't know if the same is true for items created in Outlook but I suspect it may be!

**Any other information**  
Log file attached
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8234016/OGcalsync.log)

**Comment by phw198** [comment]
Please could you try with the below patch - I've applied it to 2.9.0, so just patch the version you have without upgrading.

:package: [v2.9.0.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8403199/v2.9.0.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

If it doesn't fix it though, you'll need to upgrade to the latest alpha and see if you can replicate the problem there. But I would advise to wait until v2.9.4 is out, which should be very shortly.

Let me know how v2.9.0.10 goes...

**Comment by SteveH-B** [comment]
Hi

I've added the hotfix and told defender not to block it but now when I run the app it doesn't bring up the splash screen and when I watch in task manager it seems to start for a few seconds and then disappear.

Nothing in the taskbar (as you would suspect if it is closing down).

Tried rebooting a couple of times but doesn't get it running.

Have reverted to previous release while waiting for v2.9.4

Regards
Steve

**Comment by phw198** [comment]
Did you definitely apply the patch over v2.9.0? Were there any updates to the `OGcalsync.log` file when it briefly ran?

But yes, as you say, might be easiest to wait for v2.9.4 and then we'll pick this back up...

**Comment by SteveH-B** [comment]
Hi

I tried again and this time I Put the files in...

C:\Users\steve\AppData\Local\OutlookGoogleCalendarSync

AND

C:\Users\steve\AppData\Local\OutlookGoogleCalendarSync\app-2.9.0-beta

Didn't run from desktop shortcut BUT DID run if I go to C:\Users\steve\AppData\Local\OutlookGoogleCalendarSync\app-2.9.0-beta and double-click the exe file.

Now appears to be working properly when I update/move entries.

Thank You.

**Comment by phw198** [comment]
Glad you got it working and confirming it's also fixed the issue! :+1: 

The instruction are _not_ to replace the executable in `C:\Users\steve\AppData\Local\OutlookGoogleCalendarSync` though - pretty sure you'll have broken the upgrade mechanism as well as it not running from the shortcut :slightly_frowning_face:  If so, you'll need to install OGCS again by downloading the next release from the website.

**Comment by SteveH-B** [comment]
> Glad you got it working and confirming it's also fixed the issue! 👍
> 
> The instruction are _not_ to replace the executable in `C:\Users\steve\AppData\Local\OutlookGoogleCalendarSync` though - pretty sure you'll have broken the upgrade mechanism as well as it not running from the shortcut 🙁 If so, you'll need to install OGCS again by downloading the next release from the website.

 **FURTHER UPDATE AND QUERY**

The good news is that I didn't delete the original files in the folder... I renamed them so now I have the patches installed in the right place and the program starts as it should using the original installed file.

**I do have one more query though...**

I repeated my test sequence and it works for a new entry I created **BUT** an existing entry keeps resetting back to "Unconfirmed" any ideas why this might be? I've added the Debug level log - It is the "Mike Jordan" entry that keeps resetting back to Unconfirmed.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8426490/OGcalsync.log)

**Comment by phw198** [comment]
I'm not too sure. Can you try doing a full one-way sync O->G by pressing `Shift` and clicking `Sync` to see if that helps? You could also try deleting the item in Google and letting OGCS recreate it (make sure you have one-way sync on before doing this).

**Comment by SteveH-B** [comment]
Tried your suggestion and it's had the reverse effect... 3 items that were confirmed for next week have become unconfirmed after the forced 1 way sync from O->G

Here's a screenshot = The blue text on white are the ones that have become unconfirmed (Don't worry about the green on white that's a view I have of my partner's calendar and she hasn't confirmed the Monday meeting anyway).

![image](https://user-images.githubusercontent.com/100773931/162491859-fdccfa0e-5e6d-4190-b42a-28fbc864a743.png)

Here's the debug log
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8454135/OGcalsync.log)

**Comment by phw198** [comment]
Sorry, I think I had forgotten that you were moving the item in Google and then the acceptance status was not syncing to Outlook properly. So O->G overwrote Google for those items that were still affected! I should have been suggesting G->O to make sure Outlook was correct, then two-way sync should be stable.

For any future occurrences of this issue, can you check the Outlook acceptance status is wrong, then G->O, confirm the acceptance status is correct, revert to G<->O.

**Comment by SteveH-B** [comment]
Bad news I'm afraid - Did as you suggested...

1. Accepted the 3 calendar entries (in Google) I had originated
2. Refreshed screen and all accepted
3. Changed to G->O
4. Did Full Sync (Shift + Sync)
5. Refreshed and all accepted
6. Changed back to G<-->O
7. Sync
8. Refresh Screen
9. 3 items revert back to unaccepted for me as originator

I'm beginning to think I jumped the gun when I said the patch had fixed the problem. Some of these events have been created since the patch was applied.

Logfile attached - Latest log entries in it are for the sync's mentioned
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8461758/OGcalsync.log)

**Comment by phw198** [comment]
Yes, I think maybe that patch wasn't the fix, or only partly at least. 

So I'm a little confused on the setup...
* You are the organiser of the meeting in Google? As the organiser, you don't have the option to say whether you are attending or not, so I don't understand how you say this is showing as unaccepted?
* Any others that are invited, their responses aren't affected and not reset to unaccepted?

....ohhhhh, I see! So I think I can reproduce the invite/acceptance with:

1. Create a Google calendar item in the non-default calendar (let's call it "OGCScal")
2. Invite Google account email address to the meeting
3. Click the email icon to notify yourself of the meeting
4. The meeting now appears in the default calendar as unaccepted
5. Click the default calendar meeting and now there is the Yes/No/Maybe option - click Yes

So, I have yet to play with how sync affects this....but if you are syncing the "OGCScal" calendar with OGCS, then I think there's nothing that can be done - you've invited the organiser and the organiser has no ability to accept/decline. What you're seeing is in the default calendar as a result of the invite being emailed.

Actually I can replicate this entirely outside of OGCS.

6. Move the meeting in "OGCScal", click "Send" to notify the guests
7. Watch the default calendar item switch back to unaccepted.

Question is, why are you inviting yourself?

**Comment by SteveH-B** [comment]
Hi Paul

I'm not actually inviting myself. As per the very first post on the thread. I'm simply creating the appointment in my default (Google Business) calendar.

As per this first screenshot you will see that I'm the organiser and yet my "Yes" button at the bottom has gone from shaded to blank (expecting me to now confirm). I need it to stay confirmed otherwise it won't show as busy for my public appointment system (Calendly) and it then let's people schedule calls when I'm already busy but the status has been changed by the sync.

![image](https://user-images.githubusercontent.com/100773931/162893592-ea0dc540-3f67-4c4d-84cb-eb5c4ea4e537.png)

In this second image you will see an appointment that I have organised (again not invited myself to) but it shows by default that the "Yes" box at the bottom is shaded and as a result the appointment is shaded in my calendar indicating the time is busy.  I haven't moved or updated this one in any way and it seems to be staying in its original state.

![image](https://user-images.githubusercontent.com/100773931/162891935-d888208d-6c5e-4579-bce5-27f79de68023.png)

Now in this screenshot I (as the organiser) have simply moved the event by an hour (dragged it in the calendar). Then I've run the sync (twice). And guess what... Yep it has become "Unconfirmed". The irony is that it is staying as "confirmed" not tentative in my Outlook calendar. It is simply moving the timeslot to the new time.

![image](https://user-images.githubusercontent.com/100773931/162893352-57f62ac7-71d4-4990-9af2-ee13dbbf33eb.png)

I'm coming to the conclusion that the only reason some of my past events aren't still changing back to unconfirmed is because they are now over the 2 day old threshold that I have set for syncing events in the past.

**Comment by phw198** [comment]
Thanks for the extra detail - really helpful. So it seems the functionality of meetings differs slightly when creating them in the default calendar:
1. Create an item in the default Google calendar
2. Invite someone else; you'll automatically be added as the organiser
3. Now clicking on the item, the Yes/No/Maybe option appears

I'll do some further testing around this, no I'm clearer on your use case 👍

**Comment by phw198** [comment]
:package: Please first upgrade to latest alpha v2.9.4 and then apply [hotfix v2.9.4.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8505656/v2.9.4.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes!

**Comment by SteveH-B** [comment]
> 📦 Please first upgrade to latest alpha v2.9.4 and then apply [hotfix v2.9.4.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8505656/v2.9.4.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
> 
> Let me know how it goes!

Hi - I've done this and so far so good - I have created and moved a test appointment in Google Calendar and it doesn't seem to be resetting. I will monitor this appointment for the next 48 hours and see that it doesn't become unset as it moves into the past.

**Comment by SteveH-B** [comment]
> > 📦 Please first upgrade to latest alpha v2.9.4 and then apply [hotfix v2.9.4.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8505656/v2.9.4.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
> > Let me know how it goes!
> 
> Hi - I've done this and so far so good - I have created and moved a test appointment in Google Calendar and it doesn't seem to be resetting. I will monitor this appointment for the next 48 hours and see that it doesn't become unset as it moves into the past.

Happy to report that the meetings I had yesterday, including the one I moved about a lot as a test have stayed solid within my calendar with me still marked as attending. On that basis I'd be happy to call this resolved. Just out of interest what did it end up being (in simple terms)?

**Comment by phw198** [comment]
Hmm, in simple terms... :slightly_smiling_face: Normally, the Outlook meeting organiser is not the same email address as the Google account owner, and when creating a Google calendar item via sync the organiser _has_ to be the Google account owner (which causes its own complexities). In your situation, the Google account owner is also the Outlook meeting organiser and I hadn't quite realised that Google allows the organiser to decline their own meeting (Outlook doesn't). So the fix was, although on creation in Google OGCS sets the attendance to "accepted", thereafter not to touch the attendance status in Google if they are the organiser.

**Comment by SteveH-B** [comment]
Thanks for sorting it.

**Comment by phw198** [comment]
Reopening until released into next alpha.
