### ISSUE TITLE
On Google Calendar, moved an older all-day event to today -- OGCS wants to delete the event instead of sync it to Outlook.

### ISSUE THREAD

**Issue by jgoggan** [phw198/OutlookGoogleCalendarSync#1403]
**OGCS Version**: v2.9.3.0 alpha
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I commonly have an "all day event" from the previous week that I didn't get to since I use them more as "to-do" items sometimes.  On Google Calendar, I usually drag them from their original day (which, again, has already passed a few days ago) to the current day (so that I will remember to do it sometime today).  When I do that, the next time OGCS syncs, it will ask me if I want to delete the event from today.  If I do, it is gone.  If I don't, it leaves it on the Google Calendar, but will then ask me again at the next sync and never syncs it to Outlook.

Note that, for date range, I have it sent to 1 day in the past and 60 days in the future.  If I move one from yesterday, it seems to work fine.  It has to be more than a day ago for this problem to occur (i.e. it comes from outside of the date range).  Note also that I have Delete Confirmation on.  With it off, the event is just lost/deleted!

**Steps to Reproduce the Issue**  
1. Create an all-day event on the Google calendar side that is older than the date range window (like a week ago when I have it set to just 1 day).
2. On the Google side, drag that event from the original day and drop it on today.
3. Sync

OGCS will ask "Delete 3/14/2022 -> 'John: Testing'?" instead of just sync'ing it to Outlook.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8245931/OGcalsync.log)

**Comment by phw198** [comment]
Hi @jgoggan and thanks for reporting this. Unfortunately, it's already recorded in the Known Issues/[Limitations](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#google-events), and there's no way for me to really fix this - best thing is for you to increase the "days in the past" date range.
