### ISSUE TITLE
Outlook data file corruption

### ISSUE THREAD

**Issue by cbarina** [phw198/OutlookGoogleCalendarSync#1404]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0.0
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
Occasionally, when the sync tool is open, it is not possible to open Outlook. Normally in this case I restart and it's ok. This last time, I got this message:

![image](https://user-images.githubusercontent.com/7785375/158362806-5f68086c-8ad9-4d2a-98a3-cef8f9701e63.png)

**Steps to Reproduce the Issue**  
1. Unclear as it is sporadic - can send log file but prefer to email privately rather than post here. 
2. Letting Outlook automatically restart didn't help - had to recreate data file.

**Comment by phw198** [comment]
I'm not sure Outlook corrupting its file is anything to do with OGCS. Outlook has a habit of doing this perfectly well itself, especially if the PST is pretty large - I think over 2Gb is known to start being problematic.

There is a dedicated [PST Repair Tool](https://support.microsoft.com/en-us/office/repair-outlook-data-files-pst-and-ost-25663bc3-11ec-4412-86c4-60458afc5253) from Microsoft too - might be worth trying that if is happens again, as well as making sure you are regularly backing up the PST file.
