### ISSUE TITLE
The application called an interface that was marshalled for a different thread. RPC_E_WRONG_THREAD [0x8001010E]

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#1408]
**Are you already using OGCS
2.9.3.0

**Describe the question you have**
Getting error message when trying to sync google to outlook.  Attched is logfile
[OGcalsync 032422.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/8344964/OGcalsync.032422.txt)

**Comment by michgal2k** [comment]
Fixed it myself

**Comment by jazzzsoftware** [comment]
Can you please share how you fixed it?

**Comment by jazzzsoftware** [comment]
Fixed myself as well. Saved settings and restarted OGCS. Ok after that.

**Comment by phw198** [comment]
@Surfrat @michgal2k Can you confirm if a save and restart permanently fixed this issue? This has also been reported on #1406, so would be good to know.

Thanks!

**Comment by phw198** [comment]
According to #1419, restarting OGCS is only a temporary fix :slightly_frowning_face:

**Comment by michgal2k** [comment]
It happened shortly after adding a new event to gmail calendar. I removed the event - ran OGCS - it ran fine.  I entered the event on Outlook and it worked fine & copied to gmail.

**Comment by jazzzsoftware** [comment]
It has been working fine for me since.
