### ISSUE TITLE
Call was rejected by callee: 0x80010001 RPC_E_CALL_REJECTED

### ISSUE THREAD

**Issue by JeroenTuinstra** [phw198/OutlookGoogleCalendarSync#1411]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.3 alpha
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
OGCS is installed to start 60 seconds after startup of the computer. At that time Outlook (LTSC 2021) is not running and OGCS crashes with the error: 0x80010001 RPC_E_CALL_REJECTED. In the systray a new background instance of Outlook is started (but greyed out) it seems the crash of OGCS causes background Oultook (for programmatic access) to lock up. By ending the Outlook process Outlook will be able to start again. 
When Outlook does run then OGSC sometimes works, sometimes not. I believe OGCS is not able to handle Outlook 2021 LTSC. 

**Steps to Reproduce the Issue**  
1. Start latop, wait for OGSC to start - error message appears
2. End task Outlook in task manager
3. Start Outlook
4. Start OGSC
OGSC cannot start before outlook is started. 

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8389339/OGcalsync.log)

**Comment by phw198** [comment]
This one is a bit of a head scratcher. Could you please apply the below patch - I'm hoping it should log the following line just before it crashes out:

`About to access Outlook oApp.version property...`

:package: [Patch v2.9.3.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8402558/v2.9.3.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know once you've applied it!

**Comment by JeroenTuinstra** [comment]
Have applied your fix. Cannot test immediately but will let you know if the issue has been solved. Thanks for the quick answer.

**Comment by JeroenTuinstra** [comment]
Applied the fix, but unfortuntately it is still crashing. I can only get it to work by opening up outlook once (after I end the task Outook for programme access), and restarting OGCS. 
However when it start I cannot open the OGCS UI screen. When you click in the system tray on the OGCS icon, it appears in the taskbar but then doesn't open the window. When you click on the icon in the taskbar it minimizes to the system tray.
Difficult change the settings.

**Comment by JeroenTuinstra** [comment]
Managed to get the window open by right-clicking the systray icon and click "sync now". It then opens the window.
Attached the latest log.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8405543/OGcalsync.log)

**Comment by phw198** [comment]
Seem like maybe a change in behaviour with LTSC 2021. Previously, Outlook would give a `RPC_E_CALL_REJECTED` when attaching to Outlook and it's unresponsive; with LTSC 2021 it seems the attachment works, but then it fails with `RPC_E_CALL_REJECTED` when you try and query any data from it.

:package: This should now be resolved/handled better with [v2.9.3.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8459367/v2.9.3.12.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by phw198** [comment]
@JeroenTuinstra Any luck with v2.9.3.12?

**Comment by edbonneville** [comment]
Hi! I am on a Windows 10 machine running v2.9.5, and also getting this error - only way to avoid is to first open outlook and then OGS (as suggested in #708)..

**Comment by phw198** [comment]
@edbonneville @JeroenTuinstra I've updated this hotfix to v2.9.5 - please could you apply [v2.9.5.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/9331266/v2.9.5.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes.

**Comment by edbonneville** [comment]
Thanks @phw198 , I tried applying just now: I get the splash screen showing the right hotfix version, but after that the main GUI does not appear and I do not see in the systray either (it does seem to be running as a background process though).

**Comment by phw198** [comment]
@edbonneville could you upload your ogcalsync.log file so I can take a look at what might be happening?

**Comment by edbonneville** [comment]
Here it is: [OGcalsync.log](https://gist.github.com/edbonneville/deb64af2bacbfb7341bf572ebbfbac87)

The last line is me ending the background process from the task manager, but I guess the issue might still be on my end given the "Outlook is running without GUI for programmatic access." line

**Comment by phw198** [comment]
@edbonneville Could you increase your logging level to FINE and try again? I think you should then see a line "About to access Outlook oApp.version property..." before it hangs - when you then kill from the task manager, it will then give "The remote procedure call failed.".

If so, then the question would be, why on earth is it hanging!? The line "Outlook is running without GUI for programmatic access." usually means that Outlook only has the "Meeting reminders" window up, but not the main application open. Is this the case for you, or maybe some other application/process is actually accessing Outlook and locking OGCS out...?

Note, your hanging issue appears to be different from the OP issue where it immediately errored without hanging.

**Comment by edbonneville** [comment]
@phw198 with this hotfix version I do not see the GUI at all so I cannot change it through there -  I did however edit the relevant line in settings.xml directly and the log file is just "About to access Outlook oApp.version property..." repeating itself over and over until I end via the task manager 

> usually means that Outlook only has the "Meeting reminders" window up, but not the main application open. Is this the case for you, or maybe some other application/process is actually accessing Outlook and locking OGCS out...?

For that first part I am not sure (normally OGS should be able to access outlook even if I have no opened it yet?), and for the second part no other process is accessing Outlook..

**Comment by phw198** [comment]
:package: Sorry, silly mistake with the previous hotfix - please try again with [v2.9.5.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/9440102/v2.9.5.13.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by edbonneville** [comment]
Thanks, it seems to work! I tried opening once while outlook was open, and another time once closed - I hope it will also work at startup.

I am also attaching the [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9442772/OGcalsync.log) file, since it seems to go "Call was rejected by callee" -> "Attachment failed - Outlook is running without GUI for programmatic access." -> starts a new instance, where it finally does its thing.

**Comment by phw198** [comment]
Thanks for confirming - I think that order of events you have described is OK, so maybe just confirm that it also works on startup when you get a chance and then I'll roll this into the next alpha release.

**Comment by edbonneville** [comment]
Can confirm it works on startup! Thanks again for the hotfix, and for all your work developing OGS 🥳
