### ISSUE TITLE
Update all items - instruction not visible

### ISSUE THREAD

**Issue by gcthys** [phw198/OutlookGoogleCalendarSync#1412]
Version 2.9.3.0
Under Settings->Sync Options->What, hover over the i after "Attributes to include. Affects newly": a yellow post-it appears with instructions to update all items. However, part of it is invisible. See attachment. Expanding the screen doesn't help.... 
![Schermopname (2)](https://user-images.githubusercontent.com/68611501/161059707-8e9d0a14-6e2f-4990-938c-0311f26a2eda.png)

**Comment by phw198** [comment]
The layout of almost everything is corrupted, not just the yellow box! Can you provide your Windows display settings as per https://github.com/phw198/OutlookGoogleCalendarSync/issues/1329#issuecomment-954724830 ?
