### ISSUE TITLE
Wwhat happens when I do NOT activate the Disable deletions button AND the confirm deletions buttons at same time ?

### ISSUE THREAD

**Issue by Hermann47** [phw198/OutlookGoogleCalendarSync#1413]
**I don´t want** to be forced to control every single term, **whether I have to delete or not delete the term.**

**Is there a possibility for an automatic execution ?** 
without the danger of wrong deletions ?

**Comment by Hermann47** [comment]
#

> **I don´t want** to be forced to control every single term, **whether I have to delete or not delete the term.**
> 
> **Is there a possibility for an automatic execution ?** without the danger of wrong deletions ?

**Comment by phw198** [comment]
Have a read here for [resolving deletion prompts](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).

If repeated prompts for deletion continue after that, it's very likely a bug that needs resolving - you shouldn't have deletions disabled once you have OGCS configured as required (it's really just to protect against people wiping their calendars while still testing different things out!).
