### ISSUE TITLE
Looks like the merging with preexisting items isn't working

### ISSUE THREAD

**Issue by Malli88** [phw198/OutlookGoogleCalendarSync#1415]
**OGCS Version**: v2.9.3.0 
**Edition**: Installed 
**Sync Direction**:  O->G

**Bug Description**  
The synchronization between my Outlook and my google calendar tries to delete all my google entries.
Even when I had the option "Merge with existing entries" on.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8399733/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. Try to sync outlook with google
2. turn the option for merging  on (you should activate confirm deletion too)
3. sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Are you sure the items being deleted were _never_ in Outlook and _never_ synced with OGCS?

This doesn't replicate what you are reporting:
* O->G sync with no merging
* Create an Outlook item "A", sync to Google
* Turn on merge and sync again, "A" is not deleted in Google
* Create a new item "B" in Google
* Sync again, both "A" and "B" remain.
