### ISSUE TITLE
Outlook to Google 2-way creating thousands of duplicates

### ISSUE THREAD

**Issue by JP3251** [phw198/OutlookGoogleCalendarSync#1418]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.3.0  
**Edition**: Portable  
[OGcalsynclog1.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/8430144/OGcalsynclog1.txt)
[OGcalsynclog2.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/8430146/OGcalsynclog2.txt)

**Sync Direction**: 
Profile ENV: O (Alternate Mailbox, Default) -> G (NORR)
Profile NORR: O (Default, Default ) <-> G (NORR)

**Bug Description**  
I tried deleting an event from Outlook profile ENV calendar called "Julian is One!" and it created thousands of duplicate events in both Google calendar and Outlook profile NORR calendar.
In the log, you can see around 14:28 PM it starts duplicating the event exponentially.

**Steps to Reproduce the Issue**  
1. Create event in calendar 1
2. Sync so this event shows up on NORR and Google calendar
3. Delete event in calendar1
4. Sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
I strongly suspect this is due to #1394 which has a hotfix posted.
