### ISSUE TITLE
BSOD with 2.9.4 alpha

### ISSUE THREAD

**Issue by sjsdoc60** [phw198/OutlookGoogleCalendarSync#1421]
Had 2.9.3 running and profiles worked well with 5 profiles.  previously had 4 instances of OGCS to do same thing.   This is on a new computer with Win 11, fresh install and new install of OGCS with no prior version on this PC.  This morning turning on PC it indicated 2.9.4 alpha ready. I pressed update.  Within seconds, I got the dreaded BSOD and a reboot.  Upon reboot, OGCS not functional. Icon no longer pointed to anything.  I cant even find OGCS in program files directory. I did find leftover in apps/data/roaming.  I uninstalled. I recovered my prior appsdata/roaming/ogcs data mainly for the settings as it took quite a while to set up all the profiles. I had a fresh backup with Acronis last night thankfully.  I downloaded the 2.9.4 from here.  It installed BUT it still says 2.9.3 in About?  Anyway, I'll stick with current as it appears to be working.  That is first BSOD in windows in years.  attached is the log.

**Comment by SVNKoch** [comment]
PS you forgot to attach the log

**Comment by sjsdoc60** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8483845/OGcalsync.log)

**Comment by phw198** [comment]
Your log file doesn't really show anything untoward, but I'd be surprised if the BSOD was related to OGCS - they are normally hardware/driver related.

See [here](https://www.thewindowsclub.com/find-and-view-bsod-log-files-in-windows-10-event-viewer#:~:text=2%5D%20To%20view%20the%20BSOD,Logged%E2%80%9D%20drop%2Ddown%20menu.) and [here](https://superuser.com/questions/1097234/where-can-i-find-last-blue-screen-error-message-after-reboot-in-windows-10) for instruction on how to look up what caused the BSOD in the Event Viewer. This should also say where the minidump files were put - would be helpful if you can upload that too.

**Comment by sjsdoc60** [comment]
OK. I did do what the links said.  There is only one bugcheck error and it doesn't say the program that caused the BSOD. I found the MEMORY.DMP but it is 2.2GB.

**Comment by phw198** [comment]
Maybe something to keep an eye on then, but as I say, I'd be surprised if it was related to OGCS.
