### ISSUE TITLE
Bug or User error

### ISSUE THREAD

**Issue by BillyJIV** [phw198/OutlookGoogleCalendarSync#1423]
----

**OGCS Version**: v2.9.4.0
**Installed or Portable**: Installed

**Problem Description**  
\I keep getting this error during a sync. I don't know if it is something I did wrong or a bug in the ALPHA release 2.9.4.0

![image](https://user-images.githubusercontent.com/28783671/163200766-8f20b7ee-2af5-40f3-9f26-f43f6f7d9181.png)

**Steps to Reproduce the Issue**  
1. \Just happens during normal sync
1. 

**Any other information**  
\<Update here>

**Comment by sunk818** [comment]
I get the same errors. 2.9.2 worked great for me for a very long time. 2.9.4.0 completely trashed all my Outlook entries. This is infuriating. You go from a great working 2.9.2.0 and now all my entries are completely trashed. I have to explain to colleagues why I declined meetings, asking for recurring meetings organized by someone else... I really didn't need this to happen today.

**Comment by BillyJIV** [comment]
I am new to this forum. Does the author monitor these messages and reply or is it strictly a user community. I just don't know what that message means and how to fix it. My syncs appear to be working so that is a win for me anyway. I am sorry to hear you are having lots of issues.

**Comment by fogoat** [comment]
Hey Billy. Just venting. Hopefully, I finally got it reconstructed after I restored all the deleted events from Google Calendar, and synced it back to Outlook. I just have to remember to confirm deletions and test heavily with any new version so bad things don't happen. I was spoiled by how well 2.9.2.0 worked even if I had three instances going.

The dev does reply, but it seems to be in sprints... so it may be immediate or after some time. With spring break time, I wouldn't be surprised if there was a delay. I suggest you try turning on Debug logging and try sync again. Then you can include the log text from the time you started the sync and when it ends. Make sure to "sanitize" any entries that may be sensitive by X-ing it out before attaching it here.

![image](https://user-images.githubusercontent.com/6989799/163496914-48c51583-9451-49cf-b3e6-c4ed6dca7d9a.png)

I use the portable install so I'm not sure where the OGcalsync.log is in the installed version (maybe %appdata%\..\Local ? ) but you can include a portion of the log attaching it in a comment.

**Comment by phw198** [comment]
Thanks for reporting - it was also covered in #1432 and a hotfix is available there :+1:
