### ISSUE TITLE
Download Embedds and Links for v2.9.4.0 broken because of setup.exe name change

### ISSUE THREAD

**Issue by SVNKoch** [phw198/OutlookGoogleCalendarSync#1426]
The Page (http://www.outlookgooglecalendarsync.com/) and githubs embedds
![grafik](https://user-images.githubusercontent.com/39488412/163251849-f73a2cc8-b38f-45b2-97bb-a123da0e7113.png)
both redirekt to 
```https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.9.4-alpha/Setup.exe```
but should be
```https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.9.4-alpha/OGCS_Setup.exe```

That's also probably why the embed on the website is still showing .3 as latest alpha version
![grafik](https://user-images.githubusercontent.com/39488412/163252405-211ae74d-6064-4649-8f23-4e1fa384d758.png)

**Comment by phw198** [comment]
Thanks @SVNKoch - the first link on GitHub `readme.md` was missed, but I spotted and fixed that earlier today.

The main website download link I leave on the previous release until rollout of v2.9.4 has finished, which again I did today :slightly_smiling_face:
