### ISSUE TITLE
2.9.4 Set colour/category to co-mingles with other profiles

### ISSUE THREAD

**Issue by fogoat** [phw198/OutlookGoogleCalendarSync#1435]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.4.0
**Edition**: Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

If I edit a profile and set a colour/category to a specific color, the next profile I edit will save to the same color entry. I use custom colors called OGCS Green, OCGS Maroon, and OCGS Blue. If I save a profile with OGCS Green, the next profile is also OGCS Green even though I clearly set it for OCGS Maroon previously.  I have not tested if setting it at Calendar Default will sync with the respective unique calendar color or not. 

The workaround for me was to not use Set color/category to and use mapping under the What section.

**Comment by phw198** [comment]
I'm not sure I quite understand the issue and I can't replicate it either (both in the GUI and in the synced calendars).

So you're syncing G->O and setting the "Set colour/category to" under "How"? When you select/change the colour in Profile A, when you switch to the other Profiles, they have also been set to the same colour? 

Or is it not in the GUI, but when the sync happens, the calendar items have the wrong colour?
