### ISSUE TITLE
Log should obfuscate meeting details if it's going to be sent to the developer

### ISSUE THREAD

**Issue by forrcaho** [phw198/OutlookGoogleCalendarSync#1440]
I just got a prompt asking whether I wanted to automatically send logs to the developer.

I certainly want to help the project, but when I looked at the logs, I saw that meeting titles and descriptions were in there, and I don't really want to share that information. I declined.

If there was an option to hash those personal details, I'd be  happy to automatically send my logs.

**Comment by h07d0q** [comment]
just realized, that the address is not obfuscated in WARN OutlookGoogleCalendarSync.Forms.Main.
DEBUG OutlookGoogleCalendarSync.GoogleOgcs.Authenticator is fine
```
DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [280] -  Getting MD5 hash for 'ab******c@gmail.com'
WARN  1 OutlookGoogleCalendarSync.Forms.Main [1035] -  Outlook calendar selection changed to: NEEDSTOBEOBFUSCATED (ID: NEEDSTOBEOBFUSCATED)
WARN  1 OutlookGoogleCalendarSync.Forms.Main [1202] -  Google calendar selection changed to: NEEDSTOBEOBFUSCATEDASABOVE@gmail.com (ID: NEEDSTOBEOBFUSCATEDASABOVE@gmail.com)
WARN  1 OutlookGoogleCalendarSync.Forms.Main [1202] -  Google calendar selection changed to: NEEDSTOBEOBFUSCATED (ID: NEEDSTOBEOBFUSCATED@group.calendar.google.com)```

**Comment by phw198** [comment]
@h07d0q Thanks, I've now made that change.

@forrcaho I'll have a think on this, as very often being able to identify the subject line of calendar items is _really_ helpful when troubleshooting issues with the user

**Comment by forrcaho** [comment]
As a software development contractor working with a company whose plans (and discussions about those plans) aren't public, you can understand my reluctance to share even the meeting titles.

**Comment by phw198** [comment]
I'm going to leave it as it is - users have the option to not provide the log files, and it'll just be too painful working with logs with no meaningful subjects.
