### ISSUE TITLE
Scheduled syncs don't fire after first push sync

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1443]
Scheduled syncs will run as long as there has not been a push sync from Outlook or a manual sync. The first push sync from Outlook will work then no further syncs other than manual will occur.

![Screenshot 2022-04-24 174328](https://user-images.githubusercontent.com/70089616/164987007-ea4ced55-23ea-463c-bee6-7e82cc514896.png)

_Originally posted by @tnjgb in https://github.com/phw198/OutlookGoogleCalendarSync/issues/1432#issuecomment-1107869902_

**Comment by phw198** [comment]
Hi @tnjgb - are you still encountering this? I can't replicate it on v2.9.5...

**Comment by tnjgb** [comment]
It is not happening on v2.9.5, I assumed you had fixed it in this version.

**Comment by phw198** [comment]
Not knowingly I don't think! But good news so I'll close this, but do post if you notice it again.
