### ISSUE TITLE
Google handshake failed - proxy blocking outgoing traffic

### ISSUE THREAD

**Issue by Big-Gaz** [phw198/OutlookGoogleCalendarSync#1444]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.4.6
**Edition**: Installed
**Sync Direction**: G->O & O<->G (two profiles)

**Bug Description**  
First auto-sync on opening and subsequent manual syncs result in error as per screenshot

**Steps to Reproduce the Issue**  
1. OGCS automatically starts up with Windows - sync starts but error message appears
2. While using G->O profile, on "Sync" tab, click on "Start Sync" - sync starts but error message appears (G->O)
3. Change profile in Settings tab (this one is G<->O)
4. On "Sync" tab, click on "Start Sync" - sync starts but error message appears

**Any other information**  
Google API keys have *not* been changed.
https://gist.github.com/Big-Gaz/4d2fd29054d9ac989911e7412c0dd505

![Untitled](https://user-images.githubusercontent.com/24977745/165066542-d46a4cf1-83ea-4cd5-b187-787461d9e0ab.png)

**Comment by phw198** [comment]
Your proxy is killing all outgoing traffic. Does the same happen for previous versions of OGCS?

You could also try giving the hotfix in #1374 a whirl in case it's related to the browser agent setting OGCS is using and the proxy doesn't like it...

**Comment by Big-Gaz** [comment]
Thanks for responding - the anti-virus was the problem and it's sorted now.
