### ISSUE TITLE
Google Apps Script version

### ISSUE THREAD

**Issue by JohnLockeNJ** [phw198/OutlookGoogleCalendarSync#1450]
Would you consider leveraging the insights from this project to create a Google Apps Script version that runs every 15 min on Google's servers without the need for downloading and installing software?

Here's an article about how to do it for a one-way sync between two Google Calendars:
https://medium.com/@willroman/auto-block-time-on-your-work-google-calendar-for-your-personal-events-2a752ae91dab

Here's a fork of that script that does a two-way sync:
https://gist.github.com/alranel/f1c9b7abb9013f4a39aa4fb12f6de4ef

Is there a way to create a similar script that can sync Exchange to Google Calendar, possibly leveraging some of your existing code logic?

**Comment by JohnLockeNJ** [comment]
Never mind. I figured out that the existing scripts I linked can work if you just share the Outlook Calendar as an ICS link to Google Calendar first!
https://gist.github.com/alranel/f1c9b7abb9013f4a39aa4fb12f6de4ef?permalink_comment_id=4148162#gistcomment-4148162

**Comment by phw198** [comment]
Thanks for posting and the links provided. The focus of OGCS is really to help people sync their calendar out from Exchange (which most likely blocks external apps from connecting in to it) and syncing it to Google. This is why it runs as a client install through Office Outlook.

Whilst having cloud based syncing is very useful if the connectivity works, it's not something I have time to invest in, plus there are plenty of other players offering cloud solutions. If sharing an ICS of your Exchange calendar works and the delay in ICS updates is OK for you, sounds like you have a solution already :slightly_smiling_face:
