### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#1456]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
Ran OGCS - keep getting error

**Steps to Reproduce the Issue**  
1. Go to Start Sync
1. Sync will not finish
[OGcalsync 05.01.22.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/8600476/OGcalsync.05.01.22.txt)
.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by gismo2004** [comment]
Duplicate... (https://github.com/phw198/OutlookGoogleCalendarSync/issues/1449)

**Comment by phw198** [comment]
Duplicate of #1422 which has hotfix posted.
