### ISSUE TITLE
"Object reference not set to an instance of an object." error when synchronising.

### ISSUE THREAD

**Issue by Interlate-AlanCarter** [phw198/OutlookGoogleCalendarSync#1457]
**OGCS Version**: v2.9.4.0
**Installed or Portable**: Portable

**Problem Description**  
"Object reference not set to an instance of an object." error when synchronising.

**Steps to Reproduce the Issue**  
1. Run 2.9.4 with an existing configuration and try synchronise.

**Any other information**  
I've been using the portable version since 2.8.6 and upgraded it by overlaying the new files over the top of it.
[OGcalsync294.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8606646/OGcalsync294.log)

**Comment by TheGooginator** [comment]
I have also noticed that I am unable to get my sync to continue after the first one with the same error.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8608378/OGcalsync.log)

**Comment by mayonezo** [comment]
I have the same issue. Log file sent via Google Drive.

**Comment by phw198** [comment]
Duplicate #1422.
