### ISSUE TITLE
Problem with Google events

### ISSUE THREAD

**Issue by eknox76** [phw198/OutlookGoogleCalendarSync#1460]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to]([OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8636005/OGcalsync.log)))

**OGCS Version**: v2.9.4.0
**Edition**/ Installed
**Sync Direction**: O<->G

**Bug Description**  
There is something wrong with getting Google Events.  I'm not sure how to explain the problem.

**Steps to Reproduce the Issue**  
Click on Sync. 

**Any other information**  

![Screenshot 2](https://user-images.githubusercontent.com/12851520/167024748-feda96de-3a05-4d93-819a-1b6bb2114534.png)

![Screenshot 1](https://user-images.githubusercontent.com/12851520/167024716-8a3bf6a9-94bf-403d-9e81-fab10c828a48.png)

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8636028/OGcalsync.log)

**Comment by phw198** [comment]
Looks like you're hitting both #1422 and #1432 - [apply the hotfix here](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1432#issuecomment-1107851615).

**Comment by eknox76** [comment]
Thank you!
