### ISSUE TITLE
OGCS Application won't start - no log

### ISSUE THREAD

**Issue by SVNKoch** [phw198/OutlookGoogleCalendarSync#1463]
**OGCS Version**: v2.9.4.6

When I start the application it doesn't open. Watching task manager it dissappears roughly half a second later.
Restarting PC didn't help and renaming my settings file (so it creates a new one) didn't resolve it either.

However there is no update to the log file on level DEBUG. I tried changing it in the settings file to FINE but still no luck.

**Comment by phw198** [comment]
Are you running OGCS from its installed location or as a portable? If it's installed, are you sure you replaced the correct executeable (the one in the `app-2.9.4-alpha` subdirectory)?

You could try invoking OGCS from the command line with explicit settings and log file paths, as [explained in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Running-Multiple-Instances-of-OGCS#start-ogcs-with-command-line-parameters) - see if that helps start logging.

**Comment by SVNKoch** [comment]
yes I'm using the installed app. The update to .6 worked for the last week without problems.

Something I missed above: At Monday I wanted to add a new profile and copy pasted one in the settings file and renamed it.
After that it wasn't booting up anymore. As said, I remvoed the settings file in hope it regenereates one from scratch - but didn't. I also tried adding one without any profiles in it - didn't help either.

Starting using the command line providing locations which didn't have any files in it didn't help either.

**Comment by phw198** [comment]
Very odd. Have you tried downloading the v2.9.4 portable version and just running that? 

Is there anything in the Windows event logs for when the process disappears from Task Manager?

**Comment by SVNKoch** [comment]
yes indeed
Error 100, Application Error
```
Name der fehlerhaften Anwendung: OutlookGoogleCalendarSync.exe, Version: 2.9.4.0, Zeitstempel: 0x5b988f2c
Name des fehlerhaften Moduls: OutlookGoogleCalendarSync.exe, Version: 2.9.4.0, Zeitstempel: 0x5b988f2c
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000e811
ID des fehlerhaften Prozesses: 0x3f08
Startzeit der fehlerhaften Anwendung: 0x01d86b6b56c51e62
Pfad der fehlerhaften Anwendung: C:\Users\user\AppData\Local\OutlookGoogleCalendarSync\OutlookGoogleCalendarSync.exe
Pfad des fehlerhaften Moduls: C:\Users\user\AppData\Local\OutlookGoogleCalendarSync\OutlookGoogleCalendarSync.exe
Berichtskennung: 8b1c7485-155d-4ec5-8734-2863c6bb5bf7
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:
```

Event ID 1000
Task category100
keyword classic

**Comment by SVNKoch** [comment]
from [StackOverflow](https://stackoverflow.com/a/49781951/6846334):
=> 0xc0000409 = STATUS_STACK_BUFFER_OVERRUN
program is writing past the current stack frame, corrupting data on the stack

**Comment by SVNKoch** [comment]
Tried with 2.9.5.0 but ran into #1480. Now tried 2.9.4.14 and reconstructed all my 6 profiles and now it works again 🤷

**Comment by phw198** [comment]
Do you have the settings.xml file that was crashing in v2.9.4, so we can compare it against what you now have with the reconstructed profiles? That might give a clue as to what was causing the problem...
