### ISSUE TITLE
Changed time on appointments are not synced

### ISSUE THREAD

**Issue by janne-blakstad** [phw198/OutlookGoogleCalendarSync#1464]
**OGCS Version**: v2.9.4.0
**Installed or Portable**: Installed

**Problem Description**  
Moved appointments are not updated with new time on sync (Outlook -> Google Calendar).

**Steps to Reproduce the Issue**  
1. Create an appointment in Outlook
2. Sync to Google Calendar
3. Move appointment i Outlook
4. Sync again
5. Appointment stays at original date/time i Google Calendar

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8658888/OGcalsync.log)

Creating appointment:
> 2022-05-10 08:40:25,554 INFO  8 OutlookGoogleCalendarSync.Console [282] -  Matching calendar items...
> 2022-05-10 08:40:25,834 INFO  8 OutlookGoogleCalendarSync.Console [282] -  0 Google calendar entries to be deleted.
> 2022-05-10 08:40:25,834 INFO  8 OutlookGoogleCalendarSync.Console [282] -  1 Google calendar entries to be created.
> 2022-05-10 08:40:25,834 INFO  8 OutlookGoogleCalendarSync.Console [282] -  27 calendar entries to be compared.
> 2022-05-10 08:40:25,885 INFO  8 OutlookGoogleCalendarSync.Console [282] -  Creating 1 Google calendar entries
> 2022-05-10 08:40:26,151 DEBUG  8 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [409] -  Processing >> 11.05.2022 10:00 => "test"
> 2022-05-10 08:40:26,151 DEBUG  8 OutlookGoogleCalendarSync.Console [280] -  11.05.2022 10:00 "test"
> 2022-05-10 08:40:26,244 DEBUG  8 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [337] -  11.05.2022 10:00 => "test"
> 2022-05-10 08:40:26,244 DEBUG  8 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [337] -  outlook_CalendarID=00000000317AC5C23C9E554983C928587A68EA470100FC53C47A062BE241B9F67A68F2E4114500000979C3660000
> 2022-05-10 08:40:26,245 DEBUG  8 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [337] -  outlook_EntryID=00000000317AC5C23C9E554983C928587A68EA470700FC53C47A062BE241B9F67A68F2E4114500000979C3660000B8FA725E657FFA4883522369E399B38D0001DA4EE6290000
> 2022-05-10 08:40:26,245 DEBUG  8 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [337] -  outlook_GlobalApptID=040000008200E00074C5B7101A82E00800000000B0EF67894964D801000000000000000010000000EB082BB377E60E44B5ACF3CD5723BE3E
> 2022-05-10 08:40:26,902 INFO  8 OutlookGoogleCalendarSync.Sync.Engine+Calendar [579] -  Done.

---------------
After moving appointment:
> 2022-05-10 08:40:32,678 INFO  5 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [62] -  Item paste event caught.
> 2022-05-10 08:40:32,681 DEBUG  5 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [69] -  We've got 1 items selected for copy.
> 2022-05-10 08:40:32,685 DEBUG  5 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [78] -  11.05.2022 10:00 => "test"
> 2022-05-10 08:40:32,698 DEBUG  5 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [89] -  This item isn't managed by OGCS.
> 2022-05-10 08:40:34,738 DEBUG  26 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [192] -  Untagging copied Outlook item
> 2022-05-10 08:40:34,748 DEBUG  26 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [199] -  11.05.2022 13:00 => "test"
> 2022-05-10 08:40:34,784 DEBUG  26 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [294] -  Removed locallyCopied property.

**Comment by phw198** [comment]
That all looks as expected for one-way sync. It's a problem with Outlook in that it caches click-and-drag changes too hard - seems to be an arbitrary amount of time before the Outlook API lets OGCS see the new time. 

I've [documented this in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#outlook-click-and-drag-can-suffer-delayed-sync) with suggested workarounds.

Hope that helps.

**Comment by janne-blakstad** [comment]
Thanks. That seems to be the case.

The original issue I had was that when I am an invitee and the organizer changes the time, it didn't seem to update. I had to delete the appointments in Google for the new time to be synced. I have retested it now, and it seems to also just be a delay. It has also happened with an item that had been changed days ago, which is why I thought it was a general issue, but that was probably just a one-off.

**Comment by phw198** [comment]
If that happens again, instead of deleting the Google item, you could try a full sync by pressing `Shift` and clicking `Sync` - just in case the Google event has a newer modified timestamp than the Outlook changed item, which is stopping it syncing.

**Comment by janne-blakstad** [comment]
It happened again today, but it was corrected with a full sync like you suggested.
Not sure what the cause is. A meeting I was invited to got moved from yesterday to today. The change happened yesterday, but it was not moved in Google calendar until I did the full sync today.
