### ISSUE TITLE
Google less secure apps

### ISSUE THREAD

**Issue by raidenlal** [phw198/OutlookGoogleCalendarSync#1465]
https://support.google.com/accounts/answer/6010255?hl=en

_To help keep your account secure, starting May 30, 2022, ​​Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password._

Will this have any impact on OGCS?

**Comment by phw198** [comment]
No, OGCS doesn't use basic authentication and is a secure app (using OAuth2) as defined by:

> When a third-party app meets our security standards, you can:
> - See what level of account access you’re giving the app before you connect your Google Account
> - Let the app access only a relevant part of your Google Account, like your email or calendar
> - Connect your Google Account to the app without exposing your password
> - Disconnect your Google Account from the app at any time

**Comment by raidenlal** [comment]
Thanks for the clarification.
