### ISSUE TITLE
Outlook 2013 - Occasionally Hung

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#147]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/655975" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/alvinezz" target="_blank">alvinezz</a></strong> wrote at 2016-06-29 11:13:</p><div class="markDownOutput ">I used to use Outlook 2010 and this sync tool worked flawlessly. <br>
<br>
Since using Outlook 2013, it seems that if I enable 2-way sync between Outlook and Gmail, every time the sync happens, when the sync tries to read the Outlook Calendar, the Outlook will hang / freeze for about 30 - 60 seconds, and then says the sync failed.
<br>
If I retry to resync / continue with sync, then it usually will be successful. But still rather annoying.
<br>
<br>
During the freeze, there is a tooltip on the Outlook on the system tray saying that it is trying to get info from the Exchange server (something like that).
<br>
<br>
Any ideas why? Is this a known issue? Any work around? <br>
<br>
Thanks<br>
</div></div>

**Comment by phw198** [comment]
I would imagine this is something to do with how your connection to Exchange is configured in 2013 - sounds like maybe you don't have caching turned on and when OGCS wants to sync it's triggering Outlook to sync with Exchange first.

**Comment by wasuaje** [comment]
I'm having this very issue now, any fix?

![image](https://user-images.githubusercontent.com/4673741/105369007-df2cf700-5be0-11eb-8f56-a7f2b82651a7.png)

**Comment by phw198** [comment]
Same as previous suggestion - [turn on caching](https://www.google.com/url?sa=t&source=web&rct=j&url=https://support.microsoft.com/en-us/office/turn-on-cached-exchange-mode-7885af08-9a60-4ec3-850a-e221c1ed0c1c&ved=2ahUKEwj-39SVm7TuAhUPfMAKHdaeB7wQFjAFegQIAhAE&usg=AOvVaw2fr2V5FwsWDAvEBrY4sWN8) in your Outlook account configuration.
