### ISSUE TITLE
Problem at Outlook Google Kalender Sync

### ISSUE THREAD

**Issue by Hermann47** [phw198/OutlookGoogleCalendarSync#1476]
Every time Outlook Google Kalender Sync has executed his job, I get the following message:

Sync version: 2.9.4.0

Sync started at 13.05.2022 10:39:51

Outlook ↔ Google
Finding Calendar Entries
Scanning Outlook calendar...

35 Outlook calendar entries found.

Scanning Google calendar...
87 Google calendar entries found.
20 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...
Outlook 35, Google 88

Syncing Outlook → Google
Matching calendar items...
57 Google calendar entries to be deleted.
0 Google calendar entries to be created.
31 calendar entries to be compared.
Deleting 57 Google calendar entries
...
Comparing 31 existing Google calendar entries
10 entries updated.

Syncing Outlook ← Google
4 Outlook calendar entries to be deleted.
0 Outlook calendar entries to be created.
31 calendar entries to be compared.

Deleting 4 Outlook calendar entries
Comparing 31 existing Outlook calendar entries

**Sie haben ein Element dieser Serie geändert, und diese Instanz ist nicht mehr vorhanden. Schließen Sie alle geöffneten Elemente, und versuchen Sie es erneut.
If this keeps happening, please restart OGCS.**
1 entries updated.
Sync finished!
![grafik](https://user-images.githubusercontent.com/90775740/168246438-20af8aef-d062-4ea2-8ecc-30f69bd8095a.png)
**A simple restart does not help.**
My question : If I deinstall OGSyncronizer and install it new, **I fear to lost all my calender terms in Outlook 2010**

Is this right or is no danger to lose all my terms ???

**Comment by phw198** [comment]
Apply the fix on #1432 (or wait until I release the next alpha, hopefully in the next couple of days).

And no, re-installing OGCS won't lose any calendar items - but you don't need to uninstall.
