### ISSUE TITLE
'All Day' Outlook events not syncing to Google Calendar

### ISSUE THREAD

**Issue by clangstaffnhts** [phw198/OutlookGoogleCalendarSync#1477]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0.0 
**Edition**: Installed
**Sync Direction**: O->G 

**Bug Description**  
When syncing the calendar no errors appear but any 'All day' Outlook events are not synced to Google.

**Steps to Reproduce the Issue**  
1. Create 'All day' event on Outlook
2. Click 'Start Sync' running Outlook events to Google
3. Event is not created in Google calendar

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by clangstaffnhts** [comment]
Hi Paul,

When I upgrade the OGCS and have the 'Check for Alpha releases' option ticked the latest version picked up and available is v2.9.4 not v2.9.5. Is this correct?

Thanks,
Chris

North Huddersfield Trust School



Tel: 01484 452100 Ext 240


---------------------------------

________________________________

**Comment by phw198** [comment]
I've now mentioned this in the Upgrading wiki section - yes, it's expected if the new version has only just been released and is still being rolled out. However, you can download the setup file manually if you wish to upgrade earlier - [see the wiki for more detail](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading).
