### ISSUE TITLE
2.9.5 has many issues with Norton/Symantec 360

### ISSUE THREAD

**Issue by tnjgb** [phw198/OutlookGoogleCalendarSync#1478]
Norton 360 does not like 2.9.5, firstly it sees the downloaded installation file as dangerous, then after overriding that it blocks the install process saying "Data Protector blocked a suspicious action by OGCS_Setup.exe" with "Suspicious Process attempted deleting a file protected by Data Protector (...app-2.9.4-alpha\Console\emoji\clock1.png".

After overriding Norton it finally states that the OGCS webpage is dangerous - https://safeweb.norton.com/report/show?url=http://www.outlookgooglecalendarsync.com/release-notes.html&ulang=en 

I assume that this is mainly a Norton issue but it is odd that this has only started with this version.

**Comment by phw198** [comment]
Sounds like Norton has taken exception to the Squirrel installer mechanism (as that's what would be removing the `clock1.png` file when upgrading. Giving this installer was endorsed by Microsoft and is open source, it's particularly dumb of Norton...but that doesn't surprise me!

Note, nothing has changed with OGCS in this respect between v2.9.4 and v2.9.5 - I suspect this is new behaviour from Norton and would happen for all recent releases. 

If you haven't done so already, can I kindly ask you [submit a report to Norton](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#anti-virus-false-positives)?

**Comment by phw198** [comment]
The webpage now looks like it's being reported OK?

![image](https://user-images.githubusercontent.com/11843015/169651919-d39cefe1-9146-4e95-8fe4-5cd7f7299546.png)

**Comment by tnjgb** [comment]
Yes its fine now.
