### ISSUE TITLE
Error "Event failed"

### ISSUE THREAD

**Issue by Amerston** [phw198/OutlookGoogleCalendarSync#1479]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
Error on sync with v2.9.4.0 

Sync version: 2.9.4.0

Profile: Default

Sync started at 16/05/2022 09:18:00

Syncing from 17/03/2022 to 25/08/2022

Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...

45 Outlook calendar entries found.

Scanning Google calendar...

44 Google calendar entries found.

Total inc. recurring items spanning sync date range...
Outlook 45, Google 44
Checking for orphaned Google items

Syncing Outlook → Google
Matching calendar items...

0 Google calendar entries to be deleted.

1 Google calendar entries to be created.

44 calendar entries to be compared.

Creating 1 Google calendar entries
25/05/2022 12:00  "BRG Fairfield"

Comparing 44 existing Google calendar entries

Event update failed.
Object reference not set to an instance of an object.

Event update failed.
Object reference not set to an instance of an object.

Event update failed.
Object reference not set to an instance of an object.

Event update failed.
Object reference not set to an instance of an object.

Event update failed.
Object reference not set to an instance of an object.

Event update failed.
Object reference not set to an instance of an object.

Event update failed.
Object reference not set to an instance of an object.

Event update failed.
Object reference not set to an instance of an object.

Event update failed.
Object reference not set to an instance of an object.
0 entries updated.

Syncing Outlook ← Google
Matching calendar items...

0 Outlook calendar entries to be deleted.

0 Outlook calendar entries to be created.

44 calendar entries to be compared.

Comparing 44 existing Outlook calendar entries
0 entries updated.

Sync finished!
**Steps to Reproduce the Issue**  
1. Go to...
[Doc1.docx](https://github.com/phw198/OutlookGoogleCalendarSync/files/8699842/Doc1.docx)

1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Duplicate #1422

**Comment by Amerston** [comment]
Problem resolved with fix
