### ISSUE TITLE
Error: unhandled exception in application when switching profile

### ISSUE THREAD

**Issue by Kimble89** [phw198/OutlookGoogleCalendarSync#1480]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5  
**Edition**: Installed
**Sync Direction**: G->O / O<->G

**Bug Description**  
When i switch the profiles OGCS will show this error message:
![grafik](https://user-images.githubusercontent.com/57529094/168915210-455f5903-c88a-419c-ba8c-c8cda74436a8.png)
I copied the "details" log into a textfile

**Steps to Reproduce the Issue**  
Create 2 profiles and try to switch them.
Also with a new installation i got the same error

[OGCS_Error.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/8711742/OGCS_Error.txt)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8711758/OGcalsync.log)

**Comment by SVNKoch** [comment]
can confirm. This happens with old settings files when switching profiles and with new settings files when creating a second profile. Here is the complete error details for when creating a new profile:
[crash_new_profile.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/8728547/crash_new_profile.txt)

You however seem to be able to simply continue the program. However the settings page doesn't update properly. (I noticed it for the Sync Options > "Set color/category to" field)

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.9.5.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8747554/v2.9.5.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by Kimble89** [comment]
Hi,
yes i can confirm it is working now.
Thank you for your help :)

Greetings Kimble
