### ISSUE TITLE
Multiple Calendar Sync

### ISSUE THREAD

**Issue by SailingNut** [phw198/OutlookGoogleCalendarSync#1482]
I would like the ability to sync multiple Google calendars with Outlook (my use case is only Google to Outlook sync) and apply different color categories to each Google calendar that is synced.

**Comment by phw198** [comment]
Ok, but if you're running the latest alpha release, how is OGCS not catering for that already?

**Comment by SailingNut** [comment]
The critical detail I left out is that I'd like this for the auto sync. As far as I can discover there isn't a way to select multiple Google calendars. But I could easily be wrong on that!

**Comment by phw198** [comment]
As long as you're on the latest alpha, then set up a Profile for each calendar you want to sync and set the schedule to auto sync on each.

**Comment by SailingNut** [comment]
I COMPLETELY missed the profile setup! Thanks!
