### ISSUE TITLE
Unhandled exception creating new profile

### ISSUE THREAD

**Issue by SailingNut** [phw198/OutlookGoogleCalendarSync#1483]
**OGCS Version**: v2.9.5 Alpha
**Edition**: Installed
**Sync Direction**: G->O

**Bug Description**  
I attempted to create a profile in addition to the default and an unhandled exception occurred. (Exception detail pasted below.) I selected "Continue" then I noticed that there 2 copies of the profile I tried to create shown in the dropdown in addition to the Default profile. Now when I launch the program and attempt to look at one of the added profiles it crashes with an unhandled exception. (Second exception pasted below.)

**Steps to Reproduce the Issue**  

1. Click on "Add profile"
2. Enter name of new profile in the dialog
3. Click on "Add"
4. Unhandled exception
5. Re-Launch Application
6. Show application
7. Click settings
8. Select non-default profile from dropdown
9. Unhandled exception

**Any other information**  

**Exception encountered when creating profile**

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
```
************** Exception Text **************
System.ArgumentException: Items collection cannot be modified when the DataSource property is set.
   at System.Windows.Forms.ComboBox.CheckNoDataSource()
   at System.Windows.Forms.ComboBox.ObjectCollection.Clear()
   at OutlookGoogleCalendarSync.Forms.Main.UpdateGUIsettings_Profile() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 480
   at OutlookGoogleCalendarSync.SettingsStore.Calendar.SetActive() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\SettingsStore\Calendar.cs:line 207
   at OutlookGoogleCalendarSync.Forms.Main.ddProfile_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1073
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at OutlookGoogleCalendarSync.Forms.ProfileManage.ProfileManage_FormClosing(Object sender, FormClosingEventArgs e) in C:\Users\Paul
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8740129/OGcalsync.log)
\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\ProfileManage.cs:line 60
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

<details><summary>Detail</summary>

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4510.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookGoogleCalendarSync
    Assembly Version: 2.9.8170.39370
    Win32 Version: 2.9.5.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/OutlookGoogleCalendarSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
log4net
    Assembly Version: 2.0.12.0
    Win32 Version: 2.0.12.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Squirrel
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.1
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Splat.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Google.Cloud.Logging.Log4Net
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.Log4Net.DLL
----------------------------------------
Google.Cloud.Logging.V2
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.V2.DLL
----------------------------------------
Google.Protobuf
    Assembly Version: 3.17.3.0
    Win32 Version: 3.17.3.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Protobuf.DLL
----------------------------------------
Google.Cloud.Logging.Type
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.Type.DLL
----------------------------------------
Google.Api.Gax
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.Gax.DLL
----------------------------------------
Google.Api.CommonProtos
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.CommonProtos.DLL
----------------------------------------
Google.Api.Gax.Grpc
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.Gax.Grpc.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.54.0.0
    Win32 Version: 1.54.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.54.0.0
    Win32 Version: 1.54.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.Core.DLL
----------------------------------------
Grpc.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.1.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Core.DLL
----------------------------------------
Grpc.Core.Api
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Core.Api.DLL
----------------------------------------
Grpc.Auth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/NuGet.Squirrel.DLL
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
NodaTime
    Assembly Version: 2.4.13.0
    Win32 Version: 2.4.13.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/NodaTime.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4569.1507
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4613.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4510.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
Google.Apis.Calendar.v3
    Assembly Version: 1.54.0.2410
    Win32 Version: 1.54.0.2410
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.Calendar.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.54.0.0
    Win32 Version: 1.54.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.DLL
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Google.Cloud.DevTools.Common
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.DevTools.Common.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/System.Memory.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box

**Exception when viewing profile**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Items collection cannot be modified when the DataSource property is set.
   at System.Windows.Forms.ComboBox.CheckNoDataSource()
   at System.Windows.Forms.ComboBox.ObjectCollection.Clear()
   at OutlookGoogleCalendarSync.Forms.Main.UpdateGUIsettings_Profile() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 480
   at OutlookGoogleCalendarSync.SettingsStore.Calendar.SetActive() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\SettingsStore\Calendar.cs:line 207
   at OutlookGoogleCalendarSync.Forms.Main.ddProfile_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1073
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4510.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookGoogleCalendarSync
    Assembly Version: 2.9.8170.39370
    Win32 Version: 2.9.5.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/OutlookGoogleCalendarSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
log4net
    Assembly Version: 2.0.12.0
    Win32 Version: 2.0.12.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Squirrel
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.1
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Splat.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Google.Cloud.Logging.Log4Net
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.Log4Net.DLL
----------------------------------------
Google.Cloud.Logging.V2
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.V2.DLL
----------------------------------------
Google.Protobuf
    Assembly Version: 3.17.3.0
    Win32 Version: 3.17.3.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Protobuf.DLL
----------------------------------------
Google.Cloud.Logging.Type
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.Type.DLL
----------------------------------------
Google.Api.Gax
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.Gax.DLL
----------------------------------------
Google.Api.CommonProtos
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.CommonProtos.DLL
----------------------------------------
Google.Api.Gax.Grpc
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.Gax.Grpc.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.54.0.0
    Win32 Version: 1.54.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.54.0.0
    Win32 Version: 1.54.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.Core.DLL
----------------------------------------
Grpc.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.1.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Core.DLL
----------------------------------------
Grpc.Core.Api
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Core.Api.DLL
----------------------------------------
Grpc.Auth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/NuGet.Squirrel.DLL
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
NodaTime
    Assembly Version: 2.4.13.0
    Win32 Version: 2.4.13.0
    CodeBase: file:///C:/Users/tim/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/NodaTime.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4569.1507
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4613.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4510.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
</details>

**Comment by phw198** [comment]
Thanks for reporting this @SailingNut. However, it was also reported on #1480 which I've just posted a hotfix for, if you'd like to try that.

**Comment by SailingNut** [comment]
I attempted to get the latest Alpha with this fix but have been unsuccessful. OGCS reports that there are no new versions. I looked for a pre-compiled version to just copy over my existing files and could not find that. I then cloned the issue branch and tried to build it with VS 2022 and that failed.

Do you have a timeframe for when this will be on the main branch so that I can upgrade?

**Comment by phw198** [comment]
The comment with the hotfix and instructions [is here](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1480#issuecomment-1133608984) (you just extract the hotfix over the top of your existing installation). 

New alpha releases are every 6 weeks or so, though I don't have a date in mind for the next yet.
