### ISSUE TITLE
Google Handshake failed

### ISSUE THREAD

**Issue by Schommes** [phw198/OutlookGoogleCalendarSync#1484]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.3.4
**Edition**: Installed 
**Sync Direction**: O->G 

**Bug Description**  
![grafik](https://user-images.githubusercontent.com/43887179/169644902-a6d77ccc-f204-4527-b3cb-f2da6b269544.png)

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8747316/OGcalsync.log.zip)

**Comment by phw198** [comment]
It doesn't look like your proxy is allowing OGCS to talk to the internet - even the update checker to GitHub is failing :slightly_frowning_face:

**Comment by Schommes** [comment]
Thanks for pointing me in the right direction. Norton 360 was the culprit. Upto now the Firewall never interfered with OGCS. But now all of a sudden it was blocked. After changing it to access everything works fine again. Thanks again. This can be closed.
