### ISSUE TITLE
I want to have the SAME CATEGORY COLORS in OGCS as used in OUTLOOK 2010

### ISSUE THREAD

**Issue by Hermann47** [phw198/OutlookGoogleCalendarSync#1485]
2.9.5.0
version number.

If I syncronize my outlook calendar with OGCS , The terms **on my Smartphone calendar** are NOT the same colors as I have specified in Outlook. The terms in my Smartphone calendar ar always **only blue**
**How can I define generally, that OGCS forced to use the same color as in Outlook specified ??**
![grafik](https://user-images.githubusercontent.com/90775740/169813722-a9588209-eb4c-492c-9fd9-e8307716bc4f.png)

Thanks for helping me.

**Comment by phw198** [comment]
It could well depend on the smartphone app you are using. It would be better to check the [Google webapp](https://calendar.google.com/calendar/u/0/r/week) directly to see what is showing there - if that's correct, then you know the problem is with the phone app and not OGCS.

**Comment by Hermann47** [comment]
I habe changed my calendar synchronizing completly. It is very awful to be 
forced to control every single term whether to delete or not. I have more 
then 30 positions to control about that. This is NOT prakticable !!! I now 
back to caldav synchronizer in collaboration with davx5. It works without 
that unknowable questions "delete or not "
but it makes calendar synchronizing exactly 1:1.




Gesendet mit der Telekom Mail App



--- Original-Nachricht ---
Von: Paul Woolcock
Betreff: Re: [phw198/OutlookGoogleCalendarSync] I want to have the SAME 
CATEGORY COLORS in OGCS as used in OUTLOOK 2010 (Issue #1485)
Datum: 29. Mai 2022, 14:11
An: phw198/OutlookGoogleCalendarSync
Cc: Hermann47, Author


It could well depend on the smartphone app you are using. It would be 
better to check the Google webapp directly to see what is showing there - 
if that's correct, then you know the problem is with the phone app and not 
OGCS.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: 
***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", 
"potentialAction": { ***@***.***": "ViewAction", "target": 
"https://github.com/phw198/OutlookGoogleCalendarSync/issues/1485#issuecomment-1140436303", 
"url": 
"https://github.com/phw198/OutlookGoogleCalendarSync/issues/1485#issuecomment-1140436303", 
"name": "View Issue" }, "description": "View this Issue on GitHub", 
"publisher": { ***@***.***": "Organization", "name": "GitHub", "url": 
"https://github.com" } } ]

**Comment by phw198** [comment]
Clearly you didn't have OGCS configured correctly, but never mind, glad you have found a solution.

**Comment by Hermann47** [comment]
I don't think so whether I have tested both posssibilitys:
1. confirm deletion (more then 30 clicks necessary)
or
2. do not confirm. (= deleting all my terms, also the terms I need!!)




Gesendet mit der Telekom Mail App



--- Original-Nachricht ---
Von: Paul Woolcock
Betreff: Re: [phw198/OutlookGoogleCalendarSync] I want to have the SAME 
CATEGORY COLORS in OGCS as used in OUTLOOK 2010 (Issue #1485)
Datum: 29. Mai 2022, 14:50
An: phw198/OutlookGoogleCalendarSync
Cc: Hermann47, Author


Clearly you didn't have OGCS configured correctly, but never mind, glad you 
have found a solution.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: 
***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", 
"potentialAction": { ***@***.***": "ViewAction", "target": 
"https://github.com/phw198/OutlookGoogleCalendarSync/issues/1485#issuecomment-1140442975", 
"url": 
"https://github.com/phw198/OutlookGoogleCalendarSync/issues/1485#issuecomment-1140442975", 
"name": "View Issue" }, "description": "View this Issue on GitHub", 
"publisher": { ***@***.***": "Organization", "name": "GitHub", "url": 
"https://github.com" } } ]

**Comment by phw198** [comment]
Sounds like you had pre-existing items in the destination calendar, so for one way sync just turn on "merge items".
