### ISSUE TITLE
[OAUTH] - Google throws an Unknown Error while logging in

### ISSUE THREAD

**Issue by Yoanndp** [phw198/OutlookGoogleCalendarSync#1491]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0  
**Edition**:  Portable  
**Sync Direction**: O->G

**Bug Description**  
I can't sign in to my Google account through the application. It redirects me to the Google authentication form, then I click "Allow" and finally it redirects me to https://accounts.google.com/info/unknownerror.

**Steps to Reproduce the Issue**  
1. Open OGCS
2. Go to "Settings" tab
3. Go to "Google" sub-tab
4. Hit "Retrieve Calendar"
(The browser will open by itself)
5. Select a Google account
6. Hit "Allow"
7. You will get the following error message: "An error has occurred! Sorry, an error occurred. Please try again."

:paperclip: [OGcalsync.log](https://pastebin.com/NRExkD3q)

**Comment by phw198** [comment]
Hi @Yoanndp have you used previous versions of OGCS successfully? I note that it also fails to check if there is a new version of the timezone data, with a 401 Unauthorised error - there'll be no authentication for this, so maybe your proxy is getting in the way?

I wonder if [this might be relevant](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#page-cannot-be-displayed-after-authorising-ogcs-to-access-my-calendar) to you also?

**Comment by Yoanndp** [comment]
> Hi @Yoanndp have you used previous versions of OGCS successfully? I note that it also fails to check if there is a new version of the timezone data, with a 401 Unauthorised error - there'll be no authentication for this, so maybe your proxy is getting in the way?
> 
> I wonder if [this might be relevant](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#page-cannot-be-displayed-after-authorising-ogcs-to-access-my-calendar) to you also?
> 
> 

Hello, yes I was using version 2.9.0 successfully and it suddenly stopped to work. I don't know about the proxy, but it'd work as it was working before

**Comment by Yoanndp** [comment]
Alright, [this link](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#page-cannot-be-displayed-after-authorising-ogcs-to-access-my-calendar) definitely fixed my problem ! Thank you
