### ISSUE TITLE
[Multiple Calendars] Outlook <--> Google Multiple Calendar Sync

### ISSUE THREAD

**Issue by 10bn** [phw198/OutlookGoogleCalendarSync#1493]
**Is your feature request related to a problem? Please describe.**

At work we have a separate calendar for vacation scheduling. I'd appreciate if I could sync that to a separate work holyday google calendar.  

**Describe the solution you'd like**

The ability to synchronize multiple calendars independently. Just as if you could run the program multiple times.

**Comment by jaddel** [comment]
Is your feature request related to a problem? Please describe:

At work we have a separate calendar for vacation scheduling. I'd appreciate if I could sync that to a separate work holyday google calendar.  

Describe the solution you'd like:

The ability to synchronize multiple calendars independently. Just as if you could run the program multiple times.

**Comment by euinor** [comment]
I'm surprised this hasn't come up more often - it would be great to select multiple outlook calendars and sync them to multiple google calendars.

Is there a current workaround for this? Run two instances of the application?

Edit: It has come up before and the feature is already in the alpha version of the app :)

**Comment by 10bn** [comment]
> 

great to hear it has already been picked up. Thx for letting me know!

**Comment by devdems** [comment]
> I'm surprised this hasn't come up more often - it would be great to select multiple outlook calendars and sync them to multiple google calendars.
> 
> Is there a current workaround for this? Run two instances of the application?
> 
> Edit: It has come up before and the feature is already in the alpha version of the app :)

I have Alpha 2.9.5.0 and can't see this option. Do you have any more details?

**Comment by phw198** [comment]
Yep, simplest is to upgrade to the latest alpha release :slightly_smiling_face: 

https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars
