### ISSUE TITLE
Multi account synchronization

### ISSUE THREAD

**Issue by Badaw97** [phw198/OutlookGoogleCalendarSync#1495]
Hello,
Can we synchronize several profiles I have error messages?
Thank you for your help.
![Capture d’écran 2022-06-08 141611](https://user-images.githubusercontent.com/107118678/172613953-055d123a-61fb-4009-b1ab-fc4ae3859e45.png)

**Comment by madejackson** [comment]
I have the same issue when changing profiles on 2.9.5, had to revert back to 2.9.4

**Comment by phw198** [comment]
Duplicate of #1480 which has a hotfix posted.
