### ISSUE TITLE
My google calendar is not syncing in the initial setting

### ISSUE THREAD

**Issue by world0726** [phw198/OutlookGoogleCalendarSync#1496]
Checklist:-

- [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) latest release
- [x] Reproduce the issue
- [x] Complete the information below
- [x] Provide your OGcalsync.log file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

OGCS Version: v2.9.5.0
Edition: Installed
Sync Direction: G<->O

I installed the OGCS on my work computer and ran into trouble with google calendar sync up. 

I entered my google login information and agreed on the sync for OGCS, but it's giving me this error message.

" Your Google authorization token needs updating. the process to reauthorize to your Google account will now begin. "

and I don't find my google calendar synced in OGCS setting. 

what should I do? 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8864120/OGcalsync.log)

**Comment by phw198** [comment]
Looks like OGCS is being blocked from talking to the internet - seems to think you're on Windows 7, but I'm guessing this isn't correct.

Go to Settings > Application Behaviour > Proxy. Set it to custom, then click the "Check" button next to Browser Agent. Copy the string from the webpage that pops up back into OGCS, revert proxy to what it was before (IE?), click Save and then retry syncing.

**Comment by phw198** [comment]
:package: I've now also updated the browser agent with this [v2.9.5.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/9174641/v2.9.5.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes if you use the hotfix.

**Comment by world0726** [comment]
> Looks like OGCS is being blocked from talking to the internet - seems to think you're on Windows 7, but I'm guessing this isn't correct.
> 
> Go to Settings > Application Behaviour > Proxy. Set it to custom, then click the "Check" button next to Browser Agent. Copy the string from the webpage that pops up back into OGCS, revert proxy to what it was before (IE?), click Save and then retry syncing.

Which setting ? from Google calendar?  or Window? Please advise specifically.

**Comment by phw198** [comment]
OGCS
