### ISSUE TITLE
How do you transfer settings from old version to new?

### ISSUE THREAD

**Issue by JP3251** [phw198/OutlookGoogleCalendarSync#1497]
**OGCS Version**: v2.9.4.0.
**Installed or Portable**: Portable

When I upgrade I have to re-configure the settings.  Is there a way to transfer them?

**Comment by SVNKoch** [comment]
Since you're using the portable version you have to copy the settings file yourself.
Open the old version, go to the about tab and double click the path nerxt to "config in". Do the same for the new version.
Copy the settings.xml file from the old location to the new one.

**Comment by phw198** [comment]
[Section in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading#maintaining--backing-up-configuration-settings) improved to cover this better.
