### ISSUE TITLE
Add label to Subject

### ISSUE THREAD

**Issue by devdems** [phw198/OutlookGoogleCalendarSync#1500]
Add an option per sync profile to be able to append a label to the meeting "Subject" field on the destination calendar.

**Comment by SVNKoch** [comment]
you should be able to do that using the word obfuscation:
See [example](https://regex101.com/r/PapuLD/1): Use "$" gets replaced with " [Marker]" or whatever you want to append.
(If you want to prefix instead use "^" instead of "$")
