### ISSUE TITLE
Sync feature request: exclude all day events from sync

### ISSUE THREAD

**Issue by rmdodhia** [phw198/OutlookGoogleCalendarSync#1501]
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
I sync from outlook to google, but I have a ton of all day events that I'd like to exclude from appearing in google. Is there an existing way to do that? Or can it be included as an option?

**Steps to Reproduce the Issue**  

**Any other information**

**Comment by phw198** [comment]
Duplicate of #104
