### ISSUE TITLE
v2.9.5: System.NullReferenceException on Google Event update

### ISSUE THREAD

**Issue by ralfeus** [phw198/OutlookGoogleCalendarSync#1507]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
For some meetings, most likely recurring ones with exceptions following error occurs:
> Updated event failed to save.
> Object reference not set to an instance of an object.

First occurrence of the error is in the log file line 1389.

**Steps to Reproduce the Issue**  
I'm not sure how to reproduce the issue but for me it happens every synchronization.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9119744/OGcalsync.log)

**Comment by phw198** [comment]
:package: Please try with [v2.9.5.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/9334287/v2.9.5.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes.
