### ISSUE TITLE
Error on Profile selection and wrong sync

### ISSUE THREAD

**Issue by Malli88** [phw198/OutlookGoogleCalendarSync#1508]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0  
**Edition**: Installed
**Sync Direction**: G->O / O->G / O<->G --- any

**Bug Description**  
Synchronization is going crazy and syncing any calendar with each other. :-(
Error on Profile selection: 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9130790/OGcalsync.log)

![image](https://user-images.githubusercontent.com/7073723/179481518-52133edc-1d3a-4f74-bbc2-ac2f8cd97d48.png)

**Steps to Reproduce the Issue**  
Go to Profiles
Select a Profile

**Any other information**  
Log attached

**Comment by Malli88** [comment]
Is there something I can do to support the issue?

**Comment by phw198** [comment]
I think this is fixed with #1480.

**Comment by Malli88** [comment]
@phw198 How can Install it? I'm on Alpha Stream but the application tells me that I'm on the latest version with 2.9.5.

**Comment by Malli88** [comment]
Could you share the release, please? @phw198

**Comment by phw198** [comment]
The install instructions are [linked next to the hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1480#issuecomment-1133608984).

**Comment by Malli88** [comment]
Thanks
