### ISSUE TITLE
120 minute schedule

### ISSUE THREAD

**Issue by doylejg** [phw198/OutlookGoogleCalendarSync#1509]
**Are you already using OGCS?**
v2.9.0

**Describe the question you have**
I can only set the sync frequency to a minimum of 120 minutes. Is this a paywall, bug, or constraint? I couldn't find any information on it, but quite possibly missed it. (Pretty sure I used to have it set to 5 minutes)

**Comment by jk11235** [comment]
Me too: used to have it set more frequently; now cannot. Did you never get an answer? Strange

**Comment by jk11235** [comment]
Figured this out: 

> As per the [User Guide](https://phw198.github.io/OutlookGoogleCalendarSync/guide/syncoptions#when), scheduled syncs are restricted to a maximum frequency of 15 minutes, or 120 minutes if Push Sync is also enabled.`

So unselecting push allows 15 minute intervals.

**Comment by doylejg** [comment]
oh interesting. thanks!

still seems almost too infrequent to be very useful for me.

**Comment by phw198** [comment]
@doylejg What's the use case for neither Push Sync nor 15 minute delta syncs being frequent enough?

**Comment by doylejg** [comment]
I want my outlook calendar pushed to my Google calendar every minute so i can still live my life in the Google ecosystem (notifications and such) while IT locks me into the office 365 mess. 

e.g. Google is properly integrated with toggle (i can't integrate MS365), so i add things to my outlook calendar and then have to wait for my home machine to sync for me to do my toggle task. 

Since the task is done in a personal computer and not an external server, it was surprising to me that i didn't have finer control over the frequency.

**Comment by phw198** [comment]
Still don't see why Push Sync doesn't suffice - you make a change in Outlook, OGCS should detect the change within 2 minutes and syncs it to Google. Or are you not seeing that happen?

**Comment by doylejg** [comment]
hmm okay so I'm not getting something or i have a bag configuration. I'll
investigate further and report back. (pebcak?)

thanks

**Comment by doylejg** [comment]
Okay I think the Push Sync is working, I just didn't understand what was happening. 

Thanks again.
