### ISSUE TITLE
Sync stuck at "creating google calendar entries"

### ISSUE THREAD

**Issue by hirnheiner4711** [phw198/OutlookGoogleCalendarSync#1516]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0  
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
Sync proceeds very well and fast  until "creating 11 Google calendar entries", then lists the first entry and that was it - nothing happens any more.

**Steps to Reproduce the Issue**  
see above

**Any other information**  
Any additional information that may help troubleshoot the issue.

**Comment by sansnil** [comment]
Hi @hirnheiner4711 - I'm curious: is the Outlook client running in cached or non-cached mode?

**Comment by phw198** [comment]
Very odd - could you increase the logging level to `FINE`, retry the sync and upload your logfile again?

@sansnil Shows running as `olCachedConnectedFull` - but given it's already retrieved the Outlook items, compared them and knows there are Google items to create, the cached mode is not relevant here.

**Comment by hirnheiner4711** [comment]
Issue can be closed - out of a sudden it worked. Probably I didn't wait long enough for the items to be created.
During first run till the end I got the known "precondition failed [412] error" [https://github.com/phw198/OutlookGoogleCalendarSync/issues/528](url) - updating to v2.9.5.7 fixed it and so I'm a satisfied user :-D

**Comment by sansnil** [comment]
Hi Paul,


Thanks very much for taking a look into this. I've attached a clean log with the 'Fine' option enabled which I hope will help. I could well be wrong but it looks like it gets slow when it's syncing attendee responses information.


Stuart


________________________________

**Comment by phw198** [comment]
@sansnil My request for the FINE logs was really to @hirnheiner4711 but their issue is now resolved. I'll take a look over on #1527 for yours...
