### ISSUE TITLE
Bilateral Sync -  Google-to-Outlook Word Obfuscation

### ISSUE THREAD

**Issue by kamwatang** [phw198/OutlookGoogleCalendarSync#1517]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
Google-to-Outlook Word Obfuscation does not work.  I have a O<>G sync  with a G > O obfuscation rule that should look for any string and replace it with "Private", but new entries in Google calendar create a new entry in Outlook with the exact same subject line

**Steps to Reproduce the Issue**  
1. Go to Sync Options
1. In the How section, ensure Direction drop-down is set to Outlook <-> Google and that Word Obfuscation is checked
2. In the Word Obfuscation Rules section, ensure Obfuscate From drop-down is set to Outlook <- Google, And in the Rules Table, Find is  ^.*$ and Replace is Private
3. Save
4. Create a google calendar entry with a subject line
5. Either manually trigger sync or allow scheduled sync
6. Check Outlook for the synced entry

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/9244925/OGcalsync.zip)

**Comment by phw198** [comment]
In your "Find" rule, it looks like you have a white space before the `^` character - try removing that.

**Comment by kamwatang** [comment]
Thanks, @phw198. That was totally the reason.  Sorry I didn't spot that.
