### ISSUE TITLE
sync the update from outside outlook

### ISSUE THREAD

**Issue by nonleaf** [phw198/OutlookGoogleCalendarSync#1519]
**Are you already using OGCS?**
2.9.5

**Describe the question you have**
I'm trying to use it to sync calendar between Outlook (connected with an Exchange ActiveSync server) and google calendar.

Everything works well when I edit calendar within outlook. however when using other client to edit/update an existing event in Exchange ActiveSync server (e.g. event name, time, etc.), I can see the event changed in outlook but OGCS cannot "see" the change - saying "0 entries updated".

**Comment by phw198** [comment]
That's odd - OGCS is looking at the last modified timestamp to determine what's changed since the last sync. Are you sure the server change has synced to your local Outlook client before you run OGCS sync? Is Outlook in cached mode?

If you do a full sync by pressing `Shift` and clicking Sync, does it then see the change?

**Comment by nonleaf** [comment]
> That's odd - OGCS is looking at the last modified timestamp to determine what's changed since the last sync. Are you sure the server change has synced to your local Outlook client before you run OGCS sync? Is Outlook in cached mode?
> 
> If you do a full sync by pressing `Shift` and clicking Sync, does it then see the change?

yes, I clicked sync after I saw the change in outlook GUI. How can I check the "cached mode"?

I tested, full sync can see the change but normal sync cannot.

**Comment by phw198** [comment]
[Cached mode instructions](https://support.microsoft.com/en-us/office/turn-on-cached-exchange-mode-7885af08-9a60-4ec3-850a-e221c1ed0c1c), though I'm not sure that will make any difference.

It sounds like the other client is buggy, and it should be updating the last modified timestamp on the edited item, but it isn't :slightly_frowning_face: If you change your calendar view to "List" and then show the "Modified" column, is the date/time what you would expect?

Worth double [checking your date format](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) is accurately retrieving your Outlook items too.

**Comment by nonleaf** [comment]
1. The server is Exchange ActiveSync. I checked, there is no "cached mode" option in outlook settings. I guess ActiveSync it is not a full version Exchange server.

2. yes!!!  the last modified time is not updated (I can see this column in "List" view). so it should be the client's bug? I also tried another client (iOS native calendar), still not updated.

3. In Settings > Outlook > Regional Date Formats (format "g"), I clicked the test button and it returned 11 items.  It sounds ok?

**Comment by phw198** [comment]
Sorry for the delayed reponse @nonleaf! 

So the issue will be bullet point 2 in your post - the ActiveSync client is doing something strange and not updating the last modified timestamp when the client is changing something else in the calendar item. Clearly this is Not Good, and OGCS is a victim of that poor behaviour.
