### ISSUE TITLE
Events being deleted from Outlook instead of copied to Google

### ISSUE THREAD

**Issue by James-Oakley** [phw198/OutlookGoogleCalendarSync#1520]
Planning my calendar for the next few months, I just now created new copies of a regular meeting - it's eratic, so I don't use recurring events. Instead, I simply took the latest one that was already in the calendar, copied, and then hit paste in Outlook on the new dates I wanted.

When OGCS came to sync up, it asked me to confirm that it should delete each of those new events in Outlook.

What it should have done was created the new events in Google.

**Comment by phw198** [comment]
So you have two-way sync configured? Was OGCS running when you copy and pasted those items in Outlook? [See the wiki here regarding this limitation](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#2-way-sync).

**Comment by James-Oakley** [comment]
Thanks - I don't know whether it was or not, but I'd missed that limitation so thank you. I'll now be wise to this, and if it ever happens when OGCS is running, I'll report back here.
