### ISSUE TITLE
OGCS freezes when adding listener for inaccessible Public Folder account

### ISSUE THREAD

**Issue by Devo7v** [phw198/OutlookGoogleCalendarSync#1521]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
For the past month or so, whenever I open OGCS it causes Outlook to lock up.  Looking through the log file it continually freezes at "OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [35] -  Adding listener for Explorer '19073 - dd****k@g*****n.com - Outlook'  It also spawns 6 versions of msedgewebview2.exe in the task manager.  Ending the OGCS exe unlocks Outlook so I'm trying to figure out why OGCS is getting stuck.  Any help would be appreciated.

**Steps to Reproduce the Issue**  
1. Open OGCS

**Any other information**  
Windows Version: 10.0.19044 Build 19044
Outlook Version: 2207 (Build 15427.20194 Click-to-Run)
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9303205/OGcalsync.log)

**Comment by Devo7v** [comment]
Turns out that it doesn't crash the program, but it does freeze for upwards of 8 minutes.  Thoughts?  I've uploaded a new log.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9338422/OGcalsync.log)

**Comment by phw198** [comment]
I don't think it's the listener that's causing the delay, but the accessing of the Public Folder: 

```
Failed to get EntryID for folder: Public Folders - <your email>`
The file C:\Users\dd****k\AppData\Local\Microsoft\Outlook\dd****k@g*****n.com - new.ost is in use and cannot be accessed. 
Close any application that is using this file, and then try again. You might need to restart your computer.
```

Is this a new folder that was added? Can you access it manually / do you actually need it / can it be removed? What's on the `new.ost` and any idea what else is locking it?

**Comment by Devo7v** [comment]
You're correct, it is the Public folder locking things up.  It looks like IT is doing away with that and Outlook doesn't care until I try to access it (Outlook locks up until it throws up an error).  Since it doesn't seems like I'm going to be able to remove that from the Outlook interface, is there a way I can remove it from config files or alternatively, prevent OGCS from trying to access it on start up?

![image](https://user-images.githubusercontent.com/15945504/188167512-dd6b31d1-6aea-4b39-a412-65a3e345bee0.png)

**Comment by Devo7v** [comment]
I'm going to close it.  This is an issue on my end since the Public folder is inaccessible as you described.  I spoke with IT and it looks like nothing is going to change in the short term.

It would be nice if there was a way to prevent this within OGCS, to somehow only allow OGCS to access / query specific folders.

**Comment by Devo7v** [comment]
While I believe this isn't necessarily an issue with OGCS, is there a way to reduce the time it takes to error out?  Currently it searches for the Public folder as described and freezes everything for 8 minutes until OGCS finally results in an error and moves on.  Would it be possible to reduce this time?

`2022-12-02 08:54:03,637 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [35] -  Adding listener for Explorer 'Inbox - dd****k@g*****n.com - Outlook'
2022-12-02 09:02:46,224 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [312] -  Failed to get EntryID for folder: Public Folders - dd****k@g*****n.com`

**Comment by phw198** [comment]
Hi @Devo7v 

Maybe you could try changing the timeout for the overall email account: File > Account Settings > Manage Profiles > Email Accounts > Select the account, then Change... > More Settings... > Advanced > Server Timeouts
