### ISSUE TITLE
400=BadRequest

### ISSUE THREAD

**Issue by Baisuols** [phw198/OutlookGoogleCalendarSync#1530]
Sync version: 2.9.5.0

Profile: Default

Sync started at 2022.08.30 14:29:57

Syncing from 2022.08.29 to 2022.10.30

Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...

7 Outlook calendar entries found.

Scanning Google calendar...

4 Google calendar entries found.

Total inc. recurring items spanning sync date range...
Outlook 7, Google 7
Checking for orphaned Google items

Syncing Outlook → Google
Matching calendar items...

0 Google calendar entries to be deleted.

0 Google calendar entries to be created.

7 calendar entries to be compared.

Comparing 7 existing Google calendar entries
2022.08.30 11:00 "Spectra Baltic Portfolio presentation"

Attribute

Change

Start TimezoneEurope/Kiev → Europe/Kyiv
End TimezoneEurope/Kiev → Europe/Kyiv
Reminder15 → removed

3 attributes updated.

Updated event failed to save.
Invalid time zone definition for start time. [400=BadRequest]
2019.09.16 18:00  "Anglų kalba"

Attribute

Change

Start TimezoneEurope/Kiev → Europe/Kyiv
End TimezoneEurope/Kiev → Europe/Kyiv

2 attributes updated.

Updated event failed to save.
Invalid time zone definition for start time. [400=BadRequest]
2019.09.10 17:00  "Kasa"

Attribute

Change

Start TimezoneEurope/Kiev → Europe/Kyiv
End TimezoneEurope/Kiev → Europe/Kyiv

2 attributes updated.

Updated event failed to save.
Invalid time zone definition for start time. [400=BadRequest]
2019.09.10 15:00  "Išsikviesti DPD kurjerį"

Attribute

Change

Start TimezoneEurope/Kiev → Europe/Kyiv
End TimezoneEurope/Kiev → Europe/Kyiv

2 attributes updated.

Updated event failed to save.
Invalid time zone definition for start time. [400=BadRequest]
2016.04.16 10:00  "Anglų kalba"

Attribute

Change

Start TimezoneEurope/Kiev → Europe/Kyiv
End TimezoneEurope/Kiev → Europe/Kyiv

2 attributes updated.

Updated event failed to save.
Invalid time zone definition for start time. [400=BadRequest]
2013.01.20 08:00  "Magistrai, skaitliuku parodymai"

Attribute

Change

Start TimezoneEurope/Kiev → Europe/Kyiv
End TimezoneEurope/Kiev → Europe/Kyiv

2 attributes updated.

Updated event failed to save.
Invalid time zone definition for start time. [400=BadRequest]
0 entries updated.

Syncing Outlook ← Google
Matching calendar items...

0 Outlook calendar entries to be deleted.

0 Outlook calendar entries to be created.

7 calendar entries to be compared.

Comparing 7 existing Outlook calendar entries
0 entries updated.

Sync finished!

**Comment by phw198** [comment]
Duplicate #1525
