### ISSUE TITLE
Every time I Sync, from google to outlook (as target), OGCS creates copy and copy and copy of google items

### ISSUE THREAD

**Issue by MassimoPiva** [phw198/OutlookGoogleCalendarSync#1533]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue: same behaviour many times
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

<HTML>
<BODY>
<TABLE><TR><TD>Version</TD><TD>2.9.0.0</TD></TR><TR><TD>Running From</TD><TD>C:\Users\massi\AppData\Local\OutlookGoogleCalendarSync\app-2.9.0-beta\OutlookGoogleCalendarSync.exe</TD></TR><TR><TD>Config In</TD><TD>C:\Users\massi\AppData\Roaming\Outlook Google Calendar Sync\settings.xml</TD></TR><TR><TD>Subscription</TD><TD>N/A</TD></TR><TR><TD>Timezone DB</TD><TD>2022c</TD></TR></TABLE>

</BODY>
</HTML>

**Sync Direction**: G->O

**Bug Description** 
Every time I Sync, from google to outlook (as target), OGCS creates copy and copy and copy of google items
I have tried every options in "Sync Option" --> "Merge with ... " both on and off.
My goal is use OGCS to sync google TO Outlook,

**Steps to Reproduce the Issue**  
1. Go to Sync/Start Sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9483109/OGcalsync.log)

Thanks
Massimo

**Comment by bruisehilda** [comment]
I am having the same issue. I used OGCS on two different computers for the last year with no issues, and then one machine started to duplicate multiple events, while the other was still able to delete them.

**Comment by haydnlj** [comment]
Same issue for me on last few versions, currently on 2.9.5.0

**Comment by phw198** [comment]
@MassimoPiva Well you changed your configuration from excluding no Outlook categories (which returned 10 Outlook calendar items) to including only AzzurroDigitale (which returns no Outlook calendar items).

Fix that and OGCS should work as you intend once more.

BTW, if you upgraded to the latest version, as recommended, you would receive a warning that all your Outlook items have been excluded due to your category filters.
