### ISSUE TITLE
Unhandled exception has occurred

### ISSUE THREAD

**Issue by JP3251** [phw198/OutlookGoogleCalendarSync#1535]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: Portable v2.9.5.0  
**Edition**: / Portable  
**Sync Direction**:  O->G  & O<->G

**Bug Description**  
Unhandled exception has occurred window pops up when i switch profiles in sync settings.

**Steps to Reproduce the Issue**  
1. Go to Settings
2. Go to Sync Settings tab
3. Switch profile

**Any other information**  
n/a
 
:paperclip: Attach your `OGcalsync.log` file.
![2022-09-06_15h18_33](https://user-images.githubusercontent.com/48731166/188722059-391d0804-1cef-443f-99ac-c7736afe4d81.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9500125/OGcalsync.log)

**Comment by LouisLeNezet** [comment]
I think this is fixed with [#1480](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1480).
