### ISSUE TITLE
Outlook Program Access keeps popping up

### ISSUE THREAD

**Issue by F1RSTau** [phw198/OutlookGoogleCalendarSync#1537]
----
![Capture](https://user-images.githubusercontent.com/105864128/189500513-b2b0928c-5a6e-4b67-965f-440f69668a6e.JPG)

**OGCS Version**: v2.9.0.0
**Installed or Portable**: Installed

**Problem Description**  
I have this Outlook warning message pop up every time I restart my PC (see attached screenshot). I have added a Windows Firewall and Malwarebytes exception for Outlook Google Calendar Sync which did not resolve the issue.

Please advise how to securely allow the program to access Outlook without triggering warning messages.

Thank you.

Regards, Ralph Stulgies

**Steps to Reproduce the Issue**  
1. restart PC and let apps load.

**Any other information**  
Windows 10 (fully updated)

**Comment by zsjenei** [comment]
Same here. For some time it was possible to push few times allow and then it was ok. Now it keeps popping up which makes this very annoying. :(

**Comment by TheJacksonian** [comment]
This has been documented on the wiki: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security
