### ISSUE TITLE
allow sync options (more than one) depending on items properties

### ISSUE THREAD

**Issue by hbinkle** [phw198/OutlookGoogleCalendarSync#1540]
Hi,
currently I can define which items to by synced, like all with private category.
And I'm able to define that those are to synced for 60 days in future.

I'd like to define two of these combinations like:
sync:
1. all items of the current day 
2. private items for 60 days in future

The goal is: all private appointments I create in my office calendar should be synced for future.
But appointments related to work should only by synced at those days I'm working at the pc running ogcs.

**Comment by phw198** [comment]
Hi @hbinkle, you should be able to achieve this using the latest alpha release and _Profiles_ - one profile for each type of sync you describe.
