### ISSUE TITLE
Items after a specific date are not changing colour in Outlook

### ISSUE THREAD

**Issue by Inspiredbubbles** [phw198/OutlookGoogleCalendarSync#1541]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.5.0  
**Installed or Portable**: Installed

**Problem Description**  
\I am importing the Google calendar entries to Outlook. After a specific date (14 Nov) the colors are not being transferred, even though I keep syncing it. 

**Steps to Reproduce the Issue**  
1. I dont know??? 
1. 

**Any other information**  
\At some point, by deleting the entries on the Google Calendar, syncing, then creating the entries again, syncing, and then changing the colour reflected in the Outlook. But then once it synced again it reverted the colours to standard of Outlook

Settings are to sync 365 days in the future

Items that were added by other people (ie I was invited) has the colour changed according to my mapping

![colour_ABnormal](https://user-images.githubusercontent.com/81482347/193250023-dfc52d6e-ba35-4969-818d-7a3e0d36652d.JPG)
![colour_normal](https://user-images.githubusercontent.com/81482347/193250027-5a0260f2-7f96-41fa-9b5d-6273d63dbeaf.JPG)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9683303/OGcalsync.log)

**Comment by phw198** [comment]
1. Is the colour/category in Outlook being lost for all synced items, or just individual one(s)?
3. For the ones that lose their colour, do they have any commonality? Eg, 
     1. are they ones you have created in Google, or are you the attendee on someone else's invite?
     2. Are they alway recurring series, or it can be individual items too
4. When they lose their colour, are there any categories left assigned at all, or has it/they been removed?
5. If you are still seeing this issue, can you provide your log file as soon as it happens and let me know the title or time of the affected calendar item.

Thanks!

> At some point, by deleting the entries on the Google Calendar, syncing, then creating the entries again, syncing, and then changing the colour reflected in the Outlook. But then once it synced again it reverted the colours to standard of Outlook

This looks pretty close to step for reproducing the issue :slightly_smiling_face: If you are able to refine them down to something I can repeat to investigate the issue, that would really help me out. Are you changing the colour in Outlook manually, before OGCS reverts the colour in the next sync?
