### ISSUE TITLE
Fresh Install

### ISSUE THREAD

**Issue by dvonjr** [phw198/OutlookGoogleCalendarSync#1546]
**Are you already using OGCS?**
Provide the version number.<HTML>
<BODY>
<TABLE><TR><TD>2.9.0.0</TD></TR></TABLE>

</BODY>
</HTML>

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.
I had to do a fresh install of OG because of a failed SSD. Do i have to Donate again just to stop the splash screen?

**Comment by phw198** [comment]
No, just configure OGCS to use the same Google account as before - [see the wiki for more details](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Is-OGCS-Free%3F#what-if-i-change-my-computer).
