### ISSUE TITLE
Splash Screen dosn´t hide with Account 

### ISSUE THREAD

**Issue by DerIch79** [phw198/OutlookGoogleCalendarSync#1547]
Hello, I´m using OGCS since few times and I had Donate for hidden Splash Screen. Now I had installed new OGCS but the Splash Screen can´t disabled again.

**Comment by DerIch79** [comment]
Thank you for fix.

**Comment by phw198** [comment]
Hi @DerIch79, apologies for the delayed response - have you managed to hide the splash screen again yet?

If not, note that you need to configure the new install of OGCS with exactly the same Google account as before. If you are needing to use a different account, please email me with the details of the original email donated for and the one you need to use now - I can then get your donation "migrated".

**Comment by DerIch79** [comment]
Hi phw198, all works fine. Thank you, but the google login with 2.9.5.0 dosn´t work with Firefox. json error in Colume 1. I have aktivate with EDGE now.

**Comment by phw198** [comment]
Thanks for the feedback @DerIch79. What version of Firefox did you have installed when it reported that json error?

**Comment by DerIch79** [comment]
I´m using Firefox 107.0 64 bit.
