### ISSUE TITLE
Scheduled sync for multiple profiles

### ISSUE THREAD

**Issue by zoljaxity** [phw198/OutlookGoogleCalendarSync#1551]
Version: 2.9.5.0

With the new version the profiles were introduced. I haven't been able to figure out how to sync both my profiles automatically. I need to manually change the active profile and the either wait for scheduled sync or manually sync the profile. Is there a way to enable scheduled sync for both / multiple profiles?

Wonderful work with the program btw, has made my work a walk in a park.

**Comment by phw198** [comment]
It should just be a case of setting the sync interval on each profile, same way as beforehand when there was only a single profile?
