### ISSUE TITLE
A copied appointment in Outlook is not synchronised to Google

### ISSUE THREAD

**Issue by efranz** [phw198/OutlookGoogleCalendarSync#1552]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0
**Edition**: Installed   
**Sync Direction**: O<->G

**Bug Description**  
When I copy an appointment in Outlook calendar from one date to another the copied appointment is not synchronised to Google calendar.

**Steps to Reproduce the Issue**  
1. Copy an appointment from one day to e.g. the next day
2. Run OGCS
3. Check the calendar on Google side. The copied appointment is missing.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Hi @efranz - [this is already documented](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#outlook-appointment-copy--paste); you need to ensure that OGCS is running when you copy and paste already synced items.

**Comment by mikemberg** [comment]
Hi

I have the same issue as efranz, but (!) OGCS is always running... when i copy and paste an event in outlook, then the copied item is deleted in outlook when next sync runs (i have push activated)... i tried stopping OGCS (Exit) and then copied an pasted items, running OGCS again and then the copied items are synced (most... it's not 100% sure for all of them...)

**Comment by phw198** [comment]
@mikemberg 
:spiral_notepad: I'd need your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) covering the period of copy and paste to investigate further. Make sure you're running the latest alpha release first, however!
