### ISSUE TITLE
Exclude certain Google colours from being synced to Outlook

### ISSUE THREAD

**Issue by strfngr** [phw198/OutlookGoogleCalendarSync#1553]
**Is your feature request related to a problem? Please describe.**
I am syncing multiple Outlook inboxes with my Google calendar. For me, Google is then the aggregator and I can easily share my availabilities with others. 
1 of the syncs is bidirectional, as I want to see entries added to my Google calendar also in my main Outlook calendar.
The problem: All entries from my other Outlook calendars get synced to Google first, and then from Google to my main Outlook calendar, causing tons of duplicates.

**Describe the solution you'd like**
It would be great, if I could stop certain colour entries from being synced back from Google to Outlook. (Similar to excluding Outlook categories from being synced)
This way, I could make OGCS assign individual Google colours to each entry created from my Outlook calendars and then exclude those colours in the sync back to my main calendar.

**Comment by phw198** [comment]
Test cases:
- [x] O > G, Create non-excluded item in O, sync to G
   - [x] Exclude O item, don't delete synced items, G remains
   - [x] Exclude O item, do delete synced items, G deleted
   - [x] Exclude O item, exclude G item, nothing happens (both out of scope)
   - [x] Include O item, exclude G item, G not (re)created
   - [x] Change to G > O and exclude O item, O not duplicated

- [x] G > O, Create non-excluded item in G, sync to O
   - [x] Exclude G item, don't delete synced items, O remains
   - [x] Exclude G item, do delete synced items, O deleted
   - [x] Exclude G item, exclude O item, nothing happens (both out of scope)
   - [x] Include G item, exclude O item, O not (re)created
   - [x] Change to O > G and exclude G item, G not duplicated

**Comment by phw198** [comment]
:package: This feature is now available as an early [hotfix v2.10.1.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13063998/v2.10.1.9.zip) release ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/f427e563-e164-464b-be5a-32c93dd1bd19)

Please let me know how it goes if you give it a go!
