### ISSUE TITLE
Google Authorization Token Needs Updating

### ISSUE THREAD

**Issue by Jeffbo2332** [phw198/OutlookGoogleCalendarSync#1554]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5  
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
My syncing has stopped working.  When I try to update everything, I get a message that popes up and says "Your Google authorisation token needs updating.  The process to reauthorise access to your Google account will now begin...."  I do this and click on my Google account and then "Allow" which brings me right back to the same error message.

**Steps to Reproduce the Issue**  
1. See above..

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9983725/OGcalsync.log)
[Google Error.docx](https://github.com/phw198/OutlookGoogleCalendarSync/files/9983730/Google.Error.docx)

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
OGCS is not able to communicate with Google (or anything else, such as GitHub) - just gets the response "403 Forbidden". I see Internet Explorer is set to use a proxy, so it seems this is blocking OGCS.

:package: [Hotfix v2.9.5.16.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/10096539/v2.9.5.16.zip) should now report this better ([see instructions for applying hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)), but you'll need to resolve your proxy configuration somehow...
