### ISSUE TITLE
OGCS Crashes when it starts [0x8002802B]

### ISSUE THREAD

**Issue by elalewen** [phw198/OutlookGoogleCalendarSync#1556]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5  
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
OGCS crash when I want to start it 

**Steps to Reproduce the Issue**  
1. Just click on OutlookGoogleCalendarSync.exe
2. And I have the crash and the error message

**Any other information**  
Error Message : 2022-11-15 12:17:40,123 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1142] -  Impossible d'effectuer un cast d'un objet COM de type 'Microsoft.Office.Interop.Outlook.ApplicationClass' en type d'interface 'Microsoft.Office.Interop.Outlook._Application'. Cette opération a échoué, car l'appel QueryInterface sur le composant COM pour l'interface avec l'IID '{00063001-0000-0000-C000-000000000046}' a échoué en raison de l'erreur suivante : Élément introuvable. (Exception de HRESULT : 0x8002802B (TYPE_E_ELEMENTNOTFOUND)). 
  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10012126/OGcalsync.log)

Thanks for your HELP !

**Comment by theLadEli** [comment]
Have you got Microsoft Outlook installed?

**Comment by elalewen** [comment]
Yes I have. 
![image](https://user-images.githubusercontent.com/25105768/204253902-166ab16c-e73c-4e0e-ad77-414ebb40fc82.png)
![20221128-0711-uOU9Z0l8JB](https://user-images.githubusercontent.com/25105768/204253970-24358d35-ed84-4f88-a66c-6a21a0cab625.png)

**Comment by elalewen** [comment]
Here is my error message box : 
![20221128-0712-wa9lii6mof](https://user-images.githubusercontent.com/25105768/204254181-04b2848d-32a1-4776-aeb5-218e829aaac5.png)

**Comment by elalewen** [comment]
News ? Ideas ?

**Comment by phw198** [comment]
[Check the wiki advice](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002802b---type_e_elementnotfound). If that doesn't help, join other users on #999 to see if you can find a common cause.
