### ISSUE TITLE
Can't donate money to donate@paulwoolcock.co.uk

### ISSUE THREAD

**Issue by kanokgan** [phw198/OutlookGoogleCalendarSync#1557]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
This is issue with my Paypal account. The error says my paypal account is from the country (Thailand) that not support donation. I can't make donation to `donate@paulwoolcock.co.uk` hence I can't remove splash screen.

**Steps to Reproduce the Issue**  
1. -

**Any other information**  
Screenshot of Paypal error message.
Donate with Paypal
![image](https://user-images.githubusercontent.com/227870/202378112-d4ddf654-e366-4608-8718-2ebe66749b13.png)

**Comment by kanokgan** [comment]
I can make donation now.

**Comment by phw198** [comment]
Thanks @kanokgan! How did you resolve it in the end? Using a VPN so you can appear in a different country might be a workaround for any similar future situations...
