### ISSUE TITLE
Not all recurring annual events in Outlook are being synced to phone Google calendar (some are...)

### ISSUE THREAD

**Issue by EveOz** [phw198/OutlookGoogleCalendarSync#1559]
I installed Google calendar on my phone AND acquired OGCS both for the first time today. I had been syncing my computer's Outlook calendar with another Android phone calendar but that stopped working earlier this month after years of successful syncing. Oh well. I searched for another way and found OGCS. 

I installed Google calendar on my BlackBerry Key2 (Android) phone and synced both ways with OGCS, which went extremely well. Then I noticed that some recurring events that are not attached to a specific time on a given day's schedule are not syncing. See attached screenshot. The bank " withdrawal" on Dec 1, which occurs annually DID sync to Google calendar but "Deb's birthday" (also an annual occurrence) did not. 

I've also attached the OGcalsync.log. I'm using version 2.9.0.0.

Not sure I've complied with the other requirements. Kind of at a loss. Hope you can advise. 

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10080435/OGcalsync.log)))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

![calendar copy](https://user-images.githubusercontent.com/118949951/203682597-285f0d3f-68fa-4c85-a31b-43ab309ce321.jpg)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10080442/OGcalsync.log)

**Comment by EveOz** [comment]
The onscreen "log" says:
"11 are exceptions to recurring events"
Is this related to my question?

**Comment by phw198** [comment]
Hi @EveOz and welcome.

It looks like you have set OGCS to only sync Outlook items with certain categories, on of them being `<No category assigned>`. It doesn't look like Deb's birthday item has a category, but can you try assigning one that is being synced (eg `Blue Category`) to see if that works. I can't recall if there's a fix for "no category" in subsequent alpha releases, so you'd need to upgrade for further troubleshooting.

Also, be aware of [this wiki entry](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-cant-i-sync-more-than-1-year-past-or-future) - specifically the part "if the recurring series repeats annually, then the month it occurs must fall within the synced date range".
