### ISSUE TITLE
Backup OGCS Settings

### ISSUE THREAD

**Issue by Lusayalumino** [phw198/OutlookGoogleCalendarSync#1561]
Version 2.9.0.0

I'm wondering if there's an easy way to backup the program settings (to reinstall later)?

If not, would backing up the following directory do the trick?
C:\Users\admin\AppData\Roaming\Outlook Google Calendar Sync\

Thanks so much for this fantastic program!

**Comment by phw198** [comment]
Yes, that's basically it - [see here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading#maintaining--backing-up-configuration-settings) for a bit more detail.

**Comment by phw198** [comment]
:package: This should now be available with [hotfix v2.10.0.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12062219/v2.10.0.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

On the `Save` button on the `Settings` tab, there are additional options to export and import settings.

Please post an update if tested,
