### ISSUE TITLE
Auto Sync dosn´t work

### ISSUE THREAD

**Issue by DerIch79** [phw198/OutlookGoogleCalendarSync#1564]
The Auto Sync Option can´t be enabled in Version 2.9.5  .

**Comment by phw198** [comment]
I'll need more information than that...

**Comment by DerIch79** [comment]
I´ve seen autosync is enabled, but the Delay can´t be selected. They are grey.

**Comment by DerIch79** [comment]
I´m using Win 11...

**Comment by DerIch79** [comment]
I´ve seen that auto sync dosn´t work. It´s enabled, but dosn´t start automaticly.
![OGCS](https://user-images.githubusercontent.com/115883913/213483726-26f24f16-9eee-4420-8d7e-a66243076dc7.jpg)

**Comment by phw198** [comment]
It looks like you haven't configured a sync schedule, so there's nothing to enable.

:package: This is now made clearer through [hotfix v2.9.6.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/10611054/v2.9.6.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

![image](https://user-images.githubusercontent.com/11843015/216820160-aa982414-7a75-427a-927f-967bf2f7a55b.png)

Please let me know how it goes.

**Comment by DerIch79** [comment]
Fix is working.
