### ISSUE TITLE
OGCS should not access my e-mail address information

### ISSUE THREAD

**Issue by walter-fle** [phw198/OutlookGoogleCalendarSync#1566]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.0.0  
**Installed or Portable**: Installed

**Problem Description** 
Since the day I installed Outlook Google Calendar Sync (OGCS), the following warning message always appears when I start the programme. After each "deny", it annoys me several more times, so that I have to "deny" it again and again:

„A programme is trying to access your e-mail address information in Outlook. If this happens unexpectedly, click on "Deny". Check that your antivirus program is up to date. is up to date. Click on "Help" for more information on e-mail security and how to suppress this warning. email security and how to suppress this warning.“

What's the point? I only want to synchronise the Outlook calendar via Google Calendar - but under no circumstances my addresses or contacts!
What do I have to do so that OGCS never tries to access my email address information again? "Disable telemetry" does nothing. The unwanted access attempt will continue.
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
This is [well documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security).

Needing email addresses is non-negotiable when syncing meeting attendees, so if you have that set you'll need to turn that off.
