### ISSUE TITLE
OGCS is not updating google calendar for recurring meetings scheduled prior to Standard Time ("fall back")

### ISSUE THREAD

**Issue by iiyt** [phw198/OutlookGoogleCalendarSync#1567]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0
**Edition**: Installed 
**Sync Direction**: O->G

**Bug Description**  
OGCS is not updating google calendar for recurring meetings scheduled prior to Standard Time ("fall back").  Pretty self-explanatory.  My old recurring meetings are all off by an hour in google.

**Steps to Reproduce the Issue**  
1. schedule a recurring meeting in outlook during daylight savings time
2. wait until standard time.  outlook will show the correct time, google will not.

**Comment by phw198** [comment]
1. Upgrade to the latest alpha release
2. Perform a full sync by pressing `Shift` and clicking `Sync` button.

**Comment by iiyt** [comment]
Will do, thank you.
