### ISSUE TITLE
Using Settings.xml file on other computers?

### ISSUE THREAD

**Issue by WarningU2** [phw198/OutlookGoogleCalendarSync#1569]
**Are you already using OGCS?**
2.9.0.0

**Describe the question you have**
I have multiple computers and OGCS running on each computer.  Recently one of the settings on one of my computers was in conflict.   I made it the same as the others and all was good.   But it made me wonder can you export the settings.xml file in appdata\roaming and replace on the other other computer so that the same settings are in sync?

**Comment by phw198** [comment]
Yes, I think this is pretty much OK - that's largely why it's in the roaming directory anyway, so if you're signing into multiple computers on the same domain, the settings would follow you. 

Manually copying the settings.xml file between different computers with different installs of OGCS is slightly different, but should be OK - just be aware some items like number of syncs, and last sync date might not be accurate.

**Comment by WarningU2** [comment]
Home environment (workgroup domain).   Copied settings.xml to all 3 computers after shutting OGCS down.   Worked ok on all 3 computers same settings file that I had copied.
