### ISSUE TITLE
Not picking up new items from Outlook or Gmail calendar

### ISSUE THREAD

**Issue by devan24** [phw198/OutlookGoogleCalendarSync#1570]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.5.0
**Installed or Portable**: Installed
**Problem Description**  
Not syncing new items v2.9.5.0 

**Steps to Reproduce the Issue**  
1. Manual sync for both, then force Google to Outlook and Outlook to Google without success

**Any other information**  
Created new entry on phone, sat down later at computer to check today's activities and realized new entry from phone had not synced. tried forcing Google to Outlook to update, no success. Created event in Outlook and tried Outlook to Google and didn't update as it should have created a new event as was renamed in Outlook

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) covering the period where you are running the syncs you described.

**Comment by devan24** [comment]
Item was picked up eventually, at least a couple of hours after I reported it. Currently showing one each from Google and Outlook for event added on and for 12/17/22
