### ISSUE TITLE
Google revokes authentication token

### ISSUE THREAD

**Issue by v-aravind** [phw198/OutlookGoogleCalendarSync#1571]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
I get this error at least once a week randomly, can't figure out any pattern or specific reason why it happens.
"Google has revoked your authentication token. Account requires reauthorising.
On the Settings > Google tab, please disconnect and re-authenticate your account."
I need to disconnect and retreive the account each time this happens

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync-copy.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/10270729/OGcalsync-copy.txt)

**Comment by phw198** [comment]
I see you are using your own API keys, so maybe it is something to do with that? I'm guessing you haven't gone through the Google approval process for the Oauth app you created, but I'm not sure this would be the cause for Google keep revoking it. 

I have heard that it may happen if the IP you are accessing from with the access token changes a lot they might see that as suspicious - eg are you running OGCS on a VM in the cloud?

Ah, no it is related to the tightening up of OAuth apps that are published as "testing" - [see here](https://support.google.com/cloud/answer/10311615#zippy=%2Ctesting):

> Authorizations by a test user will expire seven days from the time of consent. If your OAuth client requests [an offline access type](https://developers.google.com/identity/protocols/oauth2/web-server#offline) and receives a refresh token, that token will also expire.

Does that match your set up?
