### ISSUE TITLE
Google blocking access to app - stuck in 'preparing to authenticate' mode

### ISSUE THREAD

**Issue by Judi-mae** [phw198/OutlookGoogleCalendarSync#1572]
> Checklist:-
> * [✔️] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [✔️] Reproduce the issue
> * [✔️] Complete the information below
> * [✔️] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0  
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
When app syncs it now manually attempts to connect to Google, asking me to select an account / log in via Chrome, then it says 'App blocked'. I have tried Google security settings and cannot find a way to get OGCS to work again. I have not recently changed anything and app was working fine until yesterday (20.12.22).

Assume others are seeing this issue? Or if not, should I reinstall? 

I updated to most recent Alpha version (v2.9.5.0) and issue is still replicating.

Cannot see a way around this, please could anybody help?

**Steps to Reproduce the Issue**  
1. Let app open with laptop start up / open app
2. Let app start to sync
3. Log in via Chrome to Google account as requested (this is new)
4. App gets stuck trying to authenticate with Google

![Google blocked access to app - stuck in 'preparing to authenticate' mode](https://user-images.githubusercontent.com/85355787/208905892-f83c26c1-0625-45ea-83b0-9a3086e5b2fe.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10277640/OGcalsync.log)

**Any other information**  
* Google security FAQs suggest 'Turn off "Less secure app access"' - this is no longer an option [https://support.google.com/accounts/answer/6010255?hl=en#zippy=%2Cif-less-secure-app-access-is-on-for-your-account]
*  ![Less secure](https://user-images.githubusercontent.com/85355787/208906642-49910c74-b351-4da6-ad10-85242a165c9d.png)

* Turned off 2 stage verification just in case this was having an impact, no change.
* No current 'security issues' highlighted in Google account.
* OGCS is still being given third party access in Google account, though now marked as 'unverified':
* ![Google security access - OGCS marked as unverified](https://user-images.githubusercontent.com/85355787/208907374-87329dd6-7e71-4860-bbc3-b87596278ef1.png)

Log attached:
:paperclip: Attach your `OGcalsync.log` file.

Please help! :)

**Comment by Judi-mae** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10277682/OGcalsync.log)

**Comment by phw198** [comment]
If you're a long time user of OGCS, then try disconnecting the Google account in the OGCS settings, and then reconnecting.

**Comment by Judi-mae** [comment]
Paul, thank you so much. I didn't think of this simple solution! It has worked. I will close. Many thanks!
