### ISSUE TITLE
Recurring events do not appear to populate for the following year

### ISSUE THREAD

**Issue by evilwraith** [phw198/OutlookGoogleCalendarSync#1573]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.5.10
**Installed or Portable**: Installed

**Problem Description**  
Recurring events do not appear to populate for the following year. 

Ex: I have birthdays populated for 2022 and prior, and 2024 and later, but not 2023. Those were deleted and will not populate.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10282320/OGcalsync.log)

**Comment by phw198** [comment]
Hi @evilwraith Apologies for the very delay response. I suspect a known bug that may have incorrectly deleted the 2023 instance of the birthdays will be the cause, and once the instance is gone, it won't automatically come back.

As you have two-way sync configured, you can 
1. edit the Outlook recurring series (select "The entire series" when editing) 
2. open the recurrence dialogue box and change end date of the series (you can revert this afterwards)
3. click `Save and Close`
4. The missing occurrence in 2023 should reappear
5. revert the change made in step 2
6. Sync from Outlook to Google

Make sure you have upgraded to the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) and if you notice the 2023 occurrences being removed again, please provide your OGcalsync.log file for the same sync run that deleted them.
