### ISSUE TITLE
Recurring event (2-weekly) does not sync from Outlook to Google

### ISSUE THREAD

**Issue by BittermanAndy** [phw198/OutlookGoogleCalendarSync#1575]
**OGCS Version**: v2.8.0.0 
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
I have a recurring event in Outlook, on a Monday, every two weeks, at 6pm, lasting 0 minutes. It does not appear in Google calendar at all.

**Steps to Reproduce the Issue**  
Seems to affect this event only, I don't know why. Other recurring events are synching OK.

**Any other information**  
Logs do not suggest any problems as far as I can see, the event just does not show up in Google and never has:
2022-12-29 22:19:18,007 DEBUG  29 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 01/02/2021 18:00 (R) => "Put garden waste out"
2022-12-29 22:19:18,008 DEBUG  29 OutlookGoogleCalendarSync.Recurrence [0] -  Creating Google iCalendar definition for recurring event.
2022-12-29 22:19:18,016 DEBUG  29 OutlookGoogleCalendarSync.Recurrence [0] -  RRULE:FREQ=WEEKLY;INTERVAL=2
2022-12-29 22:19:18,060 DEBUG  29 OutlookGoogleCalendarSync.Console [0] -  01/02/2021 18:00   "Put garden waste out"
2022-12-29 22:19:18,061 DEBUG  29 OutlookGoogleCalendarSync.Console [0] -  AttributeChangeReminder DefaultTrue → False
2022-12-29 22:19:18,077 DEBUG  29 OutlookGoogleCalendarSync.Console [0] -  1 attributes updated.

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10331312/OGcalsync.log)

**Comment by BittermanAndy** [comment]
Please do not let this issue go dormant.

Please fix it.

What's the point of providing a Github for people to report problems if you ignore them?

**Comment by BittermanAndy** [comment]
Please do not let this issue go dormant.

Please fix it.

This is so frustrating.

**Comment by phw198** [comment]
Because life is busy and there's only one of me doing this in spare time. It's also really frustrating when people ignore the [guidance for raising issues](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#found-a-bug) - v2.8.0 is 4 years old!

In order to receive support, you need to [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg). If it's still a problem after that, please upload your `OGcalsync.log` file again ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by BittermanAndy** [comment]
I completely understand that you might not have the resources to jump on every bug immediately. But in that case, you should turn off the automatic system timeout to mark bugs as dormant and about to be closed! I never demanded you fix this instantly or any given timescale at all, but it feels insulting and dismissive for the system to decide to close a bug I reported without anyone even having looked at it. That time pressure is something your system introduced, not me.

With that said, I apologise for not realising / taking enough diligence to notice that I was not running a sufficiently new version, that was wrong of me and I should have done that first, I'm sorry. I will upgrade and see if this bug is still an issue. (Why hadn't I already done that? Last time I tried to upgrade, the upgrade failed... but that is of course a problem in its own right that I should report separately).

**Comment by phw198** [comment]
Understood that it's not a good look to auto close tickets that have no response from me. Ideally it would only close ones where the last response is from me (as it's equally annoying people that raise an issue and then ignore the time and response I put in), but it doesn't have that ability. I hope to be back on top of this project now though!

The upgrade mechanism should be more robust in the more recent releases, but I know there were issues with it some years back. Probably easiest to download the latest Setup.exe from the [main website](https://phw198.github.io/OutlookGoogleCalendarSync).

**Comment by BittermanAndy** [comment]
OK, thank you for the suggestion, I will do that. Sorry again for the confusion.

**Comment by BittermanAndy** [comment]
Have just updated and checked, and can confirm that this appears to be working in the new version.

Sorry again for not updating to a newer version sooner, thank you for your help.

**Comment by phw198** [comment]
Great! Thanks for confirming :+1:
