### ISSUE TITLE
Sync Error Because of Google Handshake

### ISSUE THREAD

**Issue by JFergen** [phw198/OutlookGoogleCalendarSync#1577]
**OGCS Version**: 2.9.5.7
**Installed or Portable**: Installed

**Problem Description**  
Unable to sync because of failed Google Handshake

"Unable to authenticate with Google. The following error occurred:
Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

**Steps to Reproduce the Issue**  
1. Open OGCS
2. Try to sync
3. Brought to Google Authentication page where I allow OGCS to access
4. Error while syncing:

![image](https://user-images.githubusercontent.com/8197821/210269707-17154d53-29f6-4b6f-b210-782a628c26a9.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10333159/OGcalsync.log)

**Comment by Ficino61** [comment]
I also have this problem. It started after using OGCs for several years.

**Comment by Ficino61** [comment]
Bump

**Comment by phw198** [comment]
v2.9.5.7 is a hotfix, so maybe this didn't get applied in the right way? OGCS has been using v13 of Newtonsoft since v2.9.0, so there's no way it should be looking for v12 on a subsequent release.

Are you still getting this issue on the latest alpha release of OGCS, v2.9.6.0?

**Comment by Ficino61** [comment]
Thank you for your comment. I have uninstalled and downloaded the newer version and although it says it has synched without problems, it is still not populating my gmail calendar.

**Comment by phw198** [comment]
@Ficino61 That sounds like a different issue (or more likely an incorrect configuration) - please raise a separate issue if you need assistance.
