### ISSUE TITLE
G->O: The recurrence pattern is not valid. 

### ISSUE THREAD

**Issue by Scott3102** [phw198/OutlookGoogleCalendarSync#1578]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.5.0  
**Edition**: Installed / Portable  
**Sync Direction**: G->O

**Bug Description**  
When Google attempts to sync with Outlook, this message comes up:The recurrence pattern is not valid. 

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

> Sync version: 2.9.5.0  Profile: Default  Sync started at 1/4/2023 8:21:27 AM  Syncing from 1/3/2023 to 3/24/2023  Outlook ← Google  Finding Calendar Entries Scanning Outlook calendar...  214 Outlook calendar entries found.  Scanning Google calendar...  86 Google calendar entries found.  Total inc. recurring items spanning sync date range... Outlook 94, Google 92 Checking for orphaned Outlook items... Matching calendar items...   2 Outlook calendar entries to be deleted.  0 Outlook calendar entries to be created.  92 calendar entries to be compared.  Deleting 2 Outlook calendar entries Not deleted: 1/13/2023 6:00 PM "Dine with Nine Potluck at Church" Not deleted: 1/5/2023 3:00 PM "Eileen Ahearn-new Deacon orientation"  Comparing 92 existing Outlook calendar entries  Appointment update failed. 0 entries updated. Sync finished!

**Comment by phw198** [comment]
Apologies for the delay in responding!

:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) after you have encountered the error so I can investigate further.
