### ISSUE TITLE
unable to install & set up OGCS

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#1580]
Just got new PC windows 11.  Finally got outlook 2013 installed & working.
I now need to get OGCS working on this PC so my life can get back to normal:)

I am attaching my logfile - I download version 9.5
[OGcalsync 010423.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/10348906/OGcalsync.010423.txt)
 Please help put my life back in SYNC

**Comment by phw198** [comment]
You have a bad install of Office and the error is [0x80029C4A](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary) which is documented in the wiki - were you automatically taken there?

Seeing as you have only just installed Office, try a few reboots of your computer (no doubt you'll have now done this given the ticket is rather old :grimacing:)!

**Comment by michgal2k** [comment]
It seems to be working better.
