### ISSUE TITLE
Need help - new PC can't get OGCS to work

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#1581]
Hi Paul -
Just got new PC with windows 11. Finally got outlook 2013 installed & working.  
I now need to get OGCS working on this PC so my life can get back to normal:)

I am attaching my logfile - I download version 9.5

Please help put my life back in SYNC

[OGcalsync 010423.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/10352636/OGcalsync.010423.txt)

**Comment by Tosko4** [comment]
There is a wiki for that error, it's mentioned in the logs. Did you try to read it?

https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary

**Comment by michgal2k** [comment]
Yes I tried really hard to read it AND understand it.  Wasn't happening.  I ended up buying an update Office product and now its working again

**Comment by Tosko4** [comment]
@phw198 in that case this can be closed :)

**Comment by phw198** [comment]
Glad you got it working again @michgal2k !
