### ISSUE TITLE
Cannot fix registry issue [0x80040154]

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#1582]
Upgraded PC windows 11 and loaded Office 2013 Home & Business.
Outlook works fine although OGCS believes there to be a problem with install.  I have done a repair already.
I then followed the instructions for registry repair - nothing for WIN32 is showing up only WIN64.
 I then tried the cmd prompt - cd c:\windows\Microsoft.NET\Framework64\v2.0.50727
it did not find v2.0.50727.
I am nervous to go further as working with the registry is scary when you really have no clue what you are doing.
I really am anxious to get this working.  Thanks for the help!

**Comment by phw198** [comment]
I'm guessing you are hitting error `0x80040154` then, as that's the only error in the wiki that references `cd  c:\windows\Microsoft.NET\Framework64\v2.0.50727`?

Is this still a problem for you? As the wiki says, the only verified fix is to uninstall and reinstall Office :slightly_frowning_face:
