### ISSUE TITLE
O<->G: New Outlook item synced to Google, but then deleted from Outlook in same sync

### ISSUE THREAD

**Issue by gprscrprs** [phw198/OutlookGoogleCalendarSync#1583]
I'm using installed version 2.9.0.0.
Synchronization is O <-> G

When I create a meeting in Outlook, synchronization adds the meeting to Google and then deletes it.  In the attached logs, an example is the "Cumulus Cloud Server" meeting which was added at approximately 8:54:25 today and then requested deletion at approximately 8:55:01.  No change was made during this time.

What could cause this?

Thanks,
Dean

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10360773/OGcalsync.log)

**Comment by LucyNietoC** [comment]
I have the same problem. 
OGCS Version: I have the v2.9.5-alpha instaled. 
Edition: Installed / PC
Sync Direction: O<->G

Bug Description
Inserto varias citas nuevas en mi calendario de Outlook. Cuando hago la sincronización, me pide que borre alguna de esas citas y a veces también alguna cita de semanas atrás. No todas, solo algunas.


[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10419344/OGcalsync.log)
![Screenshot 230114 203306 a](https://user-images.githubusercontent.com/122709376/212520095-87cc7abf-2fb2-4a9e-a7a0-663977708ce8.JPG)

**Comment by Irish-Coder69** [comment]
I have just installed the same version and so far, I am not having any issues.

**Comment by westr029** [comment]
I can confirm the same issue. It is similar to the issue mentioned by @gprscrprs . Seconds after creation in Outlook it is deleted in Outlook. 

As far as I could see from the logs, the issue from @LucyNietoC is different. In the logs I could only find the deletion of the appointment in the dialog-box, but this event was not created before the deletion request.

**Comment by phw198** [comment]
@westr029 Correct, @LucyNietoC's  deletion is not relevant to this issue (@LucyNietoC [see the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync)).

@westr029 @gprscrprs Please :
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by westr029** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11147125/OGcalsync.log)

hereby my latest log file. Not using the laptop with OGCS the coming weeks, but hopes this log files gives some clue already.

**Comment by phw198** [comment]
@westr029 Thanks, but unfortunately that log file doesn't have any deletions captured at all (or creations either for that matter).

**Comment by westr029** [comment]
I am sorry that there was nothing in the log-file. Could that be, because I enabled the flag to always ask if an event can be deleted?
UNfortunately, I cannot help you with this any further, since I have a new laptop without the need for OGCS to sync calendars.

**Comment by phw198** [comment]
Thanks for letting me know, @westr029 

As the OP has not engaged with the issue since raising it, I will close it out.
