### ISSUE TITLE
O->G: Hangs on "comparing items"

### ISSUE THREAD

**Issue by JoopHofland** [phw198/OutlookGoogleCalendarSync#1584]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)
Not available, process keeps continuing without error ending

**OGCS Version**: v2.9.0.0
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
OGCS installed on new laptop (Windows 11 Home). All settings of OGCS on the old computer copied exactly.
Started synchronization G>O. This works flawlessly.
Settings adjusted for sync O<->G. Sync starts, but eventually hangs at
"Syncing Outlook→Google
Matching calendar items..." and do not complete the synchronization.
Manually aborted after waiting about an [hour.]

**Steps to Reproduce the Issue**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10375805/OGcalsync.log)

1. Go to...OGCS in tray
1. Click on...Start sync

**Any other information**  
```
Sync version: 2.9.0.0
Sync started at 9-1-2023 18:03:33
Syncing from 9-1-2022 to 10-1-2024
Outlook ↔ Google
Finding Calendar Entries
Scanning Outlook calendar...
591 Outlook calendar entries found.

Scanning Google calendar...
538 Google calendar entries found.
36 are exceptions to recurring events.
Total inc. recurring items spanning sync date range...
Outlook 591, Google 538
Checking for orphaned Google items
Reclaiming Google calendar entries
Reclaimed: 11-1-2023 09:00 "Webinar: Dag 3 - Training Natuurlijk Leiderschap"
Reclaimed: 10-1-2023 09:00 "Webinar: Dag 2 - driedelige training Natuurlijk Leiderschap"
Reclaimed: 9-1-2023 09:00 "Webinar: 3-delige training Natuurlijk Leiderschap"
Reclaimed: 12-1-2023 15:00 "5e ALV SharePeople Coöperatie"
Reclaimed: 8-2-1972 08:30  "Liesbeth Mulder jarig ('72)"
Syncing Outlook → Google
Matching calendar items...
```

**Comment by phw198** [comment]
Your log file is full of `Organiser changed time of appointment...but the organiser is you! (Shouldn't have ended up here)` - I'm not sure why this is, but 2.9.0 is pretty old now.

Please:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) after reproducing the issue again.
