### ISSUE TITLE
Rate Limit Exceeded [403=Forbidden]

### ISSUE THREAD

**Issue by Tosko4** [phw198/OutlookGoogleCalendarSync#1589]
I am currently using 2.9.5.14 of this lovely tool. And I am noticing some things I haven't gotten or noticed before. But I am wondering what rate limit it is referring too. 

Maybe I can try to limit some sort of syncing to remain within the limits. Would you know? I do get the option if I'd like to continue the sync. When I wait a little bit and press Yes, it seems to continue.

![image](https://user-images.githubusercontent.com/1294707/214289978-6685d16f-25ea-4810-a115-5f8c56f24222.png)

**Comment by phw198** [comment]
The quota is a shared quota for all users of the application. However, Google have changed they way they are reporting the quota limits being exceeded, so OGCS wasn't handling it quite right - should properly explain the issue and also information about getting guaranteed quota.

:package: This should now be improved with [hotfix v2.9.6.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11011216/v2.9.6.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes!
