### ISSUE TITLE
Issue assigning categories

### ISSUE THREAD

**Issue by hdservicesnl** [phw198/OutlookGoogleCalendarSync#1591]
Hi,

We primarly use OGCS only from Google > Outlook (oneway sync)
It works awesome, but I'd love to have the calendar items to be assigned to a category so you can easily see a difference in colors in Outlook.

Although they do not assign :(.

There are 2 options in the software for category assignment, I tried them both, but they stay category-less.

I tried the update from yesterday also, but issue is still there.

You should say this option should do the trick:

![image](https://user-images.githubusercontent.com/18151167/216287053-838486ec-97af-4b49-95ad-d276c0cc734d.png)

Hope you got the fix, Thanks!

**Comment by phw198** [comment]
I've tested it for syncing a new item in Outlook on v2.9.6.0 and it works as expected.

Have you tried it with creating a new item in Google and syncing it, or only syncing items that have already been synced? If the latter, try pressing `Shift` as you click `Sync`, to perform a full sync...

**Comment by hdservicesnl** [comment]
Hi, Thank you for your response.

We add a new item in Google Calendar, then we wait till GCS syncs it to Outlook and then the new item in the calendar does not have a category at all.

So it isn't only for existing items. Also new has the issue.

**Comment by phw198** [comment]
Please provide your logfile after you have run a sync that creates a new item in Outlook without the new category.
