### ISSUE TITLE
Is there a way of ignoring this error? Invalid start time [400=BadRequest]

### ISSUE THREAD

**Issue by DerekThorslund** [phw198/OutlookGoogleCalendarSync#1592]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.6.0
**Installed or Portable**: Installed on Windows 11

**Problem Description**  
<img width="184" alt="image" src="https://user-images.githubusercontent.com/104800073/216794532-9c8498ac-7f66-4c24-b5ef-8f0a6ef200a4.png">
Every time the program runs I have to manually intervene because an updated event failed to save due to invalid start time [400=BadRequest]. Is there a way of ignoring such errors? 

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
Timezone DB 2022g

When I look at the calendar entry in Outlook, the start time looks fine, despite the error message from OGCS which interrupts the sync ("Updated Google event failed to save. Continue with synchronization?"

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

Let me know if the issue persists afterwards.

**Comment by DerekThorslund** [comment]
Hi Paul,

Unfortunately, the error still occurs after upgrading to 2.9.6.0.

***@***.***
The event has a start time of 1:30pm Pacific Time.

Derek

**Comment by phw198** [comment]
I think we probably need to pick back up on https://github.com/phw198/OutlookGoogleCalendarSync/issues/1447#issuecomment-1193146185 - I spent a fair bit of time on this before and drew a blank, but happy to troubleshoot further.
