### ISSUE TITLE
1 Outlook items would have been deleted, but you have deletions disabled...

### ISSUE THREAD

**Issue by huotg01** [phw198/OutlookGoogleCalendarSync#1594]
First of all, it's a fantastic application!

Sometimes I receive the notification: "1 Outlook items would have been deleted, but you have deletions
disabled.". The question is then "How to know what is this Outlook item"?

Would it be possible to link this message to the Outlook item, or to have more information in the notification ?

I have to say that the solution/information could be already there, but I missed it....😒

Thanks,

Gaston

**Comment by phw198** [comment]
No, you haven't missed anything, so I've added it in a hotfix below that will now list the items that should be deleted. Note normally, the disable delete option is there just to give users confidence the sync is doing what they expect, but it should not be left with deletions disabled - else it's not a true sync :slightly_smiling_face: 

:package: Please try with [v2.9.6.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11011956/v2.9.6.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes.
