### ISSUE TITLE
O->G: Annual holiday entries not synced

### ISSUE THREAD

**Issue by Survival62** [phw198/OutlookGoogleCalendarSync#1599]
Version 2.9.0.0

I started using OGCS in January 2023, so my installation is quite fresh.
I use Outlook 2016 Calendar which contain international and national holidays of different countries.
Those entries I inserted by using the Outlook option "Add Holidays".
Outlook is my main calendar and I use the Google calendar just to sync my Android phone,
So I do not want to use the Google Holiday option.

Now I just realized that OGCS did not sync any holiday entries (e.g. easter day, Christmas, ....),

What could be tha cause for?

Christian

**Comment by phw198** [comment]
Are these holidays definitely added into the same Outlook calendar that you are syncing? If they are, do they fall into the period that you are syncing? For annually recurring series, the month must fall in between the sync from and to date.

**Comment by Survival62** [comment]
Hi Paul,

Thanks for your support!

Yes, all holidays are in the same calendar which I use by default and where e.g. all Birthdays are inserted.

Birthdays and general meetings are synced, but not the Holidays.

The Holiday entries I set within Outlook “Add Holidays to the Calendar”.

In “When” I set 7 days in the past and 365 days in the future.

e.g. Easter Sunday this year is on  9th April and it is an entry in my outlook, but not synced, even if it is inside the sync tile window..
Also other holidays are not synced.

I thought that it does not sync holiday entries because I added the holidays somewhen last year (creation date), so I did delete all Holidays in my outlook and add it again. But still it does not sync any Outlook holiday entry.

I also performed a unidirectional “Sync all” for Outlook -> Google.

What could cause it that the holiday entries are not synced?

BR
Christian

**Comment by phw198** [comment]
Hard to tell without [your logfile](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#locating-your-ogcalsynclog-file), but at a guess it might be you have some category filter set which is excluding the Holiday items from sync...?

**Comment by Survival62** [comment]
Hi Paul,

I’m pretty sure that I already checked the categories setting in OGCS and did not found a category “Holiday”.
Today I checked again and found it, but not enabled.
After enabling, all holidays are synchronized.

So it works now.

What wonders me is, that the last logfile was created on 27th, but I synced several times since today 30th.
Or is it only stored with a full sync?

BR
Christian

**Comment by Survival62** [comment]
Issue is solved! Thanks Paul!

**Comment by phw198** [comment]
Thanks for confirming @Survival62 - glad it's working as you need now.

Logging should be created all the time, unless you turned it off in the `Application Behaviour` under Settings. But not to worry...hopefully you won't hit any further issue!
