### ISSUE TITLE
Feature request: Dynamic icon for taskbar notification area

### ISSUE THREAD

**Issue by d-kleine** [phw198/OutlookGoogleCalendarSync#1602]
**Is your feature request related to a problem? Please describe.**
Currently, it's not possible to see if OutlookGoogleCalendarSync synchronizes in the background if you don't have the UI directly opened. The system tray icon in the taskbar notification area remains static, even when actively synchronizing.

**Describe the solution you'd like**
It would be helpful if the system tray icon in the taskbar notification area would change from a static to a dynamic icon, indicating that a task (e.g., synchronization) is running in the background
https://support.microsoft.com/en-us/windows/customize-the-taskbar-notification-area-e159e8d2-9ac5-b2bd-61c5-bb63c1d437c3

**Additional context**
For example, the system tray icon in the taskbar notification area for Avast Antivirus is good here. When it checks files in the background, you can see that from the tray icon changes from a static image to a dynamic image

Some examples how a dynamic system tray icon should like from my pov can be found here:
![This is an image](https://techdows.com/wp-content/uploads/2022/09/Windows-11-new-system-tray-rearrange-icons-and-fluent-tooltips-animations.gif)
and here:
![This is an image](https://static.bandicam.com/how-to/around-mouse/bandicam-icon-taskbar.gif)

Please see here how the system tray icon changes visually.

**Comment by phw198** [comment]
:package: This should now be available with [hotfix v2.10.0.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12139777/v2.10.0.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

This also includes a slight update to the icon with a more modern "G" for the Google.

Let me know how it goes if you try it!

**Comment by d-kleine** [comment]
Just tested, the dynamic icon works perfectly when syncing! 
Many thanks and kudos! 👍
