### ISSUE TITLE
The RPC server is unavailable [0x800706BA]

### ISSUE THREAD

**Issue by daveinhull** [phw198/OutlookGoogleCalendarSync#1604]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.6.0
**Installed or Portable**: Installed

**Problem Description**  
Problem encountered during synchronisation.
The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)

**Steps to Reproduce the Issue**  
1. Not sure, it just happens
2. Have to exit OGCS and restart, then it works for a while and then error again

**Any other information**  
This happened on my laptop for a while now, but worked on my desktop. However, my desktop was an older version (I think 2.9.1.0??), but since updating the software version on my desktop to the same as my laptop, latest version, it errors on both machines now. 

Any help appreciated as I really liek to software and woul dlike to donate.
Thanks
Dave

**Comment by daveinhull** [comment]
Anybody got any thoughts on this, as it is a real pain becuase when I think things have syned I olny find later that they haven't as there is even a warnign provided by the servce that it isn't syncing.

Im not sure but I think it occurs after coming out of sleep/hybinaiton mode.

Please any help would be very much appreciated as I love the app, but as it stands it creates more problems that it benefit.

Dave

**Comment by phw198** [comment]
It normally means that Outlook has been closed in the middle of OGCS trying to sync. I'd need the logfile ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) containing the issue to be able to troubleshoot further though.

**Comment by daveinhull** [comment]
Hi Paul,

Many thanks for getting back to me. I really do like this utility and am wanting to contribute, but as I say it isn’t really useful at the moment, but hope my issue can be resolved.

I think I’ve attached the correct log file, from my desktop. The exact same problem happens on my laptop as well.

I’m sure it is something to do with the PC going to sleep, as it syncs correctly all the time when it is awake, but after recovering from sleep it doesn’t sync on either machine.

I did remember that in the past when I had different versions n my desktop and my laptop, the laptop version would work after recovering from sleep but the desktop version didn’t, now I’ve updated them both the latest version neither work after sleep.

Dave

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

Please make sure the logfile you upload is for the day on which you have had the error following system wake after sleep.

After the initial sync fails, do subsequent syncs work? What do you do to get OGCS syncing again after the error? When the sysem wakes, is Outlook still running? If it is, might it be busy syncing email etc?

Thanks!

**Comment by daveinhull** [comment]
Hi Paul,

I'm in GitHub typing this, but how to I add or upload a file?

Once it fails I have to quit it and restart it, then it works.

I'm not sure if Outlook would be running after it wakes as I guess it would be dependent on whether it was running when it went to sleep. Do your mean loaded or running or doing something? If it was loaded then it would be restored when the PC comes out of sleep.

It might be loaded in background and OGCS might be synbcing to it I guess as well before it goes to sleep.

I don't think Outlook would be syncing (but it might), but then if it doesn't get restred because it wasn't loaded when it went to sleep, then it certainly wouldn't be syncing, but OGCS always fails after it wakes, so I guess that itsn't a factor?
 
Thanks
Dave

**Comment by daveinhull** [comment]
P.S. the PC has just woken from sleep, not sure if outlook was running or not becuase I loaded Outlook to get your message. I also went to OGCS and the sync page showed the last time it had synced correctly 31/3/23. So I hit Start Sync and got this error message:
Problem encountered during synchronisation.
Value cannot be null. Parameter name: pNativeData

Dave

**Comment by phw198** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by daveinhull** [comment]
Hi Paul,

Here is todays log showing the error. History:
PC came out of sleep
Outlook was NOT running
Opened OGCS and hit sync
Got the same error message
Saved log and attached below

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11200079/OGcalsync.log)

Thanks
Dave

**Comment by phw198** [comment]
I believe your logfile is from v2.9.6? From testing on v2.9.7, this issue should be resolved already :slightly_smiling_face: 

:arrow_double_up: Upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`.
