### ISSUE TITLE
Avast reports exe file as infected. v2.9.6.0

### ISSUE THREAD

**Issue by davethegeo** [phw198/OutlookGoogleCalendarSync#1609]
**OGCS Version**: v2.9.6.0 Alpha
**Edition**: Installed
**Sync Direction**: O->G 

**Bug Description**  
Avast antivirus reports OUtlookGoogleCalendarSync.exe as infected with IDP.HEUR.26

The detection of this "infection" can be repeated reliably.

OGCS still working. Keep up the good work.

PS. I'm a donater/subscriber.

![ogcs](https://user-images.githubusercontent.com/104935364/222368132-8af55507-f6ea-47a4-87fc-6c3a547e4e75.JPG)

**Comment by phw198** [comment]
Yep, it's that time of year again :roll_eyes: 

[Further information in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#anti-virus-false-positives).

Would appreciate your help [reporting the false positive to Avast](https://www.avast.com/false-positive-file-form.php).

**Comment by davethegeo** [comment]
Thanks for that info. I reported the false +ve to Avast and they seem to
have got the message as no more alerts from them.
Still a fan of OGCS. Keep up the good work.
