### ISSUE TITLE
Significant slowdown of keyboard input on startup

### ISSUE THREAD

**Issue by JpTiger** [phw198/OutlookGoogleCalendarSync#1610]
**OGCS Version**: v2.9.0.0 
**Installed or Portable**: Installed

**Problem Description**  
The program seems to sometimes cause significant slowdown in processing keyboard input on startup. This has been observed on two different machines, including a brand new i7-13th gen 16GB laptop. Is anyone else seeing this?

**Steps to Reproduce the Issue**  
1. Install and configure OGCS on machine running windows 10 or 11.

**Comment by phw198** [comment]
Is there [anything here in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-is-outlook-freezingbecoming-unresponsive-when-ogcs-syncs) that is applicable or helps?

When does the slow down occur? 
When you open OGCS even if the computer has been on for a while? 
When you perform the first sync? Any/all syncs? 
Do you have OGCS set to start on system startup? Have you tried delayed the start of OGCS?
Is Outlook already open when OGCS opens? When OGCS syncs?

**Comment by JpTiger** [comment]
The slowdown seems to have improved significantly recently and if nobody else is experiencing it, maybe it's not OGCS after all. But just in case it is and someone else is facing the same issue: 

-The (keyboard only) slowdown occurs when Outlook is first opened, while OGCS is already reining
- I do have OGCS running on startup
- Outlook is not already open, I have OGCS set to open automatically and Outlook only opens manually

Since things seem to have spontaneously improved, I'm afraid there's not much I can do to reproduce. If nobody else is having this issue, I think we can close this (and someone else can reopen if it reappears).

**Comment by phw198** [comment]
When you open Outlook, OGCS won't immediately do anything - not until it is scheduled to sync, as which point it would connect to Outlook.

Therefore, I don't think the issue was OGCS if the slow down would occur when Outlook was opened. Maybe your system was just doing some virus scanning or Outlook syncing your mailbox?? Anyway, as long as the issue has gone/improved!

Thanks for the update.
