### ISSUE TITLE
ServerFault when deleting annual birthday series in Outlook [0x80010105]

### ISSUE THREAD

**Issue by petbyuser** [phw198/OutlookGoogleCalendarSync#1611]
**OGCS Version**: v2.9.6.0  
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
Error at sync Process: Deleted appointment failed to remove.
Error of Server HRESULT: 0x80010105(RPC_E_Serverfault)

**Steps to Reproduce the Issue**  
1. Run sync.

File will be uploded via GoogleSync.

**Comment by phw198** [comment]
Seems there is a specific problem with the birthday on 27-Dec-1960 - can you try deleting this from Outlook manually yourself?

**Comment by petbyuser** [comment]
Good Morning Paul,

yes i have deletet the Birthday on 27 Dec 1960 and start a manual sync. This sync works fine, but the next automatic sync show me an 0x80010105 Error:

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

If the next error is also for a deletion, then I suggest you keep deleting them manually until there are no more errors of that nature?

**Comment by petbyuser** [comment]
![sync-error](https://user-images.githubusercontent.com/127386195/229358078-816faa52-7e68-40fc-b091-71a30d5de29d.jpg)

**Comment by petbyuser** [comment]
Hello Paul,
current I don`t see hte Appointment update failed message. But on the first sync I have ["Precondition Failed [412]" error on every sync]"(https://github.com/phw198/OutlookGoogleCalendarSync/issues/528#top) 
My Version is 2.9.6.0. So I stopp the Sync and restart it. -> No Error was seen.

**Comment by phw198** [comment]
I can't really troubleshoot without the logfile - screenshots aren't enough. 

You say on the _first_ sync you had "Precondition Failed" errors - but they don't happen any more?
You stop and restart OGCS and then no errors?

I'm not really sure what I'm meant to be troubleshooting...

RPC_E_SERVERFAULT basically means you have an unhappy Outlook - I'd start with running an [Office Repair](https://support.microsoft.com/en-us/office/repair-an-office-application-7821d4b6-7c1d-4205-aa0e-a6b40c5bb88b).

Sometimes, there may be a particular calendar item that is problematic, or your Outlook .pst or .ost files might have grown too large. An .ost file can be [deleted safely](https://learn.microsoft.com/en-us/outlook/troubleshoot/data-files/errors-have-been-detected-in-.ost-file), as it is just an offline cache of your online account and it will automatically rebuild. For a .pst, the [Microsoft Inbox Repair tool](https://learn.microsoft.com/en-us/outlook/troubleshoot/data-files/how-to-repair-personal-folder-file) can be run.

**Comment by petbyuser** [comment]
I can't really troubleshoot without the logfile - screenshots aren't enough. -> I will uplod t.

You say on the first sync you had "Precondition Failed" errors - but they don't happen any more? Yes, I see it one time.
You stop and restart OGCS and then no errors? No only the sync in the OGCS-Window

I'm not really sure what I'm meant to be troubleshooting... OK, I will have a look on my outlook first, see below.

RPC_E_SERVERFAULT basically means you have an unhappy Outlook - I'd start with running an Office Repair <https://support.microsoft.com/en-us/office/repair-an-office-application-7821d4b6-7c1d-4205-aa0e-a6b40c5bb88b> .

Sometimes, there may be a particular calendar item that is problematic, or your Outlook .pst or .ost files might have grown too large. An .ost file can be deleted safely <https://learn.microsoft.com/en-us/outlook/troubleshoot/data-files/errors-have-been-detected-in-.ost-file> , as it is just an offline cache of your online account and it will automatically rebuild. For a .pst, the Microsoft Inbox Repair tool <https://learn.microsoft.com/en-us/outlook/troubleshoot/data-files/how-to-repair-personal-folder-file>  can be run.

**Comment by petbyuser** [comment]
[OGcalsync02042023.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11132645/OGcalsync02042023.log)

**Comment by phw198** [comment]
There are no errors in the log file you have provided, so I'm still none the wiser...
