### ISSUE TITLE
Unable to install OGCS after migration to Office365 (using Outlook 2019)

### ISSUE THREAD

**Issue by lbinokc** [phw198/OutlookGoogleCalendarSync#1612]
UNABLE TO GENERATE ogcalsync.log file since I can't install the software.

**Comment by phw198** [comment]
Very unlikely to have failed to install, and that wouldn't be affected by migrating to O365. Here are the instructions on [how to locate the logfile](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#locating-your-ogcalsynclog-file).
