### ISSUE TITLE
Copy and paste Outlook entries will be deleted

### ISSUE THREAD

**Issue by Survival62** [phw198/OutlookGoogleCalendarSync#1613]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0  
**Edition**: Installed  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
I had a meeting entry on Friday 10th March. It was entered in Outlook and synced with Google.
It was a on-site service meeting and now need a second meeting on Wed. 15th.
Today I copied the meeting from Friday (left the old meeting placed) and placed it to Wednesday 15th.
I did not deleted the meeting from 10th as I just want to keep it for possible later checks.
First OGCS ask me about if I want to delete the meeting from 10th which I first answered with yes.
Then I put it back in for last Friday 10th..
Now OGCS ask me if I want to delete the new entry from 15th which I denied.
So now both entries are only in my Outlook and not synced to the google calendar.

Now I entered both again as new entry and it is synced.

I sync 7 days back and 365 days in front.

Could it be a bug or is it a wrong setting at my side?

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by Survival62** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/10957520/OGcalsync.log)

I tried to reproduce the issue and created in Outlook a "Test meeting" for last week Thursday.
Then I synced and it showed up in google calendar.
Then I copied the meeting to this week Tuesday.
Then I synced again.
OCGS ask me if I want to delete the Meeting from last week and I click on "no".
Result is that the old meeting stay, but the copied meeting will not be synced and does not show up in the google calendar.
If I resync again, it again ask me if I want to delete the item from last week.

**Comment by Survival62** [comment]
Sorry for all this messages, but I just see that the issue was already discussed in 2020/21.
But I'm not a power user with VBA Programming.
As the issue is known, is there a OGCS version which cover a fix for this?

One adds about my use of OGCS, I always start OGCS with my PC and have it running while I create calendar entries.

**Comment by Theobug** [comment]
I was just about to log this same bug but now I see it's already reported.
I'm also using the installed version 2.9.0.0
Yes, would be good to know if a fix is planned in the next version as it's a pain having to create fresh entries instead of simple copy/paste to a new date.

**Comment by phw198** [comment]
@Survival62 A log file only showing ERROR log lines and above is of very little use.

In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
    1. Copy and paste and previously synced item that still sits within the sync window date range
    2. Run a sync
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

However, copy and paste is [documented in Known Limitations](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#outlook-appointment-copy--paste), so unless there's a bug in the copy and paste detection, it's very unlikely anything further that can be done.
