### ISSUE TITLE
Option to run minimized

### ISSUE THREAD

**Issue by richj** [phw198/OutlookGoogleCalendarSync#1614]
Not a problem

I would like to have an checkbook option in the settings tag that allows the application to be minimized when running (starts hidden, runs hidden)

![image](https://user-images.githubusercontent.com/669695/225405427-78756f77-d1a2-4c9a-a808-e56bc29510d8.png)

**Comment by Irish-Coder69** [comment]
Hello;
Which version of the program do you have?

**Comment by richj** [comment]
sorry, should have included that

2.1.9.0

**Comment by Irish-Coder69** [comment]
That's Ok. There is a newer version of the program.  2.9.6.0 Alpha Version, Which I am Using and it runs in the background even if I click on the Close button. Just a Suggestion for you.

**Comment by richj** [comment]
I'll give it a try.

Thanks

**Comment by phw198** [comment]
That functionality is already provided and you appear to already have it set to do that - start in tray and minimise to tray.

**Comment by richj** [comment]
That seems to be how it is working now - thank you.  Don't know what I did in particular, but thank you.
