### ISSUE TITLE
Option to "remember" items to not delete?

### ISSUE THREAD

**Issue by cbarina** [phw198/OutlookGoogleCalendarSync#1616]
**Is your feature request related to a problem? Please describe.**
I sometimes have sync issues (I'm not sure why) when doing a full Outlook/Google sync. In particular, sometimes events from the previous day (which indeed happened in real life) then get flagged for deletion in a sync on the next day (I use the default sync setting of yesterday to X days in the future). As I do use my calendars to track work/show what I'm doing to clients (and to manage appointment requests on the Outlook calendar), I can't have these inadvertently disappear, so I normally click "do not delete" when the popup appears for these items. The popup continues to appear for the rest of the day, though, which is an ongoing interruption and annoyance.

**Describe the solution you'd like**
Would love a way to "remember" when I say "don't delete" the first time it pops up and doesn't ask me again for that item going forward.

**Describe alternatives you've considered**
I've tried fixing the sync issues by pushing everything first from Outlook to Google, downloading and trying the latest alpha version of OGCS, and even just a one-way sync. None of them quite for for me in terms of managing both availability in Outlook and accountability to clients.

**Additional context**
Really bad screenshot mockup:
![image](https://user-images.githubusercontent.com/7785375/226577439-dc7bae1d-6197-4595-81b7-0d394295b5fe.png)

**Comment by elfstrob** [comment]
YAS!!!  I get 20 of these a sync now, and it halts sync until I respond.  Another option/enhancement would be to queue these messages in a separate thread and continue processing in the background.

**Comment by phw198** [comment]
Duplicate of #1607 - and [same response](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1607#issuecomment-1483899624). If the [guidance to resolve the popups](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) doesn't work, then it need investigating more deeply...

**Comment by cbarina** [comment]
As noted in #1623 - this was my actual set of issues causing weird deletion requests; configured properly, this feature isn't as important to me and thus proves the point made in the [response given](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1607#issuecomment-1483899624) in #1607 😳
