### ISSUE TITLE
Sync multiple calendars to Outlook

### ISSUE THREAD

**Issue by daggy72** [phw198/OutlookGoogleCalendarSync#1617]
I use multiple Google Accounts/Calendars and one Outlook Calendar. I would love to be able to sync the various Google Calendars (as private events) into my one Outlook calendar so my colleagues can see my availability. The Outlook calendar should then be synced with one of the Google Calendars. 

For each Google Calendar an optional prefix and colourcoding could be added to each calendar entry to keep it organised: 
Google Calendar 1 : [work]
Google Calendar 2: [private]
Google Calendar 3: [association]

**Comment by phw198** [comment]
Sounds good! Why can't you do this already? See the wiki on [multiple calendar syncing](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars)...

**Comment by jacktose** [comment]
I had the same question. Probably because @daggy72 and I are on beta, currently 2.9.0.0, and that feature was added in 2.9.3.
