### ISSUE TITLE
Google Cloud email - Adding New Service for all App Engine Projects

### ISSUE THREAD

**Issue by TheJacksonian** [phw198/OutlookGoogleCalendarSync#1618]
**Are you already using OGCS?**
Yes. 2.9.6.0

**Describe the question you have**
I just got this email from Google (looks legit) and it mentions OutlookSync, so just wanted to pass it on, making sure there's nothing we need to do?

Thanks.

-----
We are writing to let you know that we will activate the service appenginereporting.googleapis.com on all App Engine projects on April 17, 2023.

What do you need to know?
As we continue to update the underlying infrastructure for App Engine, we are improving our integration with certain GCP shared services (e.g. Billing, Quota Management, etc.). Because of this integration, we must enable a service on all App Engine projects to properly tie-in to these shared services.

This new service will be added as part of ongoing infrastructure modernization, and will be necessary to support various aspects of metrics reporting and quotas. We are using a new service to avoid unintended side effects related to the existing App Engine services (appengine.googleapis.com and appengineflex.googleapis.com).

The new [Service Usage API](https://notifications.google.com/g/p/APdRdFyBZZDF9NJ0tFkv1XfxHhXRnpGPREpg7Lm1GnI4VVWkcm7hJAm8uVDG6TDz-2QESDqzyjVAoRwRO8XPIv7gMX55l3hbf4lACmduwxdFi55ByR-mPlU3SaWQbNWQ5teDnrpYPnbdWDjZ-OwdI8TswnCkfykW-cU6Yi6o2BY8MgBI8absru6fOH4SBdR5nvkGWVdPEUow4SnKwA-PnJFc3YmVxg) will have no impact on existing apps, no impact on billing, and has no external API. The only change customers will see is appenginereporting.googleapis.com added to the list of enabled services in their [Cloud Console](https://notifications.google.com/g/p/APdRdFxNpu8H0_wBrBByNvU3YcqECwUqkK-Mxg6d84qcQOhAoOgbhFfefnQhGe0D4p3WKhyD7qZs3-WW8lODBNAfeF0-plC5KYx92QHYcdHcC1Py-mUxrfDF6Bbj_veEpNaLzvThDJL9hfhiZzc8mqtWn-GRL5WpGWD8hUL1D780MX00S8Lt5ljkSnTNKP6N1g_4qXNalMykmKXng0ozSwk) and when running gcloud services list.

What do you need to do?
No action is required on your part. However, we recommend that you don’t disable appenginereporting.googleapis.com service while still using App Engine. If you disable this service, it might result in some issues with certain activities (like viewing quotas in your Cloud Console).

Your impacted projects are below:

[OutlookSync (outlooksync-148901)]

_//Outlook sync URL redacted: Happy to provide privately if required/helps.//_

Thanks for choosing App Engine._
____

**Comment by phw198** [comment]
Hi @TheJacksonian and thanks for raising this. However, I can't find any such notification from Google for me and OGCS shouldn't be appengine anyway - it's pretty much just the Calendar APIs.

Had you set up your own API keys for OGCS? Or how/why did you think your OutlookSync project is related to OGCS?

Interesting that Service Usage API though - that must be fairly new, as I'm pretty sure it was never possible before to programmatically query quota usage!

**Comment by TheJacksonian** [comment]
I think I did set up my own API Key for OGCS as early on I was hitting the quota limit. so I setup the Google Oauth API in the app, I bumbled my way through it for sure, but I got it working :)

No worries, just thought I'd pass it along, just in case!

Thanks again for a super handy tool!! :)
