### ISSUE TITLE
Paid my 10 quid but can't remove splash screen or suppress "spread the word" popups

### ISSUE THREAD

**Issue by quistuipater** [phw198/OutlookGoogleCalendarSync#1622]
**OGCS Version**: v2.9.0.)4  
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Paid my 10 quid but can't remove splash screen or suppress "spread the word" popups

**Steps to Reproduce the Issue**  
Always happens at startup

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11104148/OGcalsync.log)

**Comment by phw198** [comment]
Hi @quistuipater, thanks for the donation, but I can't see any evidence of you following the instructions that were emailed to you at 19:00 BST - you need to perform a sync after restarting OGCS...
