### ISSUE TITLE
Any guidance on how to start a "clean" sync (full uninstall, then clean install)?

### ISSUE THREAD

**Issue by cbarina** [phw198/OutlookGoogleCalendarSync#1623]
**Are you already using OGCS?**
2.9.0.0

**Describe the question you have**
I am the victim of my own creativity and seem to have some issues syncing between outlook and google. I wanted to take a "clean" approach to see if that fixes my problems. Is there a way to remove all config settings and history of syncs from OGCS, then start over with a "fresh" sync approach?

**Comment by phw198** [comment]
See the [guidance here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#removing-all-ogcs-metadata-from-your-calendars) - also the section below for deleting synced items, in case that might helpful (but probably isn't if you had two-way sync on and/or merged items with previously existing).

**Comment by cbarina** [comment]
Thanks - needed to get rid of the metadata due to some very confused syncing and finally got it working properly again!

A few tips for others: 

- when doing two-way sync from outlook to google, if you only sync items you've accepted, and someone changes the date or time in outlook, and the sync happens before you respond, you'll get deletion prompts (if you confirm your deletions) which can be quite confusing. 
- if you sync items from google to outlook, and assign them a category/color in outlook, make sure to NOT exclude that category in the sync. The items will initially be created in outlook as expected, then when syncing later you will be prompted to delete them from google (I think), which causes great consternation.

**Comment by phw198** [comment]
Thanks for those tips - especially the first one....I'll have a think if there's a better way for the sync to detect and handle that...
