### ISSUE TITLE
Backward date

### ISSUE THREAD

**Issue by rickfry** [phw198/OutlookGoogleCalendarSync#1625]
**Is your feature request related to a problem? Please describe.**
I can only bring in historic appointments for the last 365 days. 
**Describe the solution you'd like**
Ideally unlimited but 5 years 

**Describe alternatives you've considered**
I cant find an alternative product that works as well as this so I think I would put up with this small limitiation
**Additional context**

**Comment by phw198** [comment]
The limitation is [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-cant-i-sync-more-than-1-year-past-or-future) and won't be changing. The limitation is removed if you use your own API keys, but setting that up  is beyond the scope and support of this project.

**Comment by rickfry** [comment]
OK thank youSent from Outlook for Android
