### ISSUE TITLE
Outlook program opens during startup in full screen when starting computer with OGCS. 

### ISSUE THREAD

**Issue by HoundDogRock** [phw198/OutlookGoogleCalendarSync#1627]
**OGCS Version**: v2.9.0.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Outlook keeps opening in the task bar and in full screen each time the computer restarts. 
I haven't set it to start with the computer, so I suspect that OGCS is using it to gather data. 
Would be nice if Outlook would not be visible at all. Am I the only one with this problem? 

**Steps to Reproduce the Issue**  
1. Start the computer (with OGCS)
**2. Outlook opens in full screen and in task bar**
3. OGCS starts but stays minimized in system tray
4. Sync starts

**Any other information**  
Using Windows 10 64bit. 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11146479/OGcalsync.log)

**Comment by phw198** [comment]
The only sign that Outook is being accessed by OGCS if Outlook is not already running should be this:
![image](https://user-images.githubusercontent.com/11843015/230779311-e84d301b-cbd3-4213-9552-081e526a008c.png)

I see you are getting the Outlook security prompts - [worth reading through here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) and seeing if you can get rid of them in case that helps.

**Comment by HoundDogRock** [comment]
Hi Paul,

Thank you for the reply.

I had got rid of the security prompts after already having followed the 
instructions from the link. However, Outlook opens after having followed 
those instructions when I start my computer.
Strangely enough, sporadically, so not each time that I start my computer.

Kind regards.

**Comment by phw198** [comment]
Have you configured OGCS to start after a delay? Loading it too quickly can cause the security prompts to return if the latest virus definitions have not had a chance to download; I had not heard this being related to opening Outlook (and certainly not in full screen), but it would be worth experimenting with a delay if the behaviour is intermittent...

**Comment by HoundDogRock** [comment]
Hi!

It's been a long time since Outlook started up together with OGCS.
So, possibly the one minute delay has solved the problem.

Thank you for your help!

Kind regards,
Dan
