### ISSUE TITLE
Syncronisation Options - Privacy

### ISSUE THREAD

**Issue by Billpherry** [phw198/OutlookGoogleCalendarSync#1631]
**Are you already using OGCS?**

2.9.7.0

**Describe the question you have**

I have a profile setup to sync Outlook <>Google in both directions and have noticed that some of my events that were created in Google are not setting privacy as per my setup in Syncronisation Options ( I wish to set a privacy of 'Private' ) on anything being synced so that my personal events are not viewable in my work Outlook calendar.

![image](https://user-images.githubusercontent.com/126982946/231696537-354a06cb-54e4-4c0c-9283-d05b23ca5332.png)

This seems to work for any event that I manually create in Google Calendar but I notice that events created by other sources ( in this case Zwift ) do not sync with my preferred privacy setting. I'm not sure if this is a bug or if expected behaviour, or indeed if it may not have been considered?

**Comment by phw198** [comment]
If you want the items to be private in Outlook, then you just need to change the setting to "for all items synced to Outlook" (not Google as you currently have it).

**Comment by Billpherry** [comment]
Thank you so much, I can't believe I missed that!
