### ISSUE TITLE
No sync of copied entries in android. Adding .ogcs ad extension to email (e.g. ....@gmail.com.ogcs)

### ISSUE THREAD

**Issue by Survival62** [phw198/OutlookGoogleCalendarSync#1633]
**OGCS Version**: v2.9.0.0
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
1. create an entry in outlook (2016) and invite other people.
2. entry appears in google/Android.
3. use the entry in Android to copy it to a new entry with different date/time
(my Samsung calendar app propose existing calendar entries as template for the new entry.
4. after sync, I get a email from Gmail, that the email addresses are not known.
This is obvious as the email address of the attendees get the extension .ogcs. (e.g. john.doe@google.com.ogcs)

Result is that the entry is not synced with my Outlook calendar. 

Also it uses my @gmail.com address as attendee, but I usually use my own email address (own domain) for the outlook calendar.
So (whyever) my address used in that entry was : ......@gmail.com.ogcs

The non delivery reply from gmail was:
*************************
DNS Error: DNS type 'mx' lookup of gmail.com.ogcs responded with code NXDOMAIN Domain name not found: gmail.com.ogcs Learn more at https://support.google.com/mail/?p=BadRcptDomain

--------- Forwarded message ----------
From: [?????@gmail.com](mailto:?????@gmail.com)
To: ?????@gmail.com.ogcs, Sabine<?????@domain.de.ogcs>
Cc: 
Bcc: 
Date: Sat, 15 Apr 2023 07:23:25 +0000
Subject: Einladung: Fusspflege - Fr 26. Mai 2023 09:00 - 10:00 (MESZ) (?????@gmail.com.ogcs)
----- Message truncated -----
*************************
Additionally to that, the copy of a entry and change the date time will not be synced with outlook. 

**Steps to Reproduce the Issue**  
see above

**Any other information**  
no logfile was generated when the behaviour was seen.

After reading another thread here about this "cloaking".
I do not use any address in my google account.
Invitations should be send by outlook calendar email address. My @gmail.com address I generally do not use at all.

I'm scared about that this is not possible as this needs an interaction with my outlook email.

-

**Comment by phw198** [comment]
Have a [read through the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-am-i-getting-undeliverable-notifications-from-google-for-recipients-ogcs) - most of your concerns are covered there.

I suspect when you are copying a synced item in Google on your Samsung phone, it is copying special properties that OGCS uses to know it is synced. If these are copied, then it will cause problems with the sync behaviour - there is nothing I can do about this, except suggest you do not copy items on your mobile. 

Note, the Google calendar web interface will not copy the OGCS properties in a calendar event, so this is likely a bug in Samsung's app. You could also [try the Google calendar app](https://play.google.com/store/apps/details?id=com.google.android.calendar) on your phone to see if that works better.
