### ISSUE TITLE
O2003: O->G sync incorrectly compares events when creating and deleting

### ISSUE THREAD

**Issue by appdevdoug** [phw198/OutlookGoogleCalendarSync#1634]
**OGCS Version**: v2.9.7-alpha
**Edition**: Installed 
**Sync Direction**: O->G

**Bug Description**  
There are two bugs.

First, after entering individual events in Outlook and syncing, the information sync'd to Google is incorrect after a few syncs.

Second, I have never been able to successfully sync a recurring event.  OGCS always crashes when attempting to sent a recurring event.

**Steps to Reproduce the Issue**  
1.  In Outlook create appointment with description "Test 1" for 6/8/2023 10:00-10:30am
2.  Force OGCS sync.
3.  Check log displayed on sync tab and information displayed appears correct (one item created on Google side).  Verified the same in Google.
4. In Outlook create appointment with description "Test 2" for 4/19/2023 1:30-2:00am
5. Force OGCS sync.
6. Check log displayed on sync tab and information displayed appears correct (one item created on Google side).  Verified the same in Google.
7. In Outlook create appointment with description "Test 3" for 5/15/2023 10:00-10:30am
8. Force OGCS sync.
9. Check log displayed on sync tab.  It displays odd information.  It indicates that Test 2 was created not Test 3 and then it indicates a comparison was then performed and that Test 2 changed to the information of Test 3 and so it made that change on the Google side.  Checking on Google shows the correct end result.
10. In Outlook create appointment with description "Test 4" for 4/20/2023 1:30-2:00am
11. For OGCS sync.
12. Check log displayed on sync tab.  It again displays odd information.  It indicates that Test 2 was created not Test4 and then it indicates a comparison was then performed and that Test 2 changed to the information of Test 4 and so it made that change on the Google side.  Again checking on the Google side shows the correct end result.
13. In Outlook delete appointment with description "Test 4".
14. Force OGCS sync.
15. Test 2 is deleted not Test 4!
16. In Outlook delete appointment with description "Test 2".
17. Force OGCS sync.
18. Test 4 is deleted.

I did try even more attempts and in most cases after I do enough of these creation and deletions it seems like what I have in Outlook and what is shown in Google are 100% different depending on the order I perform the steps.

19. In Outlook create appointment with description "Rec Test 1" for 4/20/2023 1:30-2:00am recurring weekly for 10 times
20. Force OGCS sync.
21. Sync begins but once it gets to the new appointment OGCS crashes

This happens every time.

**Any other information**  

I am running Outlook 2003.

:paperclip: Attach your `OGcalsync.log` file.

**Comment by appdevdoug** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11258370/OGcalsync.log)

**Comment by phw198** [comment]
Outlook 2003! I wasn't sure I had many users still on that :slightly_smiling_face: 

I've fixed the recurring series issue, but still investigating the mixing up of calendar items...

**Comment by appdevdoug** [comment]
Yes.  My father is using it actually.  It is what he is familiar with so we just keep him on it :)

So glad you already figured out the recurring series issue and look forward to what you find on the calendar item mix ups.

Thanks!

**Comment by phw198** [comment]
Well that took me deeper back into Outlook 2003 than I would normally care to go, but I've cracked it - and I think it's been broken for a looong time!

:package: Please apply [hotfix v2.9.7.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11364814/v2.9.7.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know how it goes.

**Comment by appdevdoug** [comment]
Awesome!  I need to get remote access to my Dad's computer to test.  He is currently not home to turn it out so it might take a few days before I can confirm the patch works.

Thanks!

**Comment by appdevdoug** [comment]
Okay.  I was able to connect into his computer this afternoon and applied the patch.  Everything appears to be syncing correctly now.  I was even able to turn on bi-directional sync and it works properly now as well.  Thanks so much!
