### ISSUE TITLE
Multiple calendar sync with different settings

### ISSUE THREAD

**Issue by jedison** [phw198/OutlookGoogleCalendarSync#1638]
I have a need to sync multiple calendars but with different settings.
For example, one-way default Outlook calendar to a particular Google calendar.
Bi-directional between a separate Outlook calendar and a different Google calendar.

Could OGCS be set up to allow multiple sync profiles with different parameters?
Would it be possible to run multiple instances of OGCS?
Maybe the OGCS UI could be used to create a config file and then start it up from the command line.
Or start OGCS exe with a different profile in the same manner as Outlook itself.

**Comment by phw198** [comment]
All [as documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars) - enjoy!

**Comment by jedison** [comment]
Thanks, I wait with impatience for the Beta release of 2.9.3 or above

**Comment by phw198** [comment]
I may well be releasing the next Beta in 3-4 months, but I wouldn't be too worried with the alpha naming - it's still pretty stable :slightly_smiling_face:
