### ISSUE TITLE
Sync takes ages after WIN 11 upgrade

### ISSUE THREAD

**Issue by jochenrosen** [phw198/OutlookGoogleCalendarSync#1639]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0.0 
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
I am using OGCS since many years, always flawless under WIN10 with 1 Outloook calendar (local) and 1 gmail account, took always some minutes to complete. Needed to buy a new notebook (with mega performance ;-)  WIN 11 latest patches and updates applied. Both OGCS versions (alpha, which I usually use(d) but also beta) show now the problem that the process step "synching Outlook to google" takes 2,5 hours to show copied entries in the sync window, before that nothing happens. I would have found that potentially acceptable for the first sync but it is always like that and does not speed up even if only 1 calendar entry is added. I have approx 900 google/outlook calendar entries.
CPU/RAM/file usage of OGCS is neglectable all OK.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11358843/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
as sync ends after 3 hours there is nothing in debug file, which I have not checked yet
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
So it looks like you are syncing an Outlook calendar that is only locally on your computer (not an Exchange calendar)? 

1. How did you migrate your calendar onto the new Notebook? 
2. The first time you synced with OGCS on the new Notebook, did OGCS "reclaim" all the Google items?
3. Do you still have the old computer and does OGCS still run fine on that with the same number of calendar items? Or is that slow too now as well?

Have you tried the [Inbox Repair Tool](https://learn.microsoft.com/en-us/outlook/troubleshoot/data-files/how-to-repair-personal-folder-file) to see if there's a problem with your PST file on the new Notebook?
