### ISSUE TITLE
New Outlook for Windows does not provide COM add-in interoperability: OGCS won't work

### ISSUE THREAD

**Issue by giladgressel** [phw198/OutlookGoogleCalendarSync#1640]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
When I try to use OGCS with the new version of outlook (in preview mode) it doesnt' work. It just hangs when I run it. It appears to be launched regular outlook (I see a small notification in my tray that a service is using outlook). It's similar behavior to when I try to launch OGCS _before_ I open outlook (that has never worked for me, I always have to have outlook open first).

**Steps to Reproduce the Issue**  
1. Make your outlook preview the new outlook
1. Try to use OGCS and it wont' work.

**Any other information**  

As I said it's the same behavior I get when I try to launch OGSC without having outlook open, it tries to launch outlook for me, but never really works. So perhaps that is the issue? However, I get 2 outlook icons in my tray now - one with the new outlook and then the old outlook as well. So I think perhaps the new outlook isn't supported yet?

thanks!

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach yourOGcalsync.log` file.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11366041/OGcalsync.log)

**Comment by phw198** [comment]
The new [Outlook for Windows doesn't support COM integrations](https://support.microsoft.com/en-gb/office/getting-started-with-the-new-outlook-for-windows-656bb8d9-5a60-49b2-a98b-ba7822bc7627), so OGCS will not work with that version.

It's not yet clear whether it will once out of preview, but given it doesn't even have any offline mode yet, it clearly has a long way to go...

**Comment by giladgressel** [comment]
oh ... I see. Thank you for the explanation! Good to know. Literally means I will never use the new office.

**Comment by abhasin505** [comment]
@phw198 does that mean that you don't plan to support the new version of Outlook once it's past preview?

**Comment by phw198** [comment]
@abhasin505 Unless you have knowledge of the MS roadmap and its provision of COM inteoperability once out of Preview, then it's impossible to say. It's  not a decision I'm taking as to whether I make OGCS support it or not - if Microsoft do not provide the ability to integrate with the New Outlook, then there's nothing I, or any of the other thousands of developers, can do about it.

However, it's _extremely_ unlikely they continue to not provide COM integration once Outlook is Generally Available, as they wouldn't even be able to integrate their own products like Teams.

**Comment by abhasin505** [comment]
That makes total sense.  Thanks for your response!

**Comment by phw198** [comment]
As reported on #1365, returning to a previous version of Outlook, having already tried the New Outlook, can result in the error message "Outlook has exhausted all shared resources".

The resolution to this is [option 4 from here](https://www.linkedin.com/pulse/how-fix-microsoft-outlook-error-out-memory-system-/):-

### Reduce Memory Cache Size for Each PST File
1. Close Outlook and press `Windows + R` to open the Run dialog box.
1. Type `regedit` and press the Enter key. This will open the Registry Editor window.
1. Navigate to HKEY_CURRENT_USER> Software> Microsoft> Office> XX.X> Outlook> PST.
1. Right-click on the blank area and choose New > `DWORD (32-Bit)`.
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/37e1b0e8-e5d8-48af-9d5c-c44fbaa75614)

1. Rename the key as `UseLegacyCacheSize` and change the value to `1`.
1. Save it and then close the Registry Editor.
1. Restart the system for changes to take effect.

**Comment by heimbergj** [comment]
I saw this is closed. However is there an update if the new version does support it meanwhile? I don't feel like to create a new issue for that. 
I guess the new office isn't preview anymore?

**Comment by phw198** [comment]
I have suspected for a while that Microsoft have no intention of continuing support of COM add-ins, and this is [now officially confirmed](https://techcommunity.microsoft.com/t5/outlook-blog/add-ins-in-the-new-outlook-for-windows/ba-p/3954388).

OGCS would therefore require a significant redevelopment to work with JS and/or Graphi APIs to retrieve Outlook appointments, instead of the locally cached appointments via COM.

**Comment by KrisadaFantasy** [comment]
[Offline support for new Outlook](https://www.microsoft.com/en/microsoft-365/roadmap?filters=&searchterms=178030) start roll out this month (June 2024). Will it make thing easier for OGCS or new Graph API will have no use for any Outlook client altogether?

**Comment by phw198** [comment]
My understanding of that, unfortunately, is it just increases the functionality of the native product (eg moving and deleting emails manually in the client) - not that it alters the methods of programmatic access at all.

As you suspected, the new Graph API won't have need or make use of the New Outlook client - it'll function in much the same way as interfacing with the Google calendar does.

**Comment by phw198** [comment]
For early development builds of a version that doesn't require the Outlook client to sync, please see:-
- #1881
