### ISSUE TITLE
Splash Screen - Donated but still showing

### ISSUE THREAD

**Issue by Max6993109** [phw198/OutlookGoogleCalendarSync#1643]
Hello, 

I donated, but still cannot take off the splash screen. In the receipt, under "Purpose" it shows the correct email account.  However, I believe I made the mistake of putting another email address under the "Donation from", so there might be some confusion.  Can you help?

**Comment by phw198** [comment]
Hi @Max6993109 and thanks for the donation!

You should have received an email to both addresses with details of the steps to hide the splash screen - let me know if you need this resending. 

From what I can tell, the donation was all registered OK and the Hide Splash Screen check box should be available to you...

**Comment by Max6993109** [comment]
Thanks!  I was able to take it off.  Appreciate the quick response.
