### ISSUE TITLE
Switch from Beta to Alpha causes Donate buttons to return

### ISSUE THREAD

**Issue by jedison** [phw198/OutlookGoogleCalendarSync#1644]
**OGCS Version**: v2.9.7-Alpha
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
I donated to OGCS some time ago and the splash screen and donate buttons disappeared.
I just upgraded to 2.9.7-Alpha and the donate buttons (when adding or renaming a Profile, on the About and Socialise tabs) have returned.

**Steps to Reproduce the Issue**  
1. Go to Settings tab > Sync Settings
2. Click on Add Profile

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11429349/OGcalsync.log)

**Comment by phw198** [comment]
I'm a bit confused - your log file shows you still being identified as a donor and has the lines "Suppressing splash screen". If the splash was actually being displayed, the log would also have the lines "Showing splash screen" and "Disposed of splash screen", which it doesn't.

Are you sure you haven't somehow ended up with multiple installations of OGCS (or instances of it running with different configurations)?

**Comment by jedison** [comment]
I was not clear: the Splash screen does not show, but the Donate buttons do on About and Socialize, maybe that is as expected, and on the first time that I attempted to change (Delete or Rename) a Profile -- there is no longer a suggestion to donate when changing a Profile.

**Comment by phw198** [comment]
Thanks for confirming. Yes, that sounds like it is all working as expected - buttons would remain in those locations regardless of previous donations :+1:
