### ISSUE TITLE
This app is blocked 

### ISSUE THREAD

**Issue by nicastm** [phw198/OutlookGoogleCalendarSync#1645]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.7.0 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11445017/OGcalsync.log)

**Edition**: Installed 
**Sync Direction**: O->G 

**Bug Description**  
This app is blocked. This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
When I try to Sync I receive the following message:
**This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.**

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11445019/OGcalsync.log)

**Comment by phw198** [comment]
Looks like you're a long-time user of OGCS :slightly_smiling_face:  But it means you are on an old version of the Google authentication process, which apparently no longer works. The error message you are quoting is not in your logs, so I'm assuming you are seeing it in the browser when going to authorise access to Google?

Your logs just show:
```
Authorisation to allow OGCS to manage your Google calendar was cancelled.
Unable to authenticate with Google. The operation was cancelled.
```

[Similar to here](https://github.com/phw198/OutlookGoogleCalendarSync/issues/915#issuecomment-563376974), please go to the `Settings` > `Google` > `Disconnect Account` and then go through the OAuth process from scratch.

**Comment by nicastm** [comment]
Thanks for the response Paul.  Yes, I’m seeing the message in the browser when going to authorize access to Google. 

Success! I Disconnected the Google Account and then went through the OAuth process again and it resolved the issue. Works perfectly now

Thanks for your help!

Mike
