### ISSUE TITLE
OGCS wants to remove calendar entries in Outlook but should not.

### ISSUE THREAD

**Issue by amig500** [phw198/OutlookGoogleCalendarSync#1646]
[](url)

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.7.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
OGCS wants to remove 2 calendar entries in Outlook but should not.

**Steps to Reproduce the Issue**  
1. Click to start sync or just wait
2. Wait for the two erraneous deletion requests to come soon, say no, wait for next request :)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11445045/OGcalsync.log)
file.

**Comment by amig500** [comment]
Since I opened this case, the problem gets worse. I get warning messages and OGCS still wants to remove events, not the same, and is still wrong. Obviously the suggested solution does not help.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11484995/OGcalsync.log)

**Comment by phw198** [comment]
What's the suggested solution you are referring to? 

OK, I see in the logs, related to `19/05/2023 18:00 (R) "RdV tel avec Laura"` it says "This occurrence cannot be found in Outlook. Suggested fix: delete the entire series in Google and let OGCS recreate it." - but that has nothing to do with the issue you raised about unwanted deletions in Outlook, which would appear to be for `18/05/2023 18:00 "chez Fabien et Fanny"`

To my knowledge, [this suggested solution always works](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync)...

**Comment by amig500** [comment]
I refer to the one that appeirs on OGCS, and no it does not provide any solution.

**Comment by phw198** [comment]
Your response continues to be ambiguous and of no help.

Have you even bothered to view the wiki entry linked to in my previous post?

**Comment by amig500** [comment]
I don't understand.
The problem has been described and I told you just above that I tried the suggested fix, and it does not provide any result.
But, from this morning on, the false messages of deletion have dissapeired.
Apart from this, since the false messages do not pop anymore, the sync says to be OK but is not. For example I changed a few reccurent events on Outlook and they do not sync into Google. But some others are syncing. Is it linked? I tried to follow the wiki instructions and it does not solve the issue.

**Comment by phw198** [comment]
A very high level problem has been given, yes - with no details on the exact fix you are trying.

> I refer to the one that appeirs on OGCS

Well I gave a quote of what I think you are referring to, and you ignored it, so I have no way of knowing still whether that is the "one that appeirs on OGCS" or not. 

> and no it does not provide any solution.

A solution is certainly provided to the issue I _think_ you refer to: "delete the entire series in Google and let OGCS recreate it." but again, you are not saying if you tried that and it didn't work. I also said this has nothing to do with this issue (OGCS removing Outlook entries), so why would you expect that solution to work? For the record, it should stop the message appearing, but it wouldn't stop OGCS trying to delete items in Outlook.

> For example I changed a few reccurent events on Outlook and they do not sync into Google

Doesn't sound related no, but then without a log file to investigate with, very hard to say. Again, no explanation as to if you changed the whole series, just a few occurrences with the series etc. If the latter, and you clicked and dragged them to a new time, try restarting Outlook and syncing again.
