### ISSUE TITLE
Delete profile does not remove from settings.xml, so deleted profile still attempts to sync

### ISSUE THREAD

**Issue by jedison** [phw198/OutlookGoogleCalendarSync#1647]
**OGCS Version**: v2.9.3
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
I created 4 new profiles to combine 4 Outlook calendars into a new COMBINED calendar in Google.
Those worked more or less (sync error on one of them), but then I found a different solution so I deleted the profiles via the "Delete Profile" button.
However, the syncs continue attempting to be run even if they are no longer shown in the drop-down of the profile list.
I exited and restarted OGCS and the profiles re-appeared in the profile list, so I deleted them again -- but they are still present in in the settings.xml.

**Steps to Reproduce the Issue**  
1. Create a new profile
2. Save the settings of the profile
3. Run the profile
4. Delete the profile
5. Check if settings.xml contains the profile definitions

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11451527/OGcalsync.log)

**Comment by jedison** [comment]
Workaround:
Close OGCS.exe, open settings.xml, and delete <Calendar>...</Calendar> profiles to be removed.
Restart OGCS.exe

**Comment by phw198** [comment]
:package: Thanks for reporting this - it should now be resolved with [hotfix v2.9.7.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11522473/v2.9.7.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.
