### ISSUE TITLE
Can't sync meetings organized by other organizers in Outlook calendar (outlook -> google calendar)

### ISSUE THREAD

**Issue by whatseop** [phw198/OutlookGoogleCalendarSync#1648]
I'm using this program to one-way sync from Outlook to Google calendar.
It works very well except one thing.
The meeting that other team member is organizer is not synchronized from Outlook to Google calendar. Other invited meetings from others are fine. When I manually import the outlook ics URL to the Google calendar, there is the meeting.
Could you help me to solve it?
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11454291/OGcalsync.log)

**Comment by phw198** [comment]
Could you check:
* switching your categories inclusion config to exclusion and making sure none of them are checked
* experimenting without other date formats to see if that returns a different number of Outlook items
* turn on "export to CSV" and see if it is listed in the `outlook_appointments.csv` file

**Comment by whatseop** [comment]
Hello, Thank you for your explanation. I followed your instructions but still have the same issue.
- The new meetings/appointments, which I added in the outlook, were successfully synchronized to Google calendar.
- The events, which organizer A invited me, were successfully synchronized to Google calendar.
- The meetings, which organizer B invited me, were still not synchronized to Google calendar. -> This is my problem.
- I checked the CSV file but there was no the meetings from the organizer B.
- I tested it both 1) Filter categories > Exclude > unchecked all items, and 2) Filter categories > include > Checked all items.

What should I check additionally to solve it?

**Comment by phw198** [comment]
Thanks for the update. Could you try:
* Dialling up your logging level to `FINE` under Settings > Application Behaviour
* Try experimenting with the [date format option](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) under Settings > Outlook. It might be the missing items get included when using a different format
* Upload you logfile again if no luck

**Comment by whatseop** [comment]
Hello,
Thank you for your help. Now it works.
I changed the logging level to Fine in the Application Behaviour.
And changed the date format to Short Date & Time and then Default (g).
Sync is working for both date formats.

Should I change the logging level from Fine to previous one (Debug)?

**Comment by phw198** [comment]
So it finds the same number of Outlook items with _both_ date formats? I thought you already had the Default (g) format and that didn't work before.

As you have one-way sync, maybe manually delete the Google item and see if the problematic item from organiser B syncs with Default date format now? If not, I think you need to leave it as Short Date & Time.

The logging level can be reverted if the syncing is now working properly.
