### ISSUE TITLE
Mass deletions when syncing from iCal to Google

### ISSUE THREAD

**Issue by Mattyc106** [phw198/OutlookGoogleCalendarSync#1649]
**Are you already using OGCS?**
Provide the version number.
2.9.0.0
**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.
I have an iCal in Outlook and need to sync to Google.  Whenever the iCal is refreshed, OGCS sees all the entries as new ones and so needs to do a mass delete in Google and of course prompts to do this.

Can this mass deletion protection be removed?  I am happy to make a healthy donation if you can.

Many thanks

Mat

**Comment by phw198** [comment]
This will be the same cause as #447 - Apple are idiots and continually change an ID that should never change. 

Are you able to turn on two-way sync? If so, that allows OGCS to rely on the Google ID instead in order to match calendar items up.

**Comment by Mattyc106** [comment]
Hi, Thanks for the suggestion, but unfortunately a 2 way sync causes errors as per the below screenshot.

Sorry to ask again, but is there anyway to get a release that does not prompt about mass deletions?  The iCal is the source and we dont care what is deleted from the Google Calendar.  Again, happy to make a nice donation if you are able to do this.

Thanks in advance.

![Screenshot 2023-05-22 134433](https://github.com/phw198/OutlookGoogleCalendarSync/assets/133358709/4c7c793b-34cb-4053-969b-f20377afdbb6)

**Comment by phw198** [comment]
I'm not too keen on the idea of just allowing OGCS to delete and recreate everything on every sync - if there's a reasonable number of items in your calendar, this will unnecessarily chew up API quota and potentially annoy the Google overlords.

However, I maybe able to provide an alternative mechanism for syncing - let me see what I can do....

**Comment by phw198** [comment]
:package: OK, please have a go with [hotfix v2.9.7.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11567813/v2.9.7.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Once you get prompted about the mass deletion and you proceed with "Yes", you should get another prompt about viewing a wiki document about a possible resolution - let me know how it goes!

**Comment by Mattyc106** [comment]
Hi Paul

Firstly thanks for your efforts with this.

Sorry to report the application is crashing.  I have pasted the event log
below.

I uninstalled the App, deleted the folder, restarted the PC, installed
the App from your site (the latest Beta V2.9.0) and copied across the 2
files you gave me
to C:\Users\Paxton\AppData\Local\OutlookGoogleCalendarSync\app-2.9.0-beta
and I also tried copying the exe
to C:\Users\Paxton\AppData\Local\OutlookGoogleCalendarSync\

Error 1
Error 26/05/2023 08:06:26 .NET Runtime 1026 None
Application: OutlookGoogleCalendarSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at OutlookGoogleCalendarSync.Program.Main(System.String[])

Error 2
Error 26/05/2023 08:06:27 Application Error 1000 (100)
Faulting application name: OutlookGoogleCalendarSync.exe, version:
2.9.7.10, time stamp: 0x646f9951
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2965, time stamp:
0xf18c1c30
Exception code: 0xe0434352
Fault offset: 0x0013d6c2
Faulting process ID: 0x8f0
Faulting application start time: 0x01d98fa096a2d15c
Faulting application path:
C:\Users\Paxton\AppData\Local\OutlookGoogleCalendarSync\OutlookGoogleCalendarSync.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report ID: 45c25680-ff6f-4c4b-a799-d76baa92d50d
Faulting package full name:
Faulting package-relative application ID:

I hope you can work some magic?

Cheers

Mat

**Comment by phw198** [comment]
Thanks for trying - the patch needs to be applied on top of the latest alpha v2.9.7 though.

**Comment by Mattyc106** [comment]
Oh!  Sorry mate.  Will try again =)

**Comment by Mattyc106** [comment]
Hi Paul

I think we have a winner.  I need to do a final test with the person who
controls the iCal where they can create some new entries, but from my
testing so far I think it will work.

I really appreciate your efforts.  I have made a donation and will make a
further one after the final testing.

Thanks again

Mat

**Comment by phw198** [comment]
Thanks for the quick feedback and generous support - fingers crossed final testing is successful too :slightly_smiling_face:

**Comment by phw198** [comment]
Judging by your second donation, I'm assuming testing went well! I'm glad this release has proved useful and thanks for your generosity 👍

**Comment by Mattyc106** [comment]
Yes, I was meant to drop you a line and say all is good but work has
swamped me.

Its working brilliantly and we are very grateful for your valued support in
tweaking the software.

Thanks again =)
