### ISSUE TITLE
Sudden deletion of calendar entries

### ISSUE THREAD

**Issue by Survival62** [phw198/OutlookGoogleCalendarSync#1652]
**OGCS Version**: v2.9.7.0 
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Out of the sudden, on Wednesday17th, OGCS asked to delete plenty (10-15?) future calendar entries from this year. (but not all!)
I cannot recall all., but the items were repeating birthday entries, national holidays, but also standard single events.
I declined it, but during the next 2-3 syncronisations it asked me again and I always declined deleting.
Now it only ask me always again for one particular item which is a simple dentist appointment.
The items were not touched since a while, so I do not know what the root cause could be.
Today 19th, I updated to version 2.9.7.0 and OGCS still ask to delete this one item. 
There is no log file created today and the last one was from 14th.
There was only one from 18th yesterday which I added here.

**Steps to Reproduce the Issue**  
I do not know how to reproduce this behaivior as it just started out of the sudden.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log.2023-05-18.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11516020/OGcalsync.log.2023-05-18.log)

**Comment by phw198** [comment]
You've set your logging level to `ERROR` which is likely why you're not getting logs - which also makes them of little use for troubleshooting. This will also mean it's impossible to determine what may have caused the original spate of deletions.

You've not said where the remaining deletion is taking place, Google or Outlook. If it's Outlook, you might try the hotfix posted in #1601 and see if you are hitting that issue also.
