### ISSUE TITLE
"1 Outlook items would have been deleted, but you have deletions disabled." - Could it be possible to show which items could be deleted?

### ISSUE THREAD

**Issue by tadeas1** [phw198/OutlookGoogleCalendarSync#1656]
"1 Outlook items would have been deleted, but you have deletions disabled." - Could it be possible to show which items could be deleted?

Thank you very much

Best regards

Tomas

**Comment by VictorStankov** [comment]
Hi @tadeas1, you should consider upgrading as this is already a feature in [v2.9.7-alpha](https://www.outlookgooglecalendarsync.com/release-notes#v2970---alpha).

**Comment by phw198** [comment]
Yep, this is a duplicate of #1594
