### ISSUE TITLE
Import from Google to Outlook with different calender color?

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#166]
The scope of this enhancement has been broadened to encompass general synchronisation of calendar item colours.

**To do:**
Outlook to Google Sync
- [x] Write framework to pick closest available Google colour, given an Outlook colour
- [x] Sync colour for new events
- [x] Sync colour for updated events
- [x] GUI option to force all synced items as one colour

Google to Outlook Sync
- [x] Write framework to pick closest available Outlook colour, given a Google colour
- [x] Sync colour for new appointments
- [x] Sync colour for updated appointments
- [x] GUI option to force all synced items as one colour (category)

General
- [x] Make "Sync Options" panels collapsible
- [x] GUI option to enable sync of colours

<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/658676" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/tigole" target="_blank">tigole</a></strong> wrote at 2016-10-12 14:36:</p><div class="markDownOutput ">Hi, <br>
<br>
Is it possible to import Google Calender events to Outlook 2016 with a different color?
<br>
My work calender in Outlook uses blue color and I want my google events to be another color so I can see the difference between them.
<br>
<br>
Is this possible to achieve?<br>
</div></div>

**Comment by Lunarmanpl** [comment]
But I think it's possible already? You can sync google to different calendar made in Outlook with different color and in views make it both visible together.

**Comment by leaskovski** [comment]
+1 this enhancement request.  Doing it by importing the sync items into a new calendar doesn't work for me as I want to see my synced items in the calendar quick preview feature for meeting requests, so the need to catogrise on import into a single calendar is required.

It looks like this should be pretty easy to do:
https://stackoverflow.com/questions/4892890/how-to-colorize-categories-for-an-outlook-appointmentitem

The simplest way would be to pull the existing catagories that have been configured in outlook (be it via the outlook APIs or directly from the registry) and show them as an option meaning that the user selects a category to assign to the new AppointmentItem object that gets created...

```
private void createCalendarEntry(Event ev, ref AppointmentItem ai) {
....
            ai.Sensitivity = getPrivacy(ev.Visibility, null);
            ai.BusyStatus = getAvailability(ev.Transparency, null);
            ai.Categories = "Red Category";
```

Hopefully this can be quickly added.
