### ISSUE TITLE
Google Handshake Failed

### ISSUE THREAD

**Issue by RBarryWebster** [phw198/OutlookGoogleCalendarSync#1661]
When I initially install the app it syncs OK, but then goes into recursive "Google Handshake Failed" errors. Have tried both beta and alpha releases with same result.

What have I done wrong?

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11669223/OGcalsync.log)

**Comment by phw198** [comment]
Seems like you don't have a functioning internet connection, so OGCS can't communicate with Google.

Looks like you're configured to use the Internet Explorer proxy - not sure if that might be part of the issue...?

See also #1671 which was due to a firewall blocking comms.
