### ISSUE TITLE
Warning Dialog on each OGCS startup

### ISSUE THREAD

**Issue by cfischer69** [phw198/OutlookGoogleCalendarSync#1662]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11772910/OGcalsync.log)

**OGCS Version**: v2.9.7.0  
**Edition**: Installed   
**Sync Direction**: O->G

**Bug Description**  
Each time OGCS starts, I get a dialog box from Outlook warning me that something is trying to access my outlook data and requesting me to grant access for X minutes.

**Steps to Reproduce the Issue**  
1. Set OGCS to start at boot
2. Reboot computer
3. Notice dialog box

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
![Screenshot 2023-06-16 134849](https://github.com/phw198/OutlookGoogleCalendarSync/assets/27776818/efac3e64-657e-4a09-9b64-6fe3442480bc)

**Comment by pvenkhuijzen** [comment]
I get the same warning all day long since the recent update of OGCS

**Comment by phw198** [comment]
You'll also get a message in Windows notifications that if clicked will take you to [information on why this is happening](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#outlook-appointment-copy--paste). Usually resolved by setting a delay to OGCS starting, which gives time for your antivirus definitions to update.

Nothing related to recent update of OGCS, unless you also changed your configuration to sync meeting attendees, for example.
