### ISSUE TITLE
Issue when copying/Pasting an event on Outlook.

### ISSUE THREAD

**Issue by huotg01** [phw198/OutlookGoogleCalendarSync#1665]
Hi.

 I have had this issue for many months. On Outlook, when I Copy/Paste an event and change the date of the pasted version,, when running the sync app, I'm asked if I agree to delete the pasted/modified event in Outlook (please see the attached screenshot). Please note that this event could have been initiated in Google many months ago, but is no longer driven by Google, but by Outlook.

I'm using beta 2.10.0.0 O<->G

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11790221/OGcalsync.log)

![OtoG-1](https://github.com/phw198/OutlookGoogleCalendarSync/assets/3483165/2653c44d-5b33-451c-85a2-9389bd8ca206)

Thanks

Gaston Huot

**Comment by phw198** [comment]
Please [ensure you have OGCS running](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#outlook-appointment-copy--paste) when you copy and paste items in Outlook.

**Comment by huotg01** [comment]
Thanks phw198

I see the point. I will check out that next time. In the mean time, is there a way to fix the actual issue ? 

Thanks,

Gaston

**Comment by phw198** [comment]
Should be possible by running a one-off one-way sync - [see the wiki for details](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).
