### ISSUE TITLE
v2.9.0 OGCS shows Alpha update even though Check for Alpha releases is unchecked.

### ISSUE THREAD

**Issue by krwudtke** [phw198/OutlookGoogleCalendarSync#1669]
**Are you already using OGCS?** 
Yes, 2.9.0.0
This may actually be a bug, but as it is with the updating mechanism, updating to the latest Alpha would defeat the purpose.

**Describe the question you have**
As shown in the screen shots, I do not have "Check for Alpha releases" checked. However, each time OGCS starts, or I click "Check For Update", a window pops up saying that Alpha version 2.9.7.0 is available. I have told it to skip this version multiple times, but it keeps coming up. I see there is also a new Beta version on the GitHub page, but not on the main website. Furthermore, updating manually would defeat the purpose. Is version 2.10.0.0 still rolling out?

Thanks,
Kevin
![OGCS About window 2023-06-23](https://github.com/phw198/OutlookGoogleCalendarSync/assets/7281718/fb61fbef-86ba-47ca-ae55-fe1ecee18ef6)
![OGCS Update window 2023-06-23](https://github.com/phw198/OutlookGoogleCalendarSync/assets/7281718/0ffc9dd7-a3fb-4455-931b-6c51760b2a0f)

**Comment by cyberblob** [comment]
Yes, Same problem here. 
Also Skip this version button does not register to skip it.
Every time I reboot the prompt shows up no matter if I say skip version.

**Comment by krwudtke** [comment]
On startup today, I was offered 2.10.0.0. If nothing was changed, I guess it was still rolling out. Leaving this open just to be sure Paul is aware, but the issue appears to be resolved.

**Comment by phw198** [comment]
This is [a bug that was fixed](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1263#issuecomment-903274631) in v2.9.1 - unfortunately, whilst remaining on v2.9.0 you'll continually get bugged for update :slightly_frowning_face: 

If you haven't been offered v2.10.0 yet, roll-out should be complete by the weekend.

**Comment by krwudtke** [comment]
Thanks, Paul.
Looking at the linked issue, I may have installed 2.9.0 manually back then. At first, I thought, "But I haven't been getting bugged about every alpha release since 2.9.1." I understand now that it wouldn't have been happening until 2.10 started rolling out.
I was offered 2.10 yesterday and installed it. 
Thanks for a great piece of software!
Kevin
