### ISSUE TITLE
Sync version: 2.9.7.0   Unable to communicate with Google services. Unable to connect to the remote server,  Google handshake failed.  Sync aborted after 1 failed attempts!

### ISSUE THREAD

**Issue by FrancoCapetti** [phw198/OutlookGoogleCalendarSync#1671]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by krwudtke** [comment]
Hi Franco,
You need to complete the items above. The developer needs that info to look into the problem. He can't do anything with only the subject you entered.

**Comment by FrancoCapetti** [comment]
Hi Kevin, I found the issue and solved the problem by myself; it was a firewall unexpectedly activated that blocked the communication.
Thanks for your prompt reaction.

Franco

Franco
________________________________

**Comment by krwudtke** [comment]
Great! I'm glad it is resolved.

**Comment by krwudtke** [comment]
@FrancoCapetti Could you possibly log back into GitHub and close the issue. It appears only the creator or an admin (which I am not) can close issues. It's at the bottom next to the **Comment** button for posting a new comment.

**Comment by FrancoCapetti** [comment]
The issue was solved closing a firewall unexpectedly activated.
