### ISSUE TITLE
OGCS cannot sync from an .ICS calendar whilst it is updating

### ISSUE THREAD

**Issue by Mattyc106** [phw198/OutlookGoogleCalendarSync#1672]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.7.10 
**Edition**: Installed
**Sync Direction**:  O->G 

**Bug Description**  
The application will display a dialogue box "Google event creation failed.  Continue with synchronisation?" as per attachment error01.jpg.    If you press YES, the same prompt reappears

If you click No then a dialogue box appears "The synchronisation failed - check tab for further details - Do you want to try again?"  If you click Yes it runs without issue.  Attached is error02.jpg showing this

**Steps to Reproduce the Issue**  
Leave the Sync running and every 2 or 3 days this will appear

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11892482/OGcalsync.log)
![Error01](https://github.com/phw198/OutlookGoogleCalendarSync/assets/133358709/ca0f00e2-21fa-40c2-ab05-3443e7e8d027)
![Error02](https://github.com/phw198/OutlookGoogleCalendarSync/assets/133358709/0511e0de-cdec-4707-a51d-a613415fdb6b)

**Comment by phw198** [comment]
This is the iCal `.ics` file that is the source of the Outlook appointments, isn't it...

I'm not sure much can be done about this - it's basically failing to read the Outlook calendar items when creating the Google items; but when you start a new sync, then it's fine. How often does the ICS update? I wonder if there's a locking problem that when it updates in the middle of OGCS syncing, then it becomes unavailable :thinking: Plausible If the issue happens on the first sync of the day, when Outlook might be updating.

You can check when the ICS last updated by going to File > Info > Account Settings > Account Settings... > Internet Calendars

You could also try setting a new Send/Receive group for the ICS calendar with a different update frequency: Send/Receive > Send/Receive Groups > Define Send/Receive Groups

Are the number of items to be created in Google a concern? The log appears to be for 2 days after your screenshot, but it has
> Outlook 127, Google 193
0 Google calendar entries to be deleted.
5 Google calendar entries to be created.
122 calendar entries to be compared.

**Comment by Mattyc106** [comment]
Yes, its the iCal sitting in Outlook.

Good call on the iCal - it was set to update every 5 mins, which I had
applied when testing.  I agree its a bit too much for production and I have
reduced this to every 58 mins.    I have also changed the OGCS to sync
every 6 hours, but push Outlook changes immediately.

On the initial sync I did 365 days in the past, just to get the historic
data synced to Google.  This is static and wont change, so on all
subsequent syncs the date range is set to 0 days in the past.

I will report back in the next week to keep you updated.

Thanks

Mat

**Comment by Mattyc106** [comment]
Things are a lot better now.  There has only been one more issue since last
week, so I turned off Push Outlook changes immediately and since then its
been fine.

It would seem that you were correct - it was locking up when Outlook was in
the middle of updating the iCal.

I will update again in another week.

Thanks

Mat

**Comment by Mattyc106** [comment]
Hi Paul

Please feel free to close this.  OGCS is fine and we keep an eye on Outlook
to ensure its OK.

Many thanks

Mat

**Comment by phw198** [comment]
Thanks @Mattyc106 !

**Comment by phw198** [comment]
🔗 #1893
