### ISSUE TITLE
Could not update registry for "All Users" setting

### ISSUE THREAD

**Issue by Vantiveman** [phw198/OutlookGoogleCalendarSync#1673]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
Tried to use the option to set it for all users but received a message that it did not have permission to update the registry. Wanted to run as admin to try again but a prompt advised that it should not be run as admin.

**Steps to Reproduce the Issue**  
1. Go to settings, and then the Application Behaviour tab.
1. Click on "for all users". Received registry access denied.

If it can not be done this way could you please provide the reg key required so that I can set it manually.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11929301/OGcalsync.log)

**Comment by phw198** [comment]
You should be able to

1. Copy the registry key from `\\HKCU\Software\Microsoft\Windows\CurrentVersion\Run\Outlook Google Calendar Sync`
1. To `\\HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Run\Outlook Google Calendar Sync`

Hope that helps

**Comment by Vantiveman** [comment]
Thanks Paul,

I’ll try that after lunch :)

Alan
