### ISSUE TITLE
Email Address is not recognized

### ISSUE THREAD

**Issue by ftodaf** [phw198/OutlookGoogleCalendarSync#1674]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0.0  
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Outlook Google Calendar Sync starts at computer startup automatically.
Misbehavior: only two of the three email addresses are visible, the important one fa**************r@o******l.com where the calendar is used is not visible. Instead, the fa**************r@o****e is visible twice.

Expected behavior: All email addresses should be visible in software

**Steps to Reproduce the Issue**  
Preconditions: 3 Email addresses in Outlook. New Outlook Profile was set up recently.
1) Go to "Settings"
2) In "Outlook" Tab, select Radio Button "Alternative Mailbox"
3) Click on Dropdown 
4) Check available Email addresses

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11945585/OGcalsync.log)

**Comment by ftodaf** [comment]
Solved: Default Email Address equals required email address. No bugfix is needed. Recommendation for programmers: would it be possible to also display the default email address? That could avoid this confusion.

Issue will be closed

**Comment by phw198** [comment]
I'm not sure I quite follow your suggestion. From my below example, the content of the drop down is the same as the accounts/folders available on the left in Outlook:-

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/ab758e6e-6ab9-4b17-b3fa-dbfdd91bea8a)

**Comment by ftodaf** [comment]
![grafik](https://github.com/phw198/OutlookGoogleCalendarSync/assets/138560802/f50c30a8-558c-42e2-a13f-00df2834ee3c)
![grafik](https://github.com/phw198/OutlookGoogleCalendarSync/assets/138560802/f6f459ff-016c-44c1-8231-00c50146de7e)
In my case, f*****************fmail.com is missing

**Comment by phw198** [comment]
@ftodaf Could you confirm if you are able to see the missing folder when using v2.10.1?

**Comment by ftodaf** [comment]
Yes, it's visible after the update.
