### ISSUE TITLE
Unwanted deletiion of multiple Outlook entries during sync...

### ISSUE THREAD

**Issue by MikeSamuels** [phw198/OutlookGoogleCalendarSync#1675]
Hi
I'm not a programmer, just a long-time user of this great app.  It's been working for years perfectly but in the last couple of weeks I've had several occasions where I've watched while the sync occurs, it says (for example) 34 items to sync, then deleting 34 items.  All is deleted and luckily ends up in my Outlook desktop Deleted Items folder.  I'm on v2.9.7.0 and nothing has changed to my knowledge. 

I restored all the deleted items, synced and they deleted again.  I set OGCS to no delete and did a 1-way sync Outlook to Google.  That put everything back.  I created a 'test' entry in Outlook, switched back to 2-way sync and the test would have deleted if I didn't have no delete checked.  What's happened, or what am I doing wrong?  I rely on this tool to sync my Outlook Desktop to my Android phone Google calendar.  Help!

Thanks, Mike

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Hi - if you can provide your OGcalsync.log file showing the 'test' to be synced and it being set for deletion, then I can look to investigate further for you. Would be worth installing the lastest beta v2.10.0 first though.

Thanks.
