### ISSUE TITLE
OGCS does not always register paid calendar sync option - intermittently fails sync and offers paid option

### ISSUE THREAD

**Issue by d-bowie** [phw198/OutlookGoogleCalendarSync#1676]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
Done, already on 
> * [x] Reproduce the issue
Happens at least once per day.
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
Sent

**OGCS Version**: v2.9.7 Alpha
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
OGCS does not always register paid calendar sync option - fails to sync and offers paid option. I would say 90% of the time the paid option is registered properly.

**Steps to Reproduce the Issue**  
1. Go to the Sync tab
2. Click on start sync.
3.  Observe the sync. It often starts off with saying thank you for the support in the yellow box at the bottom. 
4. If the sync fails it may say the calender sync limit has been reached and you can subscribe to the paid option.

**Any other information**  
Any additional information that may help troubleshoot the issue?  
:paperclip: Attach your `OGcalsync.log` file.
![OGCS 1](https://github.com/phw198/OutlookGoogleCalendarSync/assets/43047494/e802a334-a529-4ad6-ae71-e5edb4b2d43c)
![OGCS 2](https://github.com/phw198/OutlookGoogleCalendarSync/assets/43047494/41d099be-5a19-4d18-b226-f31ee1765723)
![OGCS 3](https://github.com/phw198/OutlookGoogleCalendarSync/assets/43047494/83e8123c-4c56-4969-879a-124668210b81)

**Comment by phw198** [comment]
:package: Thanks @d-bowie - could you give [hotfix v2.10.0.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11996532/v2.10.0.3.zip) a whirl ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know if that behaves better...

**Comment by d-bowie** [comment]
Apologies, was on leave last week. The issue has not been repeated since the hotfix was applied thanks. Ok to close this off now.
Thanks again
