### ISSUE TITLE
One-time change in a recurring Google appointment

### ISSUE THREAD

**Issue by pospik** [phw198/OutlookGoogleCalendarSync#1681]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Hi,
I have repeated appointment in Google (example: every Tuesday 10:00) and if somebody changed time (example: to 14:00 for next Tuesday only), it wasn't reflected in Outlook. I still see 10:00. 
I have disabled deletions.
Tomas

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
With the information you provided, works OK for me:
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/4b60e111-be42-480e-967e-4d0cbf526575)

Would likely need your logfile to investigate any further.
