### ISSUE TITLE
Unclear Google account is for entire OGCS instance / all Profiles

### ISSUE THREAD

**Issue by abeszedes** [phw198/OutlookGoogleCalendarSync#1683]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0.0
**Edition**: Installed 
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
A set up two different profiles and connect them to different Google accounts. Then, moving to a different tab, only the lates account is saved for both profiles.

**Steps to Reproduce the Issue**  
1. Go to Settings and create two profiles
1. Click of GOogle and connect an account with an email
1.  Do the same for the other profile but this time for a different account.
1. Now, select the previous profile, and the account will be also this new one.
1. Syncing will not work for the first profile because the account will be wrong.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12231364/OGcalsync.log)

**Comment by phw198** [comment]
I agree, with the introduction of _Profiles_ it's no longer clear that the Google **account** being used is not for the _Profile_ but for the instance of OGCS. The Google **calendar** within the _Profile_ is customisable, however.

Will look to see how this can be improved in the user interface...

Meanwhile, see here on [how to run multiple instances](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Running-Multiple-Instances-of-OGCS) of OGCS, one for each Google account.
