### ISSUE TITLE
2.10.1 alpha actually installs hotfix 2.10.0.9

### ISSUE THREAD

**Issue by lbd1277** [phw198/OutlookGoogleCalendarSync#1684]
Latest Update does not install 2.10.1, exe is 2.10.0.9 in the folder AppData\Local\OutlookGoogleCalendarSync\app-2.10.1-alpha

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Thanks for pointing this out - I had a feeling something would go wrong with the build of this released! :slightly_frowning_face: 

I've repacked it, if you could try the new [OGCS_Setup.exe](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.10.1-alpha/OGCS_Setup.exe) install file again?

**Comment by lbd1277** [comment]
Hello,

That resolved it thanks !!!!
