### ISSUE TITLE
Create custom sync rules option

### ISSUE THREAD

**Issue by DreadedLama** [phw198/OutlookGoogleCalendarSync#1685]
Please add an option not to sync all-day events. Colleague's leave or other not so needed all-day events get synced to my Gmail which I don't want.
It would be great if we can create custom rules as to what to sync and what not to.
Thanks for the great app.

**Comment by dreadedlama** [comment]
I see this feature has been added in the latest [v2.10.1 Alpha](https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.10.1-alpha) release. Hence closing this issue.
