### ISSUE TITLE
Exclude appointments by title

### ISSUE THREAD

**Issue by jankete** [phw198/OutlookGoogleCalendarSync#1688]
**Is your feature request related to a problem? Please describe.**
Outlook automatically creates appointments for contact birthdays (Birthday of ...) and anniversarys. And I don't want these to be synced to Google.

**Describe the solution you'd like**
For now we can only exclude appointments by category, but it would be helpful if we could exclude them by (part of) title as well. So we could filter these things out.

**Comment by phw198** [comment]
v2.10.1 introduced excluding all day items (with an additional option for those marked with "free" availability). Does this help reduce the requirement for excluding by title/subject?

**Comment by jankete** [comment]
Unfortunately not, because I have some free all day entries which I need to be synced.

**Comment by phw198** [comment]
:link: Similar to #334

**Comment by phw198** [comment]
:package: This should now be available with [hotfix v2.10.1.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12445229/v2.10.1.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/17028329-695f-4d37-b67e-be389d32f59a)

Let me know how it goes!

**Comment by jankete** [comment]
Hotfix workes as expected 👍It also has removed previously synced appointments matching the string from google.

**Comment by slimninja** [comment]
Came here to request this as a feature and it's already coming in the next version! Thanks for the hard work @phw198 !

**Comment by phw198** [comment]
@slimninja Feel free to try out the hotfix available above until the next release is available.

**Comment by aking7** [comment]
I see this feature is now released as part of v2.11.0.0, which is great. As you noted, the exclusion only works for individual events or an entire event series. Is there a plan to enable excluding an occurrence of an event series? Unfortunately, categories do not work for this, as Outlook applies the category to the entire event series.

**Comment by phw198** [comment]
No, no plans - pretty much for the same reason that Outlook doesn't allow categories to be assigned to an individual occurrence. The problem is each exclusion would cause an "exception" to the series, thus changing its structure and so the series would become very "messy", due solely to the sync. 

Therefore, both in theoretical design and practical complexities with two-way sync, this is not something I'll be implementing.
