### ISSUE TITLE
Sync never ends - recurring series with 100s of exceptions

### ISSUE THREAD

**Issue by CsaChris** [phw198/OutlookGoogleCalendarSync#1690]
since upgrade to version 2.10.0 Beta the synchronisation never ends, same is with V2.10.1 Alpha.
Before it worked beautifull with V2.07

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.1 
**Edition**: Installed   
**Sync Direction**:  O<->G

**Bug Description**  
Synch starts, made synch from Outlook to Google then Google to Outlook and stays blocked on "comparing 942 existing Oulook calendar entries" 
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/141960821/003f79e4-4fca-4dc8-aa62-5471a6a1d163)

**Steps to Reproduce the Issue**  
1. Go to. OGCS
1. Click on Start Synch

**Any other information**  
[OGcalsync (2).log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12316846/OGcalsync.2.log)

**Comment by phw198** [comment]
You mean you were previously running v2.7.0 before upgrading to v2.10.0? That's a big jump - so no point in my trying to work out what's changed...

So in yours log, it was syncing from Google to Outlook and trying to process the recurring series `28/03/2022 12:00 (R) => "Infirmière (Christian)"` in Outlook for 2 hours - problem being is that series has 750 exceptions (occurrences that have been altered), one every two weeks, that run up to November 2035 before you aborted! In earlier sync it got as far as 2043.

It looks like Google has the equivalent number of exceptions too, so is there any chance you can just delete this series and recreate it?

**Comment by CsaChris** [comment]
Hello, first of all, thanks for your quick answer.
The deleting of the recurring series and creating of a new one with an enddate in 1 year solves the issue.
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/141960821/c916be6b-fa23-480d-aaa4-c088959cd83a)

Great thanks for your help.
