### ISSUE TITLE
Deleting Outlook entries when I don't want them deleted

### ISSUE THREAD

**Issue by rschwedes** [phw198/OutlookGoogleCalendarSync#1691]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
When i run sync i am frequently being asked to delete 13 Outlook entries...yet i have not deleted them from google calendar not have i deleted them from an outlook calendar.  
Each time i deny the deletion. 
But the request to delete the same entries occurs again
Is there something i need to do?
Have I done something wrong?
[](url)

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12365460/OGcalsync.log)

**Comment by phw198** [comment]
Hi - please take a look at [guidance here for resolving](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).

BTW, I note from your logs that you are running the 2.10.1 alpha release which wasn't packaged quite right (issue #1684) - you might want to install it again to get the proper release: https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.10.1-alpha/OGCS_Setup.exe

**Comment by phw198** [comment]
Been having more of a think about this and #1686 might have helped the penny drop on a fairly straight forward solution.

:package: If you're still encountering unwanted deletions, please try [hotfix v2.10.1.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12386506/v2.10.1.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

After you get a deletion prompt and select `No`, it should then also cause the item to be synced again to the other calendar and no further deletion prompts received.

Let me know how you get on!
