### ISSUE TITLE
Outlook didn't respond when accessing recurring series exception

### ISSUE THREAD

**Issue by ErwinWarmerdam** [phw198/OutlookGoogleCalendarSync#1694]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v
**Edition**: Portable  
**Sync Direction**: O<->G 

**Bug Description**  
I have received a new laptop with outlook (Microsoft® Outlook® for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20684) 64-bit) installed. On this laptop I'm using the portable OGSC version as i did on my old laptop.
I have configured OGSC but the moment the sync starts for google -> outlook some deleted appoints are mentioned but at a certain moment the OGCS stops syncing. Strangely the log doesn't show any errors but just stops logging as if the program has stopped.
The GUI is still responding.
When clicking " Stop sync"  it seems nothing is happening and need to click "Stop sync" again. (this is also in the log)

Log file:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12393618/OGcalsync.log)

**Comment by ErwinWarmerdam** [comment]
I have an update regarding my issue. The issue seems to be solved. 
What i have done to solve the issue:
First did a sync O -> G
Then did a sync from G -> O
Then did a sync O <-> G
Now it seems to sync again without issues.

**Comment by phw198** [comment]
From your logs, Outlook just didn't respond when OGCS was attempting to determine if the recurring series `06/01/2020 09:00 (R) => "Scrum meeting"` exception on 14/07/2023 was deleted or not.

I don't think changing to 1-way sync and back to 2-way would have made any difference, just Outlook glitched - though I've never seen this before. Normally Outlook would return an error or timeout or something, not just hang indefinitely.
