### ISSUE TITLE
GMail reports unable to contact email address when changing/deleting a meeting/calendar event

### ISSUE THREAD

**Issue by newtonrs** [phw198/OutlookGoogleCalendarSync#1696]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0.0
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
When an appointment, originally created via Outlook (Pro Plus 2021), is changed or deleted from within the Gmail calendar (through web browser), a notice email is generated via GMail that the email domain/account to be notified does not exist.

The email domain that is returned as not existing is "@domain.OSGS", where ".ocgs" is appended to a valid email domain. For example "user@gmail.com.ocgs". I have an image of the notification email, but nowhere to upload it for you to see the example of; there is no noted error in the OCGS.log file as this error is being shown as an auto-reply from GMail to the change request outgoing message regarding the change of the appointment.

However, no such error message is generated under the following uses:

- The calendar entry is created in Outlook but changed or deleted through the GMail calendar interface (in a browser). For instance, if the entry was created in Outlook and then changed or deleted via Outlook then there is no domain error email posted.
- Similarly, if the entry was created via the GMail calendar and then changed or deleted via the GMail calendar interface there is no error noted.

**Steps to Reproduce the Issue** 
Created several entries via Outlook then changed via GMail's calendar and vice versa. Created and changed/deleted using only Outlook. Created and changed/deleted using only GMail's calendar.

**Any other information**  
Change or delete the calendar entry using the same source that was used to initially create the calendar entry, or only use Outlook to add, change or delete calendar entries.

The "attendees" that are listed do appear to get the altered calendar entry as well as any deletions and attendance status does appear in the calendar entry within Outlook's calendar.

Not sure if this is related, however, there are occasions where an invitee--optional tested only thus far--responds to the calendar invite and there is a notice added, by Outlook, in the response indicating that the calendar entry has either been moved, or deleted, prior to the attendee's response despite that not being the case. The exact notice with the response email is:

"We couldn't find this meeting in the calendar. It may have been moved or deleted. <name_of_attendee> has accepted this meeting."

The email reply for the meeting that indicates that the attendee response is associated with a "missing", or "deleted", calendar entry has a date/time of arrival into my email account of 12:45PM, August 21, 2023. The appointment was added to my calendar the previous day (the appointment itself isn't until September 13th @ 10:30AM) and was never altered after addition. As such, the calendar entry should have been present in my Outlook calendar when the reply regarding attendance was posted.

And the calendar entry within Outlook does not show any information on attendees status/response. As yet I have not verified that this occurs only when entry created in GMail and then response comes prior to synch with Outlook's calendar, only that the attendee is responding to the event through Outlook. As such it is possible that the GMail calendar entry has not yet synch'd with Outlook prior to the acceptance of the requested attendee(s) choosing their attendance option.

None of these events appear in the OCGS logs.

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12401838/OGcalsync.log)
[Outlook Google Calendar Sync (2023-07-21 to 2023-08-20).zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12401848/Outlook.Google.Calendar.Sync.2023-07-21.to.2023-08-20.zip)
![OGCS Calendar Deletion from Google -- EMail Domain Error (Gmail)](https://github.com/phw198/OutlookGoogleCalendarSync/assets/142835709/0cba8d7f-72cf-41bc-a024-be8e545d07a3)

**Comment by phw198** [comment]
Such a shame you've gone to such effort to report documented Google behaviour and a carefully crafted OGCS workaround!

https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-am-i-getting-undeliverable-notifications-from-google-for-recipients-ogcs

**Comment by newtonrs** [comment]
Hi Paul,

 

Sorry to have created notification of an issue when it has already been documented. My error. Apologies. Thank-you for locating the appropriate FAQ, most appreciated. 😊

 

 

Thanks,

__________

Rick Newton.

E-Mail:                   ***@***.***> ***@***.***

Phone:                 905.319.1928

Mobile:                905.802.9962

**Comment by phw198** [comment]
I just wish everyone provided such detail in the issues they raise!

**Comment by newtonrs** [comment]
I used to work as a manager in software support for a company that created software to support accountants to go paperless; and previously a call-centre support person and before even that the only IT support for an accounting firm and a bankruptcy firm.

So, always aware that the best way to get a solution is to provide as much detail surrounding the issue as possible. Some may turn out to be irrelevant, but that decision should be left with the person doing the support. “Editing” before sending information can lead to not getting an answer, or getting the wrong answer.

Again, thanks for the info. and for pointing me in the right direction.
