### ISSUE TITLE
Events deleted in Outlook are not being deleted in Google Calendar

### ISSUE THREAD

**Issue by SixPines** [phw198/OutlookGoogleCalendarSync#1697]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0.0  
**Edition**: Installed
**Sync Direction**:  O<->G

**Bug Description**  
A clear and concise description of what the bug is. See Steps to Reproduce

**Steps to Reproduce the Issue**  
1. In Google Calendar, create an event.
2. Manually Sync in OGCS. 
3. Verify that event shows up in Outlook Calendar (it does show up).
4. Delete event in Outlook.
5. Manually Sync in OGCS.
6. Verify that event is deleted in Google Calendar (it is NOT deleted; rather the Google Calendar event is re-populated in Outlook Calendar)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12431734/OGcalsync.log)

**Comment by phw198** [comment]
In your issue you have said that you are two-way syncing, but in your log file it only has evidence of you one-way syncing G->O - which explains the behaviour you see.

**Comment by SixPines** [comment]
Thanks, Paul.

I misunderstood how the configuration screens work. I’ve made the change you intimated, and things are now working as expected.

Thanks!
Ricky
