### ISSUE TITLE
Start OGCS and sync immediately, then close

### ISSUE THREAD

**Issue by sachguy** [phw198/OutlookGoogleCalendarSync#1698]
**Are you already using OGCS?**
Version 2.10.0.0

**Describe the question you have**
I have been using OGCS for some time but now have a need to:
1. Start OGCS programmatically (I know how to do this) and NOT when windows starts
2. Once started, I would like OGCS to sync my Outlook calendar to my Google calendar IMMEDIATELY
3. Then quit.
4. Is this possible?
5. Thank you. Dale

**Comment by phw198** [comment]
I think there's overlap here with #974 and #1615 for timed executions, which if implemented would just leave your requirement to close OGCS after a sync. But I'm not sure that's really necessary, as it would just sit in the background when not syncing...?

**Comment by sachguy** [comment]
I update Outlook many times during the day, and leaving OGCS sitting in the background when not syncing, as you suggest, would result in multiple copies in my tray.  This is why my idea was to have it close after the sync.  Is this possible?

**Comment by phw198** [comment]
What do you mean multiple copies in the tray? It's designed to run in the background with a configured schedule on how often you want it to sync, eg hourly.

**Comment by sachguy** [comment]
I think I am satisfied with my latest settings. I have it sync every 15
minutes. I will not start it programmatically. I will close this ticket.
Thank you Paul have a great weekend.
