### ISSUE TITLE
Two way sync fails... just hangs

### ISSUE THREAD

**Issue by larskochhansen** [phw198/OutlookGoogleCalendarSync#1700]
> * [x ] Reproduce the issue
Just start the two way sync.

**OGCS Version**: v 2.10.1.0 alpha
**Edition**: Portable  
**Sync Direction**: O<->G (Two-Way)

**Bug Description**  
The Sync process just "hangs" as seen on the picture. Says "Comparing XX existing Google calendar entries".  Either I force-quit the sync or it will time out later. 

Happens every time I try to sync two-way. One way from outlook -> google works fine. I was working fine up until 3-4 months ago. Can't remember when exactly. Tried installing the alpha version 2.10.1.0 but still a problem.
Please advise.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12465669/OGcalsync.log)

![screenshot](https://github.com/phw198/OutlookGoogleCalendarSync/assets/17578995/27e72474-2525-4fc9-99d7-5c9ed16b3efa)

Thanks in advance
Lars

**Comment by larskochhansen** [comment]
Might be due to my companys firewall settings but it used to work 😊 any suggestions?

**Comment by phw198** [comment]
For the log file you uploaded, is that where it had just hung?

Anyway, your problem is with this Outlook appointment - 729 exceptions for something that looks like a weekly recurrence!
```
2023-08-29 16:29:59,749 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [666] -  10-06-2021 15:00 (R) => "MED/KIR/RTG Konference"
2023-08-29 16:29:59,765 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [667] -  This is a recurring appointment with 729 exceptions that will now be iteratively compared.
```
Can you delete it and recreate it?
