### ISSUE TITLE
Problem on new PC

### ISSUE THREAD

**Issue by dchamp56** [phw198/OutlookGoogleCalendarSync#1707]
Just set up a new PC, moved Office from one to the other (all data, emails, calendars.. etc).
Tried to set up OGCS and it appears to work, but doesn't sync anything.
I unlinked and linked to my google account again, and still not syncing.
Added in Outlook, nothing added to Google.
Added to Google, Nothing added to Outlook 2021
Any help would be appreciated.
Dave C.

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12707198/OGcalsync.log)

> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Did you get this resolved?

**Comment by dchamp56** [comment]
Yes
    	Dave
