### ISSUE TITLE
Sync between two PCs and Google

### ISSUE THREAD

**Issue by daveinhull** [phw198/OutlookGoogleCalendarSync#1709]
Hello,

I'm using OGCS V2.10.1.0
Please note the following problem did not previously exist, but not sure which version it started happening on.

I have a desktop PC and a laptop PC both with OGCS and both are running identical profiles.
Using both-ways sync, if I create an entry on the desktop and sync to Google it works, but then if I sync with laptop, the laptop wants to delete the entry.

Using both-ways sync, if I create an entry in Google and sync to the laptop it works, but then when I sync to the desktop it wants to delete the entry.

It appears that once an item is synced with one PC, it wants to be deleted from the other PC, even if the item is crated in Google, so something must be updating the Google entry so that it cannot be synced on another PC.

Firstly, can this setup actually work and if it is possble is there an issue wth it or do I need to setup the configuraiton in another way?

Thanks Dave

**Comment by phw198** [comment]
Yes, that's a supported configuration having a common Google calendar and two Outlooks. What Outlook account do you have on each computer? Is it connected to the same Exchange account (though this should work too, as long as each computer has synced with Exchange before OGCS syncs)?

:spiral_notepad: You'd need to provide your `OGcalsync.log` files ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) after having reproduced the issue for me to investigate properly, though.

What link(s) did you click through to raise this GitHub issue? It doesn't appear to have used the template...

**Comment by daveinhull** [comment]
Hi Paul,

The desktop and the laptop are both using IMAP/SMTP accounts to my own email account using a third party webhosting account on Unlimited Web Hosting (unlimitedwebhosting.co.uk).

As I said, this used to work absolutely fine, but seems to now go wrong.

I’ve uploaded the log file from the last sync I did where the problem happened. It tried to delete a calendar entry from Google because it wasn’t in my desktop Outlook. So the sequence of events was:

1.	Created diary entry on my laptop while traveling (LRQA Audit – MITA, 7/10/24)
2.	Synced to Google using OGCS on my Laptop
3.	Got home
4.	Synced to Google on my Desktop tried to delete the calendar entry

Would appreciate any help or guidance if I’m doing something incorrectly, or if you need more data further tests please let me know.

This is a great tool, but unusable at the moment ☹

Many thanks
Dave

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email, so you log file wasn't included in your previous post.

However, I think to fully troubleshoot this I will need the log file from both computers:
* Set the log level to `FINE` on both computers
* Provide the laptop logfile after OGCS has created the test item in Google
* Provide the desktop logfile after OGCS has deleted the test item in Google instead of syncing it

**Comment by daveinhull** [comment]
Hello Paul,
  
I didn't add the log file to the ticket, i went through the github upload process and gave it the ticket nunver.
  
It was saved somewhere, but not sure where?
  
Dave

**Comment by daveinhull** [comment]
Hi Paul,

Sorry, I didn’t read all your message previously.

I’m working away at the moment so don’t have access to my desktop PC. 

Ill do as you suggest once I get back home.

Dave

**Comment by phw198** [comment]
The log file you provided already is from your desktop though, right? As that includes the intended delete from Google (which you decline) and then it creates it in Outlook.

Perhaps you could just upload your laptop logfile from yesterday, which should include syncing to Google the initial manual creation of the Outlook item?

IMAP accounts don't sync the calendar folders - in Outlook they should say `(This computer only)` next to them, as in it is only the email that is being synced from the cloud. Is this what shows in yours?

If I can see your other logfile, what I'm hoping/expecting to see is the ID behind each Outlook calendar is actually the same, which it shouldn't be if Outlook created them independently on both machines. Unless you did something funky with backing up PST files and restoring on the other computer??

**Comment by daveinhull** [comment]
Hi Paul,

The log fine is from Friday (last day I used my laptop) and then yesterday on my Desktop it synced. I’ll up load that log fine shortly.

On the calendar page (on my laptop) it says:

Calendar 235 – Desktop Mailbox, nothing about “This computer only”, unless I’m looking in the wrong place

The thing is, it all worked perfectly up until about a month or so ago, then it started doing what I’ve described, but I don’t think I changed anything – I’ve been using it successfully for over a year.

Dave

**Comment by daveinhull** [comment]
Hi Paul,

I’ve uploaded the sync log from Friday, the last time my laptop synced. 

Yes the log I sent yesterday was from my desktop, the new one is form my laptop.

Also, I can’t remember doing anything fancy initially, although I may have deleted all my laptop calendar entries and used OGCS to load the laptop from my desktop, but I’m not sure I can remember. However, since whatever I did initially, it’s worked perfectly with new entries on my desktop syncing to Google and then to my laptop and vice-versa.

Given the time between the two log files, I may need to create an example specifically when I get home using fine debugging and then send again the two log files. 

Dave

**Comment by phw198** [comment]
Yes, I think if you can provide the log file from both machines after performing a specific test, that will help. The log file you just uploaded from your laptop doesn't show anything being created in Google at all.

I'm a little concerned by the Outook calendar ID being the same in both your logfile though, and also on your desktop there are lots of "Appointment GlobalID has completely changed", which it never should - I've only seen this happening with calendars hosted on iCloud....is that relevant here? UnlimitedHosting did seem to have some articles on linking domains with iCloud mailboxes...

**Comment by daveinhull** [comment]
Hi Paul,

OK, when I get home I’ll create a specific example of what goes wrong as I did this a week or so ago to try to see what was happening. 

I’m not sure if my accounts are hosted on iCloud, but as I mentioned, this was working fine a month or so ago and nothing from my side has changed (as far as I know) – I moved to UnlimitedHosting around May, but it did work following the move.

Thanks
Dave

**Comment by daveinhull** [comment]
Hello Paul,

I’m home form my work trip and I’ve done some testing, setup and test script below:

1.	Manual sync only
2.	Made sure that both desktop and laptop Outlooks were the same by forcing Google to Outlook or Outlook to Google, then 2-way sync works
3.	Existed both laptop and desktop versions of OGCS
4.	Delete both laptop and desktop logfiles
5.	Created new entry on my laptop Outlook – KeLing KL0?? 14 to 18 October 2024
6.	Started laptop OGCS, set debug to fine and did 2-way sync
7.	Entry is created in Google as expected [see screenshot file, page 1]
8.	Started desktop OGCS, set debug to fine and did a 2-way sync
9.	OGCS asks to delete the entry just created, said no, nothing created in Outlook [see screenshot file page 2]
10.	Changed to Google -> Outlook and desktop sync
11.	Entry created in desktop Outlook
12.	Changed to 2-way sync and desktop sync
13.	All worked, but status shows a number of entries being updated for some reason [see screenshot file, page 3]

I’ve uploaded the log files from both laptop (Laptop_OGcalsync.log) and desktop (Desktop_OGcalsync.log) 

I’ve also uploaded a word file with screen shots from the status windows as mentioned above.

Thank you for your help

Dave

**Comment by daveinhull** [comment]
Hi Paul,

Just wondering if you seen my last email and log file that I uploaded, any thoughts as I’ve stopped using OGCS at the moment as it makes the calendars completely unreachable, but would very much like to start using it again. It was great when it worked 😊

Dave

**Comment by phw198** [comment]
Sorry for the delay - taking a look now., thanks for the log files :+1: 

I think I see a fundamental problem here though - your Outlook calendar is connected to an Exchange account, correct? And that account is the same for both the laptop and desktop machine? If so, I don't particularly understand the reason for you syncing to Google - without Google or OGCS, both Outlooks would show your calendars up to date.

However! Your work laptop shows you connected to the Exchange server, but your desktop shows you _disconnected_ - so the items you create on the laptop are not showing on desktop; you need to sync the desktop Outlook with Exchange first before doing anything with OGCS.

So add the steps to your above test:
7.1 On the Desktop Outlook sync with Exchange, make sure the new item shows
7.2 Two-way sync with OGCS from desktop
7.3 Confirm no add or delete is happening at all

**Comment by daveinhull** [comment]
Hi Paul,

Thanks for getting back to me and I wasn’t meaning to rush you 😊

Just to answer your query first.

I use OGCS as follows.

While working at client sites I use my laptop and I often need to add diary event while doing that.

These must be uploaded to OGCS and I preferably using 2-way sync as I could have also added event in Google while traveling.

When I get home I start using my Desktop and yes I don’t need to worry about syncing the laptop and desktop events

However, I could have added further event while traveling home to Google which I won’t on my Desktop

And I cold also add more event on my desktop which I want on Google.

The use of OGCS isn’t to sync laptop with desktop, it is to keep Google updated with entries on both and also to one of the other (laptop/desktop) updated depending on which I use next with added Google events

Unless you can suggest a much simpler way, I could have overcooked the use case.

Thanks for the test update which I wil try, but I do think I’ve already done this without knowning, i.e. I switch of automaitc syncing on OGCS so it is now manual and therefore both machines have plenty of time to sync with the Exchage server.

However, I wil lgo through the test again as stated and keep track of the results. 

Thanks for your time on this, as I said it is a great tool.

Dave

**Comment by phw198** [comment]
OK, that makes sense with why you are using OGCS to sync to Google if you also need to manage calendar items there, but have them end up on Exchange too.

Before you sync with OGCS, you have to make sure the machine is fully synced with Exchange first. Your desktop had `Exchange connection mode: olCachedDisconnected` which means it only has an offline copy of the Exchange content from whenever you last synced with it. I'm guessing OGCS has been "misbehaving" ever since!

See, from OGCS's point of view, the desktop and laptop calendar are exactly the same thing - which they _are_ because it's hosted centrally on your corporate Exchange account. So when your desktop doesn't know about the new item because it's offline, OGCS thinks it has been deleted, so wants to delete in Google.

Hope that makes sense!

Hmm, a heads-up - when you put your desktop online, the items you have created with G->O sync, I think may actually show "duplicates" on Exchange. If so, you'd then need to delete one of them.

**Comment by daveinhull** [comment]
Hi Paul,
  
Yes, that makes perfect sence and thanks.
  
Does that mean i need to keep OGCS in manual mode to make sure that i get things synced before OGCS tries to sync?
  
Maybe OGCS    could haveca feature thatvwaits for the Outlook to go on line, or an option to do this    given it must know as its in the log files?
  
Best regards
Dave

**Comment by phw198** [comment]
If you can let me know if it does indeed resolve the behaviour, I can add a warning to the top of the screen when the sync starts. I think your setup is fairly unusual though, so not too sure about a new configurable option - it would be very hard to explain the risks of turning off/on.

**Comment by daveinhull** [comment]
Hi Paul,

Regarding the other point I mentioned, does this mean that I need to switch off automatic syncing and do it manually once I’m sure the laptop/desktop has synced with the exchange, I’m guess by the way you’ve explained it, that I will need to just do it manually?

Dave

**Comment by daveinhull** [comment]
Hi Paul,

Ok, so I did the following (and it still didn’t work):

1.	Automatic sync turned off
2.	Did a 2-way sync on my desktop to make sure everything was match between y desktop Outlook and Google
3.	Turned on my laptop and waited for the send and receive to finish
4.	Did a Google to Outlook sync which updated my laptop Outlook to be the same as my desktop
5.	Created a test entry on my laptop and did a 2-way sync with Google, Google got the test entry
6.	Did a send and receive on my desktop and waited until that had finished
7.	Did a 2-way sync between Google and my desktop Outlook
8.	It then asked me if I wanted to delete the test entry from Google
9.	I then went back to my laptop and did a 2-way sync and it asked me if I wanted to delete the test entry from Outlook (as it was now not in Google)

I may not have made it clear in the past, but I’m not using an exchange server, I’m using IMAP to my web hosted email account, does this make a difference?

I’ve been trying to think back to when the problem with OGCS started, because as I said it was working perfectly for since I installed it which must have been over a year ago.

The only thing I have done between installing OGCS and it working to now its not working is to change form POP to IMAP, again could this have an impact?


Sorry to cause so many problems.

Dave

**Comment by phw198** [comment]
OK, reminding me that it was IMAP (which explains why the cachedDisconnected I guess!) is useful. 

Still seems to be a missing part of the puzzle as to how you set up your desktop - as asked earlier, Outlook creates a calendar marked "IMAP calendar (this computer only)" as IMAP does not sync calendars (which would be why you are using OGCS)
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/d0de0e75-217d-43cc-bbb3-c70bdf8575e0)

By contrast, your calendar is just called "Calendar" and both your laptop and desktop have exactly the same ID: `Calendar (ID: 00000000F28F3338E911A44EA4A77ACC6CB2C972E28E0000)`

The simplest way to get out of this situation is to create a new calendar folder on your desktop (which will force a new ID) and then have OGCS sync with that new calendar. No change required on your work laptop.

**Comment by daveinhull** [comment]
Hi Paul,

OK, I’ll give that a go. This has also reminded me that I did have some issues with calendars a short while back, can’t remember the exact details, but I did have to do something, so this could have had an effect. Maybe I got something corrupt on my laptop and did a restore of the PST file from my laptop – that might mean everything would be identical, but not usre?

Anyway, I’ll give your suggestion a go and let you know what happens.

Thanks again
Dave

**Comment by phw198** [comment]
Hate to say it, but [my post on 10-Oct](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1709?notification_referrer_id=NT_kwDOALS1x7M3ODQ1MzcwNTgyOjExODQzMDE1&notifications_query=reason%3Aparticipating#issuecomment-1755398322):

> what I'm hoping/expecting to see is the ID behind each Outlook calendar is actually the same, which it shouldn't be if Outlook created them independently on both machines. Unless you did something funky with backing up PST files and restoring on the other computer??

**Comment by daveinhull** [comment]
Hi Paul,

Oh, no sorry I must have missed that…..apologies for wasting your time.

Dave

**Comment by daveinhull** [comment]
HI Paul,

Just wanted to say it all works perfectly (again) 😊

Again, sorry for wasting your time and lesson for me, read emails more closely 😊

Also, just to mention that I’ve donated, so thank you for all your help (and perseverance)

Best regards
Dave

**Comment by daveinhull** [comment]
Sorry, just one last thing, how do I now get rid of the splash screen and also sync further into the future?

Dave

**Comment by daveinhull** [comment]
Sorry, ignore last email, just got an email from OGCS explaining how to do it.

Dave

**Comment by daveinhull** [comment]
Hi,

You will be fed up of me before long , if not already 😊

Do I have to donate from both my installations of OGCS? And, is it possible to sync further ahead in the future than 365 days – I’m sure I saw somewhere that it is limited to 365 days if you don’t donate?

Dave

**Comment by phw198** [comment]
Hi @daveinhull and thank you for your donation :+1: 

The number of days into the future is [always a maximum of a year](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-cant-i-sync-more-than-1-year-past-or-future), regardless of donation, so that limited API quota doesn't get used up unfairly. The link has further information on why.

The only way around this is to set up your own API keys, which is under the "Advanced/developer options" on the Google tab - it's rather involved though and I purposefully don't provide support on that option :slightly_smiling_face:
