### ISSUE TITLE
Application Unexpectedly Terminated Error [0x8002802B]

### ISSUE THREAD

**Issue by nicastm** [phw198/OutlookGoogleCalendarSync#1710]
I'm receiving error 'Application Unexpectedly Terminated Error' when I run OGCS and I am not able to open the application.  I've uninstalled and reinstalled latest version Alpha v2.10..1-Alpha with same result. Attached is a photo capture of error.  Thanks, Mike

![Outlook Google Calendar Sync Error](https://github.com/phw198/OutlookGoogleCalendarSync/assets/47140713/41dd7802-934c-49ae-8311-073c83b5271d)

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by nicastm** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12774665/OGcalsync.log)

**Comment by phw198** [comment]
Seems the wiki redirect has broken due to changes on Github :slightly_frowning_face: 

:package: Please could you use [hotfix v2.10.1.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12775312/v2.10.1.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and see if it takes you to the wiki?

**Comment by nicastm** [comment]
Hi Paul, I applied the fix, but didn’t seem to work. The application won’t start now. I’ve attached the Log file

Thanks,
Mike

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by phw198** [comment]
Fix for wiki redirection was released in v2.10.2
