### ISSUE TITLE
The program is set to sync from outlook to google but ends up creating random entries of duplicated meetings back into outlook, Very annoying as outlook is my work calendar. Please fix this asap

### ISSUE THREAD

**Issue by csharmaGH** [phw198/OutlookGoogleCalendarSync#1713]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
As per the warning when raising the ticket, "FAILURE TO FOLLOW THE CHECKLIST MAY RESULT IN YOUR ISSUE SIMPLY BEING CLOSED! "
