### ISSUE TITLE
New Google Calendar Events Being Deleted Prior to Syncronisation

### ISSUE THREAD

**Issue by Billpherry** [phw198/OutlookGoogleCalendarSync#1714]
**OGCS Version**: v2.10.1.0
**Edition**: Installed
**Sync Direction**:  O<->G

**Bug Description**  
I keep facing an issue where I have created a new event in my Google Calendar, and when the app runs the sync, it seems that because it can't find the event in Outlook, it attempts to delete it from Google Calendar rather than the expected outcome of it being created in my Outlook Calendar. I currently have it set to confirm deletions but feel it shouldn't be doing this?

**Steps to Reproduce the Issue**  
1. Create entry in Google Calendar
2. Allow sync to take place automatically
3. Receive message to confirm delete yes/no

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12813852/OGcalsync.log)

I think I have supplied everything you need but please let me know if you need anything more?

**Comment by phw198** [comment]
I think it's do with your exclusion of Outlook categories and having the synced item deleted if excluded.

Your `Family` profile is copying from G->O and setting the category as "Yellow"? But your "Default" profile is set to exclude Yellow categories and delete the Google item.

Pretty sure I'm reading that right...

**Comment by Billpherry** [comment]
HI Paul,

I adjusted the setting you mentioned, but I'm still getting the same issue,
the entry exists in both google & outlook calendar but OCGS wants to delete
from Google, then next time it runs it will delete it from Outlook.

I've attached a screenshot below and the log file, hope this helps...

[image: image.png]

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

What settings did you adjust exactly?
