### ISSUE TITLE
Delete Outlook Items that were mis-synced

### ISSUE THREAD

**Issue by tpullano** [phw198/OutlookGoogleCalendarSync#1716]
Apologies on this but did a sync (one-way) from Outlook to Google. Selected the wrong Google calendar and want to back out these additions.

I read post #125 but do not see the googleEventID within my Outlook settings. Any other way to go about this ( I synced a year back and forward unfortunately )

**Comment by tpullano** [comment]
Cancel. Most were reoccurring meetings, so removed those and a few that were individual.

**Comment by phw198** [comment]
Glad it wasn't too much trouble to clear up!
