### ISSUE TITLE
Incorrectly reporting running multiple instances of OGCS with same configuration

### ISSUE THREAD

**Issue by joshdcurry** [phw198/OutlookGoogleCalendarSync#1717]
**OGCS Version**: v2.10.0.0
**Edition**: Portable  
**Sync Direction**: G->O 

**Bug Description**  
Issue 1. Application reports multiple instances running with the same configuration, but the instances are being launched with different configurations via the command line and instructions at https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Running-Multiple-Instances-of-OGCS.

Issue 2. You should update the instructions for multiple instances to note that using the cmd "start" requires a title or a blank double quote at the start (eg, start "" "c:\something long\run.exe") when your command line parameters have spaces in them. 

**Steps to Reproduce Issue 1**  
1. Launch two instances with different configurations via command line. Here are the actual lines from my batch file.

start "" "C:\Curry Data\Apps\Outlook Google Calendar Sync\OutlookGoogleCalendarSync.exe" /s:"C:\Curry Data\Apps\Outlook Google Calendar Sync\CurryFamilyCal\settings_fam.xml" /l:"C:\Curry Data\Apps\Outlook Google Calendar Sync\CurryFamilyCal\OGcalsync_fam.log" /t:"Curry Family Calendar"
start "" "C:\Curry Data\Apps\Outlook Google Calendar Sync\OutlookGoogleCalendarSync.exe" /s:"C:\Curry Data\Apps\Outlook Google Calendar Sync\JoshGmailCal\settings_jdc.xml" /l:"C:\Curry Data\Apps\Outlook Google Calendar Sync\JoshGmailCal\OGcalsync_jdc.log" /t:"Josh Gmail Calendar"

2. Notice the error window below pop up when the second command line runs

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/66935065/d799fd4c-ff7b-4fe1-be5e-fee191aa3b2c)

**Steps to Reproduce Issue 2**  
1. Run the batch file without double quote "" at the start of a line.  

start "C:\Curry Data\Apps\Outlook Google Calendar Sync\OutlookGoogleCalendarSync.exe" /s:"C:\Curry Data\Apps\Outlook Google Calendar Sync\CurryFamilyCal\settings_fam.xml" /l:"C:\Curry Data\Apps\Outlook Google Calendar Sync\CurryFamilyCal\OGcalsync_fam.log" /t:"Curry Family Calendar"

2. Notice error 

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/66935065/dad6db50-fcf3-4e0e-95fd-6480dc8115f3)

3. Resolution is to add double quote before the command "start" so you have this syntax: start "" "c:\something long\run.exe"

See resolution on this command line issue at https://www.donationcoder.com/forum/index.php?topic=33979.0#:~:text=If%20you%20want%20to%20use,title%20argument%20in%20double%20quotes.

**Any other information**  
Logs for both configs are attached.
[OGcalsync_jdc.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12885191/OGcalsync_jdc.log)
[OGcalsync_fam.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/12885189/OGcalsync_fam.log)

**Comment by phw198** [comment]
Thanks for reporting this and I've updated the wiki with the `start` syntax change :+1: 

:package: Issue 1 should now be resolved with [hotfix v2.10.1.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13064871/v2.10.1.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.
