### ISSUE TITLE
Moved Outlook item (click and drag) incorrectly deleted instead of synced (2-way)

### ISSUE THREAD

**Issue by PistaG** [phw198/OutlookGoogleCalendarSync#1718]
**Are you already using OGCS?**
2.10.0.0.

**Describe the question you have**
using OGCS since 3+ years, problem arises from time to time, unable to identify reason:
newly added Outlook items do not synchronise to GOOGLE, instead OGCS wants to delete them all the time.

when I check the synchro settings, OGCS identifies ***@gmail.com as my primary calendar, which is a stupidity (although I have also this email account in Outlook).
My primary calendar is an ***@outlook.com calendar, which I want to synchronise with my Google calendar, so that I can see all items added in the Outlook.com calendar (in Outlook desktop) also on Google and vice versa.

it is extra annoying to always tell OGCS that I DO NOT WANT TO DELETE those items in Outlook... they should be copied to GCAL...
obviously synch is set bidirectional...
 
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/128482570/daa6dfe9-c062-4bbf-b384-f4c35374bafb)

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/128482570/158070f1-61b0-40a7-a508-db26eb87a747)

so in both Outlook and Google the same account seems to be the connected one?

thanks for any help/hint

**Comment by phw198** [comment]
I think you're reporting two different things, and I'm not sure they are related.

For the primary calendar in Outlook, your screenshot shows the gmail account under "Alternative mailbox" - ie not your primary account. That seems quite correct to me.

For the incorrect deletions from Outlook, is it _only_ the new items that are subject to deletion, or all/any of the ones already synced? If only the new ones, I suspect you are copy and pasting items that are already synced and OGCS isn't [running in the background](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#outlook-appointment-copy--paste)...

**Comment by PistaG** [comment]
Hi Paul,

thanks for coming back.

With the primary/secondary – yes you are right, I was mislead by the interface (default mailbox does not give ANY info on which is the default – could be shown eventually) – so this is not relevant

It is not only new items – it happens frequently with items I move to a different date (e.g. I have a „do this week“ type of event on Sunday, which at the end of the week I move to next Sunday (drag-n-drop, contentwise edited frequently).

OGCS runs in the background all the time.

Maybe to note that I have many cases when I make copies of events in Outlook and there is no issue at all. (just renaming the new one afterwards – I do not know whether it is then identified as one and the same already synched event?) 

Thanks, hava fine day
Stefan

PS. Donating through the interface does not remove the slash screen 😊

**Comment by phw198** [comment]
What date range are you syncing? If you are not syncing days in the past, and you move a single synced item from the past (eg yesterday) to the future, that would make it get deleted for a two-way sync. Maybe try increasing the sync window to further in the past. To troubleshoot any further, I would need your OGcalsync.log file that covers the issue after it has happened.

For the donation, can you forward me the PayPal donation email so I can check it got processed properly?

**Comment by PistaG** [comment]
Hi, increased tthe window to -30 days, the issue persists
Log attached
S

PS. Donation was maybe 2-3 years ago, I do not have any records anymore.

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by PistaG** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13205139/OGcalsync.log)

**Comment by phw198** [comment]
Your log file just shows your starting the OGCS application - there's nothing of use in it.

> To troubleshoot any further, I would need your OGcalsync.log file that covers the issue after it has happened.

ie. you need to reproduce the error:
1. Perform a sync that runs without deletion prompt <sup>[1]</sup>
2. Perform the item move in Outlook which you say causes the error
3. Run a sync to produce the delete prompt
4. Upload your log file

<sup>[1]</sup> I think v2.10.2 feature "When deletion prompt is declined, sync item instead" may help you here.

> Maybe to note that I have many cases when I make copies of events in Outlook and there is no issue at all. (just renaming the new one afterwards – I do not know whether it is then identified as one and the same already synched event?)

What's the relevance of that to this issue? I thought you were saying you were _moving_ the item by click and drag, which caused the problem? Or are you copying the item by click and drag (pressing `Ctrl`)?

**Comment by PistaG** [comment]
Hi Paul, 

thanks for following up.

Added a new actual log + screenshots of the symptom on Github.

 

"When deletion prompt is declined, sync item instead" – I do not know where this feature is enabled:

 





 

------------------------

Created a new dummy event in Outlook:

 



 

Run synch

Calendar event in Google created without issues

 

NOW, moved (drag-drop) event in Outlook:



 

RUN synch again

 

This MOVED event synched nicely (attributes updated), without any error message...

 



 

Still the other problematic events create error messages.

 

Hm

Will try to delete those and create them anew

 

S

**Comment by phw198** [comment]
> Added a new actual log + screenshots of the symptom on Github.

Where was this? The post by email won't show images or attachments...

I think you need to work out the sequence of events to clearly reproduce the issue you're having first though, then upload you logfile that captures that.

**Comment by phw198** [comment]
Oh, looks like you posted to issue 1494!? I'll move them here...

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13248738/OGcalsync.log)
[example screenshots.docx](https://github.com/phw198/OutlookGoogleCalendarSync/files/13248746/example.screenshots.docx)

**Comment by phw198** [comment]
Yeah, I don't really know what I'm looking at. Some random deletes - but no idea if they are related to a click and drag or not.

Like I said before, get a sync running first without any deletion prompts ([further guidance here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-%26-Tips/_edit#fixing-a-stubborn-unwanted-deletion-with-full-sync)), and then produce the issue on a specific test case.

> "When deletion prompt is declined, sync item instead" – I do not know where this feature is enabled:

The words before that gave a clue - you need to upgrade to the latest alpha:

> **I think v2.10.2 feature** "When deletion prompt is declined, sync item instead" may help you here.

**Comment by PistaG** [comment]
At last I simply deleted the two problematic entries, created new ones (with the same subject and contents) – it helped.

Since then I moved those items and they synced perfectly.


Well. Lets close it for now.

Have a fine day

S
