### ISSUE TITLE
How to get multiple calendars synced automatically

### ISSUE THREAD

**Issue by stefanhoerth** [phw198/OutlookGoogleCalendarSync#1719]
**Are you already using OGCS?**
Provide the version number. 2.10.1.0

**Describe the question you have**
I have configured OGCS with 2 profiles to get 2 different calendars in Google and 2 different in Outlook synced. However it always takes just 1 profile which has been selected, although both profiles are set with Auto-Sync.

How can I get OGCS to sync both calendars automatically without the need to change the profile manually?

**Comment by phw198** [comment]
> although both profiles are set with Auto-Sync

Can you confirm this means that you have set both profiles to have a non-zero value for "Schedule every" under the "When" settings section?

**Comment by chroberino** [comment]
> > although both profiles are set with Auto-Sync
> 
> Can you confirm this means that you have set both profiles to have a non-zero value for "Schedule every" under the "When" settings section?

I was looking for the same feature (snyc multiple calendars) and just stumbled across this issue.
I can confirm this is working with v2.10.0.0, having multiple profiles and configuring the "When" sections in each profile works like a charm!

Thank you Paul, I appreciate your work on this very helpful tool and will donate!

**Comment by phw198** [comment]
Thanks @chroberino!
