### ISSUE TITLE
Different privacy in each direction?

### ISSUE THREAD

**Issue by torbengb** [phw198/OutlookGoogleCalendarSync#1723]
I am running OGCS v2.9.6.0 on Windows 11 to sync from Outlook365 (desktop application) to my personal Google Workspace calendar. 

`Outlook-->Google` works fine with these settings:  
[x] set privacy to `public`  <------ this is relevant
[x] set availability to `busy`  
[x] set color/category to `banana` (yellow)  
`10` days in the past  
`40` days in the future

**Now I want to sync in both directions, but I want the "privacy" setting to be different in each direction:**  
Outlook-->Google = `public`  (so that my family can SEE my work details)  
Google-->Outlook = `private` (so that coworkers can NOT see my private details)  

It seems that this is not possible. It seems that the "privacy" setting is always one value, either private or public, for both directions.

Also, when I tried this, I ended up with several duplicates on both sides. It's as if a work event gets copied to Google, then that event gets copied to Outlook (now I have two in Outlook), then that new event gets copied to Google again, and so on.

**Comment by phw198** [comment]
Duplicates definitely shouldn't be happening under any scenario

If you are syncing to the same Outlook and Google calendar, then I can't quite see how this would work in concept anyway, regardless of OGCS settings - either everything would end up private or everything public.

I think you would need at least need:
* a separate "work" Google calendar
   * Profile A to sync O -> G(work) with setting everything to public *
   * Exclude the category "Personal" or exclude private items **
* for your "personal" Google calendar
   * Profile B to sync G(personal) -> O with setting everything to private
   * If you don't exclude private items in Profile A, set a category "Personal" 
   * Set the "merge" option on

\* You don't really need to set anything specific here - this is more down to the permissions you grant when you share your calendar with the family's Google accounts. You can set the entire calendar to a colour (eg yellow) too, so no need to do that with OGCS either.
\** This requires the latest alpha release
