### ISSUE TITLE
v2.10.2.0: Exclusion on subject fails when subject is NULL

### ISSUE THREAD

**Issue by SVNKoch** [phw198/OutlookGoogleCalendarSync#1731]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.2.0
**Edition**: Installed
**Sync Direction**: G->O

**Bug Description**  
Since the last version, OGCS doesn't want to sync my events anymore. I always get the "Event does not have Outlook EntryID stored." error and then "Failed to retrieve master for Google recurring event outside of sync range.".
This still happens when re-connecting google account, restarting the application and starting a full sync.

Previous version v2.10.1.0 didn'T have the issue. After downgrading again, it works flawlessly again too.

**Any other information**  
[relevant.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13308256/relevant.log)

**Comment by phw198** [comment]
Hi @SVNKoch, I think you need the hotfix on #1725.

**Comment by SVNKoch** [comment]
sorry for the late reply, just applied the patch and everythink seems to work fine (not sure though if the "problematic" event is still in my date range 😅)

**Comment by SVNKoch** [comment]
I changed the setting to exclude certain subjects
now getting the "Failed to retrieve master for Google recurring event outside of sync range." again with another error following it:
System.ArgumentNullException: ... Location: IsMatch() in <Unknown File>
[log1731-1.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13675416/log1731-1.log)

**Comment by phw198** [comment]
:package: I've pulled together #1725 and #1738 (which I think you might benefit from) and also applied a specific fix on [v2.10.2.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13692723/v2.10.2.10.zip) for your recent issue.

Please let me know how it goes.
