### ISSUE TITLE
Won't sync now

### ISSUE THREAD

**Issue by Perkin5** [phw198/OutlookGoogleCalendarSync#1732]
I have installed the latest version and it originally worked but now won't, even after reinstallation. I have attached the log.

Can you advise?

Mike

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13325175/OGcalsync.log)
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13325176/OGcalsync.log)

> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13325176/OGcalsync.log)

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by Perkin5** [comment]
Ah! I solved it myself! The new date I was trying to sync was beyond the 60 day period in the settings. I extended it to 100 days and it synced immediately.

**Comment by phw198** [comment]
Glad you worked it out! :+1:
