### ISSUE TITLE
Occasional error alerts halt syncing, how to continue syncing automatically?

### ISSUE THREAD

**Issue by bdruth** [phw198/OutlookGoogleCalendarSync#1735]
**Are you already using OGCS?**
2.10.0.0

**Describe the question you have**
Occasionally a sync error will pop-up a dialog that requires interaction, seemingly, and syncing stops until that dialog is dismissed. This makes it difficult to run the sync on a machine in the background that's non-interactive, as the errors tend to happen every day or two (usually "connection to Google was closed" or something of that ilk).

Is there any setting or capability to log the issue instead of alerting & blocking further syncs? Every time I've had an issue, the subsequent sync works perfectly fine, so the errors are non-fatal and don't require any "fix" from me other than dismissing the alert.

**Comment by phw198** [comment]
Hi @bdruth I think this is already covered by #1190. Thanks for raising this though, it's reminded me to give it some further thought...

If you're able to provide any logs from when you have hit this, it might be appropriate to simply log it as a warn and not a blocking error/pop-up.

**Comment by bdruth** [comment]
I'll look for the logs the next time it happens. Thanks!!
