### ISSUE TITLE
I donated but it didn't let me change anything

### ISSUE THREAD

**Issue by cwhittl** [phw198/OutlookGoogleCalendarSync#1739]
**Are you already using OGCS?**
Provide the version number.

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

**Comment by phw198** [comment]
Thanks for the donation @cwhittl - I can see it came in at at 13:20 GMT, 6 minutes before you logged this issue, and you would have immediately received an email with details of how to hide the splash screen.

Hope that helps? Thanks again 🙂

**Comment by cwhittl** [comment]
all good now!
