### ISSUE TITLE
2.10.2 Alpha - Syncing from canceled events from Outlook to Google.  Similar to Bug #1633

### ISSUE THREAD

**Issue by The2ndGrim** [phw198/OutlookGoogleCalendarSync#1740]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v 2.10.2  
**Edition**: Installed  
**Sync Direction**:  O->G

**Bug Description**  
When canceled meeting (where I am an attendee, not the owner, and therefore not canceling the meetintg) in Outlook is synced to Google, cancellation email is generated.  That email fails because ".ogcs" is appended to all attendees' email addresses and the email fails.  Two things - First, I don't understand the .ogcs appending.  Second, I don't understand the reason for the email, since I did not cancel the meeting, I'm merely accepting the cancelation and deletion.

**Steps to Reproduce the Issue**  
1. Be an attendee of a synced Outlook meeting.
2. Have the owner cancel the meeting.
3. Accept the cancelation.
4. Re-sync.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by The2ndGrim** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13494356/OGcalsync.log)
[OGcalsync.log.2023-10-17.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13494375/OGcalsync.log.2023-10-17.log)
[OGcalsync.log.2023-10-26.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13494376/OGcalsync.log.2023-10-26.log)
[OGcalsync.log.2023-10-27.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13494377/OGcalsync.log.2023-10-27.log)
[OGcalsync.log.2023-11-15.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13494378/OGcalsync.log.2023-11-15.log)

**Comment by phw198** [comment]
Yes, the same as #1633 and the same response: not an OGCS bug and careful workaround to very long-standing Google bug - have a [read through the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-am-i-getting-undeliverable-notifications-from-google-for-recipients-ogcs) for more information.

**Comment by The2ndGrim** [comment]
Thank you, Paul!-sOn Apr 3, 2024 10:02 AM, Paul Woolcock ***@***.***> wrote:
Closed #1740 as completed.
