### ISSUE TITLE
New event failed to save. Calendar Usage attendee limit exceeded [403 Forbidden]

### ISSUE THREAD

**Issue by sprayeddog** [phw198/OutlookGoogleCalendarSync#1744]
**OGCS Version**: v2.10.2.0
**Edition**:  Portable  
**Sync Direction**: O->G

**Bug Description**  
Started a month or so ago, OGCS used to work fine. But now every time I run OGCS to do O -> G sync, I keep running into error that says 

**"New event failed to save. Calendar usage exceeded [403 Forbidden]"** 

Worse, OGCS sync just pause, and I must click "Yes" to continue, thus it does not sync the rest of the calendar events that it can sync. 

**Steps to Reproduce the Issue**  
1. Running the OGCS any time will repeat this issue

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13561007/OGcalsync.log)

**Comment by sprayeddog** [comment]
And just to add to this problem, when I tried removing "Attendees" from the sync option, everything works again. So I think the 404 Forbidden has to do with the # of attendees (maybe Google is trying to send repeated invite to those attendees for every meeting that it creates? I sure hope not)

The only downside is i am completely blind to the list of attendees for meetings, but that is the best compromise for now

**Comment by phw198** [comment]
Thanks for reporting this - it's due to a change in the way Google is reporting this.

:package: Could you re-enable sync of attendees and then try with [hotfix v2.10.2.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13613322/v2.10.2.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by sprayeddog** [comment]
Applied the hotfix and so far so good! Thanks!

**Comment by phw198** [comment]
Did you receive a warning in the sync window as per the following?
> You have added enough meeting attendees to have reached the Google API limit.
> Don't worry, this only lasts for an hour or two, but until then attendees will not be synced.

Would be good if you could upload your logfile so I can confirm if you have hit the API limit or not yet...

**Comment by sprayeddog** [comment]
Yes i see that warning message. 

Attached the log file
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13619835/OGcalsync.log)

**Comment by phw198** [comment]
I only see one sync on the hotfix in the logfile and it doesn't have anything to create in Google, so I don't think this has tested the fix yet.

This also shows it wasn't detected for today, so I think we need to wait a bit longer to confirm it's properly fixed.
> API attendee limit in effect: False
> API attendee limit last reached: 2023-07-14 2:27:32 PM

**Comment by sprayeddog** [comment]
Sounds good, thanks! Will keep an eye for calendar items with large invitee list

**Comment by phw198** [comment]
Hi @sprayeddog, just checking in to see if the date in the log line is more recent than `API attendee limit last reached: 2023-07-14 2:27:32 PM` yet?

**Comment by phw198** [comment]
I will pull this in to the next release anyway.
