### ISSUE TITLE
Syncing several calendars

### ISSUE THREAD

**Issue by mll0** [phw198/OutlookGoogleCalendarSync#1747]
**Are you already using OGCS?**
Provide the version number : 2.10.0.0

**Describe the question you have**
Hi,
I'd like to sync 2 calendars:

- Google Calendar A -> Outlook Calendar A
- Google Calendar B -> Outlook Calendar B

Is there any way to achieve this?

**Comment by phw198** [comment]
[Sure is](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars)!

**Comment by mll0** [comment]
Thank you!
