### ISSUE TITLE
Sync Settings Not Being Retained

### ISSUE THREAD

**Issue by WarningU2** [phw198/OutlookGoogleCalendarSync#1749]
> Checklist:-
> * [Y] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [?] Reproduce the issue
> * [Y] Complete the information below
> * [Y ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0.0  
**Edition**: Installed
**Sync Direction**:  O<->G

**Bug Description**  
After setting up Sync settings and options all is good but a few days later they are dropped again and I have to redo.  This is a new behavior. 

**Steps to Reproduce the Issue**  
1. It happens every few days so not able to reproduce intentionally.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13628933/OGcalsync.log)

**Comment by phw198** [comment]
You've said you've upgraded to the latest alpha but are running v2.9.0 which is ancient...

:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

Remember you do have to click `Save` after making changes you want to persist beyond a restart of OGCS.

**Comment by WarningU2** [comment]
I prefer not to run the alpha release as a few months ago it caused all sorts of issues.   I checked for the latest regular update and it says this is current.

**Comment by phw198** [comment]
Could you provide the logfile for when you check for an update? Unless you previously chose to skip v2.10.0, it should be reporting that is available.

Either way, however, I'm not able to provide support for old releases, only the latest alpha.

**Comment by WarningU2** [comment]
Upgraded to 2.10.2.0.   Initially downloaded 2.10 and then used the upgrade button successfully.  Not sure why upgrade from 2.9 didn't work.   Closing

**Comment by WarningU2** [comment]
Upgraded to 2.10.2.0.   Initially downloaded 2.10 and then used the upgrade button successfully.  Not sure why upgrade from 2.9 didn't work.   Closing
