### ISSUE TITLE
Duplicate events in Outlook even after deleting the OutlookGoogleCalendarSync application.

### ISSUE THREAD

**Issue by sapnesh-naik-pitcher** [phw198/OutlookGoogleCalendarSync#1751]
Hi, 

I installed this application few weeks ago on my Windows system to sync my work outlook Calendar events to my personal Google account (GoogleWorkspace account). I then noticed that for some reason all outlook events in my work calendar were duplicated in Outlook with my personal Gmail as the organizer/owner and adding all participants (colleagues work emails!). I had to go to my personal Google Calendar and cancel these events one by one. I deleted this application right away then because it was a risk.

But since then this issue has happened multiple times. Outlook Events are still getting duplicated even after deleting this application from my Windows system.

Apologies as I do not have any log files or details of what version of this app I installed. As I uninstalled this application long ago. Only other details I can provide are, I have a windows and a Mac system and the personal email was synced with the Mac Calendar. 

Please help resolve this issue.

**Comment by phw198** [comment]
>  deleted this application right away then because it was a risk. But since then this issue has happened multiple times. Outlook Events are still getting duplicated even after deleting this application from my Windows system.

I'm curious why you believe OGCS is the cause of this behaviour when it's not even running or installed? Even when you had OGCS installed, assuming you had it configured to sync from Outlook to Google as you described, then there is no way it created these duplicates in Outlook in the first place.

Given you say you have personal email (do you mean the personal Google workspace account?) synced to your Mac, maybe investigate what your Mac is doing?
