### ISSUE TITLE
Duplicate Creation

### ISSUE THREAD

**Issue by rhonabwymcneill** [phw198/OutlookGoogleCalendarSync#1756]
**OGCS Version**: v2.10.0.0
**Edition**: Installed
**Sync Direction**: G->O 

**Bug Description**  
With multiple profiles and all set to merge with existing entries, with one profile in outlook duplicates are created

**Steps to Reproduce the Issue**  
1. Have 1 profile G<->O
2. Have 1 profile G->O
3. Set "Merge with existing entries" for both profiles
4. Select profile G->O
5. Click on "Start Sync"
6. Wait for Sync
7. Click on "Start Sync" again

**Any other information**  

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/154022380/e260186a-bd77-4b7b-a068-6613c0edbc6b)
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/154022380/d056d4d1-3971-4557-b424-fb5480d98e13)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13693950/OGcalsync.log)

**Comment by rhonabwymcneill** [comment]
Deleting profile creating bug and create it anew seems to fix the issue.

**Comment by phw198** [comment]
You didn't happen to take a backup of your `settings.xml` file before deleting and recreating the Profile did you? I can only surmise there is a difference between the deleted Profile and how you configured the new one...

**Comment by rhonabwymcneill** [comment]
unfortunately not.
but as far as I remember, there were no differences to be seen at the frontend.

**Comment by phw198** [comment]
For the most part, the settings are actually logged at the start of a sync, so might still be worth comparing the file you uploaded previously with the log for the syncs that are now working OK.

For the record, the original behaviour you reported, I would expect:

* Kalendar (O) <-> Default (G) : without merge
* Kalendar (O) <- Familie (G) : with merge

Items on the Google Familie calendar will be added to Outlook, regardless of items that are there (eg synced from other calendars such as the default Google calendar). If you have the "same" Tanzen item in both Google calendars, they will be "duplicated" in Outlook.

**Comment by rhonabwymcneill** [comment]
Both with merge was the original configuration.
the item in the family calender is not present at the default calender, so that is not the reason for duplication

**Comment by phw198** [comment]
@rhonabwymcneill Could you confirm if the issue remains on v2.10.2? After upgrading, could you do a full sync by pressing the `Shift` key when clicking `Sync` (for the two way sync, you will need to temporarily switch it to one way, full sync, switch to the other, full sync, then back two-way).
