### ISSUE TITLE
Error at startup [0x080040154]

### ISSUE THREAD

**Issue by PaulNocero** [phw198/OutlookGoogleCalendarSync#1757]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

When program starts (Windows 11, Outlook365) I get this pop-up message:

"A problem was encountered when searching for Outlook calendar folders,
Class not registered (Exception from HRESULT: 0X080040154
(REGDB_E_CLASSNOTREG))

Log file: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13747172/OGcalsync.log)

**Comment by phw198** [comment]
OGCS should automatically [redirect you to the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040154---regdb_e_classnotreg), which contains all the known information about such errors.

Do you actually have Office installed, or are you just using the "New Outlook"?

**Comment by PaulNocero** [comment]
I have Outlook 365 (part of Office 365) installed, and am NOT using the "New Outlook."

**Comment by PaulNocero** [comment]
Even with this error, the synchronization appears to work correctly.  But the app shuts down, not staying active.  Is there any way I can force this app to keep running after it informs me of the error?

**Comment by phw198** [comment]
OGCS doesn't shut down, but it does disconnect from Outlook after a sync if you don't have Outlook already running.

So you just need to have the Outlook client running, then OGCS remains connected to it between syncs and you'd only get this error on the first sync.

**Comment by PaulNocero** [comment]
Yes, when I set the option to minimize to tray and not terminate the application, it all seems to work fine, just ignoring the error at starttup.  Thanks for the feedback.
