### ISSUE TITLE
Event created on google calendar arrives on Outlook calendar as an invitation

### ISSUE THREAD

**Issue by Colinp2p** [phw198/OutlookGoogleCalendarSync#1759]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
When I create an event on my Google calendar it arrives on my ios outlook calendar as an invitation.  If I decline the invitation the event is not added to my outlook calendar.  If I accept it, it  is added but I can't then delete it on ios.  I am a new user so I wonder if I am doing something wrong.
I hope I have supplied enough information

Thanks in advance for your help.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13767245/OGcalsync.log)

**Comment by phw198** [comment]
> When I create an event on my Google calendar it arrives on my ios outlook calendar as an invitation. 

I'm not quite sure the behaviour you describe has anything to do with OGCS? Sounds like you are maybe adding your iOS account as an attendee to your Google event, and then you are also connecting your Outlook client to your Apple calendar as well. If so, OGCS isn't causing any of that and, quite possibly, isn't even needed...

**Comment by Colinp2p** [comment]
Thanks Paul,

You are right – it had nothing to do with OGCS. My Google account was adding the entry to an Outlook account which was then mirror the entry on another account which seemed to turn it into an invitation.  Overly complicated so I have simplified things now and it is all working as it should.

Thanks very much.

Kind regards
Colin
