### ISSUE TITLE
Multiple Calendar Sync

### ISSUE THREAD

**Issue by barriekenyon** [phw198/OutlookGoogleCalendarSync#1761]
I user OGCS to sync my desktop Outlook and Gmail calendars. It is an excellent product - well done.
My wife has now started to use it as well, however she wants to sync her calendar with mine.
Is there a way to sync my desktop calendar with 2 Gmail calendars (mine and hers)? This would provide sync from my desktop to my Gmail and her Gmail, and then from her Gmail to her desktop.

Syncing the 2 Gmail calendars seems like a simpler task (both on the web) than syncing 2 Outlook calendars.

Please let me know if this is possible, or will be considered for a future release.

Many thank, and keep up the good work!
Barrie Kenyon

**Comment by barriekenyon** [comment]
Another thought!
Is it possible to add colour to a calendar post. Eg. red for Outlook posts, pink for Gmail posts.
And then of course - Blue for my Outlook posts, pale blue for my Gmail posts.
This would enable you to see where to post originated, if it was mine or my wife's, etc.
I seem to full of good ideas (or something) at present.
Happy New Year!!!
Barrie

**Comment by Philipp0205** [comment]
Your question might be [answered here.](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars)

**Comment by phw198** [comment]
Thanks @Philipp0205 for jumping in with the wiki link - that would be the answer, running two instances of OGCS if your wife's  Google calendar is on a different account to yours.

Though I do think that's over complicated. You can just sync from Outlook to Google and then share the Google calendar with her. If she then wants that Google calendar in her own Outlook, she runs OGCS herself to do that too.

Yes, [colour/category sync is an option](https://www.outlookgooglecalendarsync.com/guide/syncoptions), but again, you probably don't need it - sync to a dedicated Google calendar and set the colour for it in Google.
