### ISSUE TITLE
Default Google setting after upgrade from 2.10.0.0 to v2.10.2.0: EXCLUDE all + DELETE if excluded

### ISSUE THREAD

**Issue by luk4sschr0d3r** [phw198/OutlookGoogleCalendarSync#1764]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: Upgrade from stable v2.10.0.0 to alpha v2.10.2.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
- I used OGCS v2.10.0.0, and syncing maintained the calendar entries in O and G
- The upgrade to v2.10.2.0 defaulted the Google settings to: **EXCLUDE all** (color) categories, and DELETE synced items if excluded.
Result: **all** previously synced entries were deleted from Google.

- The Filter colours dropdown on the Google tab is "EXCLUDE" then "INCLUDE".

**Comment by phw198** [comment]
Thanks for reporting, but I can't replicate this behaviour:-

1. Run OGCS on v2.10.0
2. Use the same `settings.xml` file and run v2.10.2
3. "Filter colours" is set to "Exclude" and the colour checkbox list is empty
4. Click "Retrieve calendars" and the colour checkbox list is populated and none of them are checked

The setting.xml before and after v2.10.2 also confirms:
```xml
<Colours xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
<ColoursRestrictBy>Exclude</ColoursRestrictBy>
```

So I can only assume you accidentally checked all the boxes somehow?
