### ISSUE TITLE
Unable to communicate with Google services due to enterprise policies?

### ISSUE THREAD

**Issue by sug24** [phw198/OutlookGoogleCalendarSync#1765]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: alpha v2.10.2.9  
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description** :
I have used OGCS for years without any problems on a corporate machine. But something has changed since the beginning of December 2023. Since then I get errors like "unable to communicate with Google services, error 403" from the remote server. At the end of the Google authentification process the browser says: unable to contact server 127.0.0.1:54954. Having read the logfile, it seems to me that the enterprise policies have changed and won't allow to contact Google Calendar?

**Steps to Reproduce the Issue**  
I used OGCS v2.10.1, 2.10.2, 2.10.2.9 - always the same error. I changed the proxy settings - still the same result.

**Any other information**  
At the same time I email the logfile to the developer.

**Comment by sug24** [comment]
Correction: It is actually possible to use Google Calendar on the corporate PC, but OGCS won't sync anyway.

**Comment by sug24** [comment]
Great! v2.10.3-alpha solved my problem! Thank you so much! This is worth a donation!

**Comment by phw198** [comment]
Glad you got it working!
