### ISSUE TITLE
G Sync EOL and OCGS

### ISSUE THREAD

**Issue by regularITguy** [phw198/OutlookGoogleCalendarSync#1766]
V 2.10.0

The company I work for is a Google shop but we are currently using the native G Sync client to enable users to work in Outlook if preferred. Google is going to sunset G Sync 30 September 2024 so that will no longer be an option. I was looking for a replacement and found OGCS but it looks like this app is reliant on G Sync so will this app no longer function when G Sync is sunset? Below is the article from Google about sunsetting and EOL support.

https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html

**Comment by regularITguy** [comment]
For context, I was trying to do an install of OGCS and had uninstalled all previous G Sync and Outlook profile data. During the install I received the error below so it looks like OGCS needs G Sync to run but G Sync will be sunset in September so will OGCS not work after Septmber?

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/156204559/1e79ffbb-fea0-4b0c-8743-6e63f4d67e76)

**Comment by phw198** [comment]
No, there should be no dependency on G Sync - that would be kind of crazy given OGCS was built to fill the void created by Google killing the consumer version of G Sync 🙂 

I've never seen anyone report that error you posted; could you provide your OGcalsync.log file, so I can see exactly when this error occurs?

**Comment by phw198** [comment]
From a [quick Google](https://www.google.com/search?q=mapi+was+unable+to+load+the+information+service+gsync.dll&oq=mapi+was+unable+&gs_lcrp=EgZjaHJvbWUqBwgCEAAYgAQyBwgAEAAYgAQyBwgBEAAYgAQyBwgCEAAYgAQyBggDEEUYOTIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDINCAcQABiGAxiABBiKBTINCAgQABiGAxiABBiKBdIBCDg3NzBqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8#ip=1), appears to be a common issue and I would expect your Outlook client to not be working correctly even before you try and use OGCS. 

> had uninstalled all previous G Sync and Outlook profile data.

Essentially your uninstall has derigstered the G Sync dll, but Outlook is still trying to invoke it (triggered by OGCS in this case), so [Microsoft blocks it](https://support.microsoft.com/en-gb/topic/how-to-allow-mapi-to-load-unregistered-provider-dlls-18d9a1cd-d3d7-fa10-473e-5dfd62d38b0d) loading as a security mechanism.

Question is, how do you _fully_ uninstall G Sync, so Outlook doesn't know anything about it? Struggling to find anything helpful on Google for that...

/edit

Aside from an [uninstall and reinstall of Office](https://www.reddit.com/r/Office365/comments/bdh28r/g_suite_with_outlook_cannot_send_messages_error/) 😬
