### ISSUE TITLE
Attendees’ email addresses are modified with “.ogcs” suffix in Google Calendar after running a sync

### ISSUE THREAD

**Issue by emiliaanoldz** [phw198/OutlookGoogleCalendarSync#1767]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0.0  
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I create a Google Calendar event with all the attendees, then OGCS syncs the events in my Outlook correctly, but when I go back to Google Calendar, I see that the email addresses are appended with a ".ogcs" at the end, for example, "email@example.com.ogcs" making google not to recognize the Google Account of the attendee and also erasing the RSVP.

![Screenshot of how it looks like in Google Calendar](https://i.imgur.com/8Vc6I1M.png "Screenshot")

**Steps to Reproduce the Issue**  
1. Create a Google Calendar event and add a few attendees.
2. Sync with OGCS the latest changes to add the events in the Outlook application.
3. Check Google Calendar and the attendees you initially created are now modified; they were appended with '.ogcs' on their email addresses. The RVSP were lost as well.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

[Gist File](https://gist.github.com/emiliaanoldz/339c4676e2572ff990705e4d44f2eb31)

**Comment by phw198** [comment]
This one falls firmly in the "not a bug, but [a feature](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-am-i-getting-undeliverable-notifications-from-google-for-recipients-ogcs)" camp. 

Turn off "Cloak email in Google" if you want emails synced without `.ogcs` appended.
