### ISSUE TITLE
Duplication of events

### ISSUE THREAD

**Issue by giuseppe-r2m** [phw198/OutlookGoogleCalendarSync#1768]
**OGCS Version**: v2.10.2.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Our company uses calendar for its events.
In various cases, when I accept the invitations from Outlook, a duplicated entry is created in Calendar, with consequent mess at company-level.

I suspect - but I am NOT sure - that this happens when I accept the event tentatively.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13902390/OGcalsync.log)

**Comment by phw198** [comment]
You've set your logging level to `ERROR`, so there's nothing useful in it to help troubleshoot. As a minimum, I'd need to be able to see how you've configured the sync settings, but ideally the logs need to cover the sync that actually creates a duplicate...

Please also clearly explain the sequence of events - where does the invite come in to that you tentatively accept? Outlook or Google? The duplicate appears in which calendar? After what action? A subsequent accept of the same meeting?
