### ISSUE TITLE
Only show sync notifications if change(s) detected

### ISSUE THREAD

**Issue by huskylogic** [phw198/OutlookGoogleCalendarSync#1769]
**Are you already using OGCS?**
Provide the version number.   Version	2.10.0.0

The settings I have for testing purposes is to sync every 2 minutes.  The option for pushing changes right away isn't working so I set it to sync on a shorter interval.  Is there a way to set up what notifications I get? I have it looking every two minutes, but often I don't have anything to sync.  Is there a way to turn off the notifications unless there was something to sync?

**Comment by phw198** [comment]
No, currently it's only sync notification on or off - so that's a good enhancement request. Should be pretty straight forward, and I might make use of that myself actually 😉

**Comment by phw198** [comment]
:package: This should now be available with [hotfix v2.10.3.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14643469/v2.10.3.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `D26C42A7` Exe = `97E197B0`

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/6d781981-47be-4ce0-aef9-95d7f55a7ca8)

Let me know how it goes if you give it a try.
