### ISSUE TITLE
Some Entries dont sync on 2.10.0.0

### ISSUE THREAD

**Issue by Zeis76** [phw198/OutlookGoogleCalendarSync#1772]
i have some entries  which wouldnt sync ? One of my entrie goes 3 Days 24.5-27.5 but it wont sync . Other entries are work. Can you fix it ?

**Comment by phw198** [comment]
Not unless guidance to receive support is followed....you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
