### ISSUE TITLE
Application Unexpectedly Terminated - Cannot bind to the new display member

### ISSUE THREAD

**Issue by SuperJule** [phw198/OutlookGoogleCalendarSync#1773]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed (I think, but not 100% sure)  
**Sync Direction**: O<->G

**Bug Description**  
OGCS was working just fine, but then I went into the settings and changed to have it sync in both directions rather than just outlook to Google. Once I did this, I was no longer able to even open OGCS. Every time I try to open it, the application terminates and I get the error message "Application unexpectedly terminated!" followed by "Cannot bind to the new display member. Parameter name: newDisplayMember. I tried deleting OGCS and re-installing it multiple times, but every time I have gotten the same error.

**Steps to Reproduce the Issue**  
1. I try launching the OGCS app
2. The app attempts to launch, and then immediately terminates
3. This happens every time I try to open the app

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13981393/OGcalsync.log.log)
https://gist.github.com/SuperJule/a4b3a1be29c19a2248de5ed8b930bf1e

**Comment by phw198** [comment]
I don't think it's the two-way sync that has caused this, but potentially the switching to syncing a shared calendar, but not clicking `Save` before exiting OGCS.

Could you try:
1. Closing OGCS
2. Renaming your `settings.xml` file, eg `settings.xml.bak`
3. Starting OGCS - it's start with no configuration
4. Run through the setup again, but making sure you click `Save` after selection your shared calendar

You don't need to fully re-configure it, but if you could then send me your logfile again I can see if there's a missing piece of information that is now included. If so, I can hopefully write a fix...

**Comment by SuperJule** [comment]
That fix worked! Thank you SO much! Here is the log from the sync today. 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14199521/OGcalsync.log)

**Comment by phw198** [comment]
Ah great, glad you got it working!

I don't see you selecting a shared calendar for sync though, so maybe that was a mistake when you did it before? I also don't seem to be able to replicate the problem you ended up in either, so if you are up and running now I think I will close this...
