### ISSUE TITLE
Recurring events are syncing to Google Calendar from Outlook

### ISSUE THREAD

**Issue by zigojacko** [phw198/OutlookGoogleCalendarSync#1774]
**Are you already using OGCS?**
2.10.0.0

**Describe the question you have**
Recurring events (the entire series) are not syncing from Outlook calendar to Google calendar.

I'm unsure if there is a setting I have missed, The events are in my personal calendar where I have accepted invite to the whole series, all other events in the same calendar are synced across fine.

**Comment by phw198** [comment]
It's not really possible to say without seeing your log file or configuration, but there is no setting to differentiate between single items and recurring series...

**Comment by TheJacksonian** [comment]
Is it potentially that you are only syncing 100 days into the future (or some number of days) and the ones past that date aren't synced across yet?
I believe the application syncs the events, not the 'series' of them, so it'll only sync events that occur in the sync range you set?

**Comment by phw198** [comment]
OGCS only syncs _changes_ to occurrences that fall within the sync window, but the whole series is synced as long as the series falls withing the window. So series that start before or during the sync window will show the occurrences that fall after the window too.
