### ISSUE TITLE
Unable to find shared (group) Outlook calendar to sync to Google Calendar

### ISSUE THREAD

**Issue by zigojacko** [phw198/OutlookGoogleCalendarSync#1775]
**Are you already using OGCS?**
2.10.0.0

**Describe the question you have**
If I select a shared calendar to sync, it opens up the Exchange Global Address List and I can see the Outlook group but when I select it, it throws an error saying it can't find the shared calendar.

How do we select a group calendar to sync?

**Comment by phw198** [comment]
Can you provide the lines at the end of your log file when that error shows?

**Comment by h07d0q** [comment]
I had a similar problem with a colleague's calendar. I see his calendar because he shares ist with the whole company but I can't sync them in OGCS. So I asked him to share it explicitly with me and now it works 👍
So maybe you can share the group calendar explicitly with your user?
