### ISSUE TITLE
Update failed due to GMeet and empty body/description. Value cannot be null.

### ISSUE THREAD

**Issue by Securlock** [phw198/OutlookGoogleCalendarSync#1776]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
When syncing between Outlook and Google, I recieve the following error; "Error-Event update failed. Value cannot be null.Parameter name: input"

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14033451/OGcalsync.log)
```
2024-01-24 16:21:26,806 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentNullException: Value cannot be null.
Parameter name: input
2024-01-24 16:21:26,808 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: Match() in <Unknown File>
2024-01-24 16:21:26,809 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.Text.RegularExpressions.Regex.Match(String input)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 907
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 699
```

**Comment by Kivi-Berlin** [comment]
Same issue here.
It happens if the first appointment of an Outlook serie is deleted.
My workaround was to set the start date of the Outlook serie to the next date which is not deleted.

**Comment by MartinJJ** [comment]
And same issue here.
Since update to v 2.10.3
Only doing a   O->G sync
Every sync i get the popup :  Google event update failed. Continue with synchronisation ?
I Click : OK
Get the same popup again ...
I Click OK again:  in the end all looks to be OK...

Info In OGCS screen:

"Event update failed.
Value cannot be null. Parameter name: input"

Have at least 2 Outlook series where one or two items were changed/deleted/....

Had no issues before the update.
Have screenshots and the   OGcalsync.log  with  logging level set to ' Debug'   if you want them.

Regards, Martin

**Comment by JeroenTuinstra** [comment]
#1783 Sorry made the same bug report. Mine seems to be with a singel event, though spread over 2 days, with different time zones.

**Comment by phw198** [comment]
Apologies, time is being elusive for me at the moment! In the meantime, I think turning off syncing of Google Meet details will work around the problem until I can get a hot fix out.

**Comment by MartinJJ** [comment]
I'm only synch-ing  Outlook ->  Google,  but  turning off syncing of Google Meet details  solved it for now !

**Comment by galexmay** [comment]
I can't see an option to turn off syncing Google Meet details. If that setting exists, can someone please tell me where to find it. I found "Include Meet Conferences and I switched that off, but it did not solve (or workaround) the problem for me. If you mean turning off calendar descriptions sync, that is no better for me that turning off syncing all together. Can you please confirm what you mean.

**Comment by MadisonJim** [comment]
I have the same issue: Value cannot be null. Parameter name: input. It is not clear to me whether a solution is being worked on. I see a "closed" listing above.

**Comment by vprichard** [comment]
I have the same issue upon running sync:
"Event update failed.
Value cannot be null. Parameter name: input"

I do not use Outlook or Google for meetings and also cannot find the option for " turning off syncing of Google Meet details."

[OGcalsync.2024-01-31.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14128830/OGcalsync.2024-01-31.log)
[OGcalsync.2024-02-01.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14128831/OGcalsync.2024-02-01.log)

**Comment by phw198** [comment]
Sorry for the delay in getting to this.

:package: However, it should now be resolved with [hotfix v2.10.3.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14129716/v2.10.3.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `65B94D5C` Exe = `3ED60673`

Please let me know how it goes!

**Comment by vprichard** [comment]
This fixed the problem for me -- thanks.

**Comment by galexmay** [comment]
Yes, that seems to work. Please note, however, that the website is reporting 2.10.2 as the latest Alpha version, which is wrong. Please also note that, having downgraded back to the beta version, the check for updates didn't work and I had to force the issue to get back to 2.10.3.

**Comment by phw198** [comment]
Thanks for confirming @vprichard 👍🏻 

@galexmay Yep, I stalled further rollout of v2.10.3 knowing this issue would be affecting a lot of users. I need to decide whether to abandon this release and put this hotfix straight into v2.10.4....

**Comment by MadisonJim** [comment]
This solved the problem for me as well. THANK YOU FOR YOUR FAST SOLUTION!

**Comment by amig500** [comment]
works for me too, thanks 👍

**Comment by schnodo** [comment]
The issue was quite annoying because I synchronize on every change. I'm very happy that the hotfix resolves it. Thank you very much. Fantastic software!

**Comment by PaulNocero** [comment]
Thank you.  That seems to have fixed this problem.
