### ISSUE TITLE
Google to Outlook, set color not appearing

### ISSUE THREAD

**Issue by nahata5** [phw198/OutlookGoogleCalendarSync#1780]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0.0
**Edition**: Installed
**Sync Direction**: G->O

**Bug Description**  
Although the upgrade gives the dropdown for G -> O label, the labeled created events are not getting set color/label

**Steps to Reproduce the Issue**  
1. Set a color label for G -> O, not appearing

**Comment by nahata5** [comment]
It works in the default calendar, not the alternate email account

**Comment by phw198** [comment]
Sounds like the categories for the alternate email account aren't available. When you switch to the alternate mailbox in the OGCS settings, do the Outlook categories update in the checkbox list? If not, does a right-click on the categories and "Refresh" update them correctly?

Ideally I need to see your OGcalsync.log file to troubleshoot further...
