### ISSUE TITLE
Event update failed. Value cannot be null. Parameter name: input

### ISSUE THREAD

**Issue by JeroenTuinstra** [phw198/OutlookGoogleCalendarSync#1783]
**OGCS Version**: v2.10.3.0  
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
When syncing get the error message each time: "Event update failed. Value cannot be Null. Parameter name: input" with the popup "Google event update failed. Continue with synchronisation?"
According to the logs it is with an even that has a start-time in one Time Zone and an end time in a different one (-6 hours). Could it be that OGCS cannot handle different time zones in one event?
The different time zones is because it is a flight that starts in Europe and ends in the US.

**Steps to Reproduce the Issue**  
1. Start sync
1. No futher steps. 

**Any other information**  
Any additional information that may help troubleshoot the issue.  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14062057/OGcalsync.log)

**Comment by amig500** [comment]
+1 same bug

**Comment by Hobbel1968** [comment]
+1 same bug, since last update

**Comment by phw198** [comment]
As you suspected @JeroenTuinstra, this is duplicated by #1776 which now has a hotfix posted.
