### ISSUE TITLE
Whole multiday dates not syncing last day

### ISSUE THREAD

**Issue by VCantr** [phw198/OutlookGoogleCalendarSync#1784]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed 
**Sync Direction**:  O->G

**Bug Description**  
On outlook I create a multiday meeting, say 1-4 April. After sync, in google, event blocks out 1-3 April. If you look at the details then it says 1-4 April but the block out always misses the last day. 

**Steps to Reproduce the Issue**  
1. Create multiday, whole day events on Outlook. Save
2. Open OG sync and sync. 
3. After sync look on google calendar for event. Check block out days. 

**Any other information**

**Comment by phw198** [comment]
You've failed to mention which version of OGCS you are running.

Gut instinct is you have timezone issue between what you have in Outlook and the calendar in Google, but without a logfile I couldn't say for sure.
