### ISSUE TITLE
Event update failed: Value cannot be null. Parameter name: input

### ISSUE THREAD

**Issue by ran-klein** [phw198/OutlookGoogleCalendarSync#1785]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3.0  
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
During Comparing XX existing Google calendar entries, I get a Sync item failed message with the text "Google event update failed. Continue synchronization?". The verbose output error message is "Event update failed: Value cannot be null. Parameter name: input". After dismissing appears a couple more times during event update stage.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14067144/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. Perform a Sync

**Any other information**  
Seems to have appeared after latest update.

:paperclip: Attach your `OGcalsync.log` file.

**Comment by amig500** [comment]
+1 same bug

**Comment by gerontius1** [comment]
+1 same bug. Started happening after updating to 2.10.3.0. Reverted to 2.10.2.0 and it no longer happens.

**Comment by wallabri** [comment]
+1 same bug. Started happening after updating to 2.10.3.0
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/157862127/fc855ffd-3b2a-4992-9eee-a9946b26f629)

**Comment by xsrgithub** [comment]
+1 same bug. Started happening after updating to 2.10.3.0
Reverted to 2.10.2.0, issue disappeared.

**Comment by revere521** [comment]
I am also experiencing this on every sync

**Comment by rschwedes** [comment]
I am experiencing the same issue 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14091811/OGcalsync.log)

**Comment by Fukitsunakishi** [comment]
+1 Also having the same issue:
[OGcalsync_Bug_20240130.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14093691/OGcalsync_Bug_20240130.log)

**Comment by phw198** [comment]
Thanks for reporting, but it's a duplicate of #1776 which [has a workaround](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1776#issuecomment-1915657910).

**Comment by ran-klein** [comment]
Thank you. That did the trick in my case.

**Comment by phw198** [comment]
Just to update, the workaround on #1776 now has a hotfix to fully resolve.
