### ISSUE TITLE
Another new calendar item created in Google calendar from 1 Outlook calendar item each time a sync is done.

### ISSUE THREAD

**Issue by AndrewMac1971** [phw198/OutlookGoogleCalendarSync#1789]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Another new calendar item created in Google calendar from 1 Outlook calendar item each time a sync is done. After a few days of sync I end up with dozens of copies of an event in my google calendar.

**Steps to Reproduce the Issue**  
1. Go to... Just sync the calendar, it happens every time
1. Click on... Sync now

**Any other information**  
![Screenshot 2024-01-31 172705](https://github.com/phw198/OutlookGoogleCalendarSync/assets/144759419/7b40c0eb-1d1a-4ec7-9c10-7b9d2b552a70)

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
![Screenshot 2024-01-31 165325](https://github.com/phw198/OutlookGoogleCalendarSync/assets/144759419/f33dc943-36c5-4db7-be99-c15df8da0b0f)
![Screenshot 2024-01-31 173140](https://github.com/phw198/OutlookGoogleCalendarSync/assets/144759419/43a0f8d4-6d18-4338-937c-d57403511c10)
![Screenshot 2024-01-31 173203](https://github.com/phw198/OutlookGoogleCalendarSync/assets/144759419/469786a9-44a1-45f0-99b9-ee48bb3a98ff)

![Screenshot 2024-01-31 173244](https://github.com/phw198/OutlookGoogleCalendarSync/assets/144759419/66bb94ef-ba57-498d-a753-2315c4a61d65)

**Comment by phw198** [comment]
Ugh I hate screenshots! Any chance of the logfile? 🙂 

- Are you excluding the Sage colour from sync?
- Are you getting any deletion prompts?
- So although it's getting 156  items from Outlook, it is just that _one_ that is duplicating into Google each time?
- If you delete all the Google duplicates, do they just start reappearing again?
