### ISSUE TITLE
Google Appointments that are indicated on Google calendar want to delete from Outlook

### ISSUE THREAD

**Issue by Bman2022** [phw198/OutlookGoogleCalendarSync#1792]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3.0
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
This is more of me trying to understand what is going on.  I have a family calendar on Google that several me and another family member use.  Both users are using OGCS are running 2.10.3.0 release.  Every so often we get into a situation where a few calendar events get out of alignement on OGCS.  Meaning, the calendar events show up in Google calendar correctly, they also show up correctly in Outlook but OGCS wants to delete the calendar events every sync.  I say "no" to the delete, the events are reclaimed and then they want to delete again the next sync.

I have noticed that when first beginning the sync, OGCS see 63 events on Google and 69 on Outlook.  However, both calendars have the same appointments for the events trying to delete.  Ths only thing I can surmise is there is something not checked correctly or excluded. 

Where am I going wrong or what logic am I missing. 

Thanks-
Benjamin
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14158692/OGcalsync.log)
[outlook_delete.csv](https://github.com/phw198/OutlookGoogleCalendarSync/files/14158693/outlook_delete.csv)

**Comment by phw198** [comment]
You are hitting issue #1776 a lot - please apply the hotfix provided there and see if it then helps resolve this deletion issue. If not, please provide your latest log file, thanks.
