### ISSUE TITLE
Since upgrading to version 2.10.3.0 get following error when syncing

### ISSUE THREAD

**Issue by Veggie352** [phw198/OutlookGoogleCalendarSync#1793]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10/3/0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
When OGCS performs a sync, I get a  "Sync item failed error message". The message says "Google event update failed. Continue with synchronisation?". If I click on OK, there is a message in red "Event update failed. Value cannot be null. Parameter name: input

![Screenshot 2024-02-04 221928](https://github.com/phw198/OutlookGoogleCalendarSync/assets/54488753/ec751c90-3e64-44a9-b72e-dee4293740e1)

**Steps to Reproduce the Issue**  
1. This occurs whenever a sync runs and has only occurred since OGCS was automatically updated to this version.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by FilippoLepri** [comment]
Same here. :)
(EXACLTY the same, so I don't even attach the log file.)

**Comment by aodtcr** [comment]
Exactly the same for me, since the upgrade to latest alpha v2.10.3.0.

**Comment by phw198** [comment]
All duplicates of #1776 which has a hotfix available.
