### ISSUE TITLE
Event update failed message at sync

### ISSUE THREAD

**Issue by PaulNocero** [phw198/OutlookGoogleCalendarSync#1795]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
Whenever a sync is started, I get the message:

"Event update failed.
Value cannot be null. Parameter name: input"

**Steps to Reproduce the Issue**  
1. Go to. OG
1. Click on "sync"

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

I cannot get a log file.  When I click on the log file link in the help page, all I get is a blank form.

**Comment by PaulNocero** [comment]
I finally found the log file, attached
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14184560/OGcalsync.log)

**Comment by parovalence** [comment]
I am receiving the same error, I tried to delete the events mentioned in the log file, but this did not resolve the issue.

**Comment by BigPete62** [comment]
I'm getting this error also and also unable to resolve it. Have followed the instructions to get the log file but in the folder, the latest log file is 2 days ago, not sure what's going on.

**Comment by jwittaaot** [comment]
I am receiving this error as well. 
It happened after I installed the latest update

**Comment by phw198** [comment]
Duplicate of #1776 which has a hotfix.
