### ISSUE TITLE
O->G: Annual recurrence keeps updating every sync

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1799]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3
**Edition**: Installed / Portable  
**Sync Direction**: O->G

**Bug Description**  
Create a Google event that recurs annual, but with an interval of 1 - unknown which software does this, Google webapp doesn't.

**Steps to Reproduce the Issue**  
1. Google recurrence of `RRULE:FREQ=YEARLY;INTERVAL=1`
1. Sync an equivalent item from Outlook with recurrence of `RRULE:FREQ=YEARLY`
2. OGCS updates Google with the Outlook recurrence, but it does not take effect, seeming because Google knows they are logically the same.
3. Subsequent syncs keep making the same change.

**Any other information**  
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/b08cbf76-e2e0-4dec-aba5-6d6d544744b3)

:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Workaround seems to be save the series to Google as a 12 monthly recurrence, which would then revert back if further syncs detects changes.

:package: Please try this out with [hotfix v2.10.3.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14212944/v2.10.3.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `D9A47B4E`

Please let me know how it goes.

**Comment by TheJacksonian** [comment]
I has this issue as well in 2.10.2.0,  so I applied the change, and I still see the 'issue'.

![issue1799_01_update_failed](https://github.com/phw198/OutlookGoogleCalendarSync/assets/26889446/93cbe192-d5f8-4082-b5c0-051c1c5d9f57)

![issue1799_02_update_information](https://github.com/phw198/OutlookGoogleCalendarSync/assets/26889446/cd72d8b6-1699-4e51-a77d-a76a17fc770d)

OGcalsync.log
https://gist.github.com/TheJacksonian/11f96d8a82e9e6be41ec573e3b464432

**Comment by TheJacksonian** [comment]
Oops. I had another think about this, and realised, I'd not applied the hotfix.
2.10.3.3 Works. The first sync shows the update RRule:FREQ etc., but they don't appear on the next sync. So I think this resolves it.

![2 10 3 3](https://github.com/phw198/OutlookGoogleCalendarSync/assets/26889446/39716a04-59af-4fb4-b186-4417a1cc0fe6)

**Comment by phw198** [comment]
Hi @TheJacksonian, yep I was going to say your first post shows you on the alpha, not hotfix release 😉 

Thanks for confirming it's fixed!
