### ISSUE TITLE
Deleting meeting in Google Calendar sends update to all attendees

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#180]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/648597" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/trademark" target="_blank">trademark</a></strong> wrote at 2015-12-10 11:45:</p><div class="markDownOutput ">As title says, when I delete a meeting that has been sync'd from Outlook to Google Calendar in Google Calendar, it sends a meeting update to all attendees. Is there a way to turn that off? I don't want to update everyone that is on the meeting, I just
 want to delete the meeting from my calendar.<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/phw198" target="_blank">phw198</a></strong> wrote at 2016-03-07 22:21:</p><div class="markDownOutput ">If you're deleting it manually in Google, then you should get a popup asking if you want to notify the attendees - just click &quot;No&quot;.<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/Tlvdatsi" target="_blank">Tlvdatsi</a></strong> wrote at 2016-04-05 20:31:</p><div class="markDownOutput ">Hello, <br>
I have version 2.1.0.0 on windows 8.1 with outlook 2013. <br>
It is configured Outlook -&gt; Google. only. Which is syncing properly. The event is created in outlook and sync'd to google. When i go to remove the item in google calendar, it cascades the delete back to outlook, and generates a canceled event notice for
 everyone(even for events i do not own). I would not expect this behavior with outlook-&gt;google. I would expect it for outlook&lt;-&gt;google, change me to not attending(especially for meetings i do not own), or for it to re-add the meeting next sync. I do
 not get any message about notifying attendees. <br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/phw198" target="_blank">phw198</a></strong> wrote at 2016-04-07 19:32:</p><div class="markDownOutput ">You seem to have a different issue to the opening poster. If you don't get an alert when you delete the appointment in Google, are you not syncing meeting attendees to Google? I really can't see how OGCS would be &quot;cascading the delete back to Outlook&quot;
 if you have it syncing O-&gt;G. Can you upgrade to v2.2 and see if the problem remains. If it does, you'll need to create an Issue and upload your OGcalsync.log file.<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/Tlvdatsi" target="_blank">Tlvdatsi</a></strong> wrote at 2016-04-11 01:39:</p><div class="markDownOutput ">I think it is the same issue. When I create a meeting in outlook, sync, it gets created on google. I then delete it, get no alert to notify. Outlook then deletes the meeting and sends an alert saying the meeting was cancelled. No I am not syncing attendees
 to google. I will test with 2.2 and upload logs if it happens. <br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/deepgreens" target="_blank">deepgreens</a></strong> wrote at 2016-04-22 16:09:</p><div class="markDownOutput ">I have had similar issues in the past with OGCS canceling the meeting for all attendees when I delete the event in GCal. I did not get a popup or alert to ask me to cancel it for everyone I was likely using my phone to delete the meeting which may be the
 reason behind there being no popup/alert. <br>
<br>
I'd love to know how others are dealing with this as it's rather embarrassing to delete everyone else's meeting. Scoldings aplenty for that one!
<br>
<br>
Great product otherwise!<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/nathan_wilson" target="_blank">nathan_wilson</a></strong> wrote at 2016-12-07 14:47:</p><div class="markDownOutput ">I had the same issue. I deleted an appointment in GCal. No alerts or popups asked me to cancel it for everyone. All Outlook attendees were notified that a third party was trying to cancel the meeting. It was extremely uncomfortable for me to explain the
 issue as it was considered a hacking attempt by the meeting organizer. Is there anyway to cleanly remove all the appointments that were sent to Google Calendar without sending cancellations? At this point, I'm afraid to touch a meeting in Google Calendar.<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/ZackG" target="_blank">ZackG</a></strong> wrote at 2016-12-08 19:39:</p><div class="markDownOutput ">I've recently discovered I have a similar issue, however mine is with simple meeting reminders. It appears Google Calendar has sent out a &quot;reminder&quot; about &quot;my&quot; meeting in GMT time to some (apparently not all) attendees within my company.<br>
<br>
The email is &quot;From: <a href="mailto:calendar-notification@google.com&quot;,"  rel="nofollow">
calendar-notification@google.com&quot;,</a> and the Reply To address is my Gmail account.<br>
<br>
I did not create the meeting in Outlook, but the reminder notification shows me as the organizer. I'm assuming that's because OGCS has created a meeting on my behalf in Google and the reminder went out via Google. What isn't clear to me is why the &quot;reminder&quot;
 email only went out to some recipients. I didn't receive the email reminder on either my corporate email or my Gmail account.
<br>
<br>
In the meantime I've disabled syncing &quot;Attendees&quot; in hopes this will prevent awkward reminder emails from going out in the future. I never had &quot;Reminders&quot; included under the Sync Settings, just &quot;Description&quot; and &quot;Attendees&quot;.<br>
<br>
My sync is setup to only go from Outlook -&gt; Google. <br>
</div></div>

**Comment by rwattersjr** [comment]
What has happened to this issue? I have the same problem: delete an appointment in google, and every attendee gets a meeting cancellation notice in their Outlook. Using V. 2.5.0

**Comment by phw198** [comment]
The plan is to "cloak" the email address of attendees, so they are no longer real, as per the suggestion in #197.

Also, in recent versions, syncing of Attendees is off by default which may help reduce the occurrences for people that don't really need this information synced.

It's a mystery why only some people get the emails from Google though. I wonder if it's whether the attendee has linked their work email with their Google account and then Google is being overly helpful/invasive.

**Comment by phw198** [comment]
Closing issue and tracking under #197.
