### ISSUE TITLE
Windows 7 - Outlook 2010 - Calendar events keep deleting and end up in Deleted Items

### ISSUE THREAD

**Issue by kevinguckian** [phw198/OutlookGoogleCalendarSync#1800]
Version number. 2.10.0.0

This scenario is:

I have a user that is on 2 laptops and 1 mobile phone
Laptop 1: Windows 7 device using Outlook 2010 - Main email and calender is a non Google account (old SMTP email service)
Laptop 2: Windows 11 device using Outlook 365 - Main email and calender is a non Google account also
Mobile Phone: Samsung using default mail app and calendar - Main email is non Google BUT calendar used is Google

Both laptops have the OGCS app installed and both have been working fine for years to move calendar events between themselves and mobile phone calendar. When any event was created on any device, they would all sync

Recently, calendar events were somehow getting deleted and I was unable to find out why
Today I discovered on the Windows 7 laptop that the calendar events are in the Deleted Items folder. I moved some of these back to the calendar and within a few minutes, they again were deleted and ended up in the Deleted Items folder
I then turned off the OGCS app and this stopped the issue from happening

I then installed the Alpha version and used the same settings used on the Windows 11 Laptop for OGCS, but the sync would not start and just hang

I reinstalled the Beta version (currently still installed) and have changed the settings to be Outlook > Google (so that the deleted events would sync back to the Google account)

Can anyone help shed any idea as to what is happening? I know that Windows 7 is a very old system, but it had been working

**Comment by phw198** [comment]
Sounds like if you "changed the settings to be Outlook > Google" then you were two-way syncing before? If so, once deleted (for whatever the original reason was), undeleting them won't change what OGCS believes needs to happen - you need to follow the [wiki guidance](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) to reinstate them.
