### ISSUE TITLE
Multiple Constant Event Update Failed Value cannot be null: Parameter name: input

### ISSUE THREAD

**Issue by BillyJIV** [phw198/OutlookGoogleCalendarSync#1803]
I am on the latest ALPHA release.
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/28783671/1e4b3b92-eabe-461f-a9c8-3e492478f732)

The issue is reproduceable as it happens every time it syncs multiple times.

My version information is included with the screenshot above.

Sync direction is O>G

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/28783671/50f52c0d-84ed-4ffb-9f57-5c544c07b80c)

I have attempted to delete the entries in the Google Calendar and let OGCS recreate it, but doesn't seem to help or work.

help.

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14281515/OGcalsync.log)

**Comment by BillyJIV** [comment]
> A clear and concise description of what the bug is.

Everytime the sync occurs multiple errors about value cannot be null displays. Thus I have to fiddle with they sync to get it to complete every day.

**Comment by Fafner1976** [comment]
Maybe this could help, looks similar.
https://github.com/phw198/OutlookGoogleCalendarSync/issues/1776

**Comment by cece46** [comment]
In 2.10.3.0 and 2.10.3.1 the bug is present.
In 2.10.0.0 the bug is not present.

**Comment by BillyJIV** [comment]
Thank you Fafner1976 for the reference to topic 1776. That hotfix solved my issues as it solved it for those on that thread.

Thank you!

**Comment by BillyJIV** [comment]
Issue resolved with hotfix in topic 1776
