### ISSUE TITLE
Issue with set colour/category

### ISSUE THREAD

**Issue by sdarkly** [phw198/OutlookGoogleCalendarSync#1804]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.0.0  
**Edition**: Installed
[OGcalsync.log - kopie.2024-02-15.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14313133/OGcalsync.log.-.kopie.2024-02-15.log)

**Sync Direction**: O<->G

**Bug Description**  
Under "Settings", there is an option to set colour/category for items created by syncing or all items synced. Since a while (apologies for the not being accurate with this, didn't track it), the application only allows one colour to be set for both Google and Outlook.

It used to be that I could set category for items created by sync in Outlook to "Category X (red)" and colour for items created by sync in Google to Blue. Right now, if I set colour Blue for items created by sync in google, the corresponding option for items created by sync in Outlook is set by default to a blue category. Same thing the other way around: if i set category x (red) for items synced in Outlook, when i switched to items synced in Google the option has automatically been switched to a red colour (no matter that I just selected blue one minute earlier).

**Steps to Reproduce the Issue**  
1. Go  settings
2. Sync options
3. Set "For items created by sync in Outlook calendar"
4. Do not tick other options
5. Tick "colour/category to" and select a category (in my case a red Category X)
6. switch to "for items created by sync in Google calendar"
7. Pick blue under "set colour/category"
8. switch back to "for items created by sync in Outlook calendar", the colour will have switched to a blue category instead of remaining on the red one.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
No, it's never worked that way - for two-way sync, it is only possible to select the colour of the created items in either Google or Outlook.

To achieve what you need, you'd need to set up two one-way sync profiles.

**Comment by sdarkly** [comment]
actually, I have re-installed it from scratch and now it is back to "normal" and I can have two colours with bi-directional sync. Happy to provide details

**Comment by phw198** [comment]
Yes I'd be interested to see your configuration/how you've achieved your setup, as OGCS only has the ability to store and process enforcing a colour in a single direction.
