### ISSUE TITLE
Outlook asking me to allow or deny access to my email address before OGCS can start in tray

### ISSUE THREAD

**Issue by MarkJR84** [phw198/OutlookGoogleCalendarSync#1805]
Hi,

I have set OGCS to start automatically at start up, however, after the preset 30 seconds outlook gives me the following warning:

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/35963262/1919aa9b-6482-4c64-a966-3a32a0b78927)

OGCS does not start in the tray until I click allow, but this is only for a maximum of 10 minutes.

Do you know of a workaround or fix for this please?

Steps to reproduce:

1. Set OGCS to start after startup with 30 second delay
2. restart the PC
3. warning will appear after restart.

Thanks for your help in advance.

This is a great program, I have just donated, thanks very much for creating it!

Mark

**Comment by Fafner1976** [comment]
I set the program to autostart with a 5 minute delay to make sure the AV updates its definitions.
This pops up if they’re not up to date.

**Comment by MarkJR84** [comment]
@Fafner1976 Looks like this has worked, thanks very much!
