### ISSUE TITLE
Event Update failed

### ISSUE THREAD

**Issue by HarrieB58** [phw198/OutlookGoogleCalendarSync#1806]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3.0  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14333299/OGcalsync.log)

**Edition**: Installed   
**Sync Direction**:  O<->G

**Bug Description**  
Every time that I synchronize I see the error "Event Update Failed. Value cannot be null. Parameter Name:Input

**Steps to Reproduce the Issue**  
Synchronize

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by ftodaf** [comment]
The same issue happend on my computer. The synchronization works, but always clicking away the error popups is annoying. Happens since the last update.

**Comment by Fafner1976** [comment]
Have a look here https://github.com/phw198/OutlookGoogleCalendarSync/issues/1776

**Comment by ftodaf** [comment]
Thank you very much, @Fafner1976 ! The hotfix from #1776  solved the issue for me.

**Comment by HarrieB58** [comment]
Thank you very much, @Fafner1976  ! The hotfix from https://github.com/phw198/OutlookGoogleCalendarSync/issues/1776 also solved the issue for me!
