### ISSUE TITLE
Add 'Sync All' button to manually trigger a sync event for all profiles

### ISSUE THREAD

**Issue by leifalbor** [phw198/OutlookGoogleCalendarSync#1807]
**Is your feature request related to a problem? Please describe.**
I use three profiles within OGCS.  I am not currently aware of a method that allows me to easily sync all profiles manually.

**Describe the solution you'd like**
An additional button added within the Sync tab that allows me to trigger a sync on all profiles

**Describe alternatives you've considered**
Currently to manually sync each profile I go to the Settings tab, select the first profile, return to the Sync tab, press the Start Sync button, wait for sync to complete, then repeat the process for each remaining profile.

**Additional context**
N/A

**Comment by TheJacksonian** [comment]
Having discovered a use for profiles this week, after being a long time OGCS user (and donater :)) - I'd love this enhancement too.

**Comment by phw198** [comment]
Yep, been meaning to add this for a while - it's being tracked under #1427
