### ISSUE TITLE
Event update failed. 값은 nul일 수 없습니다. 매개 변수 이름: pattern

### ISSUE THREAD

**Issue by mrdantzig** [phw198/OutlookGoogleCalendarSync#1808]
X

Total inc.
Outlook 7
Checking

Syncing
Matching

0 Google
0 Google calendar entries to be created.
74 calendar entries to be compared.

Comparing 74 existing Google calendar entries
[Uploading OGcalsync.log…]()

18 are exceptions to recurrina events.
Sync item failed

?

Google event update failed. Continue with synchronisation?

아니요(N)

V
![스크린샷 2024-02-23 082149](https://github.com/phw198/OutlookGoogleCalendarSync/assets/52942095/fe4ae88b-9f43-4f1e-9001-11a16969ac04)

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Should be a duplicate of #1776 which has a hotfix available.
