### ISSUE TITLE
Option to sync events with free/busy only

### ISSUE THREAD

**Issue by dxsubomni** [phw198/OutlookGoogleCalendarSync#1813]
**Is your feature request related to a problem? Please describe.**
I want to share my availability to a shared Google Calendar without sharing details of my Outlook calendar appointments.

**Describe the solution you'd like**
An option to share free/busy only, similar to Google Calendar's option "Share only free/busy (hide details)."

**Describe alternatives you've considered**
Syncing from Outlook to Google with "private" mode on only prevents details from being shown when you then share the Google Calendar again. I tried syncing Outlook to a personal, private Google Calendar, and then sharing that Google Calendar with another shared Google Calendar, but that doesn't work since it shares it to the "other calendars" section instead of the "my calendars" section.

**Additional context**
None

**Comment by phw198** [comment]
I think you're along the right lines, but I don't quite understand the last part. Within the Google calendar and its settings, there's an option to "Share with specific people" and there you can select they only see free/busy details:
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/c8fb0067-d670-41d7-87ae-b924bf929232)

If that's really not working for you somehow, you could then configure OGCS to only sync limited information:
* Don't select anything under the Settings > What section
* Under `How` select `Word Obfuscation`
   *  Targeting the [S]ubject, find `^.*$` and replace with eg `Busy`

**Comment by dxsubomni** [comment]
Oh, great to know it's already possible! I tried following your instructions and I'm not getting it to work. Here's what I'm seeing:

- Nothing is selected under the Settings > What section
- In the Word Obfuscation rules I'm having trouble with the syntax. I'm familiar with regex as a concept but nothing about the rules or logic. I'm not sure what I need to do to "target the subject." I also don't know whether the "Replace" field needs to have the word busy in quotes, no quotes, or something else.

I'm wondering if you'd mind sharing exactly what needs to be entered in the "Find" and "Replace" fields. I tried about 30 different variations based on my Googling and couldn't find the winning combo. I appreciate all your work on this project!

**Comment by dxsubomni** [comment]
For clarification - the Google Calendar sharing option you describe is one of the workarounds I tried. The issue with that is that it shares to the "Other calendars" section rather than the "My calendars" section for the receiving Google account. I need it in the "My calendars" section for my team to have some ability to edit and to integrate with our CRM software. 

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/58580049/1a9726a0-bbc9-4308-8d07-810fa8ff85ab)

**Comment by phw198** [comment]
If you don't have the "targeting" option, then it sounds like you aren't on a recent alpha release and OGCS is only able to target the Subject (so don't worry about that bit - later versions can apply the regex to location and description too).

I think what I already provided is the exact text of what you need to enter? Ie find = `^.*$` and replace = `Busy` (or whatever text string you want to appear).

Oh, this will not update previously synced data that has no change at source - run a full sync by pressing `Shift` and clicking the `Sync` button.

**Comment by dxsubomni** [comment]
That did the trick! I'm confident I tried those characters alone at one point, but I didn't do the full sync so it appeared to not work. But now I've got it set up and running exactly as I needed. Thanks so much for your great work!
