### ISSUE TITLE
You cannot make changes to the contents of this read-only folder during sync

### ISSUE THREAD

**Issue by schmgl** [phw198/OutlookGoogleCalendarSync#1815]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.2.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Every sync attempt returns following error: "You cannot make changes to the contents of this read-only folder.
**Steps to Reproduce the Issue**  
1. Go to... Try to sync calendar
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14548117/OGcalsync.log)

1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Um, OK? Obviously you can't sync to a calendar you don't have write permissions on...
