### ISSUE TITLE
no possibility to write or to modify in MS Outook PC to ggogle calendar

### ISSUE THREAD

**Issue by Maxime-1** [phw198/OutlookGoogleCalendarSync#1818]
Hello - 
I insgtall calendar sync 2.10  O<->G in my PC W10 : no problème 
The Sync : no problème 

BUT : i can write ou modify an "meeting" in Outlook PC google web calendar - sait "you can't right" 
in fact i would like to write (create or modify meeting) in my "google calendar accompt" create in outlook PC an would like to synchonize in "google calendar web)

is a bog or a/my bad configuration ?

Thanks for your return 
Regards 
Maxime

**Comment by phw198** [comment]
I'm struggling to follow the issue you are reporting - sounds like you don't have permission to make changes in the Google calendar. If so, that's nothing to do with OGCS, but the Google account you have authorised OGCS to use does not have write permissions on the calendar.

**Comment by Maxime-1** [comment]
don't have permission to make changes in the Google WEB calendar : Yes :-(
 I create a web calandar by importing the "Google calendar" link in PC Oulook (Off Pro + 2021) - but I can neither create or modify my appointments from outlook PC - it replicates, that's all.
I used your "Cal sync" on another PC and it worked without problem - Has anything changed in outlook?
or is it just a parameter? I searched but didn't find

**Comment by phw198** [comment]
> don't have permission to make changes in the Google WEB calendar : Yes :-(

This means "yes you do have permissions to make changes" or "yes you don't"?

> I create a web calandar by importing the "Google calendar" link in PC Oulook (Off Pro + 2021) - but I can neither create or modify my appointments from outlook PC - it replicates, that's all.

Importing with an ICS URL isn't syncing, no, it's just a readonly view of your Google calendar that updates maybe once a day. If you still have that configured within Outlook, remove it.

> I used your "Cal sync" on another PC and it worked without problem - Has anything changed in outlook? or is it just a parameter? I searched but didn't find

Changed by whom? Permissions on what OGCS can do with the Google account you authorise it with have nothing to do with OGCS or Outlook. 

In OGCS, 
* select the Outlook calendar (which must have nothing to do with any Google account)
* connect a Google account that has write permissions on the Google calendar you want to sync
* Select the Google calendar
* Sync

**Comment by Maxime-1** [comment]
Yes - I don't have right/permission (see a attach) " ms win off message : " you can modify this folder read only" 

![problem right calendar](https://github.com/phw198/OutlookGoogleCalendarSync/assets/163401083/6062bcc4-86f2-4d37-b499-8df699bfeed5)

![setment in oulook pc](https://github.com/phw198/OutlookGoogleCalendarSync/assets/163401083/8aabfef7-df58-4872-abb6-8979e50568cb)

**Comment by phw198** [comment]
Trying to two-way sync a calendar to itself that you have surfaced in Outlook as read-only through an ICS URL literally makes no sense at all. Try re-reading my previous post, but beyond that I can't offer any further help, sorry.
