### ISSUE TITLE
New meetings - OGCS wants to delete

### ISSUE THREAD

**Issue by sih060** [phw198/OutlookGoogleCalendarSync#1820]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: 2.10.0.0
**Edition**: Installed - 
**Sync Direction**: O<->G

**Bug Description**  
When creating a calendar entry from Outlook calendar tab, OGCS begins syncing, a message pops up asking if I want to delete the meeting that I just created. 

**Steps to Reproduce the Issue**  
1. Go to... Outlook, tab to calendar, select a time and select schedule a meeting. Fill in and save
1. Click on... OGCS will ask to delete the meeting

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14656708/OGcalsync.log)

**Comment by phw198** [comment]
:arrow_double_up: To receive support, please upgrade and reproduce the issue on at least v2.10.2 by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`.
