### ISSUE TITLE
Custom colour maps for Outlook categories are repeatedly, randomly giving "invalid map error" windows and reverting to default Outlook categories

### ISSUE THREAD

**Issue by soapy12** [phw198/OutlookGoogleCalendarSync#1823]
> Checklist:-
> - [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> - [x] Reproduce the issue
> - [x] Complete the information below
> - [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3.0
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
During some syncs, OGCS window pops up saying that the custom colour map is invalid, and asks me to correct it; then when I click yes it opens to the colour mapping window. However, on this window, in the outlook categories column all of my categories from outlook have reverted to the default outlook colour name categories (I have renamed my own categories on outlook). I will usually just click no, but the window will keep popping up a few times. Whether this issue happens or not seems to be random, but it has been happening everyday since I turned on custom categories. It will sometimes be fine, but then sometimes out of nowhere when I am working the "invalid colour map" popup window will randomly appear.

I don' have any clue what to look for in the logs, but I have seen the following line (below): 

> 03-25 10:45:21,633 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [154] -  Failed getting non-default mailbox categories. Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)).

The above line pops up a bunch of times in the sections of the log that say could not convert category name x/y/z into outlook category type. The next line after that is: `Reverting to default mailbox categories.`

**Steps to Reproduce the Issue**  
Unsure of how to reproduce as it currently seems to be occurring at random.

**Any other information**  
I am using an alternative mailbox as I use OGCS to sync my university/research email calendar to my personal G-cal.

The log I have included here has debug, fine, and ultra fine levels in there - I believe that the issue presented at each level too.
I have also included a few screenshots of other related (I think?) error windows, etc,.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14738885/OGcalsync.log)

![OGCS error box thing](https://github.com/phw198/OutlookGoogleCalendarSync/assets/164835095/fa362e26-fbdb-4ec5-87bf-c4cec58ad8b1)

![custom colour mapping error box](https://github.com/phw198/OutlookGoogleCalendarSync/assets/164835095/5f0a5c0f-17f4-43e9-a679-62e7138fc3bd)

Just to add - I absolutely love the application!

Cheers!

**Comment by phw198** [comment]
:package: This should hopefully be resolved with [hotfix v2.10.3.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14812122/v2.10.3.9.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `4B019853` Exe = `E484D373`

Please let me know how it goes!

**Comment by soapy12** [comment]
Thank you! I will give it a go, and will update in a few days! :)

**Comment by phw198** [comment]
I'm keen to get the next alpha release out and include this supposed fix anyway. Please do still update up here though and reopen the issue if necessary.

**Comment by soapy12** [comment]
Hiya!

So far so good with the hotfix - have not had any issues yet thankyou!

Really awesome work mate, really admire the constant dedication to the project!

Out of curiosity, what was the issue with the colour mapping stuff?

Thanks again!

**Comment by phw198** [comment]
Thanks, always good to hear the hours put into the tool are appreciated 👍🏻 

The issue was a rather intricate one related to the connection OGCS has to the Outlook client. When the client is closed between syncs, OGCS has to detect this and explicitly reconnect to it - the problem was for connection to the alternative mailbox to get the categories, it wasn't quite handling it properly....and then reverting back to the default mailbox and its categories.

There are so many permutations of OGCS configuration possible now, and almost endless "odd" scenarios that crop up on user's machines that this kind of thing is very hard to test against!
