### ISSUE TITLE
Multiple OGCS instances running: You already have an instance of OGCS running using the same configuration

### ISSUE THREAD

**Issue by babiloofish** [phw198/OutlookGoogleCalendarSync#1824]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v 2.10.0.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I'm syncing 2 different google accounts with outlook.
I did follow your description (https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Running-Multiple-Instances-of-OGCS) and did define 2 registry keys.
When the 2 sync jobs are coming up I always get 2 popups "Multiple OGCS instances running: You already have an instance of OGCS running using the same configuration". Both jobs are using the same exe but have different parameters. In my opinion, the warning should not show up when I'm using different settings.

**Steps to Reproduce the Issue**  
1. create 2 regedit entries using the same path but different settings
2. reboot

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14787751/OGcalsync.log)

**Comment by phw198** [comment]
Already fixed in v2.10.2
