### ISSUE TITLE
Event update failed: The value must not be zero. Paramater name: Input

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#1828]
After today's update, I suddenly get an error message with every sync (without adjusting any settings). Can anyone help me to fix this?

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/165762254/8131eccc-4456-4f9c-8673-c6553b02ce00)

**Comment by phw198** [comment]
Can you confirm you were advised of an update to v2.10.3 today and that is the version you are running with this error?

**Comment by ghost** [comment]
Yes, its the newest update. and the error message has only appeared since the update.

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/165762254/ec4aa46f-8776-4d48-82ce-0741c766cddf)

**Comment by phw198** [comment]
Unfortunately, it's not the newest update - that was v2.10.4.0, released yesterday. I think the problem is that v2.10.3 was abandoned due to the error you are now getting, but the upgrade release process is now letting people upgrade to it again.

I'll see if I can stop that happening, but your options now are to apply the hotfix on #1810 or upgrade to [v2.10.4.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.10.4-alpha/OGCS_Setup.exe).

**Comment by Fafner1976** [comment]
I had 2.10.3 installed but got correctly prompted to update to 2.10.4 today.
Do you mean 2.10.2 or lesser users are getting prompted to update to 2.10.3?
Better to have the site updated asap to make ppl aware 2.10.4 is the latest.

**Comment by ghost** [comment]
I get the message that I have the latest version of OGCS.

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/165762254/c5aa13c6-d0bf-4e7b-af7d-0c6aec6e4e62)

**Comment by Fafner1976** [comment]
That's odd. Using installer or portable setup?
I'm using portable and got prompted about 2.10.4.

**Comment by ghost** [comment]
I use the normal version and was informed about the update today. However, the update was the update to version 2.10.3.

**Comment by Fafner1976** [comment]
You can just get the latest one here
https://github.com/phw198/OutlookGoogleCalendarSync

**Comment by phw198** [comment]
> I had 2.10.3 installed but got correctly prompted to update to 2.10.4 today. Do you mean 2.10.2 or lesser users are getting prompted to update to 2.10.3? Better to have the site updated asap to make ppl aware 2.10.4 is the latest.

2.10.4 is being rolled out progressively, so not all users will be notified about it. But it seems in the meantime, for users on less than 2.10.3, they will _all_ get notified of 2.10.3 being available. I've made a change to the rollout mechanism and early signs are that downloads of v2.10.3 have stopped...but at this point I'm in rather uncharted waters and if it hasn't worked, then I'll likely need to speed up rollout of 2.10.4.

Note this only affects installed versions and their upgrades; portable versions will only be notified about 2.10.4, as expected.

**Comment by ghost** [comment]
Short update. I have uninstalled version 2.10.3 and installed the latest version 2.10.4. Synchronisation works perfectly again. It is therefore probably due to version 2.10.3, which generated the error for me.

**Comment by Fafner1976** [comment]
That was indeed the bug which forced the dev to "unrelease" the 2.10.3 update.
Anyways, other than this bug fix, the ability to hide notifications if no changes are made is alone worth the update. Having 4 active profiles, I was literally flooded with unneeded "0 changes made" notifications every 2 hours.

**Comment by phw198** [comment]
v2.10.4 is now fully released, so anyone running v2.10.3 should certainly upgrade again as soon as possible.

Thanks everyone, I'll close this issue now 👍🏻
