### ISSUE TITLE
Possible infection of v2.10.3.0 alpha

### ISSUE THREAD

**Issue by davethegeo** [phw198/OutlookGoogleCalendarSync#1829]
**OGCS Version**: v2.10.3.0
**Edition**: Installed / Portable  
**Sync Direction**: O->G 

**Bug Description**  
Avast reports that OutlookGoogleCalendarSync.exe is infected with IDP.HEUR.26

Report has only been seen for the recent alpha upgrade.

**Comment by phw198** [comment]
Are you sure that was on the v2.10.3.0 release and not v2.10.4.0? The latter is signed using a new certificate, so I would not be surprised that has not been able to build reputation yet. v2.10.3.0 was an abandoned release anyway, but if Avast has a problem with it, it's a [false positive](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#anti-virus-false-positives).

**Comment by davethegeo** [comment]
Yup. It was 2.10.3.0. At least that's what the programme reports itself as in the "About" tab. Funny as I thought I had upgraded to 2.10.4.0....
In any case as it it s a false positive i will ignore it.
Thanks

**Comment by phw198** [comment]
Well v2.10.4 is now out and should be upgraded from v2.10.3, which was rather buggy. If the new certificate on v2.10.4 is flagged as infected, I'd appreciate your [help reporting it to Avast](https://www.avast.com/false-positive-file-form.php).
