### ISSUE TITLE
The option to map more than just the Outlook default categories to Google Calendar colours   

### ISSUE THREAD

**Issue by OmariInLondon** [phw198/OutlookGoogleCalendarSync#1830]
**Is your feature request related to a problem? Please describe.**
Automation in my Outlook setup means that I have event categories other than the default ones in Outlook
See here: https://imgur.com/J9RPilp

**Describe the solution you'd like**
On the Custom Colour Mapping screen instead of just a drop down of each default Outlook category, I would like to be able to add in my custom categories and map them to Google Calendar colours

**Describe alternatives you've considered**
I cannot think of another way to make this work

**Additional context**
https://imgur.com/J9RPilp

**Comment by phw198** [comment]
OGCS already picks up the categories, whether they are default or custom - though it may depends on how they are stored, as your screenshot seems to be from O365 Outlook on the Web?
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/b380ad6c-d430-4225-a568-bd0958b5b03a)

Basically the categories that OGCS can use have to be in the Outlook Master Category List - can you provide more detail of the type of email account you have configured in Outlook and where the categories are defined? [Lots of useful information here](https://www.slipstick.com/outlook/outlook-categories-and-color-categories/).
