### ISSUE TITLE
Event update failed.

### ISSUE THREAD

**Issue by stevenburg7336** [phw198/OutlookGoogleCalendarSync#1831]
OGCS Version  2.10.3.0
Edition: Installed
Sync Direction  G->O / O->G (both)

**Bug Description**  
Since update to latest version getting a sync error every time it runs. "Appointment update failed. Value cannot be null. Parameter name: input"

**Steps to Reproduce the Issue**  Run Sync. Manual or automatic, either direction.

**Any other information**  
Excerpt from log: OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 907

Note, I DO NOT HAVE A USERNAME PAUL. Probably why the app can't locate the info.

:paperclip: Attach your `OGcalsync.log` file.[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14853725/OGcalsync.log)

**Comment by stevenburg7336** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14853793/OGcalsync.log)

**Comment by rafi-d** [comment]
+1
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/2458280/2e8f0ae0-aa77-402e-b0f2-33b47873a2cd)

**Comment by Fafner1976** [comment]
Update to the latest 2.10.4 version (you can download it on GitHub, the official homepage isn't updated yet). This was a nasty bug which showed up on 2.10.3.

**Comment by rafi-d** [comment]
Thanks, updated.  While trying to use about->check for updates with 2.10.3 - it hanged  up... 
Just FYI

**Comment by phw198** [comment]
Official website it now updated, so should be straight forward to get 2.10.4. Not sure why it hung upgrading for @rafi-d - if you have the `OGcalsync.log` file for the day you upgraded, might be interesting to see what happened. However, 2.10.3 was "pulled" after release, so it could very well be due to that...

**Comment by rafi-d** [comment]
Possibly, yeah.. You can test this, tho, by installing the previous version and trying to manually update :)

**Comment by stevenburg7336** [comment]
Thank you all for your hard work and including me on the updates. The new version installed without a hitch and the system is working again.

**Comment by phw198** [comment]
@rafi-d reviewing a log file from someone who already hit the issue is a much more efficient use of my time. 

@stevenburg7336 thanks for confirming you had no problem upgrading 👍🏻

**Comment by rafi-d** [comment]
> @rafi-d reviewing a log file from someone who already hit the issue is a much more efficient use of my time.
> 
upgrading 👍🏻

Attached
[Outlook Google Calendar Sync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14896103/Outlook.Google.Calendar.Sync.zip)

I believe the last record is:
Name	Line	Text	Path
OGcalsync.log.2024-04-04	882	2024-04-04 14:30:58,996 INFO  1 OutlookGoogleCalendarSync.Updater [203] -  Applying the updated release(s)... 	C:\Users\rafi\AppData\Roaming\Outlook Google Calendar Sync

**Comment by rafi-d** [comment]
One more observation - after every update the Windows sync notifications are enabled again. The app should preserve the previous windows setting (disable notifications in my case)

**Comment by phw198** [comment]
> Thanks, updated. While trying to use about->check for updates with 2.10.3 - it hanged up... Just FYI

Thanks @rafi-d for the logfile and I've been able to reproduce this - I've raised #1837 to cover it.

**Comment by phw198** [comment]
> One more observation - after every update the Windows sync notifications are enabled again. The app should preserve the previous windows setting (disable notifications in my case)

Well spotted! I had renamed the setting but failed to migrate the name in the settings file. Raised #1841 to cover that too.
