### ISSUE TITLE
GMail Calendar Appointments created in Outlook don't sync with GMail account

### ISSUE THREAD

**Issue by jennybarton** [phw198/OutlookGoogleCalendarSync#1832]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.4.0
**Edition**: Installed 
**Sync Direction**: O>G

**Bug Description**  
I create a calendar appointment in Outlook using my GMail email address, but once saved, the appointment displays in Outlook but does not show in GMail Calendar at all or display in Apple iPhone Calendar InBox either. I added 2 GMail appointments tonight and neither synced with GMail.

**Steps to Reproduce the Issue**  
1. Create appointment in Outlook with Gmail email address
2. Save appointment in Outlook Calendar
3. Run Google Calendar Sync
4. Check if appointment is in GMail Calendar online - NO
5. Check if appointment is in Apple iPhone Calendar InBox - NO

**Any other information**  
Any additional information that may help troubleshoot the issue.  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14873662/OGcalsync.log)

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14873636/OGcalsync.log)

**Comment by phw198** [comment]
I'm not sure what you mean by "Create appointment in Outlook **with Gmail email address**"?

Regardless, OGCS is only finding 2 Outlook appointments in your calendar, so:
* are you sure you are creating the appointment in the same calendar OGCS is configured to sync against
* have you [checked your date-time formatting](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) - your time format is `h:mm tt` which might not work well with Outlook.

**Comment by jennybarton** [comment]
Hi Paul,

Thanks for your reply.

I have checked my OGCS and Outlook settings.  OGCS is set to sync with my default Outlook mailbox ***@***.*** ***@***.***>  which is the same as my Google account.

I have played around with selecting different date-time setting in OGCS as suggested and tried re-running sync. The latest results are as follows:

*	When I create an appointment in my Google calendar via Microsoft Teams or iPhone Calendar App, and then run OGCS, OGCS detects these new appointments and updates the default Google calendar in Outlook.  So, Google > Outlook sync works. 
*	When I now create an appointment directly in Outlook in the same default Google calendar, the sync back to Google and Microsoft Teams/iPhoneApps does work (not sure I really changed anything to get this result). So, Outlook > Google works (but not always – see below)
*	Outlook > Google sync doesn’t work when I create the appointment months ahead.
e.g. If I create the appointment for today, tomorrow, next week, or two months ahead in Outlook, the sync works. But when I create an appointment in Outlook in my default Google calendar for a date further ahead e.g. July, the OGCS doesn’t detect this future appointment.

I’ve created appointments in April, May & June – all successfully synced, but July onwards doesn’t.

Attached is latest OGcalsync.log.

Kind regards,
Jenny

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

But it rather sounds like you've not changed or extended the default [date range of which items to sync](https://www.outlookgooglecalendarsync.com/guide/syncoptions#when).
