### ISSUE TITLE
Sync two calendars

### ISSUE THREAD

**Issue by PiekiBi** [phw198/OutlookGoogleCalendarSync#1833]
**Are you already using OGCS?**
Provide the version number. 2.10.0.0

**Describe the question you have**
I have two calendars in outlook i wanna sync with two different google calendars. Is this possible?
And i mean without switching the settings. :-)

Do i need to make a second instand of the application? Maybe you can help me :-)

**Comment by Fafner1976** [comment]
What do you mean? 2 different Google accounts or just 2 different calendars in the same account?
If you want to use 2 accounts you have to rely on the portable version and have 2 instances of it running (just extract the zip into 2 different folders). If you need to sync to 2 calendars in the same account you'll want to use profiles in the application, one profile for each calendar. Personally, I'm using 4 profiles to sync 2 calendars of mine and 2 shared calendars from my colleagues to 4 different calendars in my Google account.

**Comment by PiekiBi** [comment]
@Fafner1976 
Thank you very much. I din't realized there are profiles. This is what i needed!

**Comment by PiekiBi** [comment]
@Fafner1976 
i am sorry to bother you again.
But maybe i am dumb. but it looks like, that i have to swap the profile manually? otherwise only one profil gets synced.
Is this correct or am i understanding sth wrong?

**Comment by Fafner1976** [comment]
You have to set sync options for each profile you add, they are not global settings!
