### ISSUE TITLE
Upgrade mechanism hangs

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1837]
**OGCS Version**: v2.10.3
**Edition**: Installed

**Bug Description**  
When upgrading eg from v2.10.3 to v2.10.4 by clicking the "Check for new release" on the `About` tab, OGCS becomes "frozen".

**Steps to Reproduce the Issue**  
1. Go to the About tab, ensure "Check for Alphas" is selected
1. Click "Check for new release"
2. When a new version is available, opt to upgrade
3. OGCS becomes unresponsive.

**Any other information**  
In actual fact, by clicking the taskbar icon and choosing "Minimise" (several times), this seems to force the application to progress and eventually the message box "Applicaton successfully updated" will appear.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.10.4.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/15028993/v2.10.4.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `7A59AF33` Exe = `43ED3CF6`

The hotfix would need to be applied before upgrading to the next alpha release, otherwise the fix will only be benefited from upgrades following _that_ release.

@rafi-d FYI

**Comment by rafi-d** [comment]
Got it, thanks.
