### ISSUE TITLE
How to keep deleted items deleted

### ISSUE THREAD

**Issue by adamklaff** [phw198/OutlookGoogleCalendarSync#1842]
**Are you already using OGCS?**
2.10.0.0

**Describe the question you have**
I have a family calendar in Google and a work calendar in Outlook. I want family calendar items synced with Outlook, but not all items. I set up a one-way sync from Google to Outlook and it works, but when I delete items from Outlook, they get re-synced. I assume this is because it's a one-way sync. Is there a way to delete the items from Outlook but not in Google? My spouse uses the google calendar and I want it to be unaffected by anything I do in Outlook, but I also want to be able to delete some of the appointments from my Outlook calendar.

Thanks,
Adam

**Comment by phw198** [comment]
You would need to:

1. Upgrade to the recent alpha release
2. Assign a different colour to the Google items you don't want synced to Outlook
3. Exclude that colour from sync (on the Settings > Google tab)
4. Opt to delete already synced items, if excluded

Hope that helps!

**Comment by adamklaff** [comment]
Looks like that worked. Thank you!
