### ISSUE TITLE
Startup behaviour - more options

### ISSUE THREAD

**Issue by hgschehl** [phw198/OutlookGoogleCalendarSync#1845]
Hi!

The tool offers me a start delay of 5-300 seconds. When I'm working from home (and even sometimes when I'm in the company), that's often too short:
We have a telephony application that interacts with Outlook. To initialise this application successfully, I have to establish a VPN connection first. Some security issues (e.g. 2FA authorisation for MS login) also take time. So I often need more time than the 5 minutes I have to start Outlook properly so that all extensions work as expected.

I tried to "cheat" the tool by manually changing the delay in the configuration file to 600s, but the tool resisted and quit with an error message :-(

The perfect solution for me would be the ability to switch between two options: 
- the current behaviour with a delay of more than 300 s. and 
- the option not to start Outlook by the tool during the first synchronisation, but to wait until the user has started Outlook and then start the synchronisation, perhaps with an additional delay ("Start sync <n> seconds after Outlook has been started by the user")

Regards
Hans-Gerhard

**Comment by phw198** [comment]
For the second option - have you seen [this VBA option](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#start-ogcs-after-outlook)?

**Comment by phw198** [comment]
:package: For the first option, you can select up to 600 seconds delay with [hotfix v2.10.4.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/15139054/v2.10.4.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `1ED971F5` Exe = `69647EC6`

Please let me know how it goes.
