### ISSUE TITLE
OGCS doesn't show up when trying to open it while a notification bubble is displaying

### ISSUE THREAD

**Issue by Fafner1976** [phw198/OutlookGoogleCalendarSync#1847]
**OGCS Version**: v2.10.4.0 (but was happening on previous ones as well)
**Edition**: Portable  
Windows 10
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
OGCS doesn't show up when trying to open it while a notification bubble is displaying

**Steps to Reproduce the Issue**  
1. Click on the tray icon while a notification bubble is displaying. 
2. OGCS doesn't show up, it just appears in the apps bar, clicking on the app bar icon doesn't make it show up either
3. Any subsequent try to make it show up fails until I close and restart the app

**Comment by phw198** [comment]
I'm assuming you have OGCS set to minimise to the notification tray?

:package: If so, I think this should be resolved with [hotfix v2.10.4.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/15139210/v2.10.4.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `357537EF` Exe = `DD57D293`

Please let me know how it goes.

**Comment by Fafner1976** [comment]
Yes I do! Will test it Monday once back to office.

**Comment by Fafner1976** [comment]
Fixed, thx!
