### ISSUE TITLE
How to save settings

### ISSUE THREAD

**Issue by cp27643** [phw198/OutlookGoogleCalendarSync#1848]
**Are you already using OGCS?**
2.10.4.0

**Describe the question you have**
Hello, 

I am wanting to lock down my settings file now that I finally have the application working the way I want it to. Can i just set the settings.xml to read only, or is there a better way to lock settings?

**Comment by phw198** [comment]
No, you can't set the file to read-only as it is written to throughout normal operation of OGCS. Probably simplest to use the `Export` function on the `Save` button, so you can save a copy of the settings somewhere.
