### ISSUE TITLE
Trial do delete items taht have been copied to a later date/time

### ISSUE THREAD

**Issue by IngolfE** [phw198/OutlookGoogleCalendarSync#1858]
**OGCS Version**: v2.10.4.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I copy an item from the past (just finished .e.g.) in outlook to have it later with the same description and same invitationgroup. Once OGCS is sync'ing now at offers me the possibility to delete the source item... even if I deny, it is asking again and again.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/15316652/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. In Outlook: Copy an item from the past to a later date/time 
2. Having "Confirm deletions" checked in OGCS, wait for sync... You'll be asked to delete

**Comment by phw198** [comment]
[This will be pertinent](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#outlook-appointment-copy--paste) - is OGCS definitely running in the background when you copy and paste?

The logs should capture a line `Item paste event caught`, but I don't see that in your log file...

**Comment by phw198** [comment]
Meanwhile, to fix the unwanted deletion you have right now, [see here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).

**Comment by IngolfE** [comment]
Hi Paul
Yes OGCS is definitely running in the background.
Regards
Ingolf

Paul Woolcock ***@***.***> schrieb am Fr., 17. Mai 2024,
01:08:

**Comment by phw198** [comment]
Please could you provide evidence:-

1. Close and reopen OGCS
2. Go to Outlook and copy and paste an appointment
3. Provide your ogcalsync.log file (log into GitHub to provide it)

**Comment by IngolfE** [comment]
Hi Paul. Indeed, I couldn't recognize the  described issue again. Pls,
close the ticket, in doubt I'll re-open it later on.
Cheers!
Ingolf

github-actions[bot] ***@***.***> schrieb am Do., 27. Juni
2024, 10:38:
