### ISSUE TITLE
When upgrading to version 2.10.5.0 error received.

### ISSUE THREAD

**Issue by Veggie352** [phw198/OutlookGoogleCalendarSync#1861]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.5.0
**Edition**: Installed   
**Sync Direction**: O<->G

**Bug Description**  
After I upgraded to v2.10.5.0 I received a pop up error box entitled Calendar Folders. The message read: A problem was encountered when searching for Outlook calenda folders. Cannot access a disposed object. Object name: 'TabPage'. On clicking OK, the window reappeared. All I could do was to kill OGCS in task manager. Can you assist please?
**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
![OGCS error](https://github.com/phw198/OutlookGoogleCalendarSync/assets/54488753/7bbe9291-3c1a-4fdc-94cb-ad17b6fe9a3a)

**Comment by phw198** [comment]
:spiral_notepad: If you can provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)), I'll take a look.

**Comment by phw198** [comment]
Thanks for the logfile. Yes, it was pretty niche - basically v2.10.4 was still initialising (and having trouble connecting to the Outlook client for some reason) and at the same time the upgrade ran and then started shutting down the application.

I've now made that shutdown much more forceful, so the initialisation doesn't attempt to continue. However, this won't be available until v2.10.6 and upgrading from there.

**Comment by Veggie352** [comment]
Thanks for the update. Do I need to delete and reinstall the app, or will it function correctly.

**Comment by phw198** [comment]
The issue is only related to completing the end of the upgrade, otherwise what you have installed is working fine - I'd suggest you just stay with what you have.

**Comment by Veggie352** [comment]
Thanks for the confirmation

**Comment by Veggie352** [comment]
I have just upgraded to v2.10.6.0 – Alpha and I am getting the following error at the end of the upgrade. Clicking OK does not close the message. I have had to kill the application in task manager. Can you advise please and is OGCS working correctly?

 



 

 

From: Brian Krasner ***@***.***> 
Sent: Tuesday, May 21, 2024 9:04 AM
To: 'phw198/OutlookGoogleCalendarSync' ***@***.***>; 'phw198/OutlookGoogleCalendarSync' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [phw198/OutlookGoogleCalendarSync] When upgrading to version 2.10.5.0 error received. (Issue #1861)

 

Thanks for the confirmation

**Comment by phw198** [comment]
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by phw198** [comment]
Also, take note of my earlier post:

> However, this [fix] won't be available until v2.10.6 and upgrading from there.
