### ISSUE TITLE
keep getting outlook security error

### ISSUE THREAD

**Issue by ElFreshPrince** [phw198/OutlookGoogleCalendarSync#1862]
A program is trying to access email address information stored in Outlook. If this is unexpected, click Deny and verify your antivirus software is up-to-date.
For more information about email safety and how you might be able to avoid getting this warning, click Help.

found this youtube vid to disable the error message - https://www.youtube.com/watch?v=pX7vGIE8O5k

**Comment by phw198** [comment]
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security

**Comment by ElFreshPrince** [comment]
> https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security

Was greyed out for me as the video showed had to open in administrator mode then it was ungreyed and could follow instructions. :)
