### ISSUE TITLE
Auto deleting when entries fall within sync date range

### ISSUE THREAD

**Issue by Billpherry** [phw198/OutlookGoogleCalendarSync#1863]
**OGCS Version**: 2.10.0.0 
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I've noticed recently that OCGS keeps trying to delete entries that are in my Google Calendar instead of syncing them as it comes across them when they fall within the sync date range. I have it set to confirm deletions after I noticed this happen recently and am struggling to work out why.

I noticed it happen with an event this morning and have attached the log for reference.

**Steps to Reproduce the Issue**  

The issue happens on auto sync and manual sync.

**Any other information**  
Any additional information that may help troubleshoot the issue.  

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/15375630/OGcalsync.log)

**Comment by phw198** [comment]
:arrow_double_up: Please confirm if you still see the issue after upgrading to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

Alternatively you can [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

**Comment by Billpherry** [comment]
Hi Paul, sadly I still have the same issue, it asks me if I want to delete the entries in Google, but then subsequently create them in Outlook, the log file is attached for reference.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/15429764/OGcalsync.log)

**Comment by phw198** [comment]
Your log only seems to show the deletions for two annually recurring birthdays, for which the monthly occurrence has fallen into the sync date window. Are you sure these weren't synced to Outlook at some point previously and either were manually removed from Outlook; or the Google series was updated/recreated.

Hmmm, actually I see you are setting all Outlook synced items with a Yellow category and then excluding any Outlook items without a category assigned. So, did you turn that configuration on _after_ the annual series were synced? Ie the birthday series flagged for deletion in Google don't have a category in Outlook and were excluded?

**Comment by Billpherry** [comment]
Aah, now you mention this, I noticed for a while that each time my rules
ran it was trying to delete everything from the opposing calendar, so I
added the category exclusion, likely after the series was synced. Thanks
for your help Paul, I'll work with recreating the entries as they occur...

**Comment by phw198** [comment]
Great, that one had me flummoxed for a while! Might be worth setting the categories in Outlook for them now and/or temporarily sync a year into the future so as to capture all the annual recurring series and fix them in one go...
