### ISSUE TITLE
Attendees from outlook meeting do not appear in google calendar

### ISSUE THREAD

**Issue by cannedconcept** [phw198/OutlookGoogleCalendarSync#1866]
Just installed, looks good. Interface is so much better than calldav synchronizer. Using 2.10.0.0. As I started fresh I completely deleted my outlook profile and preferences and set it up from scratch. My calendar was empty when I started setting up this tool. What I did is "add a calendar from internet" and this way added my google calendar (the same one as I sync to and from). Just for checking purposes.

I have some findings about attendees...

In my default outlook calendar pane, events that have been synced from google, will not show 'required' or 'optional' attendees in normal view (usually below 'from' and'title' field). In the google calendar pane within outlook it will show these fields and the attendees. 

In 'scheduling assistent' view it will however show attendees in both the outlook calendar pane as the google calendar pane within outlook (when opening the events).

I have noticed that the top menu for a calendar event that does show the required and optional attendees will say 'File/Meeting/Scheduling assistent' and a calendar event that doesn't show these fiels will say 'File/Appointment/Scheduling assitent'. This leads me to believe it has to do with outlook not understanding who created the event when importing it.

Can I fix this so I don't have to switch to 'scheduling assistent'? 

Another issue is that if I create an event from outlook it will sync to google calendar. However, when opening the google calender from a browser it will not show attendees/guests at all? Also it will not show attendees when viewing the event from my google calender pane in outlook. Not even from 'scheduling assistent'.

This is rather important to have however, can I fix this thru settings?

Regards!

**Edit:**
I just created an event in google calender from the browser. The attendees from this event are being synced to my outlook, both in the default outlook calendar pane (under scheduling assistent) as in the google calendar pane (in the required field beneath from and title field)

**Comment by phw198** [comment]
> What I did is "add a calendar from internet" and this way added my google calendar (the same one as I sync to and from)

You say this is for checking purposes, but then it's unclear which calendar you are referring to in the rest of your post. For the sake of absolute clarify, this internet calendar should form no part of your OGCS sync configuration.

I'm assuming you have actually checked the box under `Settings` > `Options` > `What` > `Attendees`? Note the description says it only affects newly synced items - if you synced them already and then turned on attendees, you need to run a full sync (press `Shift` while clicking `Sync`) or modify the calendar item in some way to force it to sync again.

Your logfile and some screenshots would help - I don't really know what you mean by a "default pane" and "normal view".

FWIW, the type of a calendar item will automatically change from appointment (no attendees) to a meeting (with attendees) when attendees are involved.

**Comment by cannedconcept** [comment]
Sorry for miscommunication. Added a screenshot to clarify. The left pane is my local Outlook calendar to and from which I am syncing my Google calendar, referred to this as the default pane. The right pane is the Google calendar as a subscription, nor Outlook nor OGCS do anything to that one, referred to that as the google calendar pane. It's just there for viewing/checking purposes.

I had the check at attendees on from the beginning and set to the default <200.

Hope this helps.

![screenshot](https://github.com/phw198/OutlookGoogleCalendarSync/assets/13829075/38a0269f-b256-410e-a9fc-03a64e2fadd5)

**Comment by phw198** [comment]
Thanks for the clarification and screenshot 👍🏻 

> In my default outlook calendar pane, events that have been synced from google, will not show 'required' or 'optional' attendees in normal view (usually below 'from' and'title' field). In the google calendar pane within outlook it will show these fields and the attendees.
>
> In 'scheduling assistent' view it will however show attendees in both the outlook calendar pane as the google calendar pane within outlook (when opening the events).
>
> I have noticed that the top menu for a calendar event that does show the required and optional attendees will say 'File/Meeting/Scheduling assistent' and a calendar event that doesn't show these fiels will say 'File/Appointment/Scheduling assitent'. This leads me to believe it has to do with outlook not understanding who created the event when importing it.
>
> Can I fix this so I don't have to switch to 'scheduling assistent'?

As far as I'm aware, that's always been how Outlook works - I've never seen attendees listed under the organizer/time/location headings; always have to go into the Scheduling Assistant. The organiser will always be you in Outlook even, though, as it's not possible to set the organiser to someone else when it is synced over from Google.

> Another issue is that if I create an event from outlook it will sync to google calendar. However, when opening the google calender from a browser it will not show attendees/guests at all?

I'd need to see your logfile to diagnose any further - ideally after you have started OGCS, set the logging level to `FINE` and then run a sync that should create a Google item with attendees and/or modify one with new attendees.
