### ISSUE TITLE
Backup of settings.xml before resetting to default

### ISSUE THREAD

**Issue by jedison** [phw198/OutlookGoogleCalendarSync#1867]
I had some issues on Windows (disk space down to 255MB, large pagefile) and needed to reduce pagefile size.
After that, some applications show problems including OGCS now having an empty settings.xml.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/15416224/OGcalsync.log)
2024-05-23 13:23:39,368 WARN  1 OutlookGoogleCalendarSync.Settings [330] -  Resetting settings.xml file to defaults.

What about taking a backup of the corrupted settings.xml file before resetting to defaults or asking the user what they would like to do, so that all of those settings are not completely lost?

**Comment by phw198** [comment]
Thanks for the suggestion @jedison - the next release will provide the opportunity to backup the settings to a file before they are reset 🙂
