### ISSUE TITLE
Issue with OGCS "items in folder do not match"

### ISSUE THREAD

**Issue by nnndrea** [phw198/OutlookGoogleCalendarSync#1869]
Hi there, I am using OGCS Version 2.10.0.0.
I am synching some of my Outlook items to my private Google calendar - I am using the tool already since 1,5 years and I like it very much. 
I was already on a higher version, but independent on what I change in the settings, I keep getting this error: 
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/170725654/6c82990f-1375-450f-a21e-847a0e90be1d)
"One or more items in the folder you synchronized do not match. To resolve the conflicts, open the items, and then try this operation again."

First of all, I do not know which items in which folder - therefore I removed all synched items from my Google calendar and tried synching only futures items -without success. I removed the tool, no change. I changed couple of other settings, nothing helps.

So please, what do I need to do to get my items back in Google calendar? Unfortunately (as written above) I deleted most of the items and I lack now appointments on my private calendar, which is quite annoying. 

Also it is annoying that this great tool does not work any longer for me.

Please help. Thank you very much! Best, Andrea

**Comment by phw198** [comment]
I'm pretty sure that is in an Outlook error message, not from OGCS. Have a look here for more details about the [Outlook conflict folder](https://www.howtogeek.com/377695/view-and-delete-sync-issues-in-outlook/).

**Comment by nnndrea** [comment]
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/170725654/821e7ee7-127e-4def-a88f-ede2f779f78a)
The message is at least triggered through OGCS, but it pops up when the Outlook calendar is scanned (as you can read on the screenshot). I read through the link you sent me, but it does not solve my problem :-) - Also I seem to use a different outlook version as I cannot make those folders visible/accessible and delete the sync error messages in there. I use a pc which is provided to my from my employer and it is also managed through them and my outlook/microsoft account is also a company one.

But still it would be nice if the issue could be solved. Thanks for another try.

**Comment by nnndrea** [comment]
please also find the log files of today attached:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/15451899/OGcalsync.log)

**Comment by Yikkayi** [comment]
Hello, do you still have access to the old/classic Outlook?  If so, I had the same error and followed Workaround 1 on this page to resolve it: https://support.microsoft.com/en-us/office/outlook-shows-conflict-errors-when-updating-or-cancelling-meetings-69c26227-40ef-4377-8f12-1749fcaad2ad.

I've also copied the steps below.

1. Open the Calendar pane in Outlook, and right-click the Calendar folder.
2. Select Properties.
3. On the General tab, select Clear Offline Items.
4. Select OK.
5. After you clear offline items, Outlook will re-sync the calendar and repopulate your calendar folder with the calendar items on the server. 

Hope this helps!

**Comment by nnndrea** [comment]
This was the solution! I do have the Outlook app on the computer, but I am not sure if it is the "classic version" - either way, I found the folder, I deleted the offline items and the sync is running and I have the right calendar entries synched from Outlook to my Google Calendar :-) 
Thank you very much!!

**Comment by phw198** [comment]
FWIW, this has been [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Resolving-Outlook-Error-Messages#one-or-more-items-in-the-folder-you-synchronized-do-not-match) for some time - but it doesn't seem OGCS is redirecting to that for users that are filtering items by category.
