### ISSUE TITLE
I've donated but the splash-screen cannot be removed

### ISSUE THREAD

**Issue by eladgross** [phw198/OutlookGoogleCalendarSync#1871]
elad.gross@gmail.com

[danation.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/15481162/danation.pdf)
![donation](https://github.com/phw198/OutlookGoogleCalendarSync/assets/171129760/11dca4dd-649f-4c03-b251-d0fc2c8fea38)

**Comment by phw198** [comment]
Hi @eladgross and thanks for your donation - I can see you have been set up for splash screen hiding; did you follow the instructions in the email you will have received?

**Comment by lammertsm** [comment]
Same issue here, donate at 17 june, but unabel to hide Splash screen.

**Comment by phw198** [comment]
@lammertsm There's very little I can do with such limited information. I can see someone donated on 17-Jun without specifying the Google account being used with OGCS - that may or may not be you, but they will have received an email on the same day requesting this information in order that I can set up splash screen hiding...

**Comment by lammertsm** [comment]
Hi,

Attached the e-mail I received after donation.

Kind regards,
Martijn Lammerts

**Comment by phw198** [comment]
Sorry, I must have been half asleep last night as I was checking 17 July, not June 🙄

I've forwarded the email to you again - please follow the guidance in it and if it still doesn't work, confirm the Google email address that is connected to OGCS and provide your log file. 

Note, you need to log in to GitHub to attach files.

**Comment by phw198** [comment]
@lammertsm As confirmed via email, you had changed the Google account with which OGCS was syncing. I have now switched over your donation too so the splash screen hiding is working again. Thanks!

**Comment by lammertsm** [comment]
Hi Paul,

All fine now, thanks for the support.


Martijn
