### ISSUE TITLE
No documentation on the Add Profile button

### ISSUE THREAD

**Issue by dbasam** [phw198/OutlookGoogleCalendarSync#1872]
**Are you already using OGCS?**
2.10.0.0

**Describe the question you have**
There is no documentation on what the purpose of the Add Profile button is, and whether all profiles are active at the same time, or how to control that feature.

**Comment by phw198** [comment]
Not quite true - it's documented in the User Guide: https://www.outlookgooglecalendarsync.com/guide/settings

But I'll add something similar to the Add Profile screen in the app too...

**Comment by phw198** [comment]
This is how it will look in the next release

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/d088ceaf-1793-4d75-ab7a-96da8d16c28b)

**Comment by dbasam** [comment]
My bad.  I thought I had looked through all the documentation, but I missed it somehow.  Thank you for making it more obvious.
