### ISSUE TITLE
Copied Outlook Item will not be synced to google but deleted in Outlook

### ISSUE THREAD

**Issue by flocke487** [phw198/OutlookGoogleCalendarSync#1875]
**OGCS Version**: v2.10.0 beta
**Edition**: Installed
**Sync Direction**:  O<->G

**Bug Description**  
When I copy an Outlook appointment to a later date, this will not sync to google but OGCS asks to delete the outlook appoint while syncing.

**Any other information**  
There is the same problem descirbed in an issue in 2017 and it is makred as solved. But I have this issue nevertheless. 
Insalled the app for the first time yesterday and wanted to add new appointments today and then the failure happens.

**Comment by phw198** [comment]
Please make sure you are familiar with the [limitations of copying items](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#limitations) - most importantly that OGCS must be running in the background when copying an already synced item.
