### ISSUE TITLE
Multiple Profiles Syncing At Once?

### ISSUE THREAD

**Issue by coryduude** [phw198/OutlookGoogleCalendarSync#1876]
Using OGCS v2.10.5.0

I have three profiles set up:
1. Outlook (work) to Google Individual 2
2. Google Individual 1 to Outlook
3. Google Family to Outlook

All profiles have schedules to sync every two hours.

(This is because I have three different Google calendars to shuffle among and the Outlook <-> Google only allows for 1-to-1 as I could see)

Right now I'm fairly sure that the sync is only happening for the most recently selected profile - for about a month after creating Profile 2, I didn't touch OGCS. My Google Ind. 1 calendar was syncing flawlessly to Outlook, but my Outlook calendar wasn't updating at all Google Individual 2.

But I see from other issues that that may not be the intended behavior? Is there a way to make sure OGCS is syncing all profiles with the rhythm I chose?

**Comment by phw198** [comment]
Yes, open each profile and make sure a schedule is set.

**Comment by coryduude** [comment]
> Yes, open each profile and make sure a schedule is set.

Thanks! I have a schedule saved for each profile, but know that some of the complications I've had aren't with OGCS at all but the various calendaring apps engaging with Google itself. I'll pay closer attention if I notice anything else amiss and if so, provide more detail for troubleshooting.  I just wanted to be sure there wasn't anything else I'm missing as a foundational level set. Thank you! :)
