### ISSUE TITLE
Update event failed to save Forbidden [403=Forbidden] when updating event on Google that should not actually be updated anyway?

### ISSUE THREAD

**Issue by LostInSwiss** [phw198/OutlookGoogleCalendarSync#1877]
> Checklist:-
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.5.0
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
For one of my profiles I Update event failed to save Forbidden [403=Forbidden] error when doing a bidirectional sync with Google.
The event that triggers the issue was created from google to outlook and despite no edits being made to in in outlook the app thinks the event has changed in outlook and try's to sync changes back to google. Since I do not own the item in my calendar it creates an error. The issue appears to be with the reoccurring event rules.
[OGcalsync - Copy.log](https://github.com/user-attachments/files/15809589/OGcalsync.-.Copy.log)

**Steps to Reproduce the Issue**  
Sync from google to outlook with a reoccurring google event with particular rules
Bidirectional sync between outlook and google

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
That's correct, you can't run a bi-directional sync when you don't own items in the target calendar. Here OGCS has detected more recent changes in Outlook for the recurrence rule, description and reminder, but as you say, doesn't have the permission to make those updates in Google.

Do you have write permission on the Google calendar at all, or is it just this individual item that's read-only? If the latter, how does this situation happen? Eg if I have an invite from someone else in my Google calendar, I still have rights to change it, so I'm not sure how to reproduce the error you have got...

**Comment by LostInSwiss** [comment]
Hello. I have worked around this by getting write permission on the calendar effected however I did not change the item in outlook it was created by OGCS and (from google) and the second sync raised the error with no edits by myself in Outlook.

**Comment by phw198** [comment]
So the entire Google calendar you were syncing with was read-only previously? OGCS should prevent that for two-way sync, as soon as such a calendar is selected:-
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/54859ca1-5718-4c99-baa7-0795ee187e75)
Ah...just tested that and it doesn't then prevent you syncing it subsequently 😖

**Comment by LostInSwiss** [comment]
just to add that I did/do have permission to edit the calendar but not the effected item in the calendrer (item owned by another google account I did not have permission to edit but accepted by one I did have permission to edit). As mentioned before I have now edit access to both accounts so don't have the issue any more.
