### ISSUE TITLE
Sync without the Outlook client!

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1881]
Since Microsoft have started rolling out the New Outlook client, I have been developing a version of OGCS that does not depend on any  Outlook client at all. Instead OGCS will connect to your Outlook calendar in much the same way as it does for Google (using OAuth) and authorising OGCS to manage your calendar.

## ⚠️ Disclaimer

**Bleeding edge development builds** will be posted here. This means:-
* Bad Things might happen. Only try these builds if you are OK with that.
* Many features are not yet implemented. See [Project KanBan](https://github.com/users/phw198/projects/2/views/1) for details.
* Feedback is welcome, though I may already be resolving an issues you may have.
   * [Kanban items](https://github.com/users/phw198/projects/2/views/1) under `Early Sight` may have issues being actively worked on; `UAT` should be more stable and certainly worth reporting bugs

## 🚧 Setup Recommendations
* Create a new Outlook calendar for OGCS to sync with.
* Unzip the development build to a new directory and have it use a new settings and log file:
```cmd
mkdir c:\temp\OGCS-dev
cd c:\temp\OGCS-dev
```
Unzip the development build into the new directory
```cmd
call OutlookGoogleCalendarSync /t:"Development Build" /s:.\settings.xml /l:.\OGcalsync.log
```

## 📦 Development Builds

| Version | Type | Release Date | Notes |
|--------|--------|--------|--------|
| [3.0.0.1](https://github.com/user-attachments/files/15859398/Portable_OGCS_v3.0.0.1.zip) | Full ZIP | 16-Jun-2024 | <li> G->O: Create & delete of single instance items</li> |

### One-Way Sync: Google -> Outlook
* Only creation and deletion of single instance items
* Recurring series will only have the initial "master" occurrence synced
* No reclaiming of orphans
* No updating of changes
* No category/colour sync

**Comment by TheJacksonian** [comment]
Where is the best place for feedback?
I'll reply here, but happy to move if required. I get an Application unexpectedly terminated on start, 'Object reference not set to an instance of an object'.
Log attached.
[OGcalsync.log](https://github.com/user-attachments/files/15860122/OGcalsync.log)
