### ISSUE TITLE
OGCS keeps creating a recurring event, eventhough it is ended in the past

### ISSUE THREAD

**Issue by terpenthijn** [phw198/OutlookGoogleCalendarSync#1884]
**OGCS Version**: v2.10.5.0  
**Edition**: Installed
**Sync Direction**: G->O

**Bug Description**  
I have a google calendar recurring event called "Isa streetdance". This event ended at April 15th 2024. For some strange reason, OGCS keeps creating a new recurring event in Outlook, everytime it syncs agenda's. I even tried to empty my Outlook agenda and a Full sync but this didn't help... Do you know what's going wrong here?

```
2024-06-18 09:02:32,349 INFO  15 OutlookGoogleCalendarSync.Console [351] -  Creating 1 Outlook calendar entries
2024-06-18 09:02:32,386 DEBUG  15 OutlookGoogleCalendarSync.Outlook.Calendar [355] -  Processing >> 4-10-2021 16:30 (R) => "Isa streetdance"
2024-06-18 09:02:32,387 DEBUG  15 OutlookGoogleCalendarSync.Console [349] -  4-10-2021 16:30 (R) "Isa streetdance"
2024-06-18 09:02:32,560 DEBUG  15 OutlookGoogleCalendarSync.Recurrence [322] -  Converting RRULE:FREQ=WEEKLY;UNTIL=20240421T215959Z;BYDAY=MO
2024-06-18 09:02:32,754 DEBUG  15 OutlookGoogleCalendarSync.Outlook.CustomProperty [451] -  4-10-2021 16:30 => "Isa streetdance"
2024-06-18 09:02:32,766 DEBUG  15 OutlookGoogleCalendarSync.Outlook.CustomProperty [0] -  googleCalendarID=ir********s@gmail.com
2024-06-18 09:02:32,781 DEBUG  15 OutlookGoogleCalendarSync.Outlook.CustomProperty [0] -  googleEventID=1l7osoh6v5fnmeb64hh6125niv
2024-06-18 09:02:32,822 INFO  15 OutlookGoogleCalendarSync.Sync.Engine+Calendar [731] -  Done.
```

Thanks for your help.

[OGcalsync_iris_2024-06-18.log](https://github.com/user-attachments/files/15897360/OGcalsync_iris_2024-06-18.log)
![2024-06-19_09-56-07](https://github.com/phw198/OutlookGoogleCalendarSync/assets/88192021/b2a88432-5e3f-4773-b58e-efecc127c6ca)

**Comment by phw198** [comment]
Initially no, I don't know what's going on! I can see OGCS is also calculating the recurrence end date to `UNTIL=20240421T215959Z` which matches what you say for a weekly event. So I have no clue why Google is returning that when only items after 19-Jun should be retrieved.

Was this series recurring for longer and then it was shortened? Do you recall how the series was shortened? Eg changing the last date on the series, or deleting the 22-Apr event and then selecting "this event and following"?

**Comment by terpenthijn** [comment]
Yes, it was recurring for longer and shortened. I'm not sure what the original end date was> I can try changing the last date... To solve this problem I can easily delete this event since it happend in the past. This post was more to signal a possible bug.

**Comment by phw198** [comment]
It feels like the bug is more likely to be on Google's side, if anything - but I'm wondering if there are basically "cancelled" events after 15-Apr, which you can't see but are causing the series to be returned for sync. That _shouldn't_ be the case though, given the series ends on 15-Apr.

Would be useful if you
1. Go to https://calendar.google.com/calendar/u/0/r/week?eventdeb=1
2. Find the series
3. Click on an event, then the 3-dot vertical elipsis menu &vellip;  scroll to the bottom of the menu and `Troubleshooting info" and copy the details here

**Comment by terpenthijn** [comment]
Event{eid=1l7osoh6v5fnmeb64hh6125niv_20240408T143000Z, organizer=ikke@irismartens.nl, participant=irismartens@gmail.com, actor=thijnjacobs@gmail.com, summary=Isa streetdance, status=CONFIRMED, seq=1, startTime=2024-04-08T14:30:00Z, endTime=2024-04-08T15:30:00Z, firstStart=20211004T163000, rdata=RRULE:FREQ=WEEKLY;BYDAY=MO}

**Comment by terpenthijn** [comment]
Event{eid=1l7osoh6v5fnmeb64hh6125niv_20240408T143000Z, organizer=i*****@*****.nl, participant=i*****@gmail.com, actor=t*****@gmail.com, summary=Isa streetdance, status=CONFIRMED, seq=1, startTime=2024-04-08T14:30:00Z, endTime=2024-04-08T15:30:00Z, firstStart=20211004T163000, rdata=RRULE:FREQ=WEEKLY;BYDAY=MO}

**Comment by phw198** [comment]
So yes, I'd say that's a Google bug - it doesn't have an `UNTIL` definition in the `RRULE` which would we be why OGCS still retrieves it in June. 

Here's what Google gives me for a weekday recurrence in my calendar, ending in December:
`firstStart=20230104T113000, rdata=RRULE:FREQ=WEEKLY;UNTIL=20241220T120000Z;BYDAY=MO,TU,WE,TH,FR`

**Comment by terpenthijn** [comment]
Thanks for looking into this... Case closed :)
