### ISSUE TITLE
Unable to update existing entries (inviting colleague deleted single events from recurrent event)

### ISSUE THREAD

**Issue by HenrikJanPersson** [phw198/OutlookGoogleCalendarSync#1895]
**OGCS Version**: v2.10.5.0  
**Edition**: Portable  
**Sync Direction**: G->O 

**Bug Description**  
```
2024-06-28 11:30:07,821 ERROR  3 OutlookGoogleCalendarSync.Console [347] -  Unable to update existing entries in the Outlook calendar.
2024-06-28 11:30:08,161 WARN  3 OutlookGoogleCalendarSync.Outlook.Errors [32] -  [0xCE604005] >> You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
2024-06-28 11:30:08,161 ERROR  3 OutlookGoogleCalendarSync.Exception [29] -  System.Runtime.InteropServices.COMException: You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
```
Not sure about the reason for this, the original entrance (a recurring event invited by a colleague) is still available in my Outlook, I have closed all Outlook instances running and resynced without success.

I think that the colleague deleted two of the recurrent events during the vacation coming up.

[OGcalsync.log](https://github.com/user-attachments/files/16027512/OGcalsync.log)

**Comment by phw198** [comment]
I notice it also fails to access the the 28-May occurrence of `4/16/2024 12:00 PM (R) => "VL: PeatForest HORIZON biweekly consortium meeting"` when syncing O->G, but it ignores that as it's outside the sync window. 

Does that occurrence actually exist in Outlook? If it does, shutdown Outlook and OGCS and make sure there is no `outlook.exe` or `outlookgooglecalendaysync.exe` process running in Task Manager. Then start then back up and see if it helps?

I feel like OGCS should probably ignore the item again for being outside the sync window anyway, but maybe it can't in order to check if the occurrence has moved dates. I'll have to check the code more closely....

**Comment by HenrikJanPersson** [comment]
It does, both on the 28th of May and the original on April 16,  and I closed all Outlook instances and OGCS and restarted it, with the same problem persistent. 
![Screenshot 2024-06-28 135115](https://github.com/phw198/OutlookGoogleCalendarSync/assets/59896277/209832c6-8fc9-4e1c-ba58-e3598063c634)

**Comment by phw198** [comment]
Can you confirm exactly what is different about the exception on 28-May? (eg, subject, location, body, time, time zone...)

After some Googling there are comments around the timezone being different and/or occurrence having been edited on an iOS device (perhaps by the organiser) which breaks the timezone.

Also, are you able to open the occurrence manually in Outlook, make an edit and save it? Or do you get the same error message "You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again."?

I've not been able to reproduce the problem thus far...

**Comment by phw198** [comment]
Could you also confirm if you can see the 28-May exception on Outlook on the Web? 

This thread suggests you have to get the organiser to remove you as an attendee and then re-invite you: https://learn.microsoft.com/en-us/archive/msdn-technet-forums/2ed2d279-3152-4d4b-a9fa-ae2f8d363710

You could maybe just try deleting the 28-May occurrence in Outlook first, given it's in the past now.

**Comment by HenrikJanPersson** [comment]
I cannot notice any differences in terms of subject, location, time or time zone... but the body is slightly different in the sense that the host had updated that specific meeting event with a complementary text on top of the automatically generated invitation text.

I could update the subject and save the event, but it had no impact on the success of synchronization.

I do see it in the Outlook on the Web.

Deleting the event in Outlook and then in Google Calendar worked, such that it was no longer complaining about this event. Yet, since it was part of a series of biweekly meetings, OGCS gave an error referring to the very first event in the series, with "Appointment update failed. The object does not support this method." 

Anyways, it is a sufficient work-around for me now and it is OK to close this from my point of view.

**Comment by phw198** [comment]
Thanks @HenrikJanPersson could you maybe send the log through (it'll be the one dated 1-Jul) for that final error message you mention, just in case that holds a clue as to the original problem?

**Comment by HenrikJanPersson** [comment]
Certainly. 
[OGcalsync.log.2024-07-01.log](https://github.com/user-attachments/files/16063994/OGcalsync.log.2024-07-01.log)
