### ISSUE TITLE
COM error - 800700c1  is not a valid Win32 application

### ISSUE THREAD

**Issue by cmbuckley** [phw198/OutlookGoogleCalendarSync#1901]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.5
**Edition**: Installed (but also happens on Portable)
**Sync Direction**: Two separate profiles, G->O / O->G

**Bug Description**  

Application will not start - the following error message seen:

**Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 800700c1  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1).**

**Steps to Reproduce the Issue**  

Cannot open the application - no repro steps. I can share more info about the machine if needed. This has been working fine until recently, so perhaps related to a system update? The log mentions "PoorlyOfficeInstall" - I've been running both new and classic Outlook side by side for a while so I can use OGCS.

[OGcalsync.log](https://github.com/user-attachments/files/16096545/OGcalsync.log)

**Comment by phw198** [comment]
Looks like the classic Outlook isn't fully running, so OGCS is trying to start it and failing - normally this error is a problem between 32/64-bit executables, but nothing has changed recently with that on OGCS's side, so I suspect something has changed with the install/upgrade of the Outlook client(s).

As a workaround, does it make any difference if you make sure classic Outlook is fully running (eg you can view the inbox or calendar folder) before starting OGCS?

**Comment by cmbuckley** [comment]
I had made sure that Classic Outlook was fully running before trying to start OCGS, and that didn’t seem to make a difference. However, I’m unfortunately no longer able to reproduce this; it’s one of those issues that disappeared after a couple more restarts. Please feel free to close this and I’ll try get more info if it happens again !

**Comment by phw198** [comment]
Thanks for reporting back - maybe an Outlook install issue was resolved through the reboots!?

I'll close the ticket, as suggested...
