### ISSUE TITLE
Calendar event deletion spam

### ISSUE THREAD

**Issue by preserved-killick** [phw198/OutlookGoogleCalendarSync#1902]
Version # 2.10.0.0

I have OGCS installed on multiple computers. I have a profile set to mutually sync outlook <--> google. On my home PC every time OGCS syncs, it tries to delete a huge number of calendar events. I do not understand On my office PC this does not happen. I have checked and double checked the sync and application settings, and they appear to be identical. 

What could this possibly be attributed to? Here are pictures of my settings. I have tried reinstalling the application, creating a new sync profile with default settings. Something I would like to try but can't figure out, is to de-connect OGCS from my outlook email, and reconnect it. How do I do that? 

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/174825056/d050b0c5-be91-4b61-a4da-6886b87fea16)

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/174825056/ec9984a0-79de-40a7-9608-725e79597840)

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/174825056/ad3c42ee-6682-4ec0-8c0d-5587bf80848c)

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/174825056/5a9e894a-a823-404c-b24b-4d9d8c350509)

**Comment by phw198** [comment]
Hi @preserved-killick 

Unfortunately, screenshots are of very limited help - the log file is the only thing of real substance to troubleshoot issues. Meanwhile:
* What is the Outlook account you are syncing? An Exchange mailbox or something else?
* You said OGCS is on "multiple computers" - how many, and do they _all_want to make large scale deletions except for the office PC? I'd suggest reducing the problem to 2 machine: your work install which is OK and your home install which apparently is not.
* Where are the deletes being requested for? Outlook or Google?
* Assuming Outlook is the "master" and deletions are requested for there, have you followed guidance for [fixing stubborn unwanted deletions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync)?

**Comment by preserved-killick** [comment]
Oh my gawd thank you so much. 
The 'fixing stubborn unwanted deletions' guide worked. I had to sync google-->outlook, then mutual sync. I had done some searching and perusing but had not found that, thank you for pointing it out to me.
