### ISSUE TITLE
Not sure this is a bug

### ISSUE THREAD

**Issue by VirlBlack** [phw198/OutlookGoogleCalendarSync#1904]
I'm using the same sync rules structure I have used for the last 2-3 years  I have included a screen shot.  I don't know how to tell which items are causing this conflict.  Please see attached screen shot below:
![Screenshot 2024-07-09 102106 OutlookGoogleCalendarSync](https://github.com/phw198/OutlookGoogleCalendarSync/assets/175137950/1479f421-8401-4eaa-8bbb-e2ee10b61981)

**Comment by VirlBlack** [comment]
[OGcalsync.log](https://github.com/user-attachments/files/16145723/OGcalsync.log)

**Comment by phw198** [comment]
Looks like a duplicate of #1869

**Comment by VirlBlack** [comment]
Thank you Paul.  I don’t know exactly how to find the numbers of the entries, but I did finally find the dup and all working.
