### ISSUE TITLE
Paying for unlimited API access starts tripping DeviceGuard

### ISSUE THREAD

**Issue by alanarthur** [phw198/OutlookGoogleCalendarSync#1905]
Everything was running fine but I tripped the Google API limit, paid the £12 subscription fee and now get an error saying that DeviceGuard is preventing the API from being loaded. This is a corporate PC and my work does use app whitelisting, but they have allowed OGCS and was all working fine. It looks like something has changed by activating the subscription. Corp IT support say the OGCS exe is still whitelisted.

> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.5.0  
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
Everything was running fine but I tripped the Google API limit, paid the £12 subscription fee and now get an error saying that DeviceGuard is preventing the API from being loaded. This is a corporate PC and my work does use app whitelisting, but they have allowed OGCS and was all working fine. It looks like something has changed by activating the subscription. Corp IT support say the OGCS exe is still whitelisted.

**Steps to Reproduce the Issue**  
1. Launch the app
2. Click on sync
3. Get error - Could not load file or assembly 'Google.Apis.Calendar.v3, Version=1.60.0.3088, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. Your organization used Device Guard to block this app. Contact your support person for more info. (Exception from HRESULT: 0x800711C7)

[OGcalsync.log](https://github.com/user-attachments/files/16154955/OGcalsync.log)
**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by alanarthur** [comment]
Actually, looking through the logs it looks like there was a version update around the time the problem started happening, so this might be the cause instead? 

2024-07-10 10:37:03,331 INFO  1 OutlookGoogleCalendarSync.Program [498] -  New upgraded version detected: from 2.10.4.0 to 2.10.5.0

**Comment by phw198** [comment]
How are your IT whitelisting the executable - just the filename or a "thumbprint" signature of the specific file? If the latter, they would need to whitelist every single version as they are released/you upgrade to them...

It's slightly odd that it's the Google library file that is referenced as blocked when you try and sync - I'm 99% certain the DLLs weren't updated between v2.10.4 and v2.10.5.
