### ISSUE TITLE
Crashed when starting, so uninstalled then ? same error on reinstall

### ISSUE THREAD

**Issue by Elephantoplasty** [phw198/OutlookGoogleCalendarSync#1908]
Hi All,

I have been using OGCS for quite a while, and it has been great.   Been using it with Outlook 2021.

It started refusing to start when PC was booted, generating a Windows error (sorry, don't have a copy).

So I uninstalled it, and tried to reinstall the latest version - 2.10.0-beta

Unfortunately, generated what appears to be the same error - see attached for image.

I'd appreciate suggestions on how to fix it - really want to keep using OGCS

Thanks,

Dave

**OGCS Version**: v2.10.0-beta  
**Edition**: Installed  
**Sync Direction**: NA - can't install it.  Used to be both ways if I recall correctly.

**Bug Description**  
As above.  

**Steps to Reproduce the Issue**  
Error could be reproduced prior to uninstalling by trying to start it.  And is now reproduced when I try to install it.

**Any other information**  
'OGcalsync.log` file of install attempt, and Windows error on attempt to reinstall.
![Install windows error](https://github.com/user-attachments/assets/e882e2c8-b1f4-4dd1-83a1-687b019cacdb)
[OGcalsync.log](https://github.com/user-attachments/files/16186016/OGcalsync.log)

**Comment by Elephantoplasty** [comment]
I ran Microsoft Office repair, and it seems like it is now working again.  

I just have to remember how I had it configured......

**Comment by phw198** [comment]
Yep, I think from v2.10.2, you'll automatically be taken to the wiki with the fix instructions (see #1710)

**Comment by Elephantoplasty** [comment]
Thanks.

 

Seems to be behaving again.

 

Dave
