### ISSUE TITLE
OGCS Fatally Crashing

### ISSUE THREAD

**Issue by buckaroo54** [phw198/OutlookGoogleCalendarSync#1909]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.5-alpha, v2.10.4 alpha, and v2.10.3 alpha
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I have been fighting with OGCS recently as it has been fatally crashing. It starts when I bootup and do not see the OGCS icon in the system tray. On realizing that, I look, and find that the shortcut has been deleted from the desktop and the Start Menu. I get an error message if I try to reinstall.

![image](https://github.com/user-attachments/assets/36354bdf-599a-41c4-9b29-4c2c40e795c6)
[SquirrelSetup.log](https://github.com/user-attachments/files/16203414/SquirrelSetup.log)

I can then uninstall OGCS from the Control Panel, but if I try to reinstall right away, I get the same error message as above. I am only able to reinstall once I restart. The installation appears successful - the shortcuts appear on the desktop and in the Start Menu again, and the icon appears in the system tray - but that only lasts for maybe a couple of minutes, and then the program crashes, the shortcuts disappear, and I'm back to where I started.

I have tried downgrading from v2.10.5-alpha to v.2.10.4-alpha and v2.10.3-alpha, but am having the same issue across all versions.

**Steps to Reproduce the Issue**  
To the extent not clear from the above, unknown

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/user-attachments/files/16203408/OGcalsync.log)

**Comment by phw198** [comment]
> but if I try to reinstall right away, I get the same error message as above. I am only able to reinstall once I restart. 

That sounds to match with the end of the squirrel.log
```
2024-07-13 15:07:35> ApplyReleasesImpl: Writing files to app directory: C:\Users\alang\AppData\Local\OutlookGoogleCalendarSync\app-2.10.5-alpha
2024-07-13 15:07:37> IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\alang\AppData\Local\OutlookGoogleCalendarSync\app-2.10.5-alpha\OutlookGoogleCalendarSync.exe' is denied.
```
...so I doubt a restart is necessary - just you most likely have an outlookgooglecalendarsync.exe process still running from that directory and reinstalling into the same directory then fails. Just fire up a Task Manager, find the process and kill it.

Once you've done that, does OGCS run OK if you execute it manually from `C:\Users\alang\AppData\Local\OutlookGoogleCalendarSync\app-2.10.5-alpha\OutlookGoogleCalendarSync.exe`?

**Comment by buckaroo54** [comment]
No.

(1) There is no second or additional instance of `outlookgooglecalendarsync.exe` running. In fact, there is not even a single instance of `outlookgooglecalendarsync.exe` running. This is confirmed in the Task Manager in that there is no process to kill.

(2) There is no `OutlookGoogleCalendarSync.exe` in the folder `C:\Users\alang\AppData\Local\OutlookGoogleCalendarSync\app-2.10.5-alpha\` although there is one in the folder above it (`C:\Users\alang\AppData\Local\OutlookGoogleCalendarSync\`).

(3) Trying to manually run `outlookgooglecalendarsync.exe` from `C:\Users\alang\AppData\Local\OutlookGoogleCalendarSync\` does nothing. I have the Task Manager open and `outlookgooglecalendarsync.exe` never appears, not even for a second.

(4) This wouldn't explain why the shortcuts have disappeared from the desktop and Start Menu (which they have).

I'm at a loss. Any guidance that you can offer is greatly appreciated.

**Comment by buckaroo54** [comment]
Tried upgrading to v2.10.6 - same problem :(
[OGcalsync.log](https://github.com/user-attachments/files/16255045/OGcalsync.log)

**Comment by phw198** [comment]
Your log file shows you have installed v2.10.5 fine and running a sync without issue, then upgrading to v2.10.6 and running a sync fine with that too.

No sign of crashes or anything untoward. If you are having this _after_ the period covered in the log file, then I would suspect something else is trashing/removing OGCS from your system - perhaps over zealous anti-virus quarantining, or if on a work computer, removal of unapproved software perhaps...

**Comment by buckaroo54** [comment]
I suspect you're right, that it must be something else. But I added the program to my anti-virus safe list, and it still happened. This is also happening on my personal computer; ironically, it works perfectly fine on my work computer 😕

Any ideas as to how I can identify the culprit?

**Comment by phw198** [comment]
Might be worth a look through the Application and System events in Windows Event Viewer - see if there's anything suspicious logged or a smoking gun of some kind...?
