### ISSUE TITLE
Unhandled API exception: 400=BadRequest

### ISSUE THREAD

**Issue by SteveGHub1** [phw198/OutlookGoogleCalendarSync#1912]
I have started seeing errors during the sync process.  It happens at every sync event.
I have upgraded to v2.10.0.0 but this didn't fix the issue.
I have uploaded the OGcalsync.log file to your GoogleDrive referencing this ticket number.
Sync Direction is: O<->G

**Comment by phw198** [comment]
Hi @SteveGHub1 

v2.10.0 is pretty old now (new Beta should be coming soon), and guidance is to update to the latest alpha before reporting issues. 

:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

Alternatively, [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

If the issue remains, please could you provide your logfile again. Thanks!

**Comment by Archie99999** [comment]
I had a similar problem. Also, when checking for update in the about page on the app (on same v2.10.0.0) it said that there are no updates available. Nor would it update using the "check for alpha releases" tickbox. However installing the latest version from the project website **did** work, and does seem to have fixed the problem, so thank you.

**Comment by SteveGHub1** [comment]
Hi Paul, updating to the 2.10.6.0 alpha version has had the desired effect and the sync process no longer shows this error.  Thanks so much for your prompt response, professional advice, and efficient service :O)
