### ISSUE TITLE
V3.0.0.4 crash at start

### ISSUE THREAD

**Issue by Morgan-6Freedom** [phw198/OutlookGoogleCalendarSync#1914]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v3.0.0.4
**Edition**: Portable  

**Bug Description**  
![image](https://github.com/user-attachments/assets/e18148aa-0729-490d-85da-53c2aa95ba27)

**Steps to Reproduce the Issue**  
1. Download V3.0.0.1
2. Unzip it in my downlaod folder
3. Download V3.0.0.4 hotfix
4. Take the two files and copy paste them in my /V3.0.0.1 folder
5. Choose "replace"
6. Open a terminal in the folder
7. > call OutlookGoogleCalendarSync /t:"Development Build" /s:.\settings.xml /l:.\OGcalsync.log
8. press Enter
9. App starts
10. App aks if I want the reports to be sent
11. I click Yes
12. I have the crash (screenshot)

**Any other information**  
If I click "no" it's the same
[OGcalsync.log](https://github.com/user-attachments/files/16331503/OGcalsync.log)

**Comment by phw198** [comment]
:package: Thanks @Morgan-6Freedom, this should now be resolved with [v3.0.0.5.zip](https://github.com/user-attachments/files/16340164/v3.0.0.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes...

**Comment by Morgan-6Freedom** [comment]
It worked.
Thank you for your hard work
