### ISSUE TITLE
Undo sync to google calendar?

### ISSUE THREAD

**Issue by Pavlacky** [phw198/OutlookGoogleCalendarSync#1917]
**Are you already using OGCS?**
2.10.0.0

**Describe the question you have**
I intended to sync a colleague's calendar as a read-only shared calendar in Outlook, but I accidentally synced that calendar to my default google calendar that had a two-way sync between Google and Outlook .  Now all my colleagues calendar events are in my default google calendar.  Is there a way to undo that calendar sync and revert to my original default calendar?

**Comment by phw198** [comment]
Worth having a read through https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#mass-deleting-synced-items but it's no easy task to revert tbh!
