### ISSUE TITLE
[V3.0.0.5] TimeZoneNotSupportedException

### ISSUE THREAD

**Issue by Fangh** [phw198/OutlookGoogleCalendarSync#1918]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v3.0.0.5  
**Edition**: Installed / Portable  
**Sync Direction**: G->O 

**Bug Description**  

**Steps to Reproduce the Issue**  
Sync my Google to Outlook

![image](https://github.com/user-attachments/assets/34a4030a-09d2-4afc-a841-2f5c9f83f003)

**Any other information**  

This is my outlook web parameters about timezone : 
![image](https://github.com/user-attachments/assets/4246806b-a1f4-47df-80a0-cf8c16907e61)

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/user-attachments/files/16378034/OGcalsync.log)

**Comment by phw198** [comment]
I have confirmed the issue is with all-day events - I'll hopefully get a fix out over the weekend.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v3.0.0.6](https://github.com/user-attachments/files/16482677/v3.0.0.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `4DBBACD7` Exe = `36E2AFF2`

Let me know how it goes.

**Comment by Fangh** [comment]
it worked.
Thank you ! I have a V3.0.0.x that is fully working for my needs ! I'm so happy !
Thank you for your hard work !
