### ISSUE TITLE
Transition from less secure apps to OAuth

### ISSUE THREAD

**Issue by raidenlal** [phw198/OutlookGoogleCalendarSync#1920]
**Bug Description**  
Google planes to deprecate unsecure apps pretty soon: https://support.google.com/a/answer/14114704

Is there a plan to implement this?

**Comment by phw198** [comment]
What do you mean? OGCS has never used basic auth, only ever Oauth.

**Comment by raidenlal** [comment]
Oh sorry, I have set up OGCS some time ago and somehow I forgot/got confused it with other utility that uses username/pass (unsecure).

Again, sorry about this.
