### ISSUE TITLE
How to unsync from Outlook?

### ISSUE THREAD

**Issue by pecbounce** [phw198/OutlookGoogleCalendarSync#1925]
v2.1.0-beta

Hi,

I'd like to sync everything from Outlook (work) to Google (personal) but only sync events as "busy" from Google to Outlook during working hours. But I wasn't able to do that so I want to reverse my two way sync and do an one way sync from Outlook to Google instead. How can I remove my Google events from Outlook? Thanks!

**Comment by phw198** [comment]
Duplicate of #1917, though that was asking about deleting from Google, the linked guidance is the same.
