### ISSUE TITLE
OGCS doesn't sync when minimized to the tray nor the Taskbar, only updates when I do it manually

### ISSUE THREAD

**Issue by jimgramling** [phw198/OutlookGoogleCalendarSync#1926]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)Done
> * [ ] Reproduce the issue  Not possible
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))   Cant figure out how to do this

**OGCS Version**: v2.10.6
**Edition**: Installed / Portable  Installed
**Sync Direction**: G->O / O->G / O<->G     O<->G

**Bug Description**  
OGCS does not  sync when minimized to the tray nor the Taskbar.  It only updates when I do it manually.  Previous versions synced even when minimized.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Sounds like you don't have a sync schedule configured.

**Comment by jimgramling** [comment]
That is not the case. I have the schedule set for 1 day in the past, 120 days in the future, every 2 hours and push immediately. If I minimize to the tray or the ask bar the schedule does not run until I do it manually. Is there another setting I am missing?

**Comment by phw198** [comment]
Those settings sound correct, but I am not able to replicate the issue. Can you provide your logfile to help troubleshoot the issue?

**Comment by jimgramling** [comment]
Thanks for your response.  For whatever reason, it now seems to be syncing on schedule while minimized to the tray. I’m not sure why, but I think you can close this case now.
