### ISSUE TITLE
InvalidArgument=Value of '0'

### ISSUE THREAD

**Issue by mrchadcooper** [phw198/OutlookGoogleCalendarSync#1927]
![Screenshot 2024-08-09 130250](https://github.com/user-attachments/assets/7be58664-e4d7-4ddb-92fa-de2a266fbf05)

**OGCS Version**: v2.10.6.0
**Edition**: Installed
**Sync Direction**: can't even get to this at this point

**Bug Description**  
The application wont load. Immediately there is an error, and I cannot add the logs.

**Steps to Reproduce the Issue**  
1. Load app crashes and pop up shows up.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
:spiral_notepad: You should still be able to find the `OGcalsync.log` file [with these instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)?

**Comment by mrchadcooper** [comment]
we can close this actually. For whatever reason there were multiple settings flies in there. I deleted them all and it loaded perfectly. Sorry about the random ticket.
