### ISSUE TITLE
Error after installation [0x8002802B]

### ISSUE THREAD

**Issue by thomaszietz** [phw198/OutlookGoogleCalendarSync#1928]
Hi, have issue while install newest OGCS on Win11 with Outlook 365:

![111111111111](https://github.com/user-attachments/assets/109cde3f-a4fe-4db8-b083-7290ab3490c2)

What can I do here?

Thomas

**Comment by phw198** [comment]
OGCS is installed fine, but your [Office install is knackered](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002802b---type_e_elementnotfound)...

**Comment by thomaszietz** [comment]
Hi phw198!
Many thanks - that works.
Thomas
