### ISSUE TITLE
Every calendar item throws exception on v2.11.0

### ISSUE THREAD

**Issue by Boechie** [phw198/OutlookGoogleCalendarSync#1929]
**OGCS Version**: v2.11.0  
**Edition**: Installed 
**Sync Direction**: O->G

**Bug Description**  
I just upgraded from v2.10.0 to v2.11.0. That version worked flawlessly for years. The new version throws an error and warning for every item. It can't sync any item.

**Steps to Reproduce the Issue**  
Just start OGCalSync and start a sync process. 
For every item in Outlook I get a message in the application like this:
![image](https://github.com/user-attachments/assets/bfbab3b4-d13b-4f8e-bc08-11eb2db2ad7d)
When OGCalSync started deleting all item from my Google Calendar, I cancelled the sync to not loose everything!

**Any other information**  
OGcalsync.log is attached, but I removed many lines that mentioned privacy information. I'm not allowed to share that publicly because of EU privacy legislation.
There are quite some lines like this:
2024-08-12 13:17:27,220 ERROR 11 OutlookGoogleCalendarSync.Exception [66] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_AllDayEvent()
   at OutlookGoogleCalendarSync.Outlook.Calendar.GetEventSummary(AppointmentItem ai, String& eventSummaryAnonymised, Boolean onlyIfNotVerbose) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 1487
**There is no user 'Paul' on my PC, nor does this directory exist.**
[OGcalsync-censored.log](https://github.com/user-attachments/files/16580991/OGcalsync-censored.log)

**Comment by phw198** [comment]
Hi - did you upgrade OGCS today? I don't see any indication of that in the log file.
```
2024-08-12 13:16:21,272 WARN  11 OutlookGoogleCalendarSync.Exception [19] -  Calendar item does not have a proper date range - cannot sync it. ExchangeMode=olOnline
2024-08-12 13:16:21,273 ERROR 11 OutlookGoogleCalendarSync.Exception [29] -  System.Runtime.InteropServices.COMException: Your server administrator has limited the number of items you can open simultaneously. Try closing messages you have opened or removing attachments and images from unsent messages you are composing.
```
Looks like you're running in Exchange Online mode instead of Cached - please try [turning cached mode on](https://support.microsoft.com/en-us/office/turn-on-cached-exchange-mode-7885af08-9a60-4ec3-850a-e221c1ed0c1c).

**Comment by phw198** [comment]
However, I have also noticed there is a change in filtering based on category, which isn't efficient due to you not having selected to exclude any categories. 

:package: This should now be resolved with [hotfix v2.11.0.1.zip](https://github.com/user-attachments/files/16582120/v2.11.0.1.zip)([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) if you would like to see if that helps too.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `75EA8C5B` Exe = `775A123D`

Please let me know how it goes.

**Comment by Boechie** [comment]
> Hi - did you upgrade OGCS today? I don't see any indication of that in the log file.
> 
> ```
> 2024-08-12 13:16:21,272 WARN  11 OutlookGoogleCalendarSync.Exception [19] -  Calendar item does not have a proper date range - cannot sync it. ExchangeMode=olOnline
> 2024-08-12 13:16:21,273 ERROR 11 OutlookGoogleCalendarSync.Exception [29] -  System.Runtime.InteropServices.COMException: Your server administrator has limited the number of items you can open simultaneously. Try closing messages you have opened or removing attachments and images from unsent messages you are composing.
> ```
> 
> Looks like you're running in Exchange Online mode instead of Cached - please try [turning cached mode on](https://support.microsoft.com/en-us/office/turn-on-cached-exchange-mode-7885af08-9a60-4ec3-850a-e221c1ed0c1c).

Hi @phw198 .

Thank you for the very quick reply! I did upgrade OGCS today, but I emptied/deleted the log file after that as it was rather big.

I now activated Cached mode. I will also install the hotfix and let you know how it goes.

Thanky you!

Boechie.

**Comment by Boechie** [comment]
Hi @phw198 ,

Activating Cached Exchange mode was quite a hassle... Nevertheless it solved the problems with OGCS! I did not need to install the hotfix, so I guess I will proceed without it? Or do you advise to install it?

Thanks for the great tool!

Boechie.

**Comment by phw198** [comment]
I think I would advise to install the hotfix anyway? Your logs showed many lines with "Could not access Categories property for...." and took from 13:11:56 to 13:14:22 - so around 3 minutes of unnecessary processing time. This might have sped up with cached mode switched on, but I would expect it to be faster still with the hotfix.

**Comment by Boechie** [comment]
@phw198  I was trying to install the hotfix, but Windows Defender keeps complaining about a trojan virus. I know this is a known issue, but Windows won't even let me start the app after applying the hotfix. It is remarkable that the new .exe is 1772KB in size whereas the original .exe is only 271KB in size. Is this correct and safe?

FYI: Even without the hotfix installed, those lines  "Could not access Categories property for...." are not in the log anymore after switching to Cached Mode.

**Comment by phw198** [comment]
I suspect you're trying to replace the wrong executable - the instruction say which one to replace (thought I might add to that to say it's _not_ the 271Kb one).

With cached mode on, it means that OGCS can now access the categories of each item - but it shouldn't be needing to check because you are not filtering by category. So a sync would still be quicker with the hotfix I think, but don't worry if it's being blocked by anti virus...

**Comment by Boechie** [comment]
> I suspect you're trying to replace the wrong executable - the instruction say which one to replace (thought I might add to that to say it's _not_ the 271Kb one).
> 
> With cached mode on, it means that OGCS can now access the categories of each item - but it should be needing to check because you are not filtering by category. So a sync would still be quicker with the hotfix I think, but don't worry if it's being blocked by anti virus...

Sorry for not accurately reading the instruction. The instruction is clear and it works now. The sync might be a little bit faster, but even without the hotfix performance is more than acceptable (in cached mode).

I have 1 last question: Do you also have an admin installer available? One that does not install in the user's profile (C:\Users\xxx\AppData\Local) but rather in the C:\Program Files folder? That would be really nice. ;-)

**Comment by phw198** [comment]
No, no admin installer (a lot of software doesn't do that anymore), but you could always manually deploy the portable version there and then unselect "make portable" so the config and logs are held in the user directory.

**Comment by Boechie** [comment]
> No, no admin installer (a lot of software doesn't do that anymore), but you could always manually deploy the portable version there and then unselect "make portable" so the config and logs are held in the user directory.

That's a good idea! I installed it that way now and it works.

I will close this issue as resolved.

Thanks again!
