### ISSUE TITLE
Software does suddenly not start (all portable versions) error [0x80040155] "A problem was encountered with your Office install. Please see the wiki for a solution"

### ISSUE THREAD

**Issue by jonashenrich** [phw198/OutlookGoogleCalendarSync#1930]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) [OGcalsync.log](https://github.com/user-attachments/files/16602529/OGcalsync.log)
**--> I cannot open the sofware anymore**

**OGCS Version**: v2.8.0, v2.10.0, 
v2.11.0
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
I use the portable version because I don`t have admin-rights on my computer. The portable version works without problems since years (always without admin-rights). Now the software does not start (all portable versions) error [0x80040155] "A problem was encountered with your Office install. Please see the wiki for a solution".  I tried to do all steps according to this guide: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered

In my case the key directory points to ..\Root\.. and the real directory is....\root\.. --> BUT I cannot change because of missing ADMIN-rights. The very last step also fails with this message: "Downloads>regtlibv12.exe "C:\Program Files\Microsoft Office\root\Office16\MSOUTL.OLB"
RegisterTypeLib of C:\Program Files\Microsoft Office\root\Office16\MSOUTL.OLB failed : 8002801c" 
I think this has also to do with missing rights?

**Steps to Reproduce the Issue**  
1. Run any OGCS.exe file (portable)

**Any other information**  
> I use Windows 11 and Office 365 --> The Windows switch from 10 to 11 was about 6 month ago and also after the switch OGCS worked "normal". Only since about 1 week this error occurs...

**Comment by r10thamus** [comment]
I don't get the same error code, but the same behavior exists for me in Windows 10 with Office 365.  No admin rights so I can't try the Office repair suggestion from #999 .  This happened prior to updating to the new beta as well as after the new beta 2.11.0.0.

**Comment by phw198** [comment]
As explained in the wiki, COM errors are nothing to do with OGCS or updating it (which is why it will affect every single version of OGCS once you have the problem) and everything to do with Microsoft being incapable of updating their own Office products properly.

If you don't have local admin permissions or the ability to repair Office, then you're out of options* 🙁 

\* Until the [new version of OGCS](#1888) that does not need the Outlook client at all

**Comment by r10thamus** [comment]
> As explained in the wiki, COM errors are nothing to do with OGCS or updating it (which is why it will affect every single version of OGCS once you have the problem) and everything to do with Microsoft being incapable of updating their own Office products properly.
> 
> If you don't have local admin permissions or the ability to repair Office, then you're out of options* 🙁
> 
> * Until the [new version of OGCS](#1888) that does not need the Outlook client at all

I'll eagerly await the new version.  In the meantime, is there anyway to figure out which COM add-in might be causing the problem?  I do have the ability to disable those but I don't want to start willy nilly.

**Comment by phw198** [comment]
It's not the third party apps or add-ins causing the problem, but Office itself. COM stands for Common Object Model, and is the mechanism by which third party tools can integrate with the Outlook client - but your Outlook install is no longer registered properly (due to a recent Office upgrade) for COM to work, which affects those tool(s) functionality.

**Comment by jonashenrich** [comment]
Thank yiu very much for your feedback! What do you think, when the new version will be available? In the meantime I try to request the manual registration at our IT-department...

**Comment by phw198** [comment]
Well it's already available under #1888, it just depends on when you want to get on board 🙂 You could use the latest development build to at least confirm you are able to connect OGCS to your Outlook online calendar, though.

It's probably going to be at least a couple of months before it's ready for an alpha release...

**Comment by jonashenrich** [comment]
Hi Paul,
I hope you are doing well. Are there any news regarding the version which does not require an outlook client? How would you assess the risk to get on board now?
Regards,Jonas

 

    Am Freitag, 16. August 2024 um 16:41:01 MESZ hat Paul Woolcock ***@***.***> Folgendes geschrieben:  
 
 


Well it's already available under #1888, it just depends on when you want to get on board 🙂 You could use the latest development build to at least confirm you are able to connect OGCS to your Outlook online calendar, though.

It's probably going to be at least a couple of months before it's ready for an alpha release...

**Comment by phw198** [comment]
I hope to get some time on this over the Christmas holiday period, so I'd probably hold off until the new year at least. I need to finish off recurring series synchronisation, but once that's done, the core product should mostly be there.
