### ISSUE TITLE
Bi-directional sync not doing what i expect

### ISSUE THREAD

**Issue by nezzek10** [phw198/OutlookGoogleCalendarSync#1931]
**Are you already using OGCS?** 2.11.0.0
Provide the version number.

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

I set ogcs to have a when of 7 days in the past and 60 days in the future however it is trying to delete 19 items with dates from 5/7/2024-10/4/2024. My goal is bi directional syn and since this a fresh install, shouldn't it sync first and i thought i read in the release notes that it would ask if a calendar should be created instead of delete. these are all items that should be there. i also have all day even for my daughters birthday it keeps trying to delete it from google.

Also recieving a forbidden=403 error for months which stopped me from using the application. i looked the error up and tried deleting the calendar entry on both outlook and google but the error still show up.

[OGcalsync.log](https://github.com/user-attachments/files/16607532/OGcalsync.log)

**Comment by phw198** [comment]
Sounds like you were on a previous version of OGCS, which was having problems two-way syncing, so I suspect the unwanted deletions are overhang from that. Follow through the [guidance here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) to resolve that.

Deletion outside your expected sync window look like they are all recurring appointments, so again, that [would be expected](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-cant-i-sync-more-than-1-year-past-or-future) if they are the master of the series - but again the above link may help stopping them being incorrectly deleted.
