### ISSUE TITLE
Impove Mutliple Google Accounts Descsription

### ISSUE THREAD

**Issue by PackElend** [phw198/OutlookGoogleCalendarSync#1934]
Hi,
that is only a short one.

In https://www.outlookgooglecalendarsync.com/guide/google you refer to https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Running-Multiple-Instances-of-OGCS. 
This is possible with a single instance if you create a new Google account and name it <your name>.ogcs@gmail.com, for example.
Then share all your calendars from different accounts that you want to have synchronized: https://support.google.com/calendar/answer/37082?hl=en#zippy=%2Cexample-how-to-share-your-calendar
![image](https://github.com/user-attachments/assets/84dd8df4-194c-4357-b3a4-e64307992d3a)

thx for this great piece of software

**Comment by phw198** [comment]
Thanks @PackElend, I've added a paragraph to the wiki page about sharing calendars 👍🏻
