### ISSUE TITLE
Error on initial startup v2.10.6.0

### ISSUE THREAD

**Issue by therealjoeblow** [phw198/OutlookGoogleCalendarSync#1935]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.6.0
**Edition**: Installed  
**Sync Direction**:  O->G 

**Bug Description**  

Every time OGCS initially starts after a reboot I get a popup error message the says:

Application unexpectedly terminated!

Retrieving the COM class factory for component with CLSID {0006f02a-0000-0000-c000-000000000046} failed doe to the following error: 800700c1 is not a valid Win32 application (Exception from HRESULT: 0x800700c1).

After I close this message, I am able to re-launch OGCS and it loads and works as expected.

**Steps to Reproduce the Issue**  
1. Reboot computer
1. Wait while everything loads, once OGCS loads the error appears.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Sounds like your registry entry for starting OGCS on system startup isn't pointing to the right place. Try just simply toggling the option off and on in the OGCS settings for "start on startup"?
