### ISSUE TITLE
Abrupt stop in smooth function with odd cluster of error messages.

### ISSUE THREAD

**Issue by Spacekat21** [phw198/OutlookGoogleCalendarSync#1936]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

OGCS Version: v2.11.0.0
Edition: Installed
Sync Direction O->G

Bug Description  
Sync does not occur, same error messages each time.
I have tried with reinstall of Beta, remove, reinstall of Alpha, result always same.

Steps to Reproduce the Issue
1. Initiate synch (same result after restart of computer with autostart or with manual initiation)

Any other information
[OGcalsync.log](https://github.com/user-attachments/files/16638936/OGcalsync.log)

**Comment by phw198** [comment]
Your log file shows you running v2.10.5 and a sync happening after your computer has apparently resumed from sleep/hibernate.

Could you please provide a logfile from v2.11.0 when you have started OGCS afresh and then the first occurrence of the problem?

**Comment by Spacekat21** [comment]
Well of course now it's functioning perfectly.  All you had to do was turn your attention to it.  That is some troubleshooting ability you have, there!
Seriously, I am very sorry to have troubled you.  I am so grateful for OGCS.
Kate

**Comment by phw198** [comment]
Always nice when that virtual "over the shoulder check" makes the problem disappear! Hopefully the issue doesn't return, but if it does just repost here...
