### ISSUE TITLE
Unable to retrieve calendars; poor UX when required Google scopes not authorised.

### ISSUE THREAD

**Issue by galexmay** [phw198/OutlookGoogleCalendarSync#1937]
I tried to install on my new computer. Despite your website talking about various versions, there only seems to be the option to download the 2.11.0-beta version so that is what I downloaded. In installed that version. I set up the Outlook folder and then connected my gmail account. I then got the following error messages. I tried to disconnect the account but when I went to reconnect it, it was already chosen and I immediately got the same error message. I tried uninstalling and reinstalling but nothing changed. In fact, the settings still appeared to be there despite the uninstall. What do I do now?

**OGCS Version**: 2.11.0-beta
**Edition**: Installed   
**Sync Direction**: didn't get that far

**Bug Description**  
see above

**Steps to Reproduce the Issue**  
see above

**Any other information**  
:paperclip: Attach your `OGcalsync.log` file. attached
[OGcalsync.log](https://github.com/user-attachments/files/16645011/OGcalsync.log)
![Clipboard_08-17-2024_02](https://github.com/user-attachments/assets/7b34ddfe-8a41-4ad7-9680-384cacbab3b5)
![Clipboard_08-17-2024_01](https://github.com/user-attachments/assets/0f09f3e4-7655-42d4-aa63-f9e6ac8076ab)

**Comment by phw198** [comment]
Oh dear, it looks like Google have changed the authentication process and the required permission is not checked by default 🙁 

You need to tick the box to give OGCS the required access:-
![image](https://github.com/user-attachments/assets/f80ecc14-8fb3-4dbd-90e7-6cc0fee85916)

However, I will now see if:-
* I can make OGCS handle it better when the required permissions are not present
* the permissions can be refined better to not require share and delete calendars (as OGCS doesn't need or do anything with that permission!)

**Comment by galexmay** [comment]
The big problem was that OGCS uninstall left a folder in the roaming folder
that remembered the failed Google authentication and therefore failed after
a reinstall. I chanced upon that folder and deleted it and then
re-authenticated and it worked.

**Comment by katie-hoemann** [comment]
I'm also running into this issue but cannot find the folder in Roaming that @galexmay mentions. Any memory of what the folder was called or thoughts about what else I might do?

**Comment by galexmay** [comment]
The folder was/is C:\Users\[username]\AppData\Roaming\Outlook Google
Calendar Sync, I think. You have to switch on the view of hidden items, I
think.

**Comment by Ammo999** [comment]
Ok, this worked for me. I disconnected the google account and restarted the app, then when it asked to reconnect, i got the checkbox option and then synced. seems to work now

**Comment by phw198** [comment]
> The big problem was that OGCS uninstall left a folder in the roaming folder that remembered the failed Google authentication and therefore failed after a reinstall. I chanced upon that folder and deleted it and then re-authenticated and it worked.

:package: OK, this [hotfix v2.11.0.2.zip](https://github.com/user-attachments/files/16788984/v2.11.0.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) should at least resolve the proper deletion of the token file, thus making it easier to then authorise the required permissions.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `9DC4E564` Exe = `A9E1AE8C`

Meanwhile, I'll work on improving behaviour with insufficient scopes...

**Comment by phw198** [comment]
:package: And now [hotfix v2.11.0.3.zip](https://github.com/user-attachments/files/16830418/v2.11.0.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) should behave better when insufficient permissions are granted to OGCS .
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `7BF01059` Exe = `55E763BA`

Please let me know how it goes!

**Comment by phw198** [comment]
:package: And now [hotfix v2.11.0.6.zip](https://github.com/user-attachments/files/16899434/v2.11.0.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) should behave better when insufficient permissions are granted to OGCS.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `45C85B51` Exe = `BB0DEF05`

Please let me know how it goes!

**Comment by phw198** [comment]
User outside of GitHub has confirmed success with hotfix.
