### ISSUE TITLE
outlook warning message - allow or block

### ISSUE THREAD

**Issue by sedlik** [phw198/OutlookGoogleCalendarSync#1938]
<img width="257" alt="outlook modal popup" src="https://github.com/user-attachments/assets/01b708a6-f109-4075-a7ed-94784cd68888">
**Are you already using OGCS?**
Provide the version number.
2.11.0.0
**Describe the question you have**
on booting up in win 11 i receive a warning from outlook - a program is trying to access email information in outlook, allow or deny.  it does not identify that program. could it be OGCS attempting to access the calendar.

**Comment by phw198** [comment]
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security
