### ISSUE TITLE
v3.0.0.1 alpha release crashes on open

### ISSUE THREAD

**Issue by dannysnell** [phw198/OutlookGoogleCalendarSync#1941]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v3.0.0.1
[OGcalsync.log](https://github.com/user-attachments/files/16719005/OGcalsync.log)

**Edition**: Portable  
**Sync Direction**: N/A

**Bug Description**  
After successfully extracting the alpha package, the app fails to start. It says "you are not connected" and immediately closes the app. I am unable to do anything else. Picture attached.

**Steps to Reproduce the Issue**  
1. Open .exe file
2. Click Yes on the "OGCS hotfix release troubleshooting" popup 
3. Application force closes

**Any other information**  
Files are attached:
[OGcalsync.log](https://github.com/user-attachments/files/16719011/OGcalsync.log)
![ogcs_start_error](https://github.com/user-attachments/assets/7868229b-e1ce-4a30-8f7e-9e2b55958381)
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
v3.0.0.1 isn't an alpha, but a development build and there have been several since then, so make sure you are running the latest one.

**Comment by dannysnell** [comment]
Sorry, dev build is what I meant to say. Because the new builds were all hotfixes, I didn't think they would change the build number, my mistake. I have gone through and applied all of the hotfixes, and the issue still occurs.

**Comment by phw198** [comment]
@dannysnell It seems that you still have the classic Outlook installed, is that correct? Does it still run if you start classic Outlook manually? I have a feeling it's not installed/uninstalled properly...

**Comment by dannysnell** [comment]
@phw198 I believe your prediction was correct. I was able to get a different license of Outlook pushed, and now I'm back running the older version, so I'm able to just use a stable build. Thanks for the help.
