### ISSUE TITLE
Everytime I sync with Google I get duplicate entries. Happens with every sync V2.11.0.0

### ISSUE THREAD

**Issue by cbonfante** [phw198/OutlookGoogleCalendarSync#1945]
Might be a simple fix or a tickbox, but everytime I sync I get duplicate entries in my google calendar. Super frustrating. Help please?

**Comment by phw198** [comment]
Without knowing your OGCS settings or what exactly is being duplicated, it's impossible to know what might be the issue. Usually simplest to provide your  `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) to assist with troubleshooting...

**Comment by cbonfante** [comment]
Thanks, Fixed. Just created a new profile.

Kind regards,

Charles Bonfante
