### ISSUE TITLE
First Time Setup - Google Error 403 Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by robyholmes** [phw198/OutlookGoogleCalendarSync#1948]
**OGCS** Version: v2.11.0.0
**Edition**: Installed
Sync Direction: N/A - Not yet setup

**Bug Description**  
Trying to set up OGCS for the first time. Have Outlook 365 installed with an Office 365 calendar. I try to connect to my Google Account (Non-GMail), but I get the following error message (Although it shows as connected). Hopefully I've not missed a step in setup but I don't think so. I can login to Google and view/edit my google calendar fine. I also see OGCS as a app on my google account.

```
Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.


Unable to get the list of Google calendars. The following error occurred:

Request had insufficient authentication scopes. [403=Forbidden]
```

**Steps to Reproduce the Issue**  
1. Go to Settings>Google
1. Click on Retrieve Calendar

**Log File**
[OGcalsync.log](https://github.com/user-attachments/files/16753339/OGcalsync.log)

**Comment by robyholmes** [comment]
Nevermind, removed it from Google Account and re-add it via OGCS. Worked correctly this time.

**Comment by phw198** [comment]
Duplicate of #1937
