### ISSUE TITLE
v2.11.0-beta opens splash screen but then disapears - cannot set up

### ISSUE THREAD

**Issue by bgibson123** [phw198/OutlookGoogleCalendarSync#1949]
When I double-click on the OGCS icon, I get the splash screen.  
<img width="376" alt="image" src="https://github.com/user-attachments/assets/3408efe2-7013-40b3-ae16-11a107712b4b">

Then, it goes away and I am unable to see the program running.  It's not hidden or minimized, but says it's open.

When I double-click the icon again, I get the multiple instances running error message, bt I cannot find the program running anywhere.

<img width="319" alt="image" src="https://github.com/user-attachments/assets/df5d22d2-45de-40c5-8d5c-bf83d59bd28d">

I've used OGCS for years and never experienced this before.  Please help!

**Comment by phw198** [comment]
:spiral_notepad: You'd need to provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) so we can see where it's getting stuck.

**Comment by bgibson123** [comment]
I cannot even get the program to open, just the splash screen.

I received this on an error message: "2024-08-27 09:02:56,168 INFO  .NET SystemEvents OutlookGoogleCalendarSync.NotificationTray [50] -  Detected system timezone change."

Does that help?  I am a basic user of this program, and had to reinstall on a new computer.  It worked well in the previous instance, but now is not working at all.

**Comment by bgibson123** [comment]
When I go to Task Manager, it shows that OGCS is open under "Background processes".

**Comment by phw198** [comment]
> I cannot even get the program to open, just the splash screen.

That means OGCS is running and there will be logs.

> I received this on an error message: "2024-08-27 09:02:56,168 INFO .NET SystemEvents OutlookGoogleCalendarSync.NotificationTray [50] - Detected system timezone change."

That's not an error, just an information log entry, so not helpful no - would need to see the previous day's log (or whenever you actually started OGCS) to see what it was doing when it stalled.

> When I go to Task Manager, it shows that OGCS is open under "Background processes".

Yes. because it is actually running - hence why you can't open another instance of OGCS. If you kill it through Task Manager, you should be able to start a new instance OK.
