### ISSUE TITLE
Message in Sync tab: "Corporate policy/anti-virus [...] may result in incorrect local start times due to DST"

### ISSUE THREAD

**Issue by netjeff** [phw198/OutlookGoogleCalendarSync#1950]
I'm using OGCS 2.11.0.0 with no problems. 

I recently noticed this message in the Sync tab at the beginning of the log:

> Corporate policy/anti-virus is restricting certain functionality. This may prevent proper detection of meeting organiser time zones, resulting in incorrect local start times due to DST

Is this something new to be concerned about?  No problems that I can see at the moment, but I'm wondering how paranoid I need to be in the future.

**Comment by phw198** [comment]
I guess it depends on how much you deal with people in other timezones that arrange meetings with you. If not, then you don't need to worry 🙂  If you do, then just keep an eye out for the meetings, to check if they have been synced with the correct start time...

**Comment by netjeff** [comment]
Thanks.  Most of the meetings are created by people 1 or 2 timezones away.  So far no problems, but I'll keep an eye out.
