### ISSUE TITLE
How can I stop this message of the new version? Upgrade fails and skip version is forgotten

### ISSUE THREAD

**Issue by AllanSoporte** [phw198/OutlookGoogleCalendarSync#1951]
already using OGCS
Version 2.10.0.0

*I tried to install it but send me an error and I tried to skip but every time I turn on my PC it appears again

![up](https://github.com/user-attachments/assets/da2adf4e-ab53-4873-b183-7c5fb4ab7c20)

![errorog](https://github.com/user-attachments/assets/9f919c21-c64a-4bb4-9e2a-97e0dcbddd39)

**Comment by repvik** [comment]
I have the same issue. OGCS is version 2.11.0, but it insists on wanting to upgrade. "Skip this version" does nothing.

**Comment by AllanSoporte** [comment]
> I have the same issue. OGCS is version 2.11.0, but it insists on wanting to upgrade. "Skip this version" does nothing.

I had to uninstall my current version and then install the 2.11.0 on my own

**Comment by phw198** [comment]
You stop it by upgrading, but the upgrade mechanism is a bit broken on v2.10.0 🙁 

Uninstall shouldn't be necessary, but when the upgrade fails just click "Yes" to downloading it manually from the website (which opens the website), close OGCS, download the setup file from the website and run it.

I've had a look and the skip version button needs to be stored by manually clicking the `Save` button on the settings screen - not ideal, so I've set it to automatically save in the next release.

@repvik Can you provide any evidence that you are indeed running v2.11.0? Your logfile would be handy.
