### ISSUE TITLE
O->G Updating Reminder on Google causes next sync to delete series.

### ISSUE THREAD

**Issue by griffithska** [phw198/OutlookGoogleCalendarSync#1956]
**OGCS Version**: v2.11.0.0
**Edition**: Installed 
**Sync Direction**: O->G

**Bug Description**  
If a synced series' reminder is updated on Google, the next sync causes the series to be deleted from Google. The following sync adds it back with no reminder. I believe this only occurs with recurring series, not individual meetings and appears to only happen if you update the Google reminder for "this and all following events"

**Steps to Reproduce the Issue**  
1. Create Outlook recurring meeting
2. Sync one way O->G with Reminders turned off
3. Update the reminder on the series in Google Calendar
4. Sync again, series will be deleted
5. Sync again, series will be re-added with no reminder

**Any other information**  
I do not want to sync reminders for all items, but I do want the ability to turn on reminders for certain events on Google so that I get notifications outside of my normal work hours but that does not seem to be working correctly.

Submitting Log via Google Form.

Thanks for your work on this tool, it has helped me with my calendar management immensely.

**Comment by phw198** [comment]
I think the reminder behaviour is actually a red-herring, and it's the "change for this and future occurrences" that's the problem.

This was also noted on https://github.com/phw198/OutlookGoogleCalendarSync/issues/1910#issuecomment-2262772990 - this has a hotfix posted, which I think might also resolve the problem you're reporting. Could you give that a try and let me know?

**Comment by griffithska** [comment]
I installed the hotfix but the behavior seems to be the same. If I add a reminder for "This and all following" they are deleted and re-added on the next two syncs. But if I add it for "All Events" that does not occur. I'll just try to remember to do "All Events" going forward as I don't see that being a problem. Thanks for the reply.

**Comment by phw198** [comment]
I've replicated your issue on v2.11.0 and then applied that hotfix and it resolved the problem for me.

Can you make sure OGCS shows you are running v2.10.6.1 on the `About` tab?
