### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by zozo01zozo** [phw198/OutlookGoogleCalendarSync#1957]
Bonjour les rappels paramètrés dans Outlook ne sont pas repris dans agenda de google résultat je n'ai pas les rappels sur mon téléphone android. 
Hello, the reminders set in Outlook are not included in Google calendar result I do not have the reminders on my Android phone.

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Make sure you have selected to sync reminders in the OGCS settings and then do a full sync.

**Comment by zozo01zozo** [comment]
Hello

I have selected to sync reminders and now it’s OK. Thanks

Cordialement
Fabrice CANTAGALLI
