### ISSUE TITLE
OGCS Screen goes blank after syncing

### ISSUE THREAD

**Issue by JonathanRhys** [phw198/OutlookGoogleCalendarSync#1958]
[OGcalsync.log](https://github.com/user-attachments/files/16836598/OGcalsync.log)
If I want to see what was synced I have to repeat the sync. otherwise the screen is just blank although it has synced. 

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by JonathanRhys** [comment]
[OGcalsync.log](https://github.com/user-attachments/files/16836621/OGcalsync.log)
As said, after syncing the screen often goes blank and I need to sync again to see what was synced.

**Comment by JonathanRhys** [comment]
Hope I have done this in the correct way

**Comment by JonathanRhys** [comment]
Sorry The issue is not closed.

**Comment by phw198** [comment]
How often do you get this blank screen? 

I have noticed it myself, but it is so infrequent and impossible to replicate on demand, so I've never been spent too much time trying to track the root cause...

**Comment by JonathanRhys** [comment]
I get this almost everytime I sync. so I need to resync again to see what was done . Thanks

**Comment by phw198** [comment]
Thanks for getting me to look at this a bit harder 🙂 

:package: Can you confirm if this is resolved with [hotfix v2.11.0.5.zip](https://github.com/user-attachments/files/16899206/v2.11.0.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `7AE788EE` Exe = `D775EC23`

Please let me know how it goes.

**Comment by JonathanRhys** [comment]
I have tried to do this following your instructions but Virus protect just will not let me and I cannot get passed it. Both Norton 360 and Windows. Sorry

**Comment by phw198** [comment]
There should always be an option to allow the file, regardless of false positives. However, I've now code signed the hotfix which _should_ help...

:package: [Hotfix v2.11.0.5.zip](https://github.com/user-attachments/files/16922144/v2.11.0.5.zip) (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by JonathanRhys** [comment]
Yippee Paul. It seems to have worked. I have run a sync three times and no blank page yet!. I will wait a day or two before closing this just in case.

**Comment by JonathanRhys** [comment]
I have done a few syncs and all working perfectly. No blank screens. Many thanks Paul
