### ISSUE TITLE
Synchronization Outlook -> google does not work

### ISSUE THREAD

**Issue by ftodaf** [phw198/OutlookGoogleCalendarSync#1960]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.11.0.0  
**Edition**: Installed
**Sync Direction**:  O<->G 

**Bug Description**  
Synchronization from Google to outlook works, but the other way round from outlook to google doesn't work

**Steps to Reproduce the Issue**  
1. Click on "Sync" button
2. Wait until sync is finished
3. Check Google calendar

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/user-attachments/files/16848787/OGcalsync.log)

**Comment by phw198** [comment]
Not sure what you mean. Your log file shows it comparing 30 Outlook items with Google and none of them have any changes, so nothing to be synced.

What are you expecting to see?

**Comment by ftodaf** [comment]
After a restart, it worked. Issue can be closed.
