### ISSUE TITLE
Duplicate calendar entries with version 2.11.0.0

### ISSUE THREAD

**Issue by Ferris321** [phw198/OutlookGoogleCalendarSync#1961]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.11.0.0  
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
Every new sync run of OGCS creates another duplicate of my Outlook calendar entries into my Google calendar. I only sync O -> G.
For all past OGCS versions I did set "Merge with existing entries" = true. But now I set for my actual version 2.11.0.0 "Merge with existing entries" = false.
I was hoping this setting could solve my issue, but still OGCS creates the duplicate calendar entries.

**Any other information**  
[OGcalsync.log](https://github.com/user-attachments/files/16887428/OGcalsync.log)

**Comment by ghost** [comment]
Having the same exact issue

**Comment by phw198** [comment]
@Ferris321 Looks like you have set OGCS to _include_ no Google colours - so they are pretty much all being excluded, and therefore "duplicated" when synced.

**Comment by Ferris321** [comment]
Problem is solved now, thanks for your hint @phw198 

Detailed Description of solution for everyone: You need to go to Settings --> Google --> Sync Configuration --> Filter colours --> include --> then select all Google colors to be included
