### ISSUE TITLE
Not able to set google account to be sync

### ISSUE THREAD

**Issue by Kovik-Turnov** [phw198/OutlookGoogleCalendarSync#1964]
[OGcalsync.log](https://github.com/user-attachments/files/16930470/OGcalsync.log)

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by Kovik-Turnov** [comment]
Issue with settting the Google account to be synced.
When selected "Retrieve the  --> a bug window appears telling " Failed to retrieve Google calndars. Please check the output on the sync tab..." If clicking YES, another error pups up (see it per below) and OGCS crashes. Reinstalled several times

```
"Informace o vyvolání ladění JIT najdete na konci této zprávy,
nikoli v tomto dialogovém okně.

************** Text výjimky **************
System.ApplicationException: Google handshake failed.
   v OutlookGoogleCalendarSync.Google.Calendar.get_Instance() v C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Google\GoogleCalendar.cs:řádek 39
   v OutlookGoogleCalendarSync.Forms.Main.cbGoogleCalendars_BuildList() v C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:řádek 1578
   v OutlookGoogleCalendarSync.Forms.Main.GetMyGoogleCalendars_Click(Object sender, EventArgs e) v C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:řádek 1570
   v System.Windows.Forms.Control.OnClick(EventArgs e)
   v System.Windows.Forms.Button.OnClick(EventArgs e)
   v System.Windows.Forms.Button.WndProc(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   v System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Načtená sestavení **************
mscorlib
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9261.0 built by: NET481REL1LAST_C
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookGoogleCalendarSync
    Verze sestavení: 2.11.8982.43122
    Verze Win32: 2.11.0.0
    Základ kódu (CodeBase): file:///C:/Users/tomas/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/OutlookGoogleCalendarSync.exe
----------------------------------------
System.Windows.Forms
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9251.0 built by: NET481REL1LAST_C
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.9261.0 built by: NET481REL1LAST_C
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Verze sestavení: 4.0.0.0"
```

**Comment by phw198** [comment]
Were you taken to https://www.outlookgooglecalendarsync.com/blog/2024/09/01/2-11-0-beta-google-permissions.html when you downloaded the install file from the website? And if so, did you read it?

Duplicate #1937
