### ISSUE TITLE
Google entries being duplicated into Outlook [OGCS 2.11.0.0, Windows 11, Outlook Pro Plus 2016, version 2408]

### ISSUE THREAD

**Issue by TRIALtri** [phw198/OutlookGoogleCalendarSync#1965]
**OGCS Version**: v2.11.0.0
**Edition**: Installed   
**Sync Direction**:  O<->G

**Bug Description**  
OGCS is duplicating entries into my Outlook calendar. When syncing Outlook to Google stage it identifies the items for deletion and asks me to confirm I do NOT confirm because I want to keep them. When it syncs Goole to Outlook it creates new entries, duplicationg the entries already there (and their reminders) This has been happening for a few days and I now have 6 copies of these events in Outlook, but just 1 afaics in Google Calendar. I cannot remember if the events were originally created in Outlook or Google.

**Steps to Reproduce the Issue**  
1. I'm just running a "normal" bi-directional sync, can click on the Sync Now button, or when a scheduled sync runs.

**Any other information**  
This was happening pre 2.11.0.0, updating to 2.11.0.0 didn't fix it.
I have tried the instructions at "Fixing a Stubborn Unwanted Deletion ......" which did not help.
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/user-attachments/files/16930580/OGcalsync.log)

**Comment by TRIALtri** [comment]
This behaviour was happening before I upgraded to 2.11.0.0. I upgraded as per the issue logging requirements and the issue still occurs.

**Comment by phw198** [comment]
> I have tried the instructions at "Fixing a Stubborn Unwanted Deletion ......" which did not help.

Please explain what you did and why it did not help - I don't see any evidence in your logs of attempting a full 1-way sync O->G.

I would expect the items currently being requested for deletion in Google to be "reclaimed" and then deletions no longer occur...

**Comment by TRIALtri** [comment]
Hi. I came back to this today. Presuming that the previous log file didn't show me running the full 1-say sync because I didn't have debug on at that time, only switched it on to record a log to submit here, above.
Anyway today I ran full sync 6 times and it alternated between "Reclaiming Outlook entries" with a clean run and then NOT reclaiming  Outlook entries but instead wanting to "Deleting Outlook entries" . But on none of the 6 syncs did it want to create further entries.
A bit weird but I decided to go into Outlook List View and delete the existing dupes myself.

And, all is now well, no more duplicates being created.

1 thing I noticed it that I had 2 separate events on the same day with similar but different subjects, which OGsync had NOT tried to sync across applications. 1 was "Luc", the other was "Luc?". Random I know but could this have caused the issue?

**Comment by TRIALtri** [comment]
And today .....  <still running 2.11.0.0, and have restarted Windows to eliminate anything "stuck">
Sync is now creating duplicate Google entries. So I now have 1 Outlook occurrence and 6 Google occurrences of 3 calendar entries from May. I have sync set to look 123 days into the past, i.e. back to 1 June so these dates are beyond the requested sync window. Re-attaching current log file
[OGcalsync.log](https://github.com/user-attachments/files/17228218/OGcalsync.log)
[OGcalsync.log](https://github.com/user-attachments/files/17228222/OGcalsync.log)

**Comment by phw198** [comment]
Logging is configured off, so there's nothing useful captured in them. Please make sure you don't have any exclusions configured in OGCS for Google for these items that are being duplicated.

**Comment by TRIALtri** [comment]
Thank you. Debug switched back on, ran a few syncs (displaying alternately different behaviour), ran the 1-way sync and then another couple of 2-ways, again still showing the alternating behaviour, creating some duplicates in Google (for last May which should be out of scope for the sync) and one in both Google and Outlook for next April.
I don't understand your "don't have any exclusions configured .." comment. There are no Filter Colours excluded but I can see that Declined Invitations and Goal Events are excluded; I have no idea what they are so I switched them off and it made no difference when I ran another couple of syncs (further log file attached, ignore the first one), further duplicates were created.

New log file attached
[OGcalsync.log](https://github.com/user-attachments/files/17269759/OGcalsync.log)
[OGcalsync.log](https://github.com/user-attachments/files/17269795/OGcalsync.log)

**Comment by phw198** [comment]
Pretty sure this is a Outlook date time format issue.

I can see your full sync for O->G:
```
2024-10-06 16:30:50,371 DEBUG 1  OutlookGoogleCalendarSync.Console [246] -  Full sync started at 06/10/2024 16:30:50
2024-10-06 16:30:50,371 DEBUG 1  OutlookGoogleCalendarSync.Console [246] -  Syncing from 05/06/2024 to 25/04/2025
2024-10-06 16:30:50,371 DEBUG 1  OutlookGoogleCalendarSync.Console [246] -  Outlook → Google
```
but then it is creating 4 items in Google that are before 5-Jun-2024:
```
2024-10-06 16:31:02,774 INFO  20 OutlookGoogleCalendarSync.Console [366] -  Creating 4 Google calendar entries
2024-10-06 16:31:02,789 DEBUG 20 OutlookGoogleCalendarSync.Google.Calendar [555] -  Processing >> 09/05/2024 13:00 => "VW viewing "
....
23-May
26-May
27-May
```
That's probably created duplicates in Google? Then when you turn back on two-way sync it wants to delete those equivalent items in Outlook and you select "No".

Take a look the [wiki entry here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) and play with different date time formats until you find one that works - your format is currently `yyyy-MM-dd hh:mm tt` and often the `tt` part throws Outlook off.

**Comment by wlau-wlau** [comment]
It's a real issue that just started to happen in the last few days.  I have a ton of duplicates on Google (not in Outlook) - one set per sync event. When I look at the status log, I think the issue is when it queries Google to see how many calendar events is on Google, it seem to return 0, so OGCS try to create new entries from the Outlook calendar causing duplicates.  It's a nightmare as I have sooo many duplicates.  Since I haven't found a bulk delete function on Google Calendar, it's a mess to clean up.  As an emergency measure, I had to disable auto-sync and push-sync.  It's creating a mess on Google Calendar.

**Comment by TRIALtri** [comment]
I have changed the Outlook setting for Date Format from Generic to Default, run 3 syncs and it is running like a well-oiled tool. Thank you.

**Comment by wlau-wlau** [comment]
It just started happening for me and I already have the Date Format set to Default g.    It was working fine for a while then suddenly the last few days, duplicates heaven.  I have 2-way enabled, and duplicates are in Google, not Outlook.   I tried to select the accept on the delete prompt but it ended up deleting the only entry in Outlook.  I then change 2-way to Outlook->Google, the same issue.

I think we need to add a bulk delete function in this, so we can clean up the mess on Google Calendar, it's way too tedious to clean up right now.

**Comment by phw198** [comment]
@wlau-wlau You're cross-posting with #1989 and @TRIALtri has already said that he is not excluding any Google colours etc.

@TRIALtri Perfect, glad the date setting fixed it 🙂
