### ISSUE TITLE
Push Outlook changes immediately not working - is this an issue with autosync?

### ISSUE THREAD

**Issue by Veggie352** [phw198/OutlookGoogleCalendarSync#1969]
**Are you already using OGCS?**
Provide the version number.: 2.11.0.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.
Just reinstalled OGCS and it seems that autosync is not working. If I create an appointment in my Outlook calendar, I am not getting the appointment synchronising into Google calendar. If I manually run a sync it works, but automatic does not seem to be running. Any ideas please?

**Comment by phw198** [comment]
You have turned on the "Push Outlook changes immediately" and waited for at least 2 minutes after making a change in Outlook? If so, how are you creating the appointment in Outlook? Try to avoid copy and paste as this is known to be problematic...

**Comment by Veggie352** [comment]
Thank you, I changed nothing and after a few days it started to work correctly. All good and thank you for responding.
