### ISSUE TITLE
What will trigger Sending out emails to attendee when deleting a event?

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#197]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/661547" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/LReyes66" target="_blank">LReyes66</a></strong> wrote at 2017-02-24 01:43:</p><div class="markDownOutput ">So im basically only trying to merge my outlook calendar to my google account just so Google Home can tell me my agenda for the day... only reason!
<br>
<br>
I plan on disabling the outlook calendar from showing up on my Phone/Ipad so there isnt a duplicate entry of events for those outlook events that are syncing over to my google account.
<br>
<br>
With that, I want to keep the attendee so if i ever needed to know whos attending, I can quickly pull it up on my phone/ipad. I created a meeting event on outlook and invitedmy 2ndary google email only to test it out. Keep in mind the main google account wasnt
 invited and was just getting the event synced to it via outlook. <br>
<br>
Well I cancelled the event that was on the main google account calendar and it ended up sending cancellation emails to both participants (outlook email and 2ndary email) even though the main google account wasnt part of the event.
<br>
<br>
<strong>What exactly is triggering the cancellation emails even from the google account that wasnt even invited?</strong><br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/phw198" target="_blank">phw198</a></strong> wrote at 2017-02-26 23:11:</p><div class="markDownOutput ">How did you delete the Google event? Through Google Home or the mobile app? I know the latter will trigger notification emails with no option to stop it(!) - perhaps Google Home is the same?<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/mmascari" target="_blank">mmascari</a></strong> wrote at 2017-02-27 13:09:</p><div class="markDownOutput ">With more and more questions and concerns around how Google treats actual attendees, it would be nice to have Outlook attendees added to the Notes on the Google Calendar (as an option) instead of simply not including them at all. Obviously not as nice
 an integration as actual attendees, but also avoids all the complications that integration creates. Right now, the only option is to not sync attendees at all, which is no integration and no information, the worst of both.
<br>
<br>
At least for one way Outlook to Google Sync.<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/phw198" target="_blank">phw198</a></strong> wrote at 2017-04-01 23:13:</p><div class="markDownOutput ">That is how a very early version of this tool worked. The code was pretty horrid, but I could maybe dig it out and see if it's worth bringing it back as an additional feature....<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/mmascari" target="_blank">mmascari</a></strong> wrote at 2017-04-02 01:35:</p><div class="markDownOutput ">Something with a very limited scenario should be easier. The big use case is for one way sync from outlook to google where it's very undesirable to sync attendees as actual attendees.
<br>
<br>
If the option is on, tack all the attendees onto the end of the description in alphabetic order before comparing. That way any change is picked up and the specific sort order means it's not subject to random updates because Outlook decides to return the list
 differently. <br>
<br>
First time it's on, every entry would get an update. Or if turned off. <br>
</div></div>

**Comment by wesarnquist** [comment]
Hi guys- I'm new here so I apologize if I'm putting this comment in the wrong place.
I also really would like to see attendees synced but have left it off for fear of my personal Google account sending out updates to my work contacts.  I also would like to see the attendees appear in Google Calendar so that I can turn off Outlook notifications.

Would it be possible to append some erroneous text to the ends of the e-mail addresses of attendees?  That way, if Google tries to send out notifications they will fail and not be delivered, but we would still be able to identify the attendees, and simply strip off the added text to send a message if desired.

For example:
John.Doe@mycompanyname.net
-->
John.Doe@mycompanyname.net.OGCS

Since the OGCS domain doesn't exist an e-mail would never actually be delivered.  If this causes delivery failure messages to be sent to Gmail, then a rule could be set up to auto-archive messages that reference ".OGCS" domains.

Is this even possible?  Thanks for all the hard work.  The tool has been tremendously helpful!

**Comment by phw198** [comment]
:package: This has now been implemented in [Development Build v2.6.1.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1273306/v2.6.1.4.zip) - see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) in the same way as a hotfix.

:warning: Make sure you apply this over the top of v2.6.1 by upgrading to the latest alpha.

Feedback welcome!

**Comment by phw198** [comment]
:package: Latest [development build v2.6.1.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1290941/v2.6.1.8.zip).

**Comment by JeffKandt** [comment]
I turned off syncing Attendees some months ago after an embarrassing incident where I and my small team at work all received an "updated invitation" (not a cancelation) in Outlook from my personal Google account, duplicating the event already on their calendar.  It just happened again today, only this time it was my entire department who got the duplicate event. I'm not sure what triggered this -- I think I had just dismissed a meeting notification on my Mac at home?

It looks to me like unchecking Attendees only affects new events that are sync'd to Google going forward, while any events sync'd previously, such as long-standing recurring meetings, retain their Attendee list so continue to be ticking time-bombs for this kind of thing.

It would have been really nice if OGCS had updated all of my previous events to remove Attendees when I told it I no longer wanted Attendees be sync'd.

In the context of this fix, I hope that OGCS will update all existing events to add the bogus email suffix, not just new sync'd events going forward.

I'm going to delete and recreate my Google calendar to force all of the events to come in fresh, hopefully without Attendees. I'm really hoping that this way I can avoid sending emails to all the attendees of all my meetings, but I'm pretty paranoid at this point...

**Comment by phw198** [comment]
Paranoia is understandable - it's pretty frustrating all round! 

You're right, OGCS only syncs change, so attendees aren't synced retrospectively when the option to sync them or not is changed within OGCS. However, you can force a sync of everything by pressing the `shift key` when clicking the `Sync` button. This should force the cloaking option to replicate through to Google.

**Comment by phw198** [comment]
v2.6.2 now also has a little :information_source: icon in the `What` section of the `Settings` tab, which will explain that configuration changes will only affect newly synced items, and to force a sync of everything Shift-Sync.

I think this release finally puts to bed the issue, so I'm closing it out.
