### ISSUE TITLE
Object reference not set to an instance upon starting the app

### ISSUE THREAD

**Issue by eventsourcer** [phw198/OutlookGoogleCalendarSync#1970]
After playing with the old and new versions simultaneously, none of them are launching with "Object reference....".
Anyone knows where to find stuff to clear and have a fresh env?

Not even uninstalls or restarts are helping.

Appreciate folks went through the headache and became familiar with it.

**Comment by eventsourcer** [comment]
I cloned to see what's not being set and this is what I get.
Not sure why this proxy instance not getting set.

<img width="909" alt="null" src="https://github.com/user-attachments/assets/1048d0a9-7727-40ac-92b6-73efe0ffeda9">

**Comment by phw198** [comment]
I'm pretty sure you'll find you have a blank `<Proxy />` section in your `settings.xml` file somehow. Either remove that element so it reinitialises it, or rename the settings file out of the way entirely to start as though from a new install.

https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#how-do-i-wipereset-the-configuration

**Comment by eventsourcer** [comment]
> I'm pretty sure you'll find you have a blank `<Proxy />` section in your `settings.xml` file somehow. Either remove that element so it reinitialises it, or rename the settings file out of the way entirely to start as though from a new install.
> 
> https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#how-do-i-wipereset-the-configuration

thanks a lot @phw198 it's back now.
