### ISSUE TITLE
Upgrading fails for 2.11.0.0 and OGSC_Setup.exe quarantined by McAffee

### ISSUE THREAD

**Issue by sgoschin** [phw198/OutlookGoogleCalendarSync#1973]
When I start the check for update function and select update. The automatic update fails with the following log entries.

[OGcalsync.log](https://github.com/user-attachments/files/17029504/OGcalsync.log)

<img width="626" alt="package-folder-content" src="https://github.com/user-attachments/assets/0b1f7070-0ed8-4c73-af6b-4ee54cf78e17">

I downloaded the latest installer version but it was immediately quarantined by my anti virus which was a bit concerning.
<img width="1150" alt="mc-affee-virus-detection" src="https://github.com/user-attachments/assets/39c9884a-3f74-4f7b-970a-169295d5a920">

I then downloaded the portable version and installed it in my AppData. Now it shows I'm using the latest version but it still says that there is an update available. If I try to manually upgrade to the latest version is there a Windows Registry entry I have to change to let the application know it is on the latest version?

PS: I also tried building the installer from scratch to see if that helps but there seems to be an issue. The nuget build is missing files. Is there a step that needs to be done prior of executing the [bat file](https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/nuget-build.bat)?

**Comment by phw198** [comment]
Unfortunately the upgrade mechanism got broken and was fixed from about v2.10.3 - so manual upgrade is the only option before then.

Yes, anti-virus software is dumb. It doesn't like how the install file is a shim that installs another executable - but that's how a lot of software installs these days, including Microsoft Teams! You can help by [reporting false positives](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#anti-virus-false-positives).

The repeated upgrade alerts have fixes developed - for the portable version, I think I've just fixed that for you, if you could confirm?

To be honest, I wouldn't expect others to build the Squirrel nuget files as that is all related to distributing the install; as long as you can build the software executable that should be enough...

**Comment by bdurrer** [comment]
FYI, GData reports it (the installer) as `Win32.Trojan-Stealer.PSWSteal.SX7C3F`
