### ISSUE TITLE
Doesn't retrieve any Outlook calendars when clicking Retrieve Calendars [v3]

### ISSUE THREAD

**Issue by eventsourcer** [phw198/OutlookGoogleCalendarSync#1977]
Latest version with patch v3.0.0.6

Hey Paul, I am using latest hotfix aiming to sync from Google to Outlook, when retrieving Outlook cals to select one, it doesn't seem to have access to any.

I even checked the app access to Outlook it's listed there, although not like Google being able to literally give calendar access to OGCS. shouldn't the OAuth for Outlook be similar to Google? selecting cal access during consent?

Not sure what I am missing from latest development and discussions

![image](https://github.com/user-attachments/assets/c7db5a72-fc1f-471e-9ed9-666db52a2e0e)

**Comment by eventsourcer** [comment]
One more question, using Office Outlook Client method to sync Office Outlook (which works fine), shouldn't I see synced calendars from new Outlook opened with the same email used for Office Outlook?

I see them from Office Outlook but not new Outlook, using same email.

**Comment by phw198** [comment]
Are you able to provide your log file from when you click on the "Retrieve calendars" for Outlook?

> One more question, using Office Outlook Client method to sync Office Outlook (which works fine), shouldn't I see synced calendars from new Outlook opened with the same email used for Office Outlook?
> 
> I see them from Office Outlook but not new Outlook, using same email.

I'm not quite understanding - are you saying regardless of OGCS, you cannot see the calendars in classic Outlook but you _can_ see them in New Outlook?

**Comment by eventsourcer** [comment]
Sure. looks like a login problem for Outlook.

![image](https://github.com/user-attachments/assets/e38ef295-6453-44ac-8cff-3af35222ce0f)

[OGcalsync.log](https://github.com/user-attachments/files/17269099/OGcalsync.log)

**Comment by eventsourcer** [comment]
> I'm not quite understanding - are you saying regardless of OGCS, you cannot see the calendars in classic Outlook but you _can_ see them in New Outlook?

No I mean syncing Google with Office Outlook which works fine and calendars are copied from Google to Office Outlook, but If I open new Outlook app with same email I used with working Office Outlook, shouldn't I see previously synced calendars?

as long as calendars are copied, regardless of weather the Outlook is legacy or new, If I use the same email I should have same calendars if I am not wrong.

**Comment by eventsourcer** [comment]
@phw198 to remind you of this, if you may check when possible.
thank you

**Comment by phw198** [comment]
This seems to be a bug on Microsoft's side, or at least a departure from their documentation and previous behaviour!

v3 has always requested scope `Calendars.ReadWrite.Shared` which [documentation says](https://learn.microsoft.com/en-us/graph/permissions-reference#calendarsreadwriteshared):-
> Read and write user and shared calendars. Allows the app to create, read, update and delete events in all calendars in the organization user has permissions to access. This includes delegate and shared calendars.

This should be over and above just `Calendars.ReadWrite`:-
> Have full access to user calendars. Allows the app to create, read, update, and delete events in user calendars.

As noted, the first scope is actually not reporting any associated permissions when it's being granted, which just seems wrong:-
![image](https://github.com/user-attachments/assets/53bd37df-b9b6-4ab9-b79e-9aca74eeca61)

Although if you are attempting to connect to a protect work account, that screen still knows the scopes properly:-
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/3eae2b4d-649b-4e2c-ab0d-1a0b3143bcfd)

Even after granting access, OGCS then fails with "Access is denied. Check credentials and try again.". So seems like a clear bug to me, but the work around is to request the less, non-shared calendar scope. I'll get out a workaround hotfix in the next few days hopefully...

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v3.0.0.7.zip](https://github.com/user-attachments/files/17530935/v3.0.0.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `13852920` Exe = `62C800AD`

Please let me know how it goes.

**Comment by eventsourcer** [comment]
> 📦 This should now be resolved with [hotfix v3.0.0.7.zip](https://github.com/user-attachments/files/17530935/v3.0.0.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).       [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `13852920` Exe = `62C800AD`
> 
> Please let me know how it goes.

thanks a lot @phw198 it works now.
