### ISSUE TITLE
Multiple deletions

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#198]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/662377" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/pablohf68" target="_blank">pablohf68</a></strong> wrote at 2017-04-04 02:14:</p><div class="markDownOutput ">Hello, for some synchronization problem, all my appointments were deleted, in Gmail, Outlook and in my smart phone (Samsung S7).
<br>
<br>
There is a way to recover them? <br>
<br>
I'm desperate, I had everything there. <br>
<br>
Thanks. <br>
<br>
Pablo.<br>
</div></div>

**Comment by ironbullx** [comment]
Was there any answer to this. I am experiencing the same thing.

**Comment by phw198** [comment]
For Google, go to the drop-down arrow next to the appropriate calendar and click "Bin" - see if they are in there for recovery.

For Outlook, they should be your Deleted Items folder.

A little intrigued how this happened - the default settings in OGCS are to merge and prompt on deletions. It should also alert if every item is going to be deleted in the target calendar...
