### ISSUE TITLE
Update from 2.10.0 fails

### ISSUE THREAD

**Issue by RayGX** [phw198/OutlookGoogleCalendarSync#1982]
**OGCS Version**: v2.10.0.0
**Edition**: Installed 
**Sync Direction**: NA

**Bug Description**  
Continually get "update failed" message whenever attempting to update from 2.10 to 2.11.  Both upgrading from within the app and downloading/installing the update fails.

**Steps to Reproduce the Issue**  
1. View app
2. Select About tab
3. Click "Check for Update" button

Update fails on my windows 11 (up-to-date) and Office/Outlook 2019 system.

**Comment by phw198** [comment]
Both #1837 and #1861 provided improvement to the upgrade process since v2.10.0 - to get upgraded from that version you need to do it manually by downloading the setup file from the website.
