### ISSUE TITLE
Cannot retrieve google calendar

### ISSUE THREAD

**Issue by mister-gem** [phw198/OutlookGoogleCalendarSync#1984]
**OGCS Version**: v2.11.0.0  
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
I added google account and attempted to retrieve, it shows connected account, but gives error:

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.

Unable to get the list of Google calendars. The following error occurred:

Request had insufficient authentication scopes. [403=Forbidden]

Unable to get the list of Google calendars. The following error occurred:

Request had insufficient authentication scopes. [403=Forbidden]

Unable to get the list of Google calendars. The following error occurred:

Request had insufficient authentication scopes. [403=Forbidden]

**Steps to Reproduce the Issue**  
1. Add google account
1. Click on retrieve calendars

[OGcalsync.log](https://github.com/user-attachments/files/17213201/OGcalsync.log)

I have tried disconnecting the google account and starting over.  Even uninstalled the app and tried again, but the google account was already there without logging in again.  Not sure how to clear it out and start fresh.

**Comment by slimninja** [comment]
Same here, tried reinstalling and have the same error and then a crash

**Comment by HiroyukiKato7** [comment]
I am having the same issue on a new Win 11 PC.  I'm also using v2.11.0.0.
Strangely, OGCS is running fine on my older Win 11 PC which also runs v2.11.0.0.

**Comment by marjonandres** [comment]
I do have the same isue. I might have forgotten to tick:
![Screenshot 2024-10-02 161921](https://github.com/user-attachments/assets/c355ce79-a88f-4951-93b8-159b1b8fc35d)

But what can I do now?

maybe delete following file?
Google.Apis.Auth.OAuth2.Responses.TokenResponse-user

Where can i find it how to access?

So many questions?

**Comment by mister-gem** [comment]
> I do have the same isue. I might have forgotten to tick: ![Screenshot 2024-10-02 161921](https://private-user-images.githubusercontent.com/183624364/372900181-c355ce79-a88f-4951-93b8-159b1b8fc35d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODcyMjcsIm5iZiI6MTcyNzg4NjkyNywicGF0aCI6Ii8xODM2MjQzNjQvMzcyOTAwMTgxLWMzNTVjZTc5LWE4OGYtNDk1MS05M2I4LTE1OWIxYjhmYzM1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNjM1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjI0YTk0ZWJlNTllYTY5MTA2Yzc2Mjc4ZDIzYmY0MGNhNTU2NTViNmFkOTVmYjFmNGI2MmY4YWZkMGY5MzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vJqNLAjZEiEzbf5SzbVXgbleb6X1Npk-xPURMdVD9Mo)
> 
> But what can I do now?
> 
> maybe delete following file? Google.Apis.Auth.OAuth2.Responses.TokenResponse-user
> 
> Where can i find it how to access?
> 
> So many questions?

I think I may have also forgotten, but can't seem to detach the gmail to get that screen to populate again.

**Comment by mister-gem** [comment]
I deleted everything in the folder where the log file is stored and I was able to reconnect the google account and select the option to see/edit/share

On the help screen at the bottom under trouble shooting, click the log file and it will open the folder in windows.  Delete all that and it should work.


![image](https://github.com/user-attachments/assets/7681b63a-6449-4521-83dd-c0e7223787d9)

**Comment by HiroyukiKato7** [comment]
That solved the problem!  Thank you!

**Comment by marjonandres** [comment]
Thank you, but in which folder I can find the log files?

**Comment by HiroyukiKato7** [comment]
As in mister-gem's comment, at the bottom of the help tab, you can find a link to "OGcalsync.log file"

**Comment by marjonandres** [comment]
Thank you so much, Finally I found it and worked!

**Comment by phw198** [comment]
Or just apply the [hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1937#issuecomment-2332495706) linked to from [the blog](https://www.outlookgooglecalendarsync.com/blog/2024/09/01/2-11-0-beta-google-permissions.html).
