### ISSUE TITLE
Import as private evens

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#199]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/655922" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/ttocsic" target="_blank">ttocsic</a></strong> wrote at 2016-06-27 18:41:</p><div class="markDownOutput ">I'm running outlook 2007 in my office (business calendar) and i want to import my google calendar (personal calendar). The issue I'm having is that my office uses the &quot;shared calendar&quot; feature so employees can see others' availability. I need
 to ensure that any google events are imported and automatically set as private in outlook otherwise everyone will know when I'm going to the doctor, my kid's birthdays and the sick concerts I attend.
<br>
<br>
The home page lists that functionality as a feature but i do not see that setting anywhere in the application.
<br>
<br>
Is this possible?<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/dwtaylornz" target="_blank">dwtaylornz</a></strong> wrote at 2017-04-06 21:54:</p><div class="markDownOutput ">i agree this would be a great feature. <br>
i would also use in similar fashion. <br>
</div></div>

**Comment by phw198** [comment]
Just to confirm, it's not an option to create a new "Google" calendar in Outlook and changing the sharing permissions on it to just Free/Busy (or removing sharing altogether)? Or do you want the free/busy information from Google to be available in your default Outlook calendar to help with booking meetings?

**Comment by visidor** [comment]
I would like this feature too... 
I kind of solved this by sharing my (personal) google calendar privately (using the option to only show availability) with another dummy google account and sharing this dummy google account with my work Outlook using OGCS.
But I would much prefer to go the direct route and have an option to share all entries privately because sometimes looking at my Outlook calendar I don't even know that the entries are...

**Comment by phw198** [comment]
@visidor As per my previous post, why are you syncing your calendars in the first place? So your work colleagues can see your availability, or so you don't have to check your commitments in more than 1 place (Outlook + Google)?

Linking issue #2.

**Comment by visidor** [comment]
So my work colleagues can see my availability.
It's required where I work, otherwise they assume I am available.

**Comment by phw198** [comment]
OK, cool. I've started work on this now and will track progress under issue #2 if you would like to subscribe to that issue for updates.
