### ISSUE TITLE
OGCS doesn't delete the canceled event of outlook into google calendar

### ISSUE THREAD

**Issue by mpegard-inrae** [phw198/OutlookGoogleCalendarSync#1991]
Hi,

I have been using OGCS for a couple of months and have noticed that while I can sync the creation and modification of events, deletions are not being synchronized. If I delete an event in my Outlook calendar, it remains in my Google calendar. The tool indicates that there are no calendar entries to be deleted.

Do you have any idea why this might be happening?

Regards,
Marie

**Comment by phw198** [comment]
Not really without your logfile. You may well have "Disable deletions" still checked though.

**Comment by mpegard-inrae** [comment]
Thanks for the reply, it was the disable delete option that was 'click'. 
I don't know why it was click but anyway it's solved.
