### ISSUE TITLE
Warning about Outlook security settings

### ISSUE THREAD

**Issue by Samoreen** [phw198/OutlookGoogleCalendarSync#1994]
**Are you already using OGCS?**
2.11.0.0

**Describe the question you have**
OGCS is working fine on my Windows 11 laptop running the latest version of Office 365. Just, I'm regularly getting a warning from OGCS telling me that my "outlook security settings may not be optimal". No further details are given. Not sure where I should look in Outlook.

Thanks in advance.

Patrick

**Comment by Samoreen** [comment]
Hi,

It seems that I eventually identified the problem. When looking at the "Program Access" security option in Outlook, I noticed that the antivirus status was set to "invalid". Which was plain wrong. I repaired the Office 365 installation and the status returned to valid. For the moment, the warning mentioned above didn't reappear.

**Comment by phw198** [comment]
As [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security).

The bug of Windows 11 notification not taking you to that page is #1870
