### ISSUE TITLE
ERROR: Unable to connect to the Google calendar

### ISSUE THREAD

**Issue by mattdmartin** [phw198/OutlookGoogleCalendarSync#1996]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.11.0.0
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
I have been using OGCS for more than a year on my work laptop. Today I started receiving the error "Unable to connect to the Google calendar."  I have disconnected and reconnected my Google account as well as uninstalled and reinstalled the app and continue to get the same error.  When reconnecting Google and attempting to retrieve calendars, I get a test pop-up message that asks if I can access the internet with Internet Explorer.  When I say yes IE launches and successfully connects to my Google account.

**Steps to Reproduce the Issue**  
Attempt to sync, receive error
Disconnect google account, attempt to retrieve calendars, receive error

**Any other information**  
[https://gist.github.com/mattdmartin/da535b9097dff718eccf049fc728f479](url)

![Screenshot 2024-10-24 040426](https://github.com/user-attachments/assets/f76252f9-f857-4730-bc4c-d93fceb4bb4c)

**Comment by mattdmartin** [comment]
![Screenshot 2024-10-25 023023](https://github.com/user-attachments/assets/8be27f46-44f9-4e64-9071-07b1b4794e43)

**Comment by tommy2gmxde** [comment]
I have the same problem

**Comment by phw198** [comment]
https://www.outlookgooglecalendarsync.com/blog/2024/09/01/2-11-0-beta-google-permissions.html

Duplicate #1937
