### ISSUE TITLE
Unable to reclaim orphan calendar entries in Google calendar.  Failed to retrieve master for Google recurring event outside of sync range.

### ISSUE THREAD

**Issue by diamonddyer** [phw198/OutlookGoogleCalendarSync#1997]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.11
**Edition**: Installed / Portable  
**Sync Direction**:  O->G 

**Bug Description**  
Every time I sync I get:

Total inc. recurring items spanning sync date range...

Unable to reclaim orphan calendar entries in Google calendar.

Failed to retrieve master for Google recurring event outside of sync range.

Value cannot be null.
Parameter name: pattern

Sync aborted after 1 failed attempts!

Everything synced fine until now, I made no changes to my Calanders or the settings of the app. 

**Steps to Reproduce the Issue**  
1. Go to sync tab
1. Click on press start sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync.log](https://github.com/user-attachments/files/17509141/OGcalsync.log)

**Comment by phw198** [comment]
:package: Thanks for reporting! This should now be resolved with [hotfix v2.11.0.11.zip](https://github.com/user-attachments/files/17535650/v2.11.0.11.zip) (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `B94ADBFA` Exe = `210B88BA`

Please let me know how it goes.

**Comment by diamonddyer** [comment]
I'm not able to download the fix. I use OGCS on my work computer and the zip file is being blocked by the admin.

**Comment by phw198** [comment]
That's annoying. Oh well, as a work around just uncheck "Word Obfuscation" given you haven't defined any rules.

**Comment by diamonddyer** [comment]
Hi, it’s working for me now. Thanks!
