### ISSUE TITLE
calendar events attempting to be deleted but prevented by deletions disabled. 

### ISSUE THREAD

**Issue by Billbarasch** [phw198/OutlookGoogleCalendarSync#1999]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [ ] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.11.0-beta
**Edition: Installed
**Sync Direction:O<->G**

When I add a meeting in outlook and sync to google calendar, OGCS creates the meeting in google and then continues.  When it reaches the  outlook <- google sync OGCS attempts to delete the the Newly created outlook entrie. I see no reason for OGCS to delete the entree.  I have deletions disabled so OGCS does not succeed
1. create calendar entry in outlook
2. start OGCS sync O<->G
3. progress windows shows the outlook entry being created in google
4. sync moves on
5. in outlook <- google sync OGCS attempts to delete the outlook side entry. 

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/user-attachments/files/17571981/OGcalsync.log)
[OGcalsync.log](https://github.com/user-attachments/files/17571986/OGcalsync.log)

**Comment by phw198** [comment]
Have you always had deletions disabled? If so, I think this may be a misleading message that it would delete the Outlook item(s). Please could you allow deletions, but enable "Confirm deletions" - this way if it _really_ is going to delete the item it just created in Google, you have the opportunity to decline the deletion.

But I suspect you won't be asked, and it will function correctly...

**Comment by phw198** [comment]
:package: I have confirmed the deletion warning is premature - please apply [hotfix v2.11.0.12.zip](https://github.com/user-attachments/files/17607454/v2.11.0.12.zip) and confirm sync works as expected (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `8BC934C5` Exe = `95E9A1E2`

Please let me know how it goes.

**Comment by Billbarasch** [comment]
> Have you always had deletions disabled? If so, I think this may be a misleading message that it would delete the Outlook item(s). Please could you allow deletions, but enable "Confirm deletions" - this way if it _really_ is going to delete the item it just created in Google, you have the opportunity to decline the deletion.
> 
> But I suspect you won't be asked, and it will function correctly...

I changed to warn for deletions on the outlook -> google. I was prompted for the deletion  
[OGcalsync.log](https://github.com/user-attachments/files/17610683/OGcalsync.log)

I created another meeting a few minutes later in outlook and no deletion prompt was received. 
In the past I did not have deletions disabled until I noticed that needed events were being deleted.

**Comment by phw198** [comment]
"test of OGCS deletion" and "test 2 ogcs deletion with debug set" both created in Outlook aren't exhibiting the behaviour initially reported (that they immediately get reported for deletion in Outlook following creation in Google), so I think that's confirmation there is at least a bug that it's warning that when it won't in fact delete.

Would have been good if you could have applied the hotfix and leave "Disable deletions" enabled, confirm that still has the same behaviour...

The deletion of Google item `10/30/2024 1:00 PM => "test"` again is separate from the two-way sync problem described, and I'm guessing that item didn't exist in Outlook either, so deleting would be the correct action.
