### ISSUE TITLE
Fails to connect to Google Calendar

### ISSUE THREAD

**Issue by sjuro54** [phw198/OutlookGoogleCalendarSync#2000]
OGC version 2.11.0.0  / Windows 11/Defender (with high level security, incl Ransomware prot) / Outlook 2021
[OGcalsync.log](https://github.com/user-attachments/files/17591768/OGcalsync.log)
When I during setup press retrieve calendar, it picks up correct google account but displays an error message "Failed to retrieve Google Calendars." I have attached the log file. 
I'd really appreciate a solution :-)
SJur

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
When you downloaded the software, [this page](https://www.outlookgooglecalendarsync.com/blog/2024/09/01/2-11-0-beta-google-permissions.html) should have displayed.

Duplicate of #1937 which has a hotfix.
