### ISSUE TITLE
Not allowing me to retrieve calendars

### ISSUE THREAD

**Issue by kathyrainsbury1** [phw198/OutlookGoogleCalendarSync#2005]
Hi, Can you tell me how to solve this - I initially managed to retrieve the calendar and authorise the app. When I then tried to sync, I wasn't able to and it get saying that google calendar not available. I reloaded it all, but now it says that it won't work if I don't allow it access to my google Calendar. However, when I try and retrieve the calendars again, it doesn't come up with the google accounts to choose from & I keep going back to not allowing access/ permission. 
Thanks for your input.
I have gone through checklist.. 

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by kathyrainsbury1** [comment]
I have now managed to fix the issue. However, many of my outlook appointments haven't transferred onto my Google calendar? Not sure why this is?

**Comment by phw198** [comment]
OP is duplicate of #1937 

Impossible to assist on last post without any of the information as requested in the checklist.
