### ISSUE TITLE
Color Mapping From Outlook To Google Fails

### ISSUE THREAD

**Issue by WarningU2** [phw198/OutlookGoogleCalendarSync#2006]
**OGCS Version**: v2.11.00
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
I have set up conditional formatting in Outlook to set colors which works fine in Outlook, but when I sync to Google calendar using OGCS with the color mapping I have defined, the colors are not set correctly on the Google calendar.  It defaults to blue.   If I define a color calendar entry on Google and sync to outlook the colors are set correctly.   

**Steps to Reproduce the Issue**  
1. Create a calendar entry in Outlook using conditional formatting.  
2. Sync to Google
3. Check Google Calendar and you'll find the color mapping did not work
4. I have created an example below using Dr.Nabeta Outlook Color Mapping which is orange in Outlook but is blue in Google for Dec17.  Then on the 24th I created a Google Calendar entry which I made orange and that is properly reflected in outlook.  Mapping from Google to Outlook works ... just not from Outlook to Google.   
5. My last step is to manually change the color to orange (tangerine in Google) on the google calendar and then sync which appears to show the color is picked up now - see pic 7 

**Any other information**  
Attached Files:
[settings.zip](https://github.com/user-attachments/files/17650459/settings.zip)
[OGcalsync.log](https://github.com/user-attachments/files/17650683/OGcalsync.log)

![pic1](https://github.com/user-attachments/assets/44f1e012-f7ec-46ee-9c1f-42feab416ba8)
![pic2](https://github.com/user-attachments/assets/29052e9f-2218-4b3a-97b4-d917b7d6c22f)
![pic3](https://github.com/user-attachments/assets/0572e6c7-6da6-4f7d-b425-b02dd908a3f7)
![pic4](https://github.com/user-attachments/assets/bc5654b8-4e5e-4e51-85da-be42b72b912e)
![pic5](https://github.com/user-attachments/assets/94145d1b-b941-46cc-8755-d4c35f01dfa1)
![pic6](https://github.com/user-attachments/assets/05e2a8a7-21cb-48a0-8e72-4b996523e3f8)
![pic7](https://github.com/user-attachments/assets/c9d4f33d-0b9d-4b37-a069-5c8a61450201)

**Comment by phw198** [comment]
:package: I can't seem to replicate this, so I've added in some logging if you could apply [hotfix v2.11.1.1.zip](https://github.com/user-attachments/files/17669587/v2.11.1.1.zip) (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `A4645EA1` Exe = `1AAD88E5`

If you could:
1. increase the logging level to `FINE` under Settings > Application Behaviour
2. delete the item in Google and then resync it from Outlook (one-way) 
3. upload the logfile again

Thanks!

**Comment by WarningU2** [comment]
Thanks for the swift reply … I will do as you requested this weekend.

**Comment by WarningU2** [comment]
Done.  The color mapping works if one way from Outlook to Google but fails if 2 way.  

The first test will show sucessful recreation.   Entry in Google deleted (on the 17th at 8am)
The second test (two way) will show the outlook entry being deleted
The third test (two way) with the entry in outlook being redefined (as orange) will show the blue entry being created in Google. pic attached of last 
[OGcalsync.log](https://github.com/user-attachments/files/17688722/OGcalsync.log)
![pic3](https://github.com/user-attachments/assets/fb9332d4-7bb8-42a5-aba2-3e5d3526d404)

**Comment by phw198** [comment]
So the first test is what I previously posted? Deleted in Google, one-way sync from Outlook? The logging shows what I would expect:-
```
2024-11-09 11:54:09,932 DEBUG 13 OutlookGoogleCalendarSync.Google.Calendar [1990] -  aiCategories: Orange Category
2024-11-09 11:54:09,933 FINE  13 OutlookGoogleCalendarSync.Google.Calendar [2054] -  Categories: Orange Category; Delimiter: , 
2024-11-09 11:54:09,974 DEBUG 13 OutlookGoogleCalendarSync.Google.Calendar [2034] -  Colour mapping used: Orange Category => 6:Tangerine
```
So after the 2nd test where the Outlook `2024-12-17 8:00 AM "Dr. Nabeta Outlook Color Entry Test"` is deleted, what created `2024-12-17 8:00 AM => "Dr. Nabeta Outlook Color Test"` in Outlook for it to be synced to Google? 

> with the entry in outlook being redefined (as orange)

I'm guessing you manually created it? Because apparently it doesn't have a category assigned:-
```
2024-11-09 11:58:20,629 DEBUG 24 OutlookGoogleCalendarSync.Google.Calendar [1990] -  aiCategories: 
2024-11-09 11:58:20,630 DEBUG 24 OutlookGoogleCalendarSync.Google.Calendar [2013] -  categoryColour is null
```
So I would expect that to sync to Google with the default calendar colour (not tangerine).

When you manually create the Outlook item, you could try double clicking it to full open it, before adding the category and saving and closing it - see if OGCS can then see the category properly?

**Comment by WarningU2** [comment]
Outlook Calendar Entry showing Orange

 



Uses conditional formatting in Outlook Calendar to set the color

(shows Orange)

 

I tried the test again

 

10:18 Google <-> Outlook = color entry on Google Calendar is blue orange outlook

10:21 Google <-- Outlook = same effect still blue Google but orange outlook

10:23 Google <-- Outlook (after deleting google calendar entry) =  same color blue 

10:27 Google <-- Outlook (after deleting google calendar entry and outlook entry and recreating a new outlook entry) =  same color blue

 



 

If I create the entry on google and make it orange it will be created <-> with correct color in Outlook
It just doesn’t work when creating the calendar entry in outlook with conditional formatting … like you said it (ogcs) doesn’t see the orange category or any category 

 



 

Well … the good news is … is that I figured it out.

 

It looks like conditional formatting does NOT actually assign the category in outlook but changes the formatting.   Or at least that is what I can infer.

 

When I changed the view to list and view by categories, the entries I am testing with are blue.   And after I drag them down to the orange category and resync … they are probably orange in Google

 



 

 

 



 

To be fair to you I didn’t realize this until now.  Sorry.  

 

And MS is doing away with Categories in Outlook … the default master list is not to be found anymore.    

 

You can close the record.   Thanks for excellent support.  

 

 

Stephen Warner | ***@***.*** | 1180 Bellview St., Burlington ON L7S 1C7 | c.905.317.7765 h.905.634.4629

**Comment by WarningU2** [comment]
[reply with pics.pdf](https://github.com/user-attachments/files/17880448/reply.with.pics.pdf)
I see the pictures didn't come across nor the settings and log file so here you are
[OGcalsync.zip](https://github.com/user-attachments/files/17880450/OGcalsync.zip)

**Comment by WarningU2** [comment]
Closing this item ... working as designed but good to know that outlook categories are not being assigned by conditional formatting.

**Comment by phw198** [comment]
Thanks for uploading the PDF with the pictures, very useful! I did wonder whether your first post was missing them (I don't know why GitHub refuses to take attachments by email).

Amazing what you learn - I've never played with conditional formatting before, and didn't know Outlook had the concept of _colours_, in contrast to _categories_. Super confusing when they do look the same at first glance, but yes a colour with no category assigned!

![Screenshot](https://github.com/user-attachments/assets/92a26104-aace-4c79-8984-e83ce4f083cf)

![Screenshot](https://github.com/user-attachments/assets/a00b8641-788a-4257-a5c8-ce8ec1f8d7e8)

**Comment by WarningU2** [comment]
![pica](https://github.com/user-attachments/assets/8f54e93b-b01c-4931-892e-a89b99d673e8)
Interesting ... I see you have a categorize button on outlook.  I don't see that option ... see pic.
For me to select a category I have to switch to list view and drag the item to the category color group. 

I am running version Microsoft® Outlook® for Microsoft 365 MSO (Version 2410 Build 16.0.18129.20158) 64-bit

**Comment by WarningU2** [comment]
reopening so you see comment above

**Comment by phw198** [comment]
Yeah, my screenshot is from Outlook 2016 MSO, so I guess you're seeing the start of Microsoft doing away with categories, as you say 😖 

I'm 99.99999% certain there is nothing related to "colours" (conditional formatting) on the COM object model for an appointment item, so I think it's purely Microsoft formatting the display of items as it renders them - there's not actually any metadata stored against the item, only the conditional formatting rules on the calendar. That's my guess anyway.

I'm also guessing that colours in Outlook on the Web _are_ stored on the appointment, and this is a change I'll have to accommodate for v3 of OGCS....

**Comment by WarningU2** [comment]
Closing
