### ISSUE TITLE
Google forwards meeting acceptance emails to Outlook attendee list

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#201]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/662596" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/ghvz1" target="_blank">ghvz1</a></strong> wrote at 2017-04-18 16:11:</p><div class="markDownOutput ">Outlook is my primary (and only) email and calendar provider at work. I use this sync program because Google is my personal calendar and I need to see my work calendar while I'm away from my desk. I've noticed something unusual today - my meeting acceptances
 that sync with Google calendar are now sending acceptance notices to the Outlook attendee list. In fact it looks like Google is forwarding the meeting to the attendees. These are for meetings created by others that I have accepted in Outlook. The Sync program
 puts these on my Google calendar and then is apparently forwarding the meeting notice from Google to the attendees. I have my sync options set to Outlook to Google. I don't have Attendees checked under Attributes to Include and yet they appear in my Google
 calendar. If Google keeps sending invites to Outlook meetings, I'm going to have to stop using this program.<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/anna781" target="_blank">anna781</a></strong> wrote at 2017-04-24 09:06:</p><div class="markDownOutput ">I am in the exact same situation as you, and this is happening to me as well. I would love for there to be a resolution because this issue is very frustrating.
<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/jaegerschnitzel" target="_blank">jaegerschnitzel</a></strong> wrote at 2017-04-24 11:33:</p><div class="markDownOutput ">I have the same setup. Google as personal calendar and company Exchange with Outlook as business calendar. I just want to see my business appointments in Google calendar. For me everyhting is working fine. Perhaps try to deactivate syncing attendees, this
 should fix your problems.<br>
</div></div>

**Comment by bbobley** [comment]
Yes, this used to happen to me until I changed the setting (under Sync Options tab) to no longer sync attendees.  Works fine now.

**Comment by phw198** [comment]
[Documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google) and a workaround proposed in issue #197.
