### ISSUE TITLE
My OGCS will not open 

### ISSUE THREAD

**Issue by MHsmithamanda** [phw198/OutlookGoogleCalendarSync#2012]
> Checklist:-
> * [ x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [ x] Complete the information below
> * [ x] Provide your `OGcalsync.log` file (see [how-to]([OGcalsync.log](https://github.com/user-attachments/files/17906726/OGcalsync.log)))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
My instance of OGCS will not open the window to allow me to actually sync/run the program. It opens the splash screen but never opens the application. When I click the application again to open it says another instance is already running but it is not open in the Apps part of the task manager - only in background processes.  I have upgraded to the Alpha from the Beta, unistalled and reinstalled the program, hard closed from task manager and attempted to run again. I also sent my log file in my uninstall google form and reattached below. 

**Steps to Reproduce the Issue**  
1. Go to... OGCS 
1. Click on... shortcut

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/user-attachments/files/17906787/OGcalsync.log)

**Comment by phw198** [comment]
Looks like Outlook isn't running when you start OGCS, and when OGCS tries to start it for you, Outlook is in Offline mode which is stopping OGCS from initialising properly.

Try starting Outlook first, making sure it is online and then starting OGCS.

**Comment by MHsmithamanda** [comment]
Thank you! I've never had to do that before now, but it seems to have fixed my issue. Appreciate the support!
