### ISSUE TITLE
Started getting     5/03/2017  "xxxxxxx" Appointment update failed. Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT)) 

### ISSUE THREAD

**Issue by TheJacksonian** [phw198/OutlookGoogleCalendarSync#2025]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: Sync version: 2.11.1.0
**Edition**: Portable  
**Sync Direction**: Both:  O<->G

**Bug Description**  
This error has just started out of nowhere, not sure what I should look at.

I've updated to 2.11.1 (Alpha) to see if that resolves, and it hasn't.
I did see a message about antivirus or Corp Policy, but I'm not sure what to check do there? Any advice/thoughts would be appreciated. I'm using Outlook on the desktop (I think it's 365 Apps for Enterprise?)

**Steps to Reproduce the Issue**  
Allow scheduled sync to happen.
[OGcalsync.log](https://github.com/user-attachments/files/18086692/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by TheJacksonian** [comment]
I'm not sure what is going on, but this is working now, no errors, please disregard.

**Comment by phw198** [comment]
`E_ABORT` is a generic error that essentially means that OGCS doesn't have permission to access to the Outlook object model. Not sure why this would have suddenly started and then stopped - hopefully just one of those Microsoft things where a reboot fixes things!
