### ISSUE TITLE
Upgrade Failure from 2.3.0.0 to 2.4.0.0

### ISSUE THREAD

**Issue by Exodii** [phw198/OutlookGoogleCalendarSync#203]
Attempted to upgrade from 2.3.0.0 to 2.4.0.0 using the quick installer.  Install completed, however on completion a dialog reports that it cannot launch and to contact the developer.  It also provides a link to an install log file that indicates the install failed the update check.  

I haven't posted the log file with this as I'm not sure whether there's anything within it that I need to scrub first - if you could let me know by reply, I'll provide it asap.

I did d/l the portable zip - the application starts there, but obviously cannot sync with the Google account.

TIA,  E.

**Comment by Exodii** [comment]
I've subsequently used Control Panel -> Programs & Features to roll back to 2.3.0 and this appears to be working as before.  A manual check in the program's About suggests 2.3.0 is the latest version however on PC start-up a dialog appears advising that a later version is available - hence my attempt to update to 2.4.0..

**Comment by phw198** [comment]
What's the name of the log file? If it has a breakdown of the ClickOnce install then it should be fine to upload here.

If it's the OGcalsync.log file, scan through and remove anything you don't want to share, but the only file you definitely should not share is the settings.xml...

Are you upgrading by accepting the upgrade notification on application start-up, or clicking Check for Update on the About tab?

**Comment by Exodii** [comment]
The logfile has a unique name each time it's generated - it's the install process log.  

Accepting the upgrade notification dialog on start-up just leads to the d/l page.  While About -> Check for Updates will tell you there's a new version but not point you at it.  I haven't installed 2.3.6 so I'm unsure whether that's a necessary interim step?  And I'm not on the machine with the log at the moment, but will attach it later so you can see whether there's anything obvious I should have done/need to do to upgrade.

**Comment by phw198** [comment]
As per OP comment in issue #92 and [their logfile](https://gist.github.com/phw198/6eb3538b0e3bf08da3ead6b91e7c6e5b), I wonder if this could be to do with anti-virus as it's reporting `System.IO.FileNotFoundException` when trying to activate the installation.

Could you try disabling AV during the install? If not, you may have to switch over to using the portable ZIP release.

To confirm, you should be upgrading from v2.3.0 to v2.4.0. v2.3.6 is an alpha release and not available through the ClickOnce installer, just as a portable ZIP release. I'm not quite sure why you're getting taken to the download page when opting to upgrade - it should just upgrade in situ...

**Comment by rrudrrud** [comment]
I'm using Avast 17.4.2294 (built 17.4.3482.0) and it was disabled it in the first place while running OutlookGoogleCalendarSync.application but couldn't run the software anyway. I'm not sure if simple disable is enough. May AV still prevent app from running? I'll try to create an exception now.

**Comment by Exodii** [comment]
OK.  First things first - yes, the logfile is to all intents the same as #92.  

Having rolled back to 2.,3, since reading your post I tried restarting OGCS again however received no upgrade notice.  I also restarted the PC, again without receiving the upgrade notice.  

I checked the version to make sure it was 2.3 (it was) and then used the manual check for update button in the About dialog.  It reported the PC was running the latest version.  I turned off AVG and manually updated the software again using the oneclick installer.  

While I'm yet to 'test' 2.4 it seems to be running happily and AVG hasn't complained but I may already have setup an exception there when I initially installed the software whenever ago.  Thanks for your assistance.

**Comment by phw198** [comment]
Definitely seems like AV is causing issues for you. @rrudrrud, did you have any luck creating an Avast exception?

**Comment by rrudrrud** [comment]
I uninstalled the software, switched off all the Avast' shields and reinstalled programme (I was running v2.4 from the beginning). Sync. worked at once. After turning shilds on AV at first didn't report anything but after several synchronizations showed a warning message about suspicious software. Ignoring that monit solved the problem. 
Regardless that issue when bidirectional sync is selected it works only one way G->O. When O->G is selcted works fine. That's weird.
Anyway thank you for the hint about AV.
