### ISSUE TITLE
App doesn´t start

### ISSUE THREAD

**Issue by ww76** [phw198/OutlookGoogleCalendarSync#204]
When starting my computer (and the app), there´s an error message ("Programm kann nicht ausgeführt werden" = " app can´t be initiated" or sthg. like that.
Within the same window I can close the app.
If I restart it, it freezes and can´t be close anymore, no matter by what, unless I reboot.
Any idea?
Also removing and re- installing tha app didn´t help.

**Comment by nvardi** [comment]
Similar problem here - OGCS starts briefly then shuts down. This installation worked for  some weeks now, until this weekend, where Windows (and possibly other software on the machine) was updated.
The log file for last start attempt is attached.
[OGcalsync.log.2017-05-15.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1000364/OGcalsync.log.2017-05-15.txt)

**Comment by phw198** [comment]
I think I might have been able to fix this remotely - can you confirm if the app starts OK now?

**Comment by team-o** [comment]
I've had the same problem - now everything works fine. Thank you!

**Comment by phw198** [comment]
Thanks for confirming. This was related to work over the weekend on the GitHub project website, where there was no release available - I have added an empty/dummy release to get around this.

**Comment by nvardi** [comment]
Today runs as expected also in Copenhagen... 
Thanx!
