### ISSUE TITLE
No github readme

### ISSUE THREAD

**Issue by Zarremgregarrok** [phw198/OutlookGoogleCalendarSync#205]
Greetings, there is no github readme greeting new users and telling them how to install this application.

**Comment by persistency** [comment]
yes.... would be very helpfull... is there a binary version available for download too?

**Comment by phw198** [comment]
Agreed, but I haven't finished migrating the project yet... :smirk:  
Documentation is the next bit to be done.

For binary install media, that can still be [found on CodePlex](https://outlookgooglecalendarsync.codeplex.com/releases/view/631330).

**Comment by persistency** [comment]
thx, but the currenty binaries crash upon startup. Was hoping this was fixed (see other thread), but the current binairies keep crashing (also after reinstall)

**Comment by cal-holman** [comment]
The binary on CodePlex stopped working on my system - the following update installed over the weekend on Windows10 - 2017-05 Cumulative Update for Windows 10 Version 1607 for x64-based Systems (KB4019472)

**Comment by phw198** [comment]
@persistency, @cal-holman Are you guys referring to issue #204? This was fixed 5 hours ago.

BTW, please don't cross-post - the app not starting has nothing to do with "No github readme"...

**Comment by persistency** [comment]
This might be well the case, but I don't have a proper build environment on my machine, so I cannot build it. Therefore I'm looking for the latest binaries. Codeplex has binaries but not the latest, but here they're not at all

**Comment by cal-holman** [comment]
@phw198 Sorry - i did read #204 but could not find the version you built to solve - then there was the comment in this thread that the binaries were over on CodePlex - so i was reacting to that.  I apologize for cross posting.

**Comment by phw198** [comment]
CodePlex does have the latest binaries - I've not shipped any changes since those in the link I provided in [my earlier comment](https://github.com/phw198/OutlookGoogleCalendarSync/issues/205#issuecomment-301464651). You'll see in #204, the fix/workaround did not require a new build.

@persistency For building from source, it's Issue #93 you're after.

**Comment by persistency** [comment]
sorry for crossposting. After uninstall, reboot, new install, it somehow started working again. Don't understand why, but I'm happy with that

**Comment by phw198** [comment]
Readme has now been competed.
