### ISSUE TITLE
Errors after upgrading to latest version

### ISSUE THREAD

**Issue by PaulOckenden** [phw198/OutlookGoogleCalendarSync#206]
I get this when I try to Sync:

**Comparing 22 existing Google calendar entries...
WARNING: Updated event failed to save.
Google.Apis.Requests.RequestError
Precondition Failed [412]
Errors [
	Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]
]**

It happens LOADS of times.

**Comment by Catskinner** [comment]
I'm having the same problem. The error message seems to be identical:

**Comparing 32 existing Google calendar entries...
WARNING: Updated event failed to save.
Google.Apis.Requests.RequestError
Precondition Failed [412]
Errors [
	Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]
]**

However it repeats several time for each sync. I assume it's related to the number of events that are causing a problem.

**Comment by phw198** [comment]
Looks like a duplicate of issue #83.
