### ISSUE TITLE
Web request to 'https://accounts.google.com/o/oauth2/token' failed

### ISSUE THREAD

**Issue by chinaski78** [phw198/OutlookGoogleCalendarSync#208]
Hi there,

Since I updated to the last version of OGCS, the synchronisation fails. I have tried downgrading, disconnecting and retrieving calendar with new Google auth code, removing the app from Google authorized applications and restart the auth process again, nothing worked so far.

Your help would be greatly appreciated!

Please see [my log file](https://gist.github.com/phw198/f87a2bb842ffd5e0eb4dd4bab23f6c5a).

**Comment by phw198** [comment]
It [looks like](https://gist.github.com/phw198/f87a2bb842ffd5e0eb4dd4bab23f6c5a#file-ogcalsync-log-L112) communication out to the internet is dying half-way through the authentication process. 

Are you able to try the authentication step on bare internet, not via a proxy?

**Comment by chinaski78** [comment]
Correct. My company firewall or proxy seems to be somehow blocking the communication, which is new...
I just tried with my personal internet access and it worked prefectly. I got fooled by the fact this issue occured just when I updated my OGCS version.
Thanks for the help!

**Comment by phw198** [comment]
Out of interest, once you have completed the authentication successfully, are you then able to sync at work through the proxy? Or has it broken OGCS entirely?

**Comment by chinaski78** [comment]
After a succesful authentication on a separate network, I am now able to sync at work.
