### ISSUE TITLE
Push Outlook Changes Immediately does not work

### ISSUE THREAD

**Issue by kaoriks** [phw198/OutlookGoogleCalendarSync#209]
Push Outlook Changes Immediately does not work -- I want to attach the log file but this site does not allow me to attach and I got an error message "We don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. "

**Comment by phw198** [comment]
Either create a gist and link to it (preferred), or rename the .log file to a .txt and upload it.

**Comment by kaoriks** [comment]
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1009075/OGcalsync.txt)

**Comment by kaoriks** [comment]
Thank you! I hope this works...

**Comment by phw198** [comment]
I haven't had a chance to look at the code yet, but could you try setting the sync internal to something like every 10 hours - I'm just wondering if the push isn't working unless the interval is something other than zero...

**Comment by alvarotrapote** [comment]
Yes, it works. I had the same problem as @kaoriks and setting "When - Interval" to something that is not 0 (10 minutes in my case) and "Push Outlook changes immediately" activated, it makes the auto sync to be triggered whenever you add an event in Outlook.

**Comment by phw198** [comment]
@kaoriks I actually can't replicate this behaviour. However, I have added some extra logging now.

:package: Could you apply this [Hotfix-v2.5.0.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1066136/Hotfix-v2.5.0.4.zip) [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)] and then set logging level to `FINE`. Every 2 minutes it should record `Push sync triggered, but no items queued.` (or of course sync if you have changed some items).

Please let me know how it goes.

**Comment by phw198** [comment]
@kaoriks Any update on v2.5.0.4 and providing the logfile?

**Comment by phw198** [comment]
The extra `FINE` level logging is added into the main application branch, so if anyone else comes across this issue, please provide the log file as instruction previously.
