### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by bbobley** [phw198/OutlookGoogleCalendarSync#210]
Most of the time, OGCS syncs just fine. But I'd say at least once a day, it fails with popup error asking if I'd like to try again. When I look in the sync window, it says "Could not create SSL/TLS secure channel." If I tell it to try again, it will often fail one more time, but then work the third time. Then it may well sync just fine the rest of the day. Log is attached.  Thanks!!

[OGcalsync - Copy.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1008605/OGcalsync.-.Copy.log.txt)

**Comment by bbobley** [comment]
As an update, I am continuing to see this at least once a day. Just now, I had to click the popup error to keep trying three times before it eventually completed the sync.

**Comment by phw198** [comment]
And the previous error to the "Could not create SSL/TLS secure channel" was "Web request to 'https://accounts.google.com/o/oauth2/token' failed.". Smells like a flaky proxy server/internet connection 
to me.

I guess I could add in a few automatic retries for these errors

**Comment by EmbeddedEngineerTinker** [comment]
+1 I am seeing a similar problem where a few times a day the sync does not run through because of a connection error or similar failure. Maybe automatic retry could be implemented with adjustable time between retries and retry count before displaying the pop-up asking to try again.
If I tell it to retry it always run through, so this will definitely eliminate those pop-ups.

**Comment by phw198** [comment]
Please confirm if this issue remains with v2.6.1, where the authentication process to Google has been updated.

**Comment by bbobley** [comment]
Thanks for this update.  I haven't seen the error in a couple of days now!  Previously, it was happening at least twice a day.

**Comment by phw198** [comment]
Sounds promising. Hopefully closing this ticket won't jinx it!
