### ISSUE TITLE
Application unexpectedly terminated! [0x8002801D TYPE_E_LIBNOTREGISTERED]

### ISSUE THREAD

**Issue by thwyster** [phw198/OutlookGoogleCalendarSync#213]
![image](https://cloud.githubusercontent.com/assets/3345073/26312394/c8bdd058-3edd-11e7-92eb-3ddefa4fb567.png)

**Comment by phw198** [comment]
Looks like you have a bad install of Office - have a read through [this SO article](http://stackoverflow.com/questions/2347529/outlook-2007-from-c-sharp-com-exception-type-e-libnotregistered) and see if you can find anything that helps...

Let me know if it gives you the solution and I'll add it to the wiki.

**Comment by phw198** [comment]
Also, instructions for a fix are [here](https://www.fieldstonsoftware.com/support/support_gsyncit_2013.shtml).

**Comment by phw198** [comment]
:link: [Wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002801d---type_e_libnotregistered)
