### ISSUE TITLE
AVG Flags as IDP.Generic and IDP.ALEXA.51

### ISSUE THREAD

**Issue by neil1111** [phw198/OutlookGoogleCalendarSync#214]
Hi. I just installed this and it worked great - once.  Then, AVG flagged it as IDP.Generic.  I presumed this was a false positive and re-installed the application.  It worked again - once.  Then, AVG flagged it with IDP.ALEXA.51.

At this point, as much as I have confidence in GitHUB, I would appreciate feedback from the developers on whether or not this is a false positive.

FYI, I'm running Outlook 2013 under Win10 64bit.  
Thank you,
Neil

**Comment by phw198** [comment]
Hi Neil,
Well I can certainly say the software isn't a virus, and there have been plenty of forks of the project so I'm sure someone would have noticed if it was :-)

The bit AVG probably doesn't like is OGCS determining the email address of meeting attendees - try turning this off in the settings of OGCS. Of course, if you still want attendees synced then I can only suggest [reporting to AVG](https://secure.avg.com/submit-sample) the false positive...
