### ISSUE TITLE
Outlook calendar won't sync to Google (version 2.4)

### ISSUE THREAD

**Issue by Naretsune** [phw198/OutlookGoogleCalendarSync#221]
Good Evening, 

When I create an event in Outlook, it won't sync over to Google. I checked previous tickets and played with the dates as suggested. However, that doesn't fix anything. Google will sync to Outlook though.
```
Sync started at 5/27/2017 11:08:09 PM
Syncing from 5/26/2017 to 7/27/2017
Outlook ↔ Google
--------------------------------------------------
Reading Outlook Calendar Entries...
0 Outlook calendar entries found.
--------------------------------------------------
Reading Google Calendar Entries...
6 Google calendar entries found.
--------------------------------------------------
Total inc. recurring items spanning sync date range...
Outlook 0, Google 6
--------------------------------------------------
0 Google calendar entries to be deleted.
0 Google calendar entries to be created. ---> 1 item should be created.
--------------------------------------------------
0 Outlook calendar entries to be deleted.
1 Outlook calendar entries to be created.
--------------------------------------------------
Creating 1 Outlook calendar entries...
5/29/2017 7:00 AM => "Test"
Done.
--------------------------------------------------
Sync finished with success!
```
Please let me know if you need additional information. 

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1033938/OGcalsync.txt)

**Comment by phw198** [comment]
What do you mean by "playing with the dates"? If you have items in Outlook in the next 2 months, it looks like the default Outlook date format isn't working for you - you need to try different formatting options until it picks them up.

From your logs, I can see you created a "test" event in Google and that synced to Outlook as expected.

**Comment by Naretsune** [comment]
Hi Paul, 

Thank you for getting back to me. Yes, the test worked from Google to Outlook, but the calendar items I make in Outlook won’t sync to Google. Below is a screenshot of what I meant by dates. Sorry, I should have said date formats. 


The attachment shows where I created an item in Outlook named “Test Outlook to Google,” ran the sync, and opened Google Calendar. The item isn’t there. I’ve uploaded an updated log file where I ran through the different date formats. I hope this helps! 


![2017-05-28 03_21_10-google calendar - week of may 28 2017](https://cloud.githubusercontent.com/assets/29009096/26530537/ac61e856-43a4-11e7-84b2-c2523f0c1dcc.png)
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1034337/OGcalsync.txt)
[OGcalsync_Date_Formats.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1034336/OGcalsync_Date_Formats.txt)
![date_format_screenshot](https://cloud.githubusercontent.com/assets/29009096/26530538/ac62b3a8-43a4-11e7-8108-fd40f273734c.png)

**Comment by phw198** [comment]
Can you update the ticket on GitHub directly - the attachments don't come through on email replies...

**Comment by Naretsune** [comment]
Hi, Paul. I've updated the original reply. - Thanks

**Comment by phw198** [comment]
Thanks, but I don't see any evidence of you changing the date format. You need to be trying each of the options in the drop-down under "Regional Date Format" and then click "Test" to see if it returns any items. With any luck the "Short Date & Time" option will work for you.

**Comment by Naretsune** [comment]
I didn't click test and then sync, but I was able to get everything to work. I ended up having to change the filter categories (disabling all of them) and both calendars synced just fine using the date format you suggested.

Thanks for your help! Awesome tool overall.

**Comment by matodanko** [comment]
This worked for me as well! Thanks guys, but it wasn't necessary to change the datetime format for me before the recent update to the latest version. It just stopped working and it took me a few days to find this thread and fix it. Paul, if you will be able to add a feature to sync also event category/color somehow to Google Calendar, you will deserve my donation!

**Comment by phw198** [comment]
@matodanko Colour sync is on the to-do list, but there are a few prerequisites before it can be done...
