### ISSUE TITLE
Can't retrieve Google Calendar in 2.4.0.0

### ISSUE THREAD

**Issue by Artyrm** [phw198/OutlookGoogleCalendarSync#222]
It says 
"Unable to get the list of Google calendars. The following error occurred:
Root element is missing."

It appears due to the fact that settings.xml is empty on first start. If click "Save" and restart app, calenar is retrieved OK.

**Comment by phw198** [comment]
I can't replicate this issue.

:spiral_notepad: Please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)].
