### ISSUE TITLE
Synced with different timezone

### ISSUE THREAD

**Issue by nereusuj** [phw198/OutlookGoogleCalendarSync#223]
Hello,

My timezone in Outlook is Asia/Seoul.
But the timezone synced in Google is changed to Asia/Chita.

```
Start Timezone: Asia/Seoul => Asia/Chita
End Timezone: Asia/Seoul => Asia/Chita
2017-05-31 19:27:57,295 DEBUG 6 OutlookGoogleCalendarSync.MainForm [0] - 2 attributes updated.
```

**Comment by nereusuj** [comment]
Now, it is changed to Asia/Yakutsk today.
I created new schedule in Outlook and synced to Google.
The timezone changed to Asia/Yakutsk in Google.

Please refer logs but I couldn't find any useful idea from log.
https://gist.github.com/nereusuj/e894e0155113f1f84e8fe7aebc657618

**Comment by nereusuj** [comment]
Ping...
Any help or comment on my issue?

**Comment by phw198** [comment]
There's been no change within OGCS for timezone information in recent releases. The only thing that would impact this is the timezone database file you're using - check in the About tab to see if you have the latest: 2017b.

Did you change/update anything when it started setting to Yakutsk?

I can't see in your log file any updates of timezone, but I'll try and have a test of your timezone when I get a moment...

**Comment by nereusuj** [comment]
The timezone database file is 2017b.

I upgraded to 2.4 and revert to 2.3 repeatedly and the timezone synced in Google has changed.

Today, the timezone changed to different one.
```
Comparing 49 existing Outlook calendar entries...
2017-06-13 오후 1:00 (R) => "XXXX"
Start Timezone: Korea Standard Time => Transbaikal Standard Time
End Timezone: Korea Standard Time => Transbaikal Standard Time
2 attributes updated.
1 entries updated.
```

Hmm. the 'Transbaikal Standard Time' seems to be Asia/Chita.
And the Asia/Chita, Asia/Yakutsk and Asia/Seoul are in same time offset UTC+9

**Comment by b0ssman** [comment]
i have the same problem
08.08.2017 11:00 (R) => "PaaS - Internal Review"
Start Timezone: Asia/Calcutta => Asia/Kolkata
End Timezone: Asia/Calcutta => Asia/Kolkata
2 attributes updated.

I think the calendar entries are compared first and then the attributes are updated. this causes the comparison to always find a difference if an attribute is modified.

**Comment by phw198** [comment]
@b0ssman I think I'd expect that change. Calcutta is the old spelling for Kolkata.

**Comment by nereusuj** [comment]
I still have this issue with 2.6.0

**Comment by phw198** [comment]
The @b0ssman Calcutta/Kolkata issue is being worked around under issue #349.

**Comment by phw198** [comment]
@nereusuj Does this page help: https://blogs.technet.microsoft.com/dst2007/2016/03/15/time-zone-updates-for-russia/

Looks like some changes have been pushed to Windows for the regions you're having problems with. What I'm not sure about is if Google are handling the changes properly (see the other issue re Calcutta/Kolkata). Anyway the MS article talks about what time zone to pick according to whether the meeting is set for before or after the change.
