### ISSUE TITLE
Not syncing Outlook → Google at all anymore

### ISSUE THREAD

**Issue by OmarGhazi** [phw198/OutlookGoogleCalendarSync#229]
Hi - Thanks for this awesome tool - I have been using it for quite some time and it's great. I rely on it everyday!

I have unfortunately ran into an issue that started maybe a week ago, at least that's when I started noticing it. Any new items added to my Outlook calendar doesn't get pushed to my Google calendar. Before v2.5.0.0 came out, I tried the hotfix method and that didn't solve the issue either. I have created dummy appointments and meetings in Outlook and not only does it not sync, it doesn't even register that there needs to be a new google calendar entry to be created. I looked around other issues and I wan't able to find anything similar so I created this Issue request. 

[OGCalSync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1052257/OGCalSync.zip)

**Comment by phw198** [comment]
I think this is the same as [Issue #221](https://github.com/phw198/OutlookGoogleCalendarSync/issues/221#issuecomment-304534728) - for some reason the default date format is no longer effective for some people from v2.4.

Let me know if this works for you.

**Comment by OmarGhazi** [comment]
This seems to work now however, if I delete a meeting from Outlook, it doesn't remove it from Google Calendar.

**Comment by phw198** [comment]
Your settings seem to show that you have deletions disabled. :wink:

**Comment by OmarGhazi** [comment]
Ahh....completely missed that. It's working great now! Thanks for this amazing tool!
