### ISSUE TITLE
AVG virus alert

### ISSUE THREAD

**Issue by hferi11** [phw198/OutlookGoogleCalendarSync#231]
Latest version (2.5.0) raises an IDP.Generic virus alert for AVG Free. I downloaded from the old codeplex site.
Is it false positive? If yes, please check with AVG, they have a whitelisting service:
https://support.avg.com/SupportArticleView?l=en&urlName=What-is-AVG-Whitelisting-service&q=How+to+report+a+false+incorrect+detection

Thanks for developing this program, it is really great! :)

**Comment by gwins** [comment]
I have the same concern. I'm wondering why there's no response from @phw198  side. Hope to receive an all-clear soon.

**Comment by pyheme** [comment]
For info, Avast had the same behaviour when upgrading to the latest version.  Unfortunately I did not write down the details at the time, but I agree it would help to whitelist the app with the AV companies.

**Comment by phw198** [comment]
I'm not sure why the false positives in 2.5.0 - the main change was preparing for a change of installer from ClickOnce to Squirrel, which now includes a bunch of compression libraries etc. 

I'm not sure I have the time to register every single release of the app with whichever over zealous AV people choose to use 🙂 I'll try and look into it, but may need assistance from the user community to submit false positives...

**Comment by pyheme** [comment]
On my side, I did report it as a false positive in Avast when it popped up. 
In case it helps, in thinking about it, I think I recall that the last update of the app did trigger Avast as well, so I don't think that it's linked to this specific update.
Now for the weird part, I tried to get Avast's alert by installing OGCS on another laptop just now and Avast did not bulged.

**Comment by yourlive** [comment]
F-Secure also flagged this as a virus.

**Comment by phw198** [comment]
Wiki [updated with AV false positive section](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#anti-virus-false-positives).
