### ISSUE TITLE
Outlook to Google doesn't sync after changes

### ISSUE THREAD

**Issue by Surj100** [phw198/OutlookGoogleCalendarSync#232]
Hi
Apologies if this isn't an issue but need some help. Everything worked fine until I changed from Office 365 to Office 2016.  

The synch is now not picking up any outlook events (though 2 way synch is on with relevant calendars loaded). Google calendar appts are picked up and synched with Outlook. 

Workaround is to have both calendars displaying on my phone - have tried re-installing app and outlook email account. Any ideas welcome.

**Comment by phw198** [comment]
Take a look at [issue #221](https://github.com/phw198/OutlookGoogleCalendarSync/issues/221#issuecomment-304534728).

**Comment by Surj100** [comment]
Thanks very much – this seems to work.
Thanks again
