### ISSUE TITLE
Program never finds any Outlook Calendar Entries

### ISSUE THREAD

**Issue by LlamaMan382** [phw198/OutlookGoogleCalendarSync#233]
Whenever I try to sync with 2.5 or 2.4, the software fails to find any Outlook events.  This was not a problem in earlier versions of the software.

**Comment by phw198** [comment]
Take a look at [issue #221](https://github.com/phw198/OutlookGoogleCalendarSync/issues/221#issuecomment-304534728).

**Comment by LlamaMan382** [comment]
I believe that took care of it, thank you!  Might have new issues but I'll play around with it some first.
