### ISSUE TITLE
Member not found -- Fails to sync.

### ISSUE THREAD

**Issue by globetrotterdesigns** [phw198/OutlookGoogleCalendarSync#235]
Downloaded the two latest betas and now the sync will not work :(

The following error was encountered during sync:-
Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND))
Reading Outlook Calendar Entries...
22 Outlook calendar entries found.

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by globetrotterdesigns** [comment]
[OGcalsync - Copy.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1071739/OGcalsync.-.Copy.zip)
Here you go!

Thank you!

**Comment by globetrotterdesigns** [comment]
Any thoughts on this? The popup window keeps popping up asking to sync and fails to sync creating the never ending popup window :(

**Comment by phw198** [comment]
Sorry for the delay on this. Could you upgrade to v2.5.1 (on the _About_ tab check the _Alphas_ box) and confirm if the issue remains?

**Comment by globetrotterdesigns** [comment]
Unfortunately, issue remains.. :( Attaching the new sync log.
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1134057/OGcalsync.zip)

**Comment by globetrotterdesigns** [comment]
Just updated and it's still showing the same error. 2.5.2.0

**Comment by phw198** [comment]
I've added in some extra logging around where I think the error's happening, but need your help.

:package: Could you apply [v2.5.2.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1168065/v2.5.2.4.zip), run a sync and then provide your new log file? See [instructions for how to apply hotfixes](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix).

Thanks!

**Comment by globetrotterdesigns** [comment]
Here you go!
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1168379/OGcalsync.zip)

**Comment by phw198** [comment]
Hmmm, unfortunately still no clearer - more logging added, if we could repeat the exercise!

:package: [v2.5.2.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1168412/v2.5.2.7.zip).

**Comment by phw198** [comment]
@globetrotterdesigns Any luck with v2.5.2.7?

**Comment by globetrotterdesigns** [comment]
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1180876/OGcalsync.zip)
Still same issue :(

**Comment by phw198** [comment]
Ok, the additional logging isn't actually showing a problem where I thought it might be. I'm not even sure it's a problem created by OGCS.

Could you try just opening the Outlook appointment series `12/6/2016 2:00 PM (R) => "テラピ"` and pressing Ctrl+S to save it (maybe making a trivial change to it too). Does this save without error?

**Comment by globetrotterdesigns** [comment]
Ya no issue when saving..

**Comment by globetrotterdesigns** [comment]
It worked perfectly before the update that happened before Jun 12.. so that's why I feel something changed, because it no longer was working without the incessant errors.

**Comment by globetrotterdesigns** [comment]
Updated to latest version, and error still is occurring.

**Comment by phw198** [comment]
Do you own the `12/6/2016 2:00 PM (R) => "テラピ"` appointment series? Can you try recreating it?

**Comment by globetrotterdesigns** [comment]
I do--I've just deleted the series all together to see if that will help :)

**Comment by globetrotterdesigns** [comment]
Wow! That did it. Must have been something with that series then. Thank you thank you thank you!!

**Comment by phw198** [comment]
Yes, that's why I'd hoped that doing a dummy save on the series might get outlook to resolve the problem itself. Anyway, glad you were able to remove the series and get OGCS working again!
