### ISSUE TITLE
installation failure when trying to update version

### ISSUE THREAD

**Issue by RJDiPietro** [phw198/OutlookGoogleCalendarSync#236]
Could not install the latest version.
Exception occurred loading manifest from file.
ICSharpCode.SharpZipLib.dll: the manifest may not be valid of the
file could not be opened.

I was trying to update from inside the application when it asks me if I want to update.   Same error when I click on Check For Update.

**Comment by phw198** [comment]
Do you have an antivirus application running? If so try disabling it during upgrade, otherwise switch to the portable ZIP version.

**Comment by RJDiPietro** [comment]
Thank you so much, I will try that.
