### ISSUE TITLE
COM Exception encountered [0x800401E3]

### ISSUE THREAD

**Issue by cycleguy55** [phw198/OutlookGoogleCalendarSync#237]
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1075846/OGcalsync.log.txt)

**Comment by phw198** [comment]
So what was happening at 11.04? Was your computer starting up as I see you have OGCS set to start on machine startup and the COM exception only happens then. When you start OGCS 30 mins later there's no problem...

**Comment by cycleguy55** [comment]
While I don't recall with certainty, I suspect this 11:04 was a re-boot. Assuming that's so, why was this the only re-boot where I got a COM exception - why not the others?

**Comment by phw198** [comment]
It could just be that on that particular boot, Windows was very busy doing other things - maybe finishing off installing some Windows updates or something? Anyway, v2.6.0 now brings the ability to set a delay on the startup of OGCS so this should help prevent recurrence of this issue if necessary.
