### ISSUE TITLE
Outlook fails on get_Body()

### ISSUE THREAD

**Issue by jrlester70** [phw198/OutlookGoogleCalendarSync#240]
Just started looking at this, and was working fine for 3 days, then started getting sync errors.

It turns out that one company I deal with send meeting invites in a weird format, and your sync tool seems to have a problem with it. What would you need from me to help diagnose this problem ? Effectively it looks like the invite body contains a 1x1 table, with all the content in the table body. I'm guessing Google can't support that and so it gets upset on the event creation.

Jason

**Comment by phw198** [comment]
:spiral_notepad: To start with, please could you provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by jrlester70** [comment]
Hope this helps: https://gist.github.com/jrlester70/2b636a8a3f7ba908730b5088f2f2685a

**Comment by phw198** [comment]
Well you're right, the sync is failing at the point where it [gets the contents](https://gist.github.com/jrlester70/2b636a8a3f7ba908730b5088f2f2685a#file-ogcalsync-log-L247-L249) of the Outlook appointment body. Bizarre and I can't find much on Google about it.

Wonder if it's just a problem with this one particular appointment. Could you uncheck the sync of Description, in order that the Google event should get created and then check the option again. We can then see if the problem occurs on another item in the future...

**Comment by jrlester70** [comment]
Yeah, if I remove the description option, it works fine.

I have included an example invite (attached), which failed (I have masked all but the sender). I think it has to do with the embedded content. I hope this helps.

Regards,
Jason

**Comment by phw198** [comment]
:paperclips: Unfortunately files can't be attached to the ticket when replying by email - please could you log in to GitHub to upload files.

**Comment by jrlester70** [comment]
Example of a calendar entry which fails

[Test entry.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1101275/Test.entry.zip)

**Comment by phw198** [comment]
I've tried using the example calendar entry you provided, but it doesn't produce any error and syncs fine. If you are OK to simply disable sync of descriptions, then I think we'll leave it there as no-one else has ever reported this! The only option I'd have is to skip sync of description when the error is encountered anyway...

**Comment by jrlester70** [comment]
Paul,

I recently upgraded to outlook 2013, and switched the descriptions back on. Since then I don’t seem to have had the same problem, but will continue to monitor. If the problem only affects legacy users, then I would suggest you ignore it. I’ll keep you updated.

Regards,
Jason

**Comment by phw198** [comment]
As you say, sounds like a bug in earlier versions of Outlook, so I think I'll leave this as it is.

Cheers,
Paul
