### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by peterf9** [phw198/OutlookGoogleCalendarSync#241]
First, congratulations for this great program. Since las update "Merge" is not working. If I do any change in google calendar (like address) the appointment is being duplicated / created a new entrie from outlook

**Comment by phw198** [comment]
Hi @peterf9, 

:spiral_notepad: It would be helpful if you are able to provide your OGcalsync.log file for me to investigate this [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]
