### ISSUE TITLE
Outlook Google Calendar merger 

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#242]
The new calendar merger is not working. I really need this to work, but I get a message informing me to contact the vendor. Not into building code, etc.,, just need to know whats going with the software.

Cheers

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by ghost** [comment]
Thank you Paul

 

I am also unable to download the new version of OG Calendar Sync and kind of get the same message.

 

Regards

 

Lachie

**Comment by phw198** [comment]
Looks like your anti-virus is getting in the way of the CodePlex ClickOnce installer, which is legacy now anyway!

Either download the Portable ZIP release and use that, or try the installer for the [latest release on GitHub](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.5.1-alpha/Setup.exe) -
 v2.5.1 is just out.

**Comment by ghost** [comment]
Hi Paul, Thanks for getting back to me. I will maybe attempt another install. I am using a legacy copy, from a previous download, which is working fine, so if I can continue to use that, I will.

Thanks again.

Regards
Lachie Tod

**Comment by phw198** [comment]
OGCS no longer uses ClickOnce as an installer.
