### ISSUE TITLE
Syncing both Google to Outlook shows timezone error

### ISSUE THREAD

**Issue by cristauser** [phw198/OutlookGoogleCalendarSync#246]
Hello,

I'm trying to synchronize Outlook <-> Google and the insertion from Outlook to Google works well, but the insertion from Google to Outlook is not working showing this at log: Timezone "CET" has no mapping.

Regards

**Comment by cristauser** [comment]
I'm using the portable application.

**Comment by phw198** [comment]
What version of OGCS are you using, and what version of the Timezone DB does it show you're using (check the _About_ tab)?

However, this did come up on [CodePlex Issue 143](https://outlookgooglecalendarsync.codeplex.com/workitem/143) and I had to close it as _Won't Fix_ - CET is not really a timezone, but a timezone region with ambiguities around daylight saving. Google Calendar webapp doesn't allow CET to be entered as a timezone, so I'm guessing some other 3rd party software created this Google Event for you?

There's a slim possibility that when I begin updating the Google DLL API library (OGCS uses a rather out of date version), that it will surface more information.....but I think that's a long shot.

**Comment by phw198** [comment]
3-letter timezones aren't proper IANA timezones and therefore this won't be fixed or supported. The timezone needs to be set properly in the source calendar.
