### ISSUE TITLE
Error COM exception

### ISSUE THREAD

**Issue by jlrose13** [phw198/OutlookGoogleCalendarSync#250]
COM exception encountered. Please log an Issue on CodePlex and upload your OGcalsync.log fillast few e.

logs attached in zip file

[OGcalsync.log.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1099715/OGcalsync.log.zip)

**Comment by phw198** [comment]
Unfortunately none of the log files you've provided include the COM error you're reporting...

**Comment by phw198** [comment]
Issue #263 resolves the no logfile problem. COM exceptions handled much better from v2.6 too.
