### ISSUE TITLE
Unable to cast COM object type/library not registered

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#251]
I've been relying on this application for about a year now (love it!). When I went to dowload the application on my new computer, I received the following error message (screenshot below). 

"Unable to cast COM object of type."...."This operation failed because the QuertyInterface call on the COM component for the interface with IID {00063001-0000-0000-C000-000000000046} failed due to the following error: Library not registerd."

![capture](https://user-images.githubusercontent.com/29711418/27548402-dce69304-5a66-11e7-865e-c33d87ce0bcf.PNG)

Can anyone give me a workaround for this? I am not very tech savvy, but can follow detailed instructions :)

**Comment by phw198** [comment]
Take a look through [this wiki entry](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002801d---type_e_libnotregistered) and see if it helps at all.

**Comment by ghost** [comment]
That worked! Thanks so much Paul; I really love this tool and recommend it
to people all the time.
