### ISSUE TITLE
System.Exception: Remote release File is empty or corrupted

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#255]
Exception occurs frequently (maybe every) 
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1117530/OGcalsync.zip)
boot.

**Comment by phw198** [comment]
Do you see that anywhere other than the log file? If not, it's expected behaviour at the moment...

**Comment by phw198** [comment]
Now we're on fully migrated on to GitHub, the releases file is properly populated and this error should not arise any longer. Even if the error does occur, it should only be seen in the logfile and fail silently.
