### ISSUE TITLE
Com Exception Encountered [0x80080005 CO_E_SERVER_EXEC_FAILURE]

### ISSUE THREAD

**Issue by gearheart89** [phw198/OutlookGoogleCalendarSync#256]
I was starting up the computer when I received an error stating that "COM exception encountered. Please log an issue on CodePlex and upload your OGcalsync.log file."  It brought me to the CodePlex website which appears to be shutting down instead of the git-hub site.  

I am running the Portable version 2.5.0.0 which I obtained from this website less than 1 month ago.  When I try to check for an update in the app it says "Update check failed.  Could not retrieve new version of the application.  Update.exe not found, not a Squirrel-installed app?" followed by another message box that says "No update required.  You are already

![update error](https://user-images.githubusercontent.com/15801983/27828510-2e0c888a-6082-11e7-8866-be1b4dbaedb3.PNG)
 on the latest release"

![error message](https://user-images.githubusercontent.com/15801983/27828393-9a7cab90-6081-11e7-86a3-ce4008a5f81f.PNG)

[OGCalsync Log.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1121873/OGCalsync.Log.zip)

**Comment by phw198** [comment]
Looks like the same as Issue #239. Could you confirm if you have the same event log captured as mentioned on that issue (DCOM event timeout)?

**Comment by gearheart89** [comment]
Yes, it looks the same to me.

**Comment by phw198** [comment]
I've now fixed the "Update Check Failed" popup, which will be included in the next version after v2.5.1.

BTW, I see you're running the app under the directory PortableApps - is this a proper PortableApp.com install, or you've just unzipped OGCS there?

**Comment by gearheart89** [comment]
I've just unzipped OGCS there.
