### ISSUE TITLE
Startup and sync issues - recurrence pattern not valid

### ISSUE THREAD

**Issue by GitManMatt** [phw198/OutlookGoogleCalendarSync#257]
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1121943/OGcalsync.txt)

As per screengrab on G+ - sync issues from Google to Outlook, and then startup issues - not starting at logon. Hope you can help, thanks.

**Comment by phw198** [comment]
I can't see any start-up issue, but the recurrence pattern it's complaining about is `FREQ=MONTHLY;BYDAY=SU,MO,TU,WE,TH,FR,SA;BYSETPOS=-1`. That looks to me like "recur every month on each of the last 7 days of the month"? Is it even possible to have such a recurrence in Outlook as that (I'm not on a computer with Outlook right now)?

**Comment by GitManMatt** [comment]
Hi - it looks like it is a reminder which 'occurs day 28 of every 1 month effective 28/05/16 from 9.30am to 10am' - I have other recurring items but this one seems to be the problematic one. I'll try deleting it, then run it again.

**Comment by GitManMatt** [comment]
Yep, no issues now.

**Comment by GitManMatt** [comment]
Logon issues - getting this message, then OGCS closes
![capture](https://user-images.githubusercontent.com/29891255/27830083-a8dffe04-60bc-11e7-8807-9899be9c1d9b.JPG)

**Comment by GitManMatt** [comment]
oh, just read back that it might be Outlook updating, causing the issue and that you are going to introduced delayed startup at logon - makes sense.

**Comment by phw198** [comment]
I think I've found the bug regarding the `recurrence pattern is not valid.` error - should be included in the next release after v2.5.1
