### ISSUE TITLE
Popup Msg for access to Outlook

### ISSUE THREAD

**Issue by KanKevin** [phw198/OutlookGoogleCalendarSync#260]
Hi, 

This is a great program. An amazing job well done.

However, a popup message that requests for Access to Outlook keeps showing whenever the program is trying to sync the calendars. 

I understand that this is a security feature of Outlook, but it is very (very) irritating - because not only do I have to click "Allow", I also have to select the allow time period in a dropdown box. 

Kindly advise or enhance the program to circumvent this popup message please.

Thank you very much.

Regards,
Kevin Kan

![popup](https://user-images.githubusercontent.com/29894783/27834329-2104cee0-6109-11e7-9bd7-d50d99933bf5.jpg)

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1122353/OGcalsync.txt)

**Comment by m-rm** [comment]
This also happens for me, although not on every sync. I'm using Outlook 2013 32bit.

**Comment by phw198** [comment]
A well known limitation of the Outlook API unfortunately - [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#what-is-this-security-pop-up-i-keep-getting).
