### ISSUE TITLE
Recurring meetings aren't syncing (O -> G)

### ISSUE THREAD

**Issue by OmarGhazi** [phw198/OutlookGoogleCalendarSync#261]
This week none of the recurring items from my outlook calendar is not showing up on my google calendar any longer. I applied the 2.5.0.6 hotfix and that didn't seem to help the issues. Any ideas on what I can do to fix this?

[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1125761/OGcalsync.zip)

**Comment by phw198** [comment]
It's only finding 1 Outlook item in the period 6/30 to 7/20 - I'm guessing this isn't correct?

If not, play with the Outlook date format under OGCS settings until it picks up the right number of items.

**Comment by OmarGhazi** [comment]
I didn't do anything different and it started working 2 days ago randomly.
