### ISSUE TITLE
Deleted reoccuring events reappear in Outlook after syncing 

### ISSUE THREAD

**Issue by dfiord** [phw198/OutlookGoogleCalendarSync#262]
This may be somewhat lengthy, but i will try to keep it brief.

I have three location I am syncing A. my main outlook calendar, B. gmail calendar and C. traveling notebook calendar.  A and B are synced automatically using another syncing tool. B and C are synced using Outlook Google Calendar Sync. The problem occurs when individual dates are deleted from recurring items. i.e., if they are deleted from A they will be deleted from B, but when B is synced to C they are not removed. If they are m=removed from C manually and then B and C are synced the removed entries reappear on calendar C.

I can provide screen shots if you would like or log files. Please let me know what the problem my be.  Thank you.

Original Calendar View:
![image](https://user-images.githubusercontent.com/26313448/27918899-589eac00-623e-11e7-871a-1fc8a4f66009.png)

Calendar View After removing events manually:
![image](https://user-images.githubusercontent.com/26313448/27918931-6d7e5666-623e-11e7-872b-60e6cc41b8b0.png)

Calendar view after syncing Gmail and Outlook using Outlook Google Calendar Sync:
![image](https://user-images.githubusercontent.com/26313448/27918994-87483c10-623e-11e7-94f1-e018d669ea9c.png)

**Comment by phw198** [comment]
I need the logfile really. What version of OGCS was this on? Any difference on the latest alpha?

When you say you manually delete from calendar C, what direction are you then syncing B and C?

**Comment by dfiord** [comment]
Paul,

This is regarding #262.

I have attached the two most recent log files for your review.

I had this problem with ver. 2.5.0.0 and just tested ver. 2.5.1.0 and the same thing happened.

I have manually deleted the data from C because I had originally removed the data from Calendar A and synced to B. The one way sync to C from calendar B did not remove the data from C, therefore I manually deleted it from C.  The sync I am doing is a one way sync from Google calendar B to Outlook calendar C. 

Please let me know if you need any additional information. I would be happy to do a call or screen share with you if that will help.

Thanks you very much for your support.

Don

**Comment by phw198** [comment]
So B had a deletion synced from A and you manually make the same deletion in C. But when you one way sync from B to C the deleted instances of the​ recurrence reappears. What happens if you make the delete manually in B (ie don't use the other sync tool between A and B) - does that sync properly to C. 

Btw, you can't attach logs to the ticket via email.

**Comment by dfiord** [comment]
I actually just tried this. 

I created an event in B and then performed a one way sync to C. It pushed the new event as expected to C. I then tried to delete the event in C and did a sync and it recreated the event in C. I then deleted the event in B and did the sync and it deleted the event correctly.

Do I have to attach the log file manually in GitHub?

**Comment by dfiord** [comment]
Paul,

Here are the two most recent log files.

[OGcalsync-log-2017-06-22.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1143426/OGcalsync-log-2017-06-22.txt)
[OGcalsync-log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1143427/OGcalsync-log.txt)

**Comment by phw198** [comment]
I think that test indicates the sync between A and B is not actually really deleting the recurring instance in B. Not sure what it's doing or how it makes it look like it's deleted, but I'm pretty sure the issue isn't with OGCS...

**Comment by dfiord** [comment]
Hi Paul,

I have done a little more experimenting this morning. 

I am not sure if your previous statement is correct or not, but what I did was to narrow the sync range to 1 day. I then manually deleted the events for that single day and instead of doing a one way sync from B to C I took a chance and did a two way sync between the two.  This seems to have fixed the problem. (I am actually not exactly sure why I selected a one way sync but I did.) It now appears that with the two way sync the events are not recreated.

I then expanded the sync range to 3 days and did the same thing. Same results, the events were not recreated. I then expanded to my normal range and the events were removed.

I am not sure why the one way sync does not work this way, but with the two way sync it does work. 

Thank you very much for your help.  I sincerely appreciate it.  If I can ever help you in the future by testing anything I would be happy to do so.

Sincerely,
Don Fiordelisi

**Comment by phw198** [comment]
Glad you found the workaround :+1: 

Now I've had a chance to look at your log files, I think I know what was happening - you've hit two "features" of Outlook as compared to Google.

You have a recurring appointment "HW Cafe" every Tues and Thurs, but the 22 June was moved to 20 June - the log file shows: `Cannot save this item....Uh oh! Outlook wasn't able to save this recurrence exception! You may have two occurences on the same day, which it doesn't allow.`

This would have caused the main recurring series to keep resyncing (so all the deleted instances reappear), but the exception on 22 June can't save.

The other one is for "--  Haircut - Dolly" which has an end date before the start date - again Outlook fails with this.

By syncing from Outlook to Google, these incompatibilities have been removed and now Google to Outlook works again!
