### ISSUE TITLE
COM issue

### ISSUE THREAD

**Issue by mp1007** [phw198/OutlookGoogleCalendarSync#264]
Uploaded as a text file.

[OGcalsync.log.2017-06-21.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1130888/OGcalsync.log.2017-06-21.txt)

**Comment by phw198** [comment]
I can't see any evidence of a COM error in the log file. Appears you're still running v2.3.6 too, so I'd suggest updating to the latest release.

**Comment by pitaki** [comment]
My #270 is on this very same subject

**Comment by phw198** [comment]
Logfile not catching error is also fixed under issue #263.
