### ISSUE TITLE
Unable to reclaim orphan calendar entries in Outlook calendar

### ISSUE THREAD

**Issue by xraydoc** [phw198/OutlookGoogleCalendarSync#266]
Pleased with program. Was using two way sync without a problem. Realized that I'm better off with a google to icloud(outlook) sync. Now I get errors. Outlook to Google syncs fine. But now two way sync and google to outlook error out.
```
Unable to reclaim orphan calendar entries in Outlook calendar.
The following error was encountered during sync:-
Could not complete the operation. One or more parameter values are not valid.
Operation aborted after 1 failed attempts
```
Cant get log .txt file to attach.

**Comment by phw198** [comment]
:spiral_notepad: [See instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file) for attaching the logfile.

**Comment by xraydoc** [comment]
Uploaded the file to your google drive.

Stephen Swearingen

**Comment by phw198** [comment]
Sorry for the delay in getting back to you! Are you still have the problem after upgrading to v2.6.0? If so, I'll need to provide you a hotfix version with extra logging to try and identify the issue better.

Let me know...

**Comment by Antallica** [comment]
Getting a similar error:
```
Unable to reclaim orphan calendar entries in Outlook calendar.
The following error was encountered during sync:-
Unknown error
Operation aborted after 1 failed attempts!
```

**Comment by phw198** [comment]
@Antallica :spiral_notepad: Please also provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)].

**Comment by Stuwilli1** [comment]
Paul,

Having issue with this ever since the new 2.7s were flying back and forth.  Running 2.7.7.8 now.

Two errors:

1. Unable to reclaim orphan calendar entries in Outlook calendar.e
2. Object reference not set to an instance of an object.

Saying I can't upload Log file type is incorrect, will try something else.


Thanks,

Stuart

**Comment by Stuwilli1** [comment]
Attached File now.

Stuart
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2777554/OGcalsync.txt)

**Comment by phw198** [comment]
@Stuwilli1 This issue is unrelated to the recent builds you are testing. v2.7.7.8 introduced some new bugs which are being worked through on https://github.com/phw198/OutlookGoogleCalendarSync/issues/656#issuecomment-455896165.
