### ISSUE TITLE
Microsoft Outlook Warning on Computer Startup

### ISSUE THREAD

**Issue by andyzxyz** [phw198/OutlookGoogleCalendarSync#269]
I keep on getting the following error message when I log into my desktop:

![microsoft outlook warning](https://user-images.githubusercontent.com/30092807/28093042-98ae994c-668d-11e7-80c3-bca86ef72da8.png)

I click Accept but it pops up everytime that I log in to windows 10, using outlook 2016 desktop version. There is also an error shown in the tray.

![outlook error in tray](https://user-images.githubusercontent.com/30092807/28093172-0f8badb6-668e-11e7-8092-1a43ce7eb725.jpg)

Any advice on getting rid of this?

**Comment by beachmiles** [comment]
Just fixed this today. Start outlook as administrator and go to File -> Options -> Trust Center -> Trust Center Settings -> Programmatic Access  and click on Never warn about suspicious activity.

**Comment by andyzxyz** [comment]
thanks beachmiles

**Comment by phw198** [comment]
Of course, [as per the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#what-is-this-security-pop-up-i-keep-getting) the other preferable option is "Warn...when antivirus is out of date".

Need to figure out a way of driving people to the wiki more...

**Comment by krempshaw** [comment]
I had been getting that message because my work computer requires a specific antivirus, and that antivirus wasn't updating. Once I fixed that, the only time I had a problem was when I was gone for several days and my antivirus was out of date again. I initiated a manual update and things were fine again.

**Comment by phw198** [comment]
v2.5.3 will now try and detect when the security pop-up happens during startup and [point people at the wiki page](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) for further information.
