### ISSUE TITLE
ClickOnce uninstall causing unhandled AggregateException

### ISSUE THREAD

**Issue by pitaki** [phw198/OutlookGoogleCalendarSync#270]
System requested my log-file

**Comment by pitaki** [comment]
Amazed!!!! Without doing anything, I just restarted the sync and this time it went just fine. Could it be a sort of a timing issue? From boot it fails and subsequent attempts are ok???

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file for the period which covers when the error occurred [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)].

**Comment by pitaki** [comment]
As far as I can see, I've done that already.

**Comment by pitaki** [comment]
Yet again. In hard-boot scenario (power off --> back on) this OGCS produced this again

"COM exception encountered. Please log an Issue on GitHub and upload your OGcalsync.log file."

Attached is the log-file requested.
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1154804/OGcalsync.zip)

**Comment by pitaki** [comment]
After time it took me to write the previous comment, something happened again. During my writing, the program was on hold and after I've done writing ... instead of closing the program, I pressed SYNC -button again... and this time it went fine again.

Can that be an issue of timing of some sort?

**Comment by phw198** [comment]
Got your log file this time :wink: which seems to show you getting multiple exceptions in a parallel process that is meant to uninstall the old ClickOnce install (if present). I'll need to knock up a patched version of OGCS to iterate through the exceptions and see what's going on so we can handle it better.

Will look to post something here in the next day or two...

**Comment by phw198** [comment]
:package: This hotfix should now handle the multiple exceptions properly when there's no ClickOnce install to uninstall - [v2.5.2.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1167632/v2.5.2.3.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Please let me know how it goes, though you may only be experiencing this problem following an upgrade to a new alpha...in which case we may have to wait until these changes are rolled in to v2.5.3.
