### ISSUE TITLE
COM exception on first run after install

### ISSUE THREAD

**Issue by turtlecrs8** [phw198/OutlookGoogleCalendarSync#271]
just installed this app and encountered this error upon my first reboot. I'm using the app on my Intel IT work laptop to sync my Google family calendar to Outlook, but not syncing in the opposite direction since that's against company policy.

**Comment by turtlecrs8** [comment]
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1146129/OGcalsync.zip)

**Comment by phw198** [comment]
Thanks for the report and welcome!

I think this is likely related to #263 and may well be fixed from v2.5.1.3. If not at least logging will catch the error, so I'll leave this ticket open for a while in case someone else still has the issue beyond this release.

**Comment by raphsab** [comment]
HI,

Thanks a lot for this work. I was really hoping that something like this would come up!
From my side I couldn't have it work, including with the new release. When starting it, I only see the start splash screen and then get an error message (I wasn't able to get to the Settings screen so far):
> when just double-clicking on it:
![2017-07-17_11-53-29](https://user-images.githubusercontent.com/30035564/28263317-961fe5ca-6ae6-11e7-9c77-6251cffe58cf.jpg)
> when right-click / open as administrator (even if my user is admin already):
![2017-07-17_11-49-09](https://user-images.githubusercontent.com/30035564/28263632-af12d5d2-6ae7-11e7-9158-8281b49757a8.jpg)

Here is the log file:
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1152195/OGcalsync.zip)

Many thanks for your help

**Comment by phw198** [comment]
@raphsab Yours is the same as issue #220. The second error is #268 and to be expected (though should be reported better by OGCS).

**Comment by phw198** [comment]
@turtlecrs8 Could you upgrade to v2.5.2 and see if the issue remains? If it does, the error will now be captured in the logfile, so please upload it again. Thanks

**Comment by turtlecrs8** [comment]
I'm actually not having the issue anymore after the weekend in v2.5.1
