### ISSUE TITLE
COM Exception OUtlook 2016 Windows 10 build 16241

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#272]
[OGcalsync - Copy.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1148719/OGcalsync.-.Copy.log.txt)

**Comment by phw198** [comment]
There's no sign of any error in the log file attached. Is this also a duplicate of [your comment](https://github.com/phw198/OutlookGoogleCalendarSync/issues/268#issuecomment-314558911) in #268?

If it only happens on startup, I suspect the issue you're after is #263.

**Comment by dutch55** [comment]
Only happens at startup. I suspect it is the same issue.

Thanks for looking at it.

Harry

**Comment by phw198** [comment]
Just a thought - could you check your `Control Panel > Uninstall a Program` and see if there is more than one entry for OGCS?

**Comment by dutch55** [comment]
Only 1 instance installed.

Harry

**Comment by phw198** [comment]
FYI, a possible hotfix has now been uploaded to #263.
