### ISSUE TITLE
Com exception encountered after upgrade to 2.5.2

### ISSUE THREAD

**Issue by hms-malta** [phw198/OutlookGoogleCalendarSync#273]
On first run after upgrade got this error. This was also happening daily on reboot with previous versions

[OGcalsync log.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1151700/OGcalsync.log.zip)

**Comment by phw198** [comment]
You need to set a delay on the "Start on login" option in OGCS.

Enhancement #263 will also look to handle this error a bit more elegantly :wink:

**Comment by phw198** [comment]
Hotfix now posted on #263.
