### ISSUE TITLE
How to remove!!!

### ISSUE THREAD

**Issue by steveternes** [phw198/OutlookGoogleCalendarSync#274]
I cant remove it, getting very embarrasing how this program is hijacking my calendar and sending to dsitrubtion lists all over my work.  Something needs to be fixed.  I uninstaleld the software, but something isnt right

**Comment by phw198** [comment]
OGCS doesn't send email, though there is a [bug/feature of Google](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google) where they might start doing that.  
[Uninstall info](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Uninstall) can be found in the wiki.

_[Linking to Issue #197]_
