### ISSUE TITLE
Can't get Google Calendar - corrupt settings.xml file

### ISSUE THREAD

**Issue by RRobaina** [phw198/OutlookGoogleCalendarSync#276]
Unable to get the list of Google calendars. The following error occurred:
'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
Unable to get the list of Google calendars. The following error occurred:
Object reference not set to an instance of an object.

Checked that Internet is working and I can see my Google calendar ok.

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by RRobaina** [comment]
Moved logfile c&p to [gist](https://gist.github.com/phw198/3ee5558e65fc68f510ce9e2e0fb22ec5).

**Comment by phw198** [comment]
Can you check the contents of the following file (eg in Notepad) and see if it's empty:
`C:\Users\rene\AppData\Roaming\Outlook Google Calendar Sync\settings.xml`

If it is, can you close OGCS, delete the file entirely and restart OGCS.

**Comment by RRobaina** [comment]
That worked.  Thanks!

**Comment by phw198** [comment]
Reopening to handle this error better.

**Comment by phw198** [comment]
:package: This should now be resolved with hotfix [v2.5.2.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1167609/v2.5.2.2.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].
