### ISSUE TITLE
Com exception encountered [0x800706BA] (RPC server is unavailable)

### ISSUE THREAD

**Issue by Lunarmanpl** [phw198/OutlookGoogleCalendarSync#278]
Hi

Today morning I had for first time com exception error:

2017-07-21 07:06:34,964 ERROR 1 OutlookGoogleCalendarSync.OGCSexception [0] - System.Runtime.InteropServices.COMException: Operacja przerwana. (Wyjątek od HRESULT: 0x80004004 (E_ABORT))
2017-07-21 07:06:34,964 ERROR 1 OutlookGoogleCalendarSync.OGCSexception [0] - Code: 0x80004004;-2147467260

Also I notice that program often hangs outlook on windows start up (auto start on system start) and OGCS also crash or just don't start. I have to manually run outlook and then OGCS.
Outlook 2007, OGCS 2.5.1.0

**Comment by Lunarmanpl** [comment]
[OGcalsync.log.2017-07-21.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1168842/OGcalsync.log.2017-07-21.txt)

That hotfix (2.5.2.1) helped with startup issue for now, thx :)

**Comment by Lunarmanpl** [comment]
Today I hade the same problem when OGCS autostart (using 2.5.2.1). Outlook not responding, OGCS don't start, I hade to manually run Outlook then OGCS.

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1182099/OGcalsync.txt)

**Comment by phw198** [comment]
I can't see that you've set a startup delay for OGCS? It's a new setting in OGCS next to `Startup on login`...

:package: I've made further enhancements in this area anyway, so please try [v2.5.2.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1186039/v2.5.2.10.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Let me know how it goes.

**Comment by Lunarmanpl** [comment]
I tested 2.5.2.10 with 60second delay. There is something wrong with this version.
If I don't have outlook in background working, everytime that i run OGCS (doesn't matter if automaticaly on start up or manualy) outlook is starting normally but OGCS trow error: "Could not establish a connection with Outlook"
If I have outlook running in background OGCS start normally and it works.
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1186499/OGcalsync.log.txt)

**Comment by phw198** [comment]
Thanks @Lunarmanpl 

:package: Does [v2.5.2.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1189067/v2.5.2.11.zip) fare any better?

**Comment by Lunarmanpl** [comment]
For now it's working fine with 60seconds delay (5-6 windows restarts so far).
Do You need any other test with it?

**Comment by phw198** [comment]
The permutations on ways in which people can start Outlook and OGCS seem infinite 😉 but if you could post you logfile for the restarts, I'd be interested to see exactly what was happening.

**Comment by Lunarmanpl** [comment]
Logs from last two days and today morning:
[OGcalsync.log.2017-08-01.1.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1196037/OGcalsync.log.2017-08-01.1.txt)
[OGcalsync.log.2017-08-01.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1196039/OGcalsync.log.2017-08-01.txt)
[OGcalsync.log.2017-08-02.1.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1196038/OGcalsync.log.2017-08-02.1.txt)
[OGcalsync.log.2017-08-02.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1196040/OGcalsync.log.2017-08-02.txt)
[OGcalsync.log.2017-08-03.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1196051/OGcalsync.log.2017-08-03.txt)

If You need more restarts with specific config or something, just let me know;)

**Comment by Lunarmanpl** [comment]
One more thing that I notice. Before updates (2.5.2.0) outlook when start was asking once per restart to allow OGCS to check things, now (2.5.2.11) when outlook start it ask for it few times in a row (today 4 times)

**Comment by phw198** [comment]
Thanks @Lunarmanpl. The repeated security pop-up will be unavoidable expected behaviour if [Outlook security settings are not configured](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) to avoid this. As OGCS is now repeatedly checking if Outlook is available to connect to, you'll get a pop-up each time it tries :disappointed: v2.5.2 and before gave up much more quickly when Outlook was busy.

By setting a longer delay on startup you should be able to largely avoid the multiple connection attempts whilst Outlook is busy inspecting its navel. Your logfile on 3 Aug with a 60s delay only seems to show 1 pop-up occurring?

**Comment by Lunarmanpl** [comment]
I have 60s delay all the time and sometimes its only 1 notice, sometimes 3-4 and today 0 :)

Thx for help :)
