### ISSUE TITLE
Upgraded Outlook to 2010, now have "The recurrence pattern is not valid." error

### ISSUE THREAD

**Issue by ABrannen** [phw198/OutlookGoogleCalendarSync#279]
[OGcalsync .txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1167082/OGcalsync.txt)

Upgraded from 2007 to 2010 and sync has failed with the  "The recurrence pattern is not valid." error since.

**Comment by phw198** [comment]
This is a strange one.

The recurrence code for the problematic `9/9/2017 (R) => "Mom & Dad's anniversary"` is `RRULE:FREQ=YEARLY;INTERVAL=1`. On MS documentation for 2007, it says:
> Also, the Interval property is not valid for yearly recurrence patterns.

My reading of the situation is:
1. You created yearly recurring event in Outlook
1. OGCS synced it to Google with `RRULE:FREQ=YEARLY;INTERVAL=1`
1. Syncing to Outlook 2007, interval was ignored. (This must be true else syncing yearly events to Outlook would never have worked for anyone on 2007).
1. Having upgraded to Outlook 2010, the interval attribute is in an "odd" state, and when OGCS tries to set it, it fails. I think the object is still half a 2007 one! :confounded:

Solutions:
- [x] Don't sync `INTERVAL=1` to Google for annual events - this is the default anyway, so doesn't need explicitly stating. Although I've updated the code, this won't help you with the already synced event.
- [ ] You open the Google event, make a trivial edit (eg change description slightly), save and then resync. (This has Google remove the `INTERVAL=1` bit for you.

Let me know if the last part works for you. If not, I'll to provide a version of OGCS with some extra logging to work out what the Outlook attributes are for this event.

**Comment by ABrannen** [comment]
Modifying it as stated didn't work, so I went ahead and deleted this event entirely from both Outlook and Google and I still receive the error.  It looks like it is now stuck on another with the same attribute. 
[OGcalsync (2).txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1168272/OGcalsync.2.txt)

**Comment by phw198** [comment]
OK, looks like you have lots of items affected by this.

:package: Could you apply [v2.5.2.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1168354/v2.5.2.6.zip), set the logging level to `FINE`, retry a sync and then upload your logfile again? See [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix).

Thanks

**Comment by ABrannen** [comment]
This patch appears to have solved the issue, it is synching successfully.
[OGcalsync (3).txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1168386/OGcalsync.3.txt)

**Comment by phw198** [comment]
Well that was a little unexpected! Glad we got it solved.
