### ISSUE TITLE
Event creation failed: String cannot be of zero length 

### ISSUE THREAD

**Issue by FilipRot** [phw198/OutlookGoogleCalendarSync#280]
Creating 1 Google calendar entries...
30-07-2017 13:00 => "Event Name xxxxxxxxxx"
WARNING: Event creation failed.
String cannot be of zero length.
Parameter name: oldValue
Operation aborted after 1 failed attempts!
Another sync has been scheduled to automatically run in 5 minutes time.

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]
