### ISSUE TITLE
Com exception encountered [0x80080005] (CO_E_SERVER_EXEC_FAILURE)

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#283]
This occured after reboot. I just installed Windows 10 Preview 16251.  I use Norton Security (the version provided through my ISP, Comcast).  I was suspicious the anti malware features having been causing problems, but while I had the Norton firewall enabled, the antivirus was disabled (I had disabled it wile the Windows 10 install process was going on).

[OGcalsync (2).txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1180421/OGcalsync.2.txt)

**Comment by phw198** [comment]
Still looks like issue #263 - could you try hotfix v2.5.2.9 posted there and set a delay for OGCS on startup (there is a new setting next to the "Start on login" checkbox).

**Comment by phw198** [comment]
Duplicate of issue #268. Should also be resolved in v2.5.3.
