### ISSUE TITLE
.net framework error while sync

### ISSUE THREAD

**Issue by Lunarmanpl** [phw198/OutlookGoogleCalendarSync#284]
Hi. Today I hade framework error while trying to sync:

************** Tekst wyjątku **************
DotNetOpenAuth.Messaging.ProtocolException: Web request to 'https://accounts.google.com/o/oauth2/token' failed. ---> System.Net.WebException: Połączenie podstawowe zostało zakończone: Wystąpił nieoczekiwany błąd przy wysyłaniu. ---> System.IO.IOException: Uwierzytelnianie nie powiodło się, ponieważ strona zdalna zamknęła strumień transportowy.
   w System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   w System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   w System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   w System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   w System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   w System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   w System.Net.TlsStream.CallProcessAuthentication(Object state)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   w System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   w System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   w System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   w System.Net.HttpWebRequest.GetRequestStream()
   w DotNetOpenAuth.Messaging.StandardWebRequestHandler.GetRequestStreamCore(HttpWebRequest request)
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w OutlookGoogleCalendarSync.OGCSexception.AnalyseDotNetOpenAuth(ProtocolException ex)
   w OutlookGoogleCalendarSync.GoogleCalendar.UserSubscriptionCheck()
   w OutlookGoogleCalendarSync.GoogleCalendar.get_Instance()
   w OutlookGoogleCalendarSync.Social.TrackSync()
   w OutlookGoogleCalendarSync.MainForm.sync_Start(Boolean updateSyncSchedule)
   w OutlookGoogleCalendarSync.MainForm.Sync_Requested(Object sender, EventArgs e)
   w OutlookGoogleCalendarSync.NotificationTray.syncItem_Click(Object sender, EventArgs e)
   w System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   w System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   w System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   w System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   w System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   w System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   w System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   w System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   w System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   w System.Windows.Forms.ToolStrip.WndProc(Message& m)
   w System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by phw198** [comment]
Do you have the `OGcalsync.log` file for the same time that this error occurred? I take it OGCS crashed right out?

**Comment by phw198** [comment]
DotNetOpenAuth is no longer used from v2.6.1
