### ISSUE TITLE
Outlook Google Calendar Sync start-up issue

### ISSUE THREAD

**Issue by Sunilhdhaduk** [phw198/OutlookGoogleCalendarSync#285]
I have to restart Outlook Google Calendar Sync and Outlook application to sync both the app properly.
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1195998/OGcalsync.txt)

**Comment by phw198** [comment]
Please could you upgrade to the latest alpha release and then apply the nightly build [v2.5.2.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1195569/v2.5.2.12.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

**Comment by Sunilhdhaduk** [comment]
Hi Paul,

Thanks for new update…

Regards,

Sunil Dhaduk

**Comment by phw198** [comment]
@Sunilhdhaduk I take it the nightly build release is working better and resolved your issue?

**Comment by Sunilhdhaduk** [comment]
Hi Paul,

I didn’t face any issue with OGCS that you forwarded.

Will let you know if any issue will be found.

Regards,
Sunil Dhaduk
