### ISSUE TITLE
Starting OGCS fails [0x80029C4A]

### ISSUE THREAD

**Issue by LesegoT** [phw198/OutlookGoogleCalendarSync#288]
My OGCS started failing on startup I suspect after updating Office 365. I have followed the link in the wiki to locate the CLID, but there is no TypeLib folder under {00063001-0000-0000-C000-000000000046}, so I could not follow the rest of the instructions. Anything else I can try?

**Comment by phw198** [comment]
I think the link in the wiki for `0x80029C4A` may well be wrong!

Can you navigate through to `HKEY_CLASSES_ROOT\TypeLib\{00062FFF-0000-0000-C000-000000000046}\9.6\0\Win64` in your registry and check the path to your `MSOUTL.OLB` file - is this actually correct? Note, 9.6 is for 64-bit Outlook 2016, so your values may differ.

If not, search your office directory (eg `C:\Program Files\Microsoft Office`) for `MSOUTL.OLB` and then try running `regtlib msoutl.olb` against it in a `cmd` window to re-register it properly.

**Comment by LesegoT** [comment]
I solved the problem by running an online repair of my Office 365 installation, and it is now working like a charm again.

**Comment by pierricklidia** [comment]
Got exactly the same issue.
I tried everything :
- All regedit hacks described in OGCS official support / https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary
- Repair Office 365
- Reinstall Office 365

OGCS is still not working ... :(
Please help me !
