### ISSUE TITLE
Outlook Google Calendar Sync wont open

### ISSUE THREAD

**Issue by 68cobrajet** [phw198/OutlookGoogleCalendarSync#290]
Newest problem is the splash screen pops up then disappears and program doesn't open.
Windows 10 64 bit.
Also when I try to download the latest version Norton tells me the setup file has a virus. If I download the zip file when i extract it Norton takes out teh Outlook Google Calendar Sync.exe file sayign it is infected with a virus. If i exclude it from Norton scans windows says it is unsafe and wont run it.

PLEASE, what do I do. I need the program!

**Comment by phw198** [comment]
:spiral_notepad: Could you provide your OGcalsync.log file for when the splash displays and then disappears? [[See instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

However, it does sound like Norton is stopping it from running properly. You could try [submitting the executable to Norton/Symantec for whitelisting](https://support.norton.com/sp/en/uk/home/current/solutions/kb20100222230832EN_EndUserProfile_en_us), though it's odd you're saying that Windows is also blocking it if you exclude the file from Norton scans.

Could you provide a screenshot of the Windows alert?

**Comment by 68cobrajet** [comment]
I installed the 2.6.0.0 update and it now works. I don’t know why it let me install that one but the previous one was stopped.

I have had intermittent problems with it opening for months. Let’s hope this version has solved that.

Thanks
