### ISSUE TITLE
"Unable to Cast COM Object of type ...." error on launch [0x80004002] (E_NOINTERFACE)

### ISSUE THREAD

**Issue by proudot** [phw198/OutlookGoogleCalendarSync#291]
Hi there,  I am having the following errors for a few weeks. 

http://imgur.com/a/tMqL6

It happens with 2.4, 2.5 and 2.6. Any idea ?

Edit: title for error number

**Comment by phw198** [comment]
Is this an error on launch of OGCS, or on start of a sync?

:spiral_notepad: Could you upload your OGcalsync.log file from v2.6 [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

:thought_balloon: Had a similar error under issue #51, but the fix for this was rolled in to v2.3.3

**Comment by proudot** [comment]
It is on launch. The app does not got past the splash screen.
Here is the log https://gist.github.com/proudot/2243ec63c6424244b7abd14b31be3d04

**Comment by phw198** [comment]
As per this [MS article](https://support.microsoft.com/en-us/help/2827747/missing-registry-information-can-cause-problems-with-the-outlook-objec), please run an Office repair.

**Comment by proudot** [comment]
That did the trick ! Thank you so much for the fast help!

**Comment by JorisDebonnet** [comment]
I guess the application could catch the error, in order to suggest this fix :)

**Comment by tripartio** [comment]
Same problem here (error on launch, , but the fix didn't work for me:
* I tried the "light" Office repair, and it made no difference. Exactly same bug.
* I tried the "full" Office repair, and it completely uninstalled Microsoft Office (which is not at all what I expected). After reinstalling Office, no difference; exactly same bug.

Please note that I use Office 365, which installs Outlook 2016. On my office computer with Outlook 2016, OGCS works just fine.

Note that I've even tried version 2.6.1.0 alpha, and the same problem exists.

**Comment by tripartio** [comment]
By the way, I'm sorry that my first contact is a complaint. In fact, on my office computer, OCGS works pretty well and I'm really grateful for the great work you've done.

**Comment by phw198** [comment]
No worries @Tripartio :-)

:spiral_notepad: Could you provide your OGcalsync.log file so I can verify you are seeing exactly this issue ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)). Thanks.

**Comment by Tripartio** [comment]
Hi Paul,

Thanks for the response. Here's the secret gist URL:
https://gist.github.com/Tripartio/27c77d20e10b3ba88fb75318646b3e29

I'll continue on the public issue page: 
https://github.com/phw198/OutlookGoogleCalendarSync/issues/291#issuecomment-324743770

Regards,
Chitu

------------------------------------------------------------------------
*De :* Paul <notifications@github.com>
*Envoyé :* Thursday, Aug 24, 2017 10:11:29 PM GMT+0200
*À :* phw198/OutlookGoogleCalendarSync 
<OutlookGoogleCalendarSync@noreply.github.com>
*Cc:* Chitu Okoli <chitu@okoli.org>, Mention <mention@noreply.github.com>
*Objet :* [phw198/OutlookGoogleCalendarSync] "Unable to Cast COM Object 
of type ...." error on launch [0x80004002] (E_NOINTERFACE) (#291)

**Comment by tripartio** [comment]
Thanks for the response. I've sent you the URL for the secret gist in a separate e-mail response.

Please note that the error on Line 65 in French is identical to the imgur error message in the initial post above, except that the very last phrase in my case has a different HRESULT exception number: 0x80040155.

I'd appreciate any help, since I would love to get this working on my laptop.

**Comment by phw198** [comment]
@JorisDebonnet Yes, it's a juggle between tracking all the various COM issues in the wiki and then coding the fix/suggested solution into the app. But I've added this one in to the app now - available after v2.6.1.

@Tripartio Your error is actually a `0x80040155`, which is tracked under #220. Suggest you try the solutions mentioned in the opening post before going through the fairly length ticket! Please post further updates on #220.

**Comment by tripartio** [comment]
OK, I'll continue on #220 ....
