### ISSUE TITLE
Error after recent update - missing Google DLL?

### ISSUE THREAD

**Issue by Bidthedog** [phw198/OutlookGoogleCalendarSync#293]
Hey there,

Thanks for this little tool, I've been using it for some time. Recent upgrade is now producing the following error on sync:
```
Sync started at 15/08/2017 07:26:20
Syncing from 08/08/2017 to 15/10/2017
Outlook ← Google
--------------------------------------------------
WARNING: Problem encountered during synchronisation.
Could not load file or assembly 'Google.Apis.Authentication.OAuth2, Version=1.2.4573.23243, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```
Going to reinstall, but thought you should know!

**Comment by phw198** [comment]
That's odd, as plenty of people are upgrading OK. Hopefully a reinstall will fix it.

Can you confirm the following file actually exists: `%LOCALAPPDATA%\OutlookGoogleCalendarSync\app-2.6.0-beta\Google.Apis.Authentication.OAuth2.dll`

**Comment by Bidthedog** [comment]
I can confirm that a reinstall rectified it. That file does exist now, not sure before, apologies.

**Comment by phw198** [comment]
OK, thanks for getting back to me.

**Comment by fabstar81** [comment]
I'm experiencing the same issue. Don't necessarily want to reinstall, so i first confirmed that the dll exists in mentioned folder. Is there another fix besides reinstalling?
