### ISSUE TITLE
Anti Virus false positive

### ISSUE THREAD

**Issue by cjlowe** [phw198/OutlookGoogleCalendarSync#295]
**Issue Summary** by @phw198

Without signing OGCS with a certificate to help prove its authenticity, anti-virus software is [much more likely](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/application-signing.md) to falsely identify it as a virus.

[Code-signing certificates](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate) cost around $111 USD/year, so if you would like to [support this and donate](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RT46CXQDSSYWJ&item_name=Outlook%20Google%20Calendar%20Sync%20donation%20for%20code-signing%20certificate), please mention it is intended to go towards a certificate.

Meanwhile, see the wiki on [reporting false positives](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#anti-virus-false-positives).

Update April 2018:
- [x] Certificate purchased
- [x] Certificate request submitted
- [x] Obtain certificate
- [x] Sign OGCS binaries

------
Hi, I'm sure it's false positive, but my anti virus is blocking installation due to: Heur.AdvML.B

This is not s specific virus detection but according to symantec:
Heur.AdvML.B is a heuristic detection designed to generically detect malicious files using advanced machine learning technology. A file detected by this detection name is deemed by Symantec to pose a risk to users and is therefore blocked from accessing the computer.

**Comment by JorisDebonnet** [comment]
BitDefender has also blocked installation of 2.6.0 beta, so this looks like a serious issue. It only says it contains "malware", can't find more information...

**Comment by JorisDebonnet** [comment]
Hm, turns out that 2.5.3 alpha has the same issue... Bitdefender keeps proudly telling me it succesfully removed the malware. Not sure whether an older version does still work, guess I'll have to try test that later...

It may be related to ClickOnceToSquirrelMigrator, since that's a dll Bitdefender blocks. On 2.6.0, it just blocks the general .exe though.

**Comment by phw198** [comment]
Yeah, over-zealous AV definitely is a serious problem :roll_eyes: 

I could [start code-signing OGCS](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate), but the certificate costs $111/year and I'm not completely sure if that will stop things like BitDefender taking exception to pre-built DLLs such as ClickOnceToSquirrelMigrator which isn't my code.

Meanwhile, users are more than welcome to [report the false positives](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#anti-virus-false-positives) to which ever AV software they use.

**Comment by JorisDebonnet** [comment]
I have reported the issue at Bitdefender's site, and was able to whitelist the application via its local settings. Not obvious to find though. Perhaps we need a wiki FAQ about how to whitelist, too :D

**Comment by phw198** [comment]
[Wiki section for AV false positives](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#anti-virus-false-positives) was added a while back now.

Will keep this ticket open to consider purchasing a code-signing certificate for OGCS.

**Comment by jetersen** [comment]
Even after signed it is still triggering defender
![image](https://user-images.githubusercontent.com/1661688/38993238-5329f4dc-43e3-11e8-9bbd-27db92055f95.png)
