### ISSUE TITLE
Recurrence issue if "End after" option is used to define number of occurrences

### ISSUE THREAD

**Issue by towncrier1776** [phw198/OutlookGoogleCalendarSync#297]
I have noticed that if I define a calendar entry with "Recurrence" and use the "End after:" option to define the range of recurrence, the last calendar entry in my Outlook 365 calendar is not synced with my Google calendar. My example was an event that occurred on Monday, Wednesday, and Friday that was set to end after 3 occurrences. The Monday and Wednesday calendar entries show up fine in Google, but the Friday entry is missing. If I change the option to "End by:" and select the day after Friday, then that calendar entry syncs correctly. I loaded beta version 2.6.0.0 and the problem is still present.

**Comment by limaking** [comment]
I have also just discovered this issue.  Had not noticed any issue with recurring meetings previous to this week, and on the Outlook calendar I'm synching to my Google calendar (one way synch) I have had several series of recurring meetings for the last ~5 weeks and didn't have any issues with them...so this seems new. 

I did some test meetings in my Outlook calendar to see what was really happening and captured a log file and pics (attached).
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1252899/OGcalsync.log.txt)
![outlook recurring mtgs short 1 day in gcal after synch](https://user-images.githubusercontent.com/31357015/29730790-999de5d4-8996-11e7-9495-e6524ef342b5.jpg)

**Comment by phw198** [comment]
I can't replicate this issue, either by selecting "End after" or "End by".

@limaking You're running v2.5.0 anyway, so please upgrade to at least 2.6.0, if not 2.6.1.

**Comment by towncrier1776** [comment]
To replicate the issue, create an Outlook meeting which occurs on Monday,
Wednesday, and Friday, then select the option to end after 3 occurrences.
In my case, the Friday meeting does not appear in my Google calendar unless
I change the Outlook meeting to end after Saturday of that week.

**Comment by phw198** [comment]
@towncrier1776 Yes that's exactly what I did and it works fine for me. I'm on Outlook 2016 - what version are you on?

**Comment by towncrier1776** [comment]
Microsoft Office Professional Plus 2016

**Comment by towncrier1776** [comment]
I am running version 2.5.0.0 of Outlook Google Calendar Sync - According to
the application, it is the most recent version.

Since I know a workaround, it is not a huge issue for me.

John Hayes

**Comment by limaking** [comment]
Hello, (if you want me to create a separate issue/post, let me know) I upgraded from 2.5.0 to 2.6.0 OGCS and I'm still seeing the problem.  I'm using MS Outlook 2016 MSO 16.0.7726.1049 32 bit, part of Office 365 ProPlus one-way push to Google Calendar accessing through Chrome.  Here are the latest log files with test recurring meetings.  Whether I pick end after # of occurrences or End By x date, the last meeting in the series won't show up in Google Calendar.  So it sounds slightly different from towncrier1776 symptoms...?  
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1257644/OGcalsync.log.txt)
![ogcs 260 ver test last mtg missing still](https://user-images.githubusercontent.com/31357015/29784932-ab866398-8bda-11e7-8808-b2e7c4059ae9.jpg)

**Comment by towncrier1776** [comment]
I see the same behavior. My workaround is to set the end after date to one
day past the last insurance. I think we are having the same issue.

**Comment by limaking** [comment]
Unfortunately, for many of my Outlook recurring meetings, I am not the host / meeting creator, so I can't use that workaround for those meetings.  Yes, it sounds like we are having the same problem.

**Comment by TARALIST** [comment]
I am having the same issue.  I have an event that repeats M-F for 8 occurrences (I have tried 8 and an end by date). The last date won't show up.

Just tried your workaround and it did work, but is there a way to know if/when it is fixed? As others stated, when its a meeting involving others this will be more difficult.

**Comment by phw198** [comment]
I can't fix the issue until I can replicate it. Are you guys all in non GMT timezones?

**Comment by TARALIST** [comment]
I'm not sure about non GMT. I'm in NY state, EST.

**Comment by limaking** [comment]
I am in the PST timezone, northern California.  I can be available to meet on Skype or Zoom or some other online meeting sw that allows screen share if that would be helpful.  Also, if you need more system details or log files, let me know. Thanks!

**Comment by TARALIST** [comment]
I can do system details or logs. Not sure if I could do Skype or zoom since
it's on my work computer.

**Comment by phw198** [comment]
Thanks for the offers @limaking and @TARALIST. However, my hunch was right, this is affecting users in timezones outside of GMT/UTC.

:package: This should now be resolved with [hotfix v2.6.1.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1289703/v2.6.1.7.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Please let me know how it goes.

**Comment by phw198** [comment]
Any update on if this is fixed for you? BTW, v2.6.2 is released with this fix now too.

**Comment by towncrier1776** [comment]
The patch seemed to fix the problem.

**Comment by limaking** [comment]
I updated to v2.6.2 and it does look like the issue has been resolved.  Yay! Thanks for taking care of this!!!
