### ISSUE TITLE
COM exception encountered. Please log an issue....

### ISSUE THREAD

**Issue by deepgreens** [phw198/OutlookGoogleCalendarSync#298]
This error occurs every time I start my PC and open up Outlook. OGCS spits out this error and closes. When I restart OGCS, it works just fine until the next day, when I open up Outlook again. It's been happening for months now throughout multiple releases.

Logs and screenshot attached. 

Great app, by the way!

![image](https://user-images.githubusercontent.com/4162633/29414207-f9ba3e38-832c-11e7-95e2-d390c013f210.png)

[OGcalsync.log.2017-08-14.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1231346/OGcalsync.log.2017-08-14.zip)

**Comment by phw198** [comment]
It looks like you have both v2.5 and v2.6 installed - could you go in to Control Panel and see if you have two series for OGCS? If so, uninstall v2.5.

**Comment by deepgreens** [comment]
Good catch! I removed the 2.5 version. OGCS gave me another error for a few days (I only start it up in the morning at work) but it started perfectly today. The most recent error was due to some other plugins starting slowly and holding OGCS up. All is well. Thanks again for your help.

**Comment by phw198** [comment]
You can also set a delayed start-up for OGCS in v2.6 - that should help if Outlook takes a while to get going.
