### ISSUE TITLE
Display of some options in Settings -> Sync Options cutoff with larger Windows text size

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#30]
I normally use my Windows 7 system with the default text size setting set to
125% (in Control Panel -&gt; Display -&gt; Make it easier to read what's on
your screen (and/or "Set custom text size (DPI)"  
  
Most of Outlook Google Calendar Sync works just fine in this mode, but I
noticed that some of the settings are getting cut off with this larger DPI
choice.  
  
When I temporarily reset the DPI / default font size to 100%, the options all
display normally with nothing cutoff.  
  
I've attached two screen shots showing the difference between "100%" and
"125%" setting.  
  
This is not a "show stopper" but definitely limits users who use a larger
setting.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 230](http://outlookgooglecalendarsync.codeplex.com/workitem/230)
**Status:**	Resolved
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Apr 6, 2016 at 11:12 PM
**Reported by:**	dgstangel
**Updated on:**	Jun 14, 2016 at 4:21 PM
**Updated by:**	dgstangel

#### Binary Attachments

[ogcs_100pct.png](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=230&FileAttachmentId=1560913)[ogcs_125pct.png](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=230&FileAttachmentId=1560914)[OutlookGoogleCalendarSync.exe](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=230&FileAttachmentId=1575904)

**Comment by phw198** [comment]
On *2016-04-07 06:13:34 UTC*, **dgstangel** commented:

The other screenshot

**Comment by phw198** [comment]
On *2016-04-24 05:29:55 UTC*, **phw198** commented:

Hi @dgstangel 

I have to admit I've not tested this (as changing the text display size requires logging out!), but could you give the attached hotfix v2.2.0.4 a go and let me know if it's done the trick? Could you also click the "Rules" button to check it expands
 enough to show the whole table? 

Thanks!

**Comment by phw198** [comment]
On *2016-04-27 22:56:04 UTC*, **dgstangel** commented:

Hi @phw198 - Sorry for the delay. I just tried running the hotfix you attached, but it crashes immediately with an "OutlookGoogleCalendarSync has stopped working" message. Perhaps the executable was corrupted or something?

Thanks,
Dan

**Comment by phw198** [comment]
On *2016-04-28 04:54:25 UTC*, **phw198** commented:

Hi Dan,
The hotfix is not a standalone executable - it needs to replace the installed/unzipped executable (depending on whether you are using ClickOnce or the portable zip). Done further instructions are under the

Documentation tab.

HTH,
Paul

**Comment by phw198** [comment]
On *2016-05-05 06:14:47 UTC*, **phw198** commented:

Any luck copying the hotfix over the existing executable?

**Comment by phw198** [comment]
On *2016-05-31 21:52:51 UTC*, **phw198** commented:

Previous hotfix did not actually resolve the problem. The new hotfix v2.2.1.3 now does (as well as other display fixes not mentioned).

**Comment by phw198** [comment]
On *2016-06-14 23:21:47 UTC*, **dgstangel** commented:

Hi! Sorry for the delay, but I did just confirm that the new hotfix v2.2.1.3 does fix the Settings issue. Thanks!!

**Comment by NicodemPL** [comment]
Using 2.7.0 beta - got same issues with options page.
