### ISSUE TITLE
Appointment update failed

### ISSUE THREAD

**Issue by GeoffC-Au** [phw198/OutlookGoogleCalendarSync#301]
'WARNING: Appointment update failed.
The recurrence pattern is not valid.'
The Outlook appointment is scheduled specifying 'Last day of month'

**Comment by phw198** [comment]
What version of OGCS are you running? Pretty sure this was fixed in the latest release. If you're on v2.6, what direction are you syncing in? Outlook to Google?

**Comment by GeoffC-Au** [comment]
I’m on Version 2.6

Syncing Outlook --> Google

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file so I can investigate further [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by GeoffC-Au** [comment]
Latest log attached

**Comment by phw198** [comment]
Unfortunately, file can't be attached via email responses - can you sign in to GitHub to upload it?

**Comment by GeoffC-Au** [comment]
https://gist.github.com/phw198/1c4715e53a58a8fb089c676fd82d924d
