### ISSUE TITLE
OGCS does not see my Outlook exchange calendar

### ISSUE THREAD

**Issue by cincidavej** [phw198/OutlookGoogleCalendarSync#302]
Hi,
I can't seem to get OGCS to see my Outlook calendar when I try to select it to synchronize. It's a work calendar set up through Microsoft exchange. It's neither the default calendar nor any of the alternate calendars. 
Do I need to do something in Outlook to make that calendar visible to OGCS? 
Thanks very much,
dave

**Comment by phw198** [comment]
So the calendar is another Calendar folder somewhere within your Default Mailbox? It should just be listed in the dropdown next to "Select Calendar". If not, please provide your OGcalsync.log file so I can investigate further [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)].

**Comment by cincidavej** [comment]
I apologize, but I found another program to do this task so i stopped trying to debug OGCS. I will close this thread. Thank you.
