### ISSUE TITLE
(401) Unauthorized When Retrieving Calendars

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#303]
I am attempting to retrieve my Google calendars for syncing, but I keep getting an error: "The remote server returned an error: (401) Unauthorized."

I've attached my OGcalsync.log
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1242936/OGcalsync.txt)

And the error popup that I am seeing.
![error](https://user-images.githubusercontent.com/2463981/29580590-8c5de08a-8744-11e7-877e-80483d41f94e.png)

After I click OK for the error, it asks me to check if I can access the internet with IE (I can). I am also able to log into my Google Calendar site without any issues.

**Comment by ghost** [comment]
It seems to be resolved with 2.6.1. I am now syncing without issues.

**Comment by phw198** [comment]
Ah great! I was hoping v2.6.1 would fix this but hadn't got round to updating the ticket yet.
