### ISSUE TITLE
Error after updating to 2.6.1 - System.Net.Http.Primitives

### ISSUE THREAD

**Issue by LHuisingh** [phw198/OutlookGoogleCalendarSync#305]
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1247396/OGcalsync.log.txt)
I downloaded the zip version of OGCS 2.6.1.  I had previously been using 2.5.2.  I just copied the files into a new folder and ran that version.  It had errors connecting to Google.  I tried disconnecting my Google account but got an unhandled exception.  I then tried reconnecting to my account but nothing happened.  I haven't captured the error message but I have included my log file.  I am running behind a corporate firewall.

**Comment by TheJacksonian** [comment]
I got the same issue, so I reverted to 2.6.0, 
When I went to disconnect the google account and unhandled exception occured, I can send that text to you if you need.

**Comment by konzertnr9** [comment]
`Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by phw198** [comment]
Thanks guys. Could you apply the updated [OutlookGoogleCalendarSync.exe.config](https://github.com/phw198/OutlookGoogleCalendarSync/files/1248158/OutlookGoogleCalendarSync.exe.config.txt) - you'll need to rename the file once downloaded to remove the `.txt` on the end.

**Comment by konzertnr9** [comment]
It seems to work now.
However I used to use my own Client ID but it seems that it doesn't allow me to change it anymore

**Comment by LHuisingh** [comment]
I applied the new config file. After restarting the app I retrieved my calendars and this time it opened a web page where I authorized the app to use my Google account.
It synced correctly! No errors. 
Thanks, Paul, for the quick and effective response!

**Comment by phw198** [comment]
This issue only affected the portable ZIP release, which I've repackaged and uploaded to the release page.

@TheJacksonian If you're still getting an unhandled exception when disconnecting the Google account, could you raise a new issue and provide the excerpt from the logs?

**Comment by TheJacksonian** [comment]
I've grabbed the repackaged portable ZIP release (I install, or extract the files to a custom folder for execution) and thank you sir, the problem is resolved, the reauthorisation went through super smoothly and the sync is running as expected!! Thanks.
