### ISSUE TITLE
Silent Install?

### ISSUE THREAD

**Issue by heidihendry** [phw198/OutlookGoogleCalendarSync#307]
Hi,
It's not an issue, but please could you explain how to perform a silent unattended install?

Thanks

**Comment by phw198** [comment]
Hi, What's your aim here? To deploy it in an enterprise environment on remote machines in order that anyone using the machine can run it?

🔗  [Squirrel discussion](https://github.com/Squirrel/Squirrel.Windows/issues/314#issuecomment-100046849) about this; should be doable

**Comment by heidihendry** [comment]
Yes. Either an MSI or silent switches would do the trick for me.

It's for a School for the teacher calendars. Teachers use Outlook because
of regional directive and Google Calendar because the students are all on
G-Suite.

Thanks

**Comment by phw198** [comment]
So as I understand it, the `Setup.exe` already provides the following options:
- `setup.exe --silent` Installs for current user but doesn't run.
- `setup.exe --machine` For the current machine, configures OGCS to be installed at the point any user logs in.

It also seems that the .msi would only mimic the second option. Can you work a solution with either of the above options?
