### ISSUE TITLE
2.6.1 problem with custom API key

### ISSUE THREAD

**Issue by konzertnr9** [phw198/OutlookGoogleCalendarSync#308]
I have been using a custom Client ID for OGCS.
With 2.6.1 it still manages to acquire the token and sync for the first run but after restarting the app (even if I hit the Save button before I quit) it shows "Your Google authorisation token needs updating" error.

**Comment by phw198** [comment]
Can you add the Google Plus API (in addition to the Calendar API) to your personal project and see if that helps?

**Comment by konzertnr9** [comment]
No, it does not solve the problem

**Comment by konzertnr9** [comment]
Oops it seems that it just took a little time for the change to become effective.
It seems to work now.

**Comment by phw198** [comment]
Yes, there can be quite a delay after enabling the new API. Glad that fixed it!
