### ISSUE TITLE
Outlook 2003 keeps asking for permission to email-adresses when syncing

### ISSUE THREAD

**Issue by superaum3** [phw198/OutlookGoogleCalendarSync#309]
When using the program Outlook 2003 Standard Edition keeps asking for permission to email-adresses when syncing.
Is there a solution to this?

**Comment by phw198** [comment]
Take a look at the [wiki page](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) for this.
