### ISSUE TITLE
Cannot install: Unable to cast COM object of type error message

### ISSUE THREAD

**Issue by kfalandays** [phw198/OutlookGoogleCalendarSync#310]
I have been getting this message for some time. This code will not run, and below is the error message I keep getting. What am I doing wrong?

![ogcs error message](https://user-images.githubusercontent.com/31048925/29751944-ee6c49d8-8b22-11e7-875c-02fe8a5e8d7a.PNG)

**Comment by phw198** [comment]
Had you seen the [wiki section](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary) for this error?

**Comment by kfalandays** [comment]
Thanks phw198, that did the trick
