### ISSUE TITLE
Past appointments duplicated as 1-hour blocks

### ISSUE THREAD

**Issue by DGreenebaum** [phw198/OutlookGoogleCalendarSync#317]
This could very well be my own error; I'm not sure how to remedy it though. Every time I sync, all past appointments are reduplicated on my Google calendar as 1-hour slots (so, say, I'll have the original 2-hr appt and a 1-hr appt with the same name and start time). I think subsequent syncs then copy the 1-hr duplicate back onto Outlook, though I'm not sure that's exactly what happens. Anyhow, my past appointments end up being a mess of one-hour copies.

Version 2.5.2.0 running on Windows 7 Professional, with Outlook 2013 (15.0.4937.1000)

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1264797/OGcalsync.txt)

[settings.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1264800/settings.txt)

**Comment by phw198** [comment]
The logfile doesn't show you creating anything in Google, be it an hour in length or not. I need you to replicate the problem and then provide the logfile.

However it does show you cancelling an upgrade? v2.5.2 is a little old now - are you having trouble upgrading?

**Comment by DGreenebaum** [comment]
Updated to 2.6.0.0; issue still occurs.
Logfile attached deals with (among others) an Outlook-native entry for a 50-minute event called "ENGL 1101 - David - K. Walker" on 9/1/17 at 9:00 AM. It's copied to Google as "ENGL 1101 - David - K. Walker From to at 09:50AM @ L216:". Similar event, "ENGL 1101 - D - K. Walker", 9/1/17 at 11:00 AM becomes "ENGL 1101 - D - K. Walker From to at 11:50AM @ L216:". Also included is screenshot of Google Calendar page as illustration.
Also it seems that all-day or multi-day events are reproduced as 1-hour blocks 8-9 PM on the last day of the event.
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1277795/OGcalsync.txt)
![screenshot](https://user-images.githubusercontent.com/30126179/30067134-f3ec4712-9227-11e7-979b-06ae965c6968.jpg)

**Comment by phw198** [comment]
Yep, this is getting pretty messy and I'm struggling to understand quite what you're wanting to do!

You have "Merge Items" set along with "Prompt for delete" and you're declining lots of deletions happening in Google. Which calendar is the original source of truth? In Google or Outlook? Or did you have some in both before you started trying to use OGCS?!

For example, OGCS is reporting `Not deleted: 8/30/2017 11:00 AM => "ENGL 1102 - David - D. Muller"` - so it wanted to delete the (60 min) entry but you told it not to. Now you're complaining you've got duplicates...? :smirk:  Why not let it delete the item and just leave you with the single 50 minute appointment at 11AM?

**Comment by DGreenebaum** [comment]
I did have info in both calendars to start with (Google/personal and Outlook/work); I had thought that two-way syncing would bring them together. Was that wrong?

So I manually cleaned up the Google calendar to remove 1-hour dupes and re-synced, allowing deletions as it ran, and--it wiped out everything on the Google calendar, original or synced, for the entire sync date range (7 days past/120 days future). Outlook calendar still has the correct info, thank goodness. With nothing to lose, I tried re-syncing but it did not restore the info to Google calendar. (Before and after screenshots, and logfile, attached)

![before1](https://user-images.githubusercontent.com/30126179/30120583-44795f56-92f7-11e7-8368-c20ce7cd2dc5.jpg)
![before2](https://user-images.githubusercontent.com/30126179/30120590-476598ce-92f7-11e7-898c-9e72cb0afcc9.jpg)
![after1](https://user-images.githubusercontent.com/30126179/30120593-4ae38e16-92f7-11e7-8278-7399d95e376a.jpg)
![after2](https://user-images.githubusercontent.com/30126179/30120594-4b473efc-92f7-11e7-8913-a8e1c7bfa5cc.jpg)
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1281658/OGcalsync.txt)

**Comment by phw198** [comment]
Yes, merging with 2-way sync should ultimately end up with all events sync to both Outlook and Google. But as soon as you delete anything in one of the calendars, that delete will sync through to the other calendar.

I wouldn't have suggested manually clearing out the "duplicates" in Google, but rather letting OGCS make the deletes it wanted to - it would only delete something in Google if:
- the item originated from Outlook and was manually deleted in Outlook
- the item originated in Google, was 2-way synced into Outlook and then manually deleted in Outlook

To get things working from where you currently are, which is everything residing in Outlook:
1. Set Merge events
1. Set 1-way sync from Outlook to Google
1. Shift-click the `Sync` button to get everything in to Google

If you have items only in Google that you still want in Outlook:
1. Set 1-way sync from Google to Outlook
1. Shift-click the `Sync` button to get them in to Outlook

Finally set back to two-way sync.

Hope that helps

:memo: Any items deleted by OGCS can be recovered frin the `Deleted Items` folder in Outlook, or the `Recycle Bin` for the relevant Google calendar.

**Comment by phw198** [comment]
Any luck with temporarily setting 1-way syncs?

**Comment by randerson4** [comment]
Hi @phw198 -

I think I seem to be having the same issue here as this person and wonder if you could help me also. I have it set up as a two-way sync as I add new events to both Outlook and Google. Everything seems to sync fine for future events but once the event occurs, the event duplicates. Usually the duplicate event is an hour long, regardless of the length of the original event and usually duplicates at the same time as the original but not always. Sometimes one duplicate event occurs...sometimes two. 
Here are screenshots of how the issue appears in my calendars from yesterday 4/4/18. I put a red X on the original events.
![outlook](https://user-images.githubusercontent.com/35932005/38374796-36bf1432-38ba-11e8-8881-5b9283da51c5.JPG)
![gcal](https://user-images.githubusercontent.com/35932005/38374830-58665b9a-38ba-11e8-80a2-750429c040eb.JPG)
Here is my log file:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1880609/OGcalsync.log)
Settings:
![settings](https://user-images.githubusercontent.com/35932005/38374970-af01e3ac-38ba-11e8-91ba-106e2534c79d.JPG)

Thanks!

**Comment by phw198** [comment]
So I don't think this is anything that OGCS is actually doing, but obviously would be good to found out what is! OGCS won't add new words to the subject unless you had set up an obfuscation rule to do so, which you haven't. Also the words "from" "to" and "at" are the words the Google android app prompts when you create a new event, which seems suspicious to me... The location is also the time it seems? I think OGCS is simply syncing these items to Outlook after whatever creates it in Google. 

Are you able to provide your logs _directly_ after one of these duplicates is created in Google, so I can see if OGCS played any part in it?

**Comment by randerson4** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2084911/OGcalsync.log)

I think this one should reflect a duplicated event called "Sell, Sell, Sell!!!" that occurred at 10am and was indeed duplicated in Google. Not sure exactly at what point it was duplicated, but I noticed it a few minutes after 10:00am. Does this help?

**Comment by phw198** [comment]
It helps on that I cannot see OGCS creating that event in Google, and also it has this line:
```
2018-06-08 10:02:37,386 DEBUG 18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] - 3 unclaimed. 2018-06-08 10:02:37,387 DEBUG 18 OutlookGoogleCalendarSync.Recurrence [0] - Event "Ivyn From to at 10:00AM @ :" did not have Outlook EntryID stored. 2018-06-08 10:02:37,387 DEBUG 18 OutlookGoogleCalendarSync.Recurrence [0] - Event "SELL SELL SELL!!! From to at 11:00AM @ 11499#:" did not have Outlook EntryID stored. 2018-06-08 10:02:37,388 DEBUG 18 OutlookGoogleCalendarSync.Recurrence [0] - Event "" did not have Outlook EntryID stored. 
```
As they do not have an Outlook ID, it means OGCS did not create them as part of the two way sync. In fact, if you turn off Merge, OGCS might actually delete them. Turn on Confirm Deletions so you can confirm/deny a deletion?

**Comment by DGreenebaum** [comment]
Jumping back in here...I had basically thrown up my hands and given up OGCS as not working for me. Since then my work computer has been upgraded from Windows 7 to Windows 10, and I didn't even try installing OGCS on the new machine. And as of a little while ago (sorry for the vagueness, but changes in workflow and such prevented me from noticing until recently) I continue to get the same effect on Google Calendar even though I no longer have OGCS installed. So somehow it has to be a Google Calendar artifact, triggered at first by interaction with OGCS but continuing on its own.

This screenshot is GCal's recording of a half-hour test event I created at about 11:30 am today on Outlook 365, scheduled to run from 12:00 to 12:30. I first noticed it on GCal at about 12:45 but had been away from my machine prior to that.
![test](https://user-images.githubusercontent.com/30126179/41170678-5bd0bc7e-6b1b-11e8-88d5-a81c4e966d9e.png)

**Comment by phw198** [comment]
Thanks for updating @DGreenebaum  - that was going to be one of my next suggestions, stop OGCS from syncing and seeing if the problem continues.

It feels to me like something is trying to use the Google "quick add" feature (which OGCS doesn't use)  and it's not working right. I know quick add got removed in the calendar redesign - did you see this problem before you calendar was updated by Google?

Also your screenshot shows todoist - are both of you using that? Or any other form of integration? Might be worth checking what apps you've allowed access and have a clean-up?

https://myaccount.google.com/permissions

**Comment by DGreenebaum** [comment]
My original issue predated my use of Todoist by several months; I haven't been using another form of integration. I did just take the opportunity to remove OGCS from my Google Permissions (which I had not done before). Just set up another test event on Outlook 365, which I expect will not now cross over to GCal. Will follow up in an hour or so.
