### ISSUE TITLE
Question: Remove Notification when syncing

### ISSUE THREAD

**Issue by markcs** [phw198/OutlookGoogleCalendarSync#319]
This is a question and/or an enhancement if it is not implemented.

Is it possible to sync the calendar from Outlook to Google, and remove any notification/reminders from the sync'd Google appointment?

I tried setting the DND option, but I still get reminders from Google.

thanks!

**Comment by phw198** [comment]
If you don't check the box to sync reminders then you shouldn't get any. The caveat being that if you have set a default reminder for your entire Google calendar, then I think this will still get set - that outside of OGCS.

If you are wanting to remove reminders from already synced events, having made sure you're not syncing reminders, try shift-clicking the Sync button to force a compare of everything.

**Comment by phw198** [comment]
Any update on this?

**Comment by markcs** [comment]
Apologies. Yes, I had to remove the default reminder options in Google Calendar.  That fixed the issue.

cheers
