### ISSUE TITLE
First Run

### ISSUE THREAD

**Issue by Panache1** [phw198/OutlookGoogleCalendarSync#320]
Thank you very much for this.

When I run it for the first time, nothing is added to my Outlook calendar if I set it for bidirectional syncing.  I have to use Google to Outlook to get it to populate my Outlook calendars.  From then on, bidirectional syncing works.

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file for the period that covers what you're reporting [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)].

**Comment by Panache1** [comment]
Unfortunately, I did a lot of installation and reinstallation to get it working the way I wanted it to.  Therefore, I'm not sure which of the logs are relevant.  Do you want me to upload all 8 logs?

**Comment by phw198** [comment]
If you're really not sure which logs files are relevant, then yes, just zip them all up.

Can you provide the steps you think will reproduce this problem? I've just tried the following without issue:-
1. Start with an empty Google and Outlook Calendar
1. Create an item in Google
1. Set OGCS to 2-way sync
1. The item gets synced to Outlook as expected.
