### ISSUE TITLE
"App unexpectedly terminated" msg at every attempt to open OGcal [0x80040155]

### ISSUE THREAD

**Issue by WGilham** [phw198/OutlookGoogleCalendarSync#322]
I get the attached message box every time I try to open OGcalSync, including the automatic open at very first install (it shows up "under" the splash-screen...).  Yet I swear the syncing is still working (in the background?) !  

I'm running latest version just downloaded by setup file = 2.6.0.0
This started when I installed Outlook 2016 - was previously using Outlook 2007 (anciennnnnt! - but it worked fine with that version.) 

![app terminated screen](https://user-images.githubusercontent.com/31629483/30035334-e74d6c04-915d-11e7-8713-4df9699e3224.jpg)
![ms office version](https://user-images.githubusercontent.com/31629483/30035335-e74d9846-915d-11e7-8e36-2985560d9eff.jpg)

Please advise "patch or oter method to restore full function, especially to open the program!

**Comment by phw198** [comment]
Another busted Office install - see the wiki for [instructions on fixing it](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered).

**Comment by WGilham** [comment]
Thanks.  Though messing around in the registry is way beyond my comfort zone, I followed steps exactly  at “instructions for fixing it” and lo! Outlook Google Calendar Sync program DOES indeed now open.  Thanks, and bravo for quick response. 

Wayne Gilham, Tacoma WA USA

**Comment by phw198** [comment]
Well done for persevering and glad it's working for you now 🙂
