### ISSUE TITLE
attendee names are missing in google

### ISSUE THREAD

**Issue by shie-erlich** [phw198/OutlookGoogleCalendarSync#323]
hi folks!
not sure if this is an issue or a feature request, but basically when syncing a meeting, only the email addresses of the attendees are synced over to google, but not their names (display name).

can this be fixed? or would the attendees need to be google contacts for this to work?

thanks for working on this!

**Comment by phw198** [comment]
That's a feature of the Google web app - it only displays the email address unless it matches a Google+ profile or is in your contacts.

If you look in e.g. your phone's calendar for Google you'll see OGCS has indeed synced the names too.

**Comment by shie-erlich** [comment]
Thanks Paul.
I tested it using the Google calendar API, iirc.
I'll double check though and see if I just remembered it wrong

Thank you and I'll check back to report
Shie

**Comment by shie-erlich** [comment]
checked and confirmed that Paul is correct. closing the issue
