### ISSUE TITLE
not all meeting synced, how can i help investigate?

### ISSUE THREAD

**Issue by shie-erlich** [phw198/OutlookGoogleCalendarSync#324]
there's an issue i'm having right now where 2 meetings today aren't synced to gcal.
the only hint i've seen (after turning on verbose output):
```
"11 are exceptions to recurring events."

"DotNetOpenAuth.Messaging [0] -  Multiple message types seemed to fit the incoming data: {AccessTokenSuccessResponse (2.0),
UnauthorizedResponse (2.0),
}"
```
tried running the sync multiple times etc. anything else i can do to help dig into this?

**Comment by shie-erlich** [comment]
in fact, i'm wondering if something odd is happening with recurring meetings.
one example is a meeting that happens on thursday and this week was extended to 1h, yet on gcal it still appears as a 30 minute meeting?

**Comment by shie-erlich** [comment]
this is happening again today, so i have another repro.

any thoughts?

**Comment by phw198** [comment]
:spiral_notepad: Can't really say without your OGcalsync.log file - could you upload it?[[See instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

You're right, the single occurrence being changed from 30mins to 1hour in the recurring series should be picked up as an exception to the recurring event, but this should still sync through.

The error line in your logfile you've highlighted isn't necessarily a problem, it normally means your Google API refresh token has expired and needs refreshing, which happens every 60 minutes.

**Comment by Lunarmanpl** [comment]
Hi. I have something similar. I had 22 in Outlook and 24 in Google. When tried to two-way sync it didn't created the missing two but when changed to 1-way google -> Outlook it created these two. 
If this help: two meetings 11.09 and 12.09 both all day, new created in Google.
[OGcalsync.2017-09-11.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1291445/OGcalsync.2017-09-11.txt)

**Comment by shie-erlich** [comment]
sorry for the late response. these are the log lines from the day the issue was happening:
https://gist.github.com/shie-erlich/f003052bcf5623172b3f209b794d983a

interesting to note that there is very little activity in the log while i know the app was running every hour - so confused. also, my log level isn't great and i just changed it to 'debug' for future needs

**Comment by phw198** [comment]
@shie-erlich The log file has very little activity as you set the logging level to `ERROR` - there's not much I can do until you've encountered the error whilst logging at `DEBUG`

**Comment by shie-erlich** [comment]
thanks @phw198 .
i just submitted https://github.com/phw198/OutlookGoogleCalendarSync/issues/332, which is not the same issue as this but has a similar side effect of a meeting not every syncing from outlook to google

**Comment by Lunarmanpl** [comment]
I tried to use 2.6.1.5 hotfix from #332 but AVG on win10 detect it as IDP.ALEXA.51 trojan

**Comment by JacquesJessen** [comment]
This sounds similar to an issue that I see as well.  If an Exchange user adjusts/changes their recurring meeting, that change, or sometimes even the meeting itself will not be sync'd to Google.  In the attached log, I've a couple of meetings that were adjusted this week, but the meeting themselves were not replicated to Google.
[OGcalsync - Copy.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1299741/OGcalsync.-.Copy.txt)

**Comment by phw198** [comment]
@JacquesJessen I'd recommend upgrading to the latest beta release at least. Would be helpful to know _which_ meetings were changed and not syncing. However, there are errors related to caching problems - if this is the item you changed, then I suspect it will sync after a restart of Outlook and OGCS.

@Lunarmanpl Working as designed. You have deletes disabled, so the "missing" item in Outlook was not being deleted in Google. It also wasn't recreating it in Outlook because that would be silly in 2-way sync. However, by switching to 1-way sync from Google to Outlook, the item is then recreated in Outlook.

To avoid AV false positives, I probably need to sign the software with a certificate. Costs $110 USD/year - donations welcome!
