### ISSUE TITLE
OGCS gets stuck at Total inc. recurring items spanning sync date range

### ISSUE THREAD

**Issue by cyentze** [phw198/OutlookGoogleCalendarSync#325]
When I run OGCS, I often encounter that it will be stuck at the following step:
Total inc. recurring items spanning sync date range...

Sometimes, it will work and proceed on to sync successfully, but most times it will just be stuck at this step.  My Outlook is connected to company LAN, but due to security, access to accounts.google.com is disabled. Thus, I will normally connect to company LAN, download the mails in Outlook, and then disconnect LAN and connect to external network, then run OGCS.  

Anybody else encounter this?  Thanks.

**Comment by phw198** [comment]
Upgrading to v2.6.1 may well fix this, though could depend on what exactly your company is blocking. Worth a try...
