### ISSUE TITLE
Wrong  owner of an appointment when  Outlook ==> Google synchronization and unwanted invitations sended

### ISSUE THREAD

**Issue by fonetval** [phw198/OutlookGoogleCalendarSync#327]
#Hi team,
I love your soft but I was facing a very annoying bug (I think) :  here it is the chronology :

1. at work, a colleague creates an appointement with invitation for many people (and I), so I have it in my Outlook calendar
2. ONGS synchronizes  it with my Google calendar, so that...
3. ...Google Calendar sends again all the invitations to all participants... indicating that I am the sender of the appointment !!!

Could you please correct this (if you agreed that it's a bug) so that the sender of the appointment remains the same and no invitation will be send twice ?

Best regards.

**Comment by phw198** [comment]
This is a [known issue on Google's side](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google), but I have also started work on a workaround on #197 which will prevent this from happening.

Regarding you being the owner of the event in Google, that's the way it has to work as you are the person who created the item in Google (through OGCS). It's not possible to set the _real_ organiser as defined in Outlook as the owner.

**Comment by fonetval** [comment]
Thanks Paul for this tremendous rapid answer :-) !
Glad that this bug is yet known and, for me, no matter that the owner of the item remains the same : it's the undesire confirmations sended that is the crucial point.
So, despite my reads of the thread #197 , what the workaround looks like  : have you add "OGCS" extension name to mail adress of attendees (like suggested by wesarnquist ?

I Trully want to thank you for your  big work on that so usefull piece of software !

Sincerely.

P.S. I'm going to test the HotFix 2.6.1.4 while I'll be back to work on monday.

**Comment by phw198** [comment]
Thanks for the feedback...always good to hear my work is appreciated :+1: 

Yes, that's basically it - ".ogcs" is appended to the end of attendee email addresses in Google calendar. To force the change for items already synced to Google, shift-click the `Sync` button.

By the way, just posted v2.6.1.8 to #197 - all being well that will be the next alpha, so let me know how it goes over on the other ticket :crossed_fingers:
