### ISSUE TITLE
Deleting single occurrences of recurring events doesn't update Google

### ISSUE THREAD

**Issue by wajdi-b** [phw198/OutlookGoogleCalendarSync#331]

**Comment by phw198** [comment]
Any evidence of this?

:spiral_notepad: Please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by wajdi-b** [comment]
This is only affecting full-day recurring events. Full-day single events sync correctly.

[OGcalsync.log](https://gist.github.com/Lapsusone/485a3311dee005349c449e1f92732848)

**Comment by phw198** [comment]
I can see it's created a full day item in Google [here](https://gist.github.com/Lapsusone/485a3311dee005349c449e1f92732848#file-ogcalsync-log-L1198), for example (`2017/07/29 => "On vacation"`), and also a recurring full day item for the last day of every month [here](https://gist.github.com/Lapsusone/485a3311dee005349c449e1f92732848#file-ogcalsync-log-L2169) (`2017/08/31 (R) => "Paie CN"`).

Unless you can explain specifically the issue you are seeing I can't help further.

**Comment by wajdi-b** [comment]
Ok, I think I have now identified the problem. 

I created a recurring full-day event in Outlook and then deleted a single occurrence, not the entire series. The change did not update accordingly in Google.

**Comment by phw198** [comment]
I cannot replicate that.
1. Created all-day recurring series in Outlook every day from Weds to Sunday
1. 1-way sync to Google
1. Deleted Friday instance in Outlook
1. 1-way synced to Google

Do those exact steps work for you?

**Comment by wajdi-b** [comment]
I think it was related with the option to ignore deletes that was activated. Everything seems fine now. Thanks for the help!
