### ISSUE TITLE
ERROR: Failed to retrieve Google event

### ISSUE THREAD

**Issue by pcskigal** [phw198/OutlookGoogleCalendarSync#333]
I've tried and tried to get sync to work and all i get is this

![image](https://user-images.githubusercontent.com/31898168/30338620-78102d02-97a9-11e7-8298-b9a01e5c1796.png)

ERROR: Failed to retrieve Google event
Outlook 89, Google 52

please help!

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by IngomarL** [comment]
Since a few days, getting the same error msg.

![image](https://user-images.githubusercontent.com/19913360/37502147-d04e6b6c-2914-11e8-8931-c236adee8c7c.png)

Any suggestions?

**Comment by phw198** [comment]
It basically means there is an Outlook recurring event that starts outside of your sync range and it's failing to find the equivalent master event for it in Google. Do you have deletions disabled in OGCS?

Would need your logfile to properly investigate further...
