### ISSUE TITLE
Feature Request:   Filter Expressions

### ISSUE THREAD

**Issue by edgepacket** [phw198/OutlookGoogleCalendarSync#334]
- [x] Exclude based on meeting name - see #1688 
- [x] Obfuscate meeting notes - see #500 
----
Any way we can filter on certain words or phrases to exclude them from being sync'd.   It would be *amazing* if we had a small rule action type of configuration panel.

If word "canceled" is in meeting name dont sync.

If phone number "4048" is in meeting notes change number to "+14045554048,,,9982706#"

This would be a massive plus.   I would donate some bucks to help implement this.

**Comment by phw198** [comment]
Interesting request. I think the option to not sync cancelled meetings and/or only sync accepted meetings has already been raised and is being considered.  However the more complicated options I think would just confuse most users - just the categories include/exclude option befuddles some!

A compromise might be for you to use vba script in Outlook to set a category if certain words are present, then set OGCS to exclude sync of that category?

**Comment by edgepacket** [comment]
I don't think VBA would be the way to go due to security concerns.    Probably would not be widely deployed.   
  
I think the feature would be relatively easy to implement and would be widely accepted and adopted.      
  
Essentially you would implement a simple rules engine that allows a user to add/modify/delete on synchronization action.    
  
Nothing overly complex but would be a massive help to mobile users wanting to tame their calendar.      
  
If $field contains x then do actio
  
Nothing extravagant.    Just simple actions like skip/delete/change text
  
Could be a simple panel on the control widget entitled rules.      
  
Regards,
Matthew

**Comment by phw198** [comment]
I think you misunderstood my VBA suggestion - for you to personally use Outlook VBA to automatically set categories that OGCS then uses to includes/excludes for sync. So no, this would not be widely deployed as you'd be the only one with the VBA code, specific to your needs.

This wouldn't of course handle the transposing of phone numbers etc you suggested, but I disagree this would be widely adopted so am very unlikely to implement it. Happy to leave the ticket open for people to vote-up if they want to see it though :slightly_smiling_face:
