### ISSUE TITLE
Categories of alternative mailbox

### ISSUE THREAD

**Issue by efapr** [phw198/OutlookGoogleCalendarSync#335]
Maybe I am doing something wrong, since I am a new user of OGCS, but when I select to use an alternative mailbox, the categories from that mailbox's calendar do not populate in order to give me the option to include/exclude certain events.  Is there already a fix to this?  Or would this be a new feature request?

**Comment by phw198** [comment]
Sounds like an enhancement to make it refresh categories on change, but meanwhile just right click the list and select refresh.

**Comment by efapr** [comment]
I've attempted the refresh, but it's still pulling categories from my default calendar in outlook.

**Comment by mcfibb** [comment]
Hey there Paul -- absolutely love OGCS. Thanks for making this!

I'm still experiencing the same issue as OP. Currently using alpha 7.7.0. Did this bug pop up again?

Thanks!

**Comment by phw198** [comment]
Thanks @mcfibb. If you do have the same problem, then I think it'll have a different root cause than this ticket, which is very old now. Could you raise a new issue ticket and upload your `OGcalsync.log` file?

**Comment by mcfibb** [comment]
Thanks for the reply. The problem still exists (alternate calendar categories not updating -- in my case, default mailbox categories remained and user-created/renamed categories for alternate calendar nowhere to be found). I ended up messing with the XML code for "Calendar 2". (FYI -- using your work around to launch second instance of OGCS). In case this helps anyone else, here's the chunk of code I modified (excerpted from very beginning through a few lines past relevant code):

```
<?xml version="1.0" encoding="utf-8"?>
<Settings xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/OutlookGoogleCalendarSync">
  <APIlimit_inEffect>false</APIlimit_inEffect>
  <APIlimit_lastHit>2000-01-01T00:00:00</APIlimit_lastHit>
  <AddAttendees>false</AddAttendees>
  <AddColours>false</AddColours>
  <AddDescription>false</AddDescription>
  <AddDescription_OnlyToGoogle>true</AddDescription_OnlyToGoogle>
  <AddLocation>false</AddLocation>
  <AddReminders>false</AddReminders>
  <AlphaReleases>true</AlphaReleases>
  <AssignedClientIdentifier>[redacted].apps.googleusercontent.com</AssignedClientIdentifier>
  <AssignedClientSecret>[redacted]</AssignedClientSecret>

//----- MODIFIED CODE BELOW ------//

<Categories xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
    <d2p1:string>[Name of Category to Match]</d2p1:string>
  </Categories>

//-----END MODIFICATION-----//

  <CategoriesRestrictBy>Include</CategoriesRestrictBy>
  <CloakEmail>true</CloakEmail>
   ETC ETC ETC
   ETC ETC ETC
```

The string doesn't include quotes, just the verbatim name of the category to be searched and synced.

Hope this helps in IDing either the issue or anyone else with the same problem!

 - McFibb

**Comment by phw198** [comment]
@mcfibb I can't replicate the problem at all - it updates the categories for my alternate Exchange mailbox fine. What is your alternate mailbox account type? Exchange also?

:spiral_notepad: Please could you reproduce the issue and then provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

Please create a new issue for this though.
