### ISSUE TITLE
Latest release in Windows 10 triggers admin approval to run

### ISSUE THREAD

**Issue by erasure** [phw198/OutlookGoogleCalendarSync#336]
I am using the portable version and just downloaded v2.6.0 Beta, and upon trying to run it on my Windows 10 machine at work (on which I do not have admin rights), I now get a message saying: "Windows SmartScreen prevented an unrecognized app from starting. Running this app requires administrator approval." I did not have this problem with the previous version; is there away around this? 

I just downgraded to v2.5.0 Beta and am once again able to run without the admin approval; however, I tried all of the v2.5.x Alphas and all of them triggered the admin approval message. 

Forgive me if I am breaking any rules or missing information - I am a GitHub n00b)

**Comment by phw198** [comment]
Welcome @erasure. That's annoying - v2.5.1 was the first release to abandon the CodePlex _ClickOnce_ installer and move to GitHub _Squirrel_, so I'm guessing SmartScreen doesn't like something about Squirrel.

It's looking like I might need to get a code signing certificate for the OGCS build, but they cost money :(

When does the block occur? At the point of download in IE? Have you tried a different, non-MS browser?

**Comment by erasure** [comment]
Ah, interesting. And sad if it's going to require a code signing certificate :( Maybe several of us can pitch in with the cost if it goes that route? 

The block actually occurs when I try to run the .exe, after copying all the files to the C:\ drive (in an OGCalSync folder). No issues with downloading the files or copying them out of the .zip.

**Comment by Lunarmanpl** [comment]
I am using win10 with no admin rights (portable version) and it also ask if I am sure to run it (SmartScreen) but i can run it without admin right (clicking more info)
![obraz](https://user-images.githubusercontent.com/30334537/30413190-f04a998c-991c-11e7-8e2c-aa96463b9ff3.png)

**Comment by phw198** [comment]
I think you should also be able to right click the executable and select _Report that this download is safe_.

@erasure thanks for the offer of pitching in for a code signing certificate. I might look at setting up a crowd funding link for it...

**Comment by erasure** [comment]
Perhaps my machine is more locked down... here is what I see when I try to run the .exe: 

![smartscreen](https://user-images.githubusercontent.com/166585/30453343-9cee7d0e-9966-11e7-87da-3ae879649600.PNG)

And here is what I get when I right click the .exe... no option to report the download is safe: 

![rightclick](https://user-images.githubusercontent.com/166585/30453364-aa3f8fd4-9966-11e7-8c38-e4ea8ffc742b.PNG)

**Comment by phw198** [comment]
So what happens if you enter your username and password and hit `Run Anyway`? Or is it requiring Administrator privileges?

**Comment by phw198** [comment]
I was using a self signed certificate for the old CodePlex builds - I'll try a build using that and see if it helps before investigating purchasing a full code signing certificate. Will try and post in the next day or so...

**Comment by phw198** [comment]
So not as simple as I'd hoped. The option to sign the application in Visual Studio with my personal certificate uses something called _Strong Naming_ which then makes it incompatible with the installer Squirrel libraries; the argument being that strong naming open source projects undermines the ethos of it as it make it a PITA for anyone to collaborate on the code.

It therefore looks like an Authenticode certificate is the only way to really stop this problem (as well as reduce false positives with AV). [$110/year](https://www.digicert.com/order/order-1.php) though.

Meanwhile, I think @erasure's issue is down to the files being tagged as "downloaded from the internet". The workaround is to right-click each file in the extracted zip and select `Unblock`. This is pretty tedious for each and every file though, so if you can run Powershell....
1. `Winkey+R` and type `powershell`
1. Change directory to the extracted files
`cd C:\my\extracted\files\directory`
1. `Get-ChildItem | Unblock-File`
1. Now run OGCS by double clicking the executable.

Let me know if this works for you.

**Comment by Lunarmanpl** [comment]
I was making few test and "problem" wint AV and Smart Screen started with release 2.6.0+, no problem with any portable 2.5.x so maybe there is some new feature added in that 2.6.0. that Windows doesn't like?

**Comment by erasure** [comment]
As you see in my screenshot above, when I right-click I don't have the option to "Unblock"... and I expected the powershell command to reject me without admin priviliges... but lo and behold, it worked!! I can now run 2.6 without it asking for admin approval :) Thanks!

**Comment by phw198** [comment]
@erasure Sorry, I meant right-click and select properties, then unblock. Glad the PowerShell worked anyway!

**Comment by erasure** [comment]
Hmm, I don't see an unblock option there either. But yes, either way the PowerShell command seems the way to go!

**Comment by phw198** [comment]
Will add this to the wiki and maybe include the PowerShell scriptlet in the ZIP file too.

**Comment by phw198** [comment]
[Wiki updated](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#windows-defender-smartscreen-protected-your-pc) and PowerShell script will be included from v2.7.2 in portable zip release.

:link: Issue #295
