### ISSUE TITLE
How to disable splash screen after donating?

### ISSUE THREAD

**Issue by joshbtdev** [phw198/OutlookGoogleCalendarSync#337]
Hi there - Apologies in advance if this is the incorrect place for this enquiry. Unfortunately we haven't received a reply via the donate email address.

Can you please advise how we can disable the splash screen since we have contributed a donation toward the project?

Thanks

**Comment by phw198** [comment]
Hi @joshbtdev could you forward me the PayPal receipt email for your donation to my donation email address? I can't see anything that might match your GitHub handle...

**Comment by joshbtdev** [comment]
Hi Paul, I have forwarded through the donation receipt email. Thanks very much for such a useful piece of software.

**Comment by phw198** [comment]
Thanks - I've also forwarded on the instructions you should have got soon after donating. Have you got that now?

**Comment by joshbtdev** [comment]
I had a look but nothing has come through. I've checked our spam folders and it's not in there either. Very odd.

EDIT: My apologies, I was checking our domain address email, not our gmail. Have got it now, thank you!

**Comment by joshbtdev** [comment]
Hi Paul, just following up to let you know the instructions worked and we have successfully disabled the splash screen. Thanks for your help!

**Comment by phw198** [comment]
Thanks for letting me know 🙂
