### ISSUE TITLE
Crashes on startup if Outlook not running

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#34]
Hello,  
  
I came across this program yesterday and wanted to try out. Downloaded the
latest version &amp; installed. But unable to use it as I am getting the
following error message at startup:  
Operation Aborted (Exception from HRESULT: 0x80004004 (E_ABORT).  
My am using Windows 10 &amp; Micrsoft Outlook 2007.  
Can someone help please.  
  
Regards  
Natarajan  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 243](http://outlookgooglecalendarsync.codeplex.com/workitem/243)
**Status:**	Resolved
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Apr 19, 2016 at 4:35 AM
**Reported by:**	NatarajanV
**Updated on:**	Sep 18, 2016 at 9:25 PM
**Updated by:**	phw198

#### Plaintext Attachments

[CodePlex Issue #243 Plain Text Attachments](https://gist.github.com/050865c901717bdef2b4f79f9197007a)

#### Binary Attachments

[OutlookGoogleCalendarSync.exe](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=243&FileAttachmentId=1607421)

**Comment by phw198** [comment]
On *2016-04-19 14:09:44 UTC*, **phw198** commented:

Could you try using the portable zip release instead - some users have reported that has fixed this issue.

**Comment by phw198** [comment]
On *2016-04-19 21:59:46 UTC*, **NatarajanV** commented:

Thanks phw198. Tried your suggestion of downloading zip release. Same error occurs. please advise.

Natarajan

**Comment by phw198** [comment]
On *2016-04-19 22:57:32 UTC*, **phw198** commented:

Is Outlook open when you start OGCS and try to sync? Or is there an icon in the task tray for Outlook with a little cog over it? The icon tooltip is "Another program is using Outlook. To disconnect programs and exit Outlook, click the Outlook icon
 and then click Exit Now." If so, click Exit to close Outlook, then close OGCS, open Outlook and then open OGCS. Any difference?

If not, please could you upload your OGcalsync.log file (found in %APPDATA%\Outlook Google Calendar Sync").

**Comment by phw198** [comment]
On *2016-05-02 10:13:17 UTC*, **NatarajanV** commented:

Hi 
Soory for the delay in responding. It appears sync works only when outlook is open first. Manual sync by opening outlook first seems to work ok. But automatic scheduled sync ot manual sync with outlook closed generates above mentioned error.

latest Log file attached as requested. 
Regards 
Natarajan

**Comment by phw198** [comment]
On *2016-05-06 16:36:06 UTC*, **OleStokie** commented:

Same issue - OK when Outlook is open.

**Comment by phw198** [comment]
On *2016-06-02 03:09:04 UTC*, **phw198** commented:

Seems you have the same as Issue 96...which I closed in defeat :( 

I still can't replicate this error, which makes me wonder if you work somewhere that has somehow locked down the ability for a program to start Outlook and then access the MAPI functions. Which would make sense I guess if you don't want some malware producing
 spam from your account... 

So I've tried a dumber approach - not to start Outlook through the API, but with a system call in the hope it won't notice a program did that and so won't block it.


Please give v2.2.1.5 attached a go!

**Comment by phw198** [comment]
On *2016-07-02 06:03:09 UTC*, **phw198** commented:

Any feedback on v2.2.1.5 please?

**Comment by phw198** [comment]
On *2016-08-03 04:51:27 UTC*, **markvoor** commented:

I am having the same issue. 

Could you send v2.2.1.5? 

Thanks, Mark

**Comment by phw198** [comment]
On *2016-08-03 04:52:26 UTC*, **markvoor** commented:

Here is my log file

**Comment by phw198** [comment]
On *2016-08-03 05:48:41 UTC*, **phw198** commented:

v2.2.1.5 is attached at the top of page. Instructions on applying it in the 
wiki

**Comment by phw198** [comment]
On *2016-08-03 23:48:10 UTC*, **markvoor** commented:

Symantec views the file as a threat and quarantines it when I open it. 

Even after I restore the file, however, I have the same problem.

Oh, well.

**Comment by phw198** [comment]
On *2016-08-14 19:40:02 UTC*, **phw198** commented:

+Issue 292


I've refined this further with the attached hotfix v2.2.3.6 - please let me know if this works!

**Comment by phw198** [comment]
On *2016-09-17 16:54:09 UTC*, **phw198** commented:

Last call for testing this hotfix! 

I've rolled it in to v2.2.4.1 and attached above again - would really appreciate if someone who experiences this issue can test it.

**Comment by phw198** [comment]
On *2016-09-19 04:25:14 UTC*, **phw198** commented:

Decided the changes are worth rolling in without anyone confirming it does actually fix this issue. Included in Alpha v2.2.5.0.

**Comment by danalexa** [comment]
i can confirm at workplace V2.5 does not start because the .exe is beeing quarantined by symantec. i cannot disable the antivirus on my work computer....
Can i help you with some more details?
