### ISSUE TITLE
Choosing the calendar for the entries to be viewed

### ISSUE THREAD

**Issue by scarcity44** [phw198/OutlookGoogleCalendarSync#340]
Google to Outlook 2007.  Sync one way.  Works great.  Lovely.  
Wish to amend something.

My Outlook 2007 has a number of calendars.  The Default is only client based and thus not available to see online.  As such, I have iCloud calendar which permits me to see my events online.  This is where I usually create my events.  

How do I setup the Sync app to have the synced Google events appear in the Outlook calendar of my choice vs. that the synced Google events are appearing in the Default Outlook calendar?

**Comment by phw198** [comment]
You should just be able to select the non-default calendar in the `Select Calendar` dropdown on the `Outlook` tab under `Settings`...?

**Comment by scarcity44** [comment]
Thanks phw198. This is what I thought would solve the issue.  
However, only the Default Calendar is listed in the "Select Calendar" dropdown.
I have now switched from Default Mailbox to Alternative mailbox which shows the Data Files, and am now able to choose.  Thank you
