### ISSUE TITLE
Norton Security Detecting v2.6.1-alpha.exe as Virus

### ISSUE THREAD

**Issue by hebendj** [phw198/OutlookGoogleCalendarSync#341]
After downloading the file, Norton determines that this file is infected.  I downloaded this file several days ago, and it was fine.  The errors and type of virus detected is:
Filename: setup.exe
Threat name: Heur.AdvML.BFull
Startup Item - No
Launched - No
Threat type: Heuristic Virus. Detection of a threat based on malware heuristics.
The file was never launched and was detected during saving the file.  I did download and install this file several days ago as I said and everything was fine.  I don't thing this is really a virus, as it is using Heuristic analysis engine to determine this, but I thought you should know.

**Comment by phw198** [comment]
Thanks for reporting.

:link: Issue #295
