### ISSUE TITLE
How to sync my Google Contacts with Outlook 365

### ISSUE THREAD

**Issue by gordon3175** [phw198/OutlookGoogleCalendarSync#342]
None of my Google contacts are showing up in Outlook. I'm using Outlook 365 annual subscription. I set up my Gmail email address, mail and calendar are working good, but no contacts. What do I need to do?

**Comment by phw198** [comment]
OGCS doesn't sync contacts or mail so not sure how you've set this up, but it's not something I can help with.

OGCS can sync meeting attendees within your appointments however.

**Comment by phw198** [comment]
:link: Feature request #407. Please give a +1 reaction there to show interest.
