### ISSUE TITLE
Total inc. recurring items spanning sync date range

### ISSUE THREAD

**Issue by cmo2k** [phw198/OutlookGoogleCalendarSync#343]
Everything has been working solid for about a week. Now receiving the following:
Total inc. recurring items spanning sync date range...
Failed to retrieve master for Google recurring event outside of sync range.
The following error was encountered during sync:-
The operation failed.
Operation aborted after 1 failed attempts!

Nothing has changed, even removed and re-installed and still no change. Please advise.
![capture](https://user-images.githubusercontent.com/32106485/30605528-486d4ee8-9d23-11e7-8bc4-094bb76bb6a9.JPG)
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1315191/OGcalsync.zip)

**Comment by phw198** [comment]
Hi - could you increase the logging level to `FINE`, reproduce the problem and then upload your log file again?

Thanks

**Comment by cmo2k** [comment]
Here you go. :)  Thanks.
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1321736/OGcalsync.zip)

**Comment by phw198** [comment]
Hi @cmo2k, I assume you didn't mean to close this issue? However, the log file is still only set at `DEBUG` - did you try and change it to `FINE`?

**Comment by cmo2k** [comment]
Paul, 
First of all, thanks so much for all of your work on this project and the expediency in communicating.
After I "found" the fine setting, I had a look through the log. I ran into this error: 
Found a master Outlook recurring item outside sync date range: 6/30/2015 8:30 AM

You've already covered this in another post. Since I'm syncing from Outlook (work) to Google, I deleted the recurring event (entire series) and voila, everything synced up as expected. I'll have the meeting organizer resend a new invite. Frustrating but not the end of the world. Keep up the good work!  Consider the ticket closed and expect a donation. :)

**Comment by phw198** [comment]
Thanks, and glad you got this sorted. 

Ideally I'd like to get to the bottom of what happened though, as it sounds like a bug that's needs fixing properly. Do you still have the log file that covers the error before you deleted the series?

**Comment by cmo2k** [comment]
Yes, I still have the log.  Would you like me to attach it to email or through the original ticket?

**Comment by phw198** [comment]
To the GitHub ticket if you could, please.
