### ISSUE TITLE
Attendees Setting Lost - 2.6.2

### ISSUE THREAD

**Issue by brozono** [phw198/OutlookGoogleCalendarSync#344]
Change to MainForm.cs to add
`cbAddAttendees_CheckedChanged(null, null);`
to
`private void syncDirection_SelectedIndexChanged(object sender, EventArgs e)`

Results in over writing the settings with this line
`Settings.Instance.AddAttendees = cbAddAttendees.Checked;`
in
`private void cbAddAttendees_CheckedChanged(object sender, EventArgs e)`

Likely fix is similar to a fix put in for Reminders ([d39e7ae8713a](https://outlookgooglecalendarsync.codeplex.com/SourceControl/changeset/db5ea1759421ee2e0df55083079664e8b7809ce3)) when of qualifying the set with Visible
`if(this.Visible) Settings.Instance.AddAttendees = cbAddAttendees.Checked;`

**Comment by phw198** [comment]
Thanks for the analysis :+1: 

:package: [Hotfix v2.6.2.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1319422/v2.6.2.1.zip) should solve it as you suggested [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Cheers!
