### ISSUE TITLE
Google Event Not Found [404]

### ISSUE THREAD

**Issue by BDJeff** [phw198/OutlookGoogleCalendarSync#345]
I get this error when syncing
```
Reading Google Calendar Entries...
ERROR: Unable to connect to the Google calendar.
The following error was encountered during sync:-
Google.Apis.Requests.RequestError
Not Found [404]
Errors [
	Message[Not Found] Location[ - ] Reason[notFound] Domain[global]
]

Operation aborted after 1 failed attempts!
```
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1322651/OGcalsync.zip)

**Comment by BDJeff** [comment]
Never mind.  User error.  I had to reauthorize the google account.

**Comment by phw198** [comment]
Hi @BDJeff - I can see you upgraded to v2.6.2 and reauthenticated to Google, but still got the error message afterwards. I'm intrigued to know how you resolved this issue?

**Comment by BDJeff** [comment]
I removed the Google account and then reauthenticated. That fixed it.
