### ISSUE TITLE
syncing from Outlook -> Google not working

### ISSUE THREAD

**Issue by bernie-mac** [phw198/OutlookGoogleCalendarSync#346]
[OGcalsync.log.2017-09-15.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1324611/OGcalsync.log.2017-09-15.txt)

syncing from Google to Outlook works okay, although there are times where recurring appointments won't sync with Outlook. However, the larger problem right now is that Outlook appointments won't sync with Google. Please advise. Thank you.

**Comment by phw198** [comment]
Couple of things happening here.

First is that you don't appear to have the rights to access Outlook appointment descriptions through OGCS, so it continually errors when syncing Outlook items to Google. Try turning off the sync of `Description` in OGCS settings.

Secondly, looks like you then reset the Google authentication by clicking `Disconnect Account` and then didn't reauthorise OGCS to manage your Google calendar - OGCS won't work unless you authorise it.

**Comment by bernie-mac** [comment]
Thank you for your response. Prior to writing to you initially, I had tried syncing with "Description" being off, but it didn't seem to make a difference. Separately, I do recall disconnecting the account as an attempt to fix the problem. So, after your response, I attempted to re-authorize access to my Google account; it appears as though OGCS received the verification code (I see the file "Google.Apis.Auth.OAuth2.Responses.TokenResponse-user" in the OGCS folder. However, I am getting the same result as before.  Can you tell by looking at the new log file as to whether OGCS has been authorized access to my Google calendar? If not, can you detail the correct steps for me to do so? Thank you for your time.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1352439/OGcalsync.log)

**Comment by phw198** [comment]
You have authorised OGCS to connect with your Google calendar, and that's working OK.

The only problem I can see is that the syncs were starting before you had changed the `Description` option to false. I note that you did change this halfway through a sync, and then try to abort the sync and restart it....problem being there's a bug with the abort function (issue #321).

Restart OGCS, and before a sync starts, change the `Description` option to false and click `Save`. Then let it sync - that should work!

**Comment by bernie-mac** [comment]
Okay, I think I have the Description option as FALSE (box is not checked). I even unchecked the Reminders attribute. However, I get the same result.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1379410/OGcalsync.log)

**Comment by phw198** [comment]
>First is that you don't appear to have the rights to access Outlook appointment descriptions through OGCS, so it continually errors when syncing Outlook items to Google. Try turning off the sync of Description in OGCS settings.

This was a bug also reported in #436 and fixed in 4b6b9c32f4a3b43ab9d27380a9109ebcec802b12 so will close this - will reopen if it's still a problem in v2.7
