### ISSUE TITLE
Deleted events not deleting off Google or Outlook 

### ISSUE THREAD

**Issue by jybruin** [phw198/OutlookGoogleCalendarSync#348]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1335930/OGcalsync.log)

If I create an event on Outlook it syncs to Google but once I delete from Outlook it does not delete from Google. 

If I create an event on Google it syncs to Outlook but once I delete from Google it does not delete from Outlook. 

This app looks amazing, has anyone found a way to fix this?

**Comment by jybruin** [comment]
Getting additional errors now "Updated Google event failed to save. Continue with Sync?" 

Attaching log 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1335960/OGcalsync.log)

**Comment by phw198** [comment]
For deletions you'll need to turn off the `Disable deletions` setting.

**Comment by phw198** [comment]
I can't see the additional error you mention in your second log file - everything seems to be working.
