### ISSUE TITLE
Issue Syncing Change to Single Occurrence of Repeating Meeting

### ISSUE THREAD

**Issue by bbobley** [phw198/OutlookGoogleCalendarSync#350]
Here's an issue I've seen. In fact, just now I carefully manually synced and saw the issue occur:

In Outlook, I have a regular monthly meeting. It was synced to Google Cal many months ago. Earlier today, the meeting organizer sent me an Outlook meeting message changing next month's meeting (and only that one occurrence) to a different day (From Oct. 10 to Oct 25). I clicked Accept in Outlook and that meeting (correctly) disappeared on October 10 and reappeared on October 25 in Outlook.

Then I ran a sync which finished with no error. But it did NOT make the change on GCal -- it still had the original Oct. 10 meeting. I then synced a couple more times (I even tried unticking the 'disable deletions' button, but that didn't fix it). Then when I synced again, the meeting in *Outlook* moved itself from October 25 *back* to October 10!  In other words, it appears that the incorrect GCal info moved back to Outlook (so now they are both wrong).  Luckily, I still had my Outlook meeting message, so I clicked "Accept" again and now I have it correct in Outlook, but still wrong in GCal. 

Log file attached:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1338466/OGcalsync.log)

What am I doing wrong? Any advice?

Brett

**Comment by bbobley** [comment]
An update: Today, I had a different meeting change dates (same scenario as above). But this time, after one sync, it was successfully moved on GCal!  So I have no idea why it didn't work in the example above (and has also failed on other occasions).

**Comment by phw198** [comment]
I'm assuming you're referring to the appointment `11/11/2014 2:00 PM (R) => "Monthly Meeting with Division Directors and Adam Wolfson"`? Something seems to have gone a bit haywire - in Outlook it says there is 1 exception for this recurring series within your sync period of a year (which is for the 10-Oct to 25-Oct change), but Google says it has _730 exceptions_!

For some reason Google has the Event on 10-Oct as "cancelled" and so it replicated this back to Outlook. I would suggest upgrading to the latest alpha (v2.6.2 or maybe v2.6.3 by the time you read this) and then:
1. Set OGCS to 1-way Outlook to Google sync
1. Delete the entire series in Google.
1. Sync from Outlook to Google to recreate it
1. Set OGCS back to 2-way sync.

Let me know if the problem recurs, but I'm hoping it's some long standing issue specific to this recurring series.

**Comment by bbobley** [comment]
yes, that is the one. I just took your advice and performed all four steps.  I'll let you know if I see this odd behavior again in the future.  Thank you.
