### ISSUE TITLE
Spend hours to remove/uninstall "Portable" Version without Success. Need urgent help

### ISSUE THREAD

**Issue by MichaMeyer** [phw198/OutlookGoogleCalendarSync#351]
Hi!

We have installed the portable version (in first step older version, then the newest one yesterday) in "C: Portables/OutlookGoogleCalendarSync" 

I tried to uninstall the application from an WIN 7 PC.  

I have removed the flag at "Autostart" several times and clicked onto "Save". if I restart application there is no more flag in the autostart button.

I removed the directory "OutlookGoogleCalendarSync" from "Portables"

**But every time the PC is rebooted, i get an errormessage that the "Exe file is not found". So windows does already try to start the application each time.**  

What I have tried:
- **all your uninstall instructions on  https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Uninstall using CMD Window in Administrator Mode**

- searched registry myself for "OutlookGoogleCalendarSync" using "Google"

- used "Autoruns.exe" from Microsoft but did not find any entry

- used msconfig, did not found any entry  

- there is no Uninstall in "Programs"

All was unsuccessfull.................

**So what to do to remove the Autostart Function to prevent the Errormessage????**

Greets Micha

**Comment by phw198** [comment]
Hi and sorry to hear you're having problem removing the portable version of OGCS.

What version did you start using OGCS? For quite a while now it's only put a registry key in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`, and I've just tested pointing this to a non-existant executable and it fails silently - so I don't think you have a stray registry key.

Older versions of OGCS simple put a shortcut in your `Startup` folder of the Windows Start menu. Could you have another look through your Start Menu and see if you have any shortcuts left for OGCS?

Does the error message not specify the actual executable that it can't find? **Could you screenshot the error message, please.** Have you looked through your EventViewer to see if there is any further details?

Note: If you ever had an entry for OGCS in your Control Panel > Uninstall Programs, then at some point you weren't using the portable version, but the installed version.

**Comment by MichaMeyer** [comment]
Thank you for your answer!

Unfortunatly I do not remember the old version exactly... 

i think we started with this one:
http://www.chip.de/downloads/Outlook-Google-Calendar-Sync_99573406.html there already the flag for "Autostart" did not delete the autostart thenm i tried the latest version from Githup (ZIP Version)

on HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run there is no entry.

_Older versions of OGCS simple put a shortcut in your Startup folder of the Windows Start menu:_
 I looked at 
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
and 
%systemdrive%\users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
and did not find an entry

Errormessage:
![error](https://user-images.githubusercontent.com/32386846/31047873-b0294daa-a612-11e7-8885-92ad352e769a.gif)

no there was never an entry in "Control Panel > Uninstall Programs" I copied the application myself into "Portables" Directory"

So where to search?

**Comment by phw198** [comment]
I've been scratching my head on this, but am stumped. However, as you mentioned www.chip.de I downloaded the app from there and ran the executable on a VM - I've no idea what this site is but it's behaving like malware. They appear to have wrapped OGCS in an installer of their own which goes and "check for components online" and then pops up various screens in German....a free scan; an amazon plugin; a free game?!?! It does finally appear to install the CodePlex ClickOnce v2.5.0 version of OGCS, but I'm not liking all the mal/adware it's pushing! :angry:

You can see the [code in v2.5.0](https://github.com/phw198/OutlookGoogleCalendarSync/blob/v2.5.0-beta/src/OutlookGoogleCalendarSync/Program.cs) is already only [using the startup registry key](https://github.com/phw198/OutlookGoogleCalendarSync/blob/e4a1efdd4e918946473ea524ff6c5663d0dbab9c/src/OutlookGoogleCalendarSync/Program.cs#L180-L184) in `Software\Microsoft\Windows\CurrentVersion\Run`, along with some legacy code to remove any remaining shortcuts from earlier versions.

Setting up either shortcuts or registry keys and then removing the target OGCS executable does not cause the popup you are getting - they fail silently. Unfortunately, I don't know what else to suggest...I hope you can work it out!

**Comment by m-rm** [comment]
Hi! There is a nice utility provided by Microsoft to find autostart applications. It's called Autoruns and you can download it from https://technet.microsoft.com/de-at/sysinternals/bb963902.aspx. You can enter "outlook" into the filter field to find it. You can also remove the entry directly from this utility.

@phw198 Chip is a well known German site that distributes software. Unfortunately some years ago they started with this malware infested installer. Although you are still able to download the official installer by choosing "Manuelle Installation". Unfortunately when you are in a German speaking country Chip is always one of the first results when searching for any software on Google.

**Comment by MichaMeyer** [comment]
Thanks for all your help. I installed 2.5.0 again and uninstalled it, then the Autostart was removed... So it. Now works... 

Chip.de is a well known German PC newspaper and I always use not the "Downloader" of them I use the "Manual Download" 

Thanks Micha
