### ISSUE TITLE
Google to outlook doesn't sync.

### ISSUE THREAD

**Issue by adevero** [phw198/OutlookGoogleCalendarSync#352]
I believe I have all the stetting done correctly. Outlook to Google is working fine. But when I create a new event on my android google calendar, it never gets to outlook.  I am not a developer, so my expertise to document is limited. This is causing massive confusion. Help!

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).
