### ISSUE TITLE
COM error 0x80010100

### ISSUE THREAD

**Issue by mgonzalez10** [phw198/OutlookGoogleCalendarSync#353]
Hi. 
I have obtained that error during the sync process: 

> COM error 0x80010100 encountered.
> Please check if there is a published solution on the OGCS wiki.

How can I solve it?.
Thanks in advance.

Regards.

**Comment by phw198** [comment]
There's [nothing in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors) for that error, though it does look very generic.

:spiral_notepad: Please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by mgonzalez10** [comment]
Now it is working fine!.  
I can't reproduce the error again so, mayby issue could be closed.
