### ISSUE TITLE
Version 2.6.2 application unexpectedly terminated!

### ISSUE THREAD

**Issue by hein23** [phw198/OutlookGoogleCalendarSync#354]
The application is not working anymore on my pc (win 10/64 ,outlook 2016)
Error:
The COM-Object type "Microsoft.Office.Interop.Outlook.ApplicationClass" could not be changed to
interface type "Microsoft.Office.Interop.Outlook._Application"
Queryinterface IID "{00063001-0000-0000-C000-000000000046} error:
Interface not registert exeption from HRESULT: 0x80040155

Registry problem ? how to solve ?
Thank you !
![grafik](https://user-images.githubusercontent.com/32483491/31123816-de6881c8-a841-11e7-8a8f-d21e4b77c610.png)

**Comment by phw198** [comment]
Solution is [in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered).

**Comment by hein23** [comment]
Not working.
I have done this:
1. 
%systemroot%\SysWoW64\regsvr32.exe %Windir%\SysWoW64\Ole32.dll               Done OK

2.1
 HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\Interface\{00063001-0000-0000-C000-000000000046}\TypeLib
default entry  was 9.6

2.2 
HKEY_CLASSES_ROOT\TypeLib\{00062FFF-0000-0000-C000-000000000046}
same entry 9.6 no other 9.X
so done OK

3. 
reglibv12.exe "C:\Programme\Microsoft Office\root\Office16\MSOUTL.OLB"             Done OK

4. 
reboot

5. start of the OutlookGoogleCalendarSync
same problem:
![grafik](https://user-images.githubusercontent.com/32483491/31136927-df21a252-a869-11e7-8728-2e81fe9646f9.png)

is the value "_Application" right ?

**Comment by hein23** [comment]
Sorry step 3. was not working
regtlibv12.exe "C:\Programme\Microsoft Office\root\Office16\MSOUTL.OLB" 

![grafik](https://user-images.githubusercontent.com/32483491/31137181-bbfa52be-a86a-11e7-80a3-75ae52a7b146.png)

**Comment by hein23** [comment]
Fixed with: 
regtlibv12.exe "C:\Programme\Microsoft Office\root\Office16\MSOUTL.OLB"
in Administrator CMD.
