### ISSUE TITLE
Nonsense deletations

### ISSUE THREAD

**Issue by tadeas1** [phw198/OutlookGoogleCalendarSync#356]
Probably there is a bug in the application. Sometimes when I create a new entry in Outlook calendar, the application wants to delete this new entry instead of synchronization it with my Google Calendar. Could you implement synchronization when I click the "No" button on the delete confirmation dialog? When I click the "No" button, the application keeps the entry rightly in Outlook calendar, but at next synchronization show me the confirmation dialog again. It is nonsense. If I do not want to delete an entry, I want to synchronization the entry.

**Comment by phw198** [comment]
So you have 2-way sync configured? How are you creating the new entry in Outlook? Copy and pasting an already synced appointment?

**Comment by tadeas1** [comment]
Yes, I have 2-way synchronization configured. You have right, I sometimes use copy and pasting old appointment for creating new appointment. In this case, the application always wants to delete new entry. Is it alright?

**Comment by phw198** [comment]
This issue is already captured under #224. v2.6.2 should largely resolve the problem (a slight improvement will also be in the next version too), so please upgrade to the latest alpha.

**Comment by tadeas1** [comment]
Unfortunately, version alpha 2.6.2 did not resolve the problem. So it cannot be used the method copy and paste for creating new entries.

**Comment by phw198** [comment]
If you can avoid using copy and paste, then that's the simplest solution. I'm not clear whether v2.6.2 didn't solve the existing items that have already been copied and pasted (I wouldn't expect it to), or whether you tested a new copy and paste. If the latter, please post further updates on #224.

Thanks.
