### ISSUE TITLE
Authorize Google Access

### ISSUE THREAD

**Issue by 60116011** [phw198/OutlookGoogleCalendarSync#358]
Hi,

This was working fine on my previous laptop, I've tried to set it up now and the Authorize Google Access screen, doesn't generate a new browser window, and I have no way of generating an access token. I'm on Windows 10 with Chrome as the default browser. Is there another way I can generate the token?

**Comment by phw198** [comment]
Upgrade to the latest alpha v2.6.2 - that should work better with Chrome.
