### ISSUE TITLE
Entries getting deleted randomly

### ISSUE THREAD

**Issue by HerrRiebmann** [phw198/OutlookGoogleCalendarSync#359]
I got a bad feeling this week, that my working calendar (O365) seems quite empty.
Appointments have randomly been gone!
At first I was unsure if it really is related to the synch, so I changed the setting to "Confirm deletions". And voilá it asks me to remove an entry which I haven´t touched since weeks.
Opened Google-Calendar and it was gone there!

Now, restarted the PC and the same thing happened again! Popup-Message says "2 entries deleted" in Google. I´ve opened the GCalendar and saw how it disappeared. Some seconds later, the confirmation prompted up, if I´d like to remove that entry in Outlook from 2017/11/08 and afterwards from 2017/11/07.

Both entries have been similar on both sides since about a month and haven´t been touched!
Due to the fact, that I don´t know what else has been deleted, I deactivated it complete...

On the other side, I can see some (recurrent) birthdays are getting duplicated. I think there is something strange going on!

If I can provide any log or test something, I´ll do so
I´m using the latest Version: 2.6.2.5.

**Comment by phw198** [comment]
This seems very odd. If you're able to provide your log file(s) that would help - possibly going back to when you think this first started happening.

:spiral_notepad: [See instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file) on how to provide your OGcalsync.log file.

Note, you should be able to retrieve deleted items from the Outlook _Deleted Items_ folder and/or Google _Recycle Bin_.

**Comment by HerrRiebmann** [comment]
I will create a bidirectional synch. for just one day and try to reproduce it.
Sadly the Recycle bin is not very helpful, because it doesn´t know about the deletation-date, but the creation-date. Which can be anytime :(

My guess, and it seems to be related to it:
Setting entries as private in one side, modifies them and on the next check, they will not be recognized as the entry on the other side. Or maybe recognized as a delete and insert as private.

The setup was like that:
- Bidirectional Synch.
- Entries from Gmail must be private in O365.

Gmail deletes the entry first and O365 afterwards on the next synch.

**Comment by ikostits** [comment]
@phw198, I am having the same problem. At some point I reinstalled the OGCS, reset all the calendars, created a new google calendar to be synced. After a few days the random deletions started happening again. I have sent you the log file by email.

**Comment by phw198** [comment]
@shalabuda Had a quick look at your logfile, but you're not running the latest alpha v2.6.3. Please upgrade to that and see if it improves. Probably best to start with a clean Google calendar again too if possible.

The only way I know of to cause the issue you describe is to copy and paste existing Outlook entries that have already been synced - fixed in #224.

**Comment by HerrRiebmann** [comment]
I can definitely say, that this happened to "not copied"-entries.
Also entries, where I was invited and nothing has changed ever since.

And I´ll also upgrade to the latest beta, reduce the synch to one-two days and test with it. Didn´t got time to do that earlier :-/
And in a clean surrounding, where I don´t delete invitations from my boss... ;)

**Comment by ikostits** [comment]
Same here, not copy-pasted events...

I've installed the latest alpha version. I'll report back when I see if the issue is resolved or not.

**Comment by ikostits** [comment]
@phw198, today some events started to disappear again. I am using the latest alpha version. I have sent you the log file by email.
