### ISSUE TITLE
Unable to cast COM object [0x8002801D]

### ISSUE THREAD

**Issue by mandlerd-wk** [phw198/OutlookGoogleCalendarSync#368]
![error](https://user-images.githubusercontent.com/5159692/31600436-bbac6fd6-b256-11e7-93a5-78b08fdb1270.png)

This error Pops up when I start the portable Version(v2.6 and 2.5). Using Windows 7 and Outlook 14.0.7188.5002 (32bit)

**Comment by blakotako** [comment]
The same error on Windows 10 64bit, Office 2016 64 bit, OGCS Version 2.6.0.0 and 2.6.2.0 (portable and installer). The Office registry keys {00063001-0000-0000-C000-000000000046} and following {00062FFF-0000-0000-C000-000000000046} are in place and seem OK.

**Comment by phw198** [comment]
Fix is [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002801d---type_e_libnotregistered).

@mandlerd Have you gone through this?

@blakotako Sounds like you've already checked this?

**Comment by blakotako** [comment]
Yes, I've checked this. I've registered the Ole32 and MSOUTL.ODB and checked the registry keys. It all didn't work.

**Comment by blakotako** [comment]
OK, I got it to work, but still don't know what the right solution was. I've deleted the registry keys and reinstalled Office.

**Comment by Smitty357** [comment]
Is there a way to correct this without re-installing Office? I am in a corporate environment, and it is extremely hard to get the installer. Running Office 365.
Also the error message is slightly different. 
![image](https://user-images.githubusercontent.com/4584982/31946897-add8cef2-b898-11e7-88c7-83972421d693.png)

**Comment by phw198** [comment]
@Smitty357 Your error's not related to this ticket. Different error, [different fix](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary) - should just be able to run an Office Repair (as also reported in #288)..
