### ISSUE TITLE
Sync fails with the error: "an-object-reference-not-set-to-an-instance-of-an-object"

### ISSUE THREAD

**Issue by McButch** [phw198/OutlookGoogleCalendarSync#369]
Hello,

I am using version 2.6.0 with outlook 2013 and can't sync one of my calendar entrys to google. During the last week everything was fine but now I get the error: "an-object-reference-not-set-to-an-instance-of-an-object". (I get the error in german because my outlook is german)

I created a few more test entrys and those sync fine. I don't remember changing anything since the last week, when everything was fine. 

I have attached my logfile

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1386945/OGcalsync.log)

**Comment by phw198** [comment]
Try upgrading to the latest alpha and see if the problem disappears.

**Comment by McButch** [comment]
Using the latest alpha resolved the problem. I did a full uninstall first tho.
