### ISSUE TITLE
Shared calendar sync - meeting not syncing

### ISSUE THREAD

**Issue by gnubee40** [phw198/OutlookGoogleCalendarSync#370]
Hi! I changed the setup at work and now I encounter a new problem with 2-way sync.

Setting:
Outlook: Shared ressource calendar, where I have full write access.
Gcal: A shared sub-calendar only for these ressource appointments

New Appointments: I use the function "Meeting with all", where I include my personal calendar and the ressource calendar. This means: Primary appointment is in my calendar, the ressource calendar is invited to meeting both as attendee and as a ressource. The ressource cal auto-accepts the meeting, and it shows both in the ressource calendar and my personal Ocal.

1. sync outlook -> gcal (the last sync in log). The meeting gets synced from ressource cal to Gcal. 

First 2-way sync: The appointment is not recognized in GCal as connected to the outlook meetin-> Outlook appointment in ressource cal is deleted.
Second 2-way sync: Gcal event is also deleted.

I just realized I might need to activate sync Attendees to prevent this from happening. Will post, if this has desired effect. So far after checking this I had one 2-way sync WITHOUT the meeting getting deleted.

So maybe an non-issue. Possibly, I Just need to make sure to check "Sync attendees" to ensure that meetings stay linked in Gcal. I will keep you posted, as it seems to be an intermittent problem, which is a bit difficult to reproduce reliably. It often happens, when I change the time of the meeting. As our Exchange server seems a bit shaky at times, working with shared ressource calendar has not been trouble free so far.

Log: https://gist.github.com/gnubee40/6642588d458e382eb5bb7d9d355acbdc#file-ogcalsync-log

**Comment by gnubee40** [comment]
Ok - now with "sync attendees" option checked - I moved the meeting around in my own calendar a bunch of times.  The ressource-calendar auto updates itself accordingly.
And when I bi-direct-sync it to gcal, everything behaves as expected.

So issue already solved. Take home messages: If the calendar that gets synced has meetings where it only is attendee, syncing attendees is necessary, so that the link to Gcal is maintained. Otherwise the meeting gets evt. deleted in 2-way sync.

**Comment by gnubee40** [comment]
Ok - I was too quick here. After a couple of syncs - and the PC being in standby - OGCS has again lost the link and wants to delete this appointment. latest log attached. 

There was an error about the RPG server, but this was probably due to me erroneously closing outlook - or due to the standby. I have "confirm deletion" checked which causes the sync to halt. When the pc goes to standby in the mean time, these error messages comes up. 

https://gist.github.com/gnubee40/1235d0f7defc7e650a86da16587a36a0#file-ogcalsync-log2

and the csv lines of the appointment in question - which seems to merge with others in the google CSV?
https://gist.github.com/gnubee40/9e7de8eec50dedd7021d3e595a4eeec3#file-csv_o_g

I suspect there might be something wrong with this appointment. Have deleted it and recreated it along with a test appointment and will see how it develops.

**Comment by gnubee40** [comment]
Without the "Sync Attendees" option (forgot to save settings) I have so far synced twice this morning without any unwarranted deletions. Must have been a random corrumpation of a single appointment (see CSV).

**Comment by gnubee40** [comment]
Well - this seemed to be a one trick pony. I have been adding and moving around 4 different test appointments in 2 different ways. They were not deleted by OGCS during several syncs over the day. I just deleted them in Outlook, and the sync deleted them correctly in Gcal.  It seems some corruption happened with the one appointment. Probably a random error.
I will keep this open a couple of days and then close it, if nothing else happens.

**Comment by phw198** [comment]
Thanks for taking the time to post all these details. Looks like the issue hasn't return though, which is good.
