### ISSUE TITLE
I've set up my calendars but it can't see any Outlook calendar entries

### ISSUE THREAD

**Issue by English-Pete** [phw198/OutlookGoogleCalendarSync#371]
Hi there

I've set up my calendars to syn from an Outlook 2010 Internet calendar but when I sync - it can't see any Outlook calendar entries :(

Do you know why?

I hope you can help!

**Comment by phw198** [comment]
On the Outlook tab in OGCS settings, there's a `Test` button under `Regional date format` - make sure that returns some appointments. If it does, check you haven't filtered all the categories out!

**Comment by English-Pete** [comment]
Thanks for the reply. It returns 66 calendar items when I do the test - but
when I syn it doesn't find any Outlook Calendar Entries :(

**Comment by English-Pete** [comment]
*when I SYNC it doesn't find...

**Comment by phw198** [comment]
Yes, so check you haven't got the category filter excluding everything (or including nothing).

**Comment by English-Pete** [comment]
Sorry, I forgot to mention that I checked that as well. There is a tick in
each box for INCLUDE. I've saved it and still get the same results as
before. I get exactly the same results when nne of the boxes are ticked.

I've tried it with my internet calendar and default calendar and Outlook
data file calendar. They all find different numbers of calendar items - but
none of them sync...

I've added a couple of screenshots, maybe you can see the problem with
these?

**Comment by phw198** [comment]
Hi - attachments don't work when updating the GitHub ticket via email. Please could you log in to GitHub and upload your screenshot - or better yet, your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

Also, please upgrade to ~~v2.6.2~~ v2.6.3 if you haven't already.

**Comment by phw198** [comment]
You may also have been hitting #364, which has been fixed in v2.6.4. 

Have you tried filtering no categories with the `exclude` option picked?
