### ISSUE TITLE
Google Calendar Zero Duration Appt Created as 1 Hour Appt in Outlook 2010

### ISSUE THREAD

**Issue by 1h8fulkat** [phw198/OutlookGoogleCalendarSync#374]
I know this is an issue with the way Outlook 2010 handles zero duration meetings.  When I create a meeting in Google for zero duration:

![image](https://user-images.githubusercontent.com/11942449/31906043-04dc7f78-b7fe-11e7-9750-ec01b54512ea.png)

It is created in Outlook with a 1 hour duration:

![image](https://user-images.githubusercontent.com/11942449/31906071-199074b0-b7fe-11e7-8924-90a83b1a4a44.png)

And generates a sync error:

![image](https://user-images.githubusercontent.com/11942449/31906081-22d2b9a2-b7fe-11e7-9249-71457100bfe9.png)

Is there any way to have an option to set the duration to 1 minute vs 1 hour?

**Comment by phw198** [comment]
Admitedly, I'm on 2016, but I can't replicate this - creating a zero minute Google entry sync to Outlook without a problem and isn't set as an hour duration. OGCS takes the start and end time values from Google and explicitly sets them, so there is not opportunity for the end to suddenly become 60 minutes later than the start.

Your last screen shot with the Outlook send/receive error looks distinctly like an ICS calendar that's been imported. OGCS doesn't deal with VEVENT abd DTEND attributes, so I don't think this is actually anything to do with OGCS...
