### ISSUE TITLE
Keeps syncing reminders, even though I have it set to not sync reminders. It even adds reminders to meetings I have no reminders for. Outlook to Google.

### ISSUE THREAD

**Issue by witkows6** [phw198/OutlookGoogleCalendarSync#377]
|Question|Answer|
|:---|:---|
|OGCS version | v1.2.3.4 |
|Installed or Portable | Installed |

**Expected Behaviour**  
Update here

**Actual Behaviour**  
Update here

**Steps to Reproduce the Issue**  
1. Step 1
1. Step 2 

**Any other information**  
Update here

:spiral_notepad: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by phw198** [comment]
You haven't provided any of the information requested.

Anyway, try turning off your default reminder you've no doubt configured on your Google calendar.

**Comment by phw198** [comment]
:link: Enhancement #366

**Comment by witkows6** [comment]
Actually, I have all reminders turned off. What do you need logging for an
error like that for? I'll just find another way to do it if you're going to
be rude about it.
