### ISSUE TITLE
Events have stopped syncing completely

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#378]
|Question|Answer|
|:---|:---|
|OGCS version | v2.6.3.0 |
|Installed or Portable | Installed |

**Problem Description**
Everything was running fine until about a week or so ago.  Nothing was changed or updated to my knowledge but it just stopped.  It appears to work fine, and I am not getting any error messages but it is not reading new events in Outlook .  No matter how many new events are added, I keep getting message that 0 deleted, 0 created, 0 updated.

:spiral_notepad: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1432100/OGcalsync.log)

**Comment by phw198** [comment]
Your log file doesn't show much because you've turned off logging :smirk: 

Turn logging back on to `DEBUG` level whilst we troubleshoot, and then experiment with different settings under the Regional Date Format on the Outlook tab. Check with the `Test` button until it returns the expected number of items.

**Comment by ghost** [comment]
Here is the log with the Debug turned on.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1435782/OGcalsync.log)

**Comment by ghost** [comment]
FYI, I changed the regional date format to "Full Month" from "default" and it appears to be working again.  My question then is: why did it suddenly stop working with the default setting.  It had been working fine for years with that setting and to my knowledge no settings were changed in OGCS or Outlook.

**Comment by phw198** [comment]
I would imagine your Windows regional or date/time settings have changed. Looks like the default Windows time format is now `h꞉mm tt` where `tt` is the AM/PM - Outlook doesn't cope with that very well..
