### ISSUE TITLE
Remove settings.xml upon uninstall

### ISSUE THREAD

**Issue by adevero** [phw198/OutlookGoogleCalendarSync#379]
**Problem Description**  
Trying to do a clean install but the data is still there when I re-download program and reinstall. 

:spiral_notepad: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by phw198** [comment]
[Check the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#how-do-i-wipereset-the-configuration).

**Comment by adevero** [comment]
Hi Paul,

I did, but thank you; found no help there  (or at least not any I understood). I work in tech and am conversant, but not a developer.

I found a different program. It was a little more challenging to install, but it’s working.

I wish I could have made it work as I really liked it while it did. I’m sure it’s my failing.

Best,

Amie

**Comment by phw198** [comment]
OK, but did you actually follow the link I provided? It took you to a section with a handful of steps to delete the `settings.xml` file.

:bulb: I'll log removal of this file (and folder) upon uninstall as an enhancement.
