### ISSUE TITLE
Why do you want to get access to my Addressbook?

### ISSUE THREAD

**Issue by Johnnii360** [phw198/OutlookGoogleCalendarSync#380]
:memo: Please use the below template to report your issue.

----

**OGCS Version**: v2.5.0.0  
**Installed or Portable**: Installed

**Problem Description**  
OGCS wants access to my Address-book, Why? For what is it necessary?

**Steps to Reproduce the Issue**  
Just starting.

**Any other information**  
\-

:spiral_notepad: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by phw198** [comment]
To identify who you are (the account owner) and if you are the organiser of appointments in Outlook. Also to get the email address of meeting attendees if you are syncing them to Google. Note, there are improvements around this in the more recent alpha releases of OGCS.
