### ISSUE TITLE
Meeting start dates off by 1 hour, sometimes later, sometimes on-time

### ISSUE THREAD

**Issue by raedaq** [phw198/OutlookGoogleCalendarSync#381]
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
First time user, pardon the stupid questions!
All went according to plan, I downloaded 2.5.0.0, updated through the application to 2.6.0.0, went into my google account created a special calendar (to mitigate damages if they occurred), went into OGCS, configured everything and hit Sync. A few moments later, beautiful meetings showed up in my G-Calendar. Went to check out if the details were good (24 instances sync-ed). Results:
1. there was 1 recurring meeting had a start time later by 30 minutes
2. some recurring meeting had a start time later by 1 hour
3. some recurring meeting had a start time on time

I don't know what to make of it, there is no daylight savings where I am in (Dubai), time zones all matched, I deleted the calendar and did the whole exercise again with the same results.

The issue seems to be with recurring meetings

**Steps to Reproduce the Issue**  
1. Created a new google calendar
2. Made sure time zones matched on google calendar, outlook calendar, and my machine's
3. Installed OGCS 2.5.0.0.
4. Updated OGCS through app to 2.6.0.0
5. Started sync-ing

**Any other information**  
Outlook 2013 (15.0.4745.1000) 32-bit
I can see time zones have come across correctly in my Google Calendar

:spiral_notepad: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by miniminime** [comment]
Sitting in Switzerland I can confirm that there is an issue with daylight savings. Since last Sunday we changed the time -1 hour and all my entries are now off by that. I deleted my calendar and synced again and it's still wrong in Google calendar, but correct in Outlook. I have applied the same settings and timezone otherwise, meaning the current time in Google calendar shows the correct time.

**Comment by phw198** [comment]
There's a [note in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#old-events-not-observing-daylight-saving) about this - does the workaround work if you try it on one of the problematic items?

**Comment by dtucny** [comment]
The note in the wiki doesn't seem to cover the situation of a received recurring meeting request that outlook has converted the start time and end time of the series, but, then adjusted on individual instances post DST start/end. The series itself cannot be modified in outlook...

**Comment by phw198** [comment]
@dtucny Not sure what version of OGCS you're running, but timezone problems should be resolved through Issue #486 and #67 - the latter which only has a hotfix released so far.
