### ISSUE TITLE
Syncing stopped

### ISSUE THREAD

**Issue by jarnott001** [phw198/OutlookGoogleCalendarSync#383]
:memo: Please use the below template to report your issue.

----

**OGCS Version**: v2.5.2.0  
**Installed or Portable**: Installed

**Problem Description**  
I only sync from Outlook to Google & it stopped

**Steps to Reproduce the Issue**  
1. Try to Sync
1. 

**Any other information**  
https://gist.github.com/jarnott001/3378bf25621cc55eeca6c4cba3cf35b9

:spiral_notepad: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by phw198** [comment]
Hi, your log file doesn't show it's stopped - it detected and compared 16 Outlook and Google items but there were no changes to sync.

Or are you expecting it to detect more calendar items? In which case maybe check #378.

Any reason you're choosing not to upgrade OGCS?
