### ISSUE TITLE
Can't create a new event in Google

### ISSUE THREAD

**Issue by kogurtsova** [phw198/OutlookGoogleCalendarSync#384]
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
During the synchronisation, there is an error message that new events can't be created in Google Calendar.

**Steps to Reproduce the Issue**  
1.  Click "Start Sync"

**Any other information**  
\<Update here>

:spiral_notepad: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

https://gist.github.com/kogurtsova/466731ea4521ccbc88e04e95dd6c66cd

**Comment by phw198** [comment]
Hi @kogurtsova, could you try disconnecting your Google account from OGCS and then reauthenticating to Google?

Would also be worth upgrading to the latest alpha release (v2,6.3) first too...
