### ISSUE TITLE
1 way sync does not delete items on target that were deleted on source

### ISSUE THREAD

**Issue by fors6630** [phw198/OutlookGoogleCalendarSync#386]
**OGCS Version**: v2.6.2.5 (patched from enhancement #186 )
**Installed or Portable**: Installed

**Problem Description**  
I have 1 way sync setup, from gcal to my work outlook.  When a reoccuring meeting is deleted from gcal, it still exists on my outlook calendar.  Shouldn't it have been deleted?  

In case it helps, I'm using these options to set the target entries: 
- "set entries as private" 
- "set entries as free/available" 

____________

I've noticed this issue on multiple prior versions, where leftover entries on the target exist after deleting them on the source.  I've had to clean these up manually using the OGCS custom fields in outlook, so am not submitting it upon first appearance.

**Comment by phw198** [comment]
You've unchecked "Disable Delete" have you?

**Comment by fors6630** [comment]
Look at that, new functionality I couldn't see right in front of me.  Problem solved, thanks Paul and sorry for missing that option.     :)

And, just to say it, I like the option you have for either prompting for confirmation or not.  Great work...going to buy you a beer next...

**Comment by phw198** [comment]
Add warning when deletion should be made, except for deletions being disabled.
