### ISSUE TITLE
Obfuscation rules cannot be saved permanently

### ISSUE THREAD

**Issue by webvet-ws** [phw198/OutlookGoogleCalendarSync#388]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.0.0  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>
Obfuscation rules cannot be saved permanently. Closing and restarting the application they are gone and need to be set up again. It only remembers the "Word obfuscation" checkmark but not the strings configured for replacement.

**Steps to Reproduce the Issue**  
1. \<Update>
1. start program
2. define obfuscation rules
3. close program
4.restart program
5. look up obfuscation rules

**Any other information**  
\<Update here>
Unrelated: Should document that regular expressions are used, so escaping of special characters like ( ) - is required in obfuscation rules (or better do this programmatically when reading the rules)

**Comment by phw198** [comment]
Fixed in v2.6.4
