### ISSUE TITLE
 Entries in Google Calendar are deleted if there is no entry in Outlook

### ISSUE THREAD

**Issue by Panache1** [phw198/OutlookGoogleCalendarSync#389]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  Yes
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  Emailed to you.

----

**OGCS Version**: v2.6.3.0
**Installed or Portable**: Portable

**Problem Description**  
If there is no corresponding calendar entry in Outlook, OGCS tries to delete the Google calendar entry instead of adding it to Outlook.

**Steps to Reproduce the Issue**  
1. Create an entry in the Google calendar (do not create an entry in the Outlook calendar)
2. Set OGCS to:
     a. Direction: Outlook<->Google 
     b. Uncheck Disable deletions
     c. Check Make application portable
3. Begin Sync

OGCS will ask you to confirm the deletion of the event created in Google.

**Any other information**  
Works as expected if direction is set to Outlook<-Google.

**Comment by Panache1** [comment]
I think part of the problem is that Push Outlook changes immediately does not appear to be working.  Changes made in Outlook aren't pushed to Google until the next scheduled calendar sync.

I am currently testing having two instances of OGCS running for each calendar, one with Outlook->Google and one with Outlook<-Google.  So far that appears to be working, except when they both try to run at the same time, and I get a synchronization failed error.

**Comment by phw198** [comment]
How are you creating the entry in Google calendar? Duplicating an existing one that's already been synced?

Having 2 instances of OGCS on the same calendars, one for each direction is likely to cause chaos. If O->G fires before G->O, then yes, I would expect it to want to delete a new entry in Google...unless you have `Merge entries` checked, but I wouldn't recommend this configuratio as nothing will ever get deleted even when it "should". 

2-way sync with a single instance _should_ fit exactly your requirements.

**Comment by phw198** [comment]
Glad you've got it sorted 🙂
