### ISSUE TITLE
How to uninstall the application fully?

### ISSUE THREAD

**Issue by DP0007** [phw198/OutlookGoogleCalendarSync#391]
Hello - I have uninstalled the application, but when I reboot my computer the application is still there and trys to connect w/ Outlook.  How do you complete remove the application?

Regards

:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Hi, you've not said which version of OGCS you've been using. Uninstall details can be [found in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Uninstall) though.

**Comment by DP0007** [comment]
I believe it’s the 2.6 version. I have uninstalled it from my computers control panel, but when I reboot, it’s still asking for access to my email (outlook) and your splash page shows up until I close it 

Do you have a registry app to completely remove all traces of the app? 

All the best,

Dan Park

**Comment by phw198** [comment]
Instructions are in the link I gave previously.
