### ISSUE TITLE
The 1st manual sync will be failed silently

### ISSUE THREAD

**Issue by PipperL** [phw198/OutlookGoogleCalendarSync#392]
**OGCS Version**: v2.6.3.0 
**Installed or Portable**: Portable

**Problem Description**  
In 2.6.x, I found that there is something strange when I manually do the sync.
The 1st manual sync will be failed silently, the 2nd sync will be successful.
Via the log there will be a 403 forbidden when doing the 1st sync.
I am behind the company firewall and I am not sure if this is relevant.

**Steps to Reproduce the Issue**  
1. Start OGSC.
2. Do a manual sync (1st). There will be no sync occurred.
3. Do a manual sync (2nd). Everything become normal, the sync process will be executed normally.

**Any other information**  
Please take a look at ogsc.log
[ogsc.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1477405/ogsc.log)

**Comment by phw198** [comment]
Is this still happening with later releases? If so, once you have successfully synced,
1. Open your token file `D:\Program Files\OutlookGoogleCalendarSync_tmp\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user` in notepad
1. Copy the value from the first field `access_token` and append it to the end of `https://www.googleapis.com/plus/v1/people/me?fields=emails&access_token=
1. Paste this into your browser - does it return your email address or give a 403 Prohibited error?

If it's prohibited, then I suspect your firewall is blocking access to www.googleapis.com....

**Comment by PipperL** [comment]
Thanks for tracking this issue.
This issue still occurred to me before today, my workaround is by doing second sync.

After receiving your email and trying your instruction today,
It seems an Google+ API is not enabled.
The browser returned the following output:

> {
>  "error": {
>   "errors": [
>    {
>     "domain": "usageLimits",
>     "reason": "accessNotConfigured",
>     "message": "Access Not Configured. Google+ API has not been used in project 144631171753 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=144631171753 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
>     "extendedHelp": "https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=144631171753"
>    }
>   ],
>   "code": 403,
>   "message": "Access Not Configured. Google+ API has not been used in project 144631171753 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=144631171753 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
>  }
> }

So I tried to enable the "api for project 144...753", waited for several minutes and tried again.
The browser now return the account info:

> {
>  "emails": [
>   {
>    "value": "___MYEMAIL__",
>    "type": "account"
>   }
>  ]
> }

Now everything works perfect! Thank you!
