### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by tmeckel** [phw198/OutlookGoogleCalendarSync#395]
**Problem Description**  
Unable to compile pulled code

**Steps to Reproduce the Issue**  
Try to compile by pulling code base from GitHub into empty directory,

**Any other information**  
packages.config is missing in GitHub repository.

**Comment by phw198** [comment]
Can you try with the file [in this zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1500389/packages.zip) - if that's all that's missing I'll get it committed.

Thanks

**Comment by phw198** [comment]
Any update?
