### ISSUE TITLE
OGCS returns 0 items to sync

### ISSUE THREAD

**Issue by matt22free** [phw198/OutlookGoogleCalendarSync#397]
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
Hi,
I just install and test OGCS.
On the Outlook settings tab when i click Test it returns 0 items, i try with any date format, and when i try to sync, it do the same.
I try to create a new calendar with 1 item, OGCS can see it, and even with this one, 0 Items is returned.

**Any other information**  
It's my work outlook calendar, and i use VPN To access. 

**Log File**
https://gist.github.com/matt22free/c59f75c356e06a23324e1392a325334c

**Comment by phw198** [comment]
Seems odd, I've changed my test machine to "French (France)" region and it seem to work OK.

The calendar you have picked for sync, "Calendrier", is that the default calendar in your mailbox? If not, could you try picking the default calendar and then testing how many items it picks up?

Could you also increase the logging level to `FINE`, run some tests and then upload your logfile again.

**Comment by matt22free** [comment]
Hi, 
Thanks for reply, yes 'calendrier' is my default calendar, ans Test is for ... testing.
I change logs settings, et try some test with filter, but i allways have 0 items. ...

https://gist.github.com/matt22free/c8095fb25038c982f9f2932f8f4acdd8
https://gist.github.com/matt22free/3cb51ce1788496612e44d1dc50c13dc6

**Comment by phw198** [comment]
OK, thanks - I can see that there are [90 items in the calendar](https://gist.github.com/matt22free/c8095fb25038c982f9f2932f8f4acdd8#file-log_all-L113-L117), but they get filtered to 0. And also that you've [tried all the formats](https://gist.github.com/matt22free/c59f75c356e06a23324e1392a325334c#file-ogcalsync-log-L227-L238) in the dropdown. Just strange that I can't replicate this by changing my machine to the France region, though I am on Outlook 2016.

Of course you can try your own custom formats by [referencing the documentation](https://msdn.microsoft.com/en-us/library/az4se3k1%28v=vs.90%29.aspx) - see if you can conjure something that works! Eg `dd-MMM-yyyy HH:mm`

Note, normally including seconds and/or AM/PM make things worse, but worth experimenting with everything!

**Comment by matt22free** [comment]
Thanks for help,

That works with : dd/MM/yyyy

good job
