### ISSUE TITLE
Missing updated Squirrel 1.7.8 dlls from 2.6.4

### ISSUE THREAD

**Issue by brozono** [phw198/OutlookGoogleCalendarSync#399]
**OGCS Version**: v2.6.4
**Installed or Portable**: Building

**Problem Description**  
Trying to build latest 2.6.4 alpha results in errors related to references to Squirrel.

**Steps to Reproduce the Issue**  
1. Pull tip as of 11/27
2. Open in VS
3. Build Release

**Any other information**  
Note this also includes SharpCompress, which I'm only assuming is related to Squirrel

If I'm supposed to update the DLLs myself please let me know and I'll go build it.

Copy of errors/warnings uploaded to CloudWok per link provided on reporting issues (if it helps).

**Comment by brozono** [comment]
Note I was able to build Squirrel 1.7.8 and use that, but perhaps the better answer is to remove the libraries that should be installed via package manager mechanisms and instead we could have a quick write up on setup to build from scratch?

**Comment by phw198** [comment]
Thanks for reporting - sorry my mistake, I should have copied the updated DLLs out into the `lib\Squirrel` folder.

Have now done this on the `development` branch, commit https://github.com/phw198/OutlookGoogleCalendarSync/commit/7383cd8d76fbc3bc1b4355bc651139f1e5e846ac.

:link: Issue #395
