### ISSUE TITLE
Meeting request updates

### ISSUE THREAD

**Issue by ITSentinel** [phw198/OutlookGoogleCalendarSync#400]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<When you arrange a meeting in Outlook and then you update it (including text or time changes), the updates are not synchronized in Google Calendar. This is not happening when you receive the meeting request from others and update it.>

**Steps to Reproduce the Issue**  
1. \<Arrange a meeting inviting more attendants>
2. \<Update text or time>
3. \<Check if updates have been synchronized in Google Calendar>

**Any other information**  
\<Outlook 2016>

**Comment by phw198** [comment]
Without a logfile or even confirmation of the version of OGCS you are running, there's little I can do.

Have you followed the advice on line 2 of your post?

**Comment by ITSentinel** [comment]
Hi, thanks for your comments.

OGCS versión is reflected in previous text (OGCS Version: v1.2.3.4). I don't know how to generate a logfile with described failure. Probably you can try to reproduce the issue and check if your meeting request is updated in Google Calendar once you have updated it in Outlook. Thank you in advance.

**Comment by phw198** [comment]
Um, v1.2.3.4 is just an example for the issue template. I seriously doubt that's what you're running, and if you are, you most certainly need to upgrade.

If the issue you describe does indeed exist, then everybody would be complaining :slightly_smiling_face:  So I'll wait until you can provide your logfile and proof of the version you are running...
