### ISSUE TITLE
COM error after upgrading Outlook [0x80040154]

### ISSUE THREAD

**Issue by kpwiebe** [phw198/OutlookGoogleCalendarSync#401]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.0  
**Installed or Portable**: Installed

**Problem Description**  
It was running OK except I upgraded to Outlook 2016 then OGCS started throwing an error at startup where I had to allow it access to email. So I thought I would just uninstall OGCS and install a fresh version. I uninstalled OGCS and downloaded the Setup file for 2.6.0 and ran Setup. After running Setup, the OGCS splash screen appears, then disappears, then nothing happens. I have no OGCS icon anywhere to configure the app.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1514566/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by kpwiebe** [comment]
alpha does same thing

**Comment by phw198** [comment]
Hi @kpwiebe, it's not an issue with OGCS but your upgraded Outlook 2016. [See the wiki for fix details](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040154---regdb_e_classnotreg).

Note, OGCS alpha v2.6.4 should have taken you to the wiki page instead of just crashing out?

**Comment by kpwiebe** [comment]
Thanks.  I got an error from regasm:

RegAsm : error RA0000 : Failed to load 'C:\Users\kwiebe\AppData\Local\OutlookGoogleCalendarSync\app-2.6.4-alpha\OutlookGoogleCalendarSync.exe' because it is not a valid .NET assembly

**Comment by phw198** [comment]
The instructions don't say to register the OGCS exe, but the outlook.dll

**Comment by kpwiebe** [comment]
Thanks again. I am still confused though. In the FAQ the command for regasm references "path-to-OGCS":

    Open a cmd window as Administrator (right-click, run-as)
    cd c:\windows\Microsoft.NET\Framework\v2.0.50727
    regasm **<path-to-OGCS>**\Microsoft.Office.Interop.Outlook.DLL

Is that the part that should actually say, "path-to-Outlook DLL"?

I found that DLL here:

C:\Program Files (x86)\Microsoft Office\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin

Is this the path I should use?

**Comment by phw198** [comment]
Uh oh, you're right - looks like the wiki was written when I was distributing the `Microsoft.Office.Interop.Outlook.DLL` along with OGCS!

So yes, try registering the DLL you found:
```
cd c:\windows\Microsoft.NET\Framework\v2.0.50727
regasm "C:\Program Files (x86)\Microsoft Office\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin\Microsoft.Office.Interop.Outlook.DLL"
```

If that doesn't work, try a simple "Office Repair" (steps at the top of the wiki page previously referenced). Otherwise I can upload a copy of the DLL I used to distribute...

**Comment by kpwiebe** [comment]
Thanks again. I got regasm to complete, but OGCS still didn't work. So I repaired Office, but OGCS still does not work.

**Comment by phw198** [comment]
From Googling a frequent response is people completely uninstalled Office and then reinstalled :expressionless:

Hopefully we can find a less sledge-hammer solution though. Could you try dropping your [attached DLL](https://github.com/phw198/OutlookGoogleCalendarSync/files/1518955/Microsoft.Office.Interop.Outlook.zip) into the `C:\Users\kwiebe\AppData\Local\OutlookGoogleCalendarSync\app-2.6.4-alpha` folder and then running regasm against it.

**Comment by kpwiebe** [comment]
regasm worked on the attd dll but ogcs still broken.

**Comment by phw198** [comment]
OK, v2.6.5 just released should now contain `Microsoft.Office.Interop.Outlook.DLL` in the install folder `%APPDATA%\OutlookGoogleCalendarSync\app-2.6.5-alpha`. Can you try running the regasm command against this file?

**Comment by kpwiebe** [comment]
regasm worked but OGCS still splashes then exits

**Comment by phw198** [comment]
Then I think we might have lost the battle and a full re-install of Office is needed. 

Might be worth you uploading your latest OGcalsync.log file, just to make sure the error hasn't changed along the way....?
