### ISSUE TITLE
Google Calendars are not retrieved, combo box is empty

### ISSUE THREAD

**Issue by angelochillemix** [phw198/OutlookGoogleCalendarSync#403]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.0  
**Installed or Portable**: Portable

**Problem Description**  
\Google Calendars are not retrieved resulting in an empty combo box. No calendar can be selected. Despite the authentication is successfull and token is returned, a dialog appears with message "You Google authorisation token needs updating. The process to reauthorise access to your Google acccount will now begin...". Screenshot of the dialog and log file attached.

**Steps to Reproduce the Issue**  
1. \Issue appears following the authorisation process in Google setup tab

**Any other information**  
\<Update here>

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1527062/OGcalsync.log)
![2017-12-04 13_32_19-authorisation token invalid](https://user-images.githubusercontent.com/13917784/33553575-9ea695b4-d8f9-11e7-84b7-c3f131865f99.jpg)

**Comment by phw198** [comment]
Please upgrade to the latest alpha release.

:link: Issue #299
