### ISSUE TITLE
install error - unable to cast COM object of type... [0x80029C4A]

### ISSUE THREAD

**Issue by tclhk** [phw198/OutlookGoogleCalendarSync#404]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.4 
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>
![image](https://user-images.githubusercontent.com/34291665/33641053-ec7077bc-da6e-11e7-827e-8e9517a803f3.png)

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Please could you provide your logfile, as 2.6.4 should have automatically taken you to the [wiki page for the fix](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary).

**Comment by phw198** [comment]
Any luck with either the fix or the logfile, or shall I close this ticket?

**Comment by tclhk** [comment]
please close.  looks like our corporate outlook has blocked off any syncing
with outside calendar.

*TCL*
