### ISSUE TITLE
Request: Add a method to exclude events from deletion, or force sync them

### ISSUE THREAD

**Issue by bambora-bcameron** [phw198/OutlookGoogleCalendarSync#409]
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
If a meeting event sent to me from someone else (so I am not the organizer) is moved, thus the original requires deletion on the Google side, the program keeps asking if it should delete the newly scheduled event in Outlook as well.  I assume this is due to the event having a static ID that was marked as deleted due to the first instance being deleted.

The work-around I use for this scenario is to allow OGCS to delete the event, then go into my deleted folder and re-accept it, which I assume causes Outlook to assign it a new ID.

Another use case is if I create an event in Outlook, then do a copy/paste of it to other times (such as creating daily recurring meetings), the subsequent copies have the original's ID somewhere so OGCS believes them to be duplicates and prompts to delete.

I'd love to see something built into the delete prompt instead of just "Yes" or "No" with the latter just skipping it, to instead give the option of "No, and don't ask again" or "No, and push back to Google".  Basically if I determine this shouldn't be deleted, it should not just stay in Outlook but also force sync back to Google?

**Comment by phw198** [comment]
Thanks for reporting, though both scenarios should be handled in the later alphas.
