### ISSUE TITLE
Outlook "Application Hang" after the latest Office-Update

### ISSUE THREAD

**Issue by stud0709** [phw198/OutlookGoogleCalendarSync#410]
**OGCS Version**: v2.6.2.0 
**Installed or Portable**: Installed

**Problem Description**  
As soon as OGCS is started, Outlook will freeze. Windows Event Log: "Application Hang" (101). See attached log file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1546874/OGcalsync.log)

**Comment by stud0709** [comment]
A workaround for this is delaying the startup of OGCS.

**Comment by phw198** [comment]
Are you sure this was the workaround? As opposed to restarting your system after the upgrade of Office/Outlook?
