### ISSUE TITLE
"Failed to retrieve Google Calendar" after changing from Windows 7 to Windows-10 Machine

### ISSUE THREAD

**Issue by IngomarL** [phw198/OutlookGoogleCalendarSync#411]
Version 2.5.0.0

I am using the same network without any changes in firewall etc, I only have new PC with new OS Windows 10; 
I can open and modify google calender through http:-calls as always, but cannot make OutlookGoogleCalendarSync work. I enter the credentials, get the authorization code, and get the a.m. failure notice after a minute or so....

BTW, seems to be the same case with other sync apps as well...

Community, any idea what might be wrong?

thanx, brgds from Tokyo/Japan!

**Comment by phw198** [comment]
Please upgrade to the latest alpha release and provide your OGcalsync.log file if the issue remains.
