### ISSUE TITLE
laptop won't sleep (or hibernate) with the app running

### ISSUE THREAD

**Issue by shie-erlich** [phw198/OutlookGoogleCalendarSync#414]
not sure if anyone sees this, but basically my laptop stays awake or wakes up to sync. all the time :)
i got to sleep at night and here the sounds the app make every once in a while, it even wakes up from hibernation - usually in my bag, then doesn't go to sleep and gets hot and all that jazz.

any thoughts?
----

**OGCS Version**: i'm using a hotpatch and the About screen reports 2.6.1.5
**Installed or Portable**: Installed

**Comment by phw198** [comment]
Have a read through https://www.howtogeek.com/122954/how-to-prevent-your-computer-from-waking-up-accidentally/ for a good guide on how to troubleshoot this.
