### ISSUE TITLE
Provide option to exclude items based on privacy (public/private)

### ISSUE THREAD

**Issue by CaryRW** [phw198/OutlookGoogleCalendarSync#415]
Love the app!  It is working 'almost' perfectly for me.  I would for there to be a way that events in Google calendar can be excluded from sync.  I have 'private' things in Google that just don't need to be in my Outlook calendar.  I'm sure there are others that would agree. So....

Here's my thinking:

There is already an option to "Set entries as private in target calendar", so, what if the "Visibility" tag in Google could be used for syncing or not.  If it is tagged "Public" then sync.  If it is marked "Private", then do not sync.

I do hope this is something that could be included.  As I mentioned, it works perfectly in every other way, but I do need for 'private' things to stay in Google.

Thanks for considering!!!

**Comment by phw198** [comment]
Hi @CaryRW, just wondering if a workaround is to move those items you don't want synced out in to a different Google calendar?

Will certainly consider your suggestion though...

**Comment by CaryRW** [comment]
Thanks, Paul, for the reply.  I suppose a new calendar is an option.  However, it seems to me that it would make more sense to simply have a way of filtering versus having to create a new calendar.  It means one more thing to have to manage, so it isn’t really productive.  Know what I mean?  Thank you for considering!!!

Cheers…

Cary R. Wagner

**Comment by phw198** [comment]
:package: This should now be available with [hotfix v2.10.0.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12207106/v2.10.0.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/b032d686-a8c5-428b-82ce-1e48522ed919)

Let me know how it goes if you try it!
