### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by tiffanysmattress** [phw198/OutlookGoogleCalendarSync#416]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.5.0
**Installed or Portable**: Installed

**Problem Description**  
Several problems.  There are a bunch of Outlook events that say....  problem.... item will not be synced..... something went wrong try again - etc.

Google is saying there is some sort of reclaim orphan calendar, object reference not set, aborted 1 failed attempts

**Steps to Reproduce the Issue**  
1. Not sure what you want here.  I've installed both a beta version and the alpha version I am using now.   I am obviously not any sort of developer or engineer just an end user so please dumb down your response with step by step instructions on how to fix.

**Any other information**  
I have posted a pick of the log in your google+ page if that info helps.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1565203/OGcalsync.log)

**Comment by phw198** [comment]
Hi @tiffanysmattress, there are a lot of warnings in your log file about Outlook items with no end date specified. I think it then fails completely later on when dealing with another item with no end date. It shouldn't be possible to create an item in this way, so I'm not sure how this is happening. Hmm, are you connecting to a Hotmail calendar through IMAP or something?

:package: Anyway, please try this hotfix [v2.6.5.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1566162/v2.6.5.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)). 

With any luck this won't fail in the same way, but I'm wondering if none of the items have end dates and therefore nothing is going to sync. Give it a go and upload your log file again afterwards...

**Comment by phw198** [comment]
Any update on this?
