### ISSUE TITLE
Sync stays 'In progress...'

### ISSUE THREAD

**Issue by mkorenbl** [phw198/OutlookGoogleCalendarSync#417]
**OGCS Version**: v2.6.5.0
**Installed or Portable**: Installed

**Problem Description**  
After OGCS has started the sync looks like it is starting but it never seems to finish

**Steps to Reproduce the Issue**  
1. Autostart OGCS
2. Check 'Sync' screen in GUI.

**Any other information**  
When problem occurs:
Next scheduled state is: 'In progress'.
Information window states 'Sync started at <date and time>. Syncing from <date> to <date>. Outlook -> Google
Button below information window states: 'Start Sync'
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1575878/OGcalsync.log)

**Comment by mkorenbl** [comment]
Look like the problem does not occur if a start delay 60 seconds is entered

**Comment by kwagner115** [comment]
I have the exact same problem that just appeared with the installation of v2.6.5.0

**Comment by kwagner115** [comment]
2.6.0.0 does not have the problem. I reinstalled that version to test.

**Comment by mkorenbl** [comment]
I can confirm that. Downgraded to 2.6.0 and it  worked again.

**Comment by phw198** [comment]
Thanks - I can confirm this bug affects v2.6.5 specifically, and no earlier version. It also only affects those that minimise the application to the notification tray.

:package: This should now be resolved with hotfix [v2.6.5.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1591727/v2.6.5.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) and make sure it is applied on top of v2.6.5.0).

Please let me know how it goes.

**Comment by mkorenbl** [comment]
Paul,

It looks like it's working again. 2.6.5.3 resolves the problem of the
'hanging sync' on my installation. I let it sync about 3 times with no
problem at all.

2017-12-28 18:19 GMT+01:00 Paul <notifications@github.com>:

**Comment by kwagner115** [comment]
I too confirm 2.6.5.3 works as expected.
