### ISSUE TITLE
Scheduled sync readds deleted events of series

### ISSUE THREAD

**Issue by maxoe** [phw198/OutlookGoogleCalendarSync#418]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I only sync from Google to Outlook. The problem occurs when you got a series in your Google calendar where you have deleted single events of the series.
The first manual sync after connecting my Google account worked fine and OGCS synced the whole series except the deleted events like it should be. But after the first scheduled sync the deleted events of the series were readded to my Outlook calendar.

**Steps to Reproduce the Issue**  
1. Add a series to your Google calendar and delete several single events from the series.
2. Connect OGCS with your Google account.
3. Sync manually
4. Wait for the first scheduled sync (choose 10 minutes interval in the settings) 

**Any other information**  
[Log file](https://gist.github.com/maxoe/03ed6133dcde19512eab56a375f6cb96), the last two syncs should be the important ones

I also noticed that the date range I had set in the settings did not work (7 days in the past, 14 days in the future). It is far more (especially for some specific series).

**Comment by phw198** [comment]
I was able to replicate this by:
1. Sync a Google recurring series with an exception in - OK
1. Change the Google master series for all items in the series, eg Subject
1. Sync again - the subject is changed for all items in Outlook, but the exceptions have been lost.

:package: This should now be resolved with [v2.6.5.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1591571/v2.6.5.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) and make sure you apply the fix on top of v2.6.5).

Please let me know how it goes.

**Comment by phw198** [comment]
Any update, please?

**Comment by phw198** [comment]
Commit 63af92d is for this issue, not 416.

**Comment by phw198** [comment]
Released in v2.6.6
