### ISSUE TITLE
Only one available Outlook calendar

### ISSUE THREAD

**Issue by Nemesis1911** [phw198/OutlookGoogleCalendarSync#420]
**OGCS Version**: v2.6 
**Installed**

**Problem Description**  

Like already mentioned in the headline I have two Outlook accounts. But I´m using only one of those accounts for my calendar. Unfortunately this is the one which can´t be chosen in the "Setting/Outlook" section. The account which is available in this section is the one with that I registered and bought the Outlook 2016 account (Student Version). 

Best, 
Nemesis

**Comment by phw198** [comment]
If both accounts are set up in the Outlook desktop application, then the other will be listed under "Alternative mailbox".

**Comment by kdelany** [comment]
I think I can reproduce the issue. I have been using CalendarSync on an old computer running outlook 2007 fine. I moved to a new computer running outlook 2016

When I select the "Default Mailbox" The only options under select calendar is "Default Calendar" 

I created a new calendar called "Test" to see if it would allow me to select it. It doesnt show up in the dialogue box, only "Default Calendar"

If if switch to an Alternative mailbox, it shows up with the list of calendars OK. So something may be broken with Outlook 2016 and the default calendar selection. 

It does appear to read the default calendar from the logs 

2018-01-04 18:10:29,754 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  OUTLOOK SETTINGS:-
2018-01-04 18:10:29,763 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Service: DefaultMailbox
2018-01-04 18:10:29,769 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Mailbox/FolderStore Name: 
2018-01-04 18:10:29,774 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: Default Calendar
2018-01-04 18:10:29,780 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Category Filter: Exclude
2018-01-04 18:10:29,785 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Categories: 
2018-01-04 18:10:29,790 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Filter String: g

And for me, no items from outlook sync to google. It always shows 0 outlook events. 
```

Sync started at 1/4/2018 6:39:27 PM
Syncing from 1/3/2018 to 1/6/2018
Outlook → Google
--------------------------------------------------
Reading Outlook Calendar Entries...
0 Outlook calendar entries found.
--------------------------------------------------
Reading Google Calendar Entries...
4 Google calendar entries found.
--------------------------------------------------
Total inc. recurring items spanning sync date range...
Outlook 0, Google 4
--------------------------------------------------
0 Google calendar entries to be deleted.
0 Google calendar entries to be created.
--------------------------------------------------
Sync finished with success!

```

**Comment by srv728** [comment]
Im the owner and did not request this.

**Comment by phw198** [comment]
@kdelany OGCS won't automatically pick up new Calendar folders that are created. You would either need to restart OGCS or select `Alternate mailbox` and back again to make it rescan for calendars - that's by design.

If it's not picking any items up in Outlook when you sync, try playing with the [date format](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items).

@srv728 Say what?
