### ISSUE TITLE
Unable to set the "when" of the synchronisation options.

### ISSUE THREAD

**Issue by itsgillian00** [phw198/OutlookGoogleCalendarSync#421]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\After installing and opening, on the settings tab, sync options subtab, when section.  This section is not completely visible, and therefore cannot be set.

**Steps to Reproduce the Issue**  
1. open setup.exe
2. navigate to the proper area (above).

**Any other information**  
\screen grab:
![image](https://user-images.githubusercontent.com/34894951/34389670-4d8719cc-eaf8-11e7-97d6-8a6929f89b8e.png)

**Comment by phw198** [comment]
Having clicked `More...` to expand the How section, click `Less...` to shrink it back.
