### ISSUE TITLE
Outlook does not appear to be installed - it is!

### ISSUE THREAD

**Issue by papadeltasierra** [phw198/OutlookGoogleCalendarSync#424]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.5.0  
**Installed or Portable**: Installed

**Problem Description**  

As per summary.  I'm trying to install and getting the popup about Outlook not being installed - but I'm using it quite happily.

**Steps to Reproduce the Issue**  

1. Install it and try to start it.

**Any other information**  

The latest Microsoft update for my Office has failed and thus far nobody from Microsoft can tell me why.  I'm guessing that whatever test you're using to detect Outlook (registry entries? connect to interface?) is failing.  I'm a developer myself so I'm happy to run any diags etc that might help.  With luck fixing this problem might even help my upgrade :-).

**Comment by phw198** [comment]
Hi,

The error code to produce the error `Outlook does not appear to be installed! This is a pre-requisite for this software.` is 2147221164.

From Googling on this it's possible that [creating a new Outlook profile](https://support.office.com/en-gb/article/Create-an-Outlook-profile-F544C1BA-3352-4B3B-BE0B-8D42A540459D?ui=en-US&rs=en-GB&ad=GB) will resolve the issue? When you do find a solution, let me know so I can add it as a suggestion in the error message...

**Comment by papadeltasierra** [comment]
Paul,

Thanks for the suggestions – I’ll give it a try.  It’s rather stupid because I can’t even delete Office at the moment to start again, that being the other suggestion I’ve found.

Paul DS.

**Comment by papadeltasierra** [comment]
Paul,

Creating a new profile did not help and eventually I had to bite the bullet and completely delete and reinstall office.  However even this was not easy because it would not uninstall from ‘Programs…’ etc.  What eventually worked was:


  1.  Download and run the Microsoft ‘delete Office’ tool
  2.  Reboot and repeat steps 1 & 2 until the tool stopped complaining that not everything worked
  3.  Manually hunt and kill all Microsoft Office related registry entries
  4.  Manually hunt and delete all %ProgramFiles% and %ProgramFiles(x86)% Microsoft Office related subdirectories (from an Administrator command prompt)
  5.  Reinstall Microsoft Office
  6.  If #5 failed (it did twice for me!), go back to #1 and try again because there’s something missed and still lurking
  7.  Now reconfigure e-mail accounts etc and reinstall the Outlook add-ins

This finally got me to a working Office with working add-ins.
Paul DS.

**Comment by phw198** [comment]
Wow, that's rather horrible! Hopefully very few people will encounter such a broken install of Office, but thanks for reporting how you fixed it :+1: 

Welcome back to OGCS :wink:
