### ISSUE TITLE
WARNING: Problem encountered during synchronisation. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by htheberge** [phw198/OutlookGoogleCalendarSync#428]
Keep getting this issue - no synch since mid-december

Will not let me attach log file? states we do not support that file type

**Comment by phw198** [comment]
:spiral_notepad: Options for uploading your logfile can be [found here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file).

**Comment by phw198** [comment]
:arrow_double_up: Assuming you're not on the latest alpha release, your other option is to upgrade by [downloading its `Setup.exe` file](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.5-alpha/Setup.exe) and running it.
