### ISSUE TITLE
Multiple Calendar Sync

### ISSUE THREAD

**Issue by CaryRW** [phw198/OutlookGoogleCalendarSync#432]
Hey Folks,

I'm liking OGCS.  As I have multiple calendars I am finding that it would be nice if OGCS could pull multiple Google calendars in to Outlook.  This would then give me the ability to sync certain Outlook items back to specified Google calendars.  Asking for too much???  :-)

Cheers...

Cary

**Comment by TriV3** [comment]
Hi all,

Same here.
I share my google calendar with my wife, so she can set events on its google calendar that appears on mine. In the software i can only select one google calendar but my wife's one is in the list;
It would be fantastic if i could sync outlook with both googlecalendars.

**Comment by phw198** [comment]
Yep, this is covered by #165 and in the [Enhancement Pipeline](https://github.com/phw198/OutlookGoogleCalendarSync/projects/3).

:link: Duplicate #165
