### ISSUE TITLE
calender sync - outlook calender doesnt loud

### ISSUE THREAD

**Issue by rachel1997** [phw198/OutlookGoogleCalendarSync#435]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
i did everything as the help page told me to do, reset the dd/mm/yyyy and checked everything else.. all lookes good but when i sync the the program say: Reading Outlook Calendar Entries...
0 Outlook calendar entries found.
i checked the "test"botton in the outlook setting and it say that there is 106 items in the calender. (i tryed the differnt optiones there - all gave me the same answer..)
I do not have any knowledg in computers. please help :(
thank you!

**Steps to Reproduce the Issue**  
1. 

**Any other information**

**Comment by phw198** [comment]
Hi, do you have any Outlook category filters set? Make sure you're not filtering everything out by accident.

If you're still stuck, please [upload your logfile](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file).

:arrow_double_up: Also, may be worth upgrading to the latest alpha release by [downloading its `Setup.exe` file](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.5-alpha/Setup.exe) and running it.

**Comment by rachel1997** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1641897/OGcalsync.log)
is that it?

**Comment by phw198** [comment]
Yes, you have multiple categories _included_ for sync. This was identified in issue #364 and fixed in v2.6.4.

:arrow_double_up: To fix, please upgrade to the latest alpha release by [downloading its `Setup.exe` file](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.5-alpha/Setup.exe) and running it.

[Duplicate #364]

**Comment by rachel1997** [comment]
it worked!! thank you very much :)
