### ISSUE TITLE
Phantom calendar invites issued by Google Calendar after sync from Outlook

### ISSUE THREAD

**Issue by unmesh59** [phw198/OutlookGoogleCalendarSync#438]
**OGCS Version**: v2.6.0.0  
**Installed or Portable**: Portable

**Problem Description**  
I have it set up to only transfer calendar entries from Outlook Desktop to Google Calendar. At times, a meeting invite sent to a group of people by a colleague becomes a meeting invite from my gmail address and gets sent to everyone on the original invite list

**Steps to Reproduce the Issue**  
1. It has happened two times in the last week and I haven't been able to force it to happen

**Any other information**  
Log file at https://gist.github.com/unmesh59/53bb3c165d880d1b9065e6d32f24dbed

**Comment by phw198** [comment]
See [the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google).

**Comment by unmesh59** [comment]
I haven't made any changes, not even a Meeting Accept on the Google side. Would people still get a re-invitation from me? Is there a workaround?

Thanks

**Comment by phw198** [comment]
It's a bug on Google's side, so who knows quite what triggers it. The workaround is to upgrade OGCS and cloak the attendees. I guess you didn't read the wiki entry...

**Comment by unmesh59** [comment]
I read the immediate paragraph that the link took me to and it looks like I should have read further :-(
