### ISSUE TITLE
MD5 is not FIPS compliant

### ISSUE THREAD

**Issue by mat1234** [phw198/OutlookGoogleCalendarSync#441]
**OGCS Version**: v2.6.6
**Installed or Portable**: Portable

**Problem Description**  
I was able to setup, configure, and sync outlook one time.  After I closed and restarted OGCS, I get "Application Terminated" with the message "Exception has been thrown by the target of an invocation."  Then the application closes.

**Steps to Reproduce the Issue**  
1. Start OGCS
2. Get error
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1653569/OGcalsync.log)

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by mat1234** [comment]
Added to original write-up

**Comment by phw198** [comment]
Thanks @mat1234.

:package: Could you [give v2.6.6.4 a go](https://github.com/phw198/OutlookGoogleCalendarSync/files/1653968/v2.6.6.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know if there's any difference?

**Comment by mat1234** [comment]
Version updated, now I get "The implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1654169/OGcalsync.log)

![capture](https://user-images.githubusercontent.com/18341200/35253487-adc57336-ffb3-11e7-8e48-83e57f4636fa.PNG)

**Comment by phw198** [comment]
Please could you try unzipping the `.config` file from [OutlookGoogleCalendarSync.exe.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1656458/OutlookGoogleCalendarSync.exe.zip) and dropping it in the same directory as the OGCS executable.

**Comment by mat1234** [comment]
It's working now..  Version 2.6.6.4 with the config file you provided.
