### ISSUE TITLE
Unable to access Outlook Calendar

### ISSUE THREAD

**Issue by sriedel1** [phw198/OutlookGoogleCalendarSync#443]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.0.0  
**Installed or Portable**: Installed

**Problem Description**  
```
Reading Outlook Calendar Entries...
Unable to access the Outlook calendar.
The following error was encountered during sync:-
Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)).
Operation aborted after 1 failed attempts!
```
**Steps to Reproduce the Issue**  
1. Run Sync

**Any other information**  
[OGcalsync.log.2018-01-22.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1657675/OGcalsync.log.2018-01-22.txt)

**Comment by phw198** [comment]
The error you reported doesn't seem to be included in the log file you provided. Can you check in Task Manager if you have more than one instance of OGCS running?

Does the problem still occur after restarting your computer?

**Comment by sriedel1** [comment]
There was only one instance of OGCS running.  But, rebooting seems to have cleared the issue.  I will let you know if it happens again.  Thanks for the quick response!!! sr
