### ISSUE TITLE
"Unmatched Google events"

### ISSUE THREAD

**Issue by randerson4** [phw198/OutlookGoogleCalendarSync#446]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1674682/OGcalsync.log)
![capture](https://user-images.githubusercontent.com/35932005/35526000-d0ca3032-04eb-11e8-8420-3b5dbf8bd9bf.JPG)
**OGCS Version**: v2.6.4.0  
**Installed or Portable**: Installed

**Problem Description**  
About a week ago, I started getting a error message consistently saying that it can't match to my Outlook calendar. Can anyone help me figure out what is going on? I'm not super tech savvy, so layman's terms is a appreciated. If I haven't attached the proper files/logs, please let me know. I have attached screenshot of the message I've been getting.

**Steps to Reproduce the Issue**  
1. Sync

Update
1. Just upgraded to 2.6.6 Alpha and the issue still happend.

**Comment by phw198** [comment]
Hi, it basically means that the Google calendar to which you are syncing has an item in it that did not originate from Outlook. OGCS therefore wants to delete it, but it's asking you to confirm that's what you want it to do first.

Most likely you created this item directly in Google yourself, so if you want to keep the item, you should either move it to a calendar that you are not syncing to with OGCS (the recommended option), or turn on `Merge with existing entries` in OGCS settings.

Unfortunately, OGCS isn't reporting the exact event in question - if you don't know which one it is, you could let it delete it (at which point it will report which one it was) and then if you need it back, recover it from the Google "Bin" in the calendar web view (under the settings cog).

Hope that helps.

BTW, how often do you have OGCS configured to sync? It seems to be syncing every 10 minutes at least as well as Push Sync being set?

**Comment by randerson4** [comment]
Thank you, @phw198 . I will try your solutions and let you know if I have more issues?

You are correct. Syncing every 10 minutes and Push Sync. Is that a poor setup? I'm only syncing one way (Outlook > Google).

**Comment by phw198** [comment]
Push Sync is designed to detect changes in Outlook and sync them within 2 minutes - ie. you don't need to do that _as well as_ schedule a sync every 10 minutes.

Likely more reasonable would be Push Sync + sync every 4 hours maybe? Or don't Push Sync at all and just sync every hour?
