### ISSUE TITLE
Do you have a MAC version?

### ISSUE THREAD

**Issue by dylankohlstadt** [phw198/OutlookGoogleCalendarSync#448]

**Comment by phw198** [comment]
Duplicate of #159

**Comment by dylankohlstadt** [comment]
Hi there

Nope, not a duplicate. I don’t use iCal, I use Outlook Calendar on a MAC.

Please help.
Ta
dk

**Comment by phw198** [comment]
Yes, a duplicate. I guess you didn't read the whole ticket. StevenBoatman had responded explaining how to get iCal to sync with a Google calendar and then continued the request for OGCS on MAC - same as you.
