### ISSUE TITLE
Minimize to icon and not task bar

### ISSUE THREAD

**Issue by gillesmar** [phw198/OutlookGoogleCalendarSync#449]
Is there a way to minimize to the icon list and not on the taskbar?
Ideally, when we select the x (to close) the app should reduce to the icon and not close.
And the minimize (- button) should do the same.

**Comment by phw198** [comment]
![capture](https://user-images.githubusercontent.com/11843015/35649938-73b6c836-06d2-11e8-96a5-0995d2aa716b.png)

See the [User Guide](https://phw198.github.io/OutlookGoogleCalendarSync/guide/appbehaviour) for more details.
