### ISSUE TITLE
IMAP accounts support categories?

### ISSUE THREAD

**Issue by Hinge87655** [phw198/OutlookGoogleCalendarSync#450]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.6.0
**Installed or Portable**: Installed

**Problem Description**  
After installing OGCS and completing the setup, I tried "test" and had a window with the following text
Date - Time Format Results
The format "g" returns 0 calendar items within the date range 1/30/2018 and 5/2/2018
I retried with all of the Date formats given.
I'm trying to move data from outlook to google only.
I also lost all categories in outlook

**Steps to Reproduce the Issue**  
1. \<Update>
1. 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1687010/OGcalsync.log)

**Any other information**  
\I forgot to include the log file, sorry.

**Comment by phw198** [comment]
Hi,

Your log file doesn't show any record of the date format tests, but it does show the category probem:
```
OutlookGoogleCalendarSync.MainForm [0] -  List Calendar folders
OutlookGoogleCalendarSync.OGCSexception [0] -  System.NullReferenceException: Object reference not set to an instance of an object.
OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.GetCategories()
```
When did this problem start? I notice you are connected to an Outlook.com address for an Alternate Mailbox - is that a MAPI connection to an external Outlook.com account? I wonder if that doesn't support categories; are you able to assign a category to a calendar item from within the Outlook desktop app?

**Comment by Hinge87655** [comment]
Hello Paul, Thanks for taking the time to help me. I'm not real goo with the jargon so please be kind. I have been using the calendar part of Outlook 2007 for some time. I've been wanting to sync with a Google calendar on y android phone. I found your software and I;m trying to use it. I never setup the email portion of Outlook 2007 because I have a an Outlook.com email account. After I sent my problem to you I realized that the Outlook 2007 was not working and I've been trying to get that working. Apparently Outlook 2007 has a problem "playing well with others" and I'm waiting for a fix to "Outlook 2007 prompts you repeatedly for a password ..." problem. This might take care of the problem I'm having with OGCS. As you might see I'm connecting Outlook 2007 to Outlook.com. Since I'm trying to sync with a Google calendar would I be better off putting my Gmail account into Outlook 2007?



Regards,

Tom Mather


Not All Who Wander are Lost

________________________________

**Comment by Hinge87655** [comment]
Hello Paul, I switched to my gmail account on Outlook 2007 and it works and I have my calendar on my phone. Yea!!

Outlook 2007 still does not see Outlook.com but I only wanted my calendar on my Outlook 2007 calendar on my phone.


Regards,

Tom Mather


Not All Who Wander are Lost

________________________________

**Comment by phw198** [comment]
:memo: Notes for reference:

* Setting an account up as IMAP in Outlook desktop client does not include a calendar folder at all.
   * The account is available in OGCS under the `Alternative mailbox` option
* It's possible to go to `Folder` view and then right click the IMAP account, `New Folder` and create it as containing `Calendar Items`
* This is created as `<given calendar name> (This computer only)` - ie not synced to cloud account
   * The calendar is available in OGCS under the `Alternative mailbox` > `Select calendar` option
* There are no categories available for "this computer only" calendar items
   * The exclude/include categories in OGCS has no effect
