### ISSUE TITLE
Popup dialog that starts with "A program is trying to access email address information"

### ISSUE THREAD

**Issue by fclifton** [phw198/OutlookGoogleCalendarSync#451]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.0.0 
**Installed or Portable**: Installed

**Problem Description**  
\<Update>
Get a popup dialog that starts with "A program is trying to access email address information" when OGCS starts.  If I allow it all syncs seem to work properly.  This behavior only started recently.  I was running Windows 7, now I am on Windows 10.  It might have started happening at the switch but I cannot remember if that is so.

**Steps to Reproduce the Issue**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1687339/OGcalsync.log)

1. \<Update>
1. start OGCS 

**Any other information**  
\<Update here>
OS Name Microsoft Windows 10 Pro
Version 10.0.16299 Build 16299
Microsoft Office 365 ProPlus
Version 1712 (Build 8827.2148 Click-to-Run)

**Comment by phw198** [comment]
Have you seen the [wiki article](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security)? Does it help?

**Comment by fclifton** [comment]
Yes, I read the wiki.  It didn't seem to help - I don't have Attendees checked under Sync Options.  I cannot change anything under Programmatic Access, I assume because the admin has disabled that.  However, I installed the 2.7.0.0. beta and I am no longer getting the popup.

**Comment by phw198** [comment]
Glad the issue is gone. Often the key is to ensure you have up to date antivirus definitions, so maybe you'd fallen behind...

**Comment by fclifton** [comment]
Possibly.  But I am on a work network, and so have no control over applying updates.  Of course, where I work, we are never behind on security updates... ;)
