### ISSUE TITLE
Windows Defender doesn't like the Installer Exe?

### ISSUE THREAD

**Issue by Zandorado** [phw198/OutlookGoogleCalendarSync#452]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
When updating from 2.6 to 2.7b, my Windows10 Defender told me that the app was not recognised. 
![image](https://user-images.githubusercontent.com/36067896/35723565-094dae5e-07fb-11e8-9550-bcd44308cc42.png)

[OGcalsync - Copy.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1688575/OGcalsync.-.Copy.log.txt)

**Steps to Reproduce the Issue**  
1. Windows 10 Enterprise & Defender installed. 
2. Download 2.7 Installer
3. Click 'Run'
4. Gives warning about Defender

![image](https://user-images.githubusercontent.com/36067896/35723935-50ae0db0-07fc-11e8-9b61-4cde3e0b784e.png)

**Any other information**  
Also, on my last Windows build, corporate IT told me my PC was Infected. I am not sure if this infection was caused by OGCS. But I am extra weary now..?

**Comment by phw198** [comment]
Sounds the same as #336 - can you right-click the downloaded `Setup.exe` file, select `Properties` and check if there is a button near the bottom to `Unblock`?

If so, unblock it and try running again. Are you running Edge? That's particularly terrible at blocking anything downloaded from the internet...
