### ISSUE TITLE
Events Not Syncing From Outlook ->Google

### ISSUE THREAD

**Issue by meliwu** [phw198/OutlookGoogleCalendarSync#453]
**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
It seems like whenever I copy events in Outlook, the sync does not recognize it as a new event and skips it entirely during the sync even though I had named the event differently and/or placed the event on a new date/time

**Steps to Reproduce the Issue**  
1. Copy Event in Outlook and put it on a future date (2-3 days out)
1. OutlookGoogleCalendarSync
1.  Start Sync
1. Compare Calendars

**Any other information**  
Here are screenshots of two events that were missed in the sync-

Outlook:
![image](https://user-images.githubusercontent.com/3059189/35743457-b46fabf6-080b-11e8-9742-de3b6fe05acf.png)

Google:
![image](https://user-images.githubusercontent.com/3059189/35743444-aa35c8fa-080b-11e8-82f2-4d5088e8b935.png)

Sync File;
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1690019/OGcalsync.log)

**Comment by phw198** [comment]
Hi and thanks for reporting. Your log file has a lot of `You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.` errors - I'm not sure if this is causing a problem or not, but it would be good to get rid of them first.

Could you confirm if the problem remains have closed down both OGCS and Outlook before restarting them.

Also try a full sync by pressing `Shift`and clicking `Sync`.

**Comment by meliwu** [comment]
I did notice that with the full sync, it was capturing more events :)

**Testing:**
1. Tested with smaller time frame to reduce any noise in the issue
2. Did a full sync
3. Closed down OGCS and Outlook and restarted before doing the full sync.
![image](https://user-images.githubusercontent.com/3059189/35833754-199644e8-0a98-11e8-9339-73617ff46075.png)

Outlook:
![image](https://user-images.githubusercontent.com/3059189/35833748-11fbc1d6-0a98-11e8-8890-32850ace6cb5.png)

Google:
![image](https://user-images.githubusercontent.com/3059189/35833829-6f53d5b2-0a98-11e8-80e0-d1764d5131a6.png)


Sync File:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1697154/OGcalsync.log)

**Comment by phw198** [comment]
Thanks for the update - I can now see the following:
```
2018-02-05 17:06:18,202 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  8/10/2017 12:00 PM (R) => "FH: Office Hours"
2018-02-05 17:06:18,202 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring appointment with 16 exceptions that will now be iteratively compared.
2018-02-05 17:06:18,656 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  Finding Google instance for Outlook exception:-
2018-02-05 17:06:18,656 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -    Original date: 01/02/2018
2018-02-05 17:06:18,671 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -    Current  date: 01/02/2018
2018-02-05 17:06:18,671 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  Matching Google Event recurrence found.
2018-02-05 17:06:18,671 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  It is deleted in Google, so cannot compare items.
2018-02-05 17:06:18,671 WARN  13 OutlookGoogleCalendarSync.Recurrence [0] -  Outlook is NOT deleted though - a mismatch has occurred somehow!
```
I'm not sure how this situation can arise, nor can it really be automatically resolved. I'd suggest you delete the entire recurring series in Google and let OGCS recreate it.

Searching your log file for `a mismatch has occurred somehow!` it seems you've quite a few exceptions to recurring series that have this problem.

:package: I've therefore surfaced the issue as a warning in the sync window with [v2.7.0.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1701244/v2.7.0.5.zip)
 ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes (a screenshot of the warning messages would be nice as I've not had time to test this).

**Comment by phw198** [comment]
Hi @meliwu, any update on this?
