### ISSUE TITLE
Could  not load  file or assembly 'office,Version = 12.0.0.0

### ISSUE THREAD

**Issue by slug13** [phw198/OutlookGoogleCalendarSync#455]
Previously used OGCS on my old machine with standalone outlook 2010. Had no issues at all, and loved the program. Perfect for my needs.
Now migrated to a new win 10 pro  machine with full MS Office 2010 and cannot get OGCS to load properly, always getting the error:
`Application unexpectedly terminated!	
Could  not load  file or assembly 'office,Version = 12.0.0.0, Culture = neutral, PublicKe yToken = 71e9bce111 e9429c' or one of its dependencies. The system cannot find the file specified.`

**OGCS Version originally**: v2.7 beta
Just tried 2.6.6 but same result.  

**Steps to Reproduce the Issue**  
1. download setup
2. run it

**Any other information**  
Since moving to Github i think the level of support has fallen.
I am not a computer guru and find it difficult and frustrating to wiggle through this site.
You always blame the Outlook installation for the particular error i am reporting.
i have run the install repair on my Outlook 2010 3 times but nothing changes.

Here is [log report](https://gist.github.com/phw198/705e50b3a66660a6e4f764d575bf0aeb) i think.

**Comment by phw198** [comment]
> Since moving to Github i think the level of support has fallen.

Really? I can assure you the project is 1000 times easier to manage on GitHub over the horror that was CodePlex. If you've been with OGCS for some time maybe it's to do with the fact there are now thousands of users and I still run this project in my spare time.

> You always blame the Outlook installation for the particular error i am reporting.

Again, really? I've only seen this error reported once before on issue #434 and it's still being troubleshot. Further updates should be made on that ticket.

But some things to try:

- on the old 2010 machine - is that still available? Can you upgrade OGCS to v2.7 on it and see if it works?
- on the new machine:
   - does the portable zip version work for v2.7 work
   - does v2.6 `Setup.exe` work

**Comment by slug13** [comment]
Hello Paul
Sorry I came across sounding nasty.
One of “those days.”

•	On the old machine, the upgrade to v2.7 worked fine, no issues.
•	On the new machine, the portable zip version did not work, same error message.
•	On the new machine, the v2.6 setup.exe did not work, same error message

 
Don

**Comment by phw198** [comment]
Hi Don,
No worries. So unfortunately for you, the other affected user has just closed their ticket because the problem magically fixed itself.

As your old machine works with both v2.6 and v2.7 and I'm confident both versions of OGCS are compatible with your new machine where neither works, does indicate the problem is somewhere on your system.

First up, if you haven't already, is the classic IT "turn it off and on again" - do a couple of full reboot cycles to flush through any pending Windows updates etc. Also perform a reboot after any Office Repair too.

Googling [found this](http://www.vbforums.com/showthread.php?727311-My-Solution-to-quot-could-not-load-file-or-assembly-office-version-12-0-0-0-culture-quot), where a user copied a folder over from the old machine to the new which fixed it. I wouldn't suggest copying the whole folder, but we at least need to check one of the files.

So - could you check in `C:\Windows\assembly` if you have a file called `Microsoft.Office.Interop.Outlook`? If so, which version do you have?

:memo: Another option is to search your C:\ drive for `gacutil.exe` and then run the following in a `cmd.exe` window - should look something like this:
```
C:\Users\Paul>"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\gacutil.exe" -l microsoft.office.interop.outlook
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  microsoft.office.interop.outlook, Version=15.0.0.0, Culture=neutral, PublicKey
Token=71e9bce111e9429c, processorArchitecture=MSIL

Number of items = 1
```
I suspect yours will return 0 items...

**Comment by slug13** [comment]
Hi Paul
i have done the turn on and off several times, especially after doing the Office repair twice.
The file you mention Microsoft.Office.Interop.Outlook was not found in the windows\assembly folder, 
However i did find it in the odd folder
G:\Old_windows\Windows.old\Program Files (x86)\Wide Angle Software\TouchCopy 12\
I don't know what version it is.
Searching for gacutil returns this:
![screenshot 2018-02-04 3](https://user-images.githubusercontent.com/34750436/35784077-0a9eca26-09e1-11e8-91c6-94d9aab5db58.jpg)

**Comment by phw198** [comment]
I think we may have found our culprit - I suspect Wide Angle Software has rather messed up your office install.

Anyway, try copying the Microsoft.Office.Interop.Outlook from that directory to the Windows\assembly folder...

**Comment by slug13** [comment]
Alas, did not work.

**Comment by phw198** [comment]
OK, remove the copied file and then download the [Outlook 2007 PIA](https://www.microsoft.com/en-gb/download/details.aspx?id=18346) (Primary Interop Assembly) - you'll need to run the downloaded `.exe` and then the `.msi` that's extracted. This should end up with a properly registered Outlook interop file in your `C:\Windows\assembly`.

(Of course, if you prefer, your other option is to uninstall and reinstall Outlook).

**Comment by slug13** [comment]
My Outlook is 2010 not 2007, so i found the 2010 PIA download. (the 2007 pia would not run saying no outlook 2007 installed)
I get the .msi file ok but I don't think its installing properly - the installer starts to run and then its gone.
No new file in the assembly folder.

**Comment by phw198** [comment]
Ah ok, I'd suggested 2007 as that is the PIA that OGCS is built on for maximum backward compatibility, but a later version won't matter for you.

Didn't seem good that the msi isn't doing much. Do you have administrator rights on your computer? You could try the [second step](https://msdn.microsoft.com/en-us/library/kh3965hw(vs.100).aspx) under "installing PIAs when you install Outlook", perhaps unchecking and rechecking to force install if it's already checked.

Otherwise I fear you're looking at a reinstall of Office...

**Comment by slug13** [comment]
Hi Paul
Well I did a fresh install of Office Professional Plus 2010( 64bit), rebooting after both uninstall and reinstall.
Your program as well reinstalled. Same error message. I'm about ready to give up.
Some screenshots follow of the windows\assembly folder now:
![screenshot 2018-02-05](https://user-images.githubusercontent.com/34750436/35836762-12968942-0ab0-11e8-9161-088d0cd0f568.jpg)
![screenshot 2018-02-05 1](https://user-images.githubusercontent.com/34750436/35836767-1c36b6ac-0ab0-11e8-8956-b0247350e40e.jpg)
![screenshot 2018-02-05 2](https://user-images.githubusercontent.com/34750436/35836771-20f08c22-0ab0-11e8-9afd-77a19e0b676f.jpg)

**Comment by phw198** [comment]
Hmm, that's the first mention of using Office 64-bit - any reason you're using that, or is using 32-bit Office an option? It's notoriously bad at running third party plugins etc :slightly_frowning_face: 

But not to quite throw in the towel yet...

:package: [v2.7.0.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1701191/v2.7.0.3.zip) has the outlook interop embedded within the OGCS executable ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

:package: [v2.7.0.4-64bit.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1701193/v2.7.0.4-64bit.zip) is compiled specifically for 64-bit and also with the PIA embedded (extract the ZIP to a new folder location and run from there).

Let me know how it goes.

**Comment by slug13** [comment]
Re the 64 bit - the stand-alone Outlook 2010 on my old machine was 64 bit, and was recommended by a Microsoft help guy. . So On the new machine i continued with a  64 bit instlall, this time the full Office suite.. Sorry i didn't mention it sooner. Tomorrow i will play with the new files you sent.. Too late tonight.

Re the previous screenshots above, you can see the Microsoft.Office.interop.Outlook folder.
Below is the content of that folder(didn't get sent last time)
![screenshot 2018-02-06 1](https://user-images.githubusercontent.com/34750436/35892527-b38b3ef2-0b77-11e8-8308-11b0522e54ca.jpg)

**Comment by slug13** [comment]
Better news!!
I ran v2.7.0.4, no error messages, however I could not select the Google calendar when pressing Retreive calendar, nothing happens

**Comment by phw198** [comment]
So a faint glimmer of hope! Though I'd much prefer not to have to maintain a 64-bit build of OGCS and I think your Microsoft guy has sold you on lies - the only reason I really know of for 64-bit Office is for high-end power users of Excel...

I take it v2.7.0.3 has the same original error?

Could you upload your logfile for v2.7.0.4?

**Comment by slug13** [comment]
v2.7.0.3 would not install. Unzipping and then clicking on the UAC prompt " yes", all app to make changes etc had no visible reulst.
[Here is logfile](https://gist.github.com/phw198/d73b892f1ea8c48dc602b3984a8065be)

**Comment by phw198** [comment]
v2.7.0.3 wasn't an install or standalone executable - it needs to replace the v2.7.0.0 executable...

**Comment by slug13** [comment]
Hi Paul
Glad you explained that.
Guess what - the sync worked !!
Don

**Comment by phw198** [comment]
Fantastic! So no need to worry about a 64-bit version of OGCS :grinning:

**Comment by slug13** [comment]
Thanks again Paul
OGCS working great now

Don

**Comment by phw198** [comment]
Glad we got there in the end and thanks for your help too, @slug13.
The change should be rolled into alpha v2.7.1 just released, if you do upgrade...
