### ISSUE TITLE
Exception in reccuring events created in Outlook automatically deleted in both calendars

### ISSUE THREAD

**Issue by 1lomeno3** [phw198/OutlookGoogleCalendarSync#461]
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed
**Problem Description**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1703995/OGcalsync.log)

When I have  Outlook <> Google sync and there is an exception in reccuring events created in Outlook, not only that this exception is not saved in Google but OGCS will also delete it in Outlook even without msg (delete confirmation is activated). What only helps is to change the direction to Outlook > Google.

**Steps to Reproduce the Issue**  
1. Create an exception to regular events
2. Do the Outlook <> Google sync

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to v2.7.0 by going to the `About` tab in OGCS and clicking `Check for Update`.

Let me know if you can then still replicate the problem...

**Comment by 1lomeno3** [comment]
Unfortunately the problem stil persists.

**Comment by phw198** [comment]
I'll need more detail then, as I can't replicate this. I did:
1. Created a daily recurring series in Outlook
1. 2-way synced it to Google
1. Moved one of the day's recurrences in Outlook to another time
1. 2-way synced it to Google

Works as expected.

Would be helpful if you could upgrade to v2.7.1, replicate the problem and let me know the name of the calendar item you are testing with?
