### ISSUE TITLE
Sync w/Exchange public folders

### ISSUE THREAD

**Issue by eh27** [phw198/OutlookGoogleCalendarSync#462]
**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

Is OGCS capable of syncing from an Exchange public folder?
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1708045/OGcalsync.log)
  It appears to connect to the folder and see calendar items within the specified date range but they are all filtered out.  I've tried every date/time format I can think of but still no joy.

Thanks,

E

**Comment by phw198** [comment]
Have you tried `dd/MMM/yyyy HH:mm` - I can't see that in the logs. Note, generally anything that includes seconds or AM/PM often doesn't work properly. 

It also looks like you had it working earlier: `The format 'f' returns 38 calendar items within the date range 02/08/2018 and 02/16/2018`?

**Comment by eh27** [comment]
The one successful sync was when I selected my default calendar by mistake.  Once I selected the public folder calendar I've had no luck.  Still trying though!

thanks

**Comment by phw198** [comment]
So as you've figured out, upping the logging to `FINE` helps see what the filter string is, and you have so far tested:
```
Filter string: [End] >= '02/07/2018 12:00 AM' AND [Start] < '02/12/2018 12:00 AM'
Filter string: [End] >= '02/07/2018 12:00:00 AM' AND [Start] < '02/12/2018 12:00:00 AM'
Filter string: [End] >= '02/7/2018 12:00 AM' AND [Start] < '02/12/2018 12:00 AM'
Filter string: [End] >= '2018-02-07 00:00:00Z' AND [Start] < '2018-02-12 00:00:00Z'
Filter string: [End] >= '2018-02-07 12:00 AM' AND [Start] < '2018-02-12 12:00 AM'
Filter string: [End] >= '2018-02-07 12:00:00 AM' AND [Start] < '2018-02-12 12:00:00 AM'
Filter string: [End] >= '2018-02-07T00:00:00' AND [Start] < '2018-02-12T00:00:00'
Filter string: [End] >= 'Wed 02/7/2018 12:00 AM' AND [Start] < 'Mon 02/12/2018 12:00 AM'
Filter string: [End] >= 'Wed 2/7/2018 12:00 AM' AND [Start] < 'Mon 2/12/2018 12:00 AM'
Filter string: [End] >= 'Wed, 02/7/2018 12:00 AM' AND [Start] < 'Mon, 02/12/2018 12:00 AM'
Filter string: [End] >= 'Wed, 07 Feb 2018 00:00:00 GMT' AND [Start] < 'Mon, 12 Feb 2018 00:00:00 GMT'
Filter string: [End] >= 'Wed, February 7,2018 12:00 AM' AND [Start] < 'Mon, February 12,2018 12:00 AM'
Filter string: [End] >= 'Wednesday 2/7/2018 12:00 AM' AND [Start] < 'Monday 2/12/2018 12:00 AM'
Filter string: [End] >= 'Wednesday, February 07, 2018 12:00 AM' AND [Start] < 'Monday, February 12, 2018 12:00 AM'
Filter string: [End] >= 'Wednesday, February 07, 2018 12:00:00 AM' AND [Start] < 'Monday, February 12, 2018 12:00:00 AM'
Filter string: [End] >= 'Wednesday, February 7,2018 12:00 AM' AND [Start] < 'Monday, February 12,2018 12:00 AM'
```
These all have "AM" or the timezone or seconds included - all to be avoided.

**Comment by eh27** [comment]
Still thinking that it has something to do with the public folder.  I tried several different combinations of date/time formats (leaving out any reference to seconds,time zone or AM/PM) without success.  If I select my default calendar it works with almost any format.  See below:

![image](https://user-images.githubusercontent.com/36274437/36050189-84dee480-0db3-11e8-9cd7-c46523e7e85c.png)


As soon as I select the available public folder (I'm the owner of the folder)  from the drop-down:

![image](https://user-images.githubusercontent.com/36274437/36050221-af536af6-0db3-11e8-9dbf-7877926dc21d.png)

**Comment by phw198** [comment]
You could well be right, but the odd thing is that your logs show it retrieving lots of calendar items from the public folder, but they are then all removed due to the date restriction; so I'd expect there to be a date format that works, just that it might be different from your non-public folder date format.

Out of curiosity, have you tried accessing the public folder as a "Shared Calendar"?

Unfortunately I don't think I have anywhere to test this as I'm pretty sure Public Folders are disabled at my work place.

**Comment by phw198** [comment]
Any luck with accessing the public folder as a "Shared Calendar"?

**Comment by eh27** [comment]
Hi Paul,

I'm afraid no luck.  It appears that public folder calendars are fundamentally different in some way.  There is a function in Outlook to export a calendar to a CSV file by selecting a range of dates and that will not work for public folders either.

On a more positive note...  I am using the application to sync a personal calendar to google and then linking that calendar to my Amazon Echo.  Works like a charm!  All I have to do is say "Alexa, what's my schedule look like today"

Thanks for the follow-up.

Ed

**Comment by phw198** [comment]
OK, good to know - thanks for updating.
