### ISSUE TITLE
Unexpected termination after update to v2.7.0.0 - Beta

### ISSUE THREAD

**Issue by Richio777** [phw198/OutlookGoogleCalendarSync#463]
" Could not load file or assembly 'office, Version=12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system could not find the file specified. "

Running Win10 Home fully updated
32gigs ram

I'm in the middle of a task I cannot interrupt, which may take several days. Therefore I cannot determine if a reboot will fix the issue. Task manager list did not show any obvious remnants of OGCS which needed to be terminated before trying again. 

Forgive me if this is the wrong place to report this or if my information supplied is in the wrong format or otherwise inadequate. Thank you.

**Comment by phw198** [comment]
Are you running 64-bit Office?

Anyway, sounds like a duplicate of issue #455 which has a fix.

**Comment by Richio777** [comment]
Believe it or not, Office Enterprise 2007. 

I can find nothing which specifies 64bit in the help/about. Nor from Word.
I have to leave for work, but will check #455 later. Thank you.

**Comment by Richio777** [comment]
Hi Paul,
'Still syncing a blockchain wallet, so I've not even been able to try a reboot as per #455.
However, I have updated to v2.7.1.0 - Alpha and everything functions perfectly.
Thanks (and closed)
Richard
(twice contributer)
