### ISSUE TITLE
Question wrt Which Outlook Calendar

### ISSUE THREAD

**Issue by ADKriel** [phw198/OutlookGoogleCalendarSync#466]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0 
**Installed or Portable**: Installed

**Problem Description**  
\<Which Outlook Calendar is accessed>

**Steps to Reproduce the Issue**  
1. \<Standard Sync  Procedure>

**Any other information**  
\<please advise which Calendar is used in Outlook.... Calendar or Calendar (this computer only)>

**Comment by phw198** [comment]
Whichever one you pick from the "Select calendar" dropdown under OGCS Settings > Outlook....?

**Comment by ADKriel** [comment]
My Outlook has two Calendar Options:  1. "Name"@Gmail.com and "Name"@Gmail.com (This Computer Only).
OGCS ONLY has an Options for Default Calendar and the "Select Calendar" which does NOT list the Calendars that are on the computer. Other Calendars are listed but those are the other emails that I draw in by registering those emails in Outlook that are NOT part of the default Outlook email address.

**Comment by phw198** [comment]
Struggling to understand your set up. Maybe some screenshots of your Outlook account configuration vs what OGCS shows would help....?

**Comment by ADKriel** [comment]
Hi Paul,
 I created “Tournaments” calendar on Google.  It seemed that OGCS selected that one, no others and not in the drop-down box, and I was confused.

I deleted that calendar in google and also cleaned up some other email addresses I had out of outlook, so that OGCS would find the correct one.

This worked… which means that OGCS has some issues:

1.	It cannot distinguish the calendars on Google.
2.	It cannot understand that more that one email address on outlook may have a calendar. Adding PST files to your Outlook brings the Calendar with it and if the Google email address is the same as the PST email address then it cannot distinguish it

Adrian Kriel

**Comment by phw198** [comment]
Did you provide screen shots with that email update? GitHub doesn't allow attachments with emails, so you'd need to log in to GitHub and make the update directly if so.

> if the Google email address is the same as the PST email address then it cannot distinguish it

I'm pretty confident that's not the issue. OGCS uses Object IDs to identify calendars both in Outlook and Google, not the email address associated with an account...

If you have multiple accounts set up in Outlook, then you'd select "Alternative Mailbox" in OGCS, select the right account and then the right calendar.

**Comment by ADKriel** [comment]
Hi Paul,

I have come right. Thanks for the info. Althogh you are using Object ID’s, there must be a difference between “Calendar (This computer Only)” and Calendar. These objects must differ as the Outlook App distinguishes between them.

TIA

Adrian Kriel

**Comment by phw198** [comment]
Not sure if you're still looking for help on this? If you are, screen shots of your calendar config in Outlook would help, but you need to log in to GitHub to upload them - attaching to email doesn't work.
