### ISSUE TITLE
Error message after installing

### ISSUE THREAD

**Issue by railfanron** [phw198/OutlookGoogleCalendarSync#467]
OGCS Version 2.7.0.0

Installed v. 2.7.0.0 on a Windows 10 machine. (Note: Same version on Windows 7 desktop works fine.)

Installed 

Receive this error message when application opens.

Application unexpectedly terminated!
Could not load file or assembly ‘office, Version=12.0.0.0,
Culture=neutral, PublicKeyToken=71e9bce111e9429c’ or one of its
Dependencies. The system cannot find the file specified.

This is the only log file I could locate.

<log4net>
	<appender name="Console" type="log4net.Appender.ConsoleAppender">
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="%date %-5level %logger [%L]: %message%newline" />
		</layout>
	</appender>
	<appender name="RollingFile" type="log4net.Appender.RollingFileAppender">
		<file type="log4net.Util.PatternString" value="%property{LogPath}OGcalsync.log" />
		<encoding value="utf-8" />
		<appendToFile value="true" />
		<maximumFileSize value="2MB" />
		<maxSizeRollBackups value="10" />
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="%date %level  %thread	%logger	[%L] -  %message%newline" />
		</layout>
	</appender>
	
	<root>
		<level value="DEBUG" />
		<appender-ref ref="Console" />
		<appender-ref ref="RollingFile" />
	</root>

	<logger name="DotNetOpenAuth">
		<level value="WARN" />
	</logger>
</log4net>

Application appears to fully install. When I open the program, it opens, then immediately displays the above error message. Have uninstalled and reinstalled several times to no avail.

**Comment by railfanron** [comment]
Here is the complete log file info:

<log4net>
	<appender name="Console" type="log4net.Appender.ConsoleAppender">
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="%date %-5level %logger [%L]: %message%newline" />
		</layout>
	</appender>
	<appender name="RollingFile" type="log4net.Appender.RollingFileAppender">
		<file type="log4net.Util.PatternString" value="%property{LogPath}OGcalsync.log" />
		<encoding value="utf-8" />
		<appendToFile value="true" />
		<maximumFileSize value="2MB" />
		<maxSizeRollBackups value="10" />
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="%date %level  %thread	%logger	[%L] -  %message%newline" />
		</layout>
	</appender>
	
	<root>
		<level value="DEBUG" />
		<appender-ref ref="Console" />
		<appender-ref ref="RollingFile" />
	</root>

	<logger name="DotNetOpenAuth">
		<level value="WARN" />
	</logger>
</log4net>

**Comment by phw198** [comment]
Instructions for finding the logfile is [here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#locating-your-ogcalsynclog-file), but this issue is fixed in v2.7.1 anyway.

:arrow_double_up: Upgrade by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`.

Duplicate #455.
