### ISSUE TITLE
Symantec is detecting virus in latest version (Probable false positive)

### ISSUE THREAD

**Issue by tosborne1215** [phw198/OutlookGoogleCalendarSync#468]
I was unable to auto update and decided to simply download the latest version. However, as soon as I clicked the link the corporate virus detection stopped the download. It looks like it was a heuristic check and I think it may be a false positive. The behavior of the program probably resembles data gathering trojans.

This was the link Symantec directed me to and indicated it was of type 'virus'
https://www.symantec.com/security_response/sape/

Thanks for the awesome software. It works great and I havent had an issue. Just wanted you to be aware

**Comment by phw198** [comment]
Thanks for reporting - yep these false positives are a pain. Think I need to spend some :moneybag: to sign OGCS with a certificate...

:link: Issue #295
