### ISSUE TITLE
Feature Request: Silently ignore network unavailable

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#47]
Is it possible to have OGCSync just silently ignore issues with internet
connectivity? It seems more appropriate to just abort the current sync and
automatically try again later. Often times my network connection will be
temporarily disrupted at work overnight for various reasons (system maint,
network blips, etc.), but OGCS stops syncing and shows a popup asking if I
want to retry. It's especially annoying if this happens say Friday just after
I leave work, and I don't get any syncs until I'm back in the office Monday
morning to click the alert popup.  
  
It would be much more helpful if there was a way for me to just set it to
silently ignore any network connection issues and just try to sync at the next
scheduled time. There's no need to alert me that the connection was
unavailable, I would expect 1) most users already know their internet is down
or 2) are not at their computer to see it and would appreciate it if the app
just automatically tried to sync again at next time.  
  
It seems like informing the user of network issue is unnecessary and just
leads to the app pausing with a popup.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 386](http://outlookgooglecalendarsync.codeplex.com/workitem/386)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Oct 16, 2016 at 2:11 PM
**Reported by:**	numericOverflow
**Updated on:**	Mar 2 at 7:03 AM
**Updated by:**	salzrat

**Comment by phw198** [comment]
On *2016-12-12 04:35:15 UTC*, **phw198** commented:

Will look to incorporate this.

**Comment by phw198** [comment]
On *2016-12-12 05:11:37 UTC*, **numericOverflow** commented:

@phw198 - Thanks! I'll gladly beta something if you need a tester. This issue happens to me on a fairly regular basis, so a fix would be greatly appreciated.

**Comment by phw198** [comment]
On *2017-03-02 15:03:10 UTC*, **salzrat** commented:

Hi,

I would really stronlgy vote for this - it is very simple, and it is really annoying to regularly get these popups when I open my laptop on the road and it takes a minute to establish internet connection.

**Comment by ScottRochford** [comment]
Another vote for this enhancement, please.  I think it would be a good idea to just change the colour or put a small red cross on the system tray icon when the most recent sync has failed for some reason.

**Comment by phw198** [comment]
This will form a subtask of #375 - so next on the list...

**Comment by phw198** [comment]
Can anyone upload their logfile of when they see this problem?

When I test without network connectivity OGCS just reports the following, without any popups etc:
```
There does not appear to be any network available! Sync aborted.
Another sync has been scheduled to automatically run in 5 minutes time.
```
Please upgrade to the latest alpha version too before providing any log files.

**Comment by philshifley** [comment]
Would love a silent mode.  Everytime it checks it makes a noise - am I missing something? Is there a switch or something to make it silent? When I'm watching Netflix the noise can be jarring.

**Comment by phw198** [comment]
@philshifley I think you're referring to a different "silence". Sounds like you have the `Show bubble tooltip in tray when syncing` option set. Uncheck it?

![capture](https://user-images.githubusercontent.com/11843015/34416500-bac40f1a-ebeb-11e7-9767-2f71de1bc190.PNG)

**Comment by phw198** [comment]
:package: [v2.6.5.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1593537/v2.6.5.4.zip) should now retry silently ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) and make sure it is applied on top of at least v2.6.5.0).

Please give it a go and let me know!

**Comment by phw198** [comment]
Anyone got any feedback on the development release v2.6.5.4?

**Comment by ScottRochford** [comment]
Hi Paul, I've been running it for about 3 days and it seems to be working fine.  In light of your Dec 4 comment "When I test without network connectivity OGCS just reports the following..." I'm not sure exactly what scenario causes it to pop up the "Would you like to test with internet explorer" dialogue, but I haven't seen one since then.  I suspect it is when network connectivity is detected, but there is something further up the line preventing OGCS from contacting Exchange or Google.

Thanks!

**Comment by phw198** [comment]
@ScottRochford Sounds promising!

Yes, I replicated what I think was the problem by setting an invalid proxy to simulate network failure and coding a fix against that.

**Comment by rmdodhia** [comment]
I followed this from issue #74. I have the same request in #74. Is there a way to disable this message? No idea why it happens. 
Logs, settings and error message attached.

![image](https://user-images.githubusercontent.com/40476088/51853536-63dc2780-22dd-11e9-833d-c2b6eee7a364.png)



[OGcalsync.log.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2804091/OGcalsync.log.zip)

**Comment by phw198** [comment]
@rmdodhia The logs you have provided do not seem to cover when the popup happened, so I cannot see why it occurred. Could you search your log files for "Updated event failed to save" and upload that one - but please create a new issue to cover this.
