### ISSUE TITLE
Error loading the program - will not run [0x80029C4A]

### ISSUE THREAD

**Issue by halology** [phw198/OutlookGoogleCalendarSync#470]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
I get this error when loading the program:
![outlooksyncerror](https://user-images.githubusercontent.com/36509800/36263893-3c50ba60-1239-11e8-9502-0c2db983ccf5.jpg)

**Steps to Reproduce the Issue**  
1. \<Update>
1. When I start the program.

**Any other information**  
\<Update here>
![outlooksyncerror](https://user-images.githubusercontent.com/36509800/36263893-3c50ba60-1239-11e8-9502-0c2db983ccf5.jpg)

**Comment by phw198** [comment]
What version of OGCS were you running? I would have expected the error to [take you to this wiki page](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary). Does the info there help?

:spiral_notepad: Could you provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)) so I can see why OGCS didn't take you to the wiki automatically?

**Comment by halology** [comment]
The info in the w2iki did not help.

**Comment by phw198** [comment]
If you want support you need to explain what you tried and what exactly didn't work etc.

Also, see issue #288 for a user that had the same error as you.
