### ISSUE TITLE
Changes sync but not new events

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#473]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1735276/OGcalsync.log)
**OGCS Version**: v2.7.1.0
**Installed or Portable**: Installed

**Problem Description**  
Recently, events stopped syncing between the calendars, no matter where they were created. Events I add in one do not show up in the other, but if I change the name of an event that does sync.

**Comment by phw198** [comment]
So you're creating the appointment in Outlook? Are you creating it from scratch or copying and pasting an existing appointment?

Have you made sure your [Outlook date format](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) is correct? Try narrowing your sync range to a day, creating a new appointment on that day and then testing it gets picked up. If you turn on CSV creation, after a sync you could also check in outlook_appointments.csv and confirm it's listed (or not).

**Comment by ghost** [comment]
Well, at least it's sorted now. Narrowing the date range made me realise that the events I was expecting to sync were outside the 60 day limit that was set. So I just increased that and it's all working fine. Sorry for wasting your time and thankyou for helping!
