### ISSUE TITLE
Will not connect to Google Calendar

### ISSUE THREAD

**Issue by aquarist-bryan** [phw198/OutlookGoogleCalendarSync#476]
**OGCS Version**: v2.7.1.0
**Installed or Portable**: Installed

**Problem Description**  
Initially the program worked great, but then it stopped syncing with my Google Calendar.  I go in and attempt to retrieve my google calendar account and it takes me to the google page, I select my account and then on the next page select allow so that OGCS has access, it says it is sending an authorization code and then the window closes, but when I go back into the program, it says that the retrieval failed.  I also deleted the older version and installed the newest version and that did not fix the problem.  Is there something I need to change in my google calendar to allow access?

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1744781/OGcalsync.log)

\<Update here>

**Comment by phw198** [comment]
I would suspect that you have either firewall software or antivirus software blocking the connection that is required for the authorisation to compete. Can you temporarily disable any such software and see if that helps?

**Comment by aquarist-bryan** [comment]
I am trying to make it work on a work computer and I do not have administrator access to change my software or settings.  I found another work around.  Thank you for your help.

**Comment by phw198** [comment]
Thanks for the update 👍
