### ISSUE TITLE
OGCS won't sync to Google anymore.

### ISSUE THREAD

**Issue by UmbraChimera** [phw198/OutlookGoogleCalendarSync#477]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0 Beta
**Installed or Portable**: Installed

**Problem Description**  
Unable to have Outlook events Sync to Google

**Any other information**  
Log attached
[OGCS_Log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1749468/OGCS_Log.txt)

**Comment by phw198** [comment]
Are you using a proxy? It's failing to even talk to GitHub: `Failed to retrieve data: The request was aborted: Could not create SSL/TLS secure channel.`.

Also, were you using you're own API key? If so, have you enable the Google+ API?

**Comment by UmbraChimera** [comment]
No Proxy and no unique API key setup. Standard install and linked the google account. Was working for them before, and then just quit.

**Comment by phw198** [comment]
Are you being taken to the Google website to authorise OGCS to manage your calendar when you try and sync?

Either way, can you move/rename/delete `C:\Users\pludw\AppData\Roaming\Outlook Google Calendar Sync\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user` out of the way and then start OGCS and try a sync. This should force it to re-authorise.

**Comment by phw198** [comment]
BTW, v2.7.2 fixes the `SSL/TLS secure channel.` problem.
