### ISSUE TITLE
latest stable version crashes?

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#478]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by ghost** [comment]
[2018-02-22_16-30-13.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/1749944/2018-02-22_16-30-13.pdf)
This from the latest stable version. I dont get the summary at the end.
I have visual studio 2017 installed, could this be the cause?

**Comment by phw198** [comment]
That's unlikely related to the version of OGCS you're using, but a recent bad upgrade or patch of Office. See Issue #288.

Did you mean to close this ticket?

**Comment by ghost** [comment]
Actually on using the latest office version too. I'll try the repair. No I
didn't understand the instructions.
