### ISSUE TITLE
Outlook Warning on Computer Startup

### ISSUE THREAD

**Issue by tzaltd** [phw198/OutlookGoogleCalendarSync#480]
**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
Recently installed (and paid) - all working fine except for the popo-up as described here: 
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security

**Steps to Reproduce the Issue**  
Start PC - every time it happens

**Any other information**  
Trust Settings in Outlook 2016 are as per the above instructions.

Have to press OK 3-4 times to get it to go away.

Using ESET Internet Security

Also, when starting PC Outlook often starts by itself.

Don't want to turn off all warnings as per: https://github.com/phw198/OutlookGoogleCalendarSync/issues/269

Any suggestions?

**Comment by phw198** [comment]
Have you tried setting a startup delay in the options of OGCS? May be that it's running before either Outlook or your antivirus is properly ready...

**Comment by tzaltd** [comment]
Thanks! Setting to longer delay seems to have sorted it. Odd thing was though, if set too long it didn't show in the tray. 120 secs seems to be right for my PC.
