### ISSUE TITLE
Command line parameter for custom settings.xml

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#481]
To better support syncing of multiple calendars by running concurrent instances of OGCS (see #165), @sgoschin suggested allowing the option to specify the settings.xml file to be used on the command line. 

This will also help testing OGCS against different configurations, so probably should have done this a long time ago!

- [x] /? or /help = dialogue box of switches
- [x] /s:settings.xml = specify settings file
- [x] /l:ogcalsync.log = specify logging file
- [x] /d:60 = startup delay in seconds (migrated from --delay)

**Comment by phw198** [comment]
:package: Development build [v2.7.1.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1778953/v2.7.1.4.zip) ([see instructions for applying in the same way as a hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Note, the `Start on startup` option will only work for a single instance of OGCS, so if you want multiple instances of OGCS to start on startup with different configurations, either 
* manually create your own registry keys in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`, or
* Drop `.bat` files into your Windows menu `Startup` folder

It's also likely safest to use full paths to reference the settings.xml file / log file.

Please let me know how it goes!

**Comment by skippy428** [comment]
Would it be possible to get a more clear explination of how to handle creating new registry keys or .bat files.  I think that helps solve the issue of having to open up multiple instances of OGCS for multiple calendar syncs.

I'm referencing back to the comments:

> Note, the Start on startup option will only work for a single instance of OGCS, so if you want multiple instances of OGCS to start on startup with different configurations, either
> 
> manually create your own registry keys in HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run, or
> Drop .bat files into your Windows menu Startup folder
> It's also likely safest to use full paths to reference the settings.xml file / log file.

Overall, I'm just looking for step by step explanation of how to setup OGCS with multiple calendar syncs and for it to open/run all of them automatically after like a computer restart.  So if multiple .bat files could help solve for this, how do the .bat files get created and where do they go?

**Comment by phw198** [comment]
@skippy428 Take a look at Issue #165 - instructions are more detailed there and hopefully that will have what you're after.
