### ISSUE TITLE
Multiple Outlook Accounts Please

### ISSUE THREAD

**Issue by RAF51** [phw198/OutlookGoogleCalendarSync#482]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.1.0 
**Installed or Portable**: Installed

**Problem Description**  
Need to sync another separate Outlook account

**Steps to Reproduce the Issue**  
Can only select the installed Outlook Account

**Any other information**  
I use Outlook for work, and not allowed to add other outlook accounts to it. I also have a google account where I have my own personal calendar set up. So far I have been ok with the syncing between the two so that I can see personal plans when I schedule whilst at work - so great.

I now have a need to also add into the mix, a shared outlook calendar that is also used for personal activities, but separate from work and my personal calendar.

Can multiple Outlook accounts be facilitated please, or suggestion of how I might be able to acheive?

Thanks

(Great product)

**Comment by phw198** [comment]
Hi @RAF51, you'll be after #165 - which I've only just made an improvement to through #481.

Have a read through those issues and see if that provides what you need.

**Comment by RAF51** [comment]
Thanks - I tried the step 3 from that ticket and now I have two entries of everything in my Google calendar after syncing (one from my original OGCS syncing and another from this new 'portable' syncing) - must have not done it right - I resolved by deleting the Google Calendar duplicate entries.

However, I can not see any way of defining the Outlook Calendar that I want to sync with the ONE Google Calendar - it just refers to the Outlook on the PC I am using. How do I specify that I want a different Outlook Account Calendar to be synced with the ONE Google Calendar please?

**Comment by phw198** [comment]
My apologies for failing to mention this, OGCS doesn't fully support multiple calendars into a single target calendar - especially if you're two-way syncing. See the _supported configuration_ diagram on the home page of the project site.

As a workaround, can you sync each Outlook calendar into a dedicated Google calendar and then just display both calendars at the same time in Google?
