### ISSUE TITLE
Google to Outlooc Sync : all events created as private

### ISSUE THREAD

**Issue by FCalderoni** [phw198/OutlookGoogleCalendarSync#483]
----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
I am syncing my google calendar to my outlook calendar, one way. Subsequently i share my outlook calendar with my colleagues
I have noticed that all my events in the Outlook calendar were private, with my colleagues unable to see details. 
I have made my calendar public in google and tried to add new events. They are still seen as private in Outlook. 
I have also tried to mark a new event specifically as public in google calendar. Once it is synced to Outlook, it is still private.

**Comment by phw198** [comment]
It is not the availability of your Google calendar that matters, but the availability of the individual Google appointments. Have you set an appointment as "Free" in Google and then checked it's also set as that in Outlook after a sync?

Alternatively, force everything to be "free" in Outlook with (note the `Less` button is `More` before it's clicked):
![image](https://user-images.githubusercontent.com/11843015/37107153-83b67488-222b-11e8-9fb7-b82a79a4cd28.png)

You'd then need to do a `Shift`+Sync to force a full sync.

**Comment by FCalderoni** [comment]
Thank you, you saved me!
