### ISSUE TITLE
OGCS not detecting system timezone change

### ISSUE THREAD

**Issue by amollerup** [phw198/OutlookGoogleCalendarSync#486]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.1.0 Alpha  
**Installed or Portable**: Installed

**Problem Description**  
The OGCS app time is not updated when Windows timezone has changed. In order for the OGCS app to have the correct time after a Windows timezone change, it needs be relaunched. As a result, synced calendar entries may have the wrong time when the Windows timezone is changed.

**Steps to Reproduce the Issue**  (Note: times below represented as 24-hr clock)
1. Windows time is 10:01 MST
2. Launching OGCS; app time is 10:01.
3. Changing Windows timezone to PST. Windows time is 09:01 (PST). OGCS app time is still 10:01.
4. Synchronizing an event from Google to Outlook (Outlook <- Google) with a start time of 13:30 MST. The event is synced to Outlook with a start time of 13:30. However, again, Windows time is 09:01 (PST), but the OGCS app time is 10:01. I assume this is the cause of the incorrect time of the new Outlook entry. The new Outlook event should have a start time of 12:30 (PST).
5. Changing Windows timezone back to MST. The Outlook event now has a start time of 14:30 (MST). It is 1 hour ahead of where it should be. Restarting the OGCS sync does NOT move the entry back to the correct start time.

**Any other information**  
1. It appears to me that OGCS should check Windows time and update app time before each sync, and not just at app launch.
2. In the debug log, the event titled "PPS Account Open" is the one I used to reproduce the issue above.
3. [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1794099/OGcalsync.log)

**Comment by phw198** [comment]
Thanks for reporting the issue so clearly - think this has been the same issue with daylight saving for a while too, so good to get fixed!

:package: This should now be resolved with [hotfix v2.7.1.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1800314/v2.7.1.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by Vasago** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	OutlookGoogleCalendarSync.exe
  Application Version:	2.7.1.6
  Application Timestamp:	5aa5212a
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24009
  Fault Module Timestamp:	5a523c5b
  Exception Code:	e0434352
  Exception Offset:	0000c54f
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Vasago** [comment]
Ah sorry I didnt update to Alpha version first - now ok.

**Comment by amollerup** [comment]
@phw198  : The issue I described above appears to be fixed in the hotfix v2.7.1.6. I can't recreate the problem with that version. Thanks!
