### ISSUE TITLE
No limit on error page openings when encountering COM error [0x80010100]

### ISSUE THREAD

**Issue by leemi** [phw198/OutlookGoogleCalendarSync#488]
**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
I changed my password in Active Directory, but didn't update credentials in Outlook and left my computer on overnight. When I came back to the computer, I had at least 15 tabs of https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors
Looks like this page gets opened every time it retries and there's a COM error?

**Steps to Reproduce the Issue**  
1. Change ADS Password
1. Leave computer
1. Return to computer, see browser tabs

**Any other information**  
[OGcalsync.log.2018-03-13.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1811391/OGcalsync.log.2018-03-13.txt)

**Comment by phw198** [comment]
Thanks for reporting - and I have also updated the wiki page now.

**Comment by phw198** [comment]
@leemi FYI, I see your update checks were also failing, for which I've issued a patch over on #490 if you would like to apply it.
