### ISSUE TITLE
Shared calendar sync - need to select calendar anew at every sync when outlook is not running

### ISSUE THREAD

**Issue by gnubee40** [phw198/OutlookGoogleCalendarSync#491]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

Link to Log
https://gist.github.com/gnubee40/158baf339914e5c230064b9a9a945ac1#file-ogcslog16-3-18-txt  

----

**OGCS Version**: Version | 2.7.1.0-
**Installed or Portable**: Portable

**Problem Description**  
Shared calendar needs to be selected anew at every sync as long as outlook is not running.
The window pop-ups, and the shared calendar has to be selected. In the windows tray outlook is open stating it is being used by another program. This icon stays and a process is visible in the process list, but never the less, at every sync, the procedure the outlook window pops up again.

**Steps to Reproduce the Issue**  
1. Select a shared calendar to sync with google calendar. I tried bidirectional sync and outook as master. Save settings.
2. Close outlook.
3. Hit the sync button.
4. Sync halts - Window pops up - choose the shared calendar again.
5. Sync finishes without trouble.
6. Hit the sync. button again.
7. Sync halts - Window pops up - Choose the shared calendar again,
etc. Same procedure when auto-syncing

As soon as outlook is started regularly as a program the prompts disappear and sync happens as expected.

Suggestion:
If it is not technically possible to access a shared calendar without outlook running as a programm (not just as a process), I would prefer OGCS to postpone sync rather than ask for the calendar each time. 

Best regards

**Comment by phw198** [comment]
Pretty sure this has been fixed through #534, if you'd like to test the hotfix there.

**Comment by gnubee40** [comment]
Ok - just saw your comment today. I am working mostly from home now. So will apply hotfix and have a look during the week.

Best regards
Nino

**Comment by phw198** [comment]
Hi @gnubee40 - did you get round to testing this?

**Comment by gnubee40** [comment]
Hey Poul.

Hope u had a Merry Christmas.

Sorry. I am rarely at my office these days. So don't use the program. Maybe
best just to close the bug for now.
Happy new year!

fre. 28. dec. 2018 16.47 skrev Paul Woolcock <notifications@github.com>:

**Comment by phw198** [comment]
Hi and thanks for the response, I'll get this closed out 🙂 

Happy New Year to you too - all the best!
