### ISSUE TITLE
"Proxy Authentication Required (407)" when inheriting from IE

### ISSUE THREAD

**Issue by Kuehling** [phw198/OutlookGoogleCalendarSync#492]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?   NO
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: V2.7.0.0
Installed

**Problem Description**  
First time Google calendar retrieval does not work.

**Steps to Reproduce the Issue**  
1) I tried to retrieve my Google Calendar and to approve

Click on Setting -> Google 

2) Google welcome page opens and I can choose my account press approve 

3) For a short time the message "retrieving verification code ... Close" ... White window

4) however nothing happens, within OGCS I still cannot choose the calendar.

Proxy problem
**Any other information**  

Outlook is used within the company with proxy authentication. 

Any help appreciated

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1819277/OGcalsync.log)

Heiko

**Comment by phw198** [comment]
Hi @Kuehling - yes you're getting `(407) Proxy Authentication Required.` errors. 

Are the credentials for your proxy the same as your Windows credentials?

**Comment by phw198** [comment]
Any update on this?

**Comment by Kuehling** [comment]
Hello Paul,

Sorry for my delayed answer. I was not in the office for some days.

I got it running now, somehow I interpreted the settings wrong, I thought,
when the proxy setting is set to "inherit from Internet explorer", and it
would take over the setting from IE.

However, it did not. I could solve it my manually entering proxy settings,
but it took several attempts until the Google calendar was found and
recognized.

It now seems to work. Thank you anyway for your assistance and the program!

Best regard and happy Easter!

Heiko

**Comment by phw198** [comment]
Glad you got it working. 

But yes, it should inherit the settings from IE, though I think it is assuming the proxy password is the same as your Windows password - hence my question as to whether they are the same for you or not?

**Comment by Kuehling** [comment]
Hello Paul,

the password for the proxy is (and was) different from my Windows Login.

BR
Heiko




2018-04-03 8:52 GMT+02:00 Paul <notifications@github.com>:

**Comment by Smog418** [comment]
I have the same problem here...

I use last alpha 2.7.4.0.

I share my log. Thanks for help!
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2141680/OGcalsync.log)

**Comment by phw198** [comment]
@Smog418 It's similar, but definitely not the same. I've created issue #546 for you to investigate further.

**Comment by r3tner** [comment]
Same issue for me. It used to work on an older version (maybe 2.6.x).

Since I tried to upgrade to a newer release, I can't authenticate with Google. It gives me the token then nothing happens.

I am behind a proxy, set by a script - URL for the script in the IE proxy window. This was the same before, when it used to work.

Thanks

**Comment by phw198** [comment]
@r3tner are you able to upload your OGcalsync.log file?

**Comment by r3tner** [comment]
Sorry for the delay. Thank you.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2366371/OGcalsync.log)

**Comment by phw198** [comment]
@r3tner Nope, yours isn't a 407 error either:
```
System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
```
Feels to me like your proxy server may have a certificate that isn't fully trusted?

**Comment by phw198** [comment]
:link: #820
