### ISSUE TITLE
Duplicated calendar entries in Outlook

### ISSUE THREAD

**Issue by pratikchak** [phw198/OutlookGoogleCalendarSync#493]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
Google calendar events are being duplicated when get synced in Outlook. This is creating multiple versions of the same event in Outlook.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1819945/OGcalsync.log)

**Steps to Reproduce the Issue**  
This duplication happens mainly when the organizer of the Google event changes the 'description text' of the meeting, or when the organizer adds a meeting room to the original invite. I feel the application is probably also using the calendar event's description to match entries between Outlook and Google. So it thinks that the Google event is a new event, instead of being an update to an existing event.

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. Alternatively, [download directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

**Comment by phw198** [comment]
I'll assume you tried the first option of updating through OGCS (which GitHub have broken and is fixed in v2.7.2). Upgrade by downloading from the website, as I suggested as an alternative.

**Comment by pratikchak** [comment]
Thanks I downloaded and installed V2.7.2.0. Lets see if this fixes the problem.

**Comment by TontonLud** [comment]
I have the same problem with one way Sync, Outlook to google. 
When I change start time or end time, very often it duplicate the event in google calendar.
I'm running last alpha version 2.7.2
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1890552/OGcalsync.log)
