### ISSUE TITLE
Norton Blocking download - marking program as unsafe

### ISSUE THREAD

**Issue by Slushbender** [phw198/OutlookGoogleCalendarSync#494]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

Ideas? Comments? I like the program

**OGCS Version**: v1.2.3.4     Unknow version as Norton Blocked install  (Windows7)

**Problem Description**  
\Not sure what to do. I have been using OutlookGoggleCalendar for about a month. Had to reinstall Windows and when I went to download OGC again, Norton stopped it indicating it was unsafe. setup contained threat WS.Reputation.1 Risk Medium
Threat type. Insight Network Threat.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Do you have the ability to whitelist/exclude the OGCS installer executable from Norton scanning? 

If not, you could try the portable version.

The problem in general is covered by #295 - am gearing up to shell out for code signing certificate which should help mitigate the problem.
