### ISSUE TITLE
Only syncing recurring items :(

### ISSUE THREAD

**Issue by Rachel144** [phw198/OutlookGoogleCalendarSync#495]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.2.0  
**Installed or Portable**: Installed

**Problem Description**  
I sync on a computer from Outlook to Google Calendar.
My normal (not recurring) calendar appointments are not syncing.
Only the recurring appointments are syncing now.
I updated from 2.7.0 to 2.7.2 to see if this resolves the issue, but sadly it does not.
I also tried 'Full Sync' (with the shift button), but that makes no difference.

**Steps to Reproduce the Issue**  
1. Run Outlook Google Calendar Sync\<Update>
1. Hit Sync

**Any other information**  
\<Update here>
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1824382/OGcalsync.log)

**Comment by phw198** [comment]
Hi @Rachel144 - it looks like you have specified a custom Outlook date format `yyyy-MM-dd hh:mm tt`? It normally comes down to [testing different formats](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) until it returns the right number of items. It also seems that sometimes, Outlook suddenly needs this changing through no identifiable reason (but perhaps related to users travelling through timezones, for example)...

**Comment by Rachel144** [comment]
Great!
Changed it to Full Month, since this gave the highest number of changes
(140!), where generic and custom only gave 39. The other options all gave
0...

Everything is working again! Thanks :D.

Rachel.
