### ISSUE TITLE
App doesn't start [0x80029C4A]

### ISSUE THREAD

**Issue by rmb17** [phw198/OutlookGoogleCalendarSync#498]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
The app crashes upon startup.

**Steps to Reproduce the Issue**  
1.  Run OGCS

**Any other information**  
![capture](https://user-images.githubusercontent.com/37656523/37763747-a7eeffea-2d9e-11e8-8448-82a59c5dcd85.JPG)

**Comment by phw198** [comment]
Could you try running a repair of Outlook:

1. Open Control Panel and "Uninstall a Program"
1. Select the "Microsoft Office" program and click "Change"
1. Select "Quick Repair" and click "Repair"
1. Start OGCS

:spiral_notepad: Would also be helpful if you could provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)) as the error should have taken you to the wiki for possible solutions.

**Comment by rmb17** [comment]
Performed quick repair, and online repair. Log file attached.

**Comment by phw198** [comment]
:paperclips: Unfortunately, files can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

Assuming you still have the same error code `0x80029C4A`, could you please try [going through the registry fixes](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#registry-fixes) as described in the wiki?
