### ISSUE TITLE
Obfuscation rules not applied to all attributes

### ISSUE THREAD

**Issue by arcadian2** [phw198/OutlookGoogleCalendarSync#500]
**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Portable

**Problem Description**  
\Obfuscation rules not applied to some attributes like meeting location. I would suggest applying obfuscation rules on each synced attributes like topic, location, description,...

**Comment by mmangelsdorf** [comment]
Or even have different rule sets for the different attribute types.

**Comment by kabadi** [comment]
This would be very useful

**Comment by phw198** [comment]
:package: This should now be possible with [hotfix v2.10.1.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12445569/v2.10.1.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

In the obfuscation table, there's a new column `Target` which takes the following values (any combination of letters permitted):
* S = Subject
* L = Location
* D = Description/Body

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/f1256796-2adc-4a37-beb3-82bfd1358201)

Let me know how it goes!
