### ISSUE TITLE
Deleting all entries from recent sync

### ISSUE THREAD

**Issue by troymcloore** [phw198/OutlookGoogleCalendarSync#501]
Hi is there a way to remove all entries just added to my outlook calendar from google calendar via a sync? I forgot to check the box that says mark all items private and there's a lot of them to do manually. :-) Thank you!!!

:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Kick off a full sync by pressing `Shift` while clicking the `Sync` button.

**Comment by troymcloore** [comment]
thank you!!
