### ISSUE TITLE
"Due to your category settings, all Outlook items have been filtered out!"

### ISSUE THREAD

**Issue by mmachnicki13** [phw198/OutlookGoogleCalendarSync#503]
----

**OGCS Version**: v2.7.0.0

**Installed or Portable**: Installed

**Problem Description**  
Due to your category settings, all Outlook items have been filtered out! 

**Steps to Reproduce the Issue**  
1. Sync attempt

**Comment by phw198** [comment]
Not sure what you're reporting here.

**Comment by mmachnicki13** [comment]
I guess I'm not sure what could be causing the issue in my category settings to be filtering out all Outlook items. The error message "Due to your category settings, all Outlook items have been filtered out!" isn't clear on what action I need to take to correct the issue.


![ogcs](https://user-images.githubusercontent.com/37815261/37936963-3fc4481c-311d-11e8-96cb-389f9500404e.jpg)

**Comment by phw198** [comment]
The screen I would need to see is the Settings > Outlook tab (or your log file) and, as the message indicates, I would expect that the categories you have selected for syncing don't have any calendar items in scope.

**Comment by mmachnicki13** [comment]
Looks like I have resolved it by including "no category assigned. Case closed.

![1234](https://user-images.githubusercontent.com/37815261/37974042-78534d5c-31a1-11e8-8d45-dbdc2dce6333.png)

![ogcs](https://user-images.githubusercontent.com/37815261/37974121-b2113450-31a1-11e8-9cb1-8f7433e33746.jpg)
