### ISSUE TITLE
Application Unexpectedly Terminated

### ISSUE THREAD

**Issue by Torgut** [phw198/OutlookGoogleCalendarSync#505]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Portable

**Problem Description**  

Upon running the portable EXE an error message pops up:

Application Unexpectedly Terminated

Could not load file or assembly 'office, Version = 12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.

\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. Run the portable exe

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
And what version of OGCS are you running? As per issue #455, should be fixed in v2.7.1

**Comment by Torgut** [comment]
Portable_OGCS_v2.7.0 
Will look for the 2.7.1 right away and will inform. And thanks a lot for everything!

**Comment by Torgut** [comment]
It starts. Will test it a bit later today. Are there any plans to include Tasks in the sync?

**Comment by phw198** [comment]
No, no plans for tasks yet (Contacts seems to be a more popular request) - but feel free to raise another issue to request task sync.
