### ISSUE TITLE
two way sync does not work

### ISSUE THREAD

**Issue by Viennasurfer** [phw198/OutlookGoogleCalendarSync#507]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.2.0  
**Installed or Portable**: Installed on Windows 10 , Google used on Portable with Android

**Problem Description**  
I have selected 2-way sync. Outlook --> Google works nicely, Google --> Outlook does not work, even if  I change to 1-way sync Google --> Outlook

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1887883/OGcalsync.log)

**Comment by phw198** [comment]
What's your definition of "doesn't work"?

OGCS is reporting "107 Google items would have been deleted, but you have deletions disabled." - this would be because they items at some point matched in Outlook, but have since been deleted. If you are expecting any changes in Google within those 107 to sync to Outlook, then they won't and they shouldn't.

**Comment by Viennasurfer** [comment]
I do not mean these not deleted items. No items I have entered to my google calender are shown in Outlook.

 

Thank you for your help

Fred

Gesendet: Sonntag, 08. April 2018 um 22:15 Uhr
Von: Paul <notifications@github.com>
An: phw198/OutlookGoogleCalendarSync <OutlookGoogleCalendarSync@noreply.github.com>
Cc: Viennasurfer <alfred.gutmann@gmx.ch>, Author <author@noreply.github.com>
Betreff: Re: [phw198/OutlookGoogleCalendarSync] two way sync does not work (#507)


What's your definition of "doesn't work"?

OGCS is reporting "107 Google items would have been deleted, but you have deletions disabled." - this would be because they items at some point matched in Outlook, but have since been deleted. If you are expecting any changes in Google within those 107 to sync to Outlook, then they won't and they shouldn't.

**Comment by araalij** [comment]
Had smilar issues but have  managed to work around them.

I'm guessing that one has to choose a primary populated calendar to copy into an empty secondary calendar and perform an initial sync for the period of time to cover before selecting bi-drectional sync to maintain. Seems to have worked for me.

Am now Synced 102 days in the past and 263 days into the future.

**Test 1: Outlook -> Google**

1. Reinstalled OGCS and started off with a empty Outlook calendar
2. Mistakenly left sync options set with Outlook -> Google

Result: 
Sync version: 2.7.0.0
Sync started at 11/04/2018 12:14:19
Syncing from 10/04/2018 to 13/04/2018
Outlook -> Google

Finding Calendar Entries
Scanning Outlook calendar...
0 Outlook calendar entries found.

Scanning Google calendar...
20 Google calendar entries found.

Total inc. recurring items spanning sync date range...
Outlook 0, Google 20
20 Google items would have been deleted, but you have deletions disabled.

0 Google calendar entries to be deleted.
0 Google calendar entries to be created.
0 calendar entries to be compared.

0 Outlook calendar entries to be deleted.
0 Outlook calendar entries to be created.
0 calendar entries to be compared.

Sync finished with success!


**Test 2: Outlook ↔ Google**

1. Set OGCS to do bi-directional sync

Result: 
Sync version: 2.7.0.0
Sync started at 11/04/2018 12:15:19
Syncing from 10/04/2018 to 13/04/2018
Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...
0 Outlook calendar entries found.

Scanning Google calendar...
20 Google calendar entries found.

Total inc. recurring items spanning sync date range...
Outlook 0, Google 20
20 Google items would have been deleted, but you have deletions disabled.

0 Google calendar entries to be deleted.
0 Google calendar entries to be created.
0 calendar entries to be compared.

0 Outlook calendar entries to be deleted.
0 Outlook calendar entries to be created.
0 calendar entries to be compared.

Sync finished with success!

**Q:** Why is the app trying to delete Google calendar entries and failing to add them to Outlook?

Test 3: Outlook <- Google

1. Set OGCS to sync from Google to Outlook

Result: 

Sync version: 2.7.0.0
Sync started at 11/04/2018 12:28:43
Syncing from 10/04/2018 to 13/04/2018
Outlook ← Google

Finding Calendar Entries
Scanning Outlook calendar...
0 Outlook calendar entries found.

Scanning Google calendar...
20 Google calendar entries found.

Total inc. recurring items spanning sync date range...
Outlook 0, Google 20

0 Outlook calendar entries to be deleted.
20 Outlook calendar entries to be created.
0 calendar entries to be compared.

Creating 20 Outlook calendar entries
12/04/2018 12:00 "GoToWebinar - GDPR for entrepreneurs and start-ups"
10/04/2012  "1st date w/ Claire"
12/04/2018 "Lailat al-Ma'raj"
11/04/1978  "Susannah Patton's Birthday"
11/04/2005  "Steve & Don's anniversary"
25/01/2017 19:00  "Distillers (Hammersmith) - Open Mic Night"
02/11/2017 14:00  "Kids on the Green "
01/11/2017 14:00  "Kids on the Green "
11/04/2018 12:00 "KotG - Zoe"
12/04/2018 06:00 "TMC - Testing"
26/12/2016 08:30  "RescueTime - Switch on"
06/08/2016 10:00  "Dudley "
04/04/2016  "Exercise"
04/04/2016  "FD"
10/04/2018 06:00 "Winscribe - Prep"
11/04/2018 08:00 "HMRC - VAT"
10/04/2018 15:30 "Winscribe - Sales"
10/04/2018 11:00 "Winscribe - ChrisR"
11/04/2018 11:15 "KotG - Prep"
11/04/2018 11:45 "KotG - Travel"

Sync finished with success!

**Comment by phw198** [comment]
@araalij Did you have the Merge option checked during test 1 or 2?

**Comment by araalij** [comment]
Yep - checked for all 3 tests. 

I can see that you've explained what I discovered by myself within your guide [https://phw198.github.io/OutlookGoogleCalendarSync/guide/syncoptions] - perhaps it would be a good idea to insert that at the end of the installation instructions given how key it is to get an initial successful sync?

**Comment by Viennasurfer** [comment]
I have found the problem: I had 2 calenders selected in Google and my Google entries were synchronized with the wrong one. After selecting only 1 calender in Google everything works nicely.
Now there stays only one problem: the time in Google is 1hour later than in Outlook (issue 508).
Thanks for helping.

**Comment by phw198** [comment]
@Viennasurfer when you say you had "two calendars selected in Google", where was that? In the Google calendar web view or somewhere in OGCS?

**Comment by Viennasurfer** [comment]
I had it selected in the OGCS-Settings on my laptop. But speaking frankly: I do not understand, what is really happening and I got it running by a trial and error approach. I work mainly with alfred.gutmann@gmx.ch as my normal email account and the PST-file in Outlook is Personal Folders..../Kalender. To get a synchronised calendar on my mobile, I opened an account alfred.gutmann@outlook.com which shows my calendar-entries on my laptop  and my mobile. But to see the entries on my mobile, I have to use the calendar of the Outlook-App for Android. This calendar I like  less than the App "aCalendar+" from Google, which is usind the data from my google account. So I tried to use OGCS, which seems to work now with the settings
![image](https://user-images.githubusercontent.com/38191686/39247208-0c8e8e92-4899-11e8-8249-61dbde26efd8.png)
![image](https://user-images.githubusercontent.com/38191686/39247391-952fba96-4899-11e8-8131-97b904f74bbb.png)
![image](https://user-images.githubusercontent.com/38191686/39247656-4f7a3692-489a-11e8-8a38-9f57cace6293.png)
I hope you can understand, what is happening now.
BUT WHY IS THE TIME IN MY SYNCHRONIZED CALENDAR WRONG ( see my other issue)?

Thanks for your answer
Viennasurfer

**Comment by phw198** [comment]
@Viennasurfer Glad you got it sorted.

@araalij 
Test 1: Working as expected.
Test 2: The only way I can replicate what you have shown, is to have **previously** performed a 2-way sync and then manually delete everything in Outlook. Subsequent two way syncs will just want to delete everything in Google and not sync them back to Outlook - but then that's the entire point of a two-way sync. 
Test 3: To work around the "issue" in test 2, you would need to temporarily set one-way G->O as you have done. Then set it back to two-way....which is what you've now done.
