### ISSUE TITLE
All meeting times synced to Google offset by 1 hour (self created, non-recurring)

### ISSUE THREAD

**Issue by Viennasurfer** [phw198/OutlookGoogleCalendarSync#508]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1887894/OGcalsync.log)
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: 2.7.2.0 and Outlook installed on PC with Windows 10, Google installed on Portable with Android 
**Installed or Portable**: Installed

**Problem Description**  
We are using daylight saving time in Switzerland. The time entered in Outlook is shown 1hour later in Google. The time shown on the clock in both systems is correct.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by Viennasurfer** [comment]
It affects all my (not recurrent) meetings entered by myself before and after the change to DST.
 
Thanks for your help
Fred
 
Von: Paul [mailto:notifications@github.com] 
Gesendet: Sonntag, 8. April 2018 22:21
An: phw198/OutlookGoogleCalendarSync
Cc: Viennasurfer; Author
Betreff: Re: [phw198/OutlookGoogleCalendarSync] wrong time in Google (#508)
 
Can you confirm if this only affects recurring meetings organised by someone in another timezone?

**Comment by Viennasurfer** [comment]
Today I have installed your new version 2.7.3.0 but the time in Google is still 1 hour later than in Outlook

**Comment by phw198** [comment]
Have you performed a full sync by pressing `Shift` while clicking `Sync` to fix items already synced? Let me know if that makes any difference on the latest alpha v2.7.4

**Comment by ghost** [comment]
I had the similar issue using 2.7.0.0-beta

Upgrading to 2.7.5.0-alpha and performing `Shift-Sync` resolved the issue

Thanks Paul!

**Comment by ScottRochford** [comment]
Same issue here, also resolved using the 2.7.7.0-alpha and a Shift-Sync.
