### ISSUE TITLE
Failed to retrieve master for Google recurring event outside of sync range.

### ISSUE THREAD

**Issue by xstrm1** [phw198/OutlookGoogleCalendarSync#509]
**OGCS Version**:    2.7.2.0
**Installed or Portable**: NO

**Problem Description**  
2-way sync  Outlook/Google.   
It seems that there's some recurring event that's causing the sync to fail 

**Steps to Reproduce the Issue**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1906112/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1906114/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Sorry for the delayed response. It looks like the appointment causing the error is `19.05.2017 11:00 (R) => "Telematics coordination group"` - does this item have special protection on it? It seems you don't have permissions to access it fully...
