### ISSUE TITLE
"Other Calendar" from Google doesnt sync

### ISSUE THREAD

**Issue by Fonzi03** [phw198/OutlookGoogleCalendarSync#512]
**OGCS Version**: v2.7.3.0
**Installed or Portable**: Installed

**Problem Description**  
Personal calendar is syncing however a company calendar that is shared with me and listed in my "Other Calendars" section is not syncing.

**Comment by phw198** [comment]
Is the shared calendar available in the calendar dropdown on the OGCS Settings > Outlook page when you have `Default Mailbox` selected, or are you going to `Shared Calendar` and selecting the person who shared it?

**Comment by Fonzi03** [comment]
in the outlook page under select calendar the only calendar available is "Default Calendar" no other options appear. If I go to shared calendars there are no options either.

**Comment by phw198** [comment]
Shared calendar should open the global address book, from which you would pick the account of the person who has shared with you their calendar...?

**Comment by Fonzi03** [comment]
I do not have a global address book showing up, actually my address book in general never came across. 

![untitled](https://user-images.githubusercontent.com/38508905/39155267-28b04c62-4706-11e8-90f4-ff8e0ceb0641.png)

**Comment by Fonzi03** [comment]
I see the calendar under the google tab but cant get it to show up in outlook

![untitled2](https://user-images.githubusercontent.com/38508905/39156404-d1c73cc6-470a-11e8-9270-b57fc749b131.png)

**Comment by Fonzi03** [comment]
bump*

**Comment by Fonzi03** [comment]
My account is an IMPA/SMTP, the calendar has been shared by a moderating user. My address book never ported either.

**Comment by phw198** [comment]
Outlook doesn't support syncing of calendar folders for IMAP accounts. If an calendar folder is created in Outlook within that account, it is only a local folder within the `.ost` file and not synced to the remote account. I think this would be why you are seeing "Default Calendar (this computer only)" under "Shared Calendar". 

As mentioned before, the shared calendar sync function in OGCS is designed to be used for a calendar hosted on an Exchange account.

🔗 [How do I add a Full Function Calendar to IMAP Account](https://social.technet.microsoft.com/Forums/en-US/596a643e-d30c-40b6-ae79-6a2cae2d2f86/outlook-2016-how-do-i-add-a-fullfunction-calendar-to-imap-account?forum=outlook)
