### ISSUE TITLE
sync range error outlook 2010 and google calendar

### ISSUE THREAD

**Issue by copperwasher** [phw198/OutlookGoogleCalendarSync#513]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

Sync options
'When'
Date range 
1 days in the past
30 days in the future

!!! the sync program is uploading years worth of data to the Google calendar - so syncing is taking a huge amount of time just to update my appointments

Any advice or suggestions ???

**Comment by phw198** [comment]
Either it is simply syncing recurring series that span the date range you are syncing (which is intended behaviour), or Outlook isn't handling your dates as expected - take a look [here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) for further guidance (normally this means Outlook doesn't find _any_ items, but maybe in your case it's finding too many).
