### ISSUE TITLE
Installation Unsuccessful

### ISSUE THREAD

**Issue by blake-enyart** [phw198/OutlookGoogleCalendarSync#514]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
The setup.exe file won't install the program. I have tried to import from both the alpha and beta versions with the setup.exe or the portable_OGCS with no luck.  It keeps bringing me back to the GitHub release notes and nothing else happens.  I have referenced all the the user guides.  I am running Windows 10.

**Steps to Reproduce the Issue**  
1. Download the setup file
2. Attempt to install it.

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

**Comment by blake-enyart** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1935098/OGcalsync.log)

**Comment by phw198** [comment]
The error is `Cannot complete the operation. You are not connected.`

How are you invoking OGCS? Is it in interactive mode for a user that had an Outlook profile configured? Googling seems to show the same error when starting a program as a service e.g. through task scheduler.

**Comment by blake-enyart** [comment]
I might not answering this correctly, but I am simply downloading the .exe
file and using that to try and initiate the installation.  It never
actually opens the program.  Once I open the setup.exe file for the 2.7.0
beta version of the software it sends me to the release notes web page
rather than opening the file.  Is there some other method for opening the
setup.exe file which I am not performing?

Blake


Cheers,

Blake Enyart
Email: blake.enyart@gmail.com
Mobile: (562) 794-0808
Linkedin Profile <https://www.linkedin.com/in/blakeenyart/>

**Comment by phw198** [comment]
No that's fine, you're starting it exactly as I would expect. It looks like when you start OGCS, Outlook was running, but perhaps only with the meeting reminders window and not the full application?

Could you try:
* Closing Outlook completely (check in your Task Manager that no `outlook.exe` process remains) and then starting OGCS; and if that still fails
* Starting Outlook up and wait for a few minutes to make sure it is fully initialiased, and then start OGCS.

Would then be helpful if you could upload your logfile again. If one of those solutions works, I might then be able to code in a fix.

Thanks!

**Comment by blake-enyart** [comment]
Hi Paul

Apologies on the late reply to your message.  I tried both of those options
and it still didn't seem to work.  Is there another work-around which you
can think of that would make this work?

Blake


Cheers,

Blake Enyart
Email: blake.enyart@gmail.com
Mobile: (562) 794-0808
Linkedin Profile <https://www.linkedin.com/in/blakeenyart/>

**Comment by phw198** [comment]
Two other things to check:
* Are you running Outlook and OGCS on a remote machine (eg via Remote Desktop/RDP) or locally. If you're not sure then it'll be locally :slightly_smiling_face: 
* Are you running both Outlook and OGCS at the same elevation level - ie. you're not running one of them "As Administrator"?

Otherwise, all I can think of it to run an [Office Repair](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#office-repair)...

**Comment by blake-enyart** [comment]
They are both being run locally.  I don't believe I am running either of
them "As Administrator" unless that is something that defaulted on my
account.  Looks like I will have to give this Office Repair a look haha.



Cheers,

Blake Enyart
Email: blake.enyart@gmail.com
Mobile: (562) 794-0808
Linkedin Profile <https://www.linkedin.com/in/blakeenyart/>

**Comment by blake-enyart** [comment]
Hey Paul!

I just wanted to let you know I was able to get it to install and is
working now.  I reinstalled Microsoft outlook and everything is good to
go.  Thank you for the help!

Blake


Cheers,

Blake Enyart
Email: blake.enyart@gmail.com
Mobile: (562) 794-0808
Linkedin Profile <https://www.linkedin.com/in/blakeenyart/>

**Comment by phw198** [comment]
Thanks for confirming, @benyart1989 

I'll look to add that in to OGCS as a suggested fix for the error you got. It depressing how many Office installs get corrupted or aren't registered in Windows properly...
