### ISSUE TITLE
Cannot move window, mouse pointer changes to resizing action over title bar.

### ISSUE THREAD

**Issue by selthofer** [phw198/OutlookGoogleCalendarSync#521]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.3 
**Installed or Portable**: Installed

**Problem Description**  
Cannot click on the title bar to move application window. Mouse pointer changes to resizing when hovered over the title bar. Tested in both Beta and Alpha.

**Steps to Reproduce the Issue**  
1. 
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
I can't reproduce this. Is it still happening after a reboot? What version of Windows are you running?

**Comment by selthofer** [comment]
correct, cannot reproduce it anymore after reboot. installed on win 7 pro.
sorry about false flag, didn't reboot as i believe was not asked to by the
installer but still i should have checked that before reporting...

**Comment by phw198** [comment]
I've not heard of a reboot being needed before, but at least that fixed it. Thanks for letting me know 👍
