### ISSUE TITLE
some calendar events not syncing

### ISSUE THREAD

**Issue by ajumpcalg** [phw198/OutlookGoogleCalendarSync#523]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Syncing from Outlook to Google Calendar. The sync is stated as a success but events for the month of May are not showing up on the Google calendar (all events after May are showing up). Also, there are 143 items on Outlook but it is only syncing 142. 

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).
