### ISSUE TITLE
Sync Issue - Exception from HRESULT: 0x80004004 (E_ABORT

### ISSUE THREAD

**Issue by mikelegg8** [phw198/OutlookGoogleCalendarSync#524]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.3.0
**Installed or Portable**: Installed

**Problem Description**  
calendar will not sync. I receive the following error.
```
Sync version: 2.7.3.0

Sync started at 5/11/2018 10:18:07 AM

Syncing from 5/10/2018 to 5/14/2018

Outlook → Google
Authenticating with Google...
Preparing to authenticate with Google.

Finding Calendar Entries
Scanning Outlook calendar...

44 Outlook calendar entries found.

Scanning Google calendar...

6 Google calendar entries found.

Total inc. recurring items spanning sync date range...

Failed to retrieve master for Google recurring event outside of sync range.

Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))

Operation aborted after 1 failed attempts!
```

**Steps to Reproduce the Issue**  
1. Click Sync

**Any other information**  
Is this an issue with corporate policies?

**Comment by mikelegg8** [comment]
Thanks Paul,
    The issue only happens when the <No category assigned> is checked.

**Comment by phw198** [comment]
:spiral_notepad: OK, that's a new one. Please could you provide me your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)) so I can look to work around this issue?

Note, you can't attach files to GitHub when replying by email - you need to log in.

**Comment by phw198** [comment]
Hi @mikelegg8 are you still having this issue? Will you be able to provide your logfile?
