### ISSUE TITLE
Outlook to Google only, Event Reminders default to 10 minutes no matter what is set in Outlook

### ISSUE THREAD

**Issue by evansthewelsh** [phw198/OutlookGoogleCalendarSync#526]
:memo: Use the below template to report your issue.
I am a contributing user using Outlook365 on a Windows 7 computer.  I am synching one way Outlook to Google only.    Everything workd great apart from the event reminders.  These are set at various times in Outlook, but these times never make it to Google, where all events appear with both 10 minute email and 10 minute reminders set up.

:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
I am using the latest version 2.7.0.0

:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions]Done as attached below.
.  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2006506/OGcalsync.log)

----

**OGCS Version**: v1.2.3.4  
Full installed version 2.7.0.0

**Problem Description**  
I am a contributing user using Outlook365 on a Windows 7 computer.  I am synching one way Outlook to Google only.    Everything workd great apart from the event reminders.  These are set at various times in Outlook, but these times never make it to Google, where all events appear with both 10 minute email and 10 minute reminders set up.

**Steps to Reproduce the Issue**  
1. This issue has been going on for several weeks.  Not sure exactly when it started.
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Given you've not set OGCS to sync reminders, I would strongly suspect what you are seeing are the defaults you've configured within the Google calendar...?

**Comment by evansthewelsh** [comment]
Paul,

You are absolutely correct! I cannot believe I did not spot that option
check box. I just checked that and all is now working as it should. Thanks
for the quick response, and sorry to trouble you with such a beginner's
error.

Thanks!

Martin.

**Comment by phw198** [comment]
No problem 😊
