### ISSUE TITLE
Upgrades fail from v2.7.1 through v2.7.3

### ISSUE THREAD

**Issue by HeavyG603** [phw198/OutlookGoogleCalendarSync#527]
:memo: If you are currently running `v2.7.1`, `v2.7.2`, `v2.7.3`, or have attempted to upgrade from these releases, the simplest solution is to [manually download and run the latest `Setup.exe` file directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

----

**OGCS Version**: v2.7.3 
**Installed or Portable**: Installed

**Problem Description**  
Latest Alpha fails to install.  It did manage to delete the existing install first so I needed to reinstall the beta.  Not sure what logs would be available but happy to post.  When it brought it up immediately after fail it said it couldn't access the directory, which at that point was gone.

**Steps to Reproduce the Issue**  
1. Install the Alpha release

**Any other information**  
\<Update here>

**Comment by HeavyG603** [comment]
I'm afraid these are still failing, this time with a Crash error on start of an Upgrade to the latest alpha.

**Comment by phw198** [comment]
Got a crash error message or log file covering the crash?

**Comment by phw198** [comment]
Covered by issue #497
