### ISSUE TITLE
Not able to sync with Google

### ISSUE THREAD

**Issue by Stuwilli1** [phw198/OutlookGoogleCalendarSync#530]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.4  
**Installed or Portable**: Installed

**Problem Description**  
Worked for awhile then I started to add the Google calendar to Outlook Live and also tried through Oulook (2016).  Stopped syncing and just stays in the "authenticating with Google, preparing
 to authenticate with Google", screen and just sits

**Steps to Reproduce the Issue**  
1. anytime sync
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2028612/OGcalsync.log)

**Comment by Stuwilli1** [comment]
I have to disconnect GMAIL account and reconnect for it to work.  Not consistent at all.  States handshake fails.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2032411/OGcalsync.log)

**Comment by Stuwilli1** [comment]
I have to disconnect Google account in other words to sync and then attain a verification code.  Otherwise, it states the "Google handshake failed"

**Comment by Stuwilli1** [comment]
Thanks, really frustrated, has to be a setting I'm missing, IDK?

Stuart

**Comment by phw198** [comment]
Yes, very odd. Seems that after you've authorised OGCS to manage your calendar it works, but then after restarting OGCS it complains that your credentials are no longer valid! I assume you've not changed your Google password in that time?

Are you using two factor authentication (though I use this without problem) or app passwords with Google or anything? I'm a bit stumped tbh...

**Comment by Stuwilli1** [comment]
No clue

**Comment by phw198** [comment]
Log file extract:
`2018-05-23 10:46:36,742 DEBUG  7 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Access token expires 5/23/2018 10:30:28 AM`
So to me that looks like the token is already expired, but OGCS is carrying on as though it's valid. So I think there is a [bug in this line of code](https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/src/OutlookGoogleCalendarSync/GoogleOgcs/Authenticator.cs#L140) around UTC values....though I'm surprised lots of people don't suffer this. 

:bulb: Ah, I know why - you're restarting OGCS which means it has to reauthenticate. If you leave OGCS open then it will be OK, and if you leave it on overnight, the GMT offset it big enough for it to know the token has _actually_ expired.

I'll get a fix out as soon as possible...

**Comment by Stuwilli1** [comment]
Thanks!

Stuart

**Comment by kwagner115** [comment]
I too have the same problem, and need to disconnect google account, then reconnect. Happens 1-2 a week. I have not been able to pin point what sequence of events breaks the authorization. I update OGCS software regularly, using most recent alpha releases. Problem has occurred under at least the last 3 releases.

**Comment by Stuwilli1** [comment]
All good, I can just disconnect and reconnect when necessary.

Thanks!

Stuart

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.7.4.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2036904/v2.7.4.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

To test, disconnect google, reconnect, shutdown OGCS, start OGCS and sync - should not need reconnecting.

**Comment by Stuwilli1** [comment]
Done, see how it goes and thanks!

**Comment by kwagner115** [comment]
Installed as well. Will see what happens over the next week or so, and post results.

**Comment by Stuwilli1** [comment]
thanks

**Comment by kwagner115** [comment]
Applied fix. Have not had a failure since. Thanks!!

**Comment by Stuwilli1** [comment]
Yep seems to be working!!

Stuart
C: (904) 615-7004


On May 27, 2018, at 1:06 PM, kwagner115 <notifications@github.com> wrote:

Applied fix. Have not had a failure since. Thanks!!

**Comment by Stuwilli1** [comment]
Thanks Paul, seems to be working just great  since that fix! 

Stuart
C: (904) 615-7004


On Jul 15, 2018, at 5:43 PM, Paul Woolcock <notifications@github.com> wrote:

Closed #530 via 5a104b1.

**Comment by Stuwilli1** [comment]
Hello!

Been awhile and ever since the new 2.7.6.0 version the sync "hangs" at this
point below.  Sometimes it has gone all the way through other times it just
sits here for a very long time until I abort.


[image: image.png]
Best regards,

Stuart A. Williams, CFE
(904) 615-7004

**Comment by Stuwilli1** [comment]
Typically have to abort and see below

[image: image.png]
Best regards,

Stuart A. Williams, CFE
(904) 615-7004

**Comment by Stuwilli1** [comment]
Started at 11:55am and finally went and finished at 12:37.  Just weird.  It
re-ran again after completed since it is set to go every 20 minutes and it
is sitting in the same spot waiting once again.

Best regards,

Stuart A. Williams, CFE
(904) 615-7004

**Comment by kwagner115** [comment]
I may have similar results./ performance issue. I have only 70 calendar entries that sync between Outlook and Google (2 way). 
 
Under most current alpha (2.7.6.0) the app seems to take an unexpected long time to process through its normal update / check routines. 
 
 
Kevin
 
 <mailto:kwagner115@gmail.com> kwagner115@gmail.com
319-382-4461 (mobile)

**Comment by Stuwilli1** [comment]
It is still processing (35 minutes in), even though no to minimal changes
form the previous.

Stuart

**Comment by Stuwilli1** [comment]
It is taking about 30 minutes for it to sync on the new software version,
by the time it is done and starts again!

Stuart
