### ISSUE TITLE
"End date you entered occurs before the start date"

### ISSUE THREAD

**Issue by adamgpage** [phw198/OutlookGoogleCalendarSync#531]
Please see image below. It refers to Open Mic at White Hotrse, but that event doesn't exist i either Outlook or Google calendar.

I'm using version 

2.7.3.0
--

I'm new to all this: my email address is adamgpage@gmail.com
Thank you for your help.

----
![screenshot 2018-05-23 11 51 31](https://user-images.githubusercontent.com/39555639/40420695-09628702-5e81-11e8-8d4f-ffd1834982af.png)

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

The item should exist in Google for OGCS to be trying to create it in Outlook. Do you know what application might have created it in Google? The web interface wouldn't allow a start date after the end date...

**Comment by adamgpage** [comment]
The instructions tell me to "paste in your OGcalsync.log" but doesn't tell
me where to find my OGcalsync.log. CAn you help please?


Adam G. Page
63, Houblon Road, Richmond, TW10 6DB
Mob: +44 (0)7788 457 890

**Comment by phw198** [comment]
Try scrolling up.
I'll amend the link for future.

**Comment by phw198** [comment]
:package: If you are on an earlier version to v2.7.5.3, please try this [development build](https://github.com/phw198/OutlookGoogleCalendarSync/files/2259460/v2.7.5.3.zip) with extra logging ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Once the error occurs, please upload your `OGcalsync.log` file. Thanks!

**Comment by phw198** [comment]
FWIW, I have no idea how such a recurrence can be created in Google, as when manually setting an end date before the start in the web UI, Google automatically changes the occurrence to "once". On second thoughts, would be better to make Outlook do this too...

**Comment by phw198** [comment]
:package: This should now be worked around with [v2.7.6.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2462618/v2.7.6.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) by changing the recurring series to a single occurrence when synced to Outlook.

**Comment by adamgpage** [comment]
The point is there isn’t an event called “White Hotrse”. It doesn’t exist. Not in Google nor in outlook.

Adam Page | Sent from my iPhone

**Comment by phw198** [comment]
@adamgpage Any update on that search result?

Given I can't replicate this issue, next steps are:
- [ ] ~~Affected users to confirm if the item really isn't visible in the Google calendar web UI~~
- [ ] ~~Me to determine best course of action; try and delete the Google event?~~
- [ ] ~~Code in solution for affected users to test~~
