### ISSUE TITLE
Finding data but not syncing between Google to Outlook and Outlook to Google calanders

### ISSUE THREAD

**Issue by desfermah** [phw198/OutlookGoogleCalendarSync#532]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2038216/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2038221/OGcalsync.log)

:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Not really sure what changes you're expecting to see.

OGCS is wanting to make some deletions - is that what you are expecting it to do? Because you have deletions disabled...
