### ISSUE TITLE
Can't retrieve g-calender

### ISSUE THREAD

**Issue by thehurz** [phw198/OutlookGoogleCalendarSync#533]
**OGCS Version**: v2.7.4.0
**Installed or Portable**: Installed

**Problem Description**  
Can't retrieve my google-calenders.
Procedure: Clean installed OGCS->start OGCS->Settings->Google->Retrieve Calenders -> Google: 500. That's an error (https://imgur.com/a/VaXrEwc)

**Any other information**  
OGcalsync.log: https://gist.github.com/thehurz/9b8670b9c4ade6d1baa4c6836ed328e5

**Comment by phw198** [comment]
A 500 error signified a server error, which it coming from Google - that's not under my control. Hopefully Google will fix it soon and it will start working again...!

**Comment by thehurz** [comment]
just tried again today - works fine now -tyvm!
