### ISSUE TITLE
Entrie from Outlook shows incorrect time in Google

### ISSUE THREAD

**Issue by giadira** [phw198/OutlookGoogleCalendarSync#536]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
During overseas travel my computer's time zone was automatically set to CET. Upon return, although my computer's time zone has been set back to EST, and after several restarts, the entries being created in Outlook appear in Google as if Google was still in CET. I have checked the settings in Google to make sure it is in EST and installed the latest alpha version and this does not correct the problem.
**Steps to Reproduce the Issue**  
1. Change system time zone
2. Sync
3. Change back system time zone
4. Create new events in Outlook
5. Sync
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2082129/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Have you performed a full sync with the latest alpha? Press `Shift` while clicking `Sync` button.

**Comment by giadira** [comment]
Paul,

This has solved the problem. Thank you very much.

Giadira
