### ISSUE TITLE
Outlook calendar events from non-primary email accounts not syncing to Google calendar

### ISSUE THREAD

**Issue by NaveenGarg** [phw198/OutlookGoogleCalendarSync#539]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.4.0
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2094793/OGcalsync.log)
.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
I have multiple email accounts setup in my Outlook and have quite a few meeting (recurring and non-recurring) appointments created using non-default accounts - such that these events are created in their own calendars (Outlook supports multiple calendars - one for each email account). I have noticed that many of my appointments from other email accounts in Outlook are not getting sync'd to Google Calendar. I have tried changing various sync options (Outlook -> Google, Outlook <-> Google) but to no avail.

**Steps to Reproduce the Issue**  
1. Create an Outlook profile that has two email accounts one at Outlook.com and another at Google.com with Outlook.com as the default calendar
2. Create an appointment from each of these email accounts in Outlook such that each appointment shows only its own calendar in Outlook
3. Attempt to sync these two appointments from Outlook to Google Calendar using Sync. Only one with default calendar succeeds whereas both should be sync'd (or at least there should be a setting to provide this as an option.)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2094816/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by NaveenGarg** [comment]
I found a workaround by going into Outlook settings in the Sync to individually select the calendar for the other email account and do a manual sync. It indeed did the trick and I can now see all these events also on my desired Google calendar.

It will be great to provide this as a default feature (allow me to select multiple Outlook Calendars and sync them all to Google), whereas Google to Outlook sync happens to default calendar (or another one of choice). - Thank you!

**Comment by phw198** [comment]
Hi @NaveenGarg, syncing of multiple calendars is an enhancement captured in issue #165, with instructions on a workaround for configuring automated syncs meanwhile. Hope that helps.
