### ISSUE TITLE
Updated to 2.7.4 - won't sync

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#540]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.4  
**Installed or Portable**: Installed

**Problem Description**  
\get notice that syncing has started but nothing else happens.

**Steps to Reproduce the Issue**  
1. \Just loops continuosly - keeps trying to sync.  Update to new version - no difference
1. 

**Any other information**  
\running windows 10
[OGcalsync 061218 939.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2096359/OGcalsync.061218.939.txt)

**Comment by phw198** [comment]
Google is returning `Invalid Credentials` - have you changed your password recently?
Try disconnecting your Google account in the OGCS Google settings page and then re-retrieving the calendars to reauthorize with Google?
