### ISSUE TITLE
OGCS not permitted to start Outlook [0x80070005] E_ACCESSDENIED

### ISSUE THREAD

**Issue by velopirate** [phw198/OutlookGoogleCalendarSync#542]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.4.0 - Alpha
**Installed or Portable**: Installed

**Problem Description**  
Application unexpectedly terminated!  Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 80070005 Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)).

**Steps to Reproduce the Issue**  
1.  Run OGCS.  I get this every time the program is started.  Antivirus has been removed.

**Any other information**  
Windows 10 Enterprise / Outlook 2016

**Comment by phw198** [comment]
Has it ever worked? Are you running it in a corporate environment? Normally this relates to your IT restricting programmatic access to Outlook.

:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by velopirate** [comment]
Hi Paul!  It has worked in the past on my Windows 10 Enterprise laptop
using Outlook 2016.  I wanted to move this to my primary workstation since
my laptop isn't always running.  I work in IT and we shouldn't be blocking
this.

Mike

**Comment by velopirate** [comment]
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2124267/OGcalsync.txt)

**Comment by phw198** [comment]
Looks like it's not able to start Outlook - does it make any difference if you already have Outlook open before opening OGCS?

**Comment by velopirate** [comment]
Nice find, Paul, It will work if Outlook is open.

**Comment by phw198** [comment]
Great! Might also be with having a look through some of the top hits on [this Google search](https://www.google.com/search?q=outlook+start+interop+0x80070005+%28E_ACCESSDENIED%29&client=firefox-b&oq=outlook+start+interop+0x80070005+%28E_ACCESSDENIED%29&gs_l=mobile-heirloom-serp.12...12643.27850.0.36193.16.15.1.0.0.1.263.1955.4j10j1.15.0....0...1c.1.34.mobile-heirloom-serp..9.7.1006.CxUDmWxiuwM) - I think you might need to tweak your DCOM config.

**Comment by velopirate** [comment]
Thanks.
