### ISSUE TITLE
Deltetions

### ISSUE THREAD

**Issue by Riptide68** [phw198/OutlookGoogleCalendarSync#545]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Activities Deleting for no apparent reason.  I have synch from Outlook to google and back.  I lost a lot of activities so I turned of the delete button.  As soon as I add an activity to my outlook calendar it wants to delete it.  Please advise.>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Are you running the latest alpha release of OGCS?

What calendar are you syncing from Outlook (eg Exchange)? iCloud calendars are known to have caused problems, but there is a fix out for those...

Also, you only have OGCS installed on one PC syncing one calendar?

**Comment by Riptide68** [comment]
Exchange (work) with google 2 way sync.  

No Icloud, I use android.

I  have the latest installed and it is only on one PC.  If I added a new event it just wanted to delete it.  Very weird, i have it set to never delete events now and I just manually do it when needed but would be nice if it worked  :)

**Comment by phw198** [comment]
:spiral_notepad: Could you upload your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) so I can take a closer look?

**Comment by Riptide68** [comment]
Might be a while.  Hitting the road for the next two weeks tomorrow but then I will!  Thanks
