### ISSUE TITLE
Corrupted  Google token file

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#546]
**OGCS Version**: v2.7.4
**Installed or Portable**: Portable deployed on network share

**Problem Description**  
Cannot authenticate properly with Google - the authentication window displays "Received verification code. You may now close this window", but nothing happens.

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2141680/OGcalsync.log)

**Comment by phw198** [comment]
@Smog418 It looks like you have deployed this to a network share? Not sure if that may be causing a problem, but
* in the OGCS folder, is there a file `Google.Apis.Auth.OAuth2.Responses.TokenResponse-user`?
* what is in the file? is it empty? does it make any difference deleting it?
* try deploying the OGCS zip file to a local directory and running from there

**Comment by Smog418** [comment]
Thanks for your help.
____________________________________________________________________________________________________________

> @Smog418 It looks like you have deployed this to a network share? Not sure if that may be causing a problem, but 

Yes, i deployed in network share. But i try somewhere else.

![2018-06-27_13-21-13](https://user-images.githubusercontent.com/23439186/41989538-a0175892-7a0d-11e8-9623-45c89c4e0eeb.jpg)

> in the OGCS folder, is there a file Google.Apis.Auth.OAuth2.Responses.TokenResponse-user?

No, you can see image above.

> what is in the file? is it empty? does it make any difference deleting it?

i don't have this file.

> try deploying the OGCS zip file to a local directory and running from there

I try on local directory, and i have the same result (see image above and now log).
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2142255/OGcalsync.log)

**Comment by phw198** [comment]
Looks like the file has gone to `C:\Document\OGCS\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user` - can you confirm if it's empty?

**Comment by Smog418** [comment]
I don't see this file. This is my screenshot of C:\Document\OGCS\
![2018-06-27_17-44-06](https://user-images.githubusercontent.com/23439186/42001513-2d3de5e6-7a32-11e8-9495-b7bf78c4e160.jpg)

I see **Google.Apis.Auth.dll** but not **Google.Apis.Auth.OAuth2.Responses.TokenResponse-user -**.

If it's **Google.Apis.Auth.dll** that you talk about, it's clearly not empty:
![2018-06-27_17-51-54](https://user-images.githubusercontent.com/23439186/42001730-ea28c298-7a32-11e8-9833-fa7daf281ced.jpg)

It's my work PC, so i don't have admin rights. This is why i use portable version.

**Comment by phw198** [comment]
Can you explain a bit about your proxy setup? Looks like you're inheriting from IE which is using http://proxy-sf.internet.rq:3128 - does this require authentication and are the credentials different from your Windows credentials?

Have you tried specifying the proxy details within OGCS?

**Comment by Smog418** [comment]
Unfortunately, I'm not a guy from IT departement at my job... I can't answer... 🙁
