### ISSUE TITLE
Hangouts URL and phone number added to events

### ISSUE THREAD

**Issue by jstride** [phw198/OutlookGoogleCalendarSync#547]
**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
A hangouts is added to new events synced to GSuite calendars

**Steps to Reproduce the Issue**  
1. Sync to a GSuite account

**Comment by phw198** [comment]
Not having a GSuite calendar to test with I can verify this. However, there is no code in OGCS related to Hangouts (though I can see it available in the API) - are you sure this isn't a setting you've configured within GSuite? 

Have you a screenshot or something of what it looks like?

**Comment by phw198** [comment]
I'd wager that this setting in your Google calendar settings is checked:
![image](https://user-images.githubusercontent.com/11843015/48207781-4dbb6c80-e369-11e8-9080-cc0fa7dabf60.png)
