### ISSUE TITLE
Could not determine organiser's GMT offset timezone

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#551]
This is a regression bug from v2.7.4.7 and [issue 67](https://github.com/phw198/OutlookGoogleCalendarSync/issues/67#issuecomment-399675930). 
Will uplift the fix into a new hotfix ASAP...

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.7.5.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2207599/v2.7.5.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

If anyone tries it, let me know how it goes.

**Comment by J-CMartin** [comment]
2.7.5 had been crashing due to GMT offset error, Hotfix seems to have fixed the issue and the Sync process is finishing successfully. Thanks
