### ISSUE TITLE
Click Outlook icon = "Sorry, we’re having trouble starting Outlook...."

### ISSUE THREAD

**Issue by RPross** [phw198/OutlookGoogleCalendarSync#553]
**OGCS Version**: V 2.7.0.0 
**Installed or Portable**: Installed

**Problem Description**  
Something new as of late last week: when starting the computer, OGCS starts as usual, and then, if I want to use Outlook (Windows 7 / Office 365), I get this message: "Sorry, we’re having trouble starting Outlook. Only one version of Outlook can run at a time. Check to see if another version of Outlooks is running, or try restarting your computer. "

When I click on Window's Notification Area's "hidden icons," both Outlook and OGCS icons are there, so I right-click the Outlook icon and chose the "Open Outlook" option. 

Outlook then works fine, but this new extra step is a hassle. 

**Steps to Reproduce the Issue**  
1. \restart the PC, let all load, then click to run Outlook. Same steps as above. 

**Any other information**  
\Windows 7 and OGCS are up to date (I think), though when I click the Check for Updates (including Alpha releases), I get a message stating: "Unable to check for new version."

OGcalsync.log attached 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2207825/OGcalsync.log)

Thanks from San Diego

**Comment by phw198** [comment]
Hi @RPross - I believe this will be fixed in v2.7.5 from [issue 535](https://github.com/phw198/OutlookGoogleCalendarSync/issues/535#issuecomment-405091067).

Download and install the [latest version here](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.7.5-alpha/Setup.exe).

Note, you could always add a delay to the startup of OGCS, to give Outlook a chance to start first too.

**Comment by RPross** [comment]
Hi. Well, I installed v2.7.5 and also set OGCS to start 60-seconds after restart. Unfortunately, now I get this message: 

OutlookGoogleCalendaSync has stopped working. 
> Check online for a solution ... 
> Close the program
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	OutlookGoogleCalendarSync.exe
  Problem Signature 02:	2.7.5.0
  Problem Signature 03:	5b4bb7b8
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.3130.0
  Problem Signature 06:	5b175e25
  Problem Signature 07:	1679
  Problem Signature 08:	ca
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Note: I tried a second restart but get the same message. Guess I will go back to the latest published version and see what happens.

**Comment by RPross** [comment]
PS: after letting the existing problem sit a few minutes, I restart OGCS and did NOT get the warning. I did nothing but wait a while. I will set it to start 120 seconds after restart and see if that helps.

**Comment by RPross** [comment]
PS: after letting the existing problem sit a few minutes, I restart OGCS and did NOT get the warning. I did nothing but wait a while. I will set it to start 120 seconds after restart and see if that helps. 

Nope. Got another error ... oddly though long before the 120 seconds were up. Here is the message:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	OutlookGoogleCalendarSync.exe
  Problem Signature 02:	2.7.5.0
  Problem Signature 03:	5b4bb7b8
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.3130.0
  Problem Signature 06:	5b175e25
  Problem Signature 07:	1679
  Problem Signature 08:	ca
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by RPross** [comment]
Decided to go back to v2.7.0 and set OGCS to 60 seconds. On restart all seems good.

**Comment by RPross** [comment]
Decided to go back to v2.7.0 and set OGCS to 60 seconds. On restart all seems good, i.e., no error on startup. However, 5 minutes later when I wanted to start Outlook, I got the original message again, saying Outlook is already running. 

I am back to the original reason I posted. Oh well, I hope the next version works as you stated. Thanks.

**Comment by phw198** [comment]
:spiral_notepad: Please can you provide your `OGcalsync.log` file for the points when it crashed ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

Got plenty of others already on v2.7.5 so I don't think there's a problem with the installer...

**Comment by RPross** [comment]
Sure I can. Here it is after a restart. Outlook (or its calendar) seems to start in the background so when I click the Outlook icon in the taskbar I get the "already running" message, and then the program comes up on screen. It's just an annoyance but I don't recall this happening a week or so ago. Thanks. 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2211759/OGcalsync.log)

**Comment by phw198** [comment]
Hmm, that logfile seems to be when you're back on v2.7.0 and it's not crashing. If you're game, install v2.7.5 again and then provide the logfile if it still crashes...

**Comment by RPross** [comment]
Sorry for the delay in response. The problem persists using v2.7.0, but I realized what triggers the message: 

If I close Outlook 2016 without first dismissing any calendar reminder pop-up windows, OGCS seems to keep Outlook active in some manner, e.g., if I open Outlook again, I get the "Sorry, we’re having trouble starting Outlook...." message. I must click "OK" and then Outlook starts. However, if I first dismiss the reminder window, and then close Outlook, the program restarts and does not generate that message. 

Is this how OGCS was designed to run? 

Here are some logfiles from the last few days. Thanks. 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2254676/OGcalsync.log)

**Comment by RPross** [comment]
Sorry for the delay in response. The problem persists using v2.7.0.

Here are some things I have noticed. Two scenarios:

1.] The computer has been on for a few days. Outlook 2016 and OGCS v2.7.0 have been used many times. Now, if I close Outlook 2016 without first dismissing any calendar reminder pop-up windows, OGCS seems to keep Outlook active in some manner. I say this because if I open Outlook again, I get the "Sorry, we’re having trouble starting Outlook..." message. I must click "OK" and then Outlook starts as normal. However, if I first dismiss the reminder window, and then close Outlook, it will restart and does not generate that message.

2.] I restart the computer and walk away. Note: OGCS is set to start 60 seconds after logging in to Windows 7. I return after a few minutes. I notice the OGCS icon is visible in the far right of the taskbar. I launch Outlook and get the "Sorry, we’re having trouble starting Outlook..." message. 

Next, I close Outlook (there were no calendar reminder windows). Note: now the OGCS icon is NOT visible at the right of the taskbar. I relauch Outlook. It starts normally. 

Why this inconsistency? It's as though sometimes OGCS keeps Outlook's calendar portion of the program running in the background. 

Below is the most recent logfile. FYI, there is also a file of the same day called "Google.Apis.Auth.OAuth2.Responses.TokenResponse-user" but I cannot add it to this post.

Thanks.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2255033/OGcalsync.log)

**Comment by phw198** [comment]
Yes, I wouldn't expect the issue to somehow fix itself on v2.7.0 - it's fixed in 2.7.5 but when you upgraded you then hit another issue. I think the new error you got is issue #559, which I'm be investigating soon...

**Comment by RPross** [comment]
Okay, and just an FYI, but when I check for new updates I get this message. Not sure if that means there is no update, or that the attempt is blocked for some reason. 
![can t update](https://user-images.githubusercontent.com/41404549/43658354-82c8baf2-970d-11e8-8df3-ae66a4489a6c.jpg)

**Comment by phw198** [comment]
Yup, and unfortunately that's issue #497
