### ISSUE TITLE
"Confirm Mass Deletion" warning appears when "Confirm Deletions" is not checked

### ISSUE THREAD

**Issue by vorgrist** [phw198/OutlookGoogleCalendarSync#554]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.5
**Installed or Portable**: Portable

**Problem Description**  
When syncing deletions for **one or more** items deleted from an Outlook (Exchange Resource) Calendar, a warning message appears and requires user interaction. Since I am trying to use this in such a way that I do not have to interact with OGCS after it is set up, being forced to interact with OGCS in order to process deletions is counterproductive.  The message follows:

![capture](https://user-images.githubusercontent.com/16689359/42966507-978794ea-8b5a-11e8-9edd-d9d247d7e7e2.PNG)

_Note: If newly created events are supposed to be synced, then the numeral will reflect the correct number of events to be created._

**Question:** Is there a way to fully suppress all deletion messages?

**Pertinent settings:**
![capture2](https://user-images.githubusercontent.com/16689359/42966566-d8a3b9ea-8b5a-11e8-9b6d-e8cf651140c1.PNG)

**Steps to Reproduce the Issue**  
1. Set up OGCS as described above.
2. Create events in the Outlook (Exchange Resource Calendar) calendar.
3. Wait for, or force, sync.
4. Delete one or more events from the Outlook (Exchange Resource Calendar) calendar.
5. Wait for sync.
6. View message, allow, watch log.

**Any other information**  
Same issue experienced with the current Beta Portable version.

**Comment by vorgrist** [comment]
GIST for OGcalsync.log

https://gist.github.com/vorgrist/cf20e1a67a49d56fdf561312624dcab7

**Comment by vorgrist** [comment]
This is an important issue for my use case, where I am looking for a "Silent" or "Quiet" mode.

**Comment by phw198** [comment]
If the number of items that want to be deleted is the same as the number of items that exist in the calendar, then yes, the **mass** deletion prompt will be given. This is to protect against users that may have misconfigured OGCS and are about to wipe their calendar - the prompt is by design, won't be removed and isn't affected by `Confirm Deletions` (which asks for confirmation for _every_ delete).

I suspect once you're out of the test phase with OGCS and it's running for real, you won't find it a problem.

**Comment by vorgrist** [comment]
Paul,

Thanks for the quick response. I looked for an explanation of the message
and could not find one. I'm sorry to have bothered you with this.

Thanks for the help and the great product. Is there a chance you can direct
me to the documents for multiple instance installation and command line
management?

Thanks again.

**Comment by phw198** [comment]
No worries :slightly_smiling_face: 

There's a link at the top of [this wiki article](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips) for multiple instance / command lines. Hope that helps!
