### ISSUE TITLE
Obfuscation rules panel doesn't close when clicking `Rules` button

### ISSUE THREAD

**Issue by mmangelsdorf** [phw198/OutlookGoogleCalendarSync#556]
**OGCS Version**: Regression since v2.7.4, it worked fine before
**Installed or Portable**: Portable

**Problem Description**  
Since v2.7.4 the **obfuscation rules panel isn't closed** anymore when clicking the `Rules` checkbox button again. Instead, clicking the button has no effect other than changing its `Checked` status.  
From a quick look at the source code, the problem seems to be that in the `CheckedChanged` event handler, the checkbox' `Checked` status is not used to trigger visibility, instead it is always set to `true`:

```C#
private void btObfuscateRules_CheckedChanged(object sender, EventArgs e) {
   this.howObfuscatePanel.Visible = true;    // This is the problem :)
   this.howMorePanel.Visible = false;
   this.btCloseRegexRules.Visible = true;
   syncOptionSizing(gbSyncOptions_How, pbExpandHow, true);
}

// Also, the close button should not be a checkbox, because its checked status will
// stay checked after closing the panel
private void btCloseRegexRules_CheckedChanged(object sender, EventArgs e) {
   this.btCloseRegexRules.Visible = false;
   this.howMorePanel.Visible = true;
   this.howObfuscatePanel.Visible = false;
   syncOptionSizing(gbSyncOptions_How, pbExpandHow, true);
}
```

**Steps to Reproduce the Issue**  
1. Install/Unzip v2.7.4 or later (still present in 2.7.5.2 ;-))
1. Go to `Settings` -> `Sync Options` and click `Rules`
1. Click `Rules` again (panel won't close)
1. Also try clicking the `X` in the 

**Any other information**  
See attached screencast for a demonstration of the current behavior:

![regression ui ogcs 2 7 4 - word obfuscation rules button doesn t close rules panel](https://user-images.githubusercontent.com/13134791/43250825-860a9f28-90be-11e8-84f2-be65f91c3a58.gif)

**Comment by phw198** [comment]
Hi @Merlin2001 - I like the screencast :slightly_smiling_face: 

However, this was an intentional behaviour change - I didn't feel the toggle `Rules` button was very intuitive and so made that button only open the rules and added the `X` button to close them.

**Comment by mmangelsdorf** [comment]
Ahh, ok! Maybe you could then use two `Button` controls instead of the currently used `CheckBox`es. Then they wouldn't "stick" when clicked :D

Since this isn't really a big issue (only a small usability glitch), feel free to close this issue and I'll try to send you a pull request soon (when I get to change it :)).

**Comment by phw198** [comment]
Ah yes, I'd forgotten they weren't proper button controls!
