### ISSUE TITLE
Install events not firing properly - shortcut icons not created

### ISSUE THREAD

**Issue by mischumerritt** [phw198/OutlookGoogleCalendarSync#557]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.6.5  
**Installed or Portable**: Installed

**Problem Description**  
There is a shortcut on the desktop, and I see it as an application under the Settings menus, but in neither the list of apps nor the tiles under the Start menu

**Steps to Reproduce the Issue**  
1. Install and run under windows 10.

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Thanks for reporting @mischumerritt 

This appears to be a regression bug starting in v2.7.5, which is causing the icons to not be created properly on install and not cleared up on uninstall.

**Comment by phw198** [comment]
This should be fixed on the next release.

**Comment by mischumerritt** [comment]
Paul,
GREAT!  Thanks for the prompt positive and effective response…making a great app a little bit better!
Michael
