### ISSUE TITLE
OGCS on Win XP

### ISSUE THREAD

**Issue by jra77** [phw198/OutlookGoogleCalendarSync#558]
**OGCS Version**: v2.7.0  
**Installed or Portable**: Installed

**Problem Description**  
Trying to install OGCS on Win XP SP3 immediately results in error message: "Setup.exe is not a valid Win32 application" 

**Steps to Reproduce the Issue**  
1. start setup.exe
 

**Any other information**  
I know, Win XP is way outdated, but it would help me a lot getting it to run at least temporarily (for migration of data). And the website says "Any version of Windows with .Net Framework 4.5 installed. Installed by OGCS Setup.exe if necessary.", so...

**Comment by phw198** [comment]
Yup, that's right it says "Any version of Windows with .Net Framework 4.5 installed" - let me know when you manage that on XP :stuck_out_tongue_winking_eye: 

https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-xp
https://blogs.msdn.microsoft.com/dotnet/p/dotnet45xp/

If you have calendar data stuck on XP, you could export/import it via an `.ics` file, or you could copy the Outlook `.ost` and/or `.pst` file to another install of Outlook on at least Vista.
