### ISSUE TITLE
 Unable to update existing entries in the Outlook calendar.  

### ISSUE THREAD

**Issue by hugoSAP** [phw198/OutlookGoogleCalendarSync#562]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
```
Sync version: 

Sync started at 2018-08-02 09:56:58

Syncing from 2018-08-02 to 2019-08-03

Outlook ↔ Google
Authenticating with Google...
Preparing to authenticate with Google.

Finding Calendar Entries
Scanning Outlook calendar...

81 Outlook calendar entries found.

Scanning Google calendar...

72 Google calendar entries found.

Total inc. recurring items spanning sync date range...

Failed to retrieve Google event

Failed to retrieve Google event
Outlook 81, Google 72Reclaimed: 2018-08-05 10:25 "Flight to Málaga (VY 2151)"


0 Google calendar entries to be deleted.

5 Google calendar entries to be created.

71 calendar entries to be compared.

Creating 5 Google calendar entries
2018-09-24 13:00 "Maria Camila"
2018-09-24 17:00 "Maria (fin)"
2018-09-19 20:00 "AGMR"
2018-08-14 08:00 "Christophe - Promenade Etangs CRA"
2018-08-04 13:00 "Coif Chantal"

Comparing 71 existing Google calendar entries
2018-09-03 "TSCM52 confirmed"
 → 

Attribute

Change

SubjectTSCM52 → TSCM52 confirmed
Description

Attendee addedSylviane Debaise
Reminder DefaultFalse → True

4 attributes updated.
1 entries updated.


3 Outlook calendar entries to be deleted.

0 Outlook calendar entries to be created.

71 calendar entries to be compared.

Deleting 3 Outlook calendar entries
Not deleted: 2018-09-03 10:00 "exam socio"
Not deleted: 
Not deleted: 

Comparing 71 existing Outlook calendar entries

Unable to update existing entries in the Outlook calendar.

The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
Attempting to reconnect to Outlook...

Operation aborted after 1 failed attempts!
```
**Steps to Reproduce the Issue**  
1. Restart sync
1. 

**Any other information**  
[Log file](https://gist.github.com/phw198/a5f9ab88c151fbc3c61393eb2d3b411e)

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

If you are on an version v2.7.3 or earlier, due to a [GitHub change](https://github.com/phw198/OutlookGoogleCalendarSync/issues/497) you will need to [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).
