### ISSUE TITLE
Trash filling up with deleted meetings

### ISSUE THREAD

**Issue by allenlook** [phw198/OutlookGoogleCalendarSync#563]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.5  
**Installed or Portable**: Installed

**Problem Description**  
Outlook is syncing one way, from Google Calendar.  (Google Calendar is syncing one way with a different instance of Outlook on a different network).  The Trash folder gets overwhelmed with thousands of deleted meetings.  I would think if a meeting is not updated, it would not be modified but apparently, OGCS goes through and first deletes every single meeting, and then re-downloads them all.  It does this every time it syncs, which seems inefficient and is blowing up my Trash folder.

**Steps to Reproduce the Issue**  
1.  Using product as normal and described above, with deletions enabled.

**Any other information**

**Comment by phw198** [comment]
So both outlook calendars are syncing to a common Google calendar? If so, that's not a supported configuration just get and will result in odd behaviour like you describe.

**Comment by allenlook** [comment]
Not exactly (I think).

Outlook instance A syncs one way (up) to Google calendar.

Google Calendar syncs one way (down) to Outlook instance B.

Regards,
Allen

**Comment by phw198** [comment]
Not exactly, but still not supported ;-) What you've got is the 2nd one with a red cross by it.

<img src="https://github.com/phw198/OutlookGoogleCalendarSync/raw/master/docs/images/supported_sync_configs.png" width=25% />

**However!** I've just released a development build that will support this (with Google being the middle calendar) over on issue #382 if you would like to try that out.

**Comment by allenlook** [comment]
Many thanks.

Downloaded, followed instructions, tried running it 4 times.  It starts to execute and then exits.

Regards,
Allen

**Comment by phw198** [comment]
Is there any error message?

:spiral_notepad: Are you able to upload your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)). Note, you can't submit this to GitHub via an email attachment.

**Comment by allenlook** [comment]
No messages whatsoever.

After a half hour, I noticed it in the system tray and in the process list, so one of them managed to launch eventually.

Then, just now, my domain account got locked out twice in 10 minutes.  It may have been a corrupted Outlook profile or the beta program, but it’s too much of a coincidence, so I shut down OGCS.

Regards,
Allen
