### ISSUE TITLE
OGCS does not start when Windows restarts

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#564]
OGCS does not start when Windows restarts.

2.7.5.0
--

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2270205/OGcalsync.log)

**Comment by kwagner115** [comment]
Possible user error.

**Comment by kwagner115** [comment]
Possible user error.

**Comment by kwagner115** [comment]
OGCS does not start when Windows restarts.

2.7.5.0
[Doc1.docx](https://github.com/phw198/OutlookGoogleCalendarSync/files/2271475/Doc1.docx)

**Comment by phw198** [comment]
Likely duplicate of #559
