### ISSUE TITLE
OGCS does not open or sync 

### ISSUE THREAD

**Issue by MissMIsh** [phw198/OutlookGoogleCalendarSync#565]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
When my laptop starts, OGCS stops working and displays the message below. I've tried downloading the alpha and beta versions but still no luck. Is it because Microsoft (2013) has blocked this app?

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
```
Application unexpectedly terminated!
Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: Interface not registered (Exception from HRESULT: 0x80040155).
```

**Comment by phw198** [comment]
Have you gone through the wiki: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered

**Comment by phw198** [comment]
Also, if OGCS only crashes on startup of your computer (ie you have OGCS to start on startup), but OGCS runs fine if you start it manually, try adding a delay to the startup of OGCS - it's an option in the settings.
