### ISSUE TITLE
Outlook calendar synch

### ISSUE THREAD

**Issue by TKucsi** [phw198/OutlookGoogleCalendarSync#567]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>Works very well and would use it in future but there is a minor topic why I can't use it.
I'm planning sometimes events a year in future and want to have this synchronized in each calendar. Current version only supports 2 months and this is far to less unfortunatley.

**Comment by phw198** [comment]
It supports up to 365 days in the future. You could also use your own API key to remove date restrictions altogether...
