### ISSUE TITLE
Synchronization is deleting Appointments in Outlook

### ISSUE THREAD

**Issue by Richi1964** [phw198/OutlookGoogleCalendarSync#569]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2296136/OGcalsync.log)
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
When syncronizing, appointments in exchange are deleted. I recreated them and the were deleted again. Some of them where missing in the Google Web Calendar and in the Google Calendar Smartphone App but some of them existed in both of these.

**Steps to Reproduce the Issue**  
1.  Create Appointment "Kunden-Mails & -Tickets" on 23.8., 28.8., 29.8.
2. Synchronize
3. In Exchange these appointments are missing on 28.8., 29.8., 31.8. In Google Web Calendar 28.8. and 29.8. are missing too, but 31.8. exists, Smartphone App the same

I see entries like 
"Could not find Outlook item with googleEventID eq1pofk3fitahnb9d12o8ptqs4 for post-processing."
and
"Item paste event caught."
in the log.

What does this mean?

Best regards,
Richard

**Comment by Richi1964** [comment]
Now I have set the syncronization to Outlook -> google.

Now I have double entries on 16.8. and 17.8. in google web (attachment 1). But still ok in Echange (attachment 2).

And missing entries in google web on 21., 22. and 24.8. (attachment 3). Also still ok in Exchange (attachment 4).

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2296162/OGcalsync.log)
![2018-08-17_080905](https://user-images.githubusercontent.com/42460804/44250557-18353600-a1f5-11e8-8ca9-2908b40a943a.jpg)
![2018-08-17_081055](https://user-images.githubusercontent.com/42460804/44250558-18353600-a1f5-11e8-9d0b-9fbd790418c4.jpg)
![2018-08-17_080611](https://user-images.githubusercontent.com/42460804/44250559-18353600-a1f5-11e8-924f-1eeb72a33c3e.jpg)
![2018-08-17_080753](https://user-images.githubusercontent.com/42460804/44250560-18cdcc80-a1f5-11e8-93ae-e08a835024ca.jpg)

**Comment by phw198** [comment]
It means that you've copied and pasted an item in Outlook that's already been synced...but more importantly, you've not upgraded to the latest alpha where that'll be fixed.

Due to a [GitHub change](https://github.com/phw198/OutlookGoogleCalendarSync/issues/497) you will need to [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/). Once upgraded, perform a full sync by pressing and holding `Shift` when clicking `Sync`.

**Comment by Richi1964** [comment]
Great - many thanks!
