### ISSUE TITLE
Deleted Appointment in Google Web Calendar is being recreated instead of syncronizing the deletion to outlook

### ISSUE THREAD

**Issue by Richi1964** [phw198/OutlookGoogleCalendarSync#570]
1. I created a appointment in outlook
2. It was syncronizet to Google Calendar
3. I deleted it in Google Calendar
4. It was not deleted in Outlook, instead it was recreated in Google Calendar at next sync

(Appointment "Test Fr" on 18.8.2018/11:00)

I have installed the latest Alpha Release this morning.

Best regards,
Richard
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2297061/OGcalsync.log)

**Comment by phw198** [comment]
That would be because the initial sync in step 2 (and most probably step 3) was performed whilst 1-way sync was configured. So this would be expected behaviour.

If you _now_ delete the Google item, it will get deleted in Outlook.

**Comment by Richi1964** [comment]
I guess I've changed the sync right after step 2. But it worked now. Thanks a lot!
