### ISSUE TITLE
Outlook to Gmail syncing error

### ISSUE THREAD

**Issue by faritale12** [phw198/OutlookGoogleCalendarSync#571]
Hi! Im trying to connect my outlook calendar to my gmail calendar. When I try to sync, it only recognizes 8 events, however there a lot more than 8 and most of them are recurring every week. Also, I keep getting a fail to sync past and future meetings/events. Please advise further.

Thank you!

**Comment by phw198** [comment]
You've made it almost impossible to advise by ignoring the Issue template and providing the requested information. You've not even mentioned the version of OGCS you are using or the error message, let alone upload your log file...

But you could try
* Upgrading to latest alpha release
* [Testing the Outlook date format](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items)
