### ISSUE TITLE
Outlook365

### ISSUE THREAD

**Issue by GRZ-Crunch** [phw198/OutlookGoogleCalendarSync#572]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Portable

**Problem Description**  
\Will either version work with Outlook365?

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
As in the desktop install Office 365 ProPlus edition? Yes sure, all OGCS versions should work with that.

However, if you mean does it connect straight to the cloud without any install of Office on your PC, then no, it doesn't.
