### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by GRZ-Crunch** [phw198/OutlookGoogleCalendarSync#573]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Portable

**Problem Description**  
\Is it possible to run multiple instances of the Portable for completely separate calendars?  e.g. one instance would sync my Outlook/Google calendars and another instance would sync some other person's Outlook/Google calendars?

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
I'm getting closer to building this into OGCS, but meanwhile take a look at [this wiki entry](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars).
