### ISSUE TITLE
Unable to cast COM object

### ISSUE THREAD

**Issue by GRZ-Crunch** [phw198/OutlookGoogleCalendarSync#574]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Portable

**Problem Description**  
\Getting the message "Unable to cast COM object...".  Snap of full message attached.  Any idea what might be causing this?  Possibly an install issue?  I did perform a repair on Outlook which did not help.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\
![outlookgooglecalsyncerror](https://user-images.githubusercontent.com/42476326/44489127-326d7a80-a620-11e8-883a-77ebe35c9bba.jpg)

**Comment by phw198** [comment]
Have a look here: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered
