### ISSUE TITLE
Some calendar entries made in outlook not copying from outlook to Google

### ISSUE THREAD

**Issue by OptimizeDigital** [phw198/OutlookGoogleCalendarSync#575]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.5.0  
**Installed or Portable**: Installed

**Problem Description**  
\<some calendar entries made in outlook not copying from outlook to Google.  See attached pics>

**Steps to Reproduce the Issue**  
1. \<I checked for update and it failed.  So I installed latest alpha, clicked update and it was latest, made sure all settings were the same and re-synced to no avail>

**Any other information**  
\<I don't know if this matters but the calendar entry in question was one that was updated for a later time.  All attachments and log file are included>
![image](https://user-images.githubusercontent.com/42647699/44533531-55993800-a6bb-11e8-927a-99760fb66f96.png)
![image](https://user-images.githubusercontent.com/42647699/44533570-6f3a7f80-a6bb-11e8-8475-273ee157572d.png)
![image](https://user-images.githubusercontent.com/42647699/44533667-a9a41c80-a6bb-11e8-86c6-85eb8cb88e7d.png)
![image](https://user-images.githubusercontent.com/42647699/44534785-2b954500-a6be-11e8-8c35-5e2719e71d4f.png)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2315118/OGcalsync.log)

**Comment by phw198** [comment]
Looks like the Google appointment was deleted at some point, and now OGCS is wanting to delete the Outlook appointment, but you're selecting no (understandably)?

Not being sure of how the Google item got deleted, to fix the immediate issue, [follow these instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-calendar-sync-with-full-sync) (you shouldn't actually need to do a full sync).
