### ISSUE TITLE
Can't install OGCS

### ISSUE THREAD

**Issue by leefko** [phw198/OutlookGoogleCalendarSync#577]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: CANNOT INSTALL

**Problem Description**  
\I am setting up new PC for a friend. He had OGCS on old computer, but when I install it on the new PC, I get the error:
Could not load file or assembly 'office, Version=12.0.0.0,
Culture=neutral, PublicKeyToken=71e9bcd111e9429c' or one
of its dependencies. The system cannot find the file specified.

**Steps to Reproduce the Issue**  
1. I've tried both the alpha and beta versions and get the same error

**Any other information**  
\New PC is an HP Gaming Desktop 690-00xx, AMD Ryzen 7 1700 8-core processor 3.00 GHZ with 16GB DDR 2666MHz RAM, 1 TB SATA, 4GB AMD Radeon RX550 Graphics, running the latest Windows 10 update

**Comment by phw198** [comment]
Sorry about that, and thanks for reporting!
Please try the newly updated alpha, v2.7.6

**Comment by leefko** [comment]
Thank you. That seems to have done the trick!

**Comment by leefko** [comment]
Hi, Paul,

Thanks for your help. I posted a comment to say that I was successful with the new version. I’ve put the beta on my own PC and will use it instead of gSyncit. I’ve made a donation on PayPal for your fine product.

Lee
