### ISSUE TITLE
Google Calendar colors copied incorrectly to Outlook Calendar

### ISSUE THREAD

**Issue by CJUnderhill** [phw198/OutlookGoogleCalendarSync#580]
**OGCS Version**: v2.7.5.0
**Installed or Portable**: Installed

**Problem Description**
When attempting to sync Google and Outlook calendars with each other, OGCS changes the "Grape" and "Lavender" Google Calendar colors to "OGCS Steel" in Outlook. This then syncs back to Google Calendar, which changes the above colors to "Graphite." The same occurs for "Tangerine," which gets changed to "OGCS Peach," which then becomes "Banana" when synced back to Google Calendar. This may occur for other colors, but I can confirm that the "Tomato," "Basil," "Peacock," and "Blueberry" colors sync properly.

**Steps to Reproduce the Issue**  
1. Create a new event in Google Calendar, assigning an event color of "Grape," "Lavender," or "Tangerine" to the event.
1. Ensure "Colours/Categories" are enabled in "Settings -> Sync Options -> What"
1. Sync the two calendars. The color will be changed to an OGCS color in Outlook that does not accurately match the Google Calendar color. In turn, the Google Calendar event will change its color ot match the new, incorrect OGCS color.
----
## Enhancements
Tasks added by @phw198 
- [x] Retrieve colours defined against select Google calendar
- [x] Provide ability to explicitly map between Google calendar colour and Outlook category. (See #759 for more details on use case)
- [x] Provide development build for feedback - see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) in the same way as a hotfix, making sure to apply it over v2.8.3.0.

:package: ~~[Development build v2.8.3.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4748524/v2.8.3.13.zip)~~
:package: ~~[Development build v2.8.3.14.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4761364/v2.8.3.14.zip)~~
:package: [Development build v2.8.3.15.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4775163/v2.8.3.15.zip) 

A new button is now available as shown below to define mappings between Google calendar colours and Outlook categories :tada: 

![ogcs-colour](https://user-images.githubusercontent.com/11843015/84082773-527a5380-a9d8-11ea-878a-ebf0d72db92e.gif)

**Comment by CassieMiller** [comment]
I'm having this problem as well.

**Comment by sync1914** [comment]
I need help with this same problem I need my Outlook desktop event colours to sync between Outlook and Google. I see above were CJ said Ensure "Colours/Categories" are enabled in "Settings -> Sync Options -> What". But when I look in my OGCS I don't see an option to Check colours under settings sync options were is it?

**Comment by phw198** [comment]
This will be because OGCS uses an algorithm to determine the closest colour match, but as you're finding, Color A converted to Colour B doesn't necessarily convert back to Colour A. This will no doubt be a risk for any algorithm, so it may be safer to define explicit mappings. Will need to think on how best to do that...

@sync1914 I don't think you have this problem at all! Sounds like you're running a version of OGCS that doesn't yet provide colour synchronisation, so first you need to upgrade to the latest alpha release 🙂

**Comment by phw198** [comment]
It's been a long time coming and _a lot_ more code than I anticipated.....but the requested feature is finally here!

A new button is available as shown below to define mappings between Google calendar colours and Outlook categories :tada: 
![image](https://user-images.githubusercontent.com/11843015/84077942-f90e2680-a9cf-11ea-9e26-a041d5b38707.png)

:package: For early adoption, please apply this [development build v2.8.3.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4748524/v2.8.3.13.zip) - see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)  in the same way as a hotfix, making sure to apply it over v2.8.3.0.

Please let me know how it goes!

@sjsdoc60 @madmax69ca

**Comment by sjsdoc60** [comment]
I am confused how to proceed.  I stopped using it quite a while ago due to
mapping conflicts, duplications etc.  I would like to try this.

I have 2.8.0.0 on the splash screen.  I may have installed an alpha variant
in the past, not sure.  However, OGCS automatically checked up for update
and asked me to go to 2.8.3. I said OK.  But it wont install.   Here is the
log.  I also tried manual and similar problem.  Since you say it has to be
2.8.3, I cant test at this point.

Thank you
Mark
ᐧ

**Comment by phw198** [comment]
@sjsdoc60 Thanks for picking this up so quick! To confirm, as per the [wiki Upgrading page](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading), you also tried downloading the alpha `Setup.exe` file afresh from the main website?

:paperclips: Unfortunately, files and screenshots can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by CassieMiller** [comment]
Hi folks,

Sorry, but I’m not sure why I’m included here...could I be removed from the thread?

Thanks,

**Comment by sjsdoc60** [comment]
I will try that and upload through there. Thanks
ᐧ

**Comment by phw198** [comment]
Hi @CassieMiller You commented back in Sep 2018, but only you can unsubscribe yourself from the thread. There should be a link in the emails you receive.

**Comment by sjsdoc60** [comment]
I just created a bug ticket #1005 in github.  I did get the software
installed as a hotfix in the alpha subdirectory.  Details in github.  But
then got the error when clicking on mapping.  See what you think. I did not
click details the first time so I repeated clicking on mapping and copied
the details in a second post.
ᐧ

**Comment by sjsdoc60** [comment]
Tried v15.  Installed in the alpha directory. Removed the .bak extension to the exe in parent directory.  Failed immediately on startup.  Application unexpectedly terminated.  Could not find file C:\users....Roaming\outlook google calendar sync\settings.xml.  Log file attached.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4777541/OGcalsync.log)

**Comment by phw198** [comment]
@sjsdoc60 Not really sure what steps you've done with the various executables, settings.xml files etc. I suggest you uninstall OGCS*, reinstall v2.8.3.0 and then patch it to v2.8.3.15 as per the [previous instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix).

\* If that doesn't work just delete the `C:\Users\sjsdo\AppData\Local\OutlookGoogleCalendarSync` directory entirely.

**Comment by phw198** [comment]
Feature released in v2.8.4

**Comment by PackElend** [comment]
> It's been a long time coming and _a lot_ more code than I anticipated.....but the requested feature is finally here!
> 
> A new button is available as shown below to define mappings between Google calendar colours and Outlook categories 🎉 ![image](https://user-images.githubusercontent.com/11843015/84077942-f90e2680-a9cf-11ea-9e26-a041d5b38707.png)
> 

Hi,
took me a while to find it.
Can that GIF be added to the wiki: https://www.outlookgooglecalendarsync.com/guide/syncoptions

**Comment by phw198** [comment]
Oops, the user guide was meant to have an animated gif showing how it works! I've now had a general update of the guide pages in light of the v2.11.0 beta release 🙂
