### ISSUE TITLE
Force Close on portable OGCS while starting

### ISSUE THREAD

**Issue by EnfantTerrible89** [phw198/OutlookGoogleCalendarSync#581]
**OGCS Version**: v2.7.6
**Installed or Portable**: Portable (can only use portable due to administration reasons)

**Problem Description**  
The application always did a great job and I love it. After a manual update though it is not starting anymore - I get a force close by Windows ("OutlookGoogleCalendarSync not working anymore").

**Steps to Reproduce the Issue**  
1. Start the application from my PC... :)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2331623/OGcalsync.log)

**Comment by EnfantTerrible89** [comment]
Hi Paul,

yes it was on the same PC. As I recall I was using 2.6.0.

Here the description of the eventvwr:
```
Name der fehlerhaften Anwendung: OutlookGoogleCalendarSync.exe, Version: 2.7.6.0, Zeitstempel: 0x5b83a4ba
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 6.1.7601.24168, Zeitstempel: 0x5b1aa7a9
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0000c54f
ID des fehlerhaften Prozesses: 0x26c8
Startzeit der fehlerhaften Anwendung: 0x01d43f9107262f8e
Pfad der fehlerhaften Anwendung: C:\Users\A34634949\Desktop\Portable_OGCS_v2.7.6\OutlookGoogleCalendarSync.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\syswow64\KERNELBASE.dll
Berichtskennung: 48740cae-ab84-11e8-ba56-2816ad2fdb53
```
Mainly it is saying that kernelbase.dll is a faulty module?

I also attached a picture of the error message. Unfortunately it is in german. 
![error](https://user-images.githubusercontent.com/42802114/44786979-7ae7e380-ab9e-11e8-8d90-c78fd6b2f3aa.png)

**Comment by phw198** [comment]
Thanks for confirming. I think in the `Application` event viewer log there should be an entry that actually captures the unhandled exception, complete with a stacktrace? It might be an earlier event to the one you provided above, if you could have a look.

**Comment by EnfantTerrible89** [comment]
Do you mean this?

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-08-29T12:15:02.000000000Z" /> 
  <EventRecordID>125164</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>BE1CF166.emea1.cds.t-internal.com</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Anwendung: OutlookGoogleCalendarSync.exe Frameworkversion: v4.0.30319 Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet. Ausnahmeinformationen: System.ComponentModel.Win32Exception bei System.Diagnostics.Process.StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo) bei System.Diagnostics.Process.Start() bei System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo) bei OutlookGoogleCalendarSync.Program.isNewVersion(Boolean) bei OutlookGoogleCalendarSync.Program.Main(System.String[])</Data> 
  </EventData>
  </Event>
```

**Comment by phw198** [comment]
Yes, that'd be it - and it's not failing where I expected!

Can you check what version of .NET framework you have installed? It looks like v4.0, but OGCS requires 4.5.
If you are already on 4.5, do you have a default web browser configured?

**Comment by EnfantTerrible89** [comment]
It was the default web browser! Changed it to Chrome (again) and now it is working as always. Thank you so much!

**Comment by phw198** [comment]
So what browser had been set as the default when it was crashing OGCS? Or you hadn't defined one?

If you are able to revert the fix and make OGCS crash again, it would be good to know how the value of the following registry keys (http and https) changes when OGCS works and doesn't: 

* `HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice\ProgId`
* `HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice\ProgId`

**Comment by EnfantTerrible89** [comment]
Actually after a system update from my working laptop no browser was set to default at all (I have no clue why...). I will try to revert the fix. Now working the values are:

- Outlook.URL.webcal.15
&
- Outlook.URL.webcal.15

Question: Why Outlook?!

**Comment by phw198** [comment]
OK, that's weird! For me key values are:
* Chrome = `ChromeURL`
* Firefox = `FirefoxURL`
* IE = `IE.HTTPS`
* Edge = `AppX90nv6nhay5n6a98fnetv7tpk64pp35es`

`Outlook.URL.webcal.15` is for Outlook 2016, so seems you have Outlook as your default web browser?! That value would normally be for eg `mailto`

I've just tried clearing my `https\ProgId` value and starting OGCS, and I got a Windows alert but OGCS didn't crash:
![image](https://user-images.githubusercontent.com/11843015/44803524-9e1e8d00-abb6-11e8-8888-ae5c7a0fb67e.png)

Maybe Windows10 handles it better than Windows7...
