### ISSUE TITLE
Word Obfuscation Rules are not applied at all

### ISSUE THREAD

**Issue by schultzter** [phw198/OutlookGoogleCalendarSync#583]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.5.0
**Installed or Portable**: Installed

**Problem Description**  
I configured a **Word obfuscation** Rule, my objective was to replace all titles with "Work"

Find: ^$
Replace: Work

**Steps to Reproduce the Issue**  
1. Updated to latest alpha
2. Set up sync
3. created word obfuscation rule to replace entire title/subject with "Work"
4. Sync Outlook calendar to Google
5. In Google the calendar entries all contain the original subject - no obfuscation was performed!!!

**Any other information**  
See screen shot below.

Also in the logs I see:
```
2018-08-30 14:33:49,716 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Obfuscate Words: True
2018-08-30 14:33:49,717 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      '^$' -> 'Work'
```
![ogcs_obuscation_rules](https://user-images.githubusercontent.com/30871/44875167-67567e80-ac6b-11e8-8680-5f4f195da578.png)

**Comment by phw198** [comment]
Don't really think that's a valid regex for what you want to do. Try `^.*$`

**Comment by schultzter** [comment]
So you were right about my Regex. I tested it in vim and few online Regex testers.

But it still doesn't work!? I tried a couple ways of defining it.
![2018-08-30 18_42_33-](https://user-images.githubusercontent.com/30871/44883374-d8566000-ac84-11e8-8ac2-65fa7b74cc5b.png)

![2018-08-30 18_51_07-](https://user-images.githubusercontent.com/30871/44883629-c4f7c480-ac85-11e8-8fd0-945dedb78ad3.png)

**Comment by schultzter** [comment]
I'm adding the events from Outlook to a separate GCal, so I can easily delete them (the individual meetings) after each test. 

But does OGCS _remember_ the meetings it has synchronized so it doesn't ever apply my obfuscation rules because I keep sync'ing the same set of meetings? So they aren't **new** meetings!

**Comment by phw198** [comment]
Sure, it only syncs _change_. So if you change the regex, it won't be applied to already synced items.

Either you can:
* Open individual Outlook items and make a pseudo change (eg add a space to the subject and remove it), then `Ctrl+S` to save it; or
* Press and hold `Shift` while clicking `Sync` to perform a full sync (not just change).

**Comment by schultzter** [comment]
I always do Press and hold Shift while clicking Sync to perform a full sync. After deleting all the events from GCal.

I've also tried:
1. ..* 
2. \* 
3. nothing (just blank)

Nothing seems to work. I must be doing something wrong?! I can't believe I'm the first person who's ever tried to replace the entire Subject of a meeting!!!

**Comment by phw198** [comment]
It's possible then that you're hitting issue #552 and need to [upgrade to v2.7.6](https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.7.6-alpha).

**Comment by schultzter** [comment]
Woohoo!

Looks like v2.7.6 solved the problem!!!
