### ISSUE TITLE
Cannot close OGCS Error Encountered window

### ISSUE THREAD

**Issue by drolevar** [phw198/OutlookGoogleCalendarSync#585]
**OGCS Version**: v2.7.5.0  
**Installed or Portable**: Installed

**Problem Description**  
Cannot close OGCS Error Encountered window. Clicking on "No" or "OK" buttons doesn't help. Clicking on "X" button in the top right corner of the window doesn't help either.
Closing the program helps.

![image](https://user-images.githubusercontent.com/14980349/44973807-0c1fd700-af5e-11e8-9177-359b18852277.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2344634/OGcalsync.log)

**Comment by phw198** [comment]
It seems the log file you have uploaded is from 3 Sep, but the error occurred on 31 Aug. Do you still have the log file from the 31 Aug? If so, please could you upload that too.

**Comment by ghost** [comment]
Just installed OGCS yesterday and when I woke my PC up this morning I had the same problem:
![image](https://user-images.githubusercontent.com/13423534/62212134-22046a80-b36e-11e9-9579-7dd36c36b570.png)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3451828/OGcalsync.log)
I had to kill the OGCS task in task manager to get the modal window to go away.

**Comment by phw198** [comment]
This is now covered by #682
