### ISSUE TITLE
Security Elevations

### ISSUE THREAD

**Issue by ognik777** [phw198/OutlookGoogleCalendarSync#589]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0 beta also v2.7.6-alpha
**Installed or Portable**: Installed

**Problem Description**  
\<Setup fails: "Outlook and OCGS are running in different security elevations ...."
I run outlook 2010 as Administrator.  Running setup as Administrator - no change if run as std. >

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Is it the same with running the portable version too?

**Comment by phw198** [comment]
The `Setup.exe` is actually completing fine, but when the first run of OGCS is automatically triggered afterwards, it is no longer in elevated mode.

However, having now installed OGCS, if you right click the installed Desktop or Start Menu icon for OGCS as Administrator, it will work as expected. 

Alternatively, as previously posted, I suspect the portable OGCS will avoid the issue surrounding installation and initial execution of the app in the wrong elevation level.
