### ISSUE TITLE
Moved appointments get deleted

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#59]
This is an issue that I reported 2 versions ago and has never been addressed.
When an appointment is moved (rather than newly created), the next time the
app syncs, that moved appointment is deleted (or asks to delete it as I have
"confirm deletions" option on). In the log attached the item that OGS want's
to delete is this one:  
  
2017-02-24 09:04:09,096 INFO 8 OutlookGoogleCalendarSync.MainForm [0] - Not
deleted: 14/03/2017 11:00 =&gt; "Healthcare customer journey"  
  
Thanks  
David  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 466](http://outlookgooglecalendarsync.codeplex.com/workitem/466)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Feb 24 at 8:12 AM
**Reported by:**	draeburn
**Updated on:**	Mar 25 at 3:52 PM
**Updated by:**	phw198

#### Plaintext Attachments

[CodePlex Issue #466 Plain Text Attachments](https://gist.github.com/78c86ab687c0549e26215e8485674bce)

**Comment by phw198** [comment]
On *2017-02-26 03:40:52 UTC*, **phw198** commented:

If the appointment still exists in Outlook and it wants to delete it in Google, then I'd let it - it will recreate it if necessary. Moves don't cause deletes though; strictly for that to happen, the source GUID of the appointment would have to change so
 the synced copy no longer matches it. I have no idea why this has happened for your "Healthcare customer journey", but I'm pretty confident it's not a bug in the app.

Under application behaviour, you could check the "create csvs" option and then compare the object IDs before and after you move an appointment to see if the IDs are in fact changing?

**Comment by phw198** [comment]
On *2017-02-28 16:11:39 UTC*, **draeburn** commented:

HI there, sorry for the delayed response! The appointment does NOT exist in Google, that is the problem....it will not sync once it's been moved and if I let OGCS delete it, then it is not recreated because it has never existed in Google. Here is another
 example: 

1 Outlook calendar entries to be deleted.
0 Outlook calendar entries to be created.
Deleting 1 Outlook calendar entries... 
Not deleted: 10/03/2017 12:00 => "Updated Invitation: Alignment Call HP/RH @ Fri Mar 10, 2017 13:00 - 14:00 (CET)
(david.raeburn@hpe.com)"
Done.
Every time I sync it wants to delete this appointment, and if I let it then it will be gone for good. So what is it about this particular appointment that means it won't sync, and why does OGCS want to delete it rather than sync?


Latest logs attached, and thanks for your help!

**Comment by phw198** [comment]
On *2017-02-28 20:56:43 UTC*, **phw198** commented:

OK, I think what's happening is the GUID of the Outlook item is changing when it gets moved. This causes it to no longer match with Google's synced copy, so that gets deleted. Then because the Outlook item know it
was synced, but there is no Google item, it now wants to delete the original Outlook item.

So the question is, what is causing the GUID to change? To troubleshoot this I'll need your help. Set OGCS to create CSVs, which records GUIDs. Make a copy of them as they stand now, and then when another item starts exhibiting this problem, we can compare
 the current CSVs against your old copied ones.

Is there a common theme to the items having this problem? Are they all invites sent by someone else and they are then moving the appointment?

Cheers

**Comment by phw198** [comment]
On *2017-02-28 21:04:01 UTC*, **phw198** commented:

By the way, a couple of workarounds for these items:

Perform a single one-way sync from Outlook to Google to recreate the item(s).
Manually create the missing Google item with the same start+end date and subject. OGCS should "reclaim" the Google item and sync it as normal.

Note, for any unintended deletions that do happen, they should be found in the deleted item of Google and/or Outlook, which can use to recover.

Really would like to find out why this is happening to you though (see previous post).

**Comment by phw198** [comment]
On *2017-03-03 01:02:03 UTC*, **draeburn** commented:

OK, no problem I'll start logging it from now and the next time it happens. Thanks!

**Comment by phw198** [comment]
On *2017-03-03 03:36:41 UTC*, **AJolly** commented:

Subscribing. I was having a similar issue, so I stopped syncing in two way mode.
(Wish there was a debug mode where I could force the app to confirm any changes before they are made!)

**Comment by draeburn** [comment]
Same problem still exists, just for the record! I didn't get an original CSV before it happened again, so once that date is passed, I'll do it and post here on the next occurrence. The workaround you suggested doesn't work either, even if the appointments are identical!

**Comment by phw198** [comment]
Fixed under issue #225.
