### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hasafi** [phw198/OutlookGoogleCalendarSync#590]
**OGCS Version**: Portable_OGCS_v2.7.6.zip
**Installed or Portable**: Portable

**Problem Description**  
app does not start

**Steps to Reproduce the Issue**  
1. Start app

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2378169/OGcalsync.log)

Previous version worked for me.

Thank you for any tip

**Comment by phw198** [comment]
Your log file shows it starting. There are some errors when it tries to connect to Outlook, as it looks like there might be corporate policy blocking access to the Outlook address book, but this will just give you reduced functionality within OGCS.

What are you seeing that makes you say OGCS doesn't start at all?
