### ISSUE TITLE
User-agent

### ISSUE THREAD

**Issue by kaoscoach** [phw198/OutlookGoogleCalendarSync#591]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.5
**Installed or Portable**: Installed

**Problem Description**  
Is there a way to modify the User-agent that is used for the outbound connection to Google? My work proxy server is preventing the connection because the agent comes across as a really old version "Mozilla / 5.0(Windows NT 6.1; WOW64; Trident / 7.0; rv 11.0) like Gecko

**Steps to Reproduce the Issue**  
1. \<Update>
Try to update, it doesn't work.

**Any other information**  
\<Update here>

**Comment by kaoscoach** [comment]
Nevermind. I found the settings.xml file and was able to edit it. Is there a way to have this autopopulated with the currently installed version of Chrome or IE?

**Comment by phw198** [comment]
I think this is pretty edge-case and determining the default browsers user-agent appears to be a _lot_ of work.

As you found, the workaround is to edit the `BrowserUserAgent` setting in `settings.xml`.

What string worked for you and what was the error being reported when it wasn't working? It might be possible for me to provide some popup guidance if the error is specific enough...

**Comment by kaoscoach** [comment]
As I said, my work proxy looks for specific (recent) versions in the the user-agent and will block any that are "old". I do not know the exact string I used. I just used the text at https://www.whatismybrowser.com/detect/what-is-my-user-agent to resolve. It would be nice to somehow auto-populate this information but I think I can update it every month or so as needed.

**Comment by phw198** [comment]
- [x] [Write web page](https://phw198.github.io/OutlookGoogleCalendarSync/browseruseragent) that detects browser
   - [x] [Waiting for fix](https://github.com/sandinmyjoints/whatsmyua/issues/7) from developer
- [x] Update UI with button to open browser to above webpage

**Comment by kaoscoach** [comment]
This site allows the connection via https, https://uploadbeta.com/api/user-agent/

**Comment by phw198** [comment]
:package: Development build [v2.7.6.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2454416/v2.7.6.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
