### ISSUE TITLE
Is there any way to stop the notifications I receive every time synchronization happens?  For some reason, it seems to not be able to handle deletions correctly.  I can probably live with that, but I don't want to constantly see and have to respond to the warning messages.

### ISSUE THREAD

**Issue by pnocero** [phw198/OutlookGoogleCalendarSync#594]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by pnocero** [comment]
Is there any way to stop the notifications I receive every time synchronization happens? For some reason, it seems to not be able to handle deletions correctly. I can probably live with that, but I don't want to constantly see and have to respond to the warning messages.

**Comment by pnocero** [comment]
I tried to do the update check on the "About" page, and it says "Unable to check for new version."  What causes this, and how do I get the latest version to see if my problem above is fixed?

I have donated.

**Comment by pnocero** [comment]
Is there any way to stop the notifications I receive every time synchronization happens? For some reason, it seems to not be able to handle deletions correctly?  I can probably live with that, but I don't want to constantly see and have to respond to the warning messages.

The "Check for Update" returns a message "Unable to check for new version."

I have Version 2.7.0.0 installed, donation made.

**Comment by pnocero** [comment]
Sorry for the repeat messages.  I didn't see the earlier ones till I closed the process.  The last message includes everything.

**Comment by phw198** [comment]
I'm not sure if this issue sold be open or closed!

:arrow_double_up: To upgrade from version v2.7.3 or earlier, due to a [GitHub change](https://github.com/phw198/OutlookGoogleCalendarSync/issues/497) you will need to [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).
