### ISSUE TITLE
Error Upon Installation

### ISSUE THREAD

**Issue by JesnarM** [phw198/OutlookGoogleCalendarSync#597]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here
![google sync](https://user-images.githubusercontent.com/43357310/45653882-18826300-bb0c-11e8-9759-45d69f9d4912.jpg)
>

**Comment by phw198** [comment]
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary

Incidentally, what version of OGCS are you running?

**Comment by JesnarM** [comment]
Used the 2.7.0-beta [setup.exe]
 
Kind Regards

**Comment by phw198** [comment]
Did the wiki article help you fix the error?

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

Note, you can't attach the logfile to a reply by email.
