### ISSUE TITLE
New Install, New PC: Precondition Failed [412=PreconditionFailed]

### ISSUE THREAD

**Issue by HeavyG603** [phw198/OutlookGoogleCalendarSync#598]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.6.0
**Installed or Portable**: Installed

**Problem Description**  
Figured I'd give this another shot on a brand new PC.  Different issues, but issues.  Setup went fine, I have the sync to Google -> Outlook only due to past issues and deletes disabled.  Full log attached.

**Steps to Reproduce the Issue**  
1. Install
2. Setup
3. Sync

**Any other information**  
[OGcalsync.log](https://gist.github.com/phw198/a381e837ca3c7b48002a65f262fe06f3)

**Comment by HeavyG603** [comment]
Update to this, after a few successful syncs now getting an object error, [log pasted here](https://gist.github.com/phw198/a381e837ca3c7b48002a65f262fe06f3#file-ogcalsync-log).

**Comment by phw198** [comment]
Not sure if you're still using OGCS, but it looks like there is a problem with the `6/25/2018 1:00 PM (R) => "Project Management Review Meeting"` appointment in Outlook - it's not able to access the attendee email address for thomas.walker, and seems to then try and both add and remove the same attendee.

As you have one-way sync G->O, could you try just deleting this appointment and letting OGCS recreate it?

**Comment by HeavyG603** [comment]
Thanks !   I’ll give it a shot.

Thanks,
Gary P. Gauvin, MBA, PMP, PSM
Ggauvin@gauvintech.com<mailto:Ggauvin@gauvintech.com>
(603)494-6200



On Dec 28, 2018, at 10:03 PM, Paul Woolcock <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if you're still using OGCS, but it looks like there is a problem with the 6/25/2018 1:00 PM (R) => "Project Management Review Meeting" appointment in Outlook - it's not able to access the attendee email address for thomas.walker, and seems to then try and both add and remove the same attendee.

As you have one-way sync G->O, could you try just deleting this appointment and letting OGCS recreate it?
