### ISSUE TITLE
Cannot set sync schedule lower than 2 hours or 120 minutes

### ISSUE THREAD

**Issue by resq93** [phw198/OutlookGoogleCalendarSync#602]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>Cannot set sync schedule lower than 2 hours or 120 minutes. Have tried setting to shorter intervals but it just jumps to 120 minutes

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>
![image](https://user-images.githubusercontent.com/43446898/45828485-a0ac6800-bcc6-11e8-8dc4-04f84d998914.png)

**Comment by phw198** [comment]
And why you would want push sync _and_ a scheduled internal of less than 2 hours? The restriction you're reporting is exactly to protect against this kind of API quota abuse. 

If you really really want to configure it this way, you'll need to set up your own Google API keys under Advanced / Developer Options on the Google settings tab.

**Comment by mkarneim** [comment]
> If you really really want to configure it this way, you'll need to set up your own Google API keys under Advanced / Developer Options on the Google settings tab.

Nice! Thank you for this hint.
This was really helpful for solving #14 for me.
However, I guess this solution is only suitable for tech guys with some Google API experiences...

**Comment by resq93** [comment]
Then maybe I misunderstand something. The check box says something about pushing Outlook changes right away but what about the other way around? I find that the changes made on the Google calendar side are not pushed in real time while the Outlook changes are.

I understood the sync settings to be on the Google Cal side and the push setting to be on the Outlook side. What am I missing?

**Comment by phw198** [comment]
@resq93 That is a fair point - there is no way to get push notifications from Google, so a schedule would be needed if you are only making changes in Google. But assuming you make a change in Outlook, this would push to Google and then OGCS automatically will pull from Google back to Outlook during the same sync (as you have two-way sync configured).

As mentioned, the limitation is there to prevent users setting push from Outlook as well as a scheduled sync every 10 minutes from Google, which wasn't fair on other users as the API quota is shared. To remove this limitation, you can set up your own API keys if you so wish.
