### ISSUE TITLE
2.7.6 Slow processing

### ISSUE THREAD

**Issue by Stuwilli1** [phw198/OutlookGoogleCalendarSync#606]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**:v2.7.6.0 
**Installed or Portable**: Installed

**Problem Description**  
\30-40 minutes to process!

**Steps to Reproduce the Issue**  
1. everytime it syncs
1. 

**Any other information**  
scan entries quickly then just sits on the comparing typically.

**Comment by phw198** [comment]
But you closed the issue?

Anyway, appears to be a duplicate of #599 - do you have high CPU usage during that "comparing" phase? If so, please increase logging to `ULTRA-FINE` and post it to #599.

As an aside, you seem to have `9/10/2018 10:00 AM (R) => "Pay AT&T "` with 730 exceptions to the recurrence (on the 7th of every month from Nov 2018 to Aug 2079)?! Not sure what your recurrence rule is, but maybe it needs improving?

**Comment by Stuwilli1** [comment]
Sent in, thank you.

Best regards,

Stuart A. Williams
(904) 615-7004
