### ISSUE TITLE
0x80004002 (E_NOINTERFACE) for IWebBrowser2

### ISSUE THREAD

**Issue by niekjol** [phw198/OutlookGoogleCalendarSync#607]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I get the following error when syncing:
```
Sync version: 
Sync started at 01-10-2018 10:27:02
Syncing from 01-09-2018 to 31-03-2019
Outlook → Google
Finding Calendar Entries
Unable to cast COM object of type 'System.__ComObject' to interface type 'IWebBrowser2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D30C1661-CDAF-11D0-8A3E-00C04FC9E26E}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

Finding Calendar Entries
Unable to cast COM object of type 'System.__ComObject' to interface type 'IWebBrowser2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D30C1661-CDAF-11D0-8A3E-00C04FC9E26E}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

Operation aborted after 2 failed attempts!
```

**Steps to Reproduce the Issue**  
1. I just installed latest beta version.

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2433234/OGcalsync.log)

I see that you already have an entry on 0x80004002 (E_NOINTERFACE). I'm running this on a company computer so I don't have the option to reinstall Office. It is a new computer, so I just got Office installed, so I don't think reinstalling will make any difference.
I'm running Office 2010. I have checked the registry and it seems fine.

**Comment by phw198** [comment]
The wiki entry for 0x80004002 is for when accessing Outlook - you appear to be getting the error when OGCS is updating the embedded web browser control! I've never seen this problem before, and there doesn't appear to be much on Google about it.

Standard advice is always to upgrade to the latest version of OGCS...

:arrow_double_up: Due to a [GitHub change](https://github.com/phw198/OutlookGoogleCalendarSync/issues/497) you will need to [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

**Comment by niekjol** [comment]
Hi,

Thanks. Actually, I started with the newest version, with didn't work. Then
I tried an older version, because the it worked fine with the old version
on my old company laptop.

Guess there is nothing much I can do?

Best regards,
Niels

**Comment by niekjol** [comment]
Thanks! I'll give it a try tomorrow.

BR Niels

**Comment by niekjol** [comment]
It worked! Thanks!!

**Comment by phw198** [comment]
Well I never! That was a shot in the dark❗️
