### ISSUE TITLE
Alternate Mailbox selection not saving properly - reverting to incorrect mailbox on re-open

### ISSUE THREAD

**Issue by mdmoran62** [phw198/OutlookGoogleCalendarSync#611]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.6.0  
**Installed or Portable**: Installed

**Problem Description**  
\I have multiple mailboxes and calendars on my Outlook installation, including three different gmail ones (all dedicated domains, rather than @gmail.com ones) - I set the "Alternative mailbox" to one of these [mark@moranCA.com], but when I close and re-open OGCS, it reverts top another one [mark@lovehardkamloops.ca]. I keep changing the drop-down in the Alternative mailbox back to my moranCA one, and "save", but consistently, when I close and re-open OGCS, it reverts back to my lovehardkamloops.ca one.

This has now synced my outlook moranCA calendar to the wrong google, and I've lost 20 very critical client appointments and google has then synced to my iphone and deleted them there too... not a happy camper at all.

For further information, about a week ago, I added the 'mark@lovehardkamloops.ca' account to my outlook (and don't use a calendar), and somehow OGCS is reverting to this one all the time - possibly because it's the latest one that I've connected to Outlook? Up until now, my 'mark@moranCA.com' account was the latest that I connected to Outlook... that is my suggestion as to a big clue to the problem.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Thanks for reporting this - I think it's been a really long standing bug!

:package: It should now be resolved with [hotfix v2.7.6.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2522322/v2.7.6.11.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by mdmoran62** [comment]
Success!

Side-note… I use multiple google accounts (and corresponding calendars, couple of business and a society gmail)… any plans for being able to sync multiple different gmail-outlook calendars such as this? Currently, I’m only set to one, and only worry about keeping one synced… but I would have need to use multiple syncs if it was ever available.

Thanks again for fixing this. 😊

Mark
__________________________________
Mark Moran, CPA,CA CISA CRISC CRMA

**Comment by phw198** [comment]
@mdmoran62 [See here for details](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars) on syncing multiple calendars (currently needs a separate instance of OGCS configured for each).

v2.7.6 set the way for building this feature in to OGCS properly, but Issue 599 is causing concern of side effects that need working out first...
