### ISSUE TITLE
Error 0x80040155

### ISSUE THREAD

**Issue by floribe2000** [phw198/OutlookGoogleCalendarSync#612]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.6 and v2.7.0
**Installed or Portable**: portable

**Problem Description**  
When I try to start the application, I get the error mentioned in the title. It seems to be the same issue that is described in issue #574 but the solution from that issue doesn't work.
The error occurs since I updated from Outlook 2013 to Office365. A reinstall and a repair of Office didn't help

**Steps to Reproduce the Issue**  
1. Start the application and get the error screen

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
So what did you try from the wiki article? There are lots of registry keys to check and update for this error...

https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#1-fix-the-interface

**Comment by floribe2000** [comment]
I think I tried all registry fixes from that page (might be possible that I forget one but I think this didn't happen). Unfortunately nothing changed, I'm still getting that error message.
Is it important that I use Outlook from Office 365?

**Comment by phw198** [comment]
> Is it important that I use Outlook from Office 365?  

I'm not too clear on the question. It's important that you have Outlook properly installed and registered, but the particular version (eg Office ProPlus for O365) shouldn't matter.

However, I think the wiki entry isn't very clear about the fix - it's not just Step 1 "Fix the interface", but also [Step 2](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#2-fix-the-typelib) and [Step 3](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#3-ensure-msoutllib-is-registered) that's needed.

If you can confirm if performing all 3 steps works, I'll get the wiki updated.

**Comment by floribe2000** [comment]
Oh, I didn't realize that step 2 and 3 are necessary too. I thought I need only step 1 because in the FAQ it says "then fix the interface". A little hint that all three steps are needed would be nice (I could have tried the other steps but usually I try not to mess with my registry so I'm a bit too careful sometimes).

Step 3 was the key, after running the command it worked again. 
Thank you for your support and the very quick reaction!
