### ISSUE TITLE
Not pushing outlook changes to google

### ISSUE THREAD

**Issue by CPSimon** [phw198/OutlookGoogleCalendarSync#614]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\Set to push changes from outlook but new appointment created does not get pushed to google calendar. 

**Steps to Reproduce the Issue**  
1. \Updated the meeting time in order to generate a new outlook change. 
1. 

**Any other information**  
\Manual sync works. Using "start sync" will sync items to google. 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2469670/OGcalsync.log)

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by [downloading the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).
