### ISSUE TITLE
Deleting calendar event from Google wont send event cancelation e-mail

### ISSUE THREAD

**Issue by oroszlanyzsolt** [phw198/OutlookGoogleCalendarSync#617]
**OGCS Version**: v2.7.0
**Installed or Portable**: Installed

**Problem Description**  
Deleting calendar event from Google calendar, event cancellation e-mails are not sent to event participants. On the other side deleting event from Outlook, Outlook sends out cancellation e-mails.

**Steps to Reproduce the Issue**  
1. Create an event in Google Calendar
2. Invite event participants (participant receives e-mail)
3. Delete event in Google Calendar
4. Participant does not receive event cancellation e-mail

**Any other information**

**Comment by oroszlanyzsolt** [comment]
I have to admit I'm unsure about this too. Yes I can see attendee email in the event, it is "obfuscated" but it is there. When I was deleting events from Google Calendar it does show the same popup as you embedded here, clicked on the Send button which should send out cancellation email, but nothing happened.

**Comment by phw198** [comment]
When you say "obfuscated" do you mean the attendee email addresses have `.ogcs` appended? If so, I'll assume you have 2-way sync on and `Cloak email in Google` checked - this a feature to stop Google spamming attendees without the user's permission (some users experienced this - [see here for the background](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google)). 

However, if you _want_ notifications to be sent, try unchecking that box and performing a full sync (`Shift` key + click `Sync` button).
