### ISSUE TITLE
Google handshake failed.

### ISSUE THREAD

**Issue by tuliofilho** [phw198/OutlookGoogleCalendarSync#618]
**OGCS Version**: v2.7.6.0 
**Installed or Portable**: Installed

**Problem Description**  
When I click on 'Retrieve Calendars' the following error shows up.
 
![image](https://user-images.githubusercontent.com/43251939/47032421-b471af80-d148-11e8-8e65-4baeb32c0cec.png)

I've attached my log file.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2484066/OGcalsync.log)

**Comment by tuliofilho** [comment]
No popup advising .Net upgrade was shown.
Same error.

Log attached.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2496886/OGcalsync.log)

**Comment by phw198** [comment]
The only call being made during this error is one to a Google auth library. I've therefore updated the relevant libraries.

:package: Could you extract the files in [v2.7.6.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2498306/v2.7.6.8.zip) to `C:\Users\Tulio\AppData\Roaming\Outlook Google Calendar Sync\app-2.7.6-alpha\` and let me know if has helped?

**Comment by cees2349** [comment]
OGCS seems to work fine now. Thanks for your help. Much appreciated. Will make contact again in case it plays up.

(Edit by @phw198 - this comment is against the wrong issue).

**Comment by phw198** [comment]
Any update @tuliofilho or shall I close this issue out?
