### ISSUE TITLE
Unable to determine outllook client version

### ISSUE THREAD

**Issue by mikeginfl** [phw198/OutlookGoogleCalendarSync#624]
Unable to sync calendars since 10/24/18 due to outlook update. OGCS errors at start up when attempting to sync. Getting error below.

----

**OGCS Version**: v2.7.6.0
**Installed or Portable**: Installed

**Problem Description**  
\
![image](https://user-images.githubusercontent.com/44608261/47718101-e6d9dd00-dc1d-11e8-9c59-f717330adde7.png)

**Steps to Reproduce the Issue**  
1. When OGCS starts it fails and reattempts provide the same failure
 
![image](https://user-images.githubusercontent.com/44608261/47718174-17ba1200-dc1e-11e8-9ead-a65e4224dc45.png)

**Comment by phw198** [comment]
Please take a [look at the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary) for how to fix this.

I'll also look at why OGCS isn't automatically taking you to there.

**Comment by WDBehr** [comment]
You don't have to install and you lose nothing in the process.
