### ISSUE TITLE
Asking for permission after each windows restart

### ISSUE THREAD

**Issue by sayed-seliman** [phw198/OutlookGoogleCalendarSync#626]
Hi,

I just downloaded the application and it works great.
I just have a problem that each time I restart my pc the application is asking to me if I want to allow access to outlook data. When I answer yes everything start to work correctly, but on the next windows restart I have to answer again to the same question.

It's not possible to store this permission?

Regards

**Comment by phw198** [comment]
Hi @sayed-seliman 

As [per the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security), likely you just need to set a startup delay for OGCS.
