### ISSUE TITLE
asking me to setup Outlook 2016

### ISSUE THREAD

**Issue by kstrohme** [phw198/OutlookGoogleCalendarSync#627]
had GoogleOutlookCalendarSync on a older computer running Windows 7 and Outlook 2010.  Got a new computer with Windows 10 but still have Outlook 2010 on it.  When I downloaded the GoogleOutlookCalendarSync on the new computer, it works ok, but every time I open it, it wants me to setup Outlook 2016, and I have to click through several warning buttons to get rid of it.  Downloaded the latest version, then uninstalled and downloaded the more stable version, but it's still doing the same thing.  How do I fix this?

**Comment by phw198** [comment]
OGCS is completely agnostic as to the version of Outlook installed. I'm not convinced the prompt to setup Outlook 2016 has anything to do with OGCS, more likely that when you open Outlook 2010 it prompts you to upgrade regardless.

I guess if you have OGCS set to auto sync and Outlook is not running, every time it does sync, Outlook will start and you'll get the prompt?

**Comment by kstrohme** [comment]
Thanks for getting back with me.  

A couple things have happened. First- I just replaced my laptop, and the new machine has windows 1o installed, while I was working with Windows 7.  I had had no problems before the change.  Outlook 2010 has given me all kinds of grief since the change.  In particular, I couldn’t get into the area where I added an email signature, and he had to make some kind of registry(?) change and now that works. (just haven’t done it yet, as you can see.)

I opened outlook and then opened OGCS, this morning, and I did NOT get the 2016 prompt.  Closed out both, then opened OGCS first, and still no prompt.  I had installed the “more stable” version of OGCS the other day.  I do know that when I closed the 2016 prompt earlier, I did get a window from OGCS with a bunch of computer jargon on it. 

So either that registry change fixed it, or the older version of your program works better for me.

One challenge this morning- when I stated the OGCS program- it deleted almost all my calendar entries from both Google and from Outlook!!  At this point, I don’t know what setting I have checked that I shouldn’t have. I’m retired, so nothing was of any major consequence, other than just some time to re-enter them.

**Comment by phw198** [comment]
Glad you got it working - I'm pretty sure it was the registry fix that resolved it, not downgrading to an older version of OGCS. 

FYI, for the deleted items, they should have been recoverable from the Deleted Items folder; you could have then one-way full synced (`Shift`+click `Sync` button) them to Google, then turned back on two way sync. But sounds like you've got things how you need now anyway.
