### ISSUE TITLE
Marks entries as "Free", although the checkbox is not ticked in the settings

### ISSUE THREAD

**Issue by szamizdat** [phw198/OutlookGoogleCalendarSync#629]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.6.0
**Installed or Portable**: Portable

**Problem Description**  
\Marks "ALL DAY EVENTS" type entries as "Free" in Outlook calendar after syncing them from Google, although the checkbox is unticked in the settings

**Steps to Reproduce the Issue**  
1. \Run Sync
2. \Check Outlook calendar entries 

**Any other information**  
\

**Comment by phw198** [comment]
Pretty sure that's the default when an all-day entry is created in Google - it's set as `Free`. Set it to `Busy` in Google and it will get synced to Outlook as such.

**Comment by szamizdat** [comment]
Ohh! I didn't noticed it! Thank you!





Paul Woolcock <notifications@github.com> ezt írta (időpont: 2018. nov. 15.,
Cs, 1:13):
