### ISSUE TITLE
OGCS won't start [0x80040155]

### ISSUE THREAD

**Issue by franckt68** [phw198/OutlookGoogleCalendarSync#630]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0.  
**Installed or Portable**: Portable

**Problem Description**  
Since yesterday I have a problem with OGCS - it just does not start. When I click on the OutlookGoogleCalendarSync.exe file, a splash screen appears, which, as always, disappears after a few seconds. Then nothing happens in most cases. Sometimes a warning to set the delay when logging in to Windows is displayed. When I click on the "OK" button, nothing happens again. Because I am already logged in, this notice is probably meaningless.

I use the portable version 2.7.0.0., Windows 10 and outlook 365
Any advice on making OGCS working again will be appreciated.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2579808/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
The fix should be found [in the wiki here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered).

**Comment by franckt68** [comment]
Unfortunately, I don't have administrator rights... (that's why I was using a portable version).
Any advice?
