### ISSUE TITLE
Should OutlookGoogleCalendarSync.exe.config be persisted?

### ISSUE THREAD

**Issue by nightscape** [phw198/OutlookGoogleCalendarSync#637]
Hi @phw198,

I wrote [a scoop manifest for OGCS](https://github.com/lukesampson/scoop-extras/blob/master/outlook-google-calendar-sync.json) which allows users to install via `scoop install outlook-google-calendar-sync`.
I'm just trying to configure the manifest to retain configurations files during updates and I was wondering if both `settings.xml` and `OutlookGoogleCalendarSync.exe.config` should be kept during an update or only the former is necessary?

**Comment by phw198** [comment]
Hi @nightscape - I would say only `settings.xml` should be kept, the `.config` is specific to each release.

HTH
