### ISSUE TITLE
v2.7.7-alpha setup.exe seems to be an empty stub

### ISSUE THREAD

**Issue by ScottRochford** [phw198/OutlookGoogleCalendarSync#638]
The v2.7.7-alpha setup.exe linked from the home page seems to be an incomplete stub.

https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.7.7-alpha/Setup.exe

When I run it I get a dialogue entitled 'hwhoops' saying "This is a dummy update.exe  If you are seeing this, your build did not correctly replace the IDR_UPDATE_ZIP resource.  Command Line: '--install .'

**Comment by phw198** [comment]
Thanks for reporting this! Not quite sure what happened there, but it should be fixed now.
