### ISSUE TITLE
Unable to Sync due to recurrence issue

### ISSUE THREAD

**Issue by dmccrea** [phw198/OutlookGoogleCalendarSync#639]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.7.0
**Installed or Portable**: Installed

**Problem Description**  
\"Unable to update existing entries in the Outlook calendar. This property cannot be changed for a single instance of a recurring meeting."

**Steps to Reproduce the Issue**  
1. \Fails each time it's run. Specific calendar entry not identified. Because operation aborted, no log file.
1. 

**Any other information**  
\Attaching screen image of repeated tries and sync verbose output.
![outlook google calendar sync error](https://user-images.githubusercontent.com/45640442/49543774-ed4b1c80-f88d-11e8-9e7f-0542504b8198.jpg)
![outlook google calendar sync outlook settings](https://user-images.githubusercontent.com/45640442/49543775-ed4b1c80-f88d-11e8-968a-6a66acd5b895.jpg)
![outlook google calendar sync report](https://user-images.githubusercontent.com/45640442/49543776-ed4b1c80-f88d-11e8-9013-18712313714b.jpg)
![outlook google calendar sync splash screen](https://user-images.githubusercontent.com/45640442/49543777-ed4b1c80-f88d-11e8-8384-1e4b388a978d.jpg)

**Comment by phw198** [comment]
:spiral_notepad: The logfile would still exist despite the abort - please [see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file).

**Comment by phw198** [comment]
:package: I think I know where the problem is - could you try this [Hotfix v2.7.7.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2692359/v2.7.7.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

If it doesn't work, could you increase the logging level to `FINE`, reproduce the error and then upload the log file again. Thanks!

**Comment by dmccrea** [comment]
Sorry for the delay! Very busy holidays! Applied the hotfix this evening and the first sync was completed successfully! Will monitor over the next couple of days. Thanks so much for responding so quickly! Love the product!

**Comment by willthong** [comment]
Same problem - hotfix worked for me too!
