### ISSUE TITLE
Outlook Warning "Access Email Info Stored in Outlook"

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#64]
Hello,  
  
I searched through the previously opened issues and didnt see anything about
this. I apologize if this has already been discussed and I missed it.  
  
Everytime I reboot my computer I get a pop-up box that states:  
  
"A program is trying to access e-mail address information stored in Outlook.
If this is unexpected, click Deny and verify your antivirus software is up-to-
date.  
  
For more information about e-mail safety and how you might be able to avoid
getting this warning, click Help.  
  
Allow Access (CHECKBOX HERE) Options (1minute/5minutes/10minute)  
  
BUTTONS: ALLOW/DENY/HELP."  
  
I've attached a screenshot of the pop-up message.  
  
Every time I select 10 minutes and click ALLOW but every time I reboot it pop-
ups again. Is there anyway to avoid this pop-up from occurring?  
  
Thank in advance.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 482](http://outlookgooglecalendarsync.codeplex.com/workitem/482)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Mar 24 at 3:00 AM
**Reported by:**	thebob6
**Updated on:**	Mar 27 at 6:56 AM
**Updated by:**	thebob6

#### Binary Attachments

[Outlook_ERR_POP_UP.PNG](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=482&FileAttachmentId=1650567)[Outlook_Warn.PNG](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=482&FileAttachmentId=1650958)

**Comment by phw198** [comment]
On *2017-03-25 23:16:42 UTC*, **phw198** commented:

Hi,
There is an 
entry in the FAQ for this - let me know if that helps?
On Outlook 2007 and newer, you can also choose "Outlook Options" > "Trust Center" > "Programmatic Access" and change the setting here to either "Warn...when antivirus is out of date" (preferable) or
 "Never warn".

**Comment by phw198** [comment]
On *2017-03-26 10:27:07 UTC*, **thebob6** commented:

Hi, 

I am running Outlook 2016 and have confirmed it is already set to "Warn...when antivirus is out of date" (preferable)"


The other options appear to be locked down via GPO but if needed I can get them unlocked.


Please see attached.

**Comment by phw198** [comment]
On *2017-03-26 14:07:20 UTC*, **phw198** commented:

Do you have OGCS set to start in start-up? Is it possible the anti virus isn't properly initialised? What if you manually start OGCS after several minutes having boot up and logged in?

**Comment by phw198** [comment]
On *2017-03-27 13:56:14 UTC*, **thebob6** commented:

Yes I do have both starting up at the same time.

It appears without rebooting starting the app after Outlook has opened gets rid of this problem.

I'll experiment a bit more.

Great suggestion - Thanks

**Comment by phw198** [comment]
v2.6 offers the option to delay startup for OGCS. Also security popup won't happen in v2.6.1 if you're not syncing meeting attendees.

**Comment by SteffenS77** [comment]
I habe the  same problem with outlook 365 after reboot, but i cant set the options.
Can you help me.

![image](https://user-images.githubusercontent.com/49787124/56426603-2d4cf200-62b9-11e9-8ed0-f9e804b3313f.png)

![image](https://user-images.githubusercontent.com/49787124/56426617-3b9b0e00-62b9-11e9-9237-8839a05789c8.png)

best regard
SteffenS
