### ISSUE TITLE
Application Unexpectedly Terminated

### ISSUE THREAD

**Issue by justinkarmann** [phw198/OutlookGoogleCalendarSync#640]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\
<img width="960" alt="screenshot 2018-12-06 12 00 31" src="https://user-images.githubusercontent.com/45667233/49599653-8130ed00-f94f-11e8-98c9-98c77aec024a.png">

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by justinkarmann** [comment]
This is what I get everytime I attempt to install this on my new laptop. No issues in the past.

**Comment by phw198** [comment]
A regression bug - same as #455
I've now rebuilt and re-released v2.7.7...

**Comment by justinkarmann** [comment]
Thank you, Paul!

I love your software

Justin Karmann
Associate Pastor of Youth, Family, and Social Justice
First Presbyterian Church of Metuchen
402.661.0784
