### ISSUE TITLE
No default calender when setting-up

### ISSUE THREAD

**Issue by fredan66** [phw198/OutlookGoogleCalendarSync#641]
**OGCS Version**: v2.7.7.0  
**Installed or Portable**: Installed

**Problem Description**  
I'm setting-up the outlook calender on a new computer and when I intalled OGCS it selected a mail address that I had in Outlook but this was not the default account as set-up in Outlook and the default mail accont did not pop-up as an alternative in the dropdown either. To make sure OGCS did not try to selct this mail account again I delete the mail account from Outlook and reintalled OGCS but then the default mailbox was empty and there are no other mailboxes in the dropdown. I used OGCS on my old computer using the same mail account without any issues. I have double checked that the mail address is set to defult in outlook and I have uninstalled and reinstalled OGCS. 

I would reallt appriciate your help

**Comment by phw198** [comment]
Were you using v2.7.7 on the old computer? If not, does the version you were using detect the default calendar on the new computer?

What is the account you are setting up in Outlook? How is it configured (local, IMAP, POP3, Exchange, etc)?

:spiral_notepad: Would also help to see your `OGcalsync.log` file in case there are errors captured in there ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
