### ISSUE TITLE
Unable to authenticate with Google. The following error occurred: Unexpected character encountered while parsing value: <. 

### ISSUE THREAD

**Issue by gpapp** [phw198/OutlookGoogleCalendarSync#642]
**OGCS Version**: v2.7.7.0  
**Installed or Portable**: Portable

**Problem Description**  
Using Chrome as the default user, synchronization doesn't work.

**Steps to Reproduce the Issue**  
1. Try to update
1. Allow permission in Chrome browser
1. Receive error
> 
> Authenticating with Google
> 
> Unable to authenticate with Google. The following error occurred:
> Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Any other information**  
I'm using OGCS in a restricted environment. Internet Explorer and Edge are not available (starting last week) The default browser is Chrome.

**Comment by phw198** [comment]
Sounds maybe more like a proxy problem? Are you using one? When did the problem start?

:spiral_notepad: Can you upload your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))?

**Comment by gpapp** [comment]
I cannot use the custom proxy settings to change the user agent string, as the web application firewall doesn't use username/password, but security token based authentication.
