### ISSUE TITLE
Google Chrome Stuck Downloading Proxy Script

### ISSUE THREAD

**Issue by JoeyDeeee** [phw198/OutlookGoogleCalendarSync#644]
https://gist.github.com/JoeyDeeee/92fe53aff54b90a19ee5bd12db00257c

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
When Outlook Google Calendar Sync is set to start automatically, Google Chrome is unusable until reboot.  Chrome gets stuck with "Downloading proxy script..." message.

**Steps to Reproduce the Issue**  
1. Check option to start on login
2. Boot up machine
3. Open Google Chrome

**Comment by JoeyDeeee** [comment]
Also note that I've downloaded the Alpha release and was able to reproduce in that version as well.

**Comment by phw198** [comment]
Does adding a delay to the start of OGCS help?

This page also explains [how to resolve the issue](https://www.jdhodges.com/blog/chrome-downloading-proxy-script-solved/). Are you _sure_ OGCS is causing this behaviour? Ie. if you don't start OGCS on startup, the `Automatically detect settings` box doesn't get checked, but it does if you do start OGCS on startup?

**Comment by JoeyDeeee** [comment]
Hi Paul.
First off, thanks for the reply.  I've been doing some testing, trying to isolate the issue.  In regards to the Automatic configuration settings, I'm on a corporate machine that uses an automatic configuration script with a specific address.  Automatically detect settings is not checked.  A couple things that I've tried:
1. Set OGCS to max start delay, issue was still present
2. Set OGCS to not start at all upon boot, issue was still present
3. Uninstalled OGCS completely, issue resolved.

**Comment by darehosa** [comment]
Wait, I was just wondering why LAN Settings from Internet explorer are located in Chrome settings?
Google should make its own in-built settings to turn on or off proxy, like we have many extensions present for that. [Hows.Tech](https://www.hows.tech/2019/06/fix-chrome-downloading-proxy-script.html) has pointed out precisely at Automatic Updating of Proxy and DNS

**Comment by JoeyDeeee** [comment]
Update - I am no longer seeing this issue with the latest release from Microsoft.  For me, it seemed the real culprit was that while connected via LAN the WLAN would flicker on and off, trying to connect, causing Chrome to not be able to get a stable connection.  I still do not know what was causing this issue.
