### ISSUE TITLE
Gmail is getting meeting accept/decline emails from the .ogcs addresses of the attendees

### ISSUE THREAD

**Issue by gsemel** [phw198/OutlookGoogleCalendarSync#647]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: ? not at work right now, but I'm sure it's a recent version 
**Installed or Portable**: Installed

**Problem Description**  
Starting a few days ago, my gmail is getting meeting accept/decline emails from the .ogcs addresses of the attendees.  I don't recall seeing this behavior before.  I prefer to sync attendees so I can see who's in the meeting on my non-work phone's Google Calendar.  Thanks for the great software!

**Steps to Reproduce the Issue**  

**Any other information**

**Comment by phw198** [comment]
The `.ogcs` emails aren't real, so I don't think you can be getting accept/decline emails from them. More likely you are getting undeliverable responses to your invitations or your attendance responses to meeting organiser by another?

See the wiki for [information on what the `.ogcs` feature is for](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google) - I strongly suspect OGCS is protecting you in exactly the way it was designed.

**Comment by gsemel** [comment]
Thanks for the reply.  I'm not sure that I understand your reply.  Do the attached screenshots from gmail help explain what I'm seeing?  Note that this particular meeting request was not created/organized by me, I'm just an invitee.  Thanks!

<img width="568" alt="screen shot 2018-12-29 at 1 02 54 am" src="https://user-images.githubusercontent.com/22755248/50534153-bf609d00-0b06-11e9-8fa1-4e2e3cb3b267.png">
<img width="578" alt="screen shot 2018-12-29 at 1 06 40 am" src="https://user-images.githubusercontent.com/22755248/50534156-c5567e00-0b06-11e9-8c59-8ed3842792a1.png">

**Comment by phw198** [comment]
So given the attendee to the Event has an email address ending `.ogcs` then this can't be a legitimate response from the attendee. If you go to the settings of the web view for the Google calendar being synced to by OGCS, what are your notification settings?
![image](https://user-images.githubusercontent.com/11843015/50542468-df9b6500-0bb5-11e9-814f-203989bf6319.png)

**Comment by gsemel** [comment]
Event Responses was set to Email, so I set it to None.  I'll let you know if the unexpected emails continue.  Thanks for the help!  Happy new year!
