### ISSUE TITLE
my sync will not add entries from my google acct in to the outlook on my desktop.  

### ISSUE THREAD

**Issue by TheMexican5757** [phw198/OutlookGoogleCalendarSync#648]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
You've not provided any of the requested information, not least the version of OGCS you are using or the `OGcalsync.log` file...

**Comment by inorv9** [comment]
i think i have a similar issue, put details in my ticket (issue #649), thanks
