### ISSUE TITLE
Dropping email address extension

### ISSUE THREAD

**Issue by jeffwash** [phw198/OutlookGoogleCalendarSync#650]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.7.0  
**Installed or Portable**: Installed

**Problem Description**  
When I sync from Google to Outlook, it is chopping the email addresses.  For example, in google the email address is `wjeff@deepiq.co`.  When brought into Outlook it becomes `<wjeff@deepiq>`.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.7.7.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2806033/v2.7.7.13.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by jeffwash** [comment]
Hi Paul,

Thanks for this! I’ve installed the update, is there a test I can run?

Thanks,
-Jeff
