### ISSUE TITLE
outlook 2019 not downloading from google, when ??

### ISSUE THREAD

**Issue by mstumpf123** [phw198/OutlookGoogleCalendarSync#651]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0 installed

**Problem Description**  
when will it support outlook 2019?

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by mstumpf123** [comment]
forgot to say, also tried 2.7.7 alpha, same result.

**Comment by phw198** [comment]
What's the evidence (e.g. OGcalsync.log file or error message) that it doesn't already? You had OGCS working previously on Outlook 2016 did you?

:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
