### ISSUE TITLE
O->G: Missing Exclusions on Recurring Events

### ISSUE THREAD

**Issue by radreza** [phw198/OutlookGoogleCalendarSync#652]
**OGCS Version**: v2.7.0.0 
**Installed or Portable**: Installed

**Problem Description**  
\<I am syncing from Outlook to Google, one way. I am excluding the category "Not Attending", however on recurring events, it still syncs them even when they are categorized as "Not Attending">

**Any other information**  
\<I am new, so let me know what is needed if anymore info is needed
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2752707/OGcalsync.log)
>

**Comment by radreza** [comment]
Actually tried that a little after posting and same issue

**Comment by phw198** [comment]
What type of recurring item are you seeing synced despite it having an excluded category?
* Type: Yearly, Monthly, Weekly, Daily
* Starting date:

📔 Date range you are syncing: past 1 days, future 60 days

If you turn on `Create CSV files` under `Application Behaviour` > `Logging`, after running a sync, open the `outlook_appointments.csv` file in the same directory as `ogcalsync.log` - does it include the recurring item with the "Not Attending" category?

If it doesn't, if you delete the item in Google, does OGCS recreate it on the next sync?

**Comment by radreza** [comment]
If I start a brand new recurring event or get invited to a new one, it’s fine, but when I take an existing recurring event and apply a category to not sync, it still syncs it

**Comment by phw198** [comment]
I had edited my previous posting with further questions and suggestions - could you take a look?

Also, if you receive an invite to a recurring series, how can that be fine as it won't have your category yet to exclude it from sync? Basically I can't replicate this issue at all, so will need some very clear instructions to reproduce it. E.g. even how you are adding the category - assigning it within the calendar view or opening the recurring series, adding the category, saving and closing...?
