### ISSUE TITLE
Two or more calendar

### ISSUE THREAD

**Issue by Abby74656** [phw198/OutlookGoogleCalendarSync#653]
Hi, I have two calendars on the Google - Personal and Family and I need sync both but it is not possible, I can only choose one. I need to have both calendars separate, the category does not solve it. I need sync Personal from Google to Personal in Outlook and Family in Google to Family in Outlook. Thank you.

**Comment by fogoat** [comment]
Did you see this option? https://github.com/phw198/OutlookGoogleCalendarSync/issues/165 -- the instructions are a little technical, but I was able to follow the last part about having a portable installation.

I made a blog post here about it:
https://discontinuo.us/use-outlook-google-calendar-sync-ogcs-and-sync-multiple-google-calendars-to-outlook/

**Comment by phw198** [comment]
Thanks @sunk818 - yes #165 is the current solution for multiple calendars. Nice blog post too 🙂
