### ISSUE TITLE
Declined GC meeting is created in Outlook

### ISSUE THREAD

**Issue by fogoat** [phw198/OutlookGoogleCalendarSync#654]
**OGCS Version**: v2.7.7-alpha
**Installed or Portable**: Portable

**Problem Description**  

Someone invited me to lunch. I declined the invite due to conflict. Google Calendar doesn't show the entry any more unless I check on `Show Declined Events`. I think my expectation is if declined events by default are not shown, it should same behavior as deleting the event.

![image](https://user-images.githubusercontent.com/6989799/51230108-bf88d700-1913-11e9-82de-068f733e21bf.png)

Even I though I declined the event in GC, it is still syncing to Outlook (one-way Google -> Outlook)

**Steps to Reproduce the Issue**  

Not sure, but I think if you create an invite from someone else, sync the invite to Outlook (with Attendees checked in Sync Options), then decline it via the invitation that Google sends you via e-mail. When you decline, the entry should disappear from Google, but the Google -> Outlook will display the invite.

**Any other information**  

Google e-mail and Outlook e-mail are different if that matters.

Google Calendar - detailed, I declined

![image](https://user-images.githubusercontent.com/6989799/51230454-e1cf2480-1914-11e9-8148-e4d306dbc850.png)

Outlook - organizer shows no response, my decline was not synced.

![image](https://user-images.githubusercontent.com/6989799/51230398-ae8c9580-1914-11e9-9b9d-9acb928f6efe.png)

**Comment by hibaa9** [comment]
I am using OGCS to sync room resource calendars, so declined events syncing to outlook is causing a bit of an issue (the room gets unnecessarily blocked for that period on the outlook side). Is there a workaround for this issue yet?

**Comment by phw198** [comment]
:package: This should now be possible with [development build v2.8.5.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5506830/v2.8.5.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

On the `Settings` > `Google` tab: "Exclude invitations I have declined"

Please let me know how it goes.

**Comment by hibaa9** [comment]
Thanks a lot! It seems to be working perfectly.
