### ISSUE TITLE
A program is trying to access Outlook

### ISSUE THREAD

**Issue by georgekatt** [phw198/OutlookGoogleCalendarSync#660]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Portable

**Problem Description**  
My Outlook keeps saying "A program is trying to access Outlook" every time it syncs and it requests permission to "allow".  If I am sitting in front of the computer, great but I work remotely often and this is not always possible.  Is there any way to prevent this from occurring?  I read the wiki at https://github.com/phw198/OutlookGoogleCalendarSync/issues/451 but  I do not have admin access on this machine and that option is grayed out.  Thanks!

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Hi, currently the advice in the wiki is your best bet - set to "Warn when antivirus definitions are out of date" and make sure your definitions are kept up to date, then you shouldn't have a problem with popups...

However, it does appear I might be able to circumvent the issue with registry changes - something I will try and experiment with:
https://www.ryadel.com/en/how-to-stop-the-outlook-a-program-is-trying-to-access-pop-up/

**Comment by guitaradam2000** [comment]
I'm also getting this message, literally every time my computer starts, or I open Outlook...or Outlook has been running more than 5 minutes.

Windows Group Policy allows the configuration of trusted add-ins, which should stop this message. It needs two parameters to configure; a DLL filename to use for the "value name", and the "Hash result" for the "Value". Could you assist in pointing me to where the DLL file is for your application? Not sure what to put for the hash result, any ideas?

**Comment by gorstj** [comment]
I've been running for a few days and this message has suddenly started. Very annoying!

Can't change the Trust settings as not got admin access. 

Can't change the Local_Machine registry settings as in phw198 link above.

Changing the current_user registry settings as above doesn't work sadly.

**Comment by phw198** [comment]
Unfortunately, on closer review, those registry keys appear to be related to managing security settings in a corporate Exchange environment, either by Exchange Public Folders or GPO. Basically, it's not a workaround for OGCS :-1: 

Advice is still to make sure you have anti-virus with up to date definitions in order to stop the Outlook security popups.
