### ISSUE TITLE
Google Calendar Login Keeps Resetting

### ISSUE THREAD

**Issue by gelobter** [phw198/OutlookGoogleCalendarSync#661]
:memo: Use the below template to report your issue.  
d  

----

**OGCS Version**: v2.7.7.0 
**Installed or Portable**: Portable

**Problem Description**  
\The program regularly "forgets" the google calendar for which it is authorized, reverting to another email account.  I am using 3 instances of OGCS in different folders with "Portable" set. This didn't start happening until I upgraded to 2.7.7

**Steps to Reproduce the Issue**  
1. \set the correct google calendar for syncing.
2. Reboot.
3. All sync settings default to only one email account.

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
What version of OGCS did you upgrade from before v2.7.7?

The Google Calendar in the Settings dropdown is sourced from the `settings.xml` file, and there is only normally that one entry shown in the dropdown unless you have clicked "Retrieve calendars". 

So assuming after you've reboot, you only have one item in the dropdown and it's the wrong one, this must mean OGCS is starting up against the wrong `settings.xml` file. Check the `About` tab to see the value for "Config In".

Are you invoking OGCS with command line parameters or somehow else?
