### ISSUE TITLE
Not-accepted Outlook meetings show up in Google, cause reminders

### ISSUE THREAD

**Issue by sweavo** [phw198/OutlookGoogleCalendarSync#662]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
not-accepted outlook meetings show up in google, cause reminders

Result: I get a reminder for a morning meeting and assume I must have accepted it, even though I wasn't invited to it until after office hours. I would have been much better off just not attending.

**Steps to Reproduce the Issue**  
1. Set up O-G sync such that you get an automatic reminders (I think this is via a default in google)
2. Invite the Outlook calendar to a meeting, buit don't accept it
3. Sync. The appointment shows up in google, complete with reminder.

**Any other information**  
It would be great to find a checkbox under the settings saying "only sync accepted meetings"

**Comment by phw198** [comment]
Is "not accepting the meeting" the same as "not responding to the invite", or do you mean it's syncing rejected meetings? 

For only syncing invites that have been responded to, that option was added in v2.7.2...

**Comment by sweavo** [comment]
Thanks for the quick reply! 

I'm talking about "not responded to invite" meetings.

Oh wow, I will update and feed back. Thanks, I just cloned the source today but haven't made time to go spelunking.

**Comment by sweavo** [comment]
Sorry, I didn't feed back, but the 2.7.2 update did indeed fix the issue. Great work, thanks!
