### ISSUE TITLE
Accepted invites in Outlook don't appear accepted on mobile

### ISSUE THREAD

**Issue by paigetcampbell** [phw198/OutlookGoogleCalendarSync#664]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.7.0
**Installed or Portable**: Installed

**Problem Description**  
\<When I accept an invite in Outlook 2013, it doesn't register as accepted in gmail nor on my mobile (Apple iPhone X, latest version iOS. The organizer(s) in my case are gmail users. Not sure if this is OGCS related but I thought to ask. >

**Steps to Reproduce the Issue**  
1. \<Recieve invite via outlook>
2. \<Accept invite via outlook >
3. \<No accept on gmail or iphone>

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
So a gmail user organising a meeting and invites you to it - is that invite sent to your gmail account or some other work/Exchange email address?
You then accept the invite in Outlook and after OGCS runs the next sync you're saying your acceptance isn't synced?

I'm assume you're syncing attendees? You would need to sync attendees as OGCS has to make you the organiser of the Google item (as you own the calendar), but it will also add you as an attendee if you are not the organiser in Outlook. This is where it will show if you have accepted or not:
![image](https://user-images.githubusercontent.com/11843015/54648438-26ef0e80-4a9e-11e9-8ab7-2206f0c237ee.png)

Do you have the `Verbose` option checked in OGCS? Does this show attendee responses being synced?

**Comment by paigetcampbell** [comment]
Good morning, 

So a gmail user organising a meeting and invites you to it - is that invite sent to your gmail account or some other work/Exchange email address?
You then accept the invite in Outlook and after OGCS runs the next sync you're saying your acceptance isn't synced?

That invite is sent to my gmail account. If I accept the invite in Outlook, it doesn’t show in gmail portal (web browser) or on my mobile that I have accepted. I am also getting double meetings in gmail now, please see below screenshot



 



 

I'm assume you're syncing attendees? You would need to sync attendees as OGCS has to make you the organiser of the Google item (as you own the calendar), but it will also add you as an attendee if you are not the organiser in Outlook. This is where it will show if you have accepted or not:
 <https://user-images.githubusercontent.com/11843015/54648438-26ef0e80-4a9e-11e9-8ab7-2206f0c237ee.png> 

 

I am syncing attendees in OGCS. 



Do you have the Verbose option checked in OGCS? Does this show attendee responses being synced?

I do have this clicked but it doesn’t show attendee responses being synced. 

 



 

 

	

  <http://www.spiresolar.com/manual-files/email-signature-2017/SP-ES-header17.png> 

	


Paige T. Campbell
Director - Business Development

  <http://www.spiresolar.com/manual-files/email-signature-2017/house17.png> 

 <https://maps.google.com/maps?q=eternal+sun+delft&hl=nl&sll=37.0625,-95.677068&sspn=58.946508,135.263672&hq=eternal+sun&hnear=Delft,+Zuid-Holland,+Nederland&t=m&z=14&iwloc=A> Eternal Sun / Spire Solar
Wolga 11
2491BK The Hague
The Netherlands

LinkedIN <https://www.linkedin.com/in/paige-t-campbell-427b5738/> 
  <http://www.spiresolar.com/manual-files/email-signature-2017/phone17.png> 
+31 6 18 18 20 55

pcampbell@eternalsun.com <mailto:pcampbell@eternalsun.com> 
  <http://www.spiresolar.com/manual-files/email-signature-2017/web17.png> 
 <http://www.spiresolar.com/> www.spiresolar.com / www.eternalsun.com <http://www.eternalsun.com/>

**Comment by phw198** [comment]
I'm struggling to understand your setup, but it sounds like you have Outlook configured to connect to your Google account and then you are _also_ using OGCS to sync from Outlook to Google. I'm not sure why you would want to do this, but if you also have the "merge" option checked, then I wouldn't be surprised about duplicates in your calendar. 

> If I accept the invite in Outlook, it doesn’t show in gmail portal  

Against which entry in Google? You said you have duplicates. I think perhaps your confused as to what OGCS is for - it's intended for people that use Outlook to connect to a non-Google account and then sync the calendar entries associated with that into Google.

Perhaps close down OGCS and then see what the behaviour of Google invitations is afterwards. If you receive a meeting invite for Gmail in Outlook and that also shows in Google calendar, then I don't think you need OGCS. If you then also accept the meeting invite in Outlook and it doesn't show as accepted in Google afterwards, that's nothing to do with OGCS...

BTW, I also can't see the screenshot you provided as attachments aren't allowed via email updates to GitHub.

**Comment by paigetcampbell** [comment]
Hi Paul, 

Indeed, I am using outlook to connect to my Google account. I am using OGCS to sync my calendar between Outlook and Google. The reason I use OGCS is that my outlook does not sync to my google automatically (I understood that was the whole purpose of OCGS?) 

I think we are onto something with the merge option. This is likely the cause of the duplicates, I’ve unchecked this. 

I’ll give it a shot running without OGCS, but I downloaded it because my calendar wasn’t syncing without it. 

Thx for your help so far!

**Comment by phw198** [comment]
No, don't turn off merge - that'll likely just want to delete the original calendar items!

So I think I'm clearer on what's going on. Have you set up Outlook to connect to Google via SMTP or IMAP? If so, these protocols don't support calendar sync - but OGCS doesn't "augment" these protocols in that sense. It is simply "copying" a calendar in Outlook (almost certainly should not be a Google calendar) into Google.

So I think the closest you could get with OGCS is to:
1. Create a new calendar within your Google account, eg "OGCS Cal"
1. Configure OGCS to sync to this new calendar

This will put the "duplicates" into their own calendar as distinct from the original calendar you current have configured.

But suffice it to say, I'm pretty sure you have misunderstood what OGCS is intended for and your current configuration will result in unexpected results!
