### ISSUE TITLE
Reschduled outlook appointment deleted from outlook

### ISSUE THREAD

**Issue by LilyEssence** [phw198/OutlookGoogleCalendarSync#665]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I accepted a outlook appointment for 2:30pm 2/8. This was declined and rescheduled to 2/11, and then again to 2/13. When I accept the 2/13 3:30pm appointment, it appears on my outlook calender. Then when my scheduled sync arrives, it deletes it from my outlook calendar.
I go into my trash and accept the outlook invite for the (twice-rescheduled) 2/13 3:30 appointment. Then I manually sync, and it deletes the appointment in my outlook calendar. 

**Steps to Reproduce the Issue**  
1. Accept calendar invite (that has been twice rescheduled)
1b. See that outlook appointment has been made
2. Manually sync
3. Observe that the new calendar invite that had once been on Outlook is now gone. 

Did that twice just to make sure. 

**Any other information**  
Checked the OGcalsync.log and found it did delete the appointment purposefully. The event is "Linda/Tianyu 1:1"
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2862428/OGcalsync.log)

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to the latest release, [v2.7.8.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.7.8-alpha/Setup.exe) and confirm if you can still replicate the issue.

I suspect the issue may remain as the rescheduling you describe happened whilst an earlier version of OGCS was installed. To resolve that, try [following the instructions here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-calendar-sync-with-full-sync).
