### ISSUE TITLE
color changes google appointments

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#670]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here> After syncing with OCGS the colors in passed appointments in Google change back to the default color.

**Steps to Reproduce the Issue**  
1. \<Update>
1. After I noticed this issue I disabled OCGA for more than 1 week. Today I enabled the syncing and the issue became obvious again. I am attaching screen shots from Before and After.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2896881/OGcalsync.log)
![before](https://user-images.githubusercontent.com/47920949/53287717-60518a00-373d-11e9-8d80-8432750d6d10.png)
![after](https://user-images.githubusercontent.com/47920949/53287718-634c7a80-373d-11e9-84da-c185195db65a.png)

**Any other information**  
\<Update here>

**Comment by WarningU2** [comment]
I have seen the same behavior with recurring calendar events.   I have sent them to be a banana color in Google Calendar and a different color in Outlook but when OGCS runs ... sometimes it changes them to default    Here is a log file 
[OGcalsync.log.2019-04-11.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3077029/OGcalsync.log.2019-04-11.txt)

**Comment by phw198** [comment]
Lot of changes over the last year on how OGCS manages categories/colours.
