### ISSUE TITLE
Unable to add new entries into the Google Calendar. Google.Apis.Requests.RequestError - Precondition Failed [412]

### ISSUE THREAD

**Issue by sumnercommajohn** [phw198/OutlookGoogleCalendarSync#672]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.7
**Installed or Portable**: Portable

**Problem Description**  
Starting about a week ago, OGCS is no longer able to successfully sync Outlook -> Google, and gets the same error each time: 

Google.Apis.Requests.RequestError Precondition Failed [412] Errors [ Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]

Have tried with Outlook 2016 on Windows 7 and Windows 10, portable versions of OGCS 2.7.7 and 2.7.0, each with fresh configurations - same result every time.  

\<Update here> 

**Steps to Reproduce the Issue**  
1. Configure fresh copy of portable OGCS
2. Connect to Google Account, Retrieve Calendars - no problem
3. Attempt sync, get error.

**Any other information**

**Comment by brozono** [comment]
You might want to check out the [Hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/646#issuecomment-460900668) that handles Google deprecating the Google+ APIs. Not sure that is you issue, but something to try.

**Comment by ericgol** [comment]
Saw this which may be related, as I also hit this. Not sure if there was a change between PATCH and UPDATE of late in the gSuite APIs?? https://stackoverflow.com/questions/18380942/drive-api-files-patch-method-fails-with-precondition-failed-conditionnotmet

**Comment by sumnercommajohn** [comment]
thanks @brozono for the suggestion, it didn't seem to fix it though.

**Comment by phw198** [comment]
@sumnercommajohn If you still encounter this issue, please provide your logfiles over on #528
