### ISSUE TITLE
Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).>

### ISSUE THREAD

**Issue by rabbieric** [phw198/OutlookGoogleCalendarSync#676]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<After an update from MS Office 365, all of the sudden I'm receiving this error message. I see someone else had the same problem but the ticket was closed after their request. I find no solution to this problem, please open a new ticket. thank you 
[outlook google sync error.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2949498/outlook.google.sync.error.txt)
>

**Comment by GoRingo-cz** [comment]
Hi, I have the same issue after update :-( Tried beta, alpha .. nothing works

OGCS Version: v.2.7.7.
Installed or Portable: Portable

Problem Description
 (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2973782/OGcalsync.log)


Any other information:
Office 365 MSO (16.0.10730.20264) 32bit

**Comment by GoRingo-cz** [comment]
I managed to correct this issue by "repair" Office 365 option in Program and Functions menu as suggested by somebody on internet in connection to error 0x80029C4A. Office update mess up something.

**Comment by rabbieric** [comment]
Thank you very much I will try this!!!

**Comment by phw198** [comment]
Fix as documented in the wiki: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary
