### ISSUE TITLE
Outlook does not appear to be installed error

### ISSUE THREAD

**Issue by sexinxs** [phw198/OutlookGoogleCalendarSync#679]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.7-alpha 
**Installed or Portable**: Installed

**Problem Description**  
As per post title, OGCS won't start soon after install arguing that Outlook is not installed... but it is and works perfectly

**Steps to Reproduce the Issue**  
Simply install and run it

**Any other information**  
Running last release of Windows 10 Pro and Outlook modern app... both running fine... same install on a different pc and everything goes smooth

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2975059/OGcalsync.log)

**Comment by phw198** [comment]
If you haven't managed to resolve this yet, please upgrade to OGCS v2.7.9 and then a apply the below fix

:package: ~~[Hotfix v2.7.9.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3195110/v2.7.9.2.zip)~~ ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by phw198** [comment]
:package: Further changes now in [Hotfix v2.7.9.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3195279/v2.7.9.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.
