### ISSUE TITLE
Changed Dates won't get recognised by OGCS and therefor not updated

### ISSUE THREAD

**Issue by theOne-Phil** [phw198/OutlookGoogleCalendarSync#680]
**OGCS Version:** v2.7.0.0
**Installed or Portable:** Installed

**Problem Description**
Some events won't get created or deleted.

**Steps to Reproduce the Issue:**
Well for now it seems pretty random.. the only pattern I can see is the subject recurring (It's a my students calender).
My guess:
- create event
- move it to a different date (theres the magic)
- somehow doesn't get updated

My Work/Syncflow:
![Syncflow](https://user-images.githubusercontent.com/45015159/54491859-02d6d600-48c2-11e9-8d92-c524ea40ca28.png)
--
Google:
![image](https://user-images.githubusercontent.com/45015159/54491057-a2449a80-48bb-11e9-96c1-85e194b5320f.png)
--
Outlook:
![image](https://user-images.githubusercontent.com/45015159/54491145-57775280-48bc-11e9-8e15-d1f1f6bdbd40.png)
--

**Files:**
I set it the log to: All since there wasn't any useful information included at Debug-level
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2975309/OGcalsync.log)

Google & Outlook events from the .csv file - the dates 20.3 and 22.3 are marked
[OGCS-calenderevents.xlsx](https://github.com/phw198/OutlookGoogleCalendarSync/files/2975312/OGCS-calenderevents.xlsx)

**Comment by theOne-Phil** [comment]
update: I have just seen the Shift + Sync function, and tried it.
It updated 2 attributes and 73 entries...
It seems that It has worked. I keep you updated through the next week.

**Comment by draeburn** [comment]
I've got the same issue, but what is Shift + Sync function? I've not seen that?

**Comment by theOne-Phil** [comment]
> I've got the same issue, but what is Shift + Sync function? I've not seen that?

The way I understood it, it's an advanced syncing option. Pressing shift whilst clicking on Sync. It bypasses the Attributes defined at Settings>Sync Options>What and syncs every attribute.

The cool thing, it prints all changed attributes and you can easily trace it. The Downpart, it overwrites the attributes I have later changed in Google e.g.: Color.

---
With this option, it updated the events that got moved from Friday to Wednesday, that wen't under the radar with the normal syncing option.

**Comment by draeburn** [comment]
Thanks for the speedy reply Phil, I'll give that a go!

**Comment by phw198** [comment]
Thanks for raising the issue. However, the advice is always to upgrade to the latest alpha to see if the issue can still be replicated before reporting. This issue should have been fixed quite some time back in v2.7.3 I believe.

The website [user guide](https://phw198.github.io/OutlookGoogleCalendarSync/guide/sync) explains the `Shift+Sync` option - it performs a full sync instead of a delta sync - and yes, would work around the bug you described.
