### ISSUE TITLE
Major sync errors, now and some items *refuse* to sync....but seems random which ones.

### ISSUE THREAD

**Issue by draeburn** [phw198/OutlookGoogleCalendarSync#681]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file
----

**OGCS Version**: v2.7.7.0
**Installed or Portable**: Installed

**Problem Description**  
3 main issues:
1: Sync is incredibly slow with Alpha release, I'm talking about 10 minutes a time. In beta version it takes less than a minute.
2. Multiple "Object reference not set to an instance of an object"
3. Failed sync on some items, no idea why.....even if I delete and re-create will not replicate. Seems to be something to do with the actual date! The objects failing to replicate are on 18/19 May 2019 and it doesn't work either way.

**Steps to Reproduce the Issue**  
Just normal use, and sync

**Any other information**  
I have tried to uninstall and re-install OGCS. I've tried to create a new calendar in Google and replicating fresh to that, and same items still fail to replicate. I've tried deleting and re-creating the outlook entries with errors, and it still occurs. 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2978027/OGcalsync.log)

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to the latest release, [v2.7.8.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.7.8-alpha/Setup.exe) and confirm if you can still replicate the issue. If you can, please re-upload your logfile.

**Comment by heshie75v** [comment]
It's been an hour since booting up my PC and the last syn. Has not automatically synced since. I am using version 2.7.8.
The beta version the other day had major problems with properly syncing ( many items not synced. )
Is there a fix out there, still love the product.

**Comment by phw198** [comment]
@heshie75v A fix for what exactly? Please also post your OGcalsync.log file.

**Comment by heshie75v** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3031426/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3031433/OGcalsync.log)

**Comment by heshie75v** [comment]
OGcalsync will only sync on boot up.

**Comment by heshie75v** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3040089/OGcalsync.log)

only syncs on boot up

**Comment by heshie75v** [comment]
OGcalsynch is still trying to delete certain appointments, I did try your posted fix as well

**Comment by phw198** [comment]
@heshie75v is a time waster, posting here, #698 and #707 never responding to anything.
