### ISSUE TITLE
Exception window is shown which cannot be closed

### ISSUE THREAD

**Issue by drolevar** [phw198/OutlookGoogleCalendarSync#682]
----

**OGCS Version**: v2.7.7.0
**Installed or Portable**: Installed

**Problem Description**  
Almost every day when I come back from home to my work laptop, I see the exception window, where clicking "OK" has no effect. Clickin on the log button though opens the file. As a result I have to force close application from the task manager.

**Steps to Reproduce the Issue**  
Well, in my case it occurs by itself while I'm away.

**Any other information**  
Log file is attached.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2982350/OGcalsync.log)

**Comment by drolevar** [comment]
That's the whole log:

[OGcalsync.log.2019-03-18.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2982359/OGcalsync.log.2019-03-18.txt)

**Comment by joaosilvapl** [comment]
Hi drolevar,

Does the application crash after the laptop is idle for a long time? Is it hibernated/sleeping then resumed?

Just for reference, can you include a screenshot of the Exception window, showing the details?

/Joao

**Comment by phw198** [comment]
The application isn't crashing. What I suspect might be happening is:
1. A sync occurs which logs an error and shows the "Error Encountered" window. This window isn't responded to.
1. A scheduled sync then occurs and the sync fails, asking the user if they want to try again. This questions pops up _behind_ the first window.

However, when simulating this happening, the entire Error Encountered screen is "frozen" - the "Open Log" button doesn't work either.

@drolevar Next time this happens, if you hover the mouse over the OGCS icon in the task bar to get the window thumbnail previews, are there any previews of screens you can't actually see?

**Comment by phw198** [comment]
I think this is actually already fixed in development. The next alpha release is due very soon, so hopefully v2.8.1 will resolve this.

**Comment by ghost** [comment]
> The application isn't crashing. What I suspect might be happening is:
> 
> 1. A sync occurs which logs an error and shows the "Error Encountered" window. This window isn't responded to.
> 2. A scheduled sync then occurs and the sync fails, asking the user if they want to try again. This questions pops up _behind_ the first window.
> 
> However, when simulating this happening, the entire Error Encountered screen is "frozen" - the "Open Log" button doesn't work either.
> 
> @drolevar Next time this happens, if you hover the mouse over the OGCS icon in the task bar to get the window thumbnail previews, are there any previews of screens you can't actually see?

I hovered, only saw one window.. tried hitting the [x] in the task bar window that popped up but it didn't work..
