### ISSUE TITLE
Flooded with status notifications for meetings I'm not the organizer.

### ISSUE THREAD

**Issue by mikolajek** [phw198/OutlookGoogleCalendarSync#683]
I'm using OGCS v2.7.0.0. Portable with Outlook 2016 32-bit.

I think what I've been experiencing is not the issue, but rather an unwanted feature and I'd like to learn how to get rid of it.

My problem is that when I sync meeting invites sent by other people at my organization, I receive status updates (accepted / rejected / etc.) from all the participants, even though I'm not the meeting organizer. I know that in Google Calendar I need to be the organizer, but I'm surprised that responses to a meeting stored in Exchange calendar are delivered to me via Google Calendar (and all of those are sent from *.ogcs altered emails).

I can't find any option to turn those notifications off. Can you please advise how to do so?

**Comment by phw198** [comment]
Do you maybe have the following option set to "Email" within the Google calendar settings?

![image](https://user-images.githubusercontent.com/11843015/54644525-63683d80-4a91-11e9-99d6-1f8dda2f4fb4.png)

**Comment by mikolajek** [comment]
Thank you, @phw198 ! Indeed I have those enabled with "Email" selected.
So this is the source of my problems, isn't it? Do I understand correctly that this causes the flooding, as Google makes me the event organizer, instead of the organizer set in the original invite and Exchange calendar?

**Comment by phw198** [comment]
Yes, I believe so. Set the notifications to "None" for the calendar you are syncing to with OGCS and things should quieten down... :slightly_smiling_face:
