### ISSUE TITLE
Sync encountered a problem and did not complete successfully

### ISSUE THREAD

**Issue by JP3251** [phw198/OutlookGoogleCalendarSync#684]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2984871/OGcalsync.log)

**OGCS Version**: v2.7.8.0  
**Installed or Portable**: Portable

**Problem Description**  
Sync encountered a problem and did not complete successfully.

**Steps to Reproduce the Issue**  
1. Start Sync

**Any other information**  
After updating to the latest Alpha v2.7.8, it stopped syncing.
Also, now I get multiple pops up on outlook when program is launched
![2019-03-19_14h18_53](https://user-images.githubusercontent.com/48731166/54630878-372ccc80-4a51-11e9-9c8d-6c51d44a2716.png)

**Comment by phw198** [comment]
For the security pop-up, see [this wiki page](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) - essentially, make sure your AV definitions are up to date.

For the failure to sync, this looks to be specific to the Portable release - I'll investigate...

**Comment by phw198** [comment]
```
2019-03-19 13:49:13,346 WARN  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Could not load file or assembly 'Google.Apis, Version=1.32.1.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
2019-03-19 13:49:13,346 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Sync encountered a problem and did not complete successfully.
```
Actually, I can't replicate the error you were getting. I've downloaded v2.7.8 portable from the GitHub website, extracted it to a clean, new folder, run it and performed a sync - no issues.

Can you make sure you are extracting the zip to a brand new folder and try again? Looks like you original extracted it to a `Downloads` subfolder and then moved it to a DropBox synced folder?
