### ISSUE TITLE
Exceptions to recurring Outlook appointments not updated in Google

### ISSUE THREAD

**Issue by JBX111** [phw198/OutlookGoogleCalendarSync#685]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: Alpha v2.7.7.0  
**Installed or Portable**: Installed

**Problem Description**  
Exceptions to recurring Outlook appointments not updated in Google

**Steps to Reproduce the Issue**  
Recurring appointments created by others (these others always seem to be based in the USA, I am in UK) sync ok, except for the exceptions - for example, meetings this week when the USA daylight savings and UK daylight saings are not aligned are showing as I hour later than expected, and exceptions where the meeting owner has moved the meeting are still showing in their original timeslot.

**Any other information**  
\<Update here>
LOG
<script src="https://gist.github.com/JBX111/83252fa4f1387694714672b2a96deac5.js"></script>

**Comment by rfgetz** [comment]
I am having the same exact issue, but this is occurring with meetings created in the Mountain Time Zone, and I am in the Eastern Time Zone,  I've tried multiple Outlook/Google Sync programs and this is an issue with all of them, so far.

**Comment by phw198** [comment]
@JBX111 I'm not too clear on what exact issue is being reported. You seem to have confused exceptions in general with exceptions landing when DST differs (which is normally only a couple of weeks per year for US and UK). I think you are reporting a problem specifically with daylight saving, but could you confirm which of these you are reporting:

When the organiser is in a different timezone to the attendee, and arranges a recurring series:
1. Occurrences (ie not exceptions) that lands on a day when DST differs between organiser and attendee always show an hour out.
1. Exceptions never sync regardless of when they occur and DST.
1. Exceptions when DST differ never sync
1. Exceptions when DST differ do sync, but are an hour out.

For one of the exceptions that is wrong, could you open it in Google calendar web view and confirm whether a timezone is set for it?

**Comment by phw198** [comment]
@rfgetz I'm not sure you do have the same issue. @JBX111 appears to be reporting an issue specifically related to daylight saving, whereas you simply mention timezone problems within the same country (so I doubt is related to DST).

You've not said what version of OGCS you're running. If it's not the latest alpha, then your issue should already be fixed - you just need to upgrade.

**Comment by phw198** [comment]
:thought_balloon: For my info, it appears [this line](https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/src/OutlookGoogleCalendarSync/GoogleOgcs/GoogleCalendar.cs#L518) clears the timezone for all exceptions. Seems like a Google bug. However, subsequent syncs should repopulate the exception timezones.

**Comment by fivage** [comment]
I experience also issues with exceptions made in Outlook. The exceptions are not pushed to Google.
Use case: 
In outlook, create recurring appointment. 
Then delete some occurences. 
When synced, all occurences are sent to Google.

**Comment by phw198** [comment]
This ticket is a mess of random observations, covering timezones, daylight saving and now exceptions not syncing. So I'm closing it. Regarding the first two, 2.8.3 brought in enhancements that may well resolve related problems. 

@fivage For your issue, if the exceptions you deleted fall in the window you are syncing, then raise a new ticket and attach your `OGcalsync.log` file that shows you carrying out your use case. Note, Outlook can cache exceptions quite heavily and there may be a delay before OGCS syncs the deletions.
