### ISSUE TITLE
Google Handshake fails on portable v2.7.8.0

### ISSUE THREAD

**Issue by voster77hh** [phw198/OutlookGoogleCalendarSync#686]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.6.8 
**Installed or Portable**: Portable

**Problem Description**  
Hi Paul,

Looks like I get a Google handshake error as in #618 with the latest portable on pressing Retrieve Calendars. The Google page goes well but the result isn't picked up in IE or Chrome. 

Can't try to upgrade .NET Framework here as suggested. I'm on a mint Windows 10 Enterprise 64bit from a client and have no real alternatives. 

Going back to a manual copy & paste in ver 2.6.0.0 fails as well.
This points me to a 404 from Google.

Pls. find logs and screens attached.

Anything you or I can do here?

I would really appreciate if this portable could work in some way.
Nevertheless you'll find a donation in your Paypal. Your idea of a portable cal sync is indispensable for IT freelancers at clients.

Best regards
Volker

**Any other information**  
Google feedback

http://127.0.0.1:65140/authorize/?code=4/FAGs7yD0ULQbMflqp03yGTLfIH8Da5h_fvmeToXpeHrO83IQN81-baxp_gthDGQZQcrUIq7_5I3tinfTiFcNr9I&scope=email%20https://www.googleapis.com/auth/calendar%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=0&session_state=42b8b2c09dc3f51c24951fb67797c375a4528340..9265&prompt=consent

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2992241/OGcalsync.log)
[OGcalsync_copynpaste_ver2600.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2992271/OGcalsync_copynpaste_ver2600.log)
<img width="261" alt="OGCS_error" src="https://user-images.githubusercontent.com/36388060/54756216-0cc14780-4be8-11e9-90ea-b63d9b12ece3.PNG">
![OGCS_error_ver2600](https://user-images.githubusercontent.com/36388060/54756270-2c587000-4be8-11e9-9b76-171710346b44.png)

**Comment by phw198** [comment]
Hi @voster77hh and thanks for the donation 👍 

Unfortunately, the error you are getting on v2.7.8 is `Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig` or `An attempt was made to access a socket in a way forbidden by its access permissions`. [According to SO](https://stackoverflow.com/questions/4799651/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi), this sounds like you have a firewall or AV software blocking traffic - do you have any control over this? It seems it's even blocking OGCS checking if you're running the latest ZIP release, so it's not just the authorisation piece that is failing.

Are you also able to try starting OGCS as administrator to see if that helps at all?

**Comment by voster77hh** [comment]
Local Admin gives me a warning that OGCS and Outlook don't run both as local admins.

**Comment by voster77hh** [comment]
Works with setting Windows Firewall to accept OGCS port. THX

**Comment by JP3251** [comment]
I don't have a firewall access because this is a work computer and I am not an admin.  is there a workaround?

**Comment by phw198** [comment]
@JP3251 Firstly, are you sure you are getting the same error message? `An attempt was made to access a socket in a way forbidden by its access permissions`

If so, I guess you could run the through the authorisation process at home/on a PC where the firewall doesn't block traffic to localhost. After you have successfully authorised OGCS:
1. Go to OGCS `About` tab and double click the `Config In` value.
1. Windows Explorer opens and there'll be a file `Google.Apis.Auth.OAuth2.Responses.TokenResponse-user`
1. Make a copy of this and transfer it to your work PC
1. On your work PC, go to OGCS `About` tab and double click the `Config In` value.
1. Copy in the file you transfered.
1. Try and sync. (restart OGCS too perhaps).
