### ISSUE TITLE
Original diary entry deleted after sync

### ISSUE THREAD

**Issue by Omnimercador** [phw198/OutlookGoogleCalendarSync#688]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
--
**Installed or Portable**: Installed

**Problem Description**  
Newly created Outlook Calendar entry is synced to Google; in the same sync, the Outlook entry is then deleted. On the subsequent sync, the Google entry is then also deleted.

**Steps to Reproduce the Issue**  
n/a 
**Any other information**  
Outlook 2013.

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to the latest release, [v2.7.8.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.7.8-alpha/Setup.exe) - I believe this issue was resolved a long time ago.

**Comment by Omnimercador** [comment]
Indeed - that's sorted it. Was avoiding an "alpha" release ;-).
