### ISSUE TITLE
Unable to reclaim orphan calendar entries in Outlook calendar.

### ISSUE THREAD

**Issue by jeffwash** [phw198/OutlookGoogleCalendarSync#691]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

Sync version: 2.7.8.0

Sync started at 3/28/2019 9:04:50 AM

Syncing from 3/28/2018 to 3/28/2020

Outlook ← Google

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.

Finding Calendar Entries
Scanning Outlook calendar...

1127 Outlook calendar entries found.

Scanning Google calendar...
1127 Google calendar entries found.

22 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...
Outlook 1127, Google 1127
Checking for orphaned items...

Unable to reclaim orphan calendar entries in Outlook calendar.

Object reference not set to an instance of an object.

Operation aborted after 1 failed attempts!

**Comment by JonDBl** [comment]
I have the same issue. It just sits there with a action box:

The Syncronisation failed-check the sync tab for further details.
Do you want to try again? YES / NO.

I have two way sync but the sync seems to occur even if you haven't actioned the YES /NO box.
[OGCS.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/3035292/OGCS.pdf)

**Comment by kwagner115** [comment]
Running 2.7.8.0. Latest version of Outlook 365, Windows 10 latest version. 

I too experienced a similar issue yesterday when I did a drag / drop of an Outlook calendar item to a new date and time (earlier date). All subsequent sync attempts produced the same error **"Unable to reclaim orphan calendar entries in Outlook calendar. Object reference not set to an instance of an object**." message until I deleted the items from both Outlook and Google.

**Comment by ReddZen** [comment]
Funny you should mention the drag and drop. Because I dragged and dropped. I didn't piece it together but it might be the cause.

**Comment by phw198** [comment]
Thanks for reporting this guys, but as per the OP instructions, what I really need to investigate these bugs is the `OGcalsync.log` file. However, from the info available it looks the same as #689 so I'll troubleshoot over on that ticket.

@kwagner115 Thanks for the pointer on drag and drop - I'll take a look at that :+1:

**Comment by jeffwash** [comment]
PFA.

Thanks,
-Jeff
