### ISSUE TITLE
Synchronized items are attempted to be deleted in Google

### ISSUE THREAD

**Issue by ralfeus** [phw198/OutlookGoogleCalendarSync#694]
**OGCS Version**: v2.7.0
**Installed or Portable**: Portable

**Problem Description**  
On the synchronization OGCS tries to delete Google items though they have their counterparts in Outlook

**Steps to Reproduce the Issue**  
1. Just synchronization 

**Any other information**  
Log is here: https://gist.github.com/ralfeus/b9dd22f583cfaf7c093ebde155cf4b66

**Comment by phw198** [comment]
Upgrade to latest alpha and have a look at https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-calendar-sync-with-full-sync
