### ISSUE TITLE
Connection refused: localhost:61377

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#695]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>Connection refused: localhost:61377

**Steps to Reproduce the Issue**  
1. \<Update>
1. Trying to authorize Google Calendar access for Outlook Google Calendar Sync. When "Allow" is selected  the Connection refused: localhost:61377 message appears in browser, application hangs (use Task Manage to end). 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3025446/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Take a look here: https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#page-cannot-be-displayed-after-authorising-ogcs-to-access-my-calendar
