### ISSUE TITLE
Can't create items in Google

### ISSUE THREAD

**Issue by ralfeus** [phw198/OutlookGoogleCalendarSync#697]
**OGCS Version**: v2.7.8.0  
**Installed or Portable**: Portable

**Problem Description**  
On a new sync (first start) Outlook items can't be created in Google. Google items are created in Outlook without problems. The issue seems to be at Outlook communication side as E_ABORT is logged at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Organizer(). Probably it's caused by fact the Exchange mailbox is used and organizer's address are in X500 format (not SMTP address). Afterwards items are attempted to be deleted in Outlook if bi-directional sync is set.

**Steps to Reproduce the Issue**  
1. Start synching (manual or automatic)

**Any other information**  
Log is here: https://gist.github.com/ralfeus/a102fb544a1a5fdde0b3eadabb02bc8b

**Comment by ralfeus** [comment]
Interesting thing. On the dev host (cloned repo and started from VS) there are no issues with same appointment. Although dev machine runs Windows 2012 and machine with error runs Windows 10

**Comment by ralfeus** [comment]
Another interesting thing. On the dev comp I see in the log:
> 2019-04-02 09:23:12,374 FINE  11 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [617] -  Meeting organiser is someone else - checking their timezone.

That's what's logged right before calling pa.GetProperty(PR_ORGANISER_TIMEZONE). I expected to see same entry in the log on the prod  comp. But there is no such entry although call stack of the exception seems to point to exactly this part. How can it be?

**Comment by ralfeus** [comment]
It turns out access to AppointmentItem.Organizer may be limited by security policy as well. As I have no admin rights on a working laptop it seems I can't change it. So I though it's better to have not checked organizer's timezone than have no item synchronized at all. So I wrapped access to ai.Organizer to try..catch. It seems though that at least in my case time of the event is taken from my mailbox and is in my timezone regardless of organizer's one. 
So this could be a viable workaround

**Comment by phw198** [comment]
I certainly agree it's going to be better to avoid accessing the `ai.Organizer` attribute rather than not have anything sync. However, the reason all that logic is there is because (if I recall correctly) Outlook recalculates the appointment times to your local time and loses the timezone information - which means if the organizer changes the appointment later the time as synced to Google then becomes incorrect.

Anyway, as access is blocked by policy, we don't have much choice but to continue regardless!

**Comment by phw198** [comment]
:package: I've taken a slightly different approach to resolving this - I'd appreciate it if you could try [hotfix v2.7.8.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3077721/v2.7.8.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) to see if it still works.

Please let me know how it goes, thanks.
