### ISSUE TITLE
Two way sync keeps trying to delete google entries

### ISSUE THREAD

**Issue by mhurley131** [phw198/OutlookGoogleCalendarSync#698]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8.0
**Installed or Portable**: Installed

**Problem Description**  
\This is a brand new install and it is experiencing the same issue on beta and alpha releases.   I am attempting to do a two-way sync between Google and Outlook, but after I attempt a follow-up sync it is attempting to delete multiple google calendar entries.    I have tried having it do a full sync from google->outlook then reconfig a two way sync (as mentioned in another issue post) but it doesn't appear to fix the issue.

**Steps to Reproduce the Issue**  
1. Manually force a sync
1. 

**Any other information**  
\<Update here>

**Comment by mhurley131** [comment]
https://gist.github.com/mhurley131/48cfca6267ff9c13783a8b6d9f51bed7

**Comment by heshie75v** [comment]
I tried to recommended fix and OGsynch still tries to delete google entries. I have posted my log
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3040121/OGcalsync.log)

**Comment by phw198** [comment]
@mhurley131 You appear to only be syncing Outlook items with the category "Copy_to_Personal". Syncing those 5 items one way from Google to Outlook won't have given them that category unless you manually assigned it after they'd been synced to Outlook. Returning to two way sync will then just want to delete the Google items again.

**Comment by phw198** [comment]
@heshie75v I responded to your issue over on #707. As far as I can see the recommended fix worked - 14 items flagged for deletion, after the fix only one is.
