### ISSUE TITLE
G <-> O: Unable to reclaim orphan calendar entries in Outlook Calendar - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jurjenarnold** [phw198/OutlookGoogleCalendarSync#701]
**OGCS Version**: v2.7.8.0  
**Installed or Portable**: Installed

**Problem Description**  
Getting the following sync-errors on every sync on two devices:
"Unable to reclaim orphan calendar entries in Outlook Calendar"
"Object reference not set to an instance of an object"

**Steps to Reproduce the Issue**  
Happens every sync, easy to reproduce.

**Any other information**  
Worked fine this morning. No changes made, not even in my meetings.
Disconnected Gmail-account, no luck. Tried it on two devices (laptop and PC) and both give same error.

**Comment by ReddZen** [comment]
FYI I am having the same issue, and it just started today. And I have done everything you just mentioned.

**Comment by patrickverzijden** [comment]
I have the same problem since 2 days, very anoying.

**Comment by jurjenarnold** [comment]
Seems to be related to this issue, although the last reply mentioned deleting a appointment which he changed:
https://github.com/phw198/OutlookGoogleCalendarSync/issues/691

Strange thing is I haven't changed a thing between the sync working and not working anymore.

**Comment by JonDBl** [comment]
I posted in issue #691 but errors now appear to be the same as yours. This is preventing sync from Google to Outlook.

**Comment by patrickverzijden** [comment]
I have tried reinstalling the programme, without any succes. The same errror keeps on coming.

**Comment by jurjenarnold** [comment]
This morning, everything works fine again on my end....?
I will test on my PC at home. If both work my problem seems resolved. Very strange!
I will report later today.

**Comment by phw198** [comment]
Thanks for reporting this @jurjenarnold and others. As you spotted, this is the same as issue #689 (and #691, now closed) so I will track this bug on #689.

**Comment by JonDBl** [comment]
FYI I was able to find the record causing the issue by changing the sync options to 1 day in the past and then adding a day and syncing again until I found the outlook record causing the issue (7 days ago for me). I removed it from the calendar and I am now syncing 2 ways without ann issue.  The rogue record did sync OK initially.

**Comment by phw198** [comment]
@JonDBl or you could apply the hotfix as posted on #689 - at the very least it should tell you which item has the problem 🙂

**Comment by JonDBl** [comment]
Cheers Paul,

Applied!
