### ISSUE TITLE
Crashing at start; currentUser of type olOtherAddressEntry

### ISSUE THREAD

**Issue by dehabe** [phw198/OutlookGoogleCalendarSync#703]
:memo: Use the below template to report your issue.  
:bulb: I have Upgraded to the latest alpha release  2.7.8.0
:paperclip: To aid investigation, I provide OGcalsync.log file (

----

**OGCS Version**: v2.7.8.0 alpha
**Installed or Portable**: Installed

**Problem Description**  
OGCalsync starts and crashes after few seconds. Startup delay to 10 sec. or 30 sec. doesn't matter

**Steps to Reproduce the Issue**  
 Outlook (MS Office Pro Plus 2016, v 1808
(be it already running or not, OGCalsync crashes)
 OS W10 Pro 64
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3038858/OGcalsync.log)
 V1809 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Fails when getting your the primary SMTP address associated with your Outlook profile account.
```
System.Runtime.InteropServices.COMException: The property "http://schemas.microsoft.com/mapi/proptag/0x39FE001E" is unknown or cannot be found.
```

Please could you increase logging to `FINE`, recreate the issue and reupload your `OGcalsync.log` file?

**Comment by dehabe** [comment]
Thanks Paul

Do you mean <LoggingLevel>DEBUG</LoggingLevel>
To <LoggingLevel>FINE</LoggingLevel>

In settings.xml?

Best regards
Daniel

**Comment by dehabe** [comment]
and here is the new logfile
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3054009/OGcalsync.log)

**Comment by phw198** [comment]
Ah yes, I forgot the app was crashing and you'd have to change the logging level in the XML! Nicely done :+1: 

So this is strange - it appears you have configured Outlook with an Exchange profile, but the user account associated with it is of type `olOtherAddressEntry` - ie not an Exchange type. Google shows [someone else reporting this](https://social.msdn.microsoft.com/Forums/en-US/971b096a-79a4-4eba-b5cc-d2917a5279a0/addressentryusertype-is-olotheraddressentry-for-the-owner-of-an-exchange-account?forum=outlookdev), but no solution. [MS docs](https://docs.microsoft.com/en-us/office/vba/api/outlook.oladdressentryusertype) even say it's a type for custom stuff like a fax number!

:package: Anyways, could you try [hotfix v2.7.8.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3056391/v2.7.8.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and re-upload your log file again?

**Comment by dehabe** [comment]
![image](https://user-images.githubusercontent.com/49239552/55775616-255fa780-5a9a-11e9-9258-dfdb0970256f.png)
can't now start the v 2.7.8.3. zip app even as an administrator.
OGCS had been working fine until a few weeks ago. at the attempt to re download the hotfix and start over, Defender blocked it as trojan.
![image](https://user-images.githubusercontent.com/49239552/55777049-01eb2b80-5a9f-11e9-9343-a51a36c89ce9.png)

Thus no new logfile.

**Comment by phw198** [comment]
Well, it's definitely not a trojan :roll_eyes: 

But I don't think you've followed the patching instructions quite right - the file to replace should be in
`C:\Users\<userid>\AppData\Local\OutlookGoogleCalendarSync\app-2.7.8-alpha\`
not
`C:\Users\<userid>\AppData\Local\OutlookGoogleCalendarSync\`

So:
1. Delete `OutlookGoogleCalendarSync.exe`
1. Rename `OutlookGoogleCalendarSync.v2.7.8.0.exe back to  OutlookGoogleCalendarSync.exe`
1. Extract the zip file to `app-2.7.8-alpha\OutlookGoogleCalendarSync.exe`

Does that work any better?

**Comment by dehabe** [comment]
not much better
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3058908/OGcalsync.log)
running as administrator
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3058915/OGcalsync.log)
running same as Outlook

**Comment by dehabe** [comment]
![image](https://user-images.githubusercontent.com/49239552/55799711-53f97480-5ad2-11e9-9f6b-2c2881655cec.png)

**Comment by phw198** [comment]
Starting OGCS as administrator I would expect it to fail, as it did.

The Windows Defender is likely because the executable is flagged as being downloaded from the internet. Right click the extracted file > Properties > Unblock.

However, it still seems you're running v2.7.8.0. Have you placed that extracted file in `C:\Users\N7104\AppData\Local\OutlookGoogleCalendarSync\app-2.7.8-alpha\OutlookGoogleCalendarSync.exe` ?

**Comment by dehabe** [comment]
Thanks. It works now. 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3063023/OGcalsync.log)
