### ISSUE TITLE
Sync time

### ISSUE THREAD

**Issue by adacomp1** [phw198/OutlookGoogleCalendarSync#704]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

Is there a way to decrease the sync time schedule to less than 120 mins?

**Comment by alaingheysens** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3076070/OGcalsync.log)
Why is there, each time, a two hours difference when I import my Google calendar into Outlook.
This is very annoying, I always have to make the corrections in Outlook, entries are each time too early.
Thank you for some answer

**Comment by phw198** [comment]
Yes, if you disable Push Sync.

**Comment by GSCSarahMorris** [comment]
Hi there,
 
Sorry to be jumping in on this issue, but I am having the same issue. What you suggested above resolves being able to schedule less than 2 hours/120 minutes, however I can't schedule any less than 15 minutes now? 

Is it possible to schedule syncs for 1-5 minutes?

(If required, I'm happy to create a new issue for this - I'm now here so not sure on the protocols)

Thanks!
Sarah

**Comment by phw198** [comment]
HI @GSCSarahMorris It's not an issue, but by design. I guess you're confused with the difference between a scheduled sync and a "push sync" triggered by change in Outlook calendar.

Let me know if the [FAQ needs clarifying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-the-restriction-on-sync-schedule) further.
