### ISSUE TITLE
System.Runtime.InteropServices.COMException: Call was rejected by callee.  on startup

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#708]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8.0
**Installed or Portable**: Installed

**Problem Description**  
 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: Call was rejected by callee. (Exception from HRESULT: 0x80010001 (RPC_E_CALL_REJECTED))

**Steps to Reproduce the Issue**  
1. Happens every boot on Windows 10 Insider Fast Ring build 18865
1. 

**Any other information**  
delayed start setting: 300 second
Outlook 365 subscription 64 bit 16.0.11425.20202
[20190405OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3050083/20190405OGcalsync.log)

**Comment by phw198** [comment]
Looks to me like Outlook is taking ages to startup when invoked by OGCS. Have you tried setting Outlook to start on startup and then OGCS starts after a delay of 300 seconds?

**Comment by dutch55** [comment]
Paul,

I have delay set at the max of 300 seconds. Outlook isn’t set up to open automatically, although under Windows 10 (I am on Fast Ring Insider 18865 – it gets updated every week or two). It seems to open Outlook automatically sometimes, but I am not sure what the exact conditions are.

Harry

**Comment by phw198** [comment]
Yes, but the point I was trying to make was to [configure Outlook to start on start-up of Windows](https://support.microsoft.com/en-us/help/4026268/windows-10-change-startup-apps) - ie don't start Outlook implicitly via OGCS as this seems to take too long.

**Comment by phw198** [comment]
@marciovenicio No, your issue is different. However, could you please try the hotfix I just posted over on #709 to see if it now redirects you to the wiki when it errors?

**Comment by JeroenTuinstra** [comment]
Just opened up a bug report, have the same issue, however with windows 11 and Outlook LTSC. It is correct that when you start Outlook manually and then start OGCS manually it seems to work. But if you let OGSC start Outlook (in the background) it doesn't work and it actually locks up Outlook completely, as in Outlook does not want to start untill you end taks via task manager. You'll see many fails in the logs: OGSC crashing out, after this error.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8389402/OGcalsync.log)
.

**Comment by JeroenTuinstra** [comment]
This might help. Apparently calling Outlook (or using outlook) from a service is unsupported. Is this what OGCS is doing? 

[https://social.msdn.microsoft.com/Forums/vstudio/en-US/c7176bde-c395-493e-bc2d-aa31f0945722/error-when-trying-using-the-command-outlookapplication-oapp-new-outlookapplication-in?forum=csharpgeneral](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c7176bde-c395-493e-bc2d-aa31f0945722/error-when-trying-using-the-command-outlookapplication-oapp-new-outlookapplication-in?forum=csharpgeneral)

See comment: 
```
Use of Outlook in a windows service is unsupported by Microsoft and as you have seen is likely to cause program crashes or hangs.
```

**Comment by phw198** [comment]
@JeroenTuinstra Even if OGCS fails to start Outlook by invoking it as a new application to run, it should not lock things up and instead you'll just get the "Another program is using Outlook" task tray icon. But let's track this over on the other ticket you raised #1411, this one is ancient!
