### ISSUE TITLE
Not redirecting to wiki for COM error resolution advice

### ISSUE THREAD

**Issue by goodthelife** [phw198/OutlookGoogleCalendarSync#709]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0 and v2.7.8
**Installed or Portable**: Installed

**Problem Description**  
Unable to cast COM object of type 
•Microsoft.Office.Interop.OutIookAppIicationCIass• to 
interface type •Microsoft.Oftice.Interop.OutIook._AppIication•. 
This operation failed because the QueMntedace call on the 
COM component for the interlace with IID 
failed due to the 
following error: Error loading type library,'OLL. (Exception from 
HRESULT: C00029C4A 

![image](https://user-images.githubusercontent.com/49351357/55675159-8580fe80-588c-11e9-82ee-1ac9762c1288.png)

**Steps to Reproduce the Issue**  
1. After installing the latest Office update, I can no longer run OGCS. It starts with the error above. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
This'll be [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary).

:spiral_notepad: Could you provide your `OGcalsync.log` file though ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)), as OGCS should have automatically taken you to the wiki page...

**Comment by goodthelife** [comment]
Uploaded to your Google Drive. Thanks!
(OGCS hadn't taken me to that page)

**Comment by phw198** [comment]
@goodthelife Did you manage to get your install of Office fixed?

:package: If not, could you try this hotfix [v2.7.8.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3061369/v2.7.8.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) to see if it now redirects you to the wiki?

Let me know how it goes.

**Comment by goodthelife** [comment]
@phw198 I didn't realize it was my Office install that was causing the problem, I thought it was OGCS. Thanks for the heads up. I updated Office to 11425.20204, started OGCS, and everything is now working perfectly. Thank you!!

**Comment by phw198** [comment]
@goodthelife Great! Did you manage to apply the hotfix and test the wiki redirection or did you just fix Office?

**Comment by phw198** [comment]
@marciovenicio Did you get to try this hotfix and see if it directed you to instructions on how to fix [your issue](https://github.com/phw198/OutlookGoogleCalendarSync/issues/708)?

**Comment by marciovenicio** [comment]
Yes. It directed me to instructions on how to fix the problem. After following the instructions it worked very well. Thank you so much!
