### ISSUE TITLE
Word obuscation

### ISSUE THREAD

**Issue by Monkey777** [phw198/OutlookGoogleCalendarSync#710]
Hi...

When I do a word obfiscation on location, it does not work.

**Comment by phw198** [comment]
Because as the tooltip on the "Word obfuscation" checkbox says, it only applies to the subject line.

You're probably interested in enhancement #500 being implemented.

**Comment by Monkey777** [comment]
Oh okay, thank you... Do we know when it would be emplemented?

**Comment by phw198** [comment]
No immediate plans, but you could give +1 reaction on #500 to vote it up...
