### ISSUE TITLE
Google created item color is changed after second synchronization

### ISSUE THREAD

**Issue by ralfeus** [phw198/OutlookGoogleCalendarSync#711]
**OGCS Version**: v2.7.8.0
**Installed or Portable**: Portable

**Problem Description**  
When an event is created in Google and synchronized to Outlook, next synchronization changes its color as it would be originated in Outlook.

**Steps to Reproduce the Issue**  
1. Create an event in Google calendar.
2. Synchronize it to Outlook
3. Run synchronization again
4. See color of event in Google calendar is changed

**Comment by phw198** [comment]
Pretty sure you're describing the same as issue #580 - could you confirm?

**Comment by ralfeus** [comment]
Not really. The color is exactly one I've specified in settings. However I expect that color is set only for synchronized events and original ones aren't touched.
So in Google I have default color of events yellow. Outlook events color is default (kind of light blue). Color in settings is dark blue. So I expect:
- items created in Outlook to be light blue
- items created in Outlook and synchronized to Google to be dark blue
- items created in Google to be yellow
- items created in Google and synchronized to Outlook to be dark blue

However I see: 
- items created in Google are yellow 
- after synchronization they are created in Outlook and are dark blue in Outlook
- after second synchronization they become dark blue in Google.

So it seems the synchronizer treats these items as they were created in Outlook and updates color in Google.

Additionally, if I change manually color of the even in Google to any other synchronization returns its color back to dark blue.

**Comment by phw198** [comment]
I can't replicate your issue at all, but it's rather difficult without your `OGcalsync.log`file or even a screenshot of your Sync Options > How section. Here's what I was trying with 2-way sync along with various other combinations:
![image](https://user-images.githubusercontent.com/11843015/55839207-f3445900-5b1e-11e9-813d-fbffedd32100.png)

>after second synchronization they become dark blue in Google.

OGCS shouldn't be working like that - it syncs change since the last sync and nothing would have changed unless you manually edited the Outlook item after OGCS had synced it there? If doing that, I can't make it sync the colour back to Google.

:spiral_notepad: Really need to see your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) covering what you're seeing.

**Comment by ralfeus** [comment]
Ok, that was my mistake. I had settings set like this:
![image](https://user-images.githubusercontent.com/1980527/55858744-c3be3c80-5b70-11e9-83a1-a44427585a44.png)
After I changed "all items" to "items created" the problem has gone. So that was expected behavior I presume.

I have another question (probably suggestion for improvement). Using this setting I can define setting color either for Google calendar or for Outlook but not for both. Is it right? Color distinguishing of events created in any calendar and ones synchronized there is useful on both sides.

**Comment by phw198** [comment]
These settings are overrides really, forcing an attribute to have a different value than that from the source calendar. The issue with two way sync is that OGCS cannot determine from which calendar an item originated, and therefore it's not possible to say "if this item was created automatically by sync and not manually, then set it a certain colour". 

I wouldn't want to add extra logic to try and do this either - eg there are users that sync two different Outlook accounts (eg home and office) to a single common Google calendar. Tracking what's come from where and how would be a nightmare :worried:

**Comment by ralfeus** [comment]
Defining the item's origin can be achieved by adding one more extended attribute. The counterpart's ID is anyway added, so it shouldn't be hard to implement. I could do that if you want. 
By the way it would be useful to add more synchronization options. For example it could be good to have two-ways synchronization but have always original items changes prevail. 

As for synchronizing with several Outlooks - it shouldn't matter from which Outlook item is originated. Should be enough to know that it's coming from Outlook.
