### ISSUE TITLE
Unable to reclaim orphan calendar entries in Outlook calendar

### ISSUE THREAD

**Issue by shawnhooper** [phw198/OutlookGoogleCalendarSync#714]
**OGCS Version**: v2.7.8.0  
**Installed or Portable**: Installed

**Problem Description**  
Sync fails with Unable to reclaim orphan calendar entries in Outlook calendar.

**Steps to Reproduce the Issue**  
1. Run Sync
1. Error occurs every time

**Comment by shawnhooper** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3076828/OGcalsync.log)

**Comment by phw198** [comment]
Thanks - please [try the hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/689#issuecomment-480601660) as posted on #689 and update your findings on that ticket.
