### ISSUE TITLE
Annoying marketing popups

### ISSUE THREAD

**Issue by sebastius** [phw198/OutlookGoogleCalendarSync#715]
Although i appreciate the need for promotion: can you please for the love of god disable all those annoying 'hey you've done 100 syncs would you like to promote this software'. It's so annoying that i'm almost at the point that i'll ask for a refund and delete the software.

**Comment by phw198** [comment]
Probably not! You'll have a got a whole two popups so far (at 10 syncs and 100) and they'll get less and less frequent - a pretty small price to pay for a tool with no limitations.

But it sounds like you may have donated and can hide the splash screen? If so, in v2.7.8 you can also suppress further popups (and they also won't block further scheduled syncs as happened in previous versions).

HTH
