### ISSUE TITLE
Synchronisation failed 

### ISSUE THREAD

**Issue by rikoos** [phw198/OutlookGoogleCalendarSync#716]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8.0
**Installed or Portable**: Portable version

**Problem Description**  
After a few succesfull syncs now i receive a error:

Sync version: 2.7.8.0

Sync started at 15-4-2019 15:57:08

Syncing from 14-4-2019 to 26-5-2019

Outlook ↔ Google

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.

Finding Calendar Entries
Scanning Outlook calendar...

91 Outlook calendar entries found.

Scanning Google calendar...
45 Google calendar entries found.

1 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...

Failed to retrieve master for Google recurring event outside of sync range.

De bewerking is afgebroken (Uitzondering van HRESULT: 0x80004004 (E_ABORT))

Operation aborted after 1 failed attempts!

**Steps to Reproduce the Issue**  
1. <Update>

**Any other information**  
\<Update here>

**Comment by rikoos** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3080487/OGcalsync.log)

**Comment by phw198** [comment]
Duplicate of #702 which already has a hotfix posted.

**Comment by rikoos** [comment]
Fixed the sync problem
