### ISSUE TITLE
Unable to reclaim orphan calendar entries in Outlook calendar. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SanvanE** [phw198/OutlookGoogleCalendarSync#723]
**OGCS Version**: v2.7.8.0
**Installed or Portable**: Installed

**Problem Description**  
It has been working untill a few days ago. Now I keep getting the error: 

Unable to reclaim orphan calendar entries in Outlook calendar.
Object reference not set to an instance of an object.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3141399/OGcalsync.log)

**Comment by phw198** [comment]
Duplicate of #689
