### ISSUE TITLE
all-day events moved on Outlook calendar not appearing in Google

### ISSUE THREAD

**Issue by Florio60** [phw198/OutlookGoogleCalendarSync#724]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v 2.7.8.0
**Installed or Portable**: Installed

**Problem Description**  
\If I move an all-day event from one day to another on my Outlook calendar, it does not subsequently appear on Google.

**Steps to Reproduce the Issue**  
1. \Drag all-day event with mouse to move it from one date to another
1. 

**Any other information**  
\<Update here>

[2019-05-03OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3145712/2019-05-03OGcalsync.txt)

**Comment by phw198** [comment]
Your log file only shows you doing a single sync. Obviously having moved the all-day item, you'd need to perform another sync...
