### ISSUE TITLE
OGCS crashes on launch

### ISSUE THREAD

**Issue by frlu05** [phw198/OutlookGoogleCalendarSync#725]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8
**Installed or Portable**: Portable

**Problem Description**  
\<After latest update of Office365 ProPlus (managed by IT-department, version 1808 and build 10730.20334) OGCS crashes when trying to start.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Attached logfile, see last 6 line "System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass'....>

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3145760/OGcalsync.log)

Attached logfileAttached logfile

**Comment by phw198** [comment]
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary
