### ISSUE TITLE
Sync fails with NullReference Exception -  using hotfix 2.7.8.1  - thsi is not the same as 689

### ISSUE THREAD

**Issue by mjlipton** [phw198/OutlookGoogleCalendarSync#730]
**OGCS Version**:   2.7.8.1
**Installed or Portable**: Installed

**Problem Description**  
I keep deleting the offending calendar entry on the outlook side to see if I can get the sync to work,  and then another calendar entry causes the failure.   sometimes the entries are in the future, sometimes in the past.
----
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3168942/OGcalsync.log)

**Steps to Reproduce the Issue**  

1. Do not know

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
So you've got lots of entries that you created by copy and paste on v2.7.8.0 before you starting using the hotfix. All of them will need recreating. Definitely is the same issue.

And don't just keep opening new issues - update [your previous one](https://github.com/phw198/OutlookGoogleCalendarSync/issues/728) if you don't agree with my analysis.
