### ISSUE TITLE
enhancement request:  is there a way to "reset"?

### ISSUE THREAD

**Issue by mjlipton** [phw198/OutlookGoogleCalendarSync#732]
----

**OGCS Version**: v2.7.8.1
**Installed or Portable**: Installed

**Problem Description**  
My calendars on both the outlook and google side are now out of sync and the system is failing repeatedly.  I can repair the events manually on both sides, but am afraid to run the tool for fear of starting a cascade of deletions.     It would be great for a tool to "reset"  (delete all of the pointers / meta data)  such that I could resync as if this was the first time.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Yes! Have a [read through here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#removing-all-ogcs-metadata-from-your-calendars).

**Comment by mjlipton** [comment]
Great,  thanks!
