### ISSUE TITLE
syncing google to outlook 

### ISSUE THREAD

**Issue by Securlock** [phw198/OutlookGoogleCalendarSync#734]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8.0
**Installed or Portable**: Installed

**Problem Description**  
\<when trying to sync, I get the following error 
"unable to reclaim orphan calendar entries in Outlook calendar."
"object reference not set to an instance of an object."
"operation aborted after 1 failed attempts!">

**Steps to Reproduce the Issue**  
1. \<manual sync>
1. 

**Any other information**  
\<Update here>

**Comment by HarrieB58** [comment]
Hi
I have the same problem; I had the problem using version 2.7.8.5, updated to version 2.7.9, and problem is occuring still (but now I know on which event...)

**Comment by phw198** [comment]
Yes, as @HarrieB58 says, upgrade to v2.7.9, identify the item causing the problem (one that you created by copy and pasting/dragging in Outlook on v2.7.8) and delete it and recreate it.
