### ISSUE TITLE
Errors: Updated event failed to save. Forbidden [403=Forbidden]

### ISSUE THREAD

**Issue by reneekblanchard** [phw198/OutlookGoogleCalendarSync#736]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8.0  
**Installed or Portable**: Installed

**Problem Description**  
When my Outlook Calendar Sync runs, there are three calendar entries where I receive an error.  The system then prompts me three times asking me 'Updated Google event failed to save. Continue with synchronisation?'  I can click yes or no.  If I click yes, the sync continues with all other updates, but I receive errors for three events.  If I click no, the sync cancels.

**Steps to Reproduce the Issue**  

[OGcalsync.2019-05-15.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3187283/OGcalsync.2019-05-15.log)
[OGcalsync.2019-05-14.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3187284/OGcalsync.2019-05-14.log)

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Can you edit any of these problematic items yourself, manually in Google Calendar webview?

The changes OGCS is trying to make in `4/15/2019 8:15 AM   "NexGen | Roto-Rooter - FSL Review"` are:
* Recurrence: From weekly on Sun → weekly on Mon, Wed, Thu
* Start Timezone: America/New_York → America/Chicago
* End Timezone: America/New_York → America/Chicago
* Description: Renee Blanchard is inviting you to a scheduled ... → more details » 
* Reminder: nothing → 10

Where did this invite originate from? I'm assuming Outlook, not Google?

**Comment by reneekblanchard** [comment]
Hi Paul,

When I originally got the errors, I tried to edit each of the 5 fields to make sure they matched each other (in outlook and google calendar web).  But I still continued to get the errors.  Even after I deleted the entries.  I noticed that the only time I am getting these errors is when I have a recurring meeting and one or more of individual occurrences are edited (times are changed).  It is like the individual occurrence meeting changes are not matching the original recurrence meeting details and it doesn’t like that.  

Regards,

Renee Blanchard | Senior Consultant

**Comment by phw198** [comment]
So to expand on what I think you're saying:
1. That you could edit the Google entry manually without a problem. 
1. You even manually set the attributes to match Outlook so OGCS wouldn't detect any difference, but OGCS still errored. With _exactly_ the same error? I would need to see the logs to see what it was trying to do if it had detected no change.
1. You deleted the entries - in Google? Explain further. I assume you set OGCS to one-way O->G sync so it would recreate the Google entries? Once Google entries had been recreated, OGCS would not want to make any further changes in Google unless the Outlook item has changed.

> It is like the individual occurrence meeting changes are not matching the original recurrence meeting details and it doesn’t like that.

Possibly, but the example of `4/15/2019 8:15 AM   "NexGen | Roto-Rooter - FSL Review"` I believe it is trying to change the master recurring series and not a single occurrence within it?
