### ISSUE TITLE
OGCS no longer works nor installs

### ISSUE THREAD

**Issue by Chris440** [phw198/OutlookGoogleCalendarSync#738]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by Chris440** [comment]
When I want to reinstall the software I get the following error as described in attachment

[errorlog.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3195448/errorlog.txt)

**Comment by phw198** [comment]
Your error message is: `Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Access to the path 'C:\Users\Chrisvdk\AppData\Local\OutlookGoogleCalendarSync\app-2.7.5-alpha\log4net.dll' is denied.`

Make sure OGCS is completely shutdown (no `outlookgooglecalendarsync.exe` processes still running) and then try and install v2.7.9.

**Comment by Chris440** [comment]
Problem solved. Thank you!
