### ISSUE TITLE
Remove Google+ Preview Community link from page

### ISSUE THREAD

**Issue by KoalaBear84** [phw198/OutlookGoogleCalendarSync#743]
**Problem Description**  
Remove Google+ Preview Community link from this page: https://phw198.github.io/OutlookGoogleCalendarSync/get-involved.html

**Steps to Reproduce the Issue**  
Visit https://phw198.github.io/OutlookGoogleCalendarSync/get-involved.html

**Comment by phw198** [comment]
Thanks for pointing that out - have now updated it.
