### ISSUE TITLE
Can't Install v2.8.0 Win10 Outlook 2019 (O365)

### ISSUE THREAD

**Issue by djbigpaul** [phw198/OutlookGoogleCalendarSync#746]
Can't install, 

Registry Entry:

Fault bucket 1835963560265603993, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: OutlookGoogleCalendarSync.exe
P2: 2.8.0.0
P3: 5cf2f1fb
P4: mscorlib
P5: 4.7.3416.0
P6: 5cabfb31
P7: 1688
P8: ca
P9: System.IO.FileNotFoundException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER8EC5.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER901E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER903E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER903E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER907E.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_OutlookGoogleCal_2365a63b74e62f0bec750957a5b63f968e6361_cc551734_7cb1927e

Analysis symbol: 
Rechecking for solution: 0
Report Id: c5e26ef4-f081-40eb-8388-455ba7a816a3
Report Status: 268435456
Hashed bucket: 2bcfd3ccee69b275597aa72176315b99
Cab Guid: 0

**Comment by phw198** [comment]
Does [v2.7.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.7.0-beta/Setup.exe) install OK?

:spiral_notepad: Also, please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) after OGCS crashes on v2.8.0.

**Comment by djbigpaul** [comment]
Yes it does! Thank you. Would it be recommended to upgrade to the latest 2.7.x release after testing?

Paul

**Comment by phw198** [comment]
OK, that's odd. Problem is, GitHub broke the upgrade mechanism on versions before 2.7.4, so you'll need to manually download later releases.

Could you try v2.8.0 `Setup.exe` again and if it doesn't work step back through the alpha releases (v2.7.9, v2.7.8) etc until it works?

https://github.com/phw198/OutlookGoogleCalendarSync/releases

**Comment by mark-szabo** [comment]
Same issue over here. v2.7.9 alpha installs correctly.

**Comment by phw198** [comment]
This'll be the same issue as #744 which is now fixed and rolled back into v2.8.0.0.

Basically, [try reinstalling](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.8.0-beta/Setup.exe) again...
