### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by jslwebster** [phw198/OutlookGoogleCalendarSync#748]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Portable and/or Installed version

**Problem Description**  
\Launching the application results in the following error:
A pop-up window appears - "OutlookGoogleCalendar Sync has stopped working"
with the following problem details. No log file gets created. Problem details follow:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	OutlookGoogleCalendarSync.exe
  Problem Signature 02:	2.8.0.0
  Problem Signature 03:	5cf2f1fb
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.34209
  Problem Signature 06:	534894cc
  Problem Signature 07:	4527
  Problem Signature 08:	ce
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Steps to Reproduce the Issue**  
1. \<Start the application>
1. 

**Any other information**  
\< OGCS version 2.7.1 starts up and runs. Any version above 2.7.1 results in the same error.
System is Windows 7SP1, Office 2016, DotNet 4.5.2 (also tested DotNet 7 - OGCS 2.7.1 works with DotNet 7>

**Comment by phw198** [comment]
Hi @jslwebster 

When and how did you download v2.8? The issue you are reporting should have been resolved at 10:30 GMT...

**Comment by Quotic** [comment]
I had same or similar issue, so I cloned repository and run it. It throws an exeption in moveFiles() for config file. Because before first start there is no settings.xml, Maybe there should be added a check, if file exist or  at least a try/catch

**Comment by phw198** [comment]
It's already patched and fixed over on #744 - I was just trying to ascertain if @jslwebster was running OGCS before the fix was deployed...
