### ISSUE TITLE
First "push" sync failed - API key missing scope

### ISSUE THREAD

**Issue by kennym8** [phw198/OutlookGoogleCalendarSync#749]
I just installed v 2.8.0.0 today and configured it.

The first "push" sync failed. see attached log.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3254849/OGcalsync.log)

**Comment by phw198** [comment]
Thanks for reporting - this should now be fixed, if you could confirm?

**Comment by kennym8** [comment]
Yes, it’s all working fine now! I will now install in the other laptop and then send a donation!!

 

Ken
