### ISSUE TITLE
Application unexpectedly terminated.  Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by meme10506** [phw198/OutlookGoogleCalendarSync#751]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Application unexpectedly terminated.  Object reference not set to an instance of an object

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
I installed the beta issue.  It's my first time using this program. I am unable to use it because it immediately gives me this error before the program even has a chance to run. I am not a programmer, so please make the solution simple.  I don't see where I can get an alpha version, only the beta version.

**Comment by phw198** [comment]
Working through this on #752.
