### ISSUE TITLE
You need to have writer access to this calendar. [403]

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#753]
Not sure if it is coincidence or not, but problem popped up after applying numerous Windows 10 updates the past few days.

I cant seem to figure out what changed / broke?

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3268556/OGcalsync.log)

----
Enhancement tasks logged by @phw198:
- [x] Show in GUI if Google calendar is read-only
- [x] Warn if selected read-only calendar for anything other than G->O
- [x] Handle error nicely if sync attempted

**Comment by phw198** [comment]
You look to be syncing with a Google calendar "Holidays in United States" - this sounds like a public read-only calendar, so I wouldn't expect you to have write access to it.

**Comment by phw198** [comment]
Enhancement:
- [ ] Show in GUI if Google calendar is read-only
- [ ] Warn if selected read-only calendar for anything other than G->O

**Comment by kwagner115** [comment]
There is no other option. When I open the pull down, the only entry / choice is “Holidays”.
 
I have tried disconnecting and reconnecting (re-authorization). Has no impact.
 
Kevin

**Comment by kwagner115** [comment]
I tried disconnecting and reconnecting (re-authorization of Google) 3-4 more times and finally got to a place where I could select the correct Google calendar. 
 
I think I’m OK now. 
 
Kevin

**Comment by phw198** [comment]
Simplest option would have just been to click `Retrieve calendars`.

**Comment by jch190** [comment]
I'm also getting this same issue, not sure how to handle. Thanks in advance, is exporting at least some events but looks like an amazing tool once fully operational for me.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3383430/OGcalsync.log)

**Comment by phw198** [comment]
@jch190 This isn't a bug - you need to have write access into the Google calendar you are syncing to. The next alpha release will clearly show the read-only calendars and warn you if selected for sync.

Click `Retrieve Calendars` and then select one you are able to create calendar items in. Check in https://calendar.google.com is you're not sure.

**Comment by jch190** [comment]
Shoot. Any idea how to allow write access?

**Comment by phw198** [comment]
If you own the calendar, then you automatically have write permissions. Which means the calendar you're trying to use is either a public "internet" calendar which will only ever be read-only, or it has been shared with you by someone you know - in which case ask them if they'd be kind enough to give you write permissions.

**Comment by telenut** [comment]
Same problem here... And I do own the agenda :-)

**Comment by telenut** [comment]
edit: I just deleted the agenda and made a new one. Now it works.
