### ISSUE TITLE
Sync gets stuck

### ISSUE THREAD

**Issue by SAH88** [phw198/OutlookGoogleCalendarSync#757]
**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
\<Sync gets stuck at "Comparing 103 existing Google calendar entries. It will stay on that step for hours, making it impossible to use Outlook. If I stop the sync, it will automatically restart in 15 minutes and get stuck at the same point. >

**Steps to Reproduce the Issue**  
1. \<Start sync. Get stuck.>
 
Sent log to phw198.

**Any other information**  
\<I do work on a company computer. So security software could be interfering. Thanks for trying to help! I really appreciate the sync program!>

![sync_ss](https://user-images.githubusercontent.com/51649544/59198945-d948e600-8b62-11e9-851d-bb7a4303af02.png)

**Comment by phw198** [comment]
:spiral_notepad: Please could you increase the logging level to `FINE`, reproduce the problem and then provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by SAH88** [comment]
Done, I think!

https://gist.github.com/SAH88/912d5730d85a034c39ecc909e47efada

Let me know if I did anything wrong.

Thanks again for your help!
Susan

**Comment by phw198** [comment]
So it looks like there is a problem when processing `5/8/2018 1:05 PM (R) => "6-12 Reveal: Cross-functional Meeting for National"` which has 46 exceptions to the recurring series. Unfortunately, Exchange is very unhelpful, simply reporting `The operation failed.`.

I note you are running Outlook in Exchange Online mode and not cached. Could you try [turning on cached Exchange mode](https://support.office.com/en-gb/article/turn-on-cached-exchange-mode-7885af08-9a60-4ec3-850a-e221c1ed0c1c) and seeing if that helps?

**Comment by SAH88** [comment]
Hmmm... I tried that and it wiped out my Outlook calendar. So after I
stopped panicking, I turned that setting back off and restarted, and it was
all back.

Oddly enough, I ran the sync after that and it finished successfully! The
log is here in case you are interested. Maybe if I'm lucky it will continue
to work!
https://gist.github.com/SAH88/a20c80353d530742877e566077f7a5cc.js


Thanks!
Susan

**Comment by phw198** [comment]
OK, that's pretty weird! A quick Google shows [someone with a similar experience](https://answers.microsoft.com/en-us/msoffice/forum/all/outlook-2016-designated-calendar-not-syncing-in/3f36cb12-ed34-4c70-892e-77eee81485bd) (could be down to a corrupt OST file that needs repair) and steps to potentially fix cache-mode.

Cached mode should give a better experience using Outlook, but up to you if you pursue it further given the problem with OGCS seems to have gone away :slightly_smiling_face:
