### ISSUE TITLE
Application Unexpectedly Terminated!

### ISSUE THREAD

**Issue by MiktaNaji** [phw198/OutlookGoogleCalendarSync#758]
**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I didn't have any issues with 2.7.0.0 however it was not removing a calendar item from my Google Calendar. I choose to download 2.8.0.0 to see if this resolved my issue however the application will no longer run. When I open the application the application attempts to run and I finally get a "Application Unexpectedly Terminated! Window Handle already exists." error message.

**Steps to Reproduce the Issue**  
1. Do not uninstall version 2.7.0.0
2. Run Setup.exe to install 2.8.0.0
3. Run version 2.8.0.0
4. Failed message appears

**Any other information**  
Nothing.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3272368/OGcalsync.log)

**Comment by phw198** [comment]
:package: Please could you apply [v2.8.0.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3273909/v2.8.0.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)), which will capture some more information when the problem occurs. 

Once patched, please reproduce the problem and then re-upload your `OGcalsync.log` file again. Thanks!
