### ISSUE TITLE
Google Calendar to Outlook Category not syncing

### ISSUE THREAD

**Issue by sjsdoc60** [phw198/OutlookGoogleCalendarSync#759]
**OGCS Version**: v2.8.0  
**Installed or Portable**: Installed

**Problem Description**  
I have 5 multiple sync OGCS instances.  The google calendars have slightly different names from my Outlook categories.  Overall, I can get them to sync individual events.  But the google calendar to outlook category does not work.  They come across from Google to Outlook without a category.  The checkbox for colours/categories in Sync Options does not do anything.  All Google entries come across as the base color/no category.  The attached log is for a Google calendar named Travel/Vacation which syncs to an  Outlook category named Vacation.  The item name is there but the color and category are wrong. I do see the correct GC name in Google tab and the Include Vacation Filter Category in Outlook tab.
A second sync after deleting a vacation item in GC does not delete the item in OC.  No doubt because the item has no category.  
I attached my calendar.log.

What to do further?  Thank you.

**Comment by sjsdoc60** [comment]
Have confirmed that Google calendar name to Outlook category sync not working for any of the 5 instances.  I can make it pick a color for Outlook new entry but even if same color as an existing category, just creates a new OGCS color, never picks the proper category.  This becomes important when you do f/u syncs as it does not see outlook event and just creates a new duplicate one (since there is no assigned category in Outlook).
Thank you for review.

**Comment by phw198** [comment]
You seem to have confused calendars with categories with colours. This is understandable as terminology between the two calendar is confused and OGCS is really only synced colours, not categories.

* A Google calendar is not a "category", simply a calendar with a colour associated. Many calendars can have the same colour.
* An Outlook category has a colour associated, many categories can have the same colour.

OGCS is syncing the colours (closest match). There is no way that it would know a Google calendar called "Holidays" which happens to have been given the colour Yellow, should sync to a category in Outlook called "My time off" that is also Yellow, when there is also another Yellow category called "Important Project A".

Therefore, OGCS creates a new category in Outlook called "OGCS Yellow" and any yellow Google calendar will receive that category in Outlook.

_([Issue 580](https://github.com/phw198/OutlookGoogleCalendarSync/issues/580) covers ideas for enhancing category syncing)_

**Comment by sjsdoc60** [comment]
Thank you for clarity.  I did know a GC is not a category but Outlook color is also not a category.  Color in outlook does not mean anything.  I did (and I think most people would) link a GC name to an Outlook category.  If you dont and you try linking multiple Google Calendars with Outlook then events will come in Outlook with no category and trying to sync Outlook/Google with multiple calendars will cause great problems if you try and keep categories in Outlook matched with proper Google Calendars (vacation, business, travel, personal...).  I dont understand why the sync tab would 'Include' an Outlook Category and the Google tab a specific Google Calendar otherwise?  Seems built for this but you are saying does not work that way if I understand correctly?  Would it be possible to get this functionality?
Thank you for your work

**Comment by madmax69ca** [comment]
I agree with **sjsdoc60** as I expected the same behavior. I used gsyncit in the past and I was able to sync a GC with a given OC Category. In OGCS, you are able to specify which OC Category you sync to GC so why can't you set the OC Category when events are created from GC ?

**Comment by phw198** [comment]
Agreed, there's room for improvement here - but I'll track that over on #580.
