### ISSUE TITLE
How to discuss possible security issue?

### ISSUE THREAD

**Issue by EldaHill** [phw198/OutlookGoogleCalendarSync#761]
Hi Paul
I sent you emails but didn't get a response. There may be an issue and I'd like to discuss it with you. Please let me know what to do next. 
Thanks :-)

**Comment by phw198** [comment]
Hi,

I've found your email - unfortunately got sent to spam :(

However, no, sharing API keys and quotas absolutely isn't a security issue - you can [read up on OAuth2 here](https://developers.google.com/identity/protocols/OAuth2#basicsteps) if interested, but essentially once you provide user consent for OGCS to manage your calendars, Google will assign you a personal access token (which lasts for an hour) and a refresh token (which allows you to get new access tokens).

These tokens are what are personal to you, allowing you (and only you) the ability to update your calendar with OGCS. You therefore must not share these tokens with anyone, especially the refresh token. OGCS stores this information in `Google.Apis.Auth.OAuth2.Responses.TokenResponse-user`.

You can centrally revoke usage of these token from Google [Account Security](https://myaccount.google.com/permissions)

Hope that helps.
