### ISSUE TITLE
Sync cannot retrieve google calendar

### ISSUE THREAD

**Issue by patrickverzijden** [phw198/OutlookGoogleCalendarSync#762]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>Today the Sync programme succesfully synchronized at 11:00 AM, later that day I got an error message that it was not able to connect to the google calendar and I got a message when I tried to connect to the google calendar: "Please ensure  you can access the internet with internet explorer. Test it now? If succesful please try retrieving your google calendars". I do not use internet explorer at all and when I click yes it opens internet explorer with a google page.
I have disconnected the google account in the settings menu and tried to use it again but the same issue occurs.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3302605/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. \<Update>Just open the sync app and the error occurs immediately
1. 

**Any other information**  
![image](https://user-images.githubusercontent.com/49266210/59703342-f5e7bc80-91f9-11e9-86d6-f7776eef7c1a.png)

\<Update here>

**Comment by patrickverzijden** [comment]
After a new attempt to sync, I got a different message:

![image](https://user-images.githubusercontent.com/49266210/59704061-8e327100-91fb-11e9-8cb2-33314b667507.png)

**Comment by phw198** [comment]
See #763.
