### ISSUE TITLE
Few events not pulling changes (Outlook -> GC and GC -> Outlook)

### ISSUE THREAD

**Issue by iscofield** [phw198/OutlookGoogleCalendarSync#767]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
Random items failing to sync.  Had an event in both Outlook/GC.  Renamed event in GC, 24 hours later it still hasn't renamed the item in Outlook.  Have an event that I moved the start time up 1 hour in outlook, several hours later, still hasn't updated GC.  It's not isolated to only one direction and I have manually synced several times in between.  Don't see any items in the verbose sync log that would indicate why it's failing, it's not even detecting the changes.

**Steps to Reproduce the Issue**  
1. Cannot consistently reproduce.  Tried moving another event earlier in outlook, but it was able to sync.  Also tried renaming another event in GC to see if it would get renamed in outlook, which did work.  Not sure what's up with these two events in particular and looking at the logs doesn't seem to indicate any errors with these events in particular.

**Any other information**  
Previously was using Sync2, but they are trying to charge me another $50 on top of the money already spent just to reactivate it after my windows box getting hosed and having to reinstall.  So I had a GC that was already synced and am trying to use this moving forward.  It seems to be mostly working, but there are a few items where it doesn't appear to be detecting changes or syncing.

(Link to private gist sent)

**Comment by phw198** [comment]
Hi @iscofield - some questions:

1. What is the name and date of one of the items that is not syncing?
1. Is is a single event, or a recurring series? If recurring, as you creating an "exception" by changing one of the occurrences within the series? *
1. Try turning on `Create CSVs` and then checking `google_events.csv` and/or `outlook_appointments.csv` in the same directory as your log file - is the item listed in there?
    1. If it's **not** in the CSV, then OGCS just isn't seeing these items for some reason. Maybe try [changing the Outlook date format](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) - often Outlook doesn't like seconds.
    1. If it **is** in the CSV, try [turning on one-way sync](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) and then press `Shift` + click `Sync` to run a full sync.
1. Are you able to recreate these problematic items, just to make sure it's not some hangover from Sync2?

\* I see you have a lot of `You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.` errors. I assume you've tried closing down Outlook and restarting?

**Comment by phw198** [comment]
Any update or shall I close this issue out?

**Comment by iscofield** [comment]
Yea you can close this out. I have reverted back to sync2 as I wasn’t able to get syncing to work consistently and wasn’t able to predictably reproduce issues.


________________________________
