### ISSUE TITLE
Unable to set interval to anything less than 120 minutes

### ISSUE THREAD

**Issue by iscofield** [phw198/OutlookGoogleCalendarSync#768]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
\The user guide says minimum sync interval is 10 minutes.  Any number I put into the interval box gets automatically set to 120 minutes.  

**Steps to Reproduce the Issue**  
1. Type any number in the minutes box and hit save.
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Well spotted...the [User Guide](https://phw198.github.io/OutlookGoogleCalendarSync/guide/syncoptions) needs updating. The minimum is 15 minutes unless you have Push sync enabled, in which can it will be 120 minutes. You can remove this "fair usage policy" restriction by using your own API keys if you wish.
