### ISSUE TITLE
Request: "Set entries as non-private" option

### ISSUE THREAD

**Issue by jrissman** [phw198/OutlookGoogleCalendarSync#769]
I currently use OGCS 2.8.00 to synce one-way from a work Outlook to a personal Google calendar, and it works great.

However, it is missing one small feature that I could really use.  I manually add both my personal and work events to my Outlook calendar, which is provided by my employer.  At my company, employees can see each others' Outlook calendars.  Therefore, I mark all of my non-work events as "Private" when I add them to my Outlook calendar, so my coworkers can see the details for my work items but only see free/busy time for my personal events.

I want my wife to be able to see the full details of all of my calendar items.  I use OGCS to one-way sync my Outlook calendar to a Google calendar, and I share that Google calendar with her.  However, because OGCS syncs the privacy flag on events, my personal events after being copied to the Google calendar are marked "private," which prevents her from seeing the details.

OGCS already includes an option to "Set entries as private," which adds the privacy flag to all of the items that are copied to a new calendar.  I want the same feature, but in reverse.  I want OGCS to be able to **remove** the privacy flag from the copies of items it makes in a new calendar.  (In my case, all items copied from Outlook to Google would be non-private in the Google calendar, but their privacy flag would be unchanged in the Outlook calendar.)

In the OGCS user interface, where the option currently exists to "Set entries as private" (on the Sync Options tab), the word "private" could become a drop-down menu, where the user can select either "private" or "non-private".

Thank you for considering this small feature request.

**Comment by phw198** [comment]
This has just been released in v2.9.5 via #1325
