### ISSUE TITLE
push outlook changes immediately  not working

### ISSUE THREAD

**Issue by Barnardm1** [phw198/OutlookGoogleCalendarSync#772]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0 
**Installed or Portable**: Installed

**Problem Description**  
push outlook changes immediately 

**Steps to Reproduce the Issue**  
1. set it up and works well when I do a manual sync
1. however does not sync immediately.

**Any other information**  
Thank you

**Comment by phw198** [comment]
Well no, it's not "immediate" - it's within 2 minutes. Or is it not triggering a sync at all? In which case I'd need to see your OGcalsync.log file after you've made a change in Outlook.
