### ISSUE TITLE
3.6.2.0 setup fails if "just for me" is selected

### ISSUE THREAD

**Issue by eitancaspi** [phw198/OutlookGoogleCalendarSync#773]
Hi, when running the setup of 3.6.2.0, either the setup.exe or the MSI file - if selecting the option of "just for me", then during the setup there is a prompt to find the MSI file and even if giving it the path to the caldav MSI file - it is not accepted and the setup is blocked and fails.
Only when selecting the "for everyone" option - it finishes successfully.
This on Windows 10 64 bit build 1809.

**Comment by phw198** [comment]
Something tells me you're posting to the wrong project.

OGCS hasn't reached version 3.6.2, doesn't have an MSI or an option to install "for everyone"...

**Comment by eitancaspi** [comment]
Right... sorry, stupid of me. Sorry!
