### ISSUE TITLE
How to sync from outlook to google replacing with outlook default reminders

### ISSUE THREAD

**Issue by thomasjmartin** [phw198/OutlookGoogleCalendarSync#774]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\I am trying to use the program to create additional noticications not avaliable in outlook. I would like to have a 15 minute, 5 minute, and 2 minute notification for each calendar event. I have gotten 15 minute notificaitons of conference call and get sidetracked and forget to call in. Is this possible to sync all events using google calendar default new notifications? I see I can replace when outlook has no default reminders but I would like to keep the default outlook reminder as well if possible.

**Steps to Reproduce the Issue**  
1. \This is a feature issue not a software error.

**Any other information**  
\None.

**Comment by phw198** [comment]
You cannot sync the Outlook reminder _and_ use the Google defaults, but you can:
1. Set up the notifications on the Google calendar: 2,5,15 minutes
1. Configure OGCS to not sync reminders, but use the Google default
![image](https://user-images.githubusercontent.com/11843015/61081820-1503f380-a420-11e9-9d5e-253641885f42.png)

HTH

**Comment by ddevinatea** [comment]
Hi, when I create a meeting in Outllok with my work account with a reminder/notification, it does not sync the notification to google. when i enter to the synced meeting in google calendar it does not have any reminder o notification.

Is there a way to sync the outlook notifications to google?

Please advise,

Thanks

**Comment by phw198** [comment]
@ddevinatea Check the `Reminders` box under `Settings` > `Sync Options` > `What`. See the [user guide](https://phw198.github.io/OutlookGoogleCalendarSync/guide/syncoptions#what) for more details.
