### ISSUE TITLE
Recurring event doesn't sync last event

### ISSUE THREAD

**Issue by spilarek** [phw198/OutlookGoogleCalendarSync#775]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
When syncing a recurring task from Outlook to Google for 2:30pm Mon and Wed (15th and 17th), the Mon event shows, but the Wed event doesn't. The Outlook event is set to repeat until 17th.

Clicking the event in the Google calendar shows a message about changing the current event or all events, so it knows it is a recurring event. Editing the event and changing the end date to 18th shows the event on the 17th, changing the end date back to 17th hides it again.

**Steps to Reproduce the Issue**  
1. Create a recurring event in Outlook. Mine is set as "Occurs every Monday and Wednesday effective 15/07/2019 until 17/07/2019 from 2:30 PM to 3:00 PM"
1. Configure OGCS to sync from Outlook->Google (probably not relevant, that's how mine is configured).
1. Do a manual sync.
1. Check Google calendar. Mine had the 2:30 PM event on Monday, but nothing appeared for Wednesday.

**Any other information**  
I've been using OGCS for ages and this is the first time I've noticed this, possibly because it's new or I just never noticed before. I am leaning toward thinking this is a Google calendar bug, because it knows the hidden event is there, it's just not showing, but I wondered if maybe OGCS is interpreting "ending on 17th" to mean midnight on the 17th, making the 2:30pm event outside the range, and that might be confusing the Google calendar. Ending on the 17th should include any events until midnight on the 18th.

The same recurring event was sent to a colleague who is using OGCS v2.8.0.0, and he had the same issue. I have since upgraded to v2.8.0.0.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3385002/OGcalsync.log)

**Comment by brozono** [comment]
I would suggest looking at [Issue-636](https://github.com/phw198/OutlookGoogleCalendarSync/issues/636) there are some oddities with DST that have been slowly found and fixed.

There is a hotfix provided by Paul [here](https://github.com/phw198/OutlookGoogleCalendarSync/issues/636#issuecomment-508952791) in that thread that I suggest you try and see if that resolves your issue. Post back if it does or does not. The post has link to instructions on applying the hot fix.

**Comment by spilarek** [comment]
Thanks, Issue-636 looks like the same problem. We don't have DST in Qld Australia, but I applied Paul's hotfix and it resolved the issue.

Thanks @brozono and Paul.

Duplicate of #636
