### ISSUE TITLE
recurring events are duplicating... help!

### ISSUE THREAD

**Issue by michaeltm2** [phw198/OutlookGoogleCalendarSync#778]
how do i set this up properly so it doesn't happen? attached is my log
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3398622/OGcalsync.log)

**Comment by phw198** [comment]
Which recurring events? _All_ of them? If not, can you specify an example duplicate we can focus on?
Originating from which calendar - I see you have two-way sync configured. 
Duplicates appear where - Google or Outlook or both?

**Comment by michaeltm2** [comment]
I think I may have fixed it. For example, i was having trouble with the weekly fixed income meeting (Wednesday’s at 10 am) originated from outlook (I was united to a group meeting by someone else). 

Michael Meltzer

T: +1.917.653.6206 
E: michael.t.meltzer@gmail.com

On Jul 16, 2019, at 6:09 PM, Paul Woolcock <notifications@github.com> wrote:

Which recurring events? All of them? If not, can you specify an example duplicate we can focus on?
Originating from which calendar - I see you have two-way sync configured.
Duplicates appear where - Google or Outlook or both?

**Comment by phw198** [comment]
Thanks for the update - looks like you resolved it, so I'll close the ticket :+1:
