### ISSUE TITLE
Migrate OGCS to GitHub or BitBucket

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#78]
CodePlex is shutting down, and the excellent OGCS tool should migrate to a new
home  
  
[ https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/
](https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/)  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 498](http://outlookgooglecalendarsync.codeplex.com/workitem/498)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Apr 18 at 2:14 PM
**Reported by:**	kennethburgener
**Updated on:**	May 6 at 9:57 PM
**Updated by:**	phw198

**Comment by phw198** [comment]
On *2017-04-26 07:41:48 UTC*, **SeanKilleen** commented:

I'd be willing to help with this -- please feel free to ping me and we can get issues moved over, releases put up & backported, and the app updated to reflect the new home.
SeanKilleen@gmail.com or @sjkilleen on Twitter.

**Comment by phw198** [comment]
On *2017-05-07 04:57:55 UTC*, **phw198** commented:

Work is underway to get migrated to GitHub. 

@SeanKilleen - thanks for the offer. I think there should be tools (some level of export/import) to assist the migration, but I'll let you know if I could do with an extra pair of hands!

**Comment by phw198** [comment]
CodePlex project site is now read-only. Still work to do around documentation for GitHub project site...

**Comment by SeanKilleen** [comment]
@phw198 if you want:

* Enable the Wiki
* Lock edits of the Wiki down to collaborators
* Add me as a collaborator

And I can move over the documentation & convert it to Markdown.

Plus, I'd suggest adding a README.md that will surface some of that information on the main screen of the repository.

Long-term, you might want to move to a static site hosted via Github Pages. Makes it much easier for folks to maintain docs on your behalf.

**Comment by phw198** [comment]
v2.5.1 has finally freed OGCS from the chains of CodePlex :tada: :balloon:
