### ISSUE TITLE
New laptop setup

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#781]
I am using version 2.8.0 with outlook 2013.  After getting OGCS installed, everytime I click on the icon - it also brings up Outlook 2016 setup window.  I don't have Outlook 2016 - only 2013!!

Unsure why it is acting this way.  Worked just find on old laptop using the same version & the same outlook.

I have nothing to attach at this time but hope you can help since i love using this product to keep my life in order:)

**Comment by phw198** [comment]
Your log file would still be helpful, but you must have at least the Outlook 2016 setup files on your system for OGCS to somehow be calling it. Have you tried stepping through the upgrade and start using 2016?

Otherwise, maybe make sure your have Outlook 2013 open first before then opening OGCS?

**Comment by michgal2k** [comment]
Here is the logfile. 

I did just change the setting to start 60 seconds after opening up Office 2013.  I do not want to pay to upgrade to 2016.

Let me know what you find out from logfile

**Comment by phw198** [comment]
:paperclips: Files can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by michgal2k** [comment]
Sorry -
[OGcalsync log 0719.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3414604/OGcalsync.log.0719.txt)

**Comment by phw198** [comment]
Thanks. Did the new laptop come with Office pre-installed? Do you know which license it came with? If it was Office 365, then as per [this article](https://www.howto-outlook.com/howto/outlook2016upgrade.htm#postpone) I think upgrades are forced on you (could be postponed until September 2016.

Regardless, I can't see there's anything I can do about this - hopefully making sure Outlook is started before OGCS works around avoiding the upgrade...

**Comment by michgal2k** [comment]
I believe a trial of Outlook 365 came with the laptop.  I did not install it. Rather I installed Office 2013 since that is what I have a license for. 

I believe changing the setup of OGCS to start 60 seconds after Outlook, it appears to have helped.

Thanks Paul

**Comment by phw198** [comment]
Cheers - with that workaround then, I'll close the ticket.
