### ISSUE TITLE
The requested registry access is not allowed

### ISSUE THREAD

**Issue by fib0207** [phw198/OutlookGoogleCalendarSync#782]
**OGCS Version**: v2.7.9
**Installed or Portable**: Installed

**Problem Description**  
Staring OGCS i get the error:
Application unexspectedly terminated

"Der angeforderte Registrierungszugriff is unzulässig"
translated
"The requested registry access is not allowed"

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by fib0207** [comment]
Pleased find herewith the logfile. 

Thanks for supporting.

Frank

**Comment by phw198** [comment]
:paperclips: Sorry, files can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by fib0207** [comment]
here  now the file
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3418292/OGcalsync.log)

**Comment by phw198** [comment]
:package: This should now be handled with [v2.8.0.15.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3438383/v2.8.0.15.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes and post your logfile again if you can.

**Comment by fib0207** [comment]
Hi Phil
unfortunately the same result,
Please find attache the latest log file.
I'll be on vacation for the next three weeks. - just to let you know. :)


[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3439120/OGcalsync.log)

**Comment by phw198** [comment]
Thanks @fib0207, your log looks good to me as it's caught the error and letting you continue. 

Will improve it slightly further now I know the exact error from your latest log...

**Comment by phw198** [comment]
As you're off on hols, will take this straight into the next release.
