### ISSUE TITLE
Registry Error - cannot do a repair

### ISSUE THREAD

**Issue by aaaa41** [phw198/OutlookGoogleCalendarSync#783]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\When I open the program, I get the error that "A problem was encountered with your Office install. Please see the wiki for a solution. [0x80004002]. I am running this on a corporate computer. I tried running the Office repair as instructed, but when I go to Uninstall a Program -> Change a box pops up that says "Setup is preparing the necessary files." but then nothing ever happens. I am unable to run a repair. Is there some other way to fix this through registry editor?

**Steps to Reproduce the Issue**  
1. Open OGCS.

**Any other information**  
\N/A

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3412279/OGcalsync.txt)

**Comment by phw198** [comment]
:package: Please could you apply [hotfix v2.8.0.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3413589/v2.8.0.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and then try:

1. Running OGCS when Outlook is already open.
1. Running OGCS with Outlook shut down.

Hopefully the hotfix will record some extra information for me, and may also return a different error code too. Please upload your `OGcalsync.log` file again once you've tested it as above.

Thanks!

_[#752]_

**Comment by slashsteve** [comment]
I am having the same issue.  I am running Outlook from o365 - Version 1907 (Build 11901.20156 Click-to-Run)

I have attached my logfile with both scenarios

/steve
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3438449/OGcalsync.log)

**Comment by phw198** [comment]
:package: This should now reliably report the correct error being encountered with [hotfix v2.8.0.16.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3438598/v2.8.0.16.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

@slashsteve Please let me know if this hotfix takes you to the wiki for [0x80029C4A](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary)

**Comment by slashsteve** [comment]
Hi Paul

It does indeed take me to 0x80029C4A.

I’m heading out for vacation until mid-Aug.  I’ll try the registry hack when I get back.

Thanks
/steve

**Comment by phw198** [comment]
Thanks @slashsteve - I've marked this issue as resolved, as OGCS is now reporting the correct error code. Finger crossed the wiki'd fix works for that code... :crossed_fingers:
