### ISSUE TITLE
Sync without install

### ISSUE THREAD

**Issue by pabloreadi** [phw198/OutlookGoogleCalendarSync#784]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Hello, I use outlook on web and gmail too. How can I use your aplication without install de software in my pc?

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by mmangelsdorf** [comment]
Hi @pabloreadi !

It seems like you want to sync your Outlook.com Calendar (http://calendar.live.com) calendar with your Google Calendar (https://calendar.google.com).

If that's the case, this software is not right for you and also not needed.

The purpose of OutlookGoogleCalendarSync is to synchronize a _local_ Outlook calendar (i.e. in Outlook that is _installed on your computer_) to Google Calendar.

To still achieve your desired synchronization, you can find hints here:  
https://answers.microsoft.com/en-us/outlook_com/forum/all/how-to-sync-a-outlookcom-calendar-with-gmail/96799bdb-d2e3-44b8-a8f8-afef8826914b

Hope this helps!  
Marcus
