### ISSUE TITLE
Appointments saved/synced to wrong time after temporary timezone change

### ISSUE THREAD

**Issue by namkce** [phw198/OutlookGoogleCalendarSync#785]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Appointments syncing with/to wrong time zone in Google Calendar (aka 1pm CST appointment becomes 3pm CST)

**Steps to Reproduce the Issue**  
1. Have a bunch of appointments in CST
2. Change your computer timezone from CST to PST
3. Change your google calendar timezone from CST to PST
4. Sync
5. Change back to CST on computer (and google)
6. create appointment and Sync
7. Observe created appointments from sync, notice they're off by 2 hours

**Any other information**  
\I went on a business trip to the west coast, changed my computer timezone from CST to PST... then after a week, returned back to my home office (CST) and changed my computer and google calendar timezones back from PST to CST... however, all my appointments are now off by 2 hours.  When I sync, it's putting them in 2 hours later than they should be.  It's DRIVING ME NUTs!  I wish I had better repro steps, but it's tough, cause my schedule is messed up enough already.  

It also doesn't seem to make sense... it's as if it's taking the dates incoming as PST and converting them to CST, even though they're CST to begin with.  I'm not sure if it's the sync tool doing this, or the Google Calendar doing this.  So an outlook appointment at 1pm CST becomes a google appointment at 3pm CST with this sync tool.  Changing my computer time to PST just makes it 5pm instead.  Changing my google calendar to PST puts them at the right "local" time (1pm), but then it's in PST, not CST.  I don't know how to fix this.

I might just uninstall and reinstall to see if that fixes the issue.  Has anyone else encountered issues when they do business trips in a different time zone??

**Comment by phw198** [comment]
Can I ask what version of OGCS you're running?

Are previously synced events all off by two hours, or just newly synced events?

**Comment by namkce** [comment]
@phw198 

Version: 2.7.0.0.  
Timezone DB: 2019b
Running Windows 10, version 1903

When I click the "Check for Update" button, I get an error message dialog box titled "Check Failed" and message of "Unable to check for new version.".  

It seemed to be changing my new stuff and anything I already had on the calendar in the future.  I decided to disable it for now till I figure things out.  Basically, I'd end up two appointments, one at the right time (on outlook), and one 2 hours later (on google)...  I primarily schedule my appointments in outlook and have it one way sync to google.  I don't sync from google to outlook, in part because I don't want my private appointments (on google) to show up in my work (on outlook) calendar.  Entire goal of my sync process was make sure my personal calendar included my work related events.

**Comment by namkce** [comment]
BTW, I think I might close this issue... as it seems to be working fine now!  

I resumed sync this afternoon, and tested a few appointments, and they are showing up in the correct timeslot in my Google Calendar.  **I'm suspecting that this issue was a temporary glitch/issue with my Google Calendar, and not with the sync tool,** as nothing really changed with my machine configuration wise (other than a few reboots since yesterday).  I'll keep an eye on it for the next few days and see if it happens again.

**Comment by phw198** [comment]
Thanks for the update, and glad it seems to have resolved itself.

The failure to automatically upgrade is known issue #497 - I'd still recommend upgrading to v2.8 to make sure you're getting all the newest features and bug fixes :slightly_smiling_face:

**Comment by brhahlen** [comment]
I am acutally experiencing the same issue right this moment.
I was in EST last week, but am in CET again today, but now some of my appointments are 6 hours too early in Google Calendar.

**Comment by brhahlen** [comment]
Okay, so forcing a full sync fixed it.
