### ISSUE TITLE
Syncs take hours, abort and never complete without error

### ISSUE THREAD

**Issue by RHeggem** [phw198/OutlookGoogleCalendarSync#789]
----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
Syncs take hours, abort and never complete without error.

**Steps to Reproduce the Issue**  
1. Press the Sync button

**Any other information**  
Log files attached
I tried to upload the Alpha version, but apparently, I have the latest version already.

[OGcalsync.log.2019-07-28.1.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3443713/OGcalsync.log.2019-07-28.1.log)
[OGcalsync.log.2019-07-28.2.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3443714/OGcalsync.log.2019-07-28.2.log)
[OGcalsync.log.2019-07-28.3.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3443715/OGcalsync.log.2019-07-28.3.log)
[OGcalsync.log.2019-07-28.4.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3443716/OGcalsync.log.2019-07-28.4.log)
[OGcalsync.log.2019-07-28.5.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3443717/OGcalsync.log.2019-07-28.5.log)
[OGcalsync.log.2019-07-28.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3443718/OGcalsync.log.2019-07-28.log)
[settings.xml.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3443719/settings.xml.log)

**Comment by phw198** [comment]
So the first thing that jumps out at me is that between now and 27 September (60 days) you have 3500 Outlook calendar items?! Does that sound right? Note, this will include recurring series that span those two months.

If you do have that number, then you'll need to reduce the date range you're syncing. I think other errors that then occur (eg "The operation failed.") is because there are so many items being accessed.

Try dropping the sync date range to just a today and then providing the logfile from that...

Also Push Sync is pointless as it's taking so long to sync - turn off Push sync and schedule a sync every 2 hours (or an interval longer than a sync takes).

**Comment by RHeggem** [comment]
Hi Paul,

Thank you for responding so quickly. Here are my comments:

- Yes, there are a lot of calendar items, mostly birthday and anniversary events. Somehow almost all of them are duplicated and so I want to merge them or delete the duplicates. I am doing that by hand for now, but that is laborious.

- I changed the date range to just today (0 days in the past, 0 days in the future)

- I turned off Push Sync

- I still got errors

Find the latest log file attached.

~ Rick

**Comment by RHeggem** [comment]
Hi Paul,

A slight aside, but something else is broken. Note the image below.

Note that the next scheduled sync is in the past. I took this shot around 8:25 PM. Interestingly, earlier in the evening the next scheduled time kept updating from 7:xx PM to 8:xx PM to 9:xx PM. Why it went backward is beyond me. Thought you’d want to know.

~ Rick

**Comment by RHeggem** [comment]
Continuing to get streams of errors. Latest log file attached.

**Comment by phw198** [comment]
Reducing the sync date range to just today won't necessarily get rid of the errors, but it should help identify what the real problems are more easily.

How did these duplicates occur and where are they? Only in Google, Outlook or both? Did OGCS create these duplicates? I think it would also be best to only sync in one direction until the errors have been resolved and the duplicates removed. In Outlook the quickest way to delete them is probably change the view to "List" and then select each one while pressing `Ctrl`.

>kept updating from 7:xx PM to 8:xx PM to 9:xx PM. Why it went backward is beyond me.

That looks like going forwards to me. And if your scheduled interval is less than the time it's taking for a sync to complete, the next scheduled sync being in the past would make complete sense.

:paperclips: Files can't be attached to the ticket when replying by email so none of your screen shots or log files are coming through. Please log in to GitHub to upload files.

**Comment by RHeggem** [comment]
Hi Paul,

- I have been able to run some syncs successfully so I opened the date range to 7 days in the past and 60 in the future.

- The duplicates have been there for some time and are not the result of OGCS. I have manually removed all of the duplicates for the entire year.

- I will attach the latest log file to the GitHub site

I appreciate your help.

Cheers!

~ Rick

**Comment by RHeggem** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3454020/OGcalsync.log)

**Comment by phw198** [comment]
It looks like all the failures left are Outlook failing to query the categories. Again, I don't know why this is as it just gives a useless "The operation failed". I think your best bet might be to turn off syncing colours/categories?

**Comment by RHeggem** [comment]
I turned off USE GOOGLE DEFAULT  and ran. Still had problems. Turned off COLOURS/CATEGORIES as you suggested and it ran without an error. Too bad the categories don’t sync.

**Comment by phw198** [comment]
I don't believe syncing reminders was causing any problem, just the categories. I don't know why your particular Outlook if having problems with that though, so don't think I'll be able to provide a fix :slightly_frowning_face:
