### ISSUE TITLE
Reminders not syncing

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#79]
Not sure what I did. I have been using this for some time without major
issues. I changed "something" and I am not sure what I did.  
  
I create an OUTLOOK event at work, which has a default 15 minute reminder for
it. I get a reminder AT WORK from Outlook.  
  
However, when I look at my GOOGLE CALENDAR the reminder is missing and of
course if it missing on my phone google calendar.  
  
This used to work. I got a new phone S8+ and everything was fine. Then I
discovered the DND option in settings and selected it and set a time range of
11pm to 7am.  
  
I "think" that is when I lost ALL my reminders.  
  
I disabled that setting, but still reminders are getting stripped.  
  
I see in the log displayed with it synced  
Reminder 15 =&gt; removed  
  
Not sure how to fix this, but need to as I am missing meeting when I am not at
my desk because I am not getting reminders.  
  
Help??  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 500](http://outlookgooglecalendarsync.codeplex.com/workitem/500)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 28 at 12:36 PM
**Reported by:**	BillyJIV
**Updated on:**	Thu at 6:28 PM
**Updated by:**	elizabethmcintosh

**Comment by BillyJIV** [comment]
I see that a beta 2.4 was released. I downloaded and installed it. The Reminders are still getting stripped out during sync. I disabled the DND (which I really need) Just wanted to let you know.

**Comment by phw198** [comment]
Thanks for the update - will try and prioritise a fix for this in the next release.
However, this looks to be a duplicate of issue #70, so to keep things clean, please follow updates there and I'll close this issue.

**Comment by phw198** [comment]
@BillyJIV Have you been able to take a look at issue #70 to confirm if that resolves the problem?
