### ISSUE TITLE
Com error 0x8000ffff

### ISSUE THREAD

**Issue by djjstew** [phw198/OutlookGoogleCalendarSync#790]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\won't start see error code above

**Steps to Reproduce the Issue**  
1. \<Update>
1. won't start
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3444949/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
```
2019-07-29 19:25:52,709 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 8000ffff Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)).
2019-07-29 19:25:52,710 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x8000FFFF;-2147418113
```
Wow, `8000ffff Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)).` doesn't sound good! Never seen that before 🙂 

Have you started off with an [Office Repair](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#office-repair)?

[This post](https://community.spiceworks.com/topic/1816077-an-unknown-error-occurred-error-code-0x8000ffff-outlook-2016) talks about recreating your profile (Windows profile I think it means, as opposed to Outlook mail profile, but you could try the mail profile first). Also at the bottom someone mentions avoiding extended charactersets in the profile name.
