### ISSUE TITLE
Bidirectional sync not working

### ISSUE THREAD

**Issue by christinemcclure** [phw198/OutlookGoogleCalendarSync#791]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0 - Beta
**Installed or Portable**: Installed

**Problem Description**  
\Have set up for bidirectional sync, but changes to Google calendar entry are not written to Outlook--they are removed. Have tried changing only the description, and the title and description, but only updates to Outlook entries are synced to Google.

**Steps to Reproduce the Issue**  
1. Set up bidirectional sync
2. Create Outlook entry and sync
3. Verify Google entry matches
4. Update Google entry
5. Sync -- entry does not match. 

**Any other information**  
\Happens both with single and recurring events.

**Comment by phw198** [comment]
:spiral_notepad: Please could you provide the `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) which covers the steps above - and let me know the calendar item's name and date you were testing with.

Thanks

**Comment by christinemcclure** [comment]
Link to Gist:
https://gist.github.com/christinemcclure/2eaa002187d21050a70b962ec5716cb1

Item name: Notes for April meeting (recurring event)
Date: July 30, 2019

Thanks,
Christine

**Comment by phw198** [comment]
I don't see any evidence of "Notes for April meeting" being created, synced or deleted - just that it gets compared and nothing's changed each time.

I do however see you created `08/01/19 1:00 PM => "testing from outlook"` in Outlook and OGCS synced this Google. On the next sync, Outlook's item is called "testing from outlook2" - is this the change you are saying doesn't get synced to Google?

**Comment by christinemcclure** [comment]
HI Paul-

Yes, that's correct. Whenever I make a change to the Google calendar entry,
it doesn't get reflected in Outlook.

Christine

**Comment by phw198** [comment]
What you've just said isn't what I'm seeing your log, or what I summarised in my previous post. I said
> On the next sync, Outlook's item is called "testing from outlook2" - is this the change you are saying **doesn't get synced to Google**?

which is not the same as 
> Whenever I make a change to the Google calendar entry, it **doesn't get reflected in Outlook**.

I can't troubleshoot something if you're not clear on the steps to replicate the problem and a log file that confirms it. Are you testing with "Notes for April meeting" or "testing from outlook2" and what are those exact test steps?

So far I have deduced:
1. Create single non-recurring entry in Outlook called "testing from outlook"
1. Two-way sync started
1. Item created in Google
1. _Something happens, most likely a manual update in Outlook to append "2"?_
1. Two-way sync started
1. The Outlook item is now showing as "testing from outlook2" but this hasn't been changed by OGSC
1. _No change made in Google, so assume it is already called the same in Google?_

Can you clarify point 4 and 7, please?

**Comment by christinemcclure** [comment]
Here is a clean version of the log from today
https://gist.github.com/christinemcclure/ae8bdbca744cadcd5cafd3b43b2d6c88

1. Created entry in Google calendar called "TEST - This item created in
Google"
2.  Created entry in Outlook called "TEST -- this item created in Outlook"
3. Ran sync -- both records appear in both places
4. Updated both entrues--from Google calendar only--to include a description
5. Ran sync -- blank description from Outlook overwrites the descriptions
added from Google.

**Comment by phw198** [comment]
I think what you're reporting is entirely expected given the configuration - in the "What" section next to "Description" you have "1-way: Outlook to Google" checked.

So yes, any changes in the Google description will get overwritten from Outlook. However, I don't exactly agree with your test above - point 5 wouldn't happen unless you modified the Outlook item more recently than the Google one. Your logfile also doesn't show the Google description getting reset to blank. So if we add step 4.1 "Edit the equivalent Outlook entry by appending something to the end of the subject", then step 5 is expected.

Uncheck 1-way sync of description. But beware, unless your Outlook descriptions are always plain text, HTML or rich text gets "corrupted" when synced to Google - so syncing this back to Outlook is probably not what you want to do...

**Comment by phw198** [comment]
:thought_balloon: I should probably add a tooltip on that checkbox to explain why it's checked...

**Comment by christinemcclure** [comment]
I hadn't realized that there were separate options for syncing the
different parts of the message. I'll set that up when I get to the office
tomorrow. Thank you.
