### ISSUE TITLE
Application fails at startup 

### ISSUE THREAD

**Issue by dbar9** [phw198/OutlookGoogleCalendarSync#793]
OGCS Version: v2.8.0.0
Installed or Portable: Installed

Problem Description
Application fails at startup with error OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The operation failed.

Steps to Reproduce the Issue
1. Open the application 
2. Splash screen comes up and log file displays with error

Any other information
Not sure if it's the reason for the issue - Outlook Version: 16.0.0.11901

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by dbar9** [comment]
Sent to you over email!

**Comment by phw198** [comment]
Is that to the email address on my GitHub profile? I've checked it and spam folders and can't see any email from you...

**Comment by dbar9** [comment]
yes, but I can add the link here as well - https://gist.github.com/dbar9/199fa3b26ace02368c71e408d5a9ed6b%C2%A0

**Comment by dbar9** [comment]
Try this instead, stripped my name and computer names for privacy purposes: 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3454268/OGcalsync.log)

**Comment by phw198** [comment]
It looks like you have a popup asking if you want to automatically report errors, and until you respond to this, the complete error won't get logged. Currently it has only logged `System.Runtime.InteropServices.COMException: The operation failed.` - I'm hoping there might be something more useful following that!

Could you accept or deny the automatic error reporting window and then provide your log file again?

Thanks!

PS Also, v2.8.1 is out now, if you could try that please.

**Comment by codahq** [comment]
I'm having this issue as well or one similar.  I emailed the email in your github profile a log.  I think it is crashing during the first time sync.  I have OGCS Version: v2.8.1.0 installed.  Outlook version is Version 1902 (Build 11328.20368 Click-to-Run).

Also, I'm not sure if you've noticed but your release for 2.8.1.0 alpha doesn't have a .exe install file like normal so it's hard to reinstall.

**Comment by phw198** [comment]
@codahq I've got the email, but there's no errors caught in your gist - did you upload the whole file?

**Comment by codahq** [comment]
Yep.  I thought it was weird also.  If I attempt to start it again the exact same log is produced with different time stamps.  Before I rolled back to 2.8.0.0 I had a log file with the sequence I provided you repeated twice.  It would go to that spot and quit without logging an error. 

It's hitting an exception because it's offering to debug rather than closing gracefully.

By the way, reinstalling 2.8.0.0 has stopped the issue.  I'm not sure if it's because I reinstalled or because the issue does not exist in 2.8.0.0.  I can update to 2.8.1.0 later and let you know if the issue comes back.

**Comment by phw198** [comment]
@codahq  Oh wow! v2.8.1 is still in draft (after I backported a fix I think) and the project homepage is 404ing for the release binaries 😱  I'll fix that this evening!

**Comment by phw198** [comment]
@codahq You should now be able to download the `setup.exe` for v2.8.1, if you could install that and give it another try. If it does crash out could you get the window stack trace and/or Windows application event log for it?

**Comment by codahq** [comment]
Still crashes.  Emailed you application events.

**Comment by phw198** [comment]
Thanks - stack trace is:
```
Application: OutlookGoogleCalendarSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.getCalendarClientSecrets()
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.spawnOauth()
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<GetAuthenticated>b__14_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.8.1.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3479013/v2.8.1.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes ASAP - I'd like to get this back-ported into v2.8.1.0...

**Comment by codahq** [comment]
Issue is not fixed on hot fix.  Sent application logs.

**Comment by phw198** [comment]
@codahq Looks like the original issue is resolved and this is a brand new issue:
```
Application: OutlookGoogleCalendarSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at OutlookGoogleCalendarSync.TimezoneDB..ctor()
   at OutlookGoogleCalendarSync.TimezoneDB.get_Instance()
   at OutlookGoogleCalendarSync.Program.Main(System.String[])
```
Can you provide your OGcalsync.log file and also check if you have the following files in the same diretory as `OutlookGoogleCalendarSync.exe`:
* tzdb.nzd
* NodaTime.dll

**Comment by codahq** [comment]
No need.  Since you only packaged the .exe I didn't think anything with the other binaries had changed.  I had tried the hotfix with version 2.8.0 beta and it crashes there.  If I try the hotfix with 2.8.1 alpha (because apparently some of the binaries were updated) it doesn't crash on startup and appears to login and check entries correctly.

**Comment by phw198** [comment]
Yes, v2.8.1 had nearly all the 3rd party DLLs updated - and I think NodaTime was a major release with breaking changes in it, so not surprised it complained. 

I'll add some handling though, so it doesn't crash out quite so badly...

**Comment by phw198** [comment]
:loudspeaker: This hotfix has been backported to v2.8.1.0.
