### ISSUE TITLE
Application Unexpectedly Terminated

### ISSUE THREAD

**Issue by suyashbansal** [phw198/OutlookGoogleCalendarSync#794]
**OGCS Version**: v2.8.1 Alpha  
**Installed or Portable**: Installed

**Problem Description**  
Application fails to start. Gives an error message "Object reference not set to an instance of an object".

**Steps to Reproduce the Issue**  
1. Open the Application from the Desktop shortcut.
1. Splash screen comes up and log file displays with error (But only once after you install the software)
1. Gives a alert box "Application Unexpectedly Terminated" with the error message "Object reference not set to an instance of an object".

**Any other information**  
Running Outlook with Office 365 version 1808 (10730.20360)
OGcalsync.log file - [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3463765/OGcalsync.log)
Error Screenshot: See below
![image](https://user-images.githubusercontent.com/5832436/62411418-01f3d600-b610-11e9-9bc1-cb71b2ac19f7.png)

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.8.1.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3464836/v2.8.1.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

I will backport this into v2.8.1.0 anyway...

**Comment by suyashbansal** [comment]
I've not tried this hotfix as I'm pretty happy with my current configuration of v2.8.0. But I really appreciate your quick response and the provision for a hotfix. Thanks for the amazing software. Totally a life saver! :satisfied:
