### ISSUE TITLE
Error when attempting to sync: Item already added. Key in dictionary: LogAs Key being added: LogAs

### ISSUE THREAD

**Issue by invalidCards** [phw198/OutlookGoogleCalendarSync#797]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.1.2
**Installed or Portable**: Installed

**Problem Description**  
Whenever I try to sync (Outlook -> Google), I get an error. This error is in my native language, not the language of OGCS, which makes me think it is a .NET error rather than one that is given by the application itself.

Native text (Dutch):
```
Item is al toegevoegd. Sleutel in woordenboek: LogAs Sleutel die wordt toegevoegd: LogAs
```

Crude translation:
```
Item already added. Key in dictionary: LogAs Key being added: LogAs
```

Failed in 2.8.1.0, attempted to fix by installing hotfix .2, but to no avail.

**Steps to Reproduce the Issue**  
Honestly, I don't know. I have no idea what is causing this issue.

**Any other information**  
Here's the log: 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3480173/OGcalsync.log)

**Comment by phw198** [comment]
Thanks for reporting.

:package: This should now be resolved with [hotfix v2.8.1.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3480614/v2.8.1.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by 8restcoop8** [comment]
@phw198 I was having the same issue and 2.8.1.3 fixed it for me.  Thanks for the quick fix!

**Comment by phw198** [comment]
:loudspeaker: This hotfix has been backported to v2.8.1.0.
