### ISSUE TITLE
Past recurring events duplication in Outlook

### ISSUE THREAD

**Issue by jjkober** [phw198/OutlookGoogleCalendarSync#799]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.1.0 
**Installed or Portable**: Installed

**Problem Description**  
Recurring events, seemingly those that have experienced changes in the past, duplicate on past dates, resulting in dozens of copies of the same event.

**Steps to Reproduce the Issue**  
1. Deleted all copies of 21-June events at 3pm PDT - Title: "Jim/Steve - Sales Rep Exec Sponsorship Bi-weekly Mtg."	Verified that Google Calendar shows ONE event on this date.
1. Turned on CSV capture in OGCS and increased logging level to FINE
1. Sync'd and confirmed a new event on 21-Jun had been created with a recurrence period of 26-April to 21-June
1. Sync'd a second time and there were now THREE events
    1. Two events showed a recurrence period of 26-April to 21-June, 
    1. A third showed a recurrence of 21-June to 13-Sept.
1. I emailed two sets of logs and CSVs

**Any other information**  
Added by @phw198 
* Syncing O<-G->O
   * G is common calendar to two different O calendars
   * G calendar ID has changed name from mesosphere to d2iq
* At some point is seems two-way sync was configured (some G items have O IDs stored)

**Comment by phw198** [comment]
Focusing on step 3 above and `Jim/Steve - Sales Rep Exec Sponsorship Bi-weekly Mtg.`

There are multiple Outlook recurring series for this meeting

:radio_button: 4/26/2019 3:00 PM - G ID = `6lpf7a5nnns4ikggg53lrmnar0`
RRULE = `FREQ=WEEKLY;WKST=SU;UNTIL=20190621T065959Z;INTERVAL=2;BYDAY=FR`
:star: This is the one that got created in step 3. This is correct.
This has been two way synced at some point - holds Outlook IDs:
```
outlook_CalendarID=00000000A43E6F927FEF02458CD60A05FC0C3BA5A2840000
outlook_CalendarID-01=00000000F98CF9AC087E0F4BADAF79194944CDE301003FB1D9A7C5501E4F8C43382EAC659C5C0000000000000000
outlook_CalendarID-02=00000000A43E6F927FEF02458CD60A05FC0C3BA5A2840000
outlook_EntryID=00000000A43E6F927FEF02458CD60A05FC0C3BA504392E00
outlook_EntryID-01=00000000F98CF9AC087E0F4BADAF79194944CDE307003FB1D9A7C5501E4F8C43382EAC659C5C0000000000000000F25D599A10C89E4396BEDE19B6E957FD0000000014900000
outlook_EntryID-02=00000000A43E6F927FEF02458CD60A05FC0C3BA504DF3000
outlook_GlobalApptID=040000008200E00074C5B7101A82E0080000000000000000000000000000000000000000320000007643616C2D55696401000000366C70663761356E6E6E7334696B67676735336C726D6E61723040676F6F676C652E636F6D00
outlook_GlobalApptID-01=040000008200E00074C5B7101A82E008000000000097B75B7B4ED50100000000000000001000000021D5E0FB06872842B2841B05841F6238
outlook_GlobalApptID-02=040000008200E00074C5B7101A82E00800000000B0B4E705A14ED5010000000000000000100000000BD77586A2A2634DBA87B530178ED26B
```
:radio_button: 6/21/2019 3:00 PM - G ID = `6lpf7a5nnns4ikggg53lrmnar0_R20190621T220000`
The entry on 8/2/2019 3:00:00 PM is deleted

:radio_button: 9/13/2019 3:00 PM - G ID = `6lpf7a5nnns4ikggg53lrmnar0_R20190913T220000`
The first entry of this recurring series is an exception with a different description.

**Comment by phw198** [comment]
@jjkober As I see it, 
* 4i in your OP is the problem being reported - a duplicate recurring series. 
* 4ii is expected as there's another recurring series in Google that starts on 21-Jun, whilst the other finishes on 21-Jun - they overlap?

Actually, no 4ii might be a timezone problem. 26-Apr series should run to `20190621T065959Z` and you're 7 hours bdehind GMT, so that's `20190620T235959`. I think this is related to #636, and as noted by @ThePsionic "I assume this is a mismatch between the way both calendar systems handle "until" dates, with Google cutting off before the start of the day, and Outlook afterwards."

I think v2.8.1 fixed syncing to Google, but has introduced a bug for syncing to Outlook.

**Comment by phw198** [comment]
Actually not quite the same problem that I thought, but I was on the right lines - the recurrence end time is the UTC value as calculated from the Google event's start timezone. So we need to convert the recurrence end time back to local time before using it.

:package: This [hotfix v2.8.1.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3489306/v2.8.1.4.zip) should stop your `4/26/2019 3:00 PM` recurring meeting showing on the 21-Jun ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please could you repeat exactly the same test as you did before and let me know how it goes - I suspect the appointment might still get duplicated, but at least finish on the right day now. If so, please provide your log and CSV files again.

**Comment by jjkober** [comment]
Test completed and results mailed.  21-Jun event was recreated with a recurrence range of 21-Jun to 27-Sept on first run.  No duplicate events were created on second run. Looks like things are now behaving as expected - thanks!  Let me know if you want to test anything else.

**Comment by phw198** [comment]
Fantastic! I was quietly hoping that it might have fixed the duplicate problem as well :grinning:

**Comment by phw198** [comment]
This'll close automatically when it's released in the next alpha.
