### ISSUE TITLE
"Updated google event faield to save"

### ISSUE THREAD

**Issue by rmdodhia** [phw198/OutlookGoogleCalendarSync#800]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I get errors every time OGCS syncs, and it's always "Updated Google event failed to save, Continue with synchronization?"
~~This is the same issue as https://github.com/phw198/OutlookGoogleCalendarSync/issues/736
but I couldn't see any solution.~~

**Steps to Reproduce the Issue**  
Event created in outlook, synching to google.

**Any other information**  
[OGcalsync.log.2019-08-10.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3490266/OGcalsync.log.2019-08-10.txt)

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to the latest release, [v2.8.1.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.8.1-alpha/Setup.exe), and confirm if you can still replicate the issue. If you can, please re-upload your logfile.

**Comment by Danabw** [comment]
Updating to 2.8.1.0 fixed my issue w/this "Updated Google event failed to save, Continue with synchronization?" error.  Thanks! 

Screen shot of the error in sync screen and log file attached in case it's useful. 

![2019-08-15 08_14_18-Outlook Google Calendar Sync](https://user-images.githubusercontent.com/24300160/63106109-fb7e2c00-bf36-11e9-81e1-c8d2e4964e3b.jpg)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3506080/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3506081/OGcalsync.log)
