### ISSUE TITLE
Forced to "disconnect" and "retrieve" on every startup

### ISSUE THREAD

**Issue by echoblaze** [phw198/OutlookGoogleCalendarSync#803]
**OGCS Version**: 2.8.0.0
**Installed or Portable**: Installed
**Problem Description**  
Every time I start up, there are Google sync errors. I have to "Disconnect Account" for Google, then "Retrieve Calendars", grant permissions, then Google sync will work again.

**Steps to Reproduce the Issue**  
1. Start up "Outlook Google Calendar Sync"
2. Google sync errors
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3506122/OGcalsync.log)
 

**Any other information**  
Attached log file

**Comment by phw198** [comment]
OGCS is failing to talk to the internet entirely - not just for stuff that requires authentication. Try setting a delay on startup as Outlook is not available to be talked to either - give OGCS 5 minutes for your system to settle down after login...

**Comment by echoblaze** [comment]
Thanks ! Looks like it's working now
