### ISSUE TITLE
Accepting invite to reschedule meeting doesn't delete old

### ISSUE THREAD

**Issue by eocactus** [phw198/OutlookGoogleCalendarSync#804]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
When I accept an invitation that revises a meeting time, the new meeting time appears on my calendar but the old meeting remains.  I have the synch settings set to prompt me to delete, but I am never prompted.   The invites I'm receiving are sent via Gmail.  Gmail online calendar handles rescheduling properly (ie. delete's the old time and recreates new time).

A recent example is in the attached log file.   High Rock meeting rescheduled from 11am 8/14 to 11am 8/16.  

**Steps to Reproduce the Issue**  
1.  Have someone send a calendar invite via Gmail and you accept in Gmail.
2.  Sync with Outlook
3.  Have someone send a revised calendar invite for same meeting in Gmail and you accept in Gmail,
4.  Sync with Outlook

**Any other information**  
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3506307/OGcalsync.txt)

**Comment by eocactus** [comment]
OGCS Version: v2.8.0.0
Installed or Portable: Installed

Problem Description:
When I accept an invitation that revises a meeting time, the new meeting time appears on my calendar but the old meeting remains.  I have the synch settings set to prompt me to delete, but I am never prompted.   The invites I'm receiving are sent via Gmail.  Gmail online calendar handles rescheduling properly (ie. delete's the old time and recreates new time).

A recent example is in the attached log file.   High Rock meeting rescheduled from 11am 8/14 to 11am 8/16.  

Steps to Reproduce the issue:
1.  Have someone send a calendar invite via Gmail and you accept in Gmail.
2.  Sync with Outlook
3.  Have someone send a revised calendar invite for same meeting in Gmail and you accept in Gmail,
4.  Sync with Outlook


[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3506307/OGcalsync.txt)

**Comment by eocactus** [comment]
Same situation today (the time of a meeting changed), but this time it worked fine.  The difference was that I accepted the revised invitation within Outlook rather than within Gmail.  Attaching log.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3510640/OGcalsync.log)

**Comment by phw198** [comment]
When an instance of a recurring meeting is changed, there is no deletion and creation that takes places - in Outlook a new exception instance is created within the recurring series. It's just not possible for there to exist both the original instance _and_ the exception at the same time in Outlook.

This as shown in your log of the updates (not delete, create):
```
2019-08-13 13:25:32,342 DEBUG  8 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring Google event with 2 exceptions in the sync date range.
2019-08-13 13:25:32,354 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing >> 8/16/2019 11:00 AM (R) => "High Rock + SEED SPOT"
2019-08-13 13:25:32,394 DEBUG  8 OutlookGoogleCalendarSync.Console [0] -  8/16/2019 11:00 AM   "High Rock + SEED SPOT"
2019-08-13 13:25:32,394 DEBUG  8 OutlookGoogleCalendarSync.Console [0] -  AttributeChangeStart time8/14/2019 11:00:00 AM → 8/16/2019 11:00:00 AMEnd time8/14/2019 12:00:00 PM → 8/16/2019 12:00:00 PMDescription──────────  Corinn Perry is inviting you to... → ──────────Corinn Perry is inviting you to a ...
2019-08-13 13:25:32,452 DEBUG  8 OutlookGoogleCalendarSync.Console [0] -  3 attributes updated.
```

However, you then said you "accepted the revised invitation within Outlook" - this rings warning bells to me. Do you have Outlook picking up your Gmail email? In which case I suspect Outlook is putting the invite it sees for the meeting change into Outlook calendar, and OGCS also syncs the Google calendar to Outlook, thus creating a duplicate...? That wouldn't be the fault of OGCS if that is your setup.

**Comment by eocactus** [comment]
Hi,

In answer to your question, yes, I am using MS Outlook for both gmail email and calendar.  I would have thought this is the norm.  As I stated, there is no duplicate when I accept the calendar change invite within Outlook; it seems to only happen when I accept the calendar change invite within the online Gmail instance.

**Comment by phw198** [comment]
> I would have thought this is the norm.

Very doubtful. I would say the norm is to connect Outlook to a corporate Exchange account and sync that calendar to Google calendar via OGCS. That's the reason OGCS was developed at any rate.

It sounds like you have connected Outlook to Gmail via IMAP for email and then, because that protocol doesn't include calendars, you want to sync Google's calendar to a standalone Outlook calendar with OGCS? As I say, oddities with how Outlook handles invitations it sees in Gmail via IMAP whilst also accepting the invite in Gmail (and syncing the result with OGCS) does not particularly surprise me. 

I would bet that if you didn't sync your gmail to Outlook and just accepted invites in Google, you wouldn't see the duplicates. If I get some time I'll try and prove out that theory...

**Comment by eocactus** [comment]
Regarding the use of Outlook, I would posit you have at least two types of users:  The first is someone with corporate Exchange who wants to bring in personal calendar appointments.  The second is someone who is using Exchange as a means to consolidate multiple email accounts and calendars in one place.  

Thanks for looking at the log.  The issue not a big deal to me, but I thought I'd provide feedback in return for using the free software.
