### ISSUE TITLE
Google APIs returning 404 during authentication handshake

### ISSUE THREAD

**Issue by mjc9885** [phw198/OutlookGoogleCalendarSync#805]
**OGCS Version**: 2.8.0.0
  
**Installed or Portable**: Installed

**Problem Description**  
When attempting to retrieve Google calendars, the application is reporting a failure when attempting the handshake.

**Steps to Reproduce the Issue**  
1. Click Settings --> Google
2. Click on the Retrieve Calendars button

**Any other information**  
Internet Explorer is able to access the internet.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3506496/OGcalsync.log)

**Comment by phw198** [comment]
This matches another user who reported Google APIs returning HTTP 404s starting on the 7-Aug. 

Theirs was slightly different, with https://www.googleapis.com/oauth2/v2/userinfo failing to return, whilst yours is https://www.googleapis.com/calendar/v3/users/me/settings/useKeyboardShortcuts - both are called in the handshake phase. You both appear to be in the US too, not sure if that's relevant yet.

Under `Settings` > `Google` > `Advanced options` can you try setting the following:
* Client ID = `653617509806-2nq341ol8ejgqhh2ku4j45m7q2bgdimv.apps.googleusercontent.com`
* Secret = `tAi-gZLWtasS58i8CcCwVwsq`

Does this allow you to connect OK?

**Comment by mjc9885** [comment]
Thanks for the reply.  I tried a couple times to get it but I'm still getting the same handshake error.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3507951/OGcalsync.log)

**Comment by phw198** [comment]
Could you open up a `cmd` window, type `ping www.googleapis.com` and send me the response?

**Comment by mjc9885** [comment]
Interesting:
> ```
>C:\>ping www.googleapis.com
>
>Pinging www.googleapis.com [199.36.153.4] with 32 bytes of data:
>Request timed out.
>Request timed out.
>Request timed out.
>Request timed out.
>
>Ping statistics for 199.36.153.4:
>    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
> ```

**Comment by phw198** [comment]
As I suspected, your ISPs DNS is out of date - I don't think that IP is valid any more.

Mine resolves to 216.58.206.106 and if I do a reverse lookup on that, it gives:
```
LookupServer 427ms
  1  c.in-addr-servers.arpa  196.216.169.10  NON-AUTH  110 ms  Received 6 Referrals , rcode=NO_ERROR    216.in-addr.arpa. 86400	IN	NS	r.arin.net,216.in-addr.arpa.	86400	IN	NS	u.arin.net,216.in-addr.arpa.	86400	IN	NS	x.arin.net,216.in-addr.arpa. 86400	IN	NS	y.arin.net,216.in-addr.arpa.	86400	IN	NS	z.arin.net,216.in-addr.arpa.	86400	IN	NS	arin.authdns.ripe.net,  

  2  arin.authdns.ripe.net  193.0.9.10  NON-AUTH  79 ms  Received 4 Referrals , rcode=NO_ERROR    206.58.216.in-addr.arpa. 86400	IN	NS	ns1.google.com,206.58.216.in-addr.arpa.	86400	IN	NS	ns2.google.com,206.58.216.in-addr.arpa.	86400	IN	NS ns3.google.com,206.58.216.in-addr.arpa.	86400	IN	NS	ns4.google.com,  

  3  ns2.google.com  216.239.34.10  AUTH  0 ms  Received 1 Answers , rcode=NO_ERROR    106.206.58.216.in-addr.arpa.	86400	IN PTR	lhr25s14-in-f10.1e100.net,  
```
If I try that for your IP, it looks like Google is now blocking it:
```
LookupServer 433ms
  1  a.in-addr-servers.arpa  199.180.182.53  NON-AUTH  93 ms  Received 6 Referrals , rcode=NO_ERROR    199.in-addr.arpa. 86400	IN	NS	u.arin.net,199.in-addr.arpa.	86400	IN	NS	arin.authdns.ripe.net,199.in-addr.arpa.	86400	IN	NS	x.arin.net,199.in-addr.arpa.	86400	IN	NS	z.arin.net,199.in-addr.arpa.	86400	IN	NS	y.arin.net,199.in-addr.arpa.	86400	IN	NS	r.arin.net,  

  2  r.arin.net  199.180.180.63  NON-AUTH  78 ms  Received 4 Referrals , rcode=NO_ERROR    153.36.199.in-addr.arpa.	86400	IN NS	ns1.google.com,153.36.199.in-addr.arpa.	86400	IN	NS	ns4.google.com,153.36.199.in-addr.arpa.	86400	IN	NS ns3.google.com,153.36.199.in-addr.arpa.	86400	IN	NS	ns2.google.com,  

  3  ns4.google.com  216.239.38.10  NON-AUTH  0 ms  , rcode=REFUSED      

  3  ns3.google.com  216.239.36.10  NON-AUTH  0 ms  , rcode=REFUSED      

  3  ns1.google.com  216.239.32.10  NON-AUTH  21 ms  , rcode=REFUSED      

  3  ns2.google.com  216.239.34.10  NON-AUTH  15 ms  , rcode=REFUSED      
```
You could try running a trace to see what's taking you to that IP, and maybe where the issue is. For me:
```
>tracert www.googleapis.com

Tracing route to googleapis.l.google.com [216.58.210.202]
over a maximum of 30 hops:

  1     3 ms     1 ms     1 ms  <IP redacted>
  2     1 ms     7 ms     7 ms  <IP redacted>
  3     8 ms     8 ms     7 ms  core2-te0-11-0-12.colindale.ukcore.bt.net [109.159.254.6]
  4     7 ms     7 ms     8 ms  194.72.16.78
  5     8 ms     8 ms     9 ms  peer2-xe3-1-3.telehouse.ukcore.bt.net [109.159.253.5]
  6     *        *        *     Request timed out.
  7    10 ms    10 ms    10 ms  108.170.238.118
  8     9 ms     9 ms     9 ms  108.170.246.175
  9     9 ms     9 ms     9 ms  216.239.58.3
 10     9 ms     9 ms     9 ms  216.239.59.76
 11     9 ms    12 ms     9 ms  74.125.242.97
 12     9 ms     9 ms     9 ms  172.253.68.219
 13     8 ms     8 ms     8 ms  lhr48s11-in-f10.1e100.net [216.58.210.202]

Trace complete.
```
For me, step 7 is the first hit against Google servers. What do you get?

**Comment by smgilliam** [comment]
reading the above, i added this to my host file "C:\Windows\System32\drivers\etc\hosts" and it resolved my issue.
216.58.210.202	googleapis.l.google.com
216.58.210.202	www.googleapis.com

**Comment by mjc9885** [comment]
> reading the above, i added this to my host file "C:\Windows\System32\drivers\etc\hosts" and it resolved my issue.
> 216.58.210.202	googleapis.l.google.com
> 216.58.210.202	[www.googleapis.com](http://www.googleapis.com)

This resolved the issue for me.

**Comment by phw198** [comment]
You're a couple of steps ahead of me 😉 

I'd still be interested to know where your routing is going wrong - it could be a common ISP in the US or internet backbone, or it could be one of Google's own servers. It must be affecting a log of people and ideally should be reported as it's been like this for about 10 days now. Of course, if you guys work for the same company and it's your corporate IT that have bungled it then I probably don't need to worry!

Who are you using for DNS? Have you tried changing it, temporarily at least, to Google's public server on 8.8.8.8?

**Comment by smgilliam** [comment]
at work, i use their DNS.

at home i get this, but i dont have much use to use the OGCS here. 
C:\Users\Sean>ping www.googleapis.com

Pinging googleapis.l.google.com [172.217.1.138] with 32 bytes of data:
Reply from 172.217.1.138: bytes=32 time=26ms TTL=55
Reply from 172.217.1.138: bytes=32 time=28ms TTL=55
Reply from 172.217.1.138: bytes=32 time=24ms TTL=55
Reply from 172.217.1.138: bytes=32 time=33ms TTL=55


ISP at work and home are different. home is Spectrum. Work is Grande.

**Comment by phw198** [comment]
@smgilliam Thanks for confirming your home ISP doesn't have a problem. However, I need to see the output from a `tracert www.googleapis.com` from work to see where it's going wrong - would that be possible? Email me the results if your prefer.

**Comment by smgilliam** [comment]
heres a tracert to 
www.googleapis.com
and
googleapis.l.google.com


```

Tracing route to www.googleapis.com [199.36.153.6]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  <IP redacted>
  2    <1 ms    <1 ms    <1 ms  <IP redacted>
  3    13 ms     9 ms    11 ms  172.19.100.137
  4    28 ms    28 ms    28 ms  172.19.0.69
  5     *       33 ms    32 ms  172.19.0.70
  6    46 ms    55 ms    38 ms  172.30.0.69
  7   133 ms    54 ms    58 ms  172.30.0.73
  8    56 ms    53 ms    54 ms  172.30.0.74
  9     *        *        *     Request timed out.
 10     *        *        *     Request timed out.
 11     *        *        *     Request timed out.
 12     *        *        *     Request timed out.
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *     ^C
U:\>tracert googleapis.l.google.com

Tracing route to googleapis.l.google.com [216.58.192.138]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  <IP redacted>
  2    <1 ms    <1 ms    <1 ms  <IP redacted>
  3    <1 ms    <1 ms    <1 ms  67-198-0-1.static.grandenetworks.net [67.198.0.1]
  4    <1 ms    <1 ms    <1 ms  ae0-0.aggr08.wacotx.grandecom.net [24.155.121.170]
  5     3 ms     3 ms     3 ms  ae1-0.core01.gf01.dllstx.grandecom.net [24.155.121.43]
  6     7 ms     7 ms     7 ms  72.14.211.194
  7     *        *        *     Request timed out.
  8     8 ms     8 ms     8 ms  72.14.236.240
  9     8 ms     8 ms     8 ms  108.170.252.131
 10     8 ms     8 ms    33 ms  216.239.62.213
 11    10 ms    10 ms    11 ms  209.85.250.37
 12    47 ms    35 ms    37 ms  209.85.246.212
 13    34 ms    43 ms    34 ms  216.239.59.162
 14    26 ms    26 ms    26 ms  108.170.244.1
 15    34 ms    33 ms    33 ms  216.239.42.149
 16    23 ms    23 ms    23 ms  ord36s01-in-f10.1e100.net [216.58.192.138]

Trace complete.
```

**Comment by phw198** [comment]
Looks like it's a problem within your corporation I'd say. IP range 172.16.0.0 - 172.31.255.255 is not publicly registered eg with an ISP, it's just a range of anonymous private "stuff".

Think there's not too much for me to worry about, but you might want to flag it up with your IT guys...
