### ISSUE TITLE
Can't send a calendar invite from Outlook

### ISSUE THREAD

**Issue by dgonynor** [phw198/OutlookGoogleCalendarSync#806]
OGcalsync.log.2019-08-15
When I create a calendar invite in Outlook the invitee receives the following:
BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 16.0 MIMEDIR//EN
VERSION:2.0
METHOD:REQUEST
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:Eastern Standard Time
BEGIN:STANDARD
DTSTART:16011104T020000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010311T020000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN=;RSVP=TRUE:mailto
CLASS:PUBLIC
CREATED:20190813T183459Z
DESCRIPTION:Let me know if you want to use your screen share or mine.\n\n \
        n\nThanks!\n\nDave\n\n
DTEND;TZID="Eastern Standard Time":20190815T150000
DTSTAMP:20190813T183459Z
DTSTART;TZID="Eastern Standard Time":20190815T140000
LAST-MODIFIED:20190813T183459Z
ORGANIZER;CN=
PRIORITY:5
SEQUENCE:0
SUMMARY;LANGUAGE=en-us:Review Punchh for email blasts
TRANSP:OPAQUE
UID:040000008200E00074C5B7101A82E00800000000B0D1A048E451D501000000000000000
        0100000000535219E5C353A458B83781C272EECC3
X-ALT-DESC;FMTTYPE=text/html:<html xmlns:v="urn:schemas-microsoft-com:vml" 
        xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-mic
        rosoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/
        12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv=Co
        ntent-Type content="text/html\; charset=us-ascii"><meta name=Generator con
        tent="Microsoft Word 15 (filtered medium)"><style></style></head><body lang=EN-US link="#0563C1" vli
        nk="#954F72"><div class=WordSection1><p class=MsoNormal><span style='font-
        size:16.0pt'>Let me know if you want to use your screen share or mine.<o:p
        ></o:p></span></p><p class=MsoNormal><span style='font-size:16.0pt'><o:p>&
        nbsp\;</o:p></span></p><p class=MsoNormal><span style='font-size:16.0pt'>T
        hanks!<o:p></o:p></span></p><p class=MsoNormal><span style='font-size:16.0
        pt'>Dave<o:p></o:p></span></p></div></body></html>
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MS-OLK-AUTOSTARTCHECK:FALSE
X-MS-OLK-CONFTYPE:0
BEGIN:VALARM
TRIGGER:-PT15M
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
END:VCALENDAR

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
I  have no idea what this has to do with OGCS...
