### ISSUE TITLE
Cannot Authorize Google Account during First-Time Setup

### ISSUE THREAD

**Issue by ChaosFreak** [phw198/OutlookGoogleCalendarSync#808]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.1.0  
**Installed or Portable**: Installed

**Problem Description**  
On initial install of v2.8.1.0 I navigated to the "Settings" tab and then the "Google" tab and clicked "Retrieve Calendars". I was redirected to my web browser where I successfully logged in to my Google account and clicked "Allow" at the authorization screen. About 30 seconds later I got a "Something Went Wrong" message that just said "Sorry, something went wrong there. Try again." There were no further details or error codes. The URL of the error was:
https://accounts.google.com/info/unknownerror?authuser=0&part=AJi8hAOQ83RbHxvUMWFY9OJRPJJEc-x3hfQOjrbicegErBbW4Lw0vGpq05diHMCpa8Q_WdTcjzSF6xayAD6ECg9WJ-b5f3JAbaSSwdULZNX6qu62hPIK2dtnzxwzZ88u181s4Oc55k1lryzP-9jI4gQejvfLh0CNRn5N1OaWBS3yWmd8x3pcqYxNXRP8cuOrnzWptRxCU-Q87VmgW2H6YtCm1kSfONCfXDtMJJkuIP_kSso-ra7jFCQj0TE85JhDXJICE8OUTUdLelu6kA6dVCt3o_v5UEzkWcKOrC43QrNQBIDgK8fsMnQ-06p_NgSU1l_sMHdBZ1xHRMre-ComHeSObkCmAbG3pdmNF26-h3tgu7PB--Bn17BzDUwi6il-0YFE58E6hWr10R5BT6yidTzE59qE3uAlEopj31_ToT7adEKMnnCtptd20H9GJX_3gBP5id1gsotBpBfozMgQ6h6M8HicKOnJRSCrXb7UEetXFZkKZa_e4N8i9WtmB7je9TI_mHJ_M4OwO1Pq6Zr793Y2yG1Oj-RmcGsjLndubEzTEiBa05kSPI5_1s0OEfeG1J98z7aqPaS3&hl=en&as=RL5E71mdXdh08jfKUyCMRg
I tried logging out of my Google account and trying again, but this same error keeps occurring.

**Steps to Reproduce the Issue**  
1. Install Outlook Google Calendar Sync v.2.8.1.0
1. Navigate to the "Settings" tab and then the "Google" tab and clicked "Retrieve Calendars"
1. In the web browser, log in to Google account and click "Allow"

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3517326/OGcalsync.log)

**Comment by phw198** [comment]
Can you confirm if the same happens with v2.8.0?

**Comment by phw198** [comment]
Never mind, Google's screwing things up again: https://www.bleepingcomputer.com/news/google/gmail-is-down-displays-something-went-wrong-errors/

Check here for [updates from Google](https://www.google.com/appsstatus#hl=en&v=issue&sid=0&iid=e3aaf7adc786e8e60c44f238c29223c9) and [here](https://status.cloud.google.com/incident/developers-console/19008) (the second link specifically mentions OAuth2 endpoints)

**Comment by ChaosFreak** [comment]
Yes, actually I tried 2.8.0 first and the same thing happened.

**Comment by ChaosFreak** [comment]
Aah, the report on Bleeping Computer says it affects free Gmail accounts, but I’m on a paid GSuite account. I suppose the issue could be affecting both platforms. I’ll try again tomorrow and let you know!

**Comment by phw198** [comment]
Google claim this issue is resolved:

> The issue with authentication to Google App Engine sites, the Google Cloud Console, Identity Aware Proxy, and Google OAuth 2.0 endpoints has been resolved for all affected customers as of Monday, 2019-08-19 12:30 US/Pacific. We will conduct an internal investigation of this issue and make appropriate improvements to our systems to help prevent or minimize future recurrence.

**Comment by ChaosFreak** [comment]
I can confirm it works now.
