### ISSUE TITLE
Unable to authenticate with Google.

### ISSUE THREAD

**Issue by Nikers** [phw198/OutlookGoogleCalendarSync#810]
**OGCS Version**: v2.8.1.0 Alpha  
**Installed or Portable**: Installed

**Problem Description**  
Sync fails on google handshake fatal error.
I've disconnected and reconnect my account and, at every sync attempt, a web browser open to ask google to athorize OGCS to access my account and a warning page "This application is not yet validated by Google". I autorize my calendar access but sync fails !

**Steps to Reproduce the Issue**  
1. Start Sync
2. Web Browser auto open on Google auth app to google account page.
3. Warning page about not yet validated app and danger
4. Advanced parameters, and go link clic
5. Authorize twice
6. Approved token message : "Received verification code. You may now close this window."
7. Sync Fails

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3524113/OGcalsync.log)

**Comment by phw198** [comment]
I see you're using your own API keys, so I'm not sure you've enabled all you need to. Have you enabled the Google+ API?

**Comment by Nikers** [comment]
Yes, of course. Also don't work without own API keys...

**Comment by phw198** [comment]
I don't see any evidence in the logs of you following through the steps in your OP - every time is asks you to authorise OGCS with Google, either you cancel the process, or another sync starts before you've completed the process.

Can you
1. Upgrade to v2.8.2 (or latest alpha)
1. Turn off Push Sync
1. Manually start a sync
1. Authorise it through to completion
1. Send the logs again

**Comment by Nikers** [comment]
Thanks for your help ! There were probably a problem with my company proxy configuration.
Evrythings work !
