### ISSUE TITLE
Does not support GMT format

### ISSUE THREAD

**Issue by mwnaumann** [phw198/OutlookGoogleCalendarSync#812]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
I use Outlook in Microsoft Office 365 ProPlus, Version 1902

I schedule calendar entries in multiple timezones.  Regardless of my laptop timezone, Outlook displays the calendar entries correctly.

When I travel, I change the default timezone to the local timezone.  For example, when in Germany/France, I set the laptop timezone to Berlin/Paris.

When OGCS syncs my Outlook calendar entries to Google calendar, some calendar entries do not appear at the correct time.  I tried to set OGCS to use the R time and date format, so that all entries are converted to GMT before sync (BTW - I thing this should be the default), but OGCS does not support the 'R' or 'r' format.  It finds 0 entries in my calendar, when I actually have over 90 entries.

**Steps to Reproduce the Issue**  
1. Settings -> Outlook -> Custom -> R
1. 

**Any other information**  
When I use the 'R' or 'r' format, OGCS finds 0 entries.
If I select any other date and time format, OGCS finds 90 entries and syncs them, but it syncs them in the wrong timezone.

**Comment by phw198** [comment]
The Outlook date format option within OGCS doesn't affect timezone information, just purely how Outlook retrieves its calendar data - so don't use `R` :wink: 

:arrow_double_up: Please upgrade to the latest release, [v2.8.1.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.8.1-alpha/Setup.exe), and then perform a [Full Sync](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync) to see if your timezone problems are resolved.
