### ISSUE TITLE
Enhancement Request: Skip error and continue

### ISSUE THREAD

**Issue by McoreD** [phw198/OutlookGoogleCalendarSync#813]
**OGCS Version**: v2.8.1.0
**Installed or Portable**: Portable

**Problem Description**  
When there is an error, OGCS prompts a dialog to continue to stop.

**Steps to Reproduce the Issue**  
See log file (towards the end)
![20190823_bWZNKIcWT4](https://user-images.githubusercontent.com/48652/63555929-6b169b80-c575-11e9-9d0f-0a7345cce63e.png)
.

**Any other information**  
It would be great to ignore the error and complete syncing the remaining calendar items.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3532231/OGcalsync.log)

**Comment by phw198** [comment]
I'd like to try and confirm why the update is forbidden. 

:package: Could you apply [hotfix v2.8.1.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3537571/v2.8.1.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)), reproduce the issue and then upload your log file again?

Thanks!

**Comment by phw198** [comment]
This has been fixed on #830 by avoiding the forbidden 403 error altogether.
