### ISSUE TITLE
Enhancement: Set entries location

### ISSUE THREAD

**Issue by Raiden38** [phw198/OutlookGoogleCalendarSync#816]
Would be great if in the Sync Options menu, I would be able to set a location for all the items that are synced. All entries, are for my work location so I would love to put my work location as the set location. Thanks!

**Comment by phw198** [comment]
Thanks for the suggestion, though I think this would come under issue #500 - if obfuscation is extended to location as well as subject, then you could apply a regex rule of `.*` and replace with `Work location`.
