### ISSUE TITLE
Enhancement: Filter by Name

### ISSUE THREAD

**Issue by Raiden38** [phw198/OutlookGoogleCalendarSync#818]
I would like to have a filter where I could exclude all entries that has a certain word in the calendar, such as "Temporary" or "Pending" etc... Thanks

**Comment by phw198** [comment]
I'm not convinced this is a common enough requirement to merit coding into OGCS. I'd propose manually assigning a category to those items and then excluding that category from syncing?

**Comment by Raiden38** [comment]
if my issue with categories is resolved (#817) , then this one can be closed...

**Comment by laurentchades** [comment]
Hi, it would indeed be great if we could exclude a category / color from syncing !

**Comment by phw198** [comment]
@laurentchades You already can if you're referring to Outlook categories. Or were you talking about something different?

**Comment by phw198** [comment]
@Raiden38 #817 is waiting on your input from testing a hotfix release...

**Comment by phw198** [comment]
Delivered through #1688
