### ISSUE TITLE
Sync failure to retrieve master for Google recurring event

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#82]
Installed 2.4 this morning and now the sync is failing on the following:  
  
```Total inc. recurring items spanning sync date range...  
Failed to retrieve master for Google recurring event.  
The following error was encountered during sync:-  
Object reference not set to an instance of an object.  
Reading Outlook Calendar Entries...  
164 Outlook calendar entries found.  
```
Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 505](http://outlookgooglecalendarsync.codeplex.com/workitem/505)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Mon at 3:12 PM
**Reported by:**	ppartlo
**Updated on:**	Mon at 10:08 PM
**Updated by:**	phw198

#### Plaintext Attachments

[CodePlex Issue #505 Plain Text Attachments](https://gist.github.com/98eb14e061d06f8ed39f2ef8565429f9)

**Comment by phw198** [comment]
On *2017-05-08 22:37:47 UTC*, **KOaks** commented:

Hi!

I had the same issue. I have mine set up from Google -- Outlook. On my Outlook calendar, I deleted every Google appointment that had previously synced for the date range that I have set. Tried it again and Voila! It worked. I think it was having issues reading
 the older synced items with the newer ones (I'm NOT too tech savvy but this seemed like a logical step to me)

Hope this helped.

KOaks

**Comment by phw198** [comment]
On *2017-05-09 05:08:13 UTC*, **phw198** commented:

The problem seems to be specifically related to the appointment: 6/25/1997 (R) => "Anniversary"


Could you try deleting that recurring series in the destination calendar (Outlook) and letting OGCS resync it? I think that will work around the issue.

**Comment by phw198** [comment]
This should now be resolved with [Hotfix-v2.4.0.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1016187/Hotfix-v2.4.0.2.zip).

**Comment by fabstar81** [comment]
tried to install the hotfix. however, i get a failure installing it: "OutlookGoogleCalendarSync" has stopped working. with the only option to "Close the program"
![2017-05-23_10-22-25](https://cloud.githubusercontent.com/assets/28888099/26344990/c67e7d00-3fa1-11e7-9737-9a877472da2b.png)

**Comment by phw198** [comment]
@fabstar81 Please see the [instruction for applying a hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix).

**Comment by fabstar81** [comment]
thanks, that helped a lot. the fix also worked. i now can finalize the sync and am all up to date now.

**Comment by fors6630** [comment]
Just wanted to say thanks for this fix!  I found this issue for the past couple weeks but the hotfix overcame the issue.  Great work!

**Comment by hollenarmor** [comment]
Hello

I have the same error message with v1.4.1.16

I deleted all the recurring events in my both calendars, but it still doesn't work...

![image](https://user-images.githubusercontent.com/37665760/37779808-9005fb82-2ded-11e8-8688-09ced42cec4e.png)

`### Sync started : 22/03/2018 16:25:33
--------------------------------------------------------------------------
Profile : Default Calendar Profile
--------------------------------------------------------------------------
Calendar Sync : Outlook <===> Google
--------------------------------------------------------------------------
Date Range : 22/03/2018 - 20/07/2018
--------------------------------------------------------------------------
Reading Outlook entries...
Outlook entries read : 10
--------------------------------------------------------------------------
Reading Google entries...
Google entries read : 14
--------------------------------------------------------------------------
Getting Google entries to delete...
Found 0 entries to delete
--------------------------------------------------------------------------
Getting Google entries to add...
Found 0 entries to add
--------------------------------------------------------------------------
Getting Outlook entries to delete...
Found 0 entries to delete
--------------------------------------------------------------------------
Getting Outlook entries to add...
Found 4 entries to add
Adding Outlook entries...
Add Complete.
--------------------------------------------------------------------------
Sync failed : Object reference not set to an instance of an object.
--------------------------------------------------------------------------
Time Elapsed : 1 s
**************************************************************************
`

What can I do ?

**Comment by hollenarmor** [comment]
Oh sh..

I did a Google Search and didn't notice the difference... 

Where can I DL yours? 

The copy doesn't work and I prefer the original! 

Thanks!

**Comment by phw198** [comment]
@hollenarmor Haha, no worries. Get OGCS from https://phw198.github.io/OutlookGoogleCalendarSync - I'd recommend the alpha v2.7.2
