### ISSUE TITLE
First sync with Google through proxy always fails: HTTP 407

### ISSUE THREAD

**Issue by Kuehling** [phw198/OutlookGoogleCalendarSync#820]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  

Sync version: 2.8.0.0
Sync started at 27.08.2019 15:29:00
Syncing from 15.08.2019 to 27.10.2019
Outlook → Google
Authenticating with Google
Preparing to authenticate with Google.
Unable to communicate with Google services.

Sync encountered a problem and did not complete successfully.
2 consecutive syncs failed.

**Steps to Reproduce the Issue**  
1. Proxy Settings - Costums settings and authentification is used and stored (server, port, username and password are correct)
2. the sync always failes when "Start Sync" button used
3.  then Go to Settings / Application Behaviour / open Proxy Setting --> withpout making any changes, just hit the "Save Button"
4. Start Sync again --> sync is successful

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3546383/OGcalsync.log)

**Comment by phw198** [comment]
:link: https://www.dreamincode.net/forums/topic/160555-working-with-proxy-servers/

**Comment by phw198** [comment]
:package: Hoping this should now be resolved with [hotfix v2.8.1.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3587570/v2.8.1.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by Kuehling** [comment]
Hello Paul,

I tried the patch, however I can't get it running at all. I renamed the exe
into OutlookGoogleCalendarSync_old.exe and copied the patch into the
startup folder - without success.
After restating the machine the program does not start. Executing the file
- same result.
[image: image.png]

Best regards
Heiko

Am So., 8. Sept. 2019 um 14:04 Uhr schrieb Paul Woolcock <
notifications@github.com>:

**Comment by phw198** [comment]
Which directory did you put the patch in? As per the instructions, "It is important you carry out the below instructions in this directory, eg app-2.8.1-alpha and not the parent directory C:\Users\<userid>\AppData\Local\OutlookGoogleCalendarSync\"

:paperclips: Note, files can't be attached to the ticket when replying by email - please log in to GitHub to upload files and screenshots.

**Comment by phw198** [comment]
Any further feedback @Kuehling?

**Comment by Kuehling** [comment]
Hello Paul,
thank you for this Alpha relaease, 2 Days ago I made the update to version 2.8.1.6 and  the bugfix works fine !
I attached the log for your reference. 
I believe you can integrate the fix in your main branch and close the item.

Thank you !!
Heiko
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3603944/OGcalsync.log)

**Comment by phw198** [comment]
Fantastic - looks like the background update checks are also working too now :+1:
