### ISSUE TITLE
Sync deletes entries from Outlook Calendar

### ISSUE THREAD

**Issue by proamt** [phw198/OutlookGoogleCalendarSync#821]
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\When I sync my calendar, it deletes entries from my Outlook (work) calendar, even though I have deletions disabled. This has caused numerous issues with missing appointments. The appointments stay on my Google calendar, but I do not use my Google calendar for work purposes.

**Steps to Reproduce the Issue**  
1. \Sync options
![Capture](https://user-images.githubusercontent.com/54602203/63810204-cfc15580-c8e9-11e9-9a8f-bc369b0016f1.PNG)
 are:
 Direction: Outlook <-> Google
Disable deletions for all items synced to Google calendar
When: 1 day in the past, 60 days in the future, 0 hours

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Maybe you should try upgrading from v1.2.3.4 :roll_eyes: 

Disabling deletions is for a standalone calendar entry or an entire recurring series, not an occurrence within a recurring series. The 2 deletions that you have highlighted are for occurrences on 29th and 28th Aug within recurring series. Are you saying those occurrences still exist in Google?

FWIW, the option to disable deletions is meant as a safety net until you are confident the sync is working how you want, then you'd allow deletions. Not sure why you'd never want deletions to be synced...

**Comment by proamt** [comment]
Yes, the entries for the 28th and 29th of August still exist in Google, but they were deleted from my outlook calendar. I cannot have confidence in the sync at all when it deletes appointments and meetings that have not been deleted in either calendar. I have missed work meetings due to the sync removing meetings from my Outlook calendar for no reason.

**Comment by phw198** [comment]
Well quite, but without your OGcalsync.log file that covers the time the deletions occurred I can't investigate why it might have happened. 

Are you sure the occurrences weren't cancelled in Google, but you have them set to still show?

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
