### ISSUE TITLE
Recurring Meetings syncing to right time in wrong time zone

### ISSUE THREAD

**Issue by nelittle** [phw198/OutlookGoogleCalendarSync#822]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
Recurring Meetings from outlook to google are ending up in Columbia Time so are off 1 hr. Both source and Target calendar are in eastern time. Non Recurring meetings end up in the wrong time zone but correct time because the time is adjusted correctly

**Steps to Reproduce the Issue**  
1. Delete recurring meeting from google calendar
2. Sync
3. See Google Calendar item is 1 hr off
 
Source Calendar (in eastern timezone)
![image](https://user-images.githubusercontent.com/4389943/63947963-e381ce80-ca45-11e9-9428-fb68d6a5ffaf.png)

Target Calendar entry (Columbia time)
![image](https://user-images.githubusercontent.com/4389943/63947985-eb417300-ca45-11e9-9690-3e964a37f0bc.png)

Non Recurring Source Calendar Meeting (Eastern)
![image](https://user-images.githubusercontent.com/4389943/63948158-2f347800-ca46-11e9-8467-af3c9ed75517.png)

Non Recurring Target Calendar Entry (Columbia time, but adjusted by 1 hr so ends up in the right time)
![image](https://user-images.githubusercontent.com/4389943/63948388-85a1b680-ca46-11e9-86c2-eb8df037c947.png)

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3555945/OGcalsync.log)

**Comment by jwolfera** [comment]
I am having the same issue.  Needless to say, but I have been late to a few meeting because I did not notice right away.  Is there a fix for this?

I have uploaded the log file using the Google Form.

**Comment by samiratou** [comment]
I am also having this issue. Sometimes changing the timezone back to the correct one in Google will keep it the right time zone after syncing, but sometimes not. I can see in the verbose sync log "Changing time zone to..." and then it changes it to Central time Central America or Central time Guatemala (which is an hour ahead). Both Outlook & Google are set to Central/Chicago.

**Comment by JoeyDeeee** [comment]
Same issue here.  I've tried changing the timezone in Google but OGCS continues to move the back to the wrong time zone.

**Comment by phw198** [comment]
I know this issue was raised first, but as I've posted a proposed fix on #843 for testing, I'll close this as a duplicate.

Please do give the development build a go and report back on the other ticket.
