### ISSUE TITLE
New feature: Only sync busy entries

### ISSUE THREAD

**Issue by amaury-d** [phw198/OutlookGoogleCalendarSync#825]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Any other information**  
I would like to sync from Outlook to Google only entries marked as non free so that calendar entries marked as Free in Outlook don't appear in Google.

Thanks for this very useful tool and for making it opensource

**Comment by phw198** [comment]
:package: This should now be available with hotfix [v2.10.0.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/12136507/v2.10.0.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/11843015/141cd3d5-f43d-42eb-ac1a-7cfd3fffb5fa)

Please let me know how it goes if you give it a try!

**Comment by euinor** [comment]
Tested it and it appears to work (testing with Tentative calendar entries only)

**Comment by amaury-d** [comment]
Thanks a lot for this implementation! I'll give it a test in the next weeks.
