### ISSUE TITLE
Calendars read only

### ISSUE THREAD

**Issue by MatosHelder** [phw198/OutlookGoogleCalendarSync#826]
[:memo:](url) Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
Hello,

I'm getting messages of read only calendars and outlook and google are failing to update, can you help? Where can I change that? Thanks.

Helder

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3569033/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3569037/OGcalsync.log)

**Comment by phw198** [comment]
Well, you appear to have picked a Google calendar for two-way sync to which you only have read access. This obviously won't work - you can only sync _from_ a read only calendar, not to it.

I'm guessing the Google calendar has been shared with you and you don't own it, so you'd have to ask the owner for permission to update the calendar.

Note, v2.8.1 no longer let's you select readonly calendars for two-way sync :slightly_smiling_face:
