### ISSUE TITLE
When moving calender events from one date to another, OGCS shows a delete message while syncing

### ISSUE THREAD

**Issue by SerajaTen** [phw198/OutlookGoogleCalendarSync#827]
**OGCS Version**: v  2.8.0.0

**Installed or Portable**: Installed

**Problem Description**  
If you change the date of a meeting because it is booked to another day, and OGCS syncs those events again, it allways shows a deletion message which you have to block for every date/event
\<Update here>

**Steps to Reproduce the Issue**  
1. make an calendar entry
2. sync with OGCS
3. move the date of the entry with drag and drop or change it directly.
4. sync the event again
**Any other information**  
\<Update here>
[Desktop.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3569317/Desktop.zip)

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file again.
