### ISSUE TITLE
OGSync crashing when starting sync, used to work no problem, no settings changed

### ISSUE THREAD

**Issue by nathanhogan316** [phw198/OutlookGoogleCalendarSync#828]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.1  
**Installed or Portable**: Installed

**Problem Description**  
OGSync crashing when starting sync, used to work no problem, no settings changed

**Steps to Reproduce the Issue**  
1. Start a sync after OGCS has opened

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3573120/OGcalsync.log)

**Comment by phw198** [comment]
So it seems OGCS is crashing out without logging anything. Could you check your Windows Event log:
1. `Win+R` > `eventvwr`
1. Windows Logs > Application
1. Check for an entry that matches when OGCS crashed and post it here.

**Comment by nathanhogan316** [comment]
Hi,

 

Please find attached the 3 logs from the crash.

 

Thank you for looking into this for me.

 

Regards,

 

Nathan

**Comment by giadira** [comment]
I am having a similar issue. I am wondering if it is the McAfee Firewall shutting it down. It is logging the event as '"Suspicious incoming network connection blocked". But I have not been able to figure out how to make it allow this program to reach the Internet. I've tried changing the Traffic Controller settings as well as the Advanced Settings and it still intervenes without prompting me.  Even turning the Firewall 'off' did not seem to work; off course, the virus protection was still on, and I know it has gotten overzealous. Not sure how to get around McAfee.

**Comment by phw198** [comment]
This [looks the same](https://github.com/phw198/OutlookGoogleCalendarSync/issues/793#issuecomment-519077888) as issue #793. 

Could you check you are running the back-ported fix - your file timestamp for `C:\Users\natha\AppData\Local\OutlookGoogleCalendarSync\app-2.8.1-alpha\OutlookGoogleCalendarSync.exe` should be 8-Aug. If not, please re-install 2.8.1.

**Comment by giadira** [comment]
Thanks! Sorry I did not find that post by myself. This seems to have worked.

 

VR,

 

Giadira
