### ISSUE TITLE
Executable file keeps taking me back to Github page 

### ISSUE THREAD

**Issue by IanNettleton** [phw198/OutlookGoogleCalendarSync#829]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0 
**Installed or Portable**: trying to install

**Problem Description**  
\<Executable file keeps taking me back to Github page and does not open the application for some reason>

**Steps to Reproduce the Issue**  
1. \<Uninstalled app>
2. clicked on setup.exe file
3.  click on the download

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Which GitHub page does it take you to?

:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by IanNettleton** [comment]
https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/docs/Release%20Notes.md
I have no log file - nothing loads from the executable

**Comment by phw198** [comment]
You must have a log file. OGCS is loading, detecting an upgrade/new install and sending you to the release notes web page. There's plenty of logging before all that happens...

**Comment by Meric-Nessange** [comment]
Hi Paul, 
Same issue here. Confirmed : Not any log in the OGCS folder (almost empty, actually).

**Comment by Meric-Nessange** [comment]
OK, uninstalled & reinstalled (and click on some obscure "update.exe" stuff found in the OGCS folder), and now it makes some logs !
Here it is.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3591138/OGcalsync.log)

I try the 2.8.1. Same behaviour with the 2.8.0.

**Comment by Meric-Nessange** [comment]
yaah the menu is working, now. 
More than 1 reboot was needed ? mandatory to first run it when Outlook is open ? perhaps.

The app is fantastic, really nice job, guy.
10£ for you.

**Comment by phw198** [comment]
@Meric-Nessange Glad you got it working. If you had an `update.exe` file then it sounds like the install bombed halfway through. Then your log file after a reinstall looks to have got stuck where it's trying to connect to Outlook. I reckon you must have had some Windows updates pending a restart which was causing problems...

Sounds like it could be different from whatever @IanNettleton was reporting though, unless some reboots resolve it for him too.

**Comment by Meric-Nessange** [comment]
You right, at this moment, windows was in pain with an update stuff.

**Comment by IanNettleton** [comment]
Thanks I am sorted
