### ISSUE TITLE
After adding calendar ID to G, subsequent saves fail

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#83]
Hi,  
  
All was working fine this morning until I upgraded to 2.4. Now I'm getting
"precondition failed (412") errors.  
  
I've attached the log.  
  
thanks!  
  
Brett  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 506](http://outlookgooglecalendarsync.codeplex.com/workitem/506)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Mon at 9:00 PM
**Reported by:**	bbobley
**Updated on:**	Mon at 9:58 PM
**Updated by:**	phw198

#### Plaintext Attachments

[CodePlex Issue #506 Plain Text Attachments](https://gist.github.com/bc6ce0c8f87a88a1bb831c5073fedc26)

**Comment by phw198** [comment]
On *2017-05-09 04:58:03 UTC*, **phw198** commented:

Looks like you've found a bug :( 

On the brighter side, I think it's related to the first few syncs following the upgrade and once you've worked through them, they won't happen anymore.


Basically, the items are being updated with the ID of the source calendar (which is a new thing for v2.4) and then when they are updated again for a different reason later on in the sync, Google doesn't like it because it thinks the object's out of date.

**Comment by phw198** [comment]
The attached [Hotfix-v2.4.0.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1016164/Hotfix-v2.4.0.1.zip) should resolve this issue.

**Comment by ScottRochford** [comment]
Hotfix works perfectly, thanks!
