### ISSUE TITLE
Unable to force sync.

### ISSUE THREAD

**Issue by schumi2004** [phw198/OutlookGoogleCalendarSync#831]
**OGCS Version**: v2.8.1.0  
**Installed or Portable**: Installed

**Problem Description**  
During testing i deleted a few entries here and there and after final configuration i'm unable to force a sync. It keeps returning the following message:
1 Google items would have been deleted, but you have deletions disabled.
10 Outlook items would have been deleted, but you have deletions disabled.

**Steps to Reproduce the Issue**  
1. Configure and delete calendar items and try to sync them again.

**Any other information**  
Enabling deletions asks me to delete the items instead of resynching them.

**Comment by phw198** [comment]
I'm guessing you have two-way sync configured? It's not much of a sync if it magically recreates items you have deleted...

If you want those 10 Outlook items to be recreated, set OGCS to sync one-way Google->Outlook.
