### ISSUE TITLE
Alternate Exchange Mailbox Categories Not Populating

### ISSUE THREAD

**Issue by mcfibb** [phw198/OutlookGoogleCalendarSync#832]
**OGCS Version**: v2.8.1.0
**Installed or Portable**: Installed

**Problem Description**  
Hi there -- I've written about this before here: "Categories of alternative mailbox #335"

I believe I had everything sorted per my cobbled-together fix, which I discussed in prior thread. However, with the Alpha upgrade to 2.8.1, things went awry, and now my workaround no longer works! So, back to the drawing board with the original issue: when I switch from "Default" to "Alternative" mailbox for Outlook, the Calendars populate properly, but the Category Names persist with those in my default account. Even when including all Category Names in the sync, including "No Category Assigned", something weird is happening: those events with Category Names that don't show up in the Alternate Calendar category list simply don't sync. And that's where my workaround previously worked -- I just changed the name of the category to match in the XML code. 

Also, this is a shared Exchange calendar, but it functions as an alternative calendar, so not sure why it's acting funky.

And one more thing: not sure if it matters, but this is the second instance of OGCS that is running.

**Steps to Reproduce the Issue**  
1. Open OGCS.
2. Change Outlook mailbox from "Default" to "Alternative"
3. Wait for Calendars to populate.
4. By Default, the primary "Calendar" mailbox is selected.
5. No change in Category Name list.

**Any other information**  
OGCS log attached.

But here is the relevant portion of the log:
```
2019-09-09 09:31:45,253 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Finding Alternative Mailbox calendar folders
2019-09-09 09:31:46,922 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Default Calendar folder: Calendar
2019-09-09 09:31:46,938 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Folder type: olExchangeMailbox
2019-09-09 09:31:46,938 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [0] -  Failed getting non-default mailbox categories. Object reference not set to an instance of an object.
2019-09-09 09:31:46,938 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [0] -  Reverting to default mailbox categories.
2019-09-09 09:31:46,954 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Setting up Explorer event watchers.
2019-09-09 09:31:46,954 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Watcher needed for 1 existing explorers.
2019-09-09 09:31:46,954 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Adding listener for Explorer 'INIR - Calendar - INIR - Outlook'
2019-09-09 09:31:46,954 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Refreshing categories...
2019-09-09 09:31:46,969 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [0] -  Failed getting non-default mailbox categories. Object reference not set to an instance of an object.
2019-09-09 09:31:46,969 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [0] -  Reverting to default mailbox categories.
2019-09-09 09:31:49,730 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  Saving settings.
```

**Comment by mcfibb** [comment]
Hi there @phw198  -- just following up to this. Hoping to find a resolution quickly, if possible!

Thanks!

**Comment by phw198** [comment]
Hi @mcfibb - I've just posted a debug hotfix over on #817 if you would like to try that and post your updated logfile?

**Comment by mcfibb** [comment]
Thanks @phw198. I've been out on sick leave the last few days, but will have access to the computer that needs the hotfix tomorrow morning. I'll keep you posted on how it goes.

Thank you!

**Comment by mcfibb** [comment]
Updated log using hotfix 2.8.1.9.

Thank you!

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3654379/OGcalsync.log)

**Comment by phw198** [comment]
:package: Please could you try [v2.8.1.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3668017/v2.8.1.12.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and upload your logfile again.

**Comment by mcfibb** [comment]
Thanks for all the hard work trying to figure this issue out. Installed the hot fix and I've attached the newest logfile.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3672091/OGcalsync.log)

**Comment by mcfibb** [comment]
Hi @phw198 -- just wanted to check-in about the progress of this ticket.

Thanks!

**Comment by phw198** [comment]
Seems we're hitting another error: `Cannot create StorageItem in this folder. Either the folder is read-only, or a storage item is not allowed in this folder. `

Are any of these true for the alternate mailbox calendar?
* The folder is a Microsoft Exchange public folder, an Internet Message Access Protocol (IMAP), MSN Hotmail, or a Microsoft SharePoint Foundation folder.
* The user permission for the folder is read-only.

**Comment by phw198** [comment]
:package: I don't really want to go down this route, but just to see if it works, could you also try [v2.8.1.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3747131/v2.8.1.13.zip) and let me know how it goes.

**Comment by mcfibb** [comment]
Thanks Paul for your continued help! A few things:

1) That's a good question. Honestly, I have no idea. It's a second mailbox that a team of people have access to and is linked to my primary Exchange account as an alternate account. So I'm not quite sure where that leaves permissions. Perhaps more interestingly is that nothing has changed on my end regarding this account, including permissions thereof, so my best guess is that something about the 2.8 update of OGCS broke the workaround I had previously set up, which functioned well despite any existing user permission issues that may (or may not?) exist. Fairly certain it is not a public folder. And as a just-in-case, I've added my primary account as an owner for calendar item; however, that didn't make a difference when I tried to load the Alternate Mailbox categories.

2) I'll try installing the patch now and see how it goes. I'll keep you posted.

**Comment by mcfibb** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3751686/OGcalsync.log)
Paul! It worked!! Something you changed in this newest alpha-alpha did it! The right categories populate! I've attached the log, but it doesn't show any of the categories... but perhaps that because I'm not excluding any of them. From an untrained eye, it looks like things loaded totally smoothly! Going to try syncing and see if there are any issues there.

**Comment by mcfibb** [comment]
You. Are. A. Genius. IT WORKS!

THANK YOU THANK YOU THANK YOU THANK YOU. 

Frankly, my wife thanks you too. The whole reason for needing this set up is that my work won't allow sharing/syncing of calendars to non-company accounts, but my wife and I need to coordinate when I'm working onsite vs offsite (which is what my team uses the alternate calendar for). So syncing alternate calendar events with just my category to an external Google calendar that I can share with my wife has been super helpful.

So, thank you so, so much!

**Comment by mcfibb** [comment]
Totally understand and am grateful nonetheless! Will keep on keeping on till I hear otherwise.

**Comment by phw198** [comment]
@mcfibb Are you still running the patched v2.8.1 release? If so, could you try the below hotfix - just experimenting with another possible solution...

:package: [Hotfix v2.8.1.14.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4145581/v2.8.1.14.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by mcfibb** [comment]
Hey there! Thanks for reaching out. I'm actually still using the previous
hotfix you sent over. Should I overwrite that fix with this one? I'm a
little worried that it will break a system that's working just fine...
(eek!)

**Comment by phw198** [comment]
Hi @mcfibb, just take a copy of the executable you are currently using before you overwrite with v2.8.1.14. You can then always revert after testing it.

**Comment by phw198** [comment]
Had any time to try out v2.8.1.14?

**Comment by mcfibb** [comment]
Hey there Paul -- sorry for the delay. Just tried this morning. No dice.
Just populates the categories from the main calendar, not the selected
alternate.

Keep 'em coming. In the meantime, I'll keep the old hotfix going.

 - Kevin

**Comment by phw198** [comment]
Hi @mcfibb Finally got to looking at this again!

I realise you've said you're running the old v2.8.1 hotfix, but could you try applying the below hotfix as you did last time (make a copy of your currently executable before overwriting it). This hotfix is actually from v2.8.3, but I'm hoping there's no breaking changes in between those releases - let me know if it won't run though.

:package: [Hotfix v2.8.3.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4470668/v2.8.3.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by phw198** [comment]
Any update @mcfibb?

**Comment by mcfibb** [comment]
So sorry — been working from home due to COVID and don’t regularly access
my work computer. I’ll make a point on Monday to pull it out and check out
the hot fix.

Thank you!

**Comment by phw198** [comment]
Another friendly poke... 😉

**Comment by mcfibb** [comment]
Thanks buddy. Will update now and get back to you.

**Comment by mcfibb** [comment]
No dice. Won't even start. Object reference error. See attached log.

**Comment by phw198** [comment]
:paperclips: Files and screenshots can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by phw198** [comment]
@mcfibb Are you able to login to provide the logfile?

**Comment by mcfibb** [comment]
Hi there -- sorry for the ridiculously long delay. I've been sticking with my ad-hoc fix for years, but  recently saw that a number of new versions have since come out, so I took the leap and updated to the most recent alpha. Still an issue! Alternative mailbox categories do not update at all.

Since it's been so long, what would you like from me to continue problem solving? Screenshots? Logs? If the latter, is it just of the initialization of the alternate calendar?

Thanks!

EDIT: Went through the log from just now opening and switching to the alternative calendar. Here's the specific lines of code that show the problem:
```

2022-04-15 12:35:19,045 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [290] -  Finding Alternative Mailbox calendar folders
2022-04-15 12:35:20,131 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [389] -  Default Calendar folder: Calendar
2022-04-15 12:35:20,131 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [390] -  Folder type: olExchangeMailbox
2022-04-15 12:35:20,150 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [128] -  Failed getting non-default mailbox categories. Object reference not set to an instance of an object.
2022-04-15 12:35:20,150 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [129] -  Reverting to default mailbox categories.
```

**Comment by phw198** [comment]
Well that was an unexpected revival of an issue! :smile: 

Took me a while to figure out what we had been working on, but hopefully I've landed on a fairly elegant solution. :crossed_fingers: 

:package: Please see if it's resolved with [hotfix v2.9.4.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8507963/v2.9.4.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by mcfibb** [comment]
Thanks Paul! I'll give it a shot today and let you know how it goes. :)

**Comment by mcfibb** [comment]
It works!! Thank you!

**Comment by mcfibb** [comment]
Alright. Update:

May be due to user error, but just horrifyingly had all my personal events copied to the shared calendar I set up as a different profile. All deleted now, but I'm pretty sure I had one-way Outlook --> Google set up for that profile, but I'll confirm and let you know.

FYI, here's my planned setup:

Profile 1: Main
Two-way sync between Main Outlook calendar and "MASTER CALENDAR" Google calendar.
Purpose -- All professional and personal appointments and tasks identical between calendars.

Profile 2: [Team Name]
One-way sync between Secondary Outlook calendar (for team member onsite availability)and "McFibb Days @ Home" Google calendar, only syncing Outlook categories labeled "McFibb".
Purpose - To let my wife know when I'm onsite vs offsite.

**Comment by mcfibb** [comment]
Alright. I think the the main calendar didn't load when I setup the second profile. So it reverted to the Team calendar, but applied all my new setting changes. Fixed now. Phew!

**Comment by phw198** [comment]
I'm not quite sure I understand what that last problem was - is "I think the the main calendar didn't load when I setup the second profile." a bug with OGCS or just human error when configuring the second Profile?

Sounds like I can roll the categories fix into the next release though!

**Comment by mcfibb** [comment]
My best guess is human error. If it happens again though, I'll let you know!

Thanks!
