### ISSUE TITLE
Outlook event color not displaying in google

### ISSUE THREAD

**Issue by MKogcsUser** [phw198/OutlookGoogleCalendarSync#833]
**OGCS Version**: v2.8.0.0 
Installed

**Problem Description**  
in google calendar all events are the same color, regardless of outlook/google origin.

Under "How" I have:
For "all items" synced to "Outlook calendar" 
Checked - Set colour/category to "Purple" 

Under "What" I have:
Checked - Colours/categories 

Not sure if I have another setting checked off wrong, any help would be appreciated.

![Sync Options](https://user-images.githubusercontent.com/55110565/64564152-ecfd1780-d31e-11e9-91ab-9c0b8da08333.PNG)

**Comment by phw198** [comment]
You've not really stated what you expect to be happening, nor what colour all the items in Google are.

You have configured OGCS to set all Outlook items that OGCS syncs to it to be set to Purple, so I'm going to assume that's happening correctly, but then Google are subsequently being set to Purple also?

...and I've been able to replicate that :+1:

:package: This should now be resolved with [hotfix v2.8.2.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3828801/v2.8.2.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by phw198** [comment]
@MKogcsUser Any feedback on testing the hotfix?

**Comment by phw198** [comment]
:spiral_notepad: Rolling this in to the next release regardless.
