### ISSUE TITLE
OutlookGoogleCalendarSync - multiple Google Calendars?

### ISSUE THREAD

**Issue by tangosdad** [phw198/OutlookGoogleCalendarSync#834]
Can OutlookGoogleCalendarSync be used to sync 2 Google Calendars into Outlook? Then sync from Outlook back to the Google Calendars so all appointments show on both calendars?

**Comment by darrepac** [comment]
I would like the other way around: sync 1 outlook to 2 Google calendar (me and my wife ;)

**Comment by phw198** [comment]
Yep, both should be possible. See #165
