### ISSUE TITLE
New Feature Request:  Add option to not sync subject and instead add a custom or fixed text instead

### ISSUE THREAD

**Issue by krambock** [phw198/OutlookGoogleCalendarSync#836]
**OGCS Version**: v2.8.0.0
**Installed or Portable**: Portable
It can be helpful for privacy purposes,  I've used AWESync for Notes - Google  and only the entries are marked as Busy Time...  Since my use for this sync is only "informative" to my family knowing when I'm free / busy.  

It's nothing that I can't live without it but something I think as nice to have.   As per all the other fields can be opted out.

**Comment by phw198** [comment]
Well that exactly what the obfuscation option is for :slightly_smiling_face: 

Search for `.*` and replace it with `Work appointment`.

But if syncing your calendar is just to inform your family, why not share the Google calendar to them with only free/busy information? That way you can still see the full details on your phone etc.

**Comment by krambock** [comment]
Beta works but replaces every word on the subject so I get a "work meeting" repeated by n-times as subject,  Alpha crashes when doing that obfuscation :)

**Comment by phw198** [comment]
Did you get this working? I'll close the ticket if so...

**Comment by krambock** [comment]
Sorry yes got it working on both versions not sure why it crashed on Alpha the first time.  I reinstalled alpha and worked.
