### ISSUE TITLE
Outlook Category Colour changes

### ISSUE THREAD

**Issue by MarkStuart0804** [phw198/OutlookGoogleCalendarSync#838]
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Bug Description**  
Hi. I have customised the category colours in Outlook 2013. These customised colours are not syncing with Google correctly. Am I doing something wrong

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Depends very much on what you mean by "correctly"...

You should also confirm you are using the latest alpha release before attempting to troubleshoot any further.
