### ISSUE TITLE
Reminders not syncing/being deleted

### ISSUE THREAD

**Issue by k8seren** [phw198/OutlookGoogleCalendarSync#840]
[OGcalsync.log.2019-09-11.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3605891/OGcalsync.log.2019-09-11.txt)

:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.1.0  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>
I have tried different settings and no matter what I choose, I am not getting reminders. This is causing problems for me as you can imagine. I have included my log file. I would really appreciate any help you can provide! The app is awesome aside from this one issue. 

**Steps to Reproduce the Issue**  
1. \<Update>
1. Sync calendars
2. Reminders do not appear in Outlook or Google calendar. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
I'd need to see your `settings.xml` file or the logfile after you've just started OGCS, so I can see you configuration. Also, if you can create a new Outlook entry and sync that to Google so I have something I can see in the logs showing what you're reporting.

If had to guess though, it might be that you select "Use Google Default" and then have no default configured in Google?

**Comment by k8seren** [comment]
Thank you for following up. I experimented with the settings and things seem to be working as expected now. Thanks again for this helpful program!
