### ISSUE TITLE
New event failed to save

### ISSUE THREAD

**Issue by slickrock** [phw198/OutlookGoogleCalendarSync#847]
OGCS 2.8.0.0

When syncing Outlook-->Google, get errors: "New event failed to save. You cannot make changes to contents of this read only folder."

**Comment by phw198** [comment]
You don't seem to have asked a question. Obviously you can't sync to a read-only destination calendar...

**Comment by phw198** [comment]
Later releases advise/prevent selecting a read-only calendar as a destination for sync.
