### ISSUE TITLE
Permissions to Outlook Calendar Required

### ISSUE THREAD

**Issue by Mitch1337** [phw198/OutlookGoogleCalendarSync#850]
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Bug Description**  
Sync version: 2.8.0.0 Sync started at 2019-09-24 9:39:41 AM Syncing from 2019-09-23 to 2019-11-24 Outlook ← Google Finding Calendar Entries Scanning Outlook calendar... 0 Outlook calendar entries found. Scanning Google calendar... 3 Google calendar entries found. Total inc. recurring items spanning sync date range... Outlook 0, Google 3 Checking for orphaned items... Matching calendar items... 0 Outlook calendar entries to be deleted. 3 Outlook calendar entries to be created. 0 calendar entries to be compared. Creating 3 Outlook calendar entries Unable to add new entries into the Outlook Calendar. You don't have permission to create an entry in this folder. Right-click the folder, and then click Properties to check your permissions for the folder. See the folder owner or your administrator to change your permissions. Operation aborted after 1 failed attempts!

**Steps to Reproduce the Issue**  
Set up OGCS for first time use.
Connect Google Calendar.
Set up Outlook Calendar to sync to.
Try to run sync, get permissions error.

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
You not having permissions to the Outlook calendar you are syncing to is not a bug. It's entirely expected and the solution is in your post:

> You don't have permission to create an entry in this folder. Right-click the folder, and then click Properties to check your permissions for the folder. See the folder owner or your administrator to change your permissions.

**Comment by Mitch1337** [comment]
Thanks for the response.

I'm just confused on what the program uses as its permissions.

As in, what entity do I provide the permissions to?

**Comment by phw198** [comment]
The OGCS app has exactly the same rights into Outlook as you do. Ie the app can only write to the Outlook calendar if you can yourself.
