### ISSUE TITLE
Is Paul missing?

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#851]
Has anyone heard from Paul?  I have never waited too thing long for help?

**Comment by BrandonGriffis** [comment]
I'm seeing commits two days ago and issue activity from him as recently as yesterday. I also have a reported bug from about two weeks back that he hasn't commented on yet, but I presume he's just busy and it's hard to get time to respond to everything.

**Comment by phw198** [comment]
Thanks for your concern - yes, I'm still here. Just a reminder that I run this project in my spare time, and there's only one of me with not much of that spare time sometimes!

As I think you realised (and per guidance), it is only practical for me to support the latest release of OGCS - so issues reported on earlier releases aren't much use.

**Comment by michgal2k** [comment]
Should bot be closed

**Comment by phw198** [comment]
Why not? I suggest you pay better attention to your posts.
