### ISSUE TITLE
Stuck in Googel-Token loop

### ISSUE THREAD

**Issue by Saphirim** [phw198/OutlookGoogleCalendarSync#854]
**OGCS Version**: v2.8.1-Alpha  
**Installed or Portable**: Installed

**Problem Description**  
Retrieving the Google OAuth-Token is stuck in a endless loop.
![image](https://user-images.githubusercontent.com/7426446/65853277-3c03fe80-e359-11e9-81f5-61c491407511.png)

**Steps to Reproduce the Issue**  
1. Start the Tool
2. Klick "OK" when the Warning-Box "Authorisation token invalid" requests to run trough the OAuth-Token retrieval process again
3. Click "Allow" in the browser where Google displays that the tool wants to access calendar
4. And than it all starts over again...

**Any other information**

**Comment by phw198** [comment]
Was it working before or is this the first time you are using OGCS?

:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by Saphirim** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3700929/OGcalsync.log)
Here is the anonymous log.

Yes, it worked before, but from what I'm getting out of the logs, Internet Explorer seems to be blocked now by a company policy (maybe a group policy on our windows OS). Seems like OGCS tries to retrieve the OAuth token using IE? Or at least perform some step with the help of IE. Thats where the logs write out the error, sadly in german. E.g. lines 341 - 405#

**Comment by phw198** [comment]
Your logs do indeed show your company blocking access through IE:

> Due to an acute security issue, Microsoft Internet Explorer cannot be used for internet access at the moment. Please use one of these browsers instead: Microsoft Edge (available on Windows 10 by default); Google Chrome (can be installed via Bulb64)

During authorising OGCS to access Google, you should be able to copy and paste the URL from IE and into eg, Chrome to complete the process. Or set Chrome as your default browser, so OGCS opens that directly.

**Comment by Saphirim** [comment]
Hi,

=> Chrome is the default browser
=> The 0Auth-Confirmation page to allow OGCS to access calendar entries opens in Chrome, no Internet Explorer showing up, besides the logs...

**Comment by phw198** [comment]
In that case, I think you just need to update the Browser Agent value in OGCS proxy settings. 

:arrow_double_up: Would be worth upgrading to the latest release, [v2.8.2.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.8.2-alpha/Setup.exe), too.

**Comment by Saphirim** [comment]
Perfect:
- Used the latest Alpha like suggested
- Updated the Browser-Agent to match my current Chrome version

Works like a charm now :) Thanks!
