### ISSUE TITLE
OGCS stopped working

### ISSUE THREAD

**Issue by rikoos** [phw198/OutlookGoogleCalendarSync#857]
**OGCS Version**: OGCS278 & OGCS280 
**Installed or Portable**: Portable

**Bug Description**  
OGCS wont start 

**Steps to Reproduce the Issue**  
1. Go to exe file
1. Click on exe file 

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.

It worked till the 16th of sept and from that moment it stopped working. I installed the latest stable but same result. The exe will start but within a few secs it is removed from memory and nothing happens (no splash or menu is shown).

I went on holiday the 17th so i havent used it since yesterday and it wasnt working :-(

**Comment by rikoos** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3680196/OGcalsync.log)

**Comment by Rdesja** [comment]
I have the same problem since september 16th. Cannot sync anymore. What  do I have to do?

**Comment by phw198** [comment]
@rikoos Seems there is a problem with your proxy configuration, the message translation being
```
An exception occurred during a Web Client request. 
An error occurred while creating the web proxy specified in the system.net/defaultProxy configuration section.
```

:arrow_double_up: Please could you try first running the latest release, [v2.8.2.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.8.2-alpha/Setup.exe), and confirm if you can still replicate the issue. If you can, please re-upload your logfile.

@Rdesja I have no idea without [seeing your logfile](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file).

**Comment by Rdesja** [comment]
Hi,

I uninstalled and reinstalled the version.2.8.2.0 and everything rolls perfectly.3

Thank you very much!
