### ISSUE TITLE
Google event colour being removed without opting to sync categories

### ISSUE THREAD

**Issue by dfripp** [phw198/OutlookGoogleCalendarSync#858]
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Bug Description**  
I am using the latest Alpha. Often, when I change the color of an event on my Google calendar, when I sync it, the color gets stripped. But not always. I do not have the click box to change to color/category on Settings/Sync Options checked. (It is also not confirming deletions, even though I have "Confirm deletions" checked.) I am using two way syncing but it also does this when I use one way (Outlook to Google) syncing.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.

**Comment by OceanEcol** [comment]
I have the same problem, some (seemingly random) events in Google Calendar have started loosing their assigned colour.

**Comment by phw198** [comment]
Is the colour being removed for single events in Google, or an instance of a recurring series?

:spiral_notepad: Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) after you have replicated the issue.

**Comment by dfripp** [comment]
Generally it’s all of a recurring series.  I’ll try it again in the morning and send you the log.

**Comment by dfripp** [comment]
Here’s the .log file. I aborted it after it started stripping the color from things. It was primarily stripping it from all the instances of recurring series, but it also caught a multi-day event (one that was “all day” for 3 days in a row). It does not seem to be impacting single day events.

I hope that helps.

Thanks!
Deborah

**Comment by phw198** [comment]
:paperclips: Unfortunately, files and screenshots can't be attached to the ticket when replying by email - if you still have that logfile from 21-Oct (hopefully it will still be found in the same folder as the `OGcalsync.log` file, but named `OGcalsync.log.2019-10-21`), please log in to GitHub to upload it.

**Comment by phw198** [comment]
Actually, it's OK, I've managed to reproduce this issue.

:package: It should now be resolved with [hotfix v2.8.2.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3828722/v2.8.2.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by dfripp** [comment]
Hi Paul,

I have not been able to make this work. Is there a fresh download I can do to just reinstall the program with the hotfix?

Thanks!
Deborah

**Comment by phw198** [comment]
:package: I can't really provide an installable version, but here is a complete [portable release for v2.8.2.5](https://github.com/phw198/OutlookGoogleCalendarSync/files/3855743/Portable_OGCS_v2.8.2.5.zip).

Extract this to a new directory and run from there.

**Comment by dfripp** [comment]
Thank you so much! And thank you for fixing that problem.
