### ISSUE TITLE
Outlook <-> Google sync issue

### ISSUE THREAD

**Issue by kevindd992002** [phw198/OutlookGoogleCalendarSync#859]
**OGCS Version**: v2.8.1.0
**Installed or Portable**: Installed

**Bug Description**  
When I choose Outlook <-> Google direction, it's trying to delete Outlook entries even though I initially synced all Outlook entries to an empty Google calendar.

**Steps to Reproduce the Issue**  
1. Empty Google calendar
2. Sync from Outlook -> Google direction.
3. Change direction to Outlook <-> Google and it starts to ask for delete confirmation of multiple entries.

**Any other information**  
I can reproduce this issue easily and the number of items it's trying to delete is random. So it's obviously a bug.

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3688915/OGcalsync.log)

**Comment by kevindd992002** [comment]
Anybody please?

**Comment by phw198** [comment]
Hi, your log file hasn't captured you attempting a two-way sync. Please can you start OGCS, run O->G and then O<->G and then upload that log?
