### ISSUE TITLE
donation

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#86]
I donated 10 GBP.  
  
How can i remove option 'Hide splasch screen'.  
  
THNX!!!  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 509](http://outlookgooglecalendarsync.codeplex.com/workitem/509)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Tue at 9:01 PM
**Reported by:**	GoldHead
**Updated on:**	Tue at 9:12 PM
**Updated by:**	phw198

**Comment by phw198** [comment]
On *2017-05-10 04:12:23 UTC*, **phw198** commented:

Hi and thanks :)

Are you Zlatko? If so, I take it you didn't click the "Donate" button from within the application, but maybe from the Donate button on the website? I ask because the application will include the gmail address so I know who to tie the donation to,
 and your donation didn't include the email address.

Anyway, these steps should get the splash screen hidden:

* Restart OGCS whenever is convenient (don't worry if the 'Hide Splash Screen' option doesn't work just yet).
* Run a manual sync by clicking the 'Sync' button.
* Go to the 'Settings' tab and 'Application Behaviour'. 
* Check 'Hide splash screen' and click 'Save' 
* The next time OGCS is started...no splash screen!

**Comment by phw198** [comment]
- [x] PayPal button outside of the app now requests user's Google email is included in the donation notes.
- [x] Above instructions added to auto-reply to donors.

**Comment by PaulOfferman** [comment]
I also donated, but I can not select the hide splash screen button

p.offerman@planet.nl

**Comment by phw198** [comment]
@PaulOfferman - Thanks, I've confirmed your donation and you should now be able to hide the splash screen (assuming the email you gave above is the Google account you are syncing with).

**Comment by lucabalda89** [comment]
I Have donated 10$ , other function works but i cant hide splash screen!
my account is studio@nataliabianchi.it
thank you!

**Comment by phw198** [comment]
@lucabalda89 It takes up to 30 minutes to process a donation. I believe you are now able to hide the splash.

**Comment by diegobrg** [comment]
Hello , I have donated GBP 10 to remove the splash screen on 28th January, but did not receive any email with instructions. Could you please help me? I registered with the following email: diego@xgoplus.com

Thanks, rgds,
Diego

**Comment by phw198** [comment]
@diegobrg it seems PayPal have been failing to send out some donation notification emails, so enabling the hide splash screen option was not processed for you. That should go through very shortly for you now...
