### ISSUE TITLE
Received Name Resolution Error during normal operations

### ISSUE THREAD

**Issue by jplewis01** [phw198/OutlookGoogleCalendarSync#861]
**OGCS Version**: v2.8.0.0
--

**Installed or Portable**: Installed

**Bug Description**  
Appears to a be a DNS Name resolution Error
"2019-10-08 14:25:14,567 WARN  1 OutlookGoogleCalendarSync.Telemetry [0] -  Failed to access URL https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&cid=678c4bb4d8c7dc140dcf6ba76692764b&ec=ogcs&ea=sync&el=calendar

2019-10-08 14:25:14,569 ERROR  1 OutlookGoogleCalendarSync.Telemetry [0] -  The remote name could not be resolved: 'www.google-analytics.com'

Error Occured while I was away from the computer. It is possible that the network experiennced a temporary outage resulting in the failed connection and DNS resolve. 

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3704677/OGcalsync.log)

**Comment by phw198** [comment]
Telemetry errors are logged as `FAIL` in subsequent alpha releases, so this would no longer be visible to the user. As you say, probably a temporary glitch on your network somewhere
