### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by Klik96** [phw198/OutlookGoogleCalendarSync#863]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.1.0  
**Installed or Portable**: Installed

**Problem Description**  
Sync seemed to complete fine, after turning on scheduled sync it had cascading failures (before the 2 hour time the sync was supposed to happen) and I had to end task. Tried to manually sync but go the error "value cannot be null parameter name: source

**Steps to Reproduce the Issue**  
1. click sync or allow it to auto sync
 

**Any other information**  
Not sure if normal or not but in task manager it shows 2 instances of outlook. 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3712298/OGcalsync.log)

**Comment by phw198** [comment]
:package: Please could you upgrade to v2.8.2.0 and then patch it with this development build [v2.8.2.15.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3899086/v2.8.2.15.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please upload your logfile if there's still an issue.

Note, 2 instances of Outlook doesn't sound quite right, but I think the issue you're encountering is related to having turned on Push Sync.
