### ISSUE TITLE
The object does not support this method. AppointmentItem.set_Categories() [0x81F20009]

### ISSUE THREAD

**Issue by thaclone** [phw198/OutlookGoogleCalendarSync#864]
**OGCS Version**: v 2.8.1.0
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3713581/OGcalsync.log)

**Installed or Portable**: Installed

**Bug Description**  
Bug is appearing within synchronisation with Outlook 365 Version 1909 Build 12023.20264.
See picture what happend. Sync is in 2way sync with google Calender. No Proxy is set.

**Steps to Reproduce the Issue**  
1. Start the App
2. Press Sync
3. After some seconds error occured.

**Any other information**  
Attached the log file
![2019-10-10 18_24_03-Outlook Google Calendar Sync](https://user-images.githubusercontent.com/56232157/66587685-309ba900-eb8b-11e9-9120-460c84236620.jpg)
![2019-10-10 18_27_49-Outlook Google Calendar Sync](https://user-images.githubusercontent.com/56232157/66588008-dbac6280-eb8b-11e9-8169-3d0910cab727.png)
![2019-10-10 18_28_03-Outlook Google Calendar Sync](https://user-images.githubusercontent.com/56232157/66588009-dbac6280-eb8b-11e9-94dd-66d0560947d4.png)
![2019-10-10 18_28_15-Outlook Google Calendar Sync](https://user-images.githubusercontent.com/56232157/66588011-dc44f900-eb8b-11e9-91da-befef3c4a08d.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3713626/OGcalsync.log)

**Comment by thaclone** [comment]
Problem is not yet solved - could somebody help. Also with version 2.8.2.0 is installed.

**Comment by phw198** [comment]
It seems the object that is having a category set for it does not support categories:
```

2019-10-10 18:23:01,892 ERROR  18 OutlookGoogleCalendarSync.Console [0] -  Unable to update existing entries in the Outlook calendar.
2019-10-10 18:23:06,025 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: Das Objekt unterstützt diese Methode nicht.
2019-10-10 18:23:06,026 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x81F20009;-2114846711
2019-10-10 18:23:06,027 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -     bei Microsoft.Office.Interop.Outlook._AppointmentItem.set_Categories(String Categories)
   bei OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
   bei OutlookGoogleCalendarSync.Recurrence.processOutlookExceptions(AppointmentItem& ai, Event ev, Boolean forceCompare)
   bei OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
   bei OutlookGoogleCalendarSync.Sync.Engine.googleToOutlook(List`1 googleEntries, List`1 outlookEntries, String& bubbleText)
   bei OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   bei OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)
```
The workaround would be to turn off sync of colours/categories - but do try the latest alpha release and report if it's still a problem.

**Comment by Brain2000** [comment]
Just curious what the outcome was here. I'm having this same issue with a different plugin. Is it an issue with a specific InteropServices version for Outlook?

**Comment by phw198** [comment]
The software is trying to manipulate the categories on an Outlook object that doesn't support categories. I'm unsure which such object that would be within a calendar, though if the account configured within Outlook is IMAP, then the entire calendar would not support categories...

**Comment by tdalon** [comment]
I am also facing an Outlook bug with vba to set Categories for an Appointment. See also reports here https://forums.slipstick.com/threads/95585-appointment-cannot-set-categories-because-conversationid-is-not-set/ and here https://stackoverflow.com/questions/62257271/setting-outlook-appointment-item-category-for-meetings-where-the-invitation-cam This is very annoying: the AppointmentItem definitely shall allow to set the Categories Property. I can see it in the Debugger window.
