### ISSUE TITLE
Copied Entries not Syncing

### ISSUE THREAD

**Issue by bensonchuong** [phw198/OutlookGoogleCalendarSync#865]
**OGCS Version**: v2.8.0.0
**Installed or Portable**: Portable

**Problem Description**  
Any calendar entries that I copy in Outlook (hold ctrl+drag) are just being modified. The original one is being deleted and modified to the copied date.
Example:
Event for Oct 10, 2019, crtl+drag to Oct 12, 2019. Outlook shows  Event on Oct 10 and Oct 12. When I sync with OGCS it modifies the Oct 10 to Oct 12 and that's it (doesn't create a new event). So in my Google Calendar only the Event on Oct 12 remains.

**Steps to Reproduce the Issue**  
Copy some calendar entries and start sync

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
I can't replicate this on the latest alpha, but then you're not using the latest alpha, so I'm unable to provide support.

You've not said if you have two-way sync configured, but if you do, when copying an already two-way synced Outlook item, you _must_ have OGCS running in the background, else unexpected deletions etc will be seen. This [known issue](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#copied-outlook-appointments-cause-unexpected-deletions) is now added to the wiki

**Comment by bensonchuong** [comment]
I tried it with the v,2.8.2.alpha and I'm still getting the same issue.

My sync is set up as one way from Outlook to Google.

The issue only occurs if the copied event is not modified. I have a all day event that I just copy from day to day (it's called Off Work). If I ctrl+drag an existing event the issue occurs. If I make a new event called Off Work then copy that one then they all sync properly.

If I delete the entries that are missing in Google from Outlook, then when I sync OGCS deletes similarly named entries but on different dates. So to fix it, I have to delete my Google Calendar and re-sync everything.

**Comment by phw198** [comment]
:spiral_notepad: OK, please reproduce the issue on v2.8.2 and then provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).
