### ISSUE TITLE
Won't start - "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by winheggem** [phw198/OutlookGoogleCalendarSync#866]
**OGCS Version**: v2.8.1.0-alpha  
**Installed or Portable**: Installed

**Bug Description**  
1. With Outlook running: OGCS crashes on load - "Application unexpectedly terminated!" "Object reference not set to an instance of an object."
2. With Outlook not running: OGCS crashes on load - "Application terminated!" "A Problem was encountered with your Office install. Please see the wiki for a solution. [0x8002801D]

Per the recommendations, I have repaired Office and then reset Office. Neither action changed the error.

Subsequently, I uninstalled and reinstalled OGCS. The problem remains.

**Steps to Reproduce the Issue**  
1. Attempt to start OGCS

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
The [wiki recommends registry hacks](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002801d---type_e_libnotregistered), not just office repairs.

Can you provide a logfile for the crash when Outlook is running?
