### ISSUE TITLE
Cloud version

### ISSUE THREAD

**Issue by primez** [phw198/OutlookGoogleCalendarSync#867]
It would be great to have a cloud version of the application to not have a computer running all the time to sync calendars

**Describe the solution you'd like**
As for the start - it can be implemented as AWS Lambda, Azure Functions, or Google Functions. Any of the options has a free tier.

**Comment by phw198** [comment]
You're welcome to give it a go! But it's not something that I'll be doing as part of this project - not least because none of the existing code could be used. Plus wouldn't users need a level of IT knowledge for deploying such a solution that the vast majority won't have?

**Comment by primez** [comment]
Yes, you are right, it requires some knowledge though.
Thanks for approval
