### ISSUE TITLE
I am losing data... 

### ISSUE THREAD

**Issue by HarrieB58** [phw198/OutlookGoogleCalendarSync#868]
**OGCS Version**: v2.8.1.0  
**Installed or Portable**: Installed

**Bug Description**  
I have "private" meetings in Outlook. These are copied to Google. Then when I sync again they are deleted first from Google, then from Outlook.  The ones that you can check are "Breathing - Naima" and "Tr Breathing - Naima"

**Steps to Reproduce the Issue**  
This seems to repeat every time I have "private" messages in Outlook.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3739071/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Sorry, this is rather an old ticket and I can't reproduce the issue on v2.8.6 at least. Please open a new ticket if still a problem!!
