### ISSUE TITLE
Failed to Output Appointments to CSV file.. Unable to translate unicode character - and sync is aborted

### ISSUE THREAD

**Issue by fluff66** [phw198/OutlookGoogleCalendarSync#869]
OGCS consitently fails to complete the sync reporting for a number of appointments it cannot write to the CSV file, then finally reports it is unable to translate a unicode character \uD83D at index 82 to specified code page.

Does that simply mean one of the future appointments has a character in the record causing an issue?  How do i find that record?  I changed to sync window from 180 days to 10, and sync worked fine, so I am guess thats the issue.

**OGCS Version**: v2.8.1.0  
**Portable**

**Comment by fluff66** [comment]
OK I found the issue in the body of a invite. There was a smiley face from the Segoe UI Emoji font. Once I removed that from the invite note sync works again

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.8.2.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3828305/v2.8.2.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Of course, CSV output is normally only required for debugging a problem, so the simplest workaround would have been to turn off the option in the settings. Thanks for reporting it though!
