### ISSUE TITLE
Unable to locate Outlook Google Calendar Sync application to start it

### ISSUE THREAD

**Issue by ssrcmr** [phw198/OutlookGoogleCalendarSync#871]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.1  
**Installed or Portable**: Installed

**Problem Description**  
I installed v2.8.1 alpha on a Windows 10 v1903 computer. I checked all the application behaviors, but am unable to locate the application to open it to adjust its settings. The application is working perfectly. I checked the system tray, the appdata\local folder and find no trace of OGCS. I restarted the computer, entered another appointment and the sync from Outlook calendar to Google calendar worked as expected. No evidence of the application. How can I open the OGCS application?

**Steps to Reproduce the Issue**  
1. I restarted the computer, entered a test event, OGCS is working
2. Checked system tray ... no app
3. checked appdata path, no folder for OGCS or OutlookGoogleCalendarSyn
4. checked control panel for the app .... no entry
5. checked task manager - no process running

**Any other information**  
I am unable to open the application to get the log.

**Comment by phw198** [comment]
I'm not sure what is doing the syncing, but it doesn't sound like OGCS! There would have to be a `OutlookGoogleCalendarSync.exe` process running (visible in task manager) for a sync to happen...

**Comment by ssrcmr** [comment]
I believe I found the issue. I installed OGCS on another pc as well. That
pc has the icon in the system tray and the app that is accessible. No need
to have it installed twice.i believe you can close this case. Thank you.
