### ISSUE TITLE
Can't change data range more than 365 days

### ISSUE THREAD

**Issue by CiquattroFPV** [phw198/OutlookGoogleCalendarSync#873]
**OGCS Version**: v2.8.2 Alpha
**Installed or Portable**: Installed and Portable (We tested both)

**Bug Description**  
Recurrencies sync well across years.. but if we have single event made in 2009 we are unable to sync it Google Calendar.
Is possible to be able to change the number of days to sync more than 365 days please?

**Steps to Reproduce the Issue**  

0. We are using API keys from Google Developer Console and set up in Settings > Google OAuth API
1. Go to... Settings > Sync option >
2. Click on...  When > Date Range 
3. Try to change the number of days to 3100 and Save it it will come back to 365

**Any other information**  
Is possible to be able to change the number of days to sync more than 365 days please?

**Comment by CiquattroFPV** [comment]
We have changed the data range in the setting.xml file but it's not able to change it more than 3650 days

**Comment by phw198** [comment]
Are you really needing to _sync_ more than 10 years ago? Or would a one-off export and import via `.ics` suffice - and then sync a smaller date window thereafter?

Just trying to understand your use case before changing any code...

**Comment by CiquattroFPV** [comment]
> Are you really needing to _sync_ more than 10 years ago? Or would a one-off export and import via `.ics` suffice - and then sync a smaller date window thereafter?
> 
> Just trying to understand your use case before changing any code...

We need to copy all calendar event from 2006 to today to a GCalendar event.

**Comment by phw198** [comment]
Why not export the Outlook calendar to ics and then [import](https://calendar.google.com/calendar/r/settings/export) to Google? This doesn't sound like you need a _sync_...

**Comment by CiquattroFPV** [comment]
> Why not export the Outlook calendar to ics and then [import](https://calendar.google.com/calendar/r/settings/export) to Google? This doesn't sound like you need a _sync_...

yes, we tried but the .ics file is too big so when we try to import it there is an error.. so we opted to find a solution for Sync the whole calendar and we found your app :-)

**Comment by phw198** [comment]
You could try manually chopping the .ics file up into separate files of a size that Google accepts? I could build a one-off version that has the 10 year restriction removed, but won't have time to at least until this weekend...

**Comment by Eletto01** [comment]
i also have the same problem with a 1.8MB file size limit on google.
We have a calendar size about 100MB...
A version without that limit would be great.
Best

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.8.2.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3827294/v2.8.2.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by CiquattroFPV** [comment]
Thank you
