### ISSUE TITLE
Guaranteed Quota

### ISSUE THREAD

**Issue by RHeggem** [phw198/OutlookGoogleCalendarSync#874]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.2.0 
**Installed or Portable**: Installed

**Problem Description**  
\I periodically see an alert about free calendar quota being exhausted. I purchased the guaranteed quota, but the problem persisted. I downloaded the Alpha version and the problem remains.

**Steps to Reproduce the Issue**  
1. \just wait for enough syncs to occur. This usually occurs later in the day. I don't do a lot of syncs, just every 3 hours.
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Please upload your OGcalsync.log file after you have started OGCS and performed the first sync.
