### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by dvonjr** [phw198/OutlookGoogleCalendarSync#876]
**Are you already using OGCS?**
Provide the version number. 2.8.2.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying. I donated before upgrading to this version so I could stop the splash screen. Now after updating the app acts as though I never donated.

**Comment by phw198** [comment]
Please could you confirm the email address that is shown as connected on the OGCS settings page for  Google? 

Would also help if you could upload your OGcalsync.log file after you have started OGCS and performed the first sync.

**Comment by dvonjr** [comment]
The email address is [removed]@gmail.com

The log file is attached.

**Comment by dvonjr** [comment]
I just replied to your email and afterwards I found the updated app to work correctly.

Thanks for your help.
