### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by burnt-loaded** [phw198/OutlookGoogleCalendarSync#879]
**Are you already using OGCS?**
V.2.8.2-Alpha

This is the error I get, can you please advice?
![Capture1](https://user-images.githubusercontent.com/57173435/67843018-e52e4800-fb03-11e9-847f-10df94fff00d.PNG)

**Comment by phw198** [comment]
Difficult to tell from that simple screenshot, but it looks suspiciously like you have set two-way sync on a Google calendar that you only have read permissions on... If so, the message is expected - you need to have writer access.
