### ISSUE TITLE
Does this work for an Outlook Mac user?

### ISSUE THREAD

**Issue by artsra** [phw198/OutlookGoogleCalendarSync#881]
Probably don't need the template. I came here because the frontpage said: 'does not need to be installed', but it does offer an install.exe. I am confused. Also, I use a MacBook. Can I use this in any way? Maybe put this in the FAQ? 

Thanks.

**Comment by phw198** [comment]
It also offers a `.zip`, which would be for those that don't want to install.

The website homepage says "Any version of Windows..." under minimal requirements - so no, unfortunately no support for Macs.
