### ISSUE TITLE
Sync Multiple Outlook Calendars to Google

### ISSUE THREAD

**Issue by sararenee2019** [phw198/OutlookGoogleCalendarSync#883]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Be able to sync multiple Outlook calendars to Google using different colors.

**Describe alternatives you've considered**
Looking into different sync programs to run side-by-side.

**Additional context**
None

**Comment by phw198** [comment]
Multiple calendar sync is being worked on through #165.

Colour sync is already available, though there are some bugs/enhancement also being worked on through out tickets.
