### ISSUE TITLE
OGCS blocked as malware for trying to access information stored in outlook

### ISSUE THREAD

**Issue by gotovamsee** [phw198/OutlookGoogleCalendarSync#885]
**OGCS Version**: v2.8.0.0  
**Portable**: Installed

**Problem Description**  
With every sync 'Microsoft Outlook' now gives a pop up warning message saying "A program is trying to access email address information stored in outlook. If this is unexpected, click deny and verify if your antivirus software is up-to-date"

Options are to allow access from 1 to 10mins. Deny or Get Help. 

Allowing accessing helps but only for 10 mins. Denying access instantly gives an error on OGCS appication saying "Operation aborted (Exception from HRESULT: 0x80004004 (E ABORT))". And the application stops syncing calendar items.

I am concerned on the fact that this application is trying to access email address information stored in my outlook.

**Steps to Reproduce the Issue**  
1. Open the application or start sync to reproduce this issue

**Comment by phw198** [comment]
You probably just need to update your virus definitions.

https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security
