### ISSUE TITLE
Prevent Calendar Item From Syncing from GCal to Outlook

### ISSUE THREAD

**Issue by nrcarnevali** [phw198/OutlookGoogleCalendarSync#887]
**Are you already using OGCS?** 
2.8.2.0

Sorry if this has been answered before but I couldn't find it in the user guide.

If I have a daily repeating calendar event at 7 am called "Walk Dog" on my GCal is there any way to prevent it from syncing to my Outlook Calendar? 

Many Thanks In Advance!

**Comment by fluff66** [comment]
i am not sure if you could exclude a specific appointment.  But you could create a new google calendar for dog walking, and any other entries you don't want to sync to Outlook.  On any device you can still see all appointments if you setup the calendars to display together, so you will be able to see all your personal  entries together.
