### ISSUE TITLE
UTC offset not calculated properly (DST) for recurrence end date

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#889]
**OGCS Version**: v2.8.2.0  

**Bug Description**  
For G->O sync, for recurrence end datetimes, the UTC is not properly taking into account daylight saving. This means the recurring event may finish a day later than it should in Outlook.

**Steps to Reproduce the Issue**  
1. Create a recurring daily series in Google in timezone "Europe/London" for 10-Nov-2019 (DST finished), finishing on 17-Nov-2019.
1. Sync recurring series to Google.
1. The Outlook series finishes on 18-Nov-2019.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.8.2.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3828384/v2.8.2.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by BrandonGriffis** [comment]
Could this be related to
https://github.com/phw198/OutlookGoogleCalendarSync/issues/843
It seems timezone detection is not always working properly.

**Comment by phw198** [comment]
No, this issue is different and only affects whether the last day of a recurring series is 1 day after the series is _meant_ to end.

But yes, #843 does need addressing...
