### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by merlin19888** [phw198/OutlookGoogleCalendarSync#890]
**OGCS Version**: v2.8.2.0
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
```
---------------------------
Sync Failed
---------------------------
The synchronization failed - check the Sync tab for further details:
-Value cannot be null. parameter name: source-
```
**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3828892/OGcalsync.log)

**Comment by phw198** [comment]
Please could you
1. apply [hotfix v2.8.2.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3829096/v2.8.2.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix))
1. increase the logging level to `FINE`
1. reproduce the issue and upload your logfile again.

Thanks!

**Comment by merlin19888** [comment]
Thanks!

The probleame was reproduce.
here the new log file.

[2019_11_11-OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3829110/2019_11_11-OGcalsync.log)

**Comment by phw198** [comment]
It doesn't look like you increased the logging level to `FINE`? Could you retry the test and upload of logfile after making that change?

**Comment by merlin19888** [comment]
Sorry, I didn't notice I didn't change it.
Thank for the help.

[2019_11_11-OGcalsyncB.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3829144/2019_11_11-OGcalsyncB.log)

**Comment by phw198** [comment]
:package: Could you please try again with [v2.8.2.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3833545/v2.8.2.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes - even if it works, I'd like to see the logfile again.

Thanks.

**Comment by merlin19888** [comment]
Hello, 
Thank you for the program. 
But unfortunately the file didn't help. 

[2019_11_12-OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3834699/2019_11_12-OGcalsync.log)

**Comment by phw198** [comment]
:package: OK, let's try that again with [hotfix v2.8.2.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3838784/v2.8.2.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix))...

**Comment by merlin19888** [comment]
Thank you!
But now there is another problem: 
"You must specify a time"
It seem that when the program tries to get the calendar it goes to the 2000's. 
"2019-11-13 08:40:58,346 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit last reached: 01/01/2000 0:00:00"

[Uploading 2019_11_13-OGcalsync.log…]()

**Comment by phw198** [comment]
It doesn't look like your logfile uploaded successfully - can you try again? So did the hotfix tell you there was a corrupted calendar item and how to find it?

FWIW the log line you quoted doesn't mean it's going back to 2000.

**Comment by merlin19888** [comment]
Yes, this time the log uploaded, 
I tried to find the source of the problem in the log, I just assumed the line is connected. 
(I'm starting to learn a bit of python, that is my level of programming)

Thank you for your help.

[2019_11_13-OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3839891/2019_11_13-OGcalsync.log)

**Comment by phw198** [comment]
I think I've just wasted an hour of my life staring at the logs wondering why it's not worked...when it looks like Microsoft's error message `You must specify a time. ` has a stray white space on the end!!

:package: OK, try again with [v2.8.2.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3843762/v2.8.2.11.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix))...

(Note, even once I've OGCS capturing the error properly, we've still got to work out what the underlying issue is - I'm hoping the guidance that OGCS should now provide will actually help!).

**Comment by merlin19888** [comment]
Sorry for this but yet again it's not working.
And again thank you very much! for the support.

"Corrupted item(s) with no start/end date exist in your Outlook calendar that need fixing or removing before a sync can run.<br/>Switch the calendar folder to <i>List View</i>, sort by date and look for entries with no start and/or end date."

[2019_11_14-OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3843854/2019_11_14-OGcalsync.log)

**Comment by phw198** [comment]
No, that is working. Now it's over to you to see if you can find the problematic item by viewing your calendar in List View...

**Comment by phw198** [comment]
@merlin19888 Were you able to find the problematic item(s) through the Outlook calendar "List View"?

**Comment by merlin19888** [comment]
Hello, 
I tried to find it but I didn't. 
In the meanwhile, I had to reformat my windows and the first time syncing it showed me the problematic item, so I deleted it and now the program works fine :)
Thank you very much for your help!

Andrew.

**Comment by phw198** [comment]
OK, that's really strange! The issue was I couldn't report the exact item with the problem because as soon as it is accessed programmatically, it would raise an exception. I guess rebuilding Windows fixed something somewhere :confused: 

Ah well, I'll roll in the extra advice I coded in on the initial error into the next release in case it helps anyone else.
