### ISSUE TITLE
OGCS does not start: crashes with error "Failed to access alternate mailbox"

### ISSUE THREAD

**Issue by jcpeiro** [phw198/OutlookGoogleCalendarSync#891]
**OGCS Version**: v2.8.0.0
**Edition**: Installed  
**Sync Direction**: O<->G

System does not start.  It crashes and gives an error message: "Failed to access alternate mailbox calendar" and terminates immediately after.  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3831101/OGcalsync.log)

How can I fix the problem?

**Comment by jcpeiro** [comment]
It worked fine for some weeks.

**Comment by phw198** [comment]
I'm thinking the calendar your had configured OGCS to sync against no longer exists? Try renaming your `settings.xml` file (found in `%APPDATA%\Outlook Google Calendar Sync`) out the way, so OGCS starts afresh and see if you can reconfigure it again...

**Comment by jcpeiro** [comment]
Thanks. It worked.  The calendar had changed name so I had to reconfigure manually in the Config file.

Enviat des del meu iPhone

El 12 nov 2019, a les 0:16, Paul Woolcock <notifications@github.com> va escriure:

**Comment by phw198** [comment]
:package: This should now be resolved (the issue highlighted to the user) with [v2.8.2.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3856106/v2.8.2.12.zip)
 ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
