### ISSUE TITLE
Update Google event failed to save.

### ISSUE THREAD

**Issue by wbree** [phw198/OutlookGoogleCalendarSync#892]
**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.
![image](https://user-images.githubusercontent.com/12870752/68616739-eb3e0480-04c5-11ea-9099-47b62714a86b.png)

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by phw198** [comment]
However, this looks the same as #844. To troubleshoot further:

1. Make sure you're upgraded to v2.8.2.0
1. Apply the [hotfix posted on #844](https://github.com/phw198/OutlookGoogleCalendarSync/issues/844#issuecomment-552665740)
1. Reproduce the error
1. Upload your logfile

**Comment by wbree** [comment]
I upgrade to 2.8.2.0  and the hotfix.
Still the same problem. See log file.
Hope to hear from you how to solve.

Greetings Wilco
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3837887/OGcalsync.log)

**Comment by wbree** [comment]
Is there anyway I can delete those entries who are giving these errors.

**Comment by phw198** [comment]
Your logfile still only shows you running v2.8.2.0 - ie the hotfix hasn't been applied.

Please can you make sure you've patched with the hotfix so OGCS shows v2.8.2.9, reproduce the problem and upload your logfile again?

**Comment by wbree** [comment]
Can you give me some hint how to patched my version with the hotfix.
 
Thanks,
Wilco

**Comment by phw198** [comment]
You mean you need more than the instructions already linked to next to the hotfix? Here's the [link again](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) for reference.

**Comment by wbree** [comment]
Thanks.
 
Wilco

**Comment by phw198** [comment]
Any joy running the hotfix? If so, please upload your logfile once you have reproduced the error.

**Comment by wbree** [comment]
I succeeded to install the hotfix. No more errors. But I could delete 
the source of the errors earlier.
Thanks

With regards,

Wilco de Bree

**Comment by phw198** [comment]
Open source software is about helping the community of users, not just fixing the problem you have. As per #844, without the logfile showing the problem under v 2.8.2.9 I can't fix this for anyone else.
