### ISSUE TITLE
[0x80004002] unresolved

### ISSUE THREAD

**Issue by dsjohnstonWV** [phw198/OutlookGoogleCalendarSync#893]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0
**Installed or Portable**: Installed

**Problem Description**  
When installing I still get error [0x80004002] despite having run not only Quick Repair but also the full online repair, which appears to amount to a full reinstallation of Office. I have checked that the Registry keys specified in the MS Knowledgebase article are indeed present. The installation fails at the same point in every case, with the same error.

The log file is attached.

Note that this computer seems to have a previous version of Office 365 Business installed, leftover from my employer before I retired. I have my own subscription to Office 365 (home) also installed, and that is what is actually used. See the attached screenshot. When I try to uninstall the Business version it appears to be uninstalling ALL versions of Office, so I canceled the uninstallation.

I hope you can advise steps to take beyond those in the FAQ.

Thank you,

David S. Johnston

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3834458/OGcalsync.log)
![Office Installs](https://user-images.githubusercontent.com/57652547/68643209-b4281d00-04de-11ea-9b48-dbd433fb7b37.JPG)

**Comment by phw198** [comment]
In order to receive support, you need to:
1. Reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)

If you had done that, the COM error would have been reported correctly as `0x80040155`, taking you to https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered. It's possible that the cancelled uninstall has removed parts of Office that OGCS relies upon....

**Comment by dsjohnstonWV** [comment]
I just finished trying v2.8.2.0, although I don’t generally try alphas. The reason I did not try it at first was because it seemed to be an Outlook issue, rather than one needing a fix in OGCS. However, I did try it, and as you said it resulted in error 0x80040155. I carried out all the steps suggested, and in the end was able to complete the installation.

Thank you for your help. I am very please with how the program works – no problems on my laptop, and the problem with the desktop install is now fixed.

Dave

**Comment by dsjohnstonWV** [comment]
I am trying to make a donation using the Donate button on the splash screen. However, when I get to PayPal it says “there is a problem” and to try again later. I will try again later, but there may be some other problem; perhaps with the email address?

Dave

**Comment by phw198** [comment]
That's great - glad it's all working now. To be fair, most developers would probably call the OGCS beta release a stable and the alpha a beta...I guess I'm too cautious 😉

Thanks for the donation! About the problem you were having with PayPal, could you possibly video a screen capture of the issue? If you need some software for that, https://www.screentogif.com is free and doesn't need install.

**Comment by dsjohnstonWV** [comment]
Paul, I can’t reproduce the problem with the donation. Today the process takes me to the Paypal donation page without an error, which it did not yesterday. Probably this was some transient error with Paypal, or perhaps it was resolved when I signed in to Paypal in the normal way. At any rate, I’m glad you got it and appreciate the simplicity and performance of the app.

Dave

**Comment by phw198** [comment]
Thanks for confirming it was just a temporary glitch and nothing I need to fix :+1:
