### ISSUE TITLE
Alternate mailbox - Public Folder has no Deleted Items folder

### ISSUE THREAD

**Issue by Scottdeslippe** [phw198/OutlookGoogleCalendarSync#895]
Version 2.8.0.0. 

Just downloaded OGCS and started set up but when I select the calendar in Outlook I want to sync to google I get a Failed to find calendar folders in alternate mailbox Error. 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3838076/OGcalsync.log)

**Comment by phw198** [comment]
:package: Please let me know if this is resolved with [v2.8.2.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3856128/v2.8.2.13.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Note:** You must upgrade to the latest alpha (v2.8.2) before applying this fix.

**Comment by phw198** [comment]
@Scottdeslippe Any feedback on testing the hotfix?

**Comment by phw198** [comment]
:spiral_notepad: Rolling this in to the next release regardless.
