### ISSUE TITLE
Crashing when syncing recurring events

### ISSUE THREAD

**Issue by cwd7c4** [phw198/OutlookGoogleCalendarSync#896]
**OGCS Version**: v2.8.0.0  
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
I recently migrated to a new IT environment within my company and updated my OS to Windows 10.  Today, I redownloaded OGCS and the sync kept crashing when it tried to sync recurring meetings.  Can anyone help me determine if this is a bug in the system, or a problem with the new IT environment?

**Steps to Reproduce the Issue**  
1. Click on...
     Sync
**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3853183/OGcalsync.log)

**Comment by phw198** [comment]
You've picked a read-only Google calendar to sync to. That's clearly not going to work and v2.8.2 would tell you as much.
