### ISSUE TITLE
How to troubleshoot: "The Google calendar being synced with must not be read-only. Cannot continue sync."

### ISSUE THREAD

**Issue by cwd7c4** [phw198/OutlookGoogleCalendarSync#898]
**Are you already using OGCS?**
v2.8.2.0
**Describe the question you have**
I tried syncing and got the following error message (see header), "The Google calendar being synced with must not be read-only. Cannot continue sync."  Can someone please advise me on how to troubleshoot this issue?  

It seems that,\ maybe, all I have to do is change a setting in my Google account but I do not know how to do that.

Thank you!

**Comment by phw198** [comment]
As per your other issue #896, you've selected the built in `Contacts` Google calendar which is not a "real" calendar. Pick a different calendar within your Google account that is not read-only - eg the default one or create a new calendar specifically for OGCS to sync to.
