### ISSUE TITLE
COM Exception Encountered (on startup)

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#90]
COM exception encountered on startup (of OGCS 2.4.0.0). Installed fine and
worked fine until the machine was rebooted. Now every time it gives me this
error.  
  
Attached is zip file containing logs and settings. Syncing with Outlook 2016,
running a Office365 exchange account with calendar.  
  
The same happened with the previous version of OGCS.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 513](http://outlookgooglecalendarsync.codeplex.com/workitem/513)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Thu at 5:45 AM
**Reported by:**	tah1174
**Updated on:**	Thu at 5:54 AM
**Updated by:**	tah1174

#### Binary Attachments

[Outlook Google Calendar Sync.zip](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=513&FileAttachmentId=1661571)
[OGcalsync.log](https://gist.github.com/phw198/c9c21abac6ce07ae48e3062c4ca390c3#file-ogcalsync-log-L7-L9)

**Comment by phw198** [comment]
On *2017-05-11 12:54:18 UTC*, **tah1174** commented:

Further to this I have now found out that If I wait for a while (after the first COM Exception shuts it down the first time, and after other startup activity ceases) before relaunching it, it seems to work fine.

**Comment by TontonLud** [comment]
Same error here with Outlook 2016 on Windows 10 (1703), Exchange 2016.
[Outlook Google Calendar Sync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1010582/Outlook.Google.Calendar.Sync.zip)

**Comment by phw198** [comment]
@TontonLud Your issue is different from the OP. You have COM `0x80040155 Interface Not Registered`, which is [covered in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#ogcs-just-crashes-with-a-strange-error-code).

@tah1174 Could you change your logging level to `DEBUG`, repeat the error and resubmit your logfile - I can't quite tell what's causing the issue from the current log. If the app won't start enough for you to open change the setting, open the `settings.xml` file and change `LoggingLevel` to `DEBUG`.

**Comment by tah1174** [comment]
Hi Paul,

I have attached the log file and settings after changing the settings to DEBUG logging.

I found that I only observe the error when starting the Sync before Outlook is started (or at around the same time).  If I wait until Outlook is completely running I get no errors.

Best Regards,
Tom Harris

**Comment by phw198** [comment]
@tah1174 you can't attach files to the ticket when replying via email - you need to log in to GitHub and upload it.

**Comment by TontonLud** [comment]
@phw198 I've checked the FAQ. The only version installed on my computer is Office 2016. My computer is brand new and I've never installed a previous version of Office.

So I've check my debug log
`2017-05-26 09:37:16,818 ERROR 1 OutlookGoogleCalendarSync.OGCSexception [0] - System.InvalidCastException: Impossible d'effectuer un cast d'un objet COM de type 'Microsoft.Office.Interop.Outlook.ApplicationClass' en type d'interface 'Microsoft.Office.Interop.Outlook._Application'. Cette opération a échoué, car l'appel QueryInterface sur le composant COM pour l'interface avec l'IID '{00063001-0000-0000-C000-000000000046}' a échoué en raison de l'erreur suivante : Interface non enregistrée (Exception de HRESULT : 0x80040155).`

I've checked HKEY_CLASSES_ROOT\Interface\{00063001-0000-0000-C000-000000000046}\TypeLib key, version is 9.6.
Then I've checked HKEY_CLASSES_ROOT\TypeLib\{00062FFF-0000-0000-C000-000000000046} key, I've only 9.6 subkey.

**Comment by phw198** [comment]
@TontonLud I've created a new issue #220 to track your problem - please post updates there.

**Comment by phw198** [comment]
@tah1174 Any chance you can login to GitHub to upload your logfile?

**Comment by tah1174** [comment]
Please find attached the log files as requested.
[TH-Log Files.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1062621/TH-Log.Files.zip)

**Comment by phw198** [comment]
@tah1174 
:package: Could you see if this [Hotfix-v2.5.0.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1082594/Hotfix-v2.5.0.6.zip) makes any difference? [[See instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

**Comment by tah1174** [comment]
Hi Paul,

No difference in behavior observed after applying the hotfix.

Best Regards,
Tom Harris,
0432270535

**Comment by phw198** [comment]
@tah1174 
Seems you've been hitting a couple of different bugs. The first in the ZIP file on CodePlex for v2.4.0 shows `System.IO.IOException: The process cannot access the file 'C:\Users\THarris\AppData\Roaming\Outlook Google Calendar Sync\settings.xml' because it is being used by another process.`. This was fixed in subsequently releases.

Your [last logfile](https://github.com/phw198/OutlookGoogleCalendarSync/issues/90#issuecomment-307249753) again on v2.4.0 shows `Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)` - check the [wiki entry](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002801d---type_e_libnotregistered) for help around this one.

However, I do notice that on the above failure, your connection to Exchange was `olCachedDisconnected`, and then when it was successful later, it showed `olCachedConnectedDrizzle`. I wonder if this is playing some part in it too.... Were you on a ropey network connection? Does OGCS behave better on a stable connection?

**Comment by phw198** [comment]
@tah1174 I suspect this issue is resolved with alpha release v2.5.3 - could you confirm?
