### ISSUE TITLE
Fail to load Release Notes with bad Proxy

### ISSUE THREAD

**Issue by mgueydan** [phw198/OutlookGoogleCalendarSync#900]
**OGCS Version**: post 2.8.2 alph. commit : 0d574dd13d207f42c8d5d2a0193e05e3342d0d8e
**Edition**: cloned
**Sync Direction**: None

**Bug Description**  
System.Diagnostics.Process.Start at line 448 from Program.cs fail with exception due to strict proxy

**Steps to Reproduce the Issue**  
1. Clone commit 0d574dd13d207f42c8d5d2a0193e05e3342d0d8e
2. Build
3. Disconnect Host from the internet (or, in my case, use a pretty strict proxy)
4. Remove appenders from logger.xml (see  #899)
5. Launch
6. Application crashes and Log is truncated.

**Any other information**  
As the proxy usage is handled in the rest of the application, I assume this needs to be done here too. In my case i just used a try watch with a warning, something like : 
```c#
try
{  
          System.Diagnostics.Process.Start("https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/docs/Release%20Notes.md");
}
catch (Exception)
{
          log.Warn("Unable to load Release note (due to proxy ?)");
}
```

Call Stack being :
```
System.ComponentModel.Win32Exception (0x80004005): Application introuvable
   à System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   à System.Diagnostics.Process.Start()
   à System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   à System.Diagnostics.Process.Start(String fileName)
   à OutlookGoogleCalendarSync.Program.isNewVersion(Boolean isSquirrelInstall) dans C:\workspace\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:ligne 448
   à OutlookGoogleCalendarSync.Program.Main(String[] args) dans C:\workspace\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:ligne 65
```

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3862957/OGcalsync.log)

**Comment by mgueydan** [comment]
Damn, I can't figure out how to format code.

**Comment by phw198** [comment]
I'm not sure this is a problem with your proxy. The code is simply saying to start your _default_ browser and open the URL passed to it. 

When the exception occurs, does a browser open? If so, what URL is it trying to go to? What is your default browser?

Options could be on fail:
* try to open `iexplore.exe` explicitly
* try to determine [default browser through registry](https://stackoverflow.com/questions/10503909/how-can-i-launch-a-url-in-the-users-default-browser-from-my-application/10503920#10503920)

**Comment by phw198** [comment]
As per #901, you mentioned Edge is your default.

Could you try replacing  
``` c#
System.Diagnostics.Process.Start("https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/docs/Release%20Notes.md");
```
with
``` c#
System.Diagnostics.ProcessStartInfo psi = new System.Diagnostics.ProcessStartInfo("https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/docs/Release%20Notes.md");
psi.UseShellExecute = true;
psi.Verb = "open";
System.Diagnostics.Process.Start(psi);
```

**Comment by phw198** [comment]
Any update @mgueydan ?

**Comment by mgueydan** [comment]
Sorry, you know what it is, once you have a workaround, you don't really care the initial issue.

- Test 1
** Reverting to 0d574dd13d207f42c8d5d2a0193e05e3342d0d8e
** removing appenders again
** resetting default browser on edge. 
** launching
Result is : Edge is now opening on "https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/docs/Release%20Notes.md"

I'm not sure what changed in my configuration in the mean time.

- Test 2
** same as 1
** setting default browser on IE
Result is : IE is now opening on "https://github.com/phw198/OutlookGoogleCalendarSync/blob/master/docs/Release%20Notes.md"

- Test 3
** setting default browser on a non-existing file
Same issue as describerd here : "System.ComponentModel.Win32Exception: Application introuvable"

- Test 4
** same as 3 (with a broken default browser) and adding your code update :
Similar issue : "System.ComponentModel.Win32Exception: Aucune application n’est associée au fichier spécifié pour cette opération"

**Comment by phw198** [comment]
Thanks for the update. Could you try test 3 and 4 on 58a809aa8f1672117f8c77be095de6758690625f ?

Out of interest, how are you setting the default browser to a non-existant file? Are you editing a registry key manually?

**Comment by phw198** [comment]
Closing this as believe it is superseded from v2.9.1 with the Helper class with OpenBrowser() method.
