### ISSUE TITLE
OGCS and Windows Security -Virus & Threat protection

### ISSUE THREAD

**Issue by Veggie352** [phw198/OutlookGoogleCalendarSync#902]
**Are you already using OGCS?**
Provide the version number. 
2.8.2.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

Whenever OGCS syncs, I get a pop up security warning from Windows Security saying a severe threat has been blocked. 

The threat detected is Trojan:Win32/Fuery.C!cl, alert level is severe and the affected item is file: C:\Users\bbkt\AppData\Local\OutlookGoogleCalendarSync\app-2.8.2-alpha\00030503.tmp

Can you advise where there is an issue with OGCS. I have noticed this has only happened since I updated with 2.8.2.0.

It appears to be blocked by Windows Security but is this a genuine virus or not?

Thanks

**Comment by phw198** [comment]
Thanks for raising this. I'm not sure what has produced that `00030503.tmp` file - it's not one I ship. What's the timestamp of the file? It's possible it is produced during the install process, but I've not noticed this before. 

In order of triage, what happens to the ability for OGCS to run if you:
1. Rename it to something else
1. Allow anti-virus to quarantine it
1. Delete it

If you uninstall and reinstall v2.8.2, does the `.tmp` file reappear? Are there any other `.tmp` files?

**Comment by phw198** [comment]
I've just run an install of OGCS, and no `.tmp` file appears.
```
c:\>dir /s %LOCALAPPDATA%\OutlookGoogleCalendarSync\app-2.8.2-alpha\*.tmp
 Volume in drive C has no label.
 Volume Serial Number is F0B0-9417
File Not Found
```
I rather fear you have something else malicious dropping files around your computer...

**Comment by Veggie352** [comment]
I cannot follow steps 1 -3 you have described as Windows Security automatically deletes it. Hence if I run a dir on the folder there is nothing there. Each time Windows Security reports an issue, the file is a different .tmp file. The latest is C:\Users\bbkt\AppData\Local\OutlookGoogleCalendarSync\app-2.8.2-alpha\00025886.tmp. OGCS seems to run with no issues. Based on your concern, which I have as well, I will run a full antivirus scan on my HDD and also uninstall and reinstall v.2.8.2/
I will let you know what I find. Thanks!

**Comment by Veggie352** [comment]
I ran a full virus scan on complete HDD and no issues found. I deleted OGCS and restarted computer. I have reinstalled OGCS and the issue is not occurring now. I will continue to monitor but looks like the error has gone away since reinstalling OGCS. Any ideas what could have caused it? Thanks

**Comment by phw198** [comment]
I did find another github project that uses the same installation mechanism that seemed to have a similar issue, but the problem went away - apparently due to the AV correcting the false positive. Possibly the same happening here, but it's difficult to know for sure...

**Comment by Veggie352** [comment]
Thanks Paul. Issue seemed to go away by removing and reinstalling OGCS. Thanks for looking into this and all good for now
