### ISSUE TITLE
Don`t work [0x8002801D]

### ISSUE THREAD

**Issue by bobinek** [phw198/OutlookGoogleCalendarSync#903]
My OGCS don`t work, help please. 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3874564/OGcalsync.log)
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
You have a busted install of Office - error `0x8002801D`. [See the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x8002801d---type_e_libnotregistered).

**Comment by bobinek** [comment]
I was repair instal and it nothing do.

sob., 23 lis 2019 o 11:41 Paul Woolcock <notifications@github.com>
napisał(a):

**Comment by phw198** [comment]
So I guess you didn't do any of the registry fixes then...
