### ISSUE TITLE
'Check Busy' on OGCS start

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#905]
Hi - 
I'm running Win 10 v1903, Outlook v1911, and OGCS v2.8.0.0.
**Is your feature request related to a problem? Please describe.**
I start up outlook using a scheduled task 90 seconds after logging on. If I start OGCS (either manually or with a scheduled task) while Outlook is syncing "send/receive" to the server, the Windows / Outlook security warning will appear.  This seems to be all about timing.  If I wait a minute or two after the send/receive has completed there are no security (or other issues) and OGCS starts and works fine the rest of the day with no further warnings or failed sync's..

**Describe the solution you'd like**
My guess (I don't know how to check) is that there is a conflict when OGCS is trying to start that generates the security flag.  I will receive upto 3 warnings that have to be closed.  My suggestion is a "check if outlook busy" process to let outlook finish and then start / connect OGCS.  I'm happy to gather data if you tell me what you need.

**Describe alternatives you've considered**
The fully working answer is to wait 2 minutes after send/receive completes the first time and then start OGCS.  This works manually or as a scheduled task.

**Additional context**
The number of warnings also seems related to timing - the faster I try to start OGCS, the greater the number.  However, I've never had more than 3, but that could still be timing also.   I don't know  if it's important, but I sync with an IMAP server, not an exchange server.

**Comment by phw198** [comment]
The security warnings aren't related to Outlook being busy, but more likely your AV software updating its definitions. See [here for more details](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) on the popup.

The simplest way of working around this would be to set OGCS to start on system startup, but also configure a delay of eg 300 seconds (5 mins).

**Comment by ghost** [comment]
OK.  I didn't think / know that an MS AV update would impact other programs that way.  Delayed start works fine.
