### ISSUE TITLE
This program doesn't seem to work unless my computer is on and syncing every 15 min

### ISSUE THREAD

**Issue by dwall8888** [phw198/OutlookGoogleCalendarSync#910]
**Are you already using OGCS?**
2.8.2.0

**Describe the question you have**
This program doesn't seem to work unless my computer is on and syncing every 15 minutes. I need it to work with my computer off too. Can you please advise if it should be now, or if that's a feature you're able to add to it?

**Comment by phw198** [comment]
Sorry, you want your computer to run software while it's turned off?

**Comment by dwall8888** [comment]
No I want ogcs to run all the time, regardless of my computer being on or off. I use it to update google calendar every 15 min. That google cal is viewed in my phone when im in the office or out of the office.

**Comment by daniu-de** [comment]
[OT] really wonder what an applications engineer is ... would think it has something to do with software[\OT]

I recommend to rethink what you want: you install (or use) a software ON YOUR COMPUTER and think that it can sync your data which is not on your computer to google while the computer (where you installed/use the software) is not running? If that does not ring a bell then ask someone you know who knows more about software to explain to you why this is not possible.

**Comment by dwall8888** [comment]
Well I appreciate the feedback I guess.. I was hoping to add a cloud based service to continue updates in background regardless of the computer's state. Something that would permit this to continue updating. I travel for work a lot so when it comes to getting updates I rely on my google calendar a lot. And your app. Have for a long time. That said, when it's not running my calendar isn't syncing, and my computer can't run while it's off and in the trunk.

**Comment by phw198** [comment]
@dwall8888 Yes, cloud services are obviously all the rage, but the very point of why OGCS was created was for people who want to sync their work Outlook calendar outside of their fire-walled corporate environment.

In other words, OGCS needs to be _installed somewhere_ - and yes, you could spin up a VM in which ever cloud service provider of your choosing (Google, AWS, Azure...) and install Outlook and OGCS. But unless your corporate IT have a pretty lax view on security, Outlook won't be able to connect to your Exchange server....and therefore OGCS has nothing to sync.

Your other option is to create/use a server/computer within your office environment that runs OGCS all the time (ie don't rely on your laptop), but that's probably going to raise lots of questions from IT.

(And for anyone thinking "What about EWS?", then yes, that may work for a small set of users, but this would likely trigger other corporate security mechanisms such as MFA. Plus in the 4 years of developing OGCS, barely anyone has asked for EWS to be supported, so I've very little appetite to implement it).
