### ISSUE TITLE
OGCS fails when the description of a single instance of a recurring event is changed on the Google side.

### ISSUE THREAD

**Issue by mjlipton** [phw198/OutlookGoogleCalendarSync#911]
This failure happens to me fairly frequently.   My remedy is to delete the instance of the recurring event, and replace it with a non-recurring event.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3912259/OGcalsync.log)

**Comment by phw198** [comment]
Duplicate of #897 which is resolved with hotfix posted.
