### ISSUE TITLE
Move Outlook item to next day, update subject, sync, causes delete in Google, sync, then deletes in Outlook

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#912]
**OGCS Version**: v2.8.2.14
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
Moving Outlook item to next day (drag and drop), then updating subject text, causes delete on Google calendar on next sync. Then in next subsequent sync, deletes the entry in Outlook calendar

I've seen this same error occur over the past 3-4 months, on numerous versions / betas / alphas, but never had the time or patience to try to recreate what I done. 

Still not sure I know exactly what causes the erroneous delete in Google, then in Outlook. But I realized today that the original subject text included 1-2 special characters. The "/" and/or the "(" or ")". 

So my first reaction was to wonder whether there was some form of parsing going on and the program gets confused.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3917361/OGcalsync.log)
.

**Comment by Mr-Sloth** [comment]
I have the same problem, If you move a calendar entry in outlook. It wants to delete it at the next sync because it does not exist in google calendar. 
On delete confirmation window a 3rd button with "No, push instead" would help.

Any workaround?

**Comment by phw198** [comment]
@kwagner115 Given your log file does not include a `Item paste event caught` line, I can only assume you don't have OGCS running when you drag and drop the calendar item in Outlook.

See [wiki entry](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#copied-outlook-appointments-cause-unexpected-deletions).

**Comment by kwagner115** [comment]
Paul,
 
I always have OGCS running! It is set up to start at Windows start. The only time it is not running is immediately following a reboot, as it has a 300 second start-up delay to handle to antivirus Outlook warning. 
 
Will play around with it when I have some free time. 
 
Kevin

**Comment by phw198** [comment]
@kwagner115 OK, odd then. You'd need to build a test case from scratch, eg:
1. With Outlook running, close and restart OGCS.
1. Create a problem item in Outlook and sync
1. Click and drag-copy the item
1. Sync and reproduce the problem.
1. Upload logfile, mentioning the time and title of your test item.

**Comment by McoreD** [comment]
@kwagner115 good luck, I hope you succeed because I had O <--> G with Delete enabled (yes, had too much confidence after using OGCS for over a year) and just one day, two months of Outlook calendar items were deleted (November and December). They were not in Google Calendar either.

I have since turned on Ask for Confirmation on deletion. 

In general, yes, shifting time in Outlook and/or changing Calendar Title prompts OGCS to remove the item completely.

**Comment by phw198** [comment]
@McoreD Changing the title in itself would have no bearing on whether an item is removed - items are matched on their internal systems IDs (both in Outlook and Google).

The reason that you need OGCS running when copying or click-and-dragging items in Outlook is because it is supremely dumb and also copies the internal IDs - OGCS needs to be able to see this happen in real time to fix it....otherwise duplicate IDs cause problems.

Note: Deleted items can always be retrieved from Google `Bin` or Outlook `Deleted Items`.

**Comment by kwagner115** [comment]
"Rector Holiday Party??" on Dec 20, moved to Dec 21 with title amended to "Rector Holiday Party"

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3942356/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3942365/OGcalsync.log)

Time of event not changed

**Comment by kwagner115** [comment]
Just uploaded a recreated failure with log.
 
Kevin

**Comment by phw198** [comment]
@kwagner115 So did you _really_ do step 1 before step 3? Your logfile simply shows you starting OGCS, running a sync and it doing the delete in Google on the 20-Dec. There's barely any time for you to have moved the Outlook item to the 21-Dec after starting OGCS and running the sync (20 seconds).

This is going to be very tricky to troubleshoot, so instructions really do need to be followed. Revised steps now are:
1. Start OGCS
1. Turn on `Create CSVs`
1. Create Outlook item on 20-Dec and sync
1. Save the CSVs into a zip file and call it `Initial state.zip`
1. Click and drag the 20-Dec item to 21-Dec
1. Sync (assuming incorrect delete happens in Google)
1. Save the CSVs into a zip file and call it `problem.zip`
1. Upload ZIPs and `OGcalsync.log`

All,
I note @kwagner115 is syncing to iCloud via Outlook - is that common with everyone on the ticket?

**Comment by kwagner115** [comment]
Paul,
 
It is possible that the 300 second delay is what is catching me. I will have to retest as your sequence below. 
 
OGCS was running in my first test, and then I made the drag drop and title update. Then I forced a sync by pressing the sync button. I’ll bet I was able to do all of that before the 300 second “wait” had passed.  
 
Kevin

**Comment by kwagner115** [comment]
I tried for over an hour this evening to try to re-create the error with no success. That is exactly why I didn’t report it months ago. It seemed so random, I could never seem to see a pattern. IO will just wait toil it happens again ;-(
 
Sorry.
 
Hopefully someone else who is having similar issues will stumble on the “just right” set of circumstances!
  
Kevin

**Comment by kwagner115** [comment]
OK.  Got up this morning and just tried the drag to the next day for an existing Outlook calendar entry. And to my surprise (well, not really), it did fail. But I was not ready to capture as you had asked. 
 
So the log file is large, but the failures happened at or about 8am CT in the US. 
 
As you can see below, OGCS is and has been running, Outlook is running,  this item in question (dragged from Dec 26 to Dec 27 – Call Directv) is now asking to OK the delete! This is wrong. Moving to next day shouldn’t prompt for delete. I answered YES, finished the sync. That would have been the result if I did not have confirm delete option set on. Then I requested another sync and it then prompted for delete of the entry on Dec 27. I answered YES, finished the sync. That would have been the result if I did not have confirm delete option set on.
 
Kevin
  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3945208/OGcalsync.log)
[OGcalsync.log1.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3945211/OGcalsync.log1.log)
![ScreenPrint](https://user-images.githubusercontent.com/33904818/70536723-e603c200-1b24-11ea-86eb-79b6845f397f.png)

**Comment by phw198** [comment]
> It is possible that the 300 second delay is what is catching me. I will have to retest as your sequence below.

Not with your logfile [posted here](https://github.com/phw198/OutlookGoogleCalendarSync/issues/912#issuecomment-563496779) - you started OGCS manually which doesn't use the delay. The delay is only when OGCS is started automatically at system startup.

OK, so the other time that OGCS cannot detect if you have click-and-dragged an Outlook item is _during_ a sync. I wonder if because you have Push sync enabled, that if you are making several changes over the course of a few minutes, you are clicking and dragging in the middle of OGCS syncing?

Could you do some tests on this? Conciously dragging items outside of an active sync, and then during a sync?

**Comment by kwagner115** [comment]
Paul,
 
I had no success recreating a failure. I tried numerous drag and drops with OGCS running, not running, immediately following a reboot of Windows with 300 sec delay, during a sync, etc..
 
This one has me baffled!
 
Kevin

**Comment by kwagner115** [comment]
Happen again today. Made a simple change to subject text as follows:

Was "Travel to Dallas on way home??"

Changed to: "Travel thu Dallas on way home??"

Caused a delete first on Google side, then on next sync a delete on Outlook side.



2019-12-18 16:03:36,448 FINE  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Comparing Outlook CalendarID
2019-12-18 16:03:36,448 FINE  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Comparing Outlook EntryID
2019-12-18 16:03:36,448 FINE  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Checking 04/01/20 => "Travel to Dallas on way home??"
2019-12-18 16:03:36,464 FINE  5 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - all day event
2019-12-18 16:03:36,464 ULTRA-FINE  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Checking 04/01/20 => "Travel thu Dallas on way home??"
2019-12-18 16:03:36,464 FINE  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Comparing Outlook GlobalID
2019-12-18 16:03:36,573 FINE  5 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - all day event

**Comment by phw198** [comment]
Forgot to say, if you're now on v2.8.3 then the CSV files are kept from the previous sync run too - so it should make it easier to collect the files from before and after when the delete happens. 

Probably too late for that last delete now though...

**Comment by kwagner115** [comment]
I am on 2.8.3 ;-(
 
But will keep in mind the CSV files going forward.
 
PS… I know you explained the subject line does not play a roll in any matching, but just a coincidence perhaps that the problem this time also had a ? in the subject text.
  
Kevin
