### ISSUE TITLE
Forbidden 403 Updated Event failed to save.

### ISSUE THREAD

**Issue by techfilmguy** [phw198/OutlookGoogleCalendarSync#918]
**Are you already using OGCS?**
2.8.0.0

**Describe the question you have**
Followed the steps in the guide. Allowed permissions from Google. When I went to sync it kept giving me the Forbidden 403 error.
I created a test event in my Outlook and it did not show up.
Attached it the log file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3941943/OGcalsync.log)

**Comment by phw198** [comment]
If you upgrade to v2.8.2, it'll tell you syncing to a read-only calendar is not possible.

**Comment by techfilmguy** [comment]
Thanks for the response. So why is my Outlook/Google Calendar Read-Only? My Outlook calendar is through my work and I should be able to edit event and such(which I can) so i'm confused on how it is read only?

**Comment by techfilmguy** [comment]
I'm curious as to which calendar is "Read-Only"?

**Comment by phw198** [comment]
I guess you've not upgraded to the latest version of OGCS then?

You're syncing _to_ Google so it needs write access to that - so that's the calendar that is apparently read only.
