### ISSUE TITLE
Application cannot be started - error at startup

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#92]
I get error message at startup: "Application cannot be started. Contact the
application vendor".  
Full log attached. Can you help solve this issue? Can this be due to AV?  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 515](http://outlookgooglecalendarsync.codeplex.com/workitem/515)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Thu at 10:25 AM
**Reported by:**	rrud
**Updated on:**	Thu at 10:25 AM
**Updated by:**	rrud

#### Plaintext Attachments

[CodePlex Issue #515 Plain Text Attachments](https://gist.github.com/6eb3538b0e3bf08da3ead6b91e7c6e5b)

**Comment by phw198** [comment]
This looks like a duplicate of issue #203, so please continue posts there.

**Comment by rrudrrud** [comment]
I'm using Avast 17.4.2294 (built 17.4.3482.0) and it was disabled it in the first place while running OutlookGoogleCalendarSync.application but couldn't run the software anyway. I'm not sure if simple disable is enough. May AV still prevent app from running? I'll try to create an exception now.

**Comment by Engineerica-NLA** [comment]
My logs too from error.
[OGcalsync.log.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1321508/OGcalsync.log.zip)

**Comment by phw198** [comment]
@Engineerica-NLA This issue is closed and your error does not relate to it. You do have a problem whereby you're running v2.5.0 and it's not prompting you to upgrade to v2.6.0 (I've captured this in issue #313), but please could you [upgrade to v2.6.0 manually](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.0-beta/Setup.exe).

**Comment by Engineerica-NLA** [comment]
Thanks! I went ahead and updated it.  Hopefully this helps with the issues it’s reporting.

-Nick
