### ISSUE TITLE
Syncing Recurring Microsoft Teams Meeting

### ISSUE THREAD

**Issue by ablundon** [phw198/OutlookGoogleCalendarSync#920]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3950545/OGcalsync.log)

**OGCS Version**: v2.8.2.0
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
I have a recurring meeting in my Outlook calendar that is not being copied to the Google Calendar.  The item is a meeting that is set up in Microsoft Teams (which is integrated with Outlook and the MS environment).

Note that all other calendar entries appears to be synced correctly.  I can also create new entries (and delete) within Outlook and they got modified in Google.

**Comment by phw198** [comment]
I doubt this would be anything specific to Teams - I use that all the time without issue. Some initial  troubleshooting to try:
* Turn on CSV Export, sync and then check if the item is listed in `outlook_appointments.csv`
* If not, [try different datetime formats](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) until it is picked up.
