### ISSUE TITLE
Confirm Delete...FROM WHAT!?

### ISSUE THREAD

**Issue by curts** [phw198/OutlookGoogleCalendarSync#921]
**Is your feature request related to a problem? Please describe.**

When OGCS is set to confirm deletes I am confused as to where I am deleting.  This just happened...I am working along happily (as opposed to grumpily) and I see this confirmation dialog:

![image](https://user-images.githubusercontent.com/1950836/70630648-81626900-1bf1-11ea-8a6e-ca207f20bb04.png)

Hmmm, I say to myself audibly, WTF is going to happen when I select, "Yes"?  Am I getting rid of an event in Google, in Outlook, or both?  The worst part of it...I can't even interact with the OGCS application to view the sync status property page because these confirmation dialog boxes are application modal!  I either have to select Y/N on the dialog, or exit/end-task the OGCS application!  

**Describe the solution you'd like**

At the very least, the modal should clearly indicate where the delete(s) will happen (local Outlook, remote Google, both).  Alternatively, make the dialog non-modal.  *Ideally*:  create a dialog that has a list of deletion confirmations - allow the user to cherry-pick some/none/all of the items for deletion.

**Describe alternatives you've considered**

I have thought about gouging my eyes out with a dull fork, but that does not seem to address the underlying issue...and I would still be confused with the screen reader's audible prompt from the accessibility helper.

**Additional context**

None

**Comment by phw198** [comment]
Thanks for the detailed feedback...and humour :wink: 

> create a dialog that has a list of deletion confirmations - allow the user to cherry-pick some/none/all of the items for deletion.

An interesting idea, though I'm just going to go with the simpler option of showing in the dialogue title bar where the deletion would happen. Confirming deletions _shouldn't_ be necessary unless something is going wrong with the sync - and if that's the case, then I don't want to make it particularly easy to cherry pick as we need to get the bottom of why items are being marked for deletion in the first place.
