### ISSUE TITLE
Start OGCS not with computer but with outlook?

### ISSUE THREAD

**Issue by mhuber3004** [phw198/OutlookGoogleCalendarSync#922]
**Are you already using OGCS?**
2.8.2.0

**Describe the question you have**
I would like OGCS to start automatically, but not with my computer but when I start outlook. (reason: I often *don't* start outlook when starting my computer because I want to work in peace ...) Is that possible? When I check "start on login", outlook is started automatically as well. Sorry if the question is stupid, I am no expert.

**Comment by phw198** [comment]
No, not stupid - [here's how to do it](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#start-ogcs-after-outlook).

However, you can have OGCS running and scheduled to sync, and if Outlook is not running, it will start it programmatically, then close it again after the sync is complete. You should barely notice, except for an Outlook icon in the task tray with a cog over it.

**Comment by mhuber3004** [comment]
Thank you! I did not get that VBA module to run - my fault, surely. But I understand now what you mean by "you should barely notice". I tried again with "start on login" and *normally*, it really works fine, just symbols in the task bar. But *sometimes* outlook is started in full window mode and stays open. And I haven't found out yet why it happens sometimes and sometimes doesn't.

**Comment by phw198** [comment]
If Outlook is not being responsive, OGCS will fall back to trying to open it in full - sounds like that might happen sometimes on your system.

Are you OK for me to close this ticket now?

**Comment by mhuber3004** [comment]
OK, yes, thank you!
