### ISSUE TITLE
Outlook crashes

### ISSUE THREAD

**Issue by SkipHill** [phw198/OutlookGoogleCalendarSync#925]
**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
I don't start outlook with the boot, but OGCS does start with a delay. It brings up the reminder window while doing the sync, but that window does not close automatically. It stays open with OGCS.

If I leave that reminder window open and start outlook, the first attempt that Outlook makes to sync email causes outlook to just disappear. Upon restarting Outlook, it works as expected. 

If I close OGCS and the reminder window, and then start Outlook, the crash does not occur.  

It's not troublesome enough to cause me to abandon your package though, I love it. Best and easiest way I have found to sync Outlook to Google where I can see it on my phone when I need to. 

**Any other information**  
Windows 7-64

**Comment by phw198** [comment]
Hmm, I thought the Reminder window should also close automatically if OGCS starts Outlook to sync. Could you upgrade to v2.8.3 and see if the issue remains?

**Comment by SkipHill** [comment]
Sorry, didn’t notice there was an update. I’ll try it. 

Thanks Paul

Skip

**Comment by SkipHill** [comment]
Ok, tried the latest v2.8.3 this morning. It did close the reminder window, but the outlook crash still occurred with the first attempt to sync email. As before, a restart of outlook immediately continues seemingly where it crashed with syncing and succeeded. I have 7-10 email accounts on different email servers so it has some work to do. 

Skip

**Comment by phw198** [comment]
I'd need to see your `OGcalsync.log` file from startup of OGCS through to Outlook crash and restart etc. Also, if Outlook is fully crashing, can you check your Windows Event Viewer > Application logs to see if there's anything relevant in there?

**Comment by SkipHill** [comment]
Paul, 

Thanks for the follow up. It’s better but still sometimes crashes. If I exit OGCS instead of leaving it running, Outlook does not crash. Again, I’m not getting on your case. Running the software 2-3 times a day gets the job done and is a great tool for me. 

I will get that log file and examine the event viewer, but it will be after the holiday. 

Hope you have a good one. 

Skip

**Comment by phw198** [comment]
Given you've said you have 7 accounts configured on Outlook, it's possible that's causing some kind of problem. How about [starting OGCS after you start Outlook](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#start-ogcs-after-outlook)?

**Comment by SkipHill** [comment]
I’ll try that, but I have it starting automatically after 300 seconds. I boot my system and make coffee in the morning, so it’s nearly always longer than 300 seconds before I start outlook. I suppose I could configure outlook to start automatically, but I generally avoid auto startups.

**Comment by phw198** [comment]
I'm not sure what your point about a 300 second delay is. The link provides code to start OGCS whenever Outlook is started - nothing to do with system start-up or delays.

This should work around any problem you're experiencing due to OGCS starting/syncing before Outlookb is open.
