### ISSUE TITLE
Syncing Issue on Alpha 2.8.3.0

### ISSUE THREAD

**Issue by CaHansom** [phw198/OutlookGoogleCalendarSync#928]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.3.0 
**Installed or Portable**: Installed

**Problem Description**  
\Since updating to the newest Alpha, the syncing has changed and is trying to delete items on Google calendar because it is not in the existing machines outlook calendar, but the existing machine did not delete the calendar entry.  I use Google as the master between 4 other Outlook machines.  In the past, it synced and merged the new data and if the existing machine deleted an event, then it was deleted on Google.  Then when the other machines come online, it deleted the event in Outlook.  Now it does Outlook to Google first and wants to delete the Google event before syncing it to Outlook.  I didn't see this happen in the previous version 2.8.2.0.

**Steps to Reproduce the Issue**  
1. \I create an event in Outlook, it syncs, then turn on a portable machine and when it syncs, it wants to delete the new event from Google because it isn't on the new machine yet.
1. 

**Any other information**  
\When you make a change in Outlook, then the on-demand sync should sync Outlook to Google, but when doing a normal scheduled sync, it should be Google to Outlook.

**Comment by phw198** [comment]
That sounds like pre v2.8.0 behaviour. Have you tried downgrading to v2.8.2 to see if the issue disappears? If it does, I'd be surprised as I don't think anything changed in this area between that and v2.8.3. 

Has anything in your Outlook configuration or account changed recently?

**Comment by CaHansom** [comment]
I went to each machine and synced one way with google the master, then changed back to two way sync and that has stopped the deletions.

Thanks,
Carl,
