### ISSUE TITLE
Cannot start OGCS - 4002 error won't go away after Quick Repair

### ISSUE THREAD

**Issue by jpmacl** [phw198/OutlookGoogleCalendarSync#929]
**OGCS Version**: v.2.8.0  
**Installed or Portable**: Installed

**Problem Description**  
OGCS used to start and run, but it stopped. Now, I always get the error message 0x80004002 - and get taken to the wiki page. Running Quick Repair option (from Control Panel > Uninstall > Change) does not work. Neither does the Online Repair function.

**Steps to Reproduce the Issue**  
1. Run the app - won't start

**Any other information**  
- I am running MS Office 365 Business
- This version of OGCS and this version of Office was working fine for a few weeks (new PC) ... 
- ... but, I run CCleaner (https://www.ccleaner.com/ccleaner) every once in a while, and that has a function / process to "clean up issues in the Registry". After a few weeks - and I had run CCleaner more than once, with no ill effect - this error started happening, and I cannot resolve.

I kinda suspect that CCleaner munged something in the registry that OGCS is relying on, but the Quick Repair and Online Repair don't fix it.

I do appreciate any help you can offer - I have been using OGCS for some time and I really like it, works great, nice piece of work!

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4004107/OGcalsync.log)

**Comment by phw198** [comment]
You'll need to upgrade to the latest alpha which will report a more accurate error code. But yes, likely to be some kind of registry fix required...

**Comment by jpmacl** [comment]
Problem solved ...
- Installed latest alpha
- problem reoccured ... and led me to more detailed wiki item with detailed instructions
- Made all registry repairs
- App works normally again

Excellent step by step instructions, by the way. One minor observation - under Registry Fixes -> Fix the Interface, it says to navigate to the keys that exist. For me, only one of the three existed, and it seemed like that might be bad. It might be a good idea to say that missing keys here are ok, only one of these is expected, something like that.

Thank you very much for your help!!
