### ISSUE TITLE
Build Setup

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#93]
Can you outline the changed to the build setup for 2.4?  
  
I'm trying to merge the latest in, but am not sure how to best include
Squirrel and ClickOnceToSquirrelMigrator within Visual Studio to get it to
build.  
  
I tried just pulling down your latest check in, but still get a bunch of
errors.  
  
Thanks.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 516](http://outlookgooglecalendarsync.codeplex.com/workitem/516)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Thu at 9:24 PM
**Reported by:**	brozono
**Updated on:**	Thu at 9:25 PM
**Updated by:**	brozono

**Comment by phw198** [comment]
Looks like I completely failed to commit all the Squirrel DLLs! I've now added them to the [CodePlex repository](https://outlookgooglecalendarsync.codeplex.com/SourceControl/changeset/e4828a862933a33617fc7a02018c56bfacb90042) - if you could confirm you can successfully build with that, I'll make the same commit to GitHub...

**Comment by brozono** [comment]
That resolved MOST of the issues. I am down to one build error.

"'Could not find Update.exe"

**Comment by brozono** [comment]
Looking into csproj file I'm pretty sure that comes from this portion

    <Content Include="Update.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>

Perhaps another prebuilt file that needs to be included?

**Comment by phw198** [comment]
I've now [added Update.exe to CodePlex](https://outlookgooglecalendarsync.codeplex.com/SourceControl/changeset/c977984b7be574854efa6f633ae6b6a8f98ddb51) too.

FYI, this file is a bit of a cludge to support migration from ClickOnce to Squirrel in the next release. A native Squirrel install would deploy Update.exe itself, but because everyone will be coming from ClickOnce it needs deploying in the final ClickOnce release. For a one-off build that you are probably after, you could just remove the reference to it you quoted in the `.csproj` file.

**Comment by phw198** [comment]
Missing files have now been included in v2.5.0 on the GitHub repository as well.
