### ISSUE TITLE
Error when inviting from Google Calendar

### ISSUE THREAD

**Issue by famco75** [phw198/OutlookGoogleCalendarSync#930]
Hello Paul,
I notice when I invite someone using my Google calendar (on phone) through my "work calendar", the invite does not go through. It appears it is getting routed incorrectly. I am not sure if this makes sense... Here is an image from Google: 
[Google Error Message.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/4007055/Google.Error.Message.pdf)

Perhaps when inviting someone, I should go straight to the Outlook calendar? I am asking just in case there is a setting, etc that I need to change. 

I am using version 2.8.3.0. 

Thanks,
Franco

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
I'm not sure you've explained the issue quite right. It looks like you have synced attendees from an Outlook meeting, then changed the meeting in Google one your phone. This will spam all attendees whether you ask Google to or specifically ask it to _not_. 

For this reason OGCS "cloaks" attendees emails to prevent spam. If you _want_ this, then uncheck the cloaking option and force a full sync by pressing `Shift`and clicking `Sync`. Now Google can happily email your attendees. 

FWIW I don't particularly recommend this - better to make edits in Outlook and sync then to Google.
