### ISSUE TITLE
Pop-up notification in android is not showing

### ISSUE THREAD

**Issue by salvagalimany** [phw198/OutlookGoogleCalendarSync#931]
**OGCS Version**: v2.8.3.0  
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I have already been using OGCS for almost 2 years and it has always worked amazing. However, since a little time ago, notifications in android when syncing from outlook are not popping- up anymore. The event itself appears in the google calendar, but the notification is not showing up. I have the reminders box checked in the sync options tab. I have not updated or changed anything in my phone, so i do not think it's a configuration issue in it.
The other way syncing works perfectly as always, and pop-ups in outlook are showing up.

**Steps to Reproduce the Issue**  
1. Create an event in outlook.
2. Sync
3. Wait until the time of the event and the notification is not shown in google calendar, despite the event is there.

Thank you very much!

**Comment by phw198** [comment]
Don't believe there's been any changes around this in the last release. Could you upload your `OGcalsync.log` file after you have started OGCS.

**Comment by salvagalimany** [comment]
I think i just realised what the problem is! When you create an event in outlook with the reminder in "0 minutes", it shows a pop-up only at the time of the event. When transferring this event to gmail, it appears in the G calendar as there is no reminder, even the one at the time of the event.
Probably it has been acting like this since the begginning, but i may not hace noticed it because on important events i am used to set a different reminder than 0 minutes.

**Comment by phw198** [comment]
Nope, I don't get this at all - set a 0 minute reminder in Outlook, it syncs to Google fine. Have you checked what is actually in calendar.google.com and not just your Android? If it's in the web view but not your mobile app, then it's not a problem with OGCS.
