### ISSUE TITLE
Deleted event not working 

### ISSUE THREAD

**Issue by billjaq65** [phw198/OutlookGoogleCalendarSync#933]
See the image below to see my sync settings, focusing on the Push Outlook changes check box. This works fine when I create a new Outlook event but does not delete the event in Google after I delete it in Outlook after  the Push sync executes. If I run a manual sync the Outlook event is deleted.
(https://github.com/phw198/OutlookGoogleCalendarSync/files/4021233/OGcalsync.log)
![image](https://user-images.githubusercontent.com/54357935/71754677-cffbcf80-2e4c-11ea-9434-eca95813e4b2.png)

**OGCS Version**: v2.8.0  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
I can't reproduce this on v2.8.3. 

In order to receive support, you need to:
1. Upgrade to the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Increase logging level to `FINE`
1. Reproduce the issue
1. Provide your `OGcalsync.log` file
