### ISSUE TITLE
Update from  Portable_OGCS_v2.8.2 to Portable_OGCS_v2.8.3

### ISSUE THREAD

**Issue by tfriedrich85** [phw198/OutlookGoogleCalendarSync#934]
-->

**OGCS Version**: Portable_OGCS_v2.8.2
**Edition**:  Portable  
**Sync Direction**:  O->G 

**Bug Description**  
I used the Portable_OGCS_v2.8.2 and I donate to get rid of the first screen. Now I want to update to 
Portable_OGCS_v2.8.3.

How can I use the old settings and features?

Thanks.

**Comment by phw198** [comment]
I've added a [wiki page for upgrading](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) - let me know if there's anything missing.

**Comment by tfriedrich85** [comment]
Hey, 
I tried to follow your instructions, but I accidentally overwrote my settings.xml by coping the new folder in the existing. I guess I have to configure everything again. That’s why I am thinking about changing to the installed version. Can you give me the advantages from the donation manually?

**Comment by phw198** [comment]
`settings.xml` aren't automatically backed up anyway, so yes, you'd need to reconfigure things again.

The donation features will follow your instance of OGCS as long as you are syncing to the same  Google account as when you donated.
