### ISSUE TITLE
Google calendar not update after confirmation in Outlook

### ISSUE THREAD

**Issue by remcovaal** [phw198/OutlookGoogleCalendarSync#935]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: 

**Problem Description**  
\I did a full sync Google to Outlook, Then I turn bi-directional sync on and re-sync. Then I confirmed an invite in OUtlook and resync. Unfortunately, the confirmed meeting isn't visible in Google Calendar.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4026033/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
That's some pretty sketchy information to troubleshoot with, and you've not upgraded to the latest alpha before reporting problems, as per the instructions.

Nevertheless,
- what is the date/time and subject of the confirmed meeting which hasn't synced?
- does it fall within the date range you are syncing?
- if you turn on the "Create CSV files" option in `Settings` > `Application Behaviour`, run a sync and then view `outlook_appointments.csv`, is the meeting listed in there?

Just in case it's a Teams invite, there is issue #920.
