### ISSUE TITLE
Outlook Archive

### ISSUE THREAD

**Issue by kdconod** [phw198/OutlookGoogleCalendarSync#936]
Version 2.8.0.0

Hi new user here - so glad to have found this app. I have been using for a couple of months and right now I'm having a bit of trouble where my Outlook (an older version Office Pro Plus 2010 under Win7 Pro) needs to archive older messages otherwise the mailbox gets full. Problem is when Outlook archives these items, OGCS think's they've been deleted and keeps asking to remove them from my Google Calendar, which gets annoying after a while. I'd rather keep those item, so I'm wondering if there's anyway to get OGCS to distinguish between deleted and archived messages?

**Comment by phw198** [comment]
Well they have been ~~deleted~~ moved :slightly_smiling_face: 

When they are archived, they are moved to a different calendar, which OGCS is not syncing. You could [configure multiple calendars](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars) to be synced and point it at the "Alternate Mailbox" for your Archive PST, or you could exclude your calendar folder from autoarchive - archiving emails is probably sensible, archiving meetings/appointments not so much.

View your mailbox in "Folder" view, then right-click the Calendar folder and Properties, AutoArchive, select "Do not archive items in this folder".

![image](https://user-images.githubusercontent.com/11843015/71931763-6bb37580-3196-11ea-800f-8d31b75ae028.png)

**Comment by kdconod** [comment]
Ah - that is an excellent point! I'll will turn off the AutoArchiving on my calendar!

Thank you!
