### ISSUE TITLE
Outlook email addresses do not appear

### ISSUE THREAD

**Issue by paddycy** [phw198/OutlookGoogleCalendarSync#938]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\I added another account to my outlook, and then the account I had synched through outlook dissapeared. In the meantime I downloaded and installed the alpha version ( I had beta before), but I did not manage to find the address I would like to sync there anymore.

**Steps to Reproduce the Issue**  
1. \Added new email account in outlook.
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Not really following what you're trying to report here.

> then the account I had synched through outlook dissapeared.

Disappeared from where?

Normally your primary email account as configured in Outlook would be the "Default mailbox" in OGCS, any other Outlook accounts would be under "Alternative mailbox".

**Comment by paddycy** [comment]
Hi Paul thank you for getting back to me.

Sorry for the confusion, my mistake was that i was looking to find the
default account's name somewhere. Not understanding that default account
setting is all i had to click, without even seeing the name of the account
there.

Problem solved. Thank you for your time.

**Comment by braulee** [comment]
Hi
I take this thread to ask.
I have outlook 2016 with an IMAP account and another POP3.
When putting OGCS, it only detects the files of the POP3 account and others that I use as a backup and archive.
Do you know what I am doing wrong?
Greetings and congratulations for your work

**Comment by phw198** [comment]
@braulee Are you expecting to find a calendar in your IMAP account? Because IMAP doesn't support calendars, so OGCS wouldn't be able to do anything with that account.
