### ISSUE TITLE
Beta Version syncing every 5 minutes

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#94]
Just updated to the new beta version - syncing is happening every 5
minutes........help  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 517](http://outlookgooglecalendarsync.codeplex.com/workitem/517)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Fri at 12:53 PM
**Reported by:**	michgal2k
**Updated on:**	Fri at 1:01 PM
**Updated by:**	michgal2k

#### Plaintext Attachments

[CodePlex Issue #517 Plain Text Attachments](https://gist.github.com/f1cfbf2cee0a6d9c36b941d1bc9f58ac)

**Comment by phw198** [comment]
On *2017-05-12 20:01:07 UTC*, **michgal2k** commented:

here is the logfile

**Comment by phw198** [comment]
Please confirm if this issue remains after upgrading to v2.4.0

**Comment by michgal2k** [comment]
I opened OGCSand updated to 2.4.  Now when I open 2.4 - it won't run:(  I get a popup that says it has stopped working.  Please advise

**Comment by phw198** [comment]
What's the exact error message? Could you upload your OGcalsync.log file too.

**Comment by michgal2k** [comment]
No I cannot since the app doesn't actually open.  When I click on it - it automatically stops
[Window Title]
OutlookGoogleCalendarSync

[Main Instruction]
OutlookGoogleCalendarSync has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

[Close program]

**Comment by phw198** [comment]
In Windows Explorer, go to "%APPDATA%\Outlook Google Calendar Sync" - you should find the logfile in there.

Also, isn't there a button for more details on the error message you're getting? 

Are you using 64-bit Outlook?

**Comment by michgal2k** [comment]
The system is not accepting the *.txt logfile.  I am using Outlook 2013 32 bit - no button for more details I posted everything it shows.  Should i remove & reinstall

**Comment by phw198** [comment]
I think you may have been hitting Issue #204, which started over the weekend and may now be resolved.

**Comment by michgal2k** [comment]
Since I couldn't get 2.4 to work, I reverted back to 2.3 and it seems to be fine.  Not sure if I should try 2.4 beta or wait for alpha release.
