### ISSUE TITLE
Webex meeting events generated on Google Calendar are garbled when synced

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#940]
[Outlook event saved as txt SmartNIC ecosystem collateral and market expansion.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4043484/Outlook.event.saved.as.txt.SmartNIC.ecosystem.collateral.and.market.expansion.txt)
[Text version of Webex meeting invite web page on Google Calendar.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4043485/Text.version.of.Webex.meeting.invite.web.page.on.Google.Calendar.txt)
[Outlook event body saved as txt.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4043486/Outlook.event.body.saved.as.txt.txt)

**OGCS Version**: v2.8.3.0
**Edition**: Installed 
**Sync Direction**: G->O

**Bug Description**  

**Steps to Reproduce the Issue**  
Create a Webex meeting in Google calendar.
Sync it one-way to Outlook.

The Outlook version of the event has most or all of the right content, but the formatting is unreadable.
Attached are 3 versions of an example event:
1. The outlook event body saved as txt.
The Outlook event saves as txt.
The Text version of the web page source from viewing the Google Calendar entry.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4043511/OGcalsync.log)

[Outlook event body saved as txt.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4043494/Outlook.event.body.saved.as.txt.txt)
[Outlook event saved as txt SmartNIC ecosystem collateral and market expansion.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4043496/Outlook.event.saved.as.txt.SmartNIC.ecosystem.collateral.and.market.expansion.txt)
[Text version of Webex meeting invite web page on Google Calendar.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4043499/Text.version.of.Webex.meeting.invite.web.page.on.Google.Calendar.txt)

:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Unfortunately, there's nothing that can be done about this - it's a short coming of the both the Outlook API and the actual application itself. Even if Outlook surfaced the `HTMLBody` attribute for meeting invites (which it doesn't, only the plain text `Body`), the HTML engine it uses is the completely useless one from Word (not IE).

I've read about some people trying to program in the use of Word to generate the HTML that is compatible with Outlook and then use MAPI to populate the `HTMLBody` attribute - but even if I wanted to do this, it'd be completely incompatible with 2-way sync.

**Comment by dutch55** [comment]
Paul,  Thanks for responding. This probably does not help but just to be clear:
If I accept a WebEx invite generated by Google Cloud Platform mail it looks correct.
If I accept  WebEx invite generated in an Outlook client for a Google Cloud Platform it looks correct.
If I have merge entries on, a calendar entry that looked correct before the sync will be overwritten and garbled in the process.

**Comment by phw198** [comment]
Again, more questions than answers.

What has accepting the invite got to do with anything? And where are you accepting it? In Outlook or Google.

Assuming acceptance is in Google (as that's your source calendar), are you saying that how it displays in Outlook depends on whether it has been accepted or not?! That strikes me as very bizarre.

And what significance does "merge" have in this scenario? If OGCS has synced an item and then the source is updated, OGCS will update the destination again. That's expected and the whole point of a sync. All merge does it to _not_ delete anything in the destination which OGCS did not sync there (well, strictly it will "reclaim" items it did not sync if they have the same date,time,subject,location).

I'd also assume you don't keep changing the merge option in OGCS, so it has no bearing on whether the body displays correctly in Outlook.

You need to identify the exact process by which to reproduce the issue you are seeing, eg:

1. Receive meeting invite to Google.
1. Sync to Outlook - displays correctly
1. Accept invite in Google
1. Sync to Outlook - displays garbled

**Comment by dutch55** [comment]
I almost never accept meeting invites in Google Mail. Almost always in Outlook.

1. I receive and accept a WebEx meeting invite in Outlook (my corpmail account, synced with IMAP), it adds it to the Exchange calendar. It displays correctly.

2. OGCS one-way sync from Google, with merge on, it garbles the body if the meeting invite was generated by the Google Mail Webex plugin.

3. Here is why I have merge entries off.  If I have merge entries selected, then OGCS overwrites the body of the meeting invite, rendering it painful to use (no longer can I just click on a link). The lesser of evils has been to let OGCS create one duplicate entry. I can deal with one duplicate.

I also have mail clients (two different ones) on an Android phone, and their behavior handling meeting invites isn't completely reliable, which is why, after an absence, i started using OGCS.

**Comment by phw198** [comment]
Right OK, that makes a lot more sense now. Accepting meeting invites sent to Gmail, but responded to in Outlook via IMAP is certainly not the expected configuration and I am not surprised by what you see happening.

When accepting the Gmail invite in Outlook, I assume the body looks OK in Outlook because Outlook is "natively" setting the body - which is more effective than what is available via the programming interface. I also assume (though it would be good if you could confirm), that the accepted invite then also displays OK within Google webview of the calendar. But because you are updating Gmail via IMAP, the modified date for Google is _after_ that of the entry in Outlook calendar, so then OGCS syncs the newer version from Google and messes up the body.

There are 2 work arounds I can see:
1. Turn off syncing of "Description" in OGCS - if you always accept invites in Outlook, then do you need to sync this attribute from Google?
1. Before OGCS syncs, pseudo-edit the Outlook calendar entry (open it, append a space to the subject, remove it, save and close) - this will stop OGCS syncing the item from Google (at least until the Google event is modified with a newer datetime than Outlook).
