### ISSUE TITLE
OutlookGoogleCalendarSync Creates Duplicate Entries in Outlook

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#941]
**OGCS Version**: v2.8.3.0
**Edition**: Installed
**Sync Direction**: G->O 

**Bug Description**  
There is a Google Calendar entry for a Webex meeting invite. I believe the meeting creator used the Outlook Webex plugin in their Outlook client to create the meeting invite. The meeting is a recurring meeting, which occurs every two weeks. Note this may be related to a bug submitted a few days ago where OGCS fails to properly sync Webex meeting content when the meeting was created using Gmail, not Outlook.  In this case the content with the meeting details is not garbled, but OGCS is creating duplicate entries in Outlook. It appears a duplicate is created every time OGCS syncs.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
I am attaching a .XIP with  .mht version of one of the duplicates created by OGCS (I can tell it is a duplicate, because OGCS assigns it to a category). and a .mht version of the original.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4051387/OGcalsync.log)

[Duplicate Webex Meeting Sync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4051386/Duplicate.Webex.Meeting.Sync.zip)

, along with a .mht version of the original.
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
So it creates a `4/24/2019 09:00 (R) => "Developer Community Support  Bi-weekly"` every time it syncs - are you manually deleting this each time after sync? Because each sync only picks up the same number of Outlook items at the start - 108.

Also, the item it creates shows:
```
2020-01-12 10:29:42,103 WARN  17 OutlookGoogleCalendarSync.OutlookOgcs.Categories [0] -  Failed to find Outlook category olCategoryColorDarkRed with name 'Dark Red'
2020-01-12 10:29:42,103 DEBUG  17 OutlookGoogleCalendarSync.OutlookOgcs.Categories [0] -  Using category with name "OGCS Dark Red" instead.
```
So it's not creating it with the "OGCS Blue" category as you stated.

Also, the item already in Outlook, what created that? If OGCS, why does it not have a category?

OGCS wants to delete items but it seems you have "deletions disabled"? This is likely to cause problems as the "duplicate" is likely the valid entry, and the "original" likely should be deleted.

Try manually deleting both/all events for "Developer Community Support  Bi-weekly" and letting OGCS create the one it wants to...

**Comment by dutch55** [comment]
Let me take a step back, and describe my normal operation:
I have two computers, a desktop and a notebook, each has Outlook configured the same way with one Exchange account, and multiple IMAP accounts. Currently i have one Google corpmail account.  The recurring meeting that i reported causing duplicate entries in Outlook is labeled Developer Bi-weekly. It  created by a corpmail user with the Webex plugin for the Web Google client. Without OGCS configured to sync, I can accept calendar invites in the corpmail and other accounts, and Outlook adds a calendar entry in my Exchange calendar. It looks correct in my Outlook.  When it syncs, OGCS garbles the Webex meeting content (reported in another report), and with successive syncs, it creates duplicate entries.  I have experimented with OGCS installed on both machines although currently it is only configured on the desktop,  At various times, have configured OGCS to assign to different categories on each machine, so i can see which is changing the body content in Outlook. I currently do not have merge entries set in OGCS, because it garbles Webex details, and If i have deletions allowed, then OGCS will delete entries from other accounts than corpmail that are in Outlook but not on the Google corpmail calendar,   Attached is a screen snip of the Outlook Exchange account calendar, where you can see from the date in the column on the right that they were created every 15 minutes when OGCS is configured to sync.
![Dev meeting duplicates list](https://user-images.githubusercontent.com/3947471/72391764-f8a08680-36e2-11ea-850c-1618d50bc3d3.JPG)

**Comment by phw198** [comment]
Taking a further step back, I'm not really clear the requirement for syncing Google calendar to Outlook at all. If you manage your Gmail account through Outlook via IMAP, and accept meeting invites within Outlook, then that in itself will put your Google calendar items in Outlook calendar without syncing at all?

Do you have _other_ items in Google calendar that are not created by meeting invites and you want them to display in Outlook also? If so,
a) Do you need to sync the description of those entries? If not, turn off syncing of description by OGCS.
b) Can you create them in a different Google calendar and then have OGCS sync that to another dedicate Outlook calendar? Ie segregate the meeting invites entries from everything else.

If neither of the above are possible, I can't really see a solution. I think you need to turn off "Disable deletions" to prevent the duplicates increasing, and you need "Merge" turned on so it doesn't delete items from other corporate accounts....but if you _must_ sync description then your webex invites will get garbled :slightly_frowning_face:
