### ISSUE TITLE
Syncs remove/delete email address of invited people

### ISSUE THREAD

**Issue by jlrose13** [phw198/OutlookGoogleCalendarSync#942]
v 2.8.1.0
install

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4053781/OGcalsync.log)

ed
windows 7

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4053787/OGcalsync.log)

**Problem Description**  
I think OGCS is removing or not updating the email addresses of invited people on events.  Not sure when.  Have attached a couple log files.

**Steps to Reproduce the Issue**  
I add the invited, and have also re-added when its removed.  
tried new and existing events

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
You appear to have uploaded the same log file twice, neither of which show anything useful.

Please provide a logfile that includes 
- when you have started OGCS (so it shows your configuration settings) and 
- an example of the alleged removal of attendee email addresses

Also, you are not on the latest alpha release, so no further support can be provided until then.
