### ISSUE TITLE
Crash after switching default data file in Outlook

### ISSUE THREAD

**Issue by x3n0n10** [phw198/OutlookGoogleCalendarSync#944]
**OGCS Version**: v2.8.3-alpha  
**Installed or Portable**: Installed
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4064530/OGcalsync.log)

**Problem Description**  
OGCS crashes after switching default data file in Outlook. First a message box appears saying default calendar has been selected and auto sync has been temporarily disabled. Immediately after that, another message box appears with 'Window handle already exists' (see screenshot).
<img width="257" alt="Annotation 2020-01-15 115216" src="https://user-images.githubusercontent.com/20641331/72428227-889b0a80-378d-11ea-94af-e86c0b4c5d70.png">

**Steps to Reproduce the Issue**  
1. Exit Outlook
2. Exit OGCS
3. Wait for Outlook icon to disappear from tray
4. Open Mail settings in Control Panel
5. Click 'Data files', select a non-default data file and click button 'Set as Default'. Confirm message box.
6. Close Mail settings
7. Start OGCS
8. Problem occurs

**Any other information**  
To reproduce it's best to have another valid data file (second mailbox) ready first.

**Comment by phw198** [comment]
Hi @x3n0n10 

You've turned off logging :slightly_smiling_face: Please could you set logging to at least `DEBUG` (you maybe need to edit `LoggingLevel` directly in `settings.xml`), reproduce the issue and then upload your logfile again?

**Comment by x3n0n10** [comment]
Terribly sorry, here you go!

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4113462/OGcalsync.log)

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.8.3.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4113595/v2.8.3.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by x3n0n10** [comment]
That did the trick, thank you!
