### ISSUE TITLE
Error starting multiple instances

### ISSUE THREAD

**Issue by jorgenbosman** [phw198/OutlookGoogleCalendarSync#945]
**OGCS Version**: v2.8.3-alpha
**Installed or Portable**: Installed

**Problem Description**  
I have configured 3 instances of ogcs to start at login time (in the registry Run settings) and since I upgraded to the latest alpha version, I sometimes get an error from 2 instances:
Application unexpectedly terminated!
The process cannot access the file 'c:\Users\<user>\AppData\Local\OutlookGoogleCalendarSync\app-2.8.3-alpha\ErrorReporting.json' because it is being used by another process
The application stops after this

**Steps to Reproduce the Issue**  
start multiple instances of OGCS at the same time

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.8.3.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4112995/v2.8.3.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by jorgenbosman** [comment]
Thanks, I'll give it a go

**Comment by jorgenbosman** [comment]
I didn't get an error message  anymore since I installed this patch. Thanks for the quick fix!
