### ISSUE TITLE
0x80040154 - REGDB_E_CLASSNOTREG - feedback

### ISSUE THREAD

**Issue by frankdpGH** [phw198/OutlookGoogleCalendarSync#947]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0  
**Installed or Portable**: Installed

**Problem Description**  
System.Runtime.InteropServices.COMException: Class not registered
after registrating with the proposed regasm , the problem remains.
There is no popup error window anymore but the app dies after starting.
Log attached.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4091019/OGcalsync.log)

**Comment by phw198** [comment]
You could try the [options in this thread](https://social.technet.microsoft.com/Forums/lync/en-US/ed866c4c-32b4-4679-8934-15ea6d58719b/error-code-0x80040154-in-outlook-2010?forum=outlook), but as my wiki says, it looks like the only definite way of fixing the corruption is by reinstalling Outlook.
