### ISSUE TITLE
OC -> GC "My calendars"

### ISSUE THREAD

**Issue by churn** [phw198/OutlookGoogleCalendarSync#948]
**Is your feature request related to a problem? Please describe.**
I use Google Calendar as my personal, and Outlook for work, I would like see all my calendar entries in Google Calendar, but also have the option to switch it off (ie not see my work calendar entries). Google Calendar has a "My calendars" and "Other calendars", which I can switch on/off as per attached screen shot.
![GCals](https://user-images.githubusercontent.com/3783033/72857409-a3cbc400-3d11-11ea-9431-d44a6ccd8c42.PNG)

**Describe the solution you'd like**
I only use OC -> GC and not the other way round. I would like the option to be able to Sync my Outlook entries into my "Work" calendar in Google Calendar

**Describe alternatives you've considered**
Under Settings/How, I can set the colour/category, but that doesn't allow me hide these entries (as far as I can tell)

**Additional context**
I used to manually export Outlook entries, and import them into GCal and choose the appropriate calendar, but of course that led me to your awesome app!

**Comment by phw198** [comment]
The ability to select the calendar you sync from or to has always been in OGCS. Just go to `Settings` > `Google` > `Retrieve calendars` and then select the Work calendar from the drop down.

**Comment by churn** [comment]
Ah exactly what I need. For some reason it only showed my email as the only calendar last time. Works now. Thanks Paul!
