### ISSUE TITLE
Duplicate entries in Outlook and Gmail

### ISSUE THREAD

**Issue by AdeLock** [phw198/OutlookGoogleCalendarSync#950]
I'm hoping this is a really simple and easy to answer question - but I didn't see it in issues already raised: Whenever a put a calendar entry into Gmail, it automatically reproduces it in outlook so that I have two entries for everything in my calendar. I don't usually invite anyone else - it is just an entry for my benefit only. I have the checkbox - 'merge with existing entries' checked. 

Is there a way to stop this from happening? I have a vague memory that when I first downloaded and starting using this synch tool a few weeks ago that it asked me if I wanted it to duplicate entries (did I imagine that?), and I may have said yes at the time, but I can't see anywhere to switch that off now.

As I only downloaded recently, I assume that I have the latest version and the answer to Issue #493 doesn't apply to me. Issue #941 seems related to WebEx appts only so not so relevant to me.

Any ideas?

Many thanks

**Comment by phw198** [comment]
You'd only have the latest version if you installed the alpha release, but #493 was raising under 2.6.0 so you'd definitely have newer than that.

I don't think OGCS ever asks if you want duplicates, so I think you imagined that :slightly_smiling_face: 

> Whenever a put a calendar entry into Gmail, it automatically reproduces it in outlook so that I have two entries for everything in my calendar.

This sounds like there is already an equivalent entry in Outlook? How did that get there if not by OGCS? Do you have deletion's disabled? Perhaps you need to allow deletions so OGCS can remove the duplicate...

**Comment by AdeLock** [comment]
Thanks for your reply. No - I have allowed deletions. But I'm beginning to
wonder if I have misunderstood how this all works.

When I am in my outlook email account and switch to calendar, I have it set
up to display both gmail and outlook calendar entries. As I am asking it to
synchronise the two calendars, it shows entries from both calendars, so it
appears duplicated. If I switch off the display of the other calendar it
only has one entry. Problem solved. I guess I just need to trust in the
synch process - whichever calendar I put an entry into originally, and just
ask it to display one of the two calendars at any one time.

I think I was expecting the calendars to merge because I had ticked 'merge
entries' so there was only one entry on display even when I had both
calendars ticked to display.

So - as long as I ask it to only display one calendar at a time, I think
the duplicate entry problem will be solved.

Does that make sense? It seems to have solved the problem anyway.

Thanks again.

Adrian

**Comment by phw198** [comment]
So if you already have your Google calendar displaying in Outlook without OGCS, I'm assuming you maybe want the Google calendar items actually synced into Outlook by OGCS so other colleagues that use Outlook can see them/your availability?

In that case, yes, just hiding the non-OGCS Google calendar in Outlook will stop it displayed "duplicates".
