### ISSUE TITLE
Upgrade to new computer results in unwanted calendar deletions

### ISSUE THREAD

**Issue by VTJeff** [phw198/OutlookGoogleCalendarSync#953]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v.2.8.3.0  
**Installed or Portable**: Installed

**Problem Description**  
Upgraded from W7 to new computer with W10. OGCS keeps asking me to OK item deletions I did not delete.  It won't take No for an answer.
Every time it syncs it asks me to delete a long list if items.   Some are in the past, some in the future.
I updated to the latest OGCS, but same behavior.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
Not much info to go on there.
What version of OGCS did you have on W7? What version did you install initially on W10? What sync direction? Deletions in which calendar? Why no logfile?

Have you followed the [wiki guidance](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync)?

**Comment by VTJeff** [comment]
Hi Paul,

Thanks very much for getting back to me.

I’m afraid  with all the problems I’ve gotten from W10, I can’t answer some of those questions.

I was hoping it was a common symptom with a simple solution.

 

I don’t recall the old version.  Maybe 2.4.2?  The new one is the latest alpha download version: 2.8.3

Initially, that same old version was running under W10; I hoped the new one would solve the problem.

 

Always synced in both directions.  It always worked without issues.  Only use one calendar. 

I’ve always been used to confirming calendar deletions – a good thing, when I wanted to delete them.

But these two recurring batches of 6 to 12 items (both past and future) which keep asking for confirmation are ones I never deleted, and really don’t want to.

 

There are many logfiles – including those that show me trying not to confirm the deletions.  I don’t know what to do with them. I don’t want to send my calendar info to everyone...

I guess I need to read the Wiki?

 

Is this the Wiki guidance you meant?

Fixing a Stubborn Unwanted Deletion with Full Sync

If you encounter a calendar item that is always flagged for deletion but shouldn't be, it may be possible to resolve this by forcing a full synchronisation.

The following example is for a problematic Google item:

1.     If you have two-way sync configuration, once you're sure Google has no further changes that need syncing to Outlook, set OGCS to one-way sync: Outlook to Google.

2.     Force a full sync by pressing and holding the Shift key while clicking the Sync button

3.     Set OGCS back to two-way sync, if necessary

4.     Perform a normal (differential) sync by just clicking Sync and confirm if the problem has been resolved

Thanks again.

This tool has been very useful – actually essential.  If it works again, I’ll happily contribute to the effort, although I never want to hide the splash screen – I like seeing that it’s running! 

 

 

  _____  

Dean Corren

92 Brookes Ave.

Burlington, VT  05401

802-864-9916

**Comment by phw198** [comment]
Yes, that was the wiki guidance I linked to. Given you were on such an old version of OGCS, that didn't support syncing multiple different Outlook calendars to the same Google calendar. Although you might think that's not what you did, I believe that the new Win10 Outlook calendar would have had a new ID and therefore treated as a different calendar, which will cause weird behaviour.

Have you tried the steps in the wiki. I think forcing full one-way syncs should help resolve issues...

**Comment by VTJeff** [comment]
Thank you Paul. I'm very grateful for the help.
Yes, I updated and then did that procedure with the full one-way sync.
Unfortunately it didn't work, so I had to disable deletions. I will try it
again though. It's not the only thing W10 has messed up.

- Dean (mobile)

**Comment by phw198** [comment]
Let me know if there's any progress or something I can help with...
