### ISSUE TITLE
Syncing Multiple Gmail calendars in one account 

### ISSUE THREAD

**Issue by octoberfalling** [phw198/OutlookGoogleCalendarSync#956]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\In settings, Google, I can only choose one calendar.  Is it possible to select more than one?

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>
![image](https://user-images.githubusercontent.com/60712359/73874375-68f18200-4821-11ea-9380-44e1154cb442.png)

**Comment by phw198** [comment]
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars
