### ISSUE TITLE
Sync Error with Alpha 2.8.3.0 -- Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by timotei82** [phw198/OutlookGoogleCalendarSync#958]
**OGCS Version**: v2.8.3.0
**Edition**: Portable  
**Sync Direction**: O->G

Failed to sync with new or existing O->G calc.

![image](https://user-images.githubusercontent.com/17809366/74326209-4b289d80-4d8a-11ea-8b90-85069e7b8a40.png)

![image](https://user-images.githubusercontent.com/17809366/74326519-d0ac4d80-4d8a-11ea-9cc5-cc0e7003fc1f.png)

Error already exits after ExtirpateOgcsMetadata = true

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4191328/OGcalsync.log)

**Comment by phw198** [comment]
:package: Please could you apply [hotfix v2.8.3.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4208584/v2.8.3.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)), try another sync and let me know if there's any difference in the sync or error message?

Thanks!

**Comment by timotei82** [comment]
Hi, currently the error is gone... 

If the sync works in the next days, you can close the issue.
Thx

**Comment by timotei82** [comment]
Hello,

issue still exits with your patch, too.

Attached you find the log.

Greetings.. Timo
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4217633/OGcalsync.log)

**Comment by phw198** [comment]
Thanks @timotei82 - that was the same error, different problem this time!

:package: The cause of the error should now be properly reported with [v2.8.3.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4241473/v2.8.3.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) - would appreciate it if you could confirm that does now happen.

However, in your case, it looks like your corporate IT is now blocking access to Google:
```
Die eigenmächtige Installation von Software ist verboten. Daher wird vom Webfilter auch der Download von ausführbaren Dateien/ Software unterbunden. 
Falls Sie Software für geschäftliche Zwecke benötigen, bestellen Sie diese auf der Seite IT-Corner / IT-Arbeitsplatz. Über diesen ordentlichen Prozess werden die Beschaffung und die Installation, das Lizenzmanagement, der IT-Betrieb sowie der Support geregelt.

URL: https://www.googleapis.com/calendar/v3/calendars/5e01vkrtdor2ld7mdlpa32k7ng@group.calendar.google.com/events/1q6td54dci4ft4h3ssaq99d954
Filename: 1q6td54dci4ft4h3ssaq99d954
Media Type (detected): application/x-gzip
Media Type (from file name):
```

Translation being:
> The unauthorized installation of software is prohibited. The web filter therefore also prevents the download of executable files / software.
If you need software for business purposes, order it on the IT Corner / IT Workplace page. Procurement and installation, license management, IT operations and support are regulated via this orderly process.

FWIW, I think their rules are misconfigured and it shouldn't be blocking the above URL.

**Comment by phw198** [comment]
@timotei82 Have you been able to confirm if v2.8.3.6 reports the issue more accurately?

**Comment by phw198** [comment]
:shipit: Rolling changes into next release anyway.
