### ISSUE TITLE
v2.8.3.0 deletes Google calendar entry created by google voice command on Android phone

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#959]
[outlook_create.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4210031/outlook_create.zip)

v2.8.3.0 deletes Google calendar entry created by google voice command on Android phone.

1) create new calendar entry on Google calendar using Google voice commands on Android phone.
2) entry is confirmed created on Google calendar
3) either wait for scheduled sync cycle, or force a sync on demand / manual
4) app shows number of outlook entries (for example 90, then show number of google calendar entries (in this example 91)
5) correct processing would have the new Google calendar entry added to Outlook during the sync process.
6) but the opposite happens, the google calendar entry created by google voice is deleted from the google calendar, and placed in google calendar trash
7) problem can be recreated at will
8) ultra fine log attached, csv files attached in zip file

[OGcalsync.log.1 (2).log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4210018/OGcalsync.log.1.2.log)

**Comment by phw198** [comment]
I can't reproduce this issue and you've not said the title of the  specific item that is being deleted in your Google calendar. Furthermore, your logs show no Google deletions at all.

**Comment by kwagner115** [comment]
Cant recreate issue.
