### ISSUE TITLE
Sync fails with No to app requesting access to Olk Contacts

### ISSUE THREAD

**Issue by hafizullahchishti** [phw198/OutlookGoogleCalendarSync#960]
Outlook2003, Windows10/64, app version 2.8.3.0
--
Sync fails when repeated requests to access Outlook contacts is denied.

1. Start app
2. Initiate manual sync or wait for scheduled sync
3. Sync pauses and request to access Outlook Contacts is raised
4. Request denied by clicking No
Request dialog is raised several times, denied each time
5. Sync fails, throwing additional dialog and errmsgs in verbose log 

Expect: 
* One denial to be enough
* Option in Settings to not scrape Outlook Contacts

 ~~I do not have my Contacts' permission for an app to access their data~~

![Screenshot 2020-02-16 20 37 16](https://user-images.githubusercontent.com/40682057/74628964-e5327200-510b-11ea-98bc-f13aa54934ad.png)
![Screenshot 2020-02-16 20 40 09](https://user-images.githubusercontent.com/40682057/74628965-e5cb0880-510b-11ea-9a7d-0a12a276cc76.png)
![Screenshot 2020-02-16 20 40 28](https://user-images.githubusercontent.com/40682057/74628967-e5cb0880-510b-11ea-8ada-af09bc6a451a.png)

**Comment by phw198** [comment]
Long been a [FAQ](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security).
