### ISSUE TITLE
Unable to sync with Google Calendar

### ISSUE THREAD

**Issue by AngelosAlevizos** [phw198/OutlookGoogleCalendarSync#968]
This is what I get:

2020-03-19 14:39:42,936 WARN  7 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
You need to have writer access to this calendar. [403]
Errors [
	Message[You need to have writer access to this calendar.] Location[ - ] Reason[requiredAccessLevel] Domain[calendar]

**Comment by phw198** [comment]
Which indicates you've ignored the advice to upgrade to the latest release of OGCS and are also trying to write to a read-only Google calendar. That's not a bug.
