### ISSUE TITLE
Sticky error message "A problem was encountered when searching for Outlook calendar folders"

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#971]
**OGCS Version**: v2.8.3.0 - Alpha  
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
Error message "**A problem was encountered when searching for Outlook calendar folders**" cannot be closed with "OK" button. Re-appears after each click on OK. Program needs to be closed using Task Manager (End Task).

**Steps to Reproduce the Issue**  
1. Start program
2. Error message pops up (in my case, not sure why, usually no error)
3. click OK button on error message popup
4. Error message re-appears, popup does not 
5. repeat steps 3. and 4. multiple times. Error popup does not go away.

**Any other information**  
Any additional information that may help troubleshoot the issue.
Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4386033/OGcalsync.log)

**Comment by phw198** [comment]
The full error message in your logs is `There is not enough free memory to run this program. Quit one or more programs, and then try again.`.

I have now made a change to surface this in the popup box, but there's not much OGCS can do about it - seems like you could do with more RAM in your machine?
