### ISSUE TITLE
The requested operation required elevation

### ISSUE THREAD

**Issue by sunnykaul5** [phw198/OutlookGoogleCalendarSync#976]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
The requested operation required elevation. I receive this message when i try to start the application.

**Steps to Reproduce the Issue**  
1. click on the application icon to run the application
1. 

**Any other information**  
\<Update here>

**Comment by sunnykaul5** [comment]
![Annotation 2020-04-14 230626](https://user-images.githubusercontent.com/56005603/79303799-a0754e00-7ea4-11ea-8c37-1d22f8d67d40.jpg)

**Comment by phw198** [comment]
Do [these instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#windows-defender-smartscreen-protected-your-pc) for unblocking your download help?
