### ISSUE TITLE
Updated Appointment failed to save. Unknown error. 

### ISSUE THREAD

**Issue by jcav1** [phw198/OutlookGoogleCalendarSync#977]
I am not a programmer so having a hard time uploading the log file.

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Impossible to diagnose without a log file.
