### ISSUE TITLE
Remove Google synced events from Outlook?

### ISSUE THREAD

**Issue by dseely** [phw198/OutlookGoogleCalendarSync#978]
**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I mistakenly did a two way sync with google and outlook and now I have my google events on my outlook calendar and they are syncing back to my google calendar creating duplicates. After some review, I decided that I really need to do a one way sync (outlook > google) and am syncing to a secondary google calendar so I can easily separate and see my google and outlook events. Trouble is, I cannot figure out how to easily get my google events off my outlook calendar, there are lots! Is there any easy fix for this, or do I need to manually go through and delete from outlook?

**Comment by phw198** [comment]
You'll probably want a [read through this](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#mass-deleting-synced-items) - should be pretty straight forward for deleting Outlook items.
