### ISSUE TITLE
Error code (0x80040155)

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#983]
Version 2.8.3.0

Just installed new pre-release version of Windows 10 as part of Insiders program:

Windows 10 RS-Prerelease Build 19619 is out to Fast

OGCS fails upon start with error code 0x80040155 - Interface not Registered

Application terminated!

A problem was encountered with your Office install.

Please see the wiki for a solution. (0x80040155)

https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered

0x80040155 - Interface not Registered

This can be a particularly nasty problem. Follow through the steps:
Register Ole32.dll
Make sure part of Microsoft Office (the Ole32.dll file that is located in the %windir%\System32 folder) is registered correctly in the Windows registry:

Click Start, and then type Command Prompt, in appeared list, right-click Command Prompt and select Run as Administrator
In Command Prompt window type the following command and press Enter
For 32 bit Windows: regsvr32.exe %windir%\System32\Ole32.dll
For 64 bit Windows: %systemroot%\SysWoW64\regsvr32.exe %windir%\SysWoW64\Ole32.dll
In the RegSvr32 dialog box, click OK.
Then follow the 3 steps through below from "Fix the Interface" to "Ensure MSOUTL.LIB is Registered" (the final step usually being the most important).

==============================================

It appears that the Windows 10 update installation today caused the App to fail the first and all subsequent attempts to run it following the update. 

I'm not smart enough to know whether Windows 10 update broke the app, or the app was designed in a way that was not compatible with the last 2 Windows updates. 

That said the app had survived numerous Windows 10 updates in the past, and has just started failing with the last 2 Windows 10 insider updates this past week. 

I was able to get OGSC to work but only after running an Office Online Repair

Control Panel\All Control Panel Items\Programs and Features\Microsoft 365

KW

**Comment by phw198** [comment]
Windows updates frequently cause problems and introduce new bugs! It's not that OGCS isn't designed to work with Windows updates, it just can't cope very well when Windows corrupts it's own registry which Office, Outlook and OGCS rely upon.

As you discovered, running an Office Repair usually fixes said registry corruption which then allows OGCS to work again.

**Comment by phandoo** [comment]
The repair is not helping. Not sure if this is related to the problem

HKEY_CLASSES_ROOT\Interface\{00063001-0000-0000-C000-000000000046}\TypeLib >> EXISTS AND ALL GOOD. 
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\WOW6432Node\Interface\{00063001-0000-0000-C000-000000000046}\TypeLib >> DOES NOT EXIT
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Classes\Interface\{00063001-0000-0000-C000-000000000046}\TypeLib >> DOES NOT EXIT

Running repair has not helped. both online and quick haven't. Any ideas?
