### ISSUE TITLE
Read-only Outlook calendar

### ISSUE THREAD

**Issue by kartik0908** [phw198/OutlookGoogleCalendarSync#984]
Hi folks
I'm getting a error that says unable to add new entries into the outlook calendar  
> You don't have permission to create an entry in this folder. Right-click the folder, and then click Properties to check your permissions for the folder. See the folder owner or your administrator to change your permissions.

Which folder do i right click to add permission?
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4576131/OGcalsync.log)

**Comment by phw198** [comment]
v2.8.1 won't let you sync to a read-only calendar, thereby preventing the error you encountered (with text from Microsoft, not OGCS).

Nevertheless, if you have edit permission rights on the calendar you selected for sync, then just replace the word "Folder" with "Calendar" and follow the original instructions.

However, from your logs, it looks like you have selected the calendar "Birthdays", which may only be allowed to be read-only.

**Comment by kartik0908** [comment]
@phw198  - Many thanks! I will update accordingly
