### ISSUE TITLE
Particular meeting will not sync to Outlook

### ISSUE THREAD

**Issue by johnmwaldron** [phw198/OutlookGoogleCalendarSync#987]
Using Version 2.8.0.0

All Google to Outlook events sync exactly as expected.
One particular recurring event does not sync, even upon the event creator updating event.

That same creator can create other recurring events that sync perfectly.  Even pre-dating the recurring meeting.

I have also tried declining and then re-accepting the meeting invite.  That does not seem to fix it either.

Any suggestions?

Attached is my log file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4588502/OGcalsync.log)

**Comment by phw198** [comment]
Firstly, you're not on the latest alpha release, but I'm not sure that matters for this case.

I see you have two-way sync on, so to be clear, you are talking specifically about a recurring event created by someone else in Google - and this isn't syncing to Outlook? Silly question, but you're sure it's in the same Google calendar that you have picked to sync?

Points of note:
* You are excluding Outlook invites 
    * you have not yet responded to
    * that have any category assigned
* You are not deleting calendar items, and OGCS _does_ want to delete 1 Google event.

**Comment by johnmwaldron** [comment]
Hi.
Yes, someone else created a recurring google calendar event.  This one will not sync to Outlook.
When the same person creates another recurring event, those events DO sync.
(I then created a duplicate with a different name, to force an event into my Outlook... this can obviously be deleted once we solve this)

They are both associated with the same google calendar.

To your other points of note:
- I think I can change those Outlook exclusions... I didnt realize that on.  Would that create this scenario?
- Is there a benefit to deleting these events?  Does this create the problem I'm seeing?

Images of duplicates:
![image](https://user-images.githubusercontent.com/64920011/81565148-e79d1480-9366-11ea-880f-f615fb02debc.png)
![image](https://user-images.githubusercontent.com/64920011/81565360-2df27380-9367-11ea-860b-f77b7cea9676.png)

**Comment by phw198** [comment]
Yes, is could well be the disabled deletions that's part of the issue. It's possible the event was synced at some point, then deleted in Outlook - so now it will never get back to Outlook and OGCS wants to delete it in Google.

You could enable deletions with prompt, and see if it wants to delete this problematic item. If it does, decline the delete and [then follow these steps](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync).
