### ISSUE TITLE
Error Message "Sign in with Google temporarily disabled for this app This app has not been verified yet by Google in order to use Google Sign In."

### ISSUE THREAD

**Issue by ghost** [phw198/OutlookGoogleCalendarSync#990]
For both the beta and alpha version, I keep receiving the following error:
"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

I am not able to produce a log file because I cannot get past this step.

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Duplicate of #915
