### ISSUE TITLE
Sync schedule frequency

### ISSUE THREAD

**Issue by ccannon88** [phw198/OutlookGoogleCalendarSync#992]
I'm using version 2.8.0.0

On sync schedule frequency, the lowest value I can enter in the 'Schedule every:' field is 120 Minutes/2 hours. Is that by design or a bug? 

I'd like to increase the frequency because I'm doing a 2-way sync with Google Calendar.

Please let me know if or how I can increase sync frequency.

Thanks.

**Comment by phw198** [comment]
By design and [documented](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-the-restriction-on-sync-schedule).

**Comment by ccannon88** [comment]
That makes perfect sense. Thanks for letting me know.
