### ISSUE TITLE
Breaks Outlook Password Memory

### ISSUE THREAD

**Issue by BJ4444** [phw198/OutlookGoogleCalendarSync#997]
I have been using the latest Alpha version for about 2 weeks.  Downloaded , removed, reinstalled and had to remove again.  After a while, OCGS will just stop Outlook from working without continually re-entering your email passwords.  Uninstall and all works well again.  This is repeatable for me.

Outlook 2019

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) covering a day that exhibits the described issue.

Also explaining the type of account Outlook is configured with and how you have set OGCS to sync (regular intervals / push sync / manual); is Outlook always running or OGCS opens it when it needs to sync.... etc?
