### ISSUE TITLE
Resource has been deleted [410]

### ISSUE THREAD

**Issue by echoblaze** [phw198/OutlookGoogleCalendarSync#998]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: 2.8.0.0
--

  
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
Getting "Deleted event failed to remove. Resource has been deleted [410=Gone]" alert every sync.

**Steps to Reproduce the Issue**  

1. Friend sends a Google Calendar invite
2. Google Calendar invite is synced to Outlook
3. User deletes Google Calendar invite (by accident)
4. The event is recreated by Outlook

Unsure if the following contributed to the problem:

- going on and off VPN at various points
- Friend removed and re-sent Google Calendar invite
- Event is now in Google Calendar, but will not sync to Outlook
- attempted to use a fresh install but did not fix the issue

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4711842/OGcalsync.log)

**Comment by phw198** [comment]
I cannot reproduce this problem on the latest alpha, but you are right it probably has something to do with the organiser deleting and recreating the event.

To get the new event to sync to Outlook, temporarily turn on one-way sync G->O.

HTH, but unless you can identify the exact steps to reproduce this issue again on the latest alpha, I'll close this issue shortly.

**Comment by phw198** [comment]
I have, however, found a bug related to reclaiming "orphans" which can occur for two-way sync where a Google event is recreated - I'm just not 100% if this is the bug you encountered as its symptoms weren't quite as you described...

**Comment by echoblaze** [comment]
Yea I imagine this issue would be almost impossible to reproduce; 
however, I followed your suggestion to do a one-way sync first, before switching back to two-way sync
and I don't get the error any more. Perfect ! Thanks again
